### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by fisart** [alexreinert/piVCCU#10]
When I change the password on my pi from raspberry to something else the system accepts the change but does not change the password. I installed the pre-prepared sd card image

**Comment by alexreinert** [comment]
Please provide more information. I just tested it with a fresh written image on a Raspberry Pi 2 and it worked without any problems.

**Comment by fisart** [comment]
Difficult to provide further information so I just attach
![passwd](https://user-images.githubusercontent.com/1668175/34106833-c56a4f46-e3c7-11e7-841e-c71c0a2c1dcd.JPG)
 a screenshot

**Comment by alexreinert** [comment]
Very easy: You used sudo, so passwd ran as root and you changed the root password. To change the password of the user pi run the passwd command without sudo.

**Comment by fisart** [comment]
Looks like I have egg in my face :(  Just tried it and your obviously right. Sry for wasting your time
