### ISSUE TITLE
New Documentation Wifi CCU3

### ISSUE THREAD

**Issue by Schattenruf** [alexreinert/piVCCU#100]
Hey there,

I wanted to install your piVCCU3 build (latest at the moment). I started with a clean raspbian and followed your installation instructions to that point where wifi starts.

Below you find my configs. Everytime I add the IF up hook I cannot reach my device anymore per ssh. wlan0 seems to start after the ethernet connection is up and both are not pingable anymore. Up to step 2 they are. I tried your prebuilt versions as well: 
  a) First installtion via eth0 no problems; webui reachable
  b) getting started with the wifi docu -> problems after I put the IF hook up, no ssh no ping, nothing

The problem is I don't have a usb keyboard anymore. Well maybe somewhere... 

So maybe you could update the docu?
I gonna try CCU2 and will post afterwards if it worked.

/etc/network/if-up.d/pivccu

> #!/bin/sh
> 
> HOST_IF=wlan0
> BRIDGE=br0
> HOST_IP=192.168.253.1
> CCU_IP=192.168.253.2
> 
> if [ "$IFACE" = "$BRIDGE" ]; then
>   echo 1 > /proc/sys/net/ipv4/ip_forward
>   iptables -A FORWARD -i $IFACE -s $HOST_IP/24 -m conntrack --ctstate NEW -j ACCEPT
>   iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
>   iptables -A POSTROUTING -t nat -j MASQUERADE
> 
>   iptables -t nat -A PREROUTING -p tcp -i $HOST_IF --dport 80 -j DNAT --to-destination $CCU_IP:80
>   iptables -t nat -A PREROUTING -p tcp -i $HOST_IF --dport 1999 -j DNAT --to-destination $CCU_IP:1999
>   iptables -t nat -A PREROUTING -p tcp -i $HOST_IF --dport 2000 -j DNAT --to-destination $CCU_IP:2000
>   iptables -t nat -A PREROUTING -p tcp -i $HOST_IF --dport 2001 -j DNAT --to-destination $CCU_IP:2001
>   iptables -t nat -A PREROUTING -p tcp -i $HOST_IF --dport 2002 -j DNAT --to-destination $CCU_IP:2002
>   iptables -t nat -A PREROUTING -p tcp -i $HOST_IF --dport 2010 -j DNAT --to-destination $CCU_IP:2010
>   iptables -t nat -A PREROUTING -p tcp -i $HOST_IF --dport 8181 -j DNAT --to-destination $CCU_IP:8181
>   iptables -t nat -A PREROUTING -p tcp -i $HOST_IF --dport 8183 -j DNAT --to-destination $CCU_IP:8183
>   iptables -t nat -A PREROUTING -p tcp -i $HOST_IF --dport 8700 -j DNAT --to-destination $CCU_IP:8700
>   iptables -t nat -A PREROUTING -p tcp -i $HOST_IF --dport 8701 -j DNAT --to-destination $CCU_IP:8701
> fi

/etc/network/interfaces

> source-directory /etc/network/interfaces.d
> 
> auto lo
> iface lo inet loopback
> 
> auto eth0
> iface eth0 inet static
>   address 192.168.1.201
>   netmask 255.255.255.0
>   gateway 192.168.1.1
>   dns-nameservers 192.168.1.1
> 
> auto wlan0
> allow-hotplug wlan0
> iface wlan0 inet static
>   address 192.168.1.202
>   netmask 255.255.255.0
>   gateway 192.168.1.1
> 
> auto br0
> iface br0 inet static
>   bridge_ports none
>   address 192.168.253.1
>   netmask 255.255.255.0
> 
 /etc/wpa_supplicant/wpa_supplicant.conf
> ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
> update_config=1
> country=DE
> ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
> update_config=1
> network={
> 	ssid="xxx"
> 	psk=a60cc150995ea2ca162c493c1dd19096d8ae81c0e57ba1e540151d6b7ee2071e
> }

/var/lib/piVCCU3/userfs/etc/config

> HOSTNAME=homematic-ccu2
> MODE=MANUAL
> CURRENT_IP=192.168.253.2
> CURRENT_NETMASK=255.255.255.0
> CURRENT_GATEWAY=192.168.253.1
> CURRENT_NAMESERVER1=8.8.4.4
> CURRENT_NAMESERVER2=8.8.8.8
> IP=192.168.253.2
> NETMASK=255.255.255.0
> GATEWAY=192.168.253.1
> NAMESERVER1=8.8.4.4
> NAMESERVER2=8.8.8.8
> CRYPT=0

**Comment by Schattenruf** [comment]
Same problem here.
Connected a screen to the pi. He says something similar like "Failed to raise network. see systemctl status network.service" in ccu2 and 3.

Sadly I don't have a keyboard to look what's in there.

**Comment by alexreinert** [comment]
The /etc/network/interfaces is not matching the one in the documentation...
But as your problem is now solved, I close this issue.
