### ISSUE TITLE
[Doc] Add option to expose lxc container to localhost only

### ISSUE THREAD

**Issue by mrueg** [alexreinert/piVCCU#101]
I don't have a lot of LXC knowledge, but can you add an option to the documentation to only expose the webinterface to localhost instead of bridging it to everyone? I assume users can forward it, if they want to access it from remote optionally.
For my usecase I need only the XML-RPC available locally.

**Comment by alexreinert** [comment]
The CCU sometime needs internet access (e.g. for teaming HmIP devices or when changing the radio module). Because of that an unbridged setup could cause some trouble.
Therefore I will not document, how to setup this. Please use the CCU firewall instead.

**Comment by mrueg** [comment]
Thanks for the quick response. Understood, but maybe there's a way to use an overlay network to achieve this? My main concern is about accidentally exposing the API or user interface to an untrusted network and ideally I would not rely on an application firewall for that.

**Comment by alexreinert** [comment]
Just do not bind the physical network interface to the bridge and use static ip adresses for the CCU and the bridge using a subnet different to the physical interface.
But as said, this can cause trouble.

**Comment by mrueg** [comment]
Thanks for the suggestion I'll give that a try. :+1:  On a side note, do you know if the CCU supports TLS?

**Comment by alexreinert** [comment]
Yes, can be activated using the WebUI: Control-Panel/Network Settings.
