### ISSUE TITLE
Support for NanoPi M4 (Rockchip RK3399)

### ISSUE THREAD

**Issue by XtraLarge** [alexreinert/piVCCU#102]
Hi,

my raspberry with iobroker anderen pivccu didn't had enough performance so I bought a NanoPi M4. This one had enough performance to run both, but pivccu didn't supoort this chipset. .... It would be great If you can change this:)

**Comment by alexreinert** [comment]
Take a look at the GPIO header: Physically not possible to attach the radio module there as the GPIO header has no 2.54mm pitch.

**Comment by XtraLarge** [comment]
Hi,



please take a look at http://wiki.friendlyarm.com/wiki/index.php/NanoPi_M4 <http://wiki.friendlyarm.com/wiki/index.php/NanoPi_M4> 



GPIO1 has a 40 pin 2.54mm layout. (same as Raspberry)



thx

Hans-Willi Werres

Brücker Mauspfad 564a

51109 Köln



Telefon +49 (221) 94642476

Fax +49 (221) 94642475

Mobile +49 (152) 53902692



-----Ursprüngliche Nachricht-----
Von: Alexander Reinert <notifications@github.com>
Gesendet: Dienstag 18 Dezember 2018 13:31
An: alexreinert/piVCCU <piVCCU@noreply.github.com>
CC: XtraLarge <eMail@WilliWerres.de>; Author <author@noreply.github.com>
Betreff: Re: [alexreinert/piVCCU] Support for NanoPi M4 (Rockchip RK3399) (#102)

Take a look at the GPIO header: Physically not possible to attach the radio module there as the GPIO header has no 2.54mm pitch.

**Comment by alexreinert** [comment]
Sorry, I mixed this up with the NanoPi Neo4.
I have no test device, but according to the pin description in the wiki, it dhould be possible. If yor are willing to support me with some tests, I can add something in abour one week.

**Comment by XtraLarge** [comment]
This would be great. Thank you!

**Comment by XtraLarge** [comment]
If you wish I can give you an access to the nanopc m4. So you can access ssh and web by your own.

**Comment by alexreinert** [comment]
Sorry, took me some time to build an image because of the holidays.
Can you please test the image https://www.pivccu.de/images/piVCCU3/dev/Armbian_5.68_Nanopim4_Debian_stretch_dev_4.19.0.zip with an attached radio module?
pivccu-info should detect the radio module and the WebUI of the CCU should respond quick.

**Comment by XtraLarge** [comment]
Hello,
I've installed the image but Ican't get an IP Adress of the PIVCCU Web Interface. Perhaps you will get a look .... I've isolated the System an opened an ssh port. The system ist bare/not configured.
I'll give you the address with a private email. Pleae send me your address at eMail@WilliWerres.de.

**Comment by alexreinert** [comment]
Released in testing apt repo

**Comment by alexreinert** [comment]
Released in stable apt repo
