### ISSUE TITLE
SSH credentials not working in Orange Pi Zero Image 2018-11-18

### ISSUE THREAD

**Issue by 2000one** [alexreinert/piVCCU#103]
Hi,

access with documented credentials
user: root
pass: 1234
does not work.

Anything I can do to access the Orange Pi?

Thanks for the great work!

**Comment by raystream** [comment]
any news on this issue?
i have installed the image to my orangepi zero but i need to get ssh working

**Comment by alexreinert** [comment]
The credentials are root/1234.
But it is possible, that the SSH host keys are not fully created by Armbian, which results in the same error.
I'm just recreating the images.

**Comment by raystream** [comment]
trying to ssh in the device results just in an direkt close of the connection.
seems ssh ist not running or declines the connection

**Comment by alexreinert** [comment]
New image is now online.
