### ISSUE TITLE
URL Down

### ISSUE THREAD

**Issue by aje89** [alexreinert/piVCCU#104]
Updates and installation not working www.pivccu.de is not reachable.

**Comment by alexreinert** [comment]
My monitoring informed me about 5 p.m. cet. But due to christmas I was not able to resolve the issue directly. Issue is now resolved.

**Comment by joachimarp** [comment]
Aktuell scheint die Website erneut offline zu sein. Hoffe es ist kein größeres Problem.

**Comment by alexreinert** [comment]
Auch hier nochmal: Ich kann keinen Ausfall feststellen. Seite ist über Telekom problemlos erreichbar, im (externen) Monitoring ist auch kein Ausfall erkennbar.

**Comment by joachimarp** [comment]
Hallo,

 

ich weiß aktuell noch nicht wo das Problem liegt, über mein Handy kann ich die Seite erreichen, über den PC nicht auch über das Tablet nicht. Tablet sagt es konnte keine sichere Verbindung hergestellt werden.

 

So, scheinbar hab ich das Problem gefunden. Habe in der FritzBox die DNS Server geändert auf die Google Server 8.8.8.8 und 8.8.4.4, weil im Browser den Fehler DNS_PROBE_FINISHED_NXDOMAIN angezeigt bekommen habe. Hab die Standard Server der Telekom raus und die rein und sihe da, alles wieder gut.

 

Mit freundlichen Grüßen

 

Joachim Arp

 

Am Wasserturm 24

90455 Nürnberg

Telefon 09129 – 1438033

Mobil 0177 – 6028521

Email joachimarp@t-online.de

 

Von: Alexander Reinert <notifications@github.com> 
Gesendet: Sonntag, 5. Mai 2019 14:08
An: alexreinert/piVCCU <piVCCU@noreply.github.com>
Cc: joachimarp <joachimarp@t-online.de>; Comment <comment@noreply.github.com>
Betreff: Re: [alexreinert/piVCCU] URL Down (#104)

 

Auch hier nochmal: Ich kann keinen Ausfall feststellen. Seite ist über Telekom problemlos erreichbar, im (externen) Monitoring ist auch kein Ausfall erkennbar.

**Comment by heikok88** [comment]
Aktuell ist die Seite wieder offline. Ist absehbar ab wann sie wieder erreichbar ist?
Ich wollte gerade meine pi's auf bullseye upgraden.

**Comment by heikok88** [comment]
Sie ist schon wieder erreichbar. Trotzdem Danke!

**Comment by alexreinert** [comment]
sie war ein paar Minuten wg. geplanter Updates down, muss auch manchmal sein. ;-)
