### ISSUE TITLE
Names of "Favorites"

### ISSUE THREAD

**Issue by Jojo-A** [alexreinert/piVCCU#105]
Hi,

I recently faced a problem regarding the displayed name of components in a "Favorites" list.

I have set individual names for all my components. These names are displayed correctly on the properties pages of each component, like the HM-CC-RT-DN series thermostate for the bathroom has the serial number OEQ123456 while its name is "bathroom".
![grafik](https://user-images.githubusercontent.com/33325587/50445551-d1c4b600-090f-11e9-9f47-3edcab4bd017.png)

Now the problem: when adding this device to a "Favorites" list, this name is not displayed. The name-field shows in this case: 
"HM-CC-RT-DN OEQ123456:4"
![grafik](https://user-images.githubusercontent.com/33325587/50445598-1ea88c80-0910-11e9-867a-b49faf6f23e0.png)

So when you've got a lot of components in your favorites list, it can become very hard to tell, which device is what by only seeing the serial number ;) .

Greetings,
Jojo

**Comment by alexreinert** [comment]
In the favorite list you do not add devices. You add channels there. So you need to rename the channels. Not really intuitive, but this is how the original CCU works.
