### ISSUE TITLE
Add additional architectures to APT repository

### ISSUE THREAD

**Issue by angelnu** [alexreinert/piVCCU#106]
I added support for the [CCU docker container](https://github.com/angelnu/docker-ccu2) based on your pivccu-modules-dkms package. Now I am working in a multiarch docker image that can be deployed on any platform such as x86. There your kernel modules for the generic UART, the eq3 loopback and your new USB adapter would be very useful.

Could you please add x86_64 and i386 archs to your [apt repository] (https://www.pivccu.de/piVCCU/dists/stable/main/)?

**Comment by alexreinert** [comment]
x64 and i386 are not supported and untested at the moment.

**Comment by angelnu** [comment]
I was able to build the modules on x64 but I was not able to sign on my current server since it requires signed kernel modules. I will test in another system with the fake device uart driver.

Is there any other test needed? Would you consider offer x64 only in testing?
