### ISSUE TITLE
LXC 3 compatibility

### ISSUE THREAD

**Issue by dontobi** [alexreinert/piVCCU#108]
I use raspbian (testing) to test some functions. The system recently uses LXC in version 3 and pivccu stops working.

**Comment by alexreinert** [comment]
Can you please provide more information:
Which image are you using exactly?
Which piVCCU version do you use?
What error messages do you get?

**Comment by dontobi** [comment]
Ich mache es mir Mal einfach und schreibe auf deutsch...

Ich nutze ein raspbian Testing (auf dem neusten Stand). Also LXC in Version 3 samt python3 usw.. Zudem nutze ich pivccu (stabil), nicht pivccu3.
Ich kann dir leider derzeit keine Liste der installierten Pakete hier Posten, weil ich dazu die SDKarte wechseln müsste und ich gerade mein produktiv System am laufen habe. Ich versuche im Laufe des Wochenende das nachzureichen.

**Comment by alexreinert** [comment]
Ok, ich habe das Problem gefunden: Mit LXC3 haben sich ein paar Sachen in der Config verändert.
Bis ich einen vollständigen Fix fertig habe, welcher sowohl auf LXC2 als auch auf LXC3 läuft, kann man sich behelfen, in dem man das Config-Template anpasst:

```sudo lxc-update-config -c /etc/piVCCU3/lxc.config```

**Comment by alexreinert** [comment]
Fix in testing released

**Comment by alexreinert** [comment]
Released in stable
