### ISSUE TITLE
Container staret nicht mit Mount.entry für USB-Stick

### ISSUE THREAD

**Issue by sjheinzweiler** [alexreinert/piVCCU#110]
Hi,
ich habe piVCCU3 in der Version 3.41.11-12 mit dem Image "Raspbian_Stretch_Lite_piVCCU3_2018-11-19.zip" der Quelle "https://www.pivccu.de/images/piVCCU3/" installiert.
Homematic startet perfekt!
Dann einen USB-Stick (8GB vfat) gemäß der Anleitung: "https://www.elektronik-kompendium.de/sites/raspberry-pi/2012181.htm" in das Verzeichnis /media/usbstick der Debainumgebung mittels /etc/fstab eingebunden.
(Das hab ich schon häufiger gemacht :-)) 
Geht!
Jetzt wollte ich gemäß der Anleitung: "https://homematic-forum.de/forum/viewtopic.php?t=41819" den USB Stick wie dort vorgeschlagen in den "Medienpfad des Containers" einhängen...
Dabei file als erstes auf, dass der Befehl:
sudo mkdir /var/lib/piVCCU/rootfs/media/usbstick
in´s Leere läuft, da das rootfs jetzt wohl im Pfad ../piVCCu3/.. ist.

- Bitte bestättigen - 
Jedenfalls hab ich dort das Verzeichnis /usbstick erzeugt
[sudo mkdir /var/lib/piVCCU3/rootfs/media/usbstick]
Laut Anleitung soll man jetzt in der "/etc/piVCCU/lxc.config " einen Eintrag:
"lxc.mount.entry = /media/usbstick media/usbstick none defaults,bind 0 0"
machen und dann rebooten.
Hab ich getan - jetzt startet der Container nicht mehr und man erhält die Fehlermeldung im log:
"
      lxc-start 20181228170435.554 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20181228170435.554 ERROR    lxc_start_ui - tools/lxc_start.c:main:368 - To get more details, run the container in foreground mode.
      lxc-start 20181228170435.554 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.
      lxc-start 20181228171829.691 ERROR    lxc_conf - conf.c:mount_entry:1708 - No such file or directory - failed to mount '/media/usbstick' on '/usr/lib/arm-linux-gnueabihf/lxc/rootfs/media/usbstick'
      lxc-start 20181228171829.706 ERROR    lxc_conf - conf.c:lxc_setup:3869 - failed to setup the mount entries for 'lxc'
      lxc-start 20181228171829.706 ERROR    lxc_start - start.c:do_start:811 - Failed to setup container "lxc".
"

Wenn ich den Mountentry: lxc.mount.entry = /media/usbstick media/usbstick none defaults,bind 0 0
wieder rausnehme, startet die Homematic.
Kann mit bitte jemand helfen oder wie muss der lxc.mount.entry richtig lauten?
BZW Muss ein bestimmtes Filessystem auf dem USB-Stick sein?

Vielen Dank

**Comment by alexreinert** [comment]
Readme lesen, bei piVCCU3 geht das anders und viel einfacher.
Stick anstöpseln,
sudo dpkg-reconfigure pivccu3
ausführen, Stick dort auswählen, fertig.

**Comment by sjheinzweiler** [comment]
Ganz schlecht beschrieben in der README :-(

Mit freundlichen Grüßen - With kind regards - cul8ter - ciao - salut

Stefan Heinz

D-55413 Weiler b. Bingen
Deutschland


Fon 0049 (0) 6721 992653

Hinweis: Der Inhalt dieser eMail ist vertraulich und ausschließlich für den bezeichneten Adressaten bestimmt. Wenn Sie nicht der vorgesehene Adressat dieser eMail sein sollten, setzen Sie sich bitte mit dem Absender der eMail oder unter der angegebenen Telefonnummer in Verbindung und vernichten Sie diese eMail auf Ihren Speichermedien.
Notice: The information contained in this email is confidential. It is intended solely for the addressee named above. If you are not the intended recipient, please notify the sender immediately and destroy this message on any media of yours.


Am 29. Dezember 2018 um 17:54:50 +01:00, hat Alexander Reinert <notifications@github.com> geschrieben:

**Comment by alexreinert** [comment]
Einfach besser machen...

**Comment by sjheinzweiler** [comment]
Ich kann das....

Gruß Stefan Heinz
Send mobile

**Comment by alexreinert** [comment]
Dann freu ich mich über den PR.
