### ISSUE TITLE
piVCCU3 and LAN-GW

### ISSUE THREAD

**Issue by CP-12** [alexreinert/piVCCU#111]
Hi,

I am more or less a beginner in this topic, so please give me simple answers;-)

I just upgraded from pivCCU2 to pivCCU3 and everything seemed to run smooth for about 1,5days, than I encountered two problems:
1: The INFO LED of my LAN GW flashes some times fast, some times slow. Devices connected to the GW can sometimes be controlled via WEBUI and sometimes not- not depending on the rhythm of the LED. Some actors can not be reached any longer (which were critical anyway). The WEB-UI shows LAN GW as "connected" and no problems with it. Restarting the Rasp, the CCU, the LAN GW, taking it from power nothing helped. Resetting the GW is not possibile as it ignores pressing the reset button - any ideas, before the update, the LAN GW was stable.

2. The other thing is the connection of Tinymatic to the CCU. While approaching the CCU over the web with cloudmatic is not a problem. Synching the app is no longer possibile complete sync stops after 50% and it gives when trying to sync the error: 

org.xmlpull.v1.XmlPullParser Exception: illegal:"<" inside attribue value (position: Start_TAG <systemVaraiblename"=Alarm_Einbruch abwesend" variable="0"@>1:662 in java.io.bufferedreader@b4ee70e) while parsing sysvarlist. 

The XML Extension otherwise works fine. Any ideas to this issue`?

Best regards and Happy New Year

C

**Comment by alexreinert** [comment]
Both issues are not related with piVCCU itself, they are related with the underlying CCU3 firmware. Because of this, I'm not able to help you.
