### ISSUE TITLE
Armbian with Kernel 4.19.13 on Orangepi Plus 2E

### ISSUE THREAD

**Issue by darkman242** [alexreinert/piVCCU#114]
Hi, with update of armbian from 12.01.2019, the kernel has changed to version 4.19.13. now pivccu3 does not work anymore - error in dpkg-reconfigure pivccu-modules-dkms.

[make.log](https://github.com/alexreinert/piVCCU/files/2770113/make.log)

thx

**Comment by alexreinert** [comment]
Which OS are you using? Stretch or Xenial?

**Comment by darkman242** [comment]
Stretch.

**Comment by alexreinert** [comment]
Very strange, this is working here withou any issue.
But on a Tinkerboard with Xenial I see a similar issue (but not on Stretch)

**Comment by alexreinert** [comment]
Kernel 4.19 needs flex and bison, which are not installed by default on older systems.
Please try:
```
sudo apt install flex bison
cd /usr/src/linux-headers-4.19.13-sunxi
sudo make scripts
sudo dpkg-reconfigure pivccu-modules-dkms
```

**Comment by darkman242** [comment]
great, it works.
thx

**Comment by Juweii** [comment]
> Kernel 4.19 needs flex and bison, which are not installed by default on older systems.
> Please try:
> 
> ```
> sudo apt install flex bison
> cd /usr/src/linux-headers-4.19.13-sunxi
> sudo make scripts
> sudo dpkg-reconfigure pivccu-modules-dkms
> ```

Great, thank you - the upgrade to 4.19 recently killed the kernel module for the HM-MOD-RPI-PCB. pivccu couldn't start with it.
