### ISSUE TITLE
Support for RockPI4

### ISSUE THREAD

**Issue by mrueg** [alexreinert/piVCCU#119]
It would be awesome if we could get support for RockPI 4 (Version B) http://rockpi.org/

Do you see any issues with the way the GPIOs there or will it be similar to the NanoPI M4 (same Rockchip CPU)?
I'm planning to get one and hopefully can provide a PR.

**Comment by alexreinert** [comment]
At the moment I have no test device, which makes it impossible to me to add the support.
But according to the schematics it should be possible.

**Comment by alexreinert** [comment]
And maybe you should consider to buy a NanoPC T4. Seems cheaper to me.

**Comment by mrueg** [comment]
The 4GB variant of the rockpi 4 b is available for ~100€ (https://shop.maker-store.de/single-board-computer/boards/einzelne-boards/2076/rock-pi-4-model-b-4gb-mit-dualband-2-4/5ghz-wlan/bluetooth-5.0) 
Did you see cheaper offers for the NanoPC T4 or NanoPI M4 in Germany?
If you're looking for a test device, maybe Radxa might be able to send you one (https://wiki.radxa.com/Special:SpecialContact). They did it for some boards in the past. :)

**Comment by alexreinert** [comment]
Amazon, 150€ But including Heatsink, Case, eMMC and power supply (and direct M.2 socket).
Without heatsink and eMMC you will not have that fun with a RK3399 based board.

**Comment by mrueg** [comment]
I still think the rockpi has some advantages (e.g. being able to use PowerDelivery and Quickcharge via usb-c and the heatspreader on the bottom, so it doesn't conflict with the HM mods)
fwiw, DTS has been posted for inclusion upstream: https://lkml.org/lkml/2019/1/1/8 :)

**Comment by markusmaker** [comment]
Hi Alex,
I use the RockPi 4 with a NVMe SSD and Ubuntu Server - so it will not work with piVCCU for. Annual install? Can I do something to help for supporting the RockPi 4?

**Comment by markusmaker** [comment]
Ok after reading through the last hours using HB-RF-USB and debmatic should work with the rock pi 4 via USB or?

**Comment by alexreinert** [comment]
I now have a test device, support should be implemented soon.

**Comment by alexreinert** [comment]
Support for Rock Pi 4 is now available
