### ISSUE TITLE
Image for rock64 not working on eMMC

### ISSUE THREAD

**Issue by eagleye2** [alexreinert/piVCCU#124]
The image for rock64 provided here works on a SD-Card perfectly out of the box.
If this image is flashed on an eMMC the whole device is not starting/not booting.
After several unsuccessful tries, I've tried to do a complete new manual install.
Dowloaded from armbian the dev stretch version went to so far okay.
It boots normally from the eMMC, and I can do almost all steps  of the Manual install of pivccu.
Everything reboots normally, until I do the command for the installation of the bridge. After that (like on the original image provided here) no reboot from the eMMC possible anymore and system doesn't start. Any Idea how to fix this? I would love to have the whole system on the eMMC instead of using a SD-Card. Thanks.

**Comment by MSStyle** [comment]
Hallo,
Das gleiche Problem habe ich auch mit dem emmc Modul.
Auch meine USB Geräte z.B. cc2531 (zigbee) und Z-wave werden nicht erkannt. 

> root@rock64:~# lsusb
Bus 005 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Mit dem normalen Image von Armbian werden diese ohne probleme erkannt.

Danke im Voraus

**Comment by MSStyle** [comment]
Habe noch etwas herausgefunden. Sobald ich vom Kernel 4.20 wechsle auf 4.4 oder 4.18 etc. funktionieren die USB Geräte, auch das kopieren von SD auf die emmc funktioniert. Jedoch nicht das HM-MOD-RPI-PCB Modul

**Comment by alexreinert** [comment]
Mir fehlt an Stelle leider eine eMMC um das nachstellen zu können.

**Comment by MSStyle** [comment]
Ok. Wäre es den möglich pivccu auf einem anderen Kernel außer 4.20 zum laufen zu bekommen? Da die USB ports bei dem 4.20 auch nicht funktionieren.

**Comment by MSStyle** [comment]
Guten Abend,
Ich habe das Problem lösen können. eMMC und die USB-Ports funktionieren jetzt auch. Und zwar habe ich im Netzt folgendes gefunden. 

> You can use this patched device tree file until it is fixed in upstream:
https://cabinets.mystia.org/parly/2019/01/06/rk3328-rock64.zip
After updating the kernel to 4.20.0-2, simply replace /boot/dtbs/rockchip/rk3328-rock64.dtb with the extracted file and reboot.

Bei mir funktioniert jetzt alles. Könnte man diese Datei eventuell in dem Image ersetzten?

**Comment by alexreinert** [comment]
Danke für die Info. Das im Image zu ändern, bringt aber nur eingeschränkt etwas, da das dann beim nächsten Kernel Update von Armbian wieder weg wäre. Daher muss diese Änderung bei Armbian gemacht werden.

**Comment by eagleye2** [comment]
gibt es hierzu Neuigkeiten? Wäre echt toll wenn es irgendwann funktionieren würde.

**Comment by MSStyle** [comment]
Hallo,
Habe gestern das Image "Armbian_5.68_Rock64_Debian_Stretch_dev_piVCCU3_2019-01-08" installiert und per "apt update && apt upgrade" wurde Kernel 5.0 installiert. Jetzt funktionieren die USB Geräte und werden auch erkannt in Iobroker. Mit dem eMMC Modul habe ich es noch nicht getestet.
