### ISSUE TITLE
Could not run it on rpi3

### ISSUE THREAD

**Issue by jogibear9988** [alexreinert/piVCCU#125]
I could not run it on my pi3

    pi@raspberrypi:~ $ sudo pivccu-info
    piVCCU version: 2.41.5-42
    Kernel modules: Available
    Raw UART dev:   Not available
    Rasp.Pi3 UART:  Assigned to GPIO pins
    HMRF Hardware:  unknown
    HMIP Hardware:  unknown
    Board serial:   unknown
    Radio MAC:      unknown
    SGTIN:          unknown
    State:          STOPPED

**Comment by jogibear9988** [comment]
pi@raspberrypi:~ $ sudo dmesg | grep uart
    [    0.000000] Kernel command line: 8250.nr_uarts=1 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=tty1 root=PARTUUID=a781502d-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
    [    0.029718] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
    [    0.833989] uart-pl011 3f201000.serial: cts_event_workaround enabled

**Comment by alexreinert** [comment]
Did you install the package pivccu-modules-raspberrypi and did you reboot your system after the installation of that package as it is stated in the documentation?

Can you please provide the content of your /boot/config.txt?

**Comment by jogibear9988** [comment]
root@raspberrypi:/home/pi# sudo apt install pivccu-modules-raspberrypi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pivccu-modules-raspberrypi is already the newest version (2.0-11).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@raspberrypi:/home/pi#

**Comment by jogibear9988** [comment]
# For more options and information see
# http://rpf.io/configtxtreadme
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on



#jochen test
#enable_uart=1
#dtoverlay=pi3-miniuart-bt
#core_freq=250dtoverlay=pi3-disable-bt
dtoverlay=pi3-disable-bt
#dtoverlay=pivccu-raspberrypi

**Comment by alexreinert** [comment]
Please remove the leading # in the last line before dtoverlay=pivccu-raspberrypi and reboot your system.

**Comment by jogibear9988** [comment]
d.h. 

in der config steht nur:

    dtparam=audio=on
    dtoverlay=pi3-disable-bt

**Comment by alexreinert** [comment]
Es fehlt aber 
```
dtoverlay=pivccu-raspberrypi
```
Ich versuche gerade zu erruieren, wie das auskommentiert da rein kommen kann, aber bevor ich einen Fix fertig habe, ist es das schnellste, das schnell selber rauszunehmen.

**Comment by jogibear9988** [comment]
now it works...

but when you look in your doku: https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md
step 5

i go for Option 1: Disabled bluetooth (prefered)

and the line dtoverlay=pi3-miniuart-bt
is only in option 2

**Comment by jogibear9988** [comment]
das dtoverlay=pivccu-raspberrypi hab ich rauskommentiert...

**Comment by jogibear9988** [comment]
dachte weil ich in der doku zu step 5 das nicht gefunden hatte es wäre durch meine zahreiche installationen reingekommen

**Comment by alexreinert** [comment]
Ok, dann brauch ich nicht weitersuchen. Das wird automatisch vom Paket pivccu-modules-raspberrypi da rein geschrieben.

**Comment by jogibear9988** [comment]
danke für die hilfe

**Comment by jogibear9988** [comment]
> Ok, dann brauch ich nicht weitersuchen. Das wird automatisch vom Paket pivccu-modules-raspberrypi da rein geschrieben.

okay, vlt. sollte man noch iwo reinschreiben was am ende alles in der boot/config sein sollte

**Comment by jogibear9988** [comment]
danke
