### ISSUE TITLE
Homematic IP wired ?

### ISSUE THREAD

**Issue by dr-apple** [alexreinert/piVCCU#126]
Hi gibt es eine Möglichkeit, HM IP wired ohne Homematic IP Wired Access Point HmIPW-DRAP an die piVCCU3 zu bekommen ? Per USB Adapter oder sowas ?

**Comment by alexreinert** [comment]
Nein und das wird aufgrund der Verschlüsselungshardware im HmIPW-DRAP auch zukünftig nicht gehen.
Stand jetzt geht HmIP Wired mit der Firmware 3.41.11 auch noch gar nicht (Weder bei piVCCU, noch bei RaspberryMatic oder original CCU3).
Im Moment braucht es zwingend eine spezielle Firmware, welche man exklusiv im Rahmen von Sunrise Projekten erhält.
