### ISSUE TITLE
Die Homematic CCU2 ist noch nicht bereit.

### ISSUE THREAD

**Issue by overfl0w72** [alexreinert/piVCCU#127]
Hallo Zusammen, kurz Vorweg ich bin ein blutiger Anfänger.

Ich habe vor ca. 1 1/2 Jahren einen ELV CCU2 Bausatz gekauft und diesen auch auf mein Tinkerboard gesteckt. Die Oberfläche der CCU2 ging bis Dato auch immer, ich habe Sie bislang jedoch nicht gebraucht, da ich meine Geräte nur Schritt für Schritt erweitere. Nun wollte ich das erste Homematic Gerät anbinden und komme nicht mehr auf die Webgui, ich bekomme immer: 

Die Homematic CCU2 ist noch nicht bereit
Bitte warten. Sie werden automatisch auf die Startseite weitergeleitet.

Jetzt wollte ich ein Update über SSH machen, dies schlägt aber irgendwie fehl..
Ich benutze folgendes Image: http://www.iobroker.net/docu/?page_id=7604&lang=de

> root@tinkerboard:~# sudo pivccu-info
> piVCCU version: 2.29.23-16
> Kernel modules: Available
> Raw UART dev:   Available
> Board serial:   OEQ0307189
> State:          RUNNING
> PID:            10488
> IP:             192.168.23.61
> IP:             2003:d4:2bcd:4800:d834:d5ff:fe71:5f91
> CPU use:        782.11 seconds
> BlkIO use:      56.00 KiB
> Memory use:     67.71 MiB
> KMem use:       1.87 MiB
> Link:           vethpivccu
>  TX bytes:      617.95 KiB
>  RX bytes:      2.13 MiB
>  Total bytes:   2.74 MiB

Über Hilfe wäre ich mehr als Dankbar,
Liebe Grüße

Maurice

**Comment by alexreinert** [comment]
Falls die CCU noch überhaupt nie im Einsatz war, würde ich an der Stelle hingehen und die alte CCU2 Version deinstallieren und stattdessen gleich die CCU3 Version installieren und nutzen. Dann spart man sich später die Migration.

Dafür per SSH auf dem Tinkerboard einloggen und:
```
sudo apt update
sudo apt install pivccu-devicetree-armbian pivccu-modules-dkms
sudo reboot
sudo apt install pivccu3
sudo apt purge pivccu
````

**Comment by overfl0w72** [comment]
Erstmal vielen Dank für die Hilfe. Leider bekomme ich schon beim ersten Command Probleme:

> root@tinkerboard:~# sudo apt update
> Hit:1 http://ports.ubuntu.com xenial InRelease
> Hit:2 http://ports.ubuntu.com xenial-security InRelease
> Hit:4 http://ports.ubuntu.com xenial-updates InRelease
> Hit:5 http://ports.ubuntu.com xenial-backports InRelease
> Ign:6 https://alexreinert.github.io/piVCCU stable InRelease
> Hit:3 https://apt.armbian.com xenial InRelease
> Err:7 https://alexreinert.github.io/piVCCU stable Release
>   404  Not Found
> Get:8 https://deb.nodesource.com/node_6.x xenial InRelease [4.634 B]
> Reading package lists... Done
> E: The repository 'https://alexreinert.github.io/piVCCU stable Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by alexreinert** [comment]
Ui, dann bist du auf einen wirklich alten System.
Du musst die Url ```https://alexreinert.github.io/piVCCU``` durch ```https://www.pivccu.de/piVCCU``` ersetzen in der Datei /etc/apt/sources.list und ggf. in allen Dateien im Verzeichnis /etc/apt/sources.list.d

Und dann mit den Schritten von oben von vorne anfangen.

**Comment by overfl0w72** [comment]
Es sprengt warschl. deine Zeit, ich habe alles gemacht, nur bekomme ich folgendes:

> root@tinkerboard:~# sudo apt install pivccu3
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following packages will be REMOVED:
>   pivccu
> The following NEW packages will be installed:
>   pivccu3
> 0 upgraded, 1 newly installed, 1 to remove and 2 not upgraded.
> 1 not fully installed or removed.
> Need to get 103 MB of archives.
> After this operation, 0 B of additional disk space will be used.
> Do you want to continue? [Y/n] y
> Get:1 https://www.pivccu.de/piVCCU stable/main armhf pivccu3 armhf 3.41.11-17 [1                         03 MB]
> Fetched 103 MB in 2min 55s (583 kB/s)
> Preconfiguring packages ...
> (Reading database ... 64744 files and directories currently installed.)
> Removing pivccu (2.29.23-16) ...
> Removed symlink /etc/systemd/system/multi-user.target.wants/pivccu.service.
> Selecting previously unselected package pivccu3.
> (Reading database ... 60020 files and directories currently installed.)
> Preparing to unpack .../pivccu3_3.41.11-17_armhf.deb ...
> Unpacking pivccu3 (3.41.11-17) ...
> Setting up pivccu-modules-dkms (1.0.22) ...
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area....
> make KERNELRELEASE=4.19.18-rockchip ARCH=arm all.....(bad exit status: 2)
> Error! Bad return status for module build on kernel: 4.19.18-rockchip (armv7l)
> Consult /var/lib/dkms/pivccu/1.0.22/build/make.log for more information.
> dpkg: error processing package pivccu-modules-dkms (--configure):
>  subprocess installed post-installation script returned error exit status 10
> dpkg: dependency problems prevent configuration of pivccu3:
>  pivccu3 depends on pivccu-modules-dkms (>= 1.0.10); however:
>   Package pivccu-modules-dkms is not configured yet.
> 
> dpkg: error processing package pivccu3 (--configure):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  pivccu-modules-dkms
>  pivccu3
> piVCCU: DTB rk3288-miniarm.dtb was already patched
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> root@tinkerboard:~# sudo apt purge pivccu
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following packages will be REMOVED:
>   pivccu*
> 0 upgraded, 0 newly installed, 1 to remove and 2 not upgraded.
> 2 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> Do you want to continue? [Y/n] y
> (Reading database ... 80057 files and directories currently installed.)
> Removing pivccu (2.29.23-16) ...
> Purging configuration files for pivccu (2.29.23-16) ...
> dpkg: warning: while removing pivccu, directory '/var/lib/piVCCU/userfs' not emp                         ty so not removed
> dpkg: warning: while removing pivccu, directory '/var/lib/piVCCU/sdcardfs' not e                         mpty so not removed
> dpkg: warning: while removing pivccu, directory '/var/lib/piVCCU/rootfs/root' no                         t empty so not removed
> Setting up pivccu-modules-dkms (1.0.22) ...
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area....
> make KERNELRELEASE=4.19.18-rockchip ARCH=arm all....(bad exit status: 2)
> Error! Bad return status for module build on kernel: 4.19.18-rockchip (armv7l)
> Consult /var/lib/dkms/pivccu/1.0.22/build/make.log for more information.
> dpkg: error processing package pivccu-modules-dkms (--configure):
>  subprocess installed post-installation script returned error exit status 10
> dpkg: dependency problems prevent configuration of pivccu3:
>  pivccu3 depends on pivccu-modules-dkms (>= 1.0.10); however:
>   Package pivccu-modules-dkms is not configured yet.
> 
> dpkg: error processing package pivccu3 (--configure):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  pivccu-modules-dkms
>  pivccu3
> piVCCU: DTB rk3288-miniarm.dtb was already patched
> E: Sub-process /usr/bin/dpkg returned an error code (1)

Hat es geklappt? Glaube nicht oder?

**Comment by alexreinert** [comment]
Was steht in der Datei /var/lib/dkms/pivccu/1.0.22/build/make.log?

**Comment by overfl0w72** [comment]
> DKMS make.log for pivccu-1.0.22 for kernel 4.19.18-rockchip (armv7l)
> Mi 6. Feb 20:19:12 CET 2019
> make -C /lib/modules/4.19.18-rockchip/build M=/var/lib/dkms/pivccu/1.0.22/build modules
> make[1]: Entering directory '/usr/src/linux-headers-4.19.18-rockchip'
>   CC [M]  /var/lib/dkms/pivccu/1.0.22/build/eq3_char_loop.o
> /bin/sh: 1: ./scripts/recordmcount: not found
> scripts/Makefile.build:309: recipe for target '/var/lib/dkms/pivccu/1.0.22/build/eq3_char_loop.o' failed
> make[2]: *** [/var/lib/dkms/pivccu/1.0.22/build/eq3_char_loop.o] Error 127
> make[2]: *** Deleting file '/var/lib/dkms/pivccu/1.0.22/build/eq3_char_loop.o'
> Makefile:1520: recipe for target '_module_/var/lib/dkms/pivccu/1.0.22/build' failed
> make[1]: *** [_module_/var/lib/dkms/pivccu/1.0.22/build] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-4.19.18-rockchip'
> Makefile:23: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by alexreinert** [comment]
```
sudo apt install bison flex
sudo apt install --reinstall linux-headers-next-rockchip
sudo apt install --reinstall pivccu-modules-dkms pivccu3
```

**Comment by overfl0w72** [comment]
> root@tinkerboard:~# sudo apt install bison flex
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> bison is already the newest version (2:3.0.4.dfsg-1).
> bison set to manually installed.
> flex is already the newest version (2.6.0-11).
> flex set to manually installed.
> 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
> 2 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> Do you want to continue? [Y/n] y
> Setting up pivccu-modules-dkms (1.0.22) ...
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area....
> make KERNELRELEASE=4.19.18-rockchip ARCH=arm all....(bad exit status: 2)
> Error! Bad return status for module build on kernel: 4.19.18-rockchip (armv7l)
> Consult /var/lib/dkms/pivccu/1.0.22/build/make.log for more information.
> dpkg: error processing package pivccu-modules-dkms (--configure):
>  subprocess installed post-installation script returned error exit status 10
> dpkg: dependency problems prevent configuration of pivccu3:
>  pivccu3 depends on pivccu-modules-dkms (>= 1.0.10); however:
>   Package pivccu-modules-dkms is not configured yet.
> 
> dpkg: error processing package pivccu3 (--configure):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  pivccu-modules-dkms
>  pivccu3
> piVCCU: DTB rk3288-miniarm.dtb was already patched
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> root@tinkerboard:~# sudo apt install --reinstall linux-headers-next-rockchip
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> 0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 2 not upgraded.
> 2 not fully installed or removed.
> Need to get 0 B/10,6 MB of archives.
> After this operation, 0 B of additional disk space will be used.
> (Reading database ... 80051 files and directories currently installed.)
> Preparing to unpack .../linux-headers-next-rockchip_5.73_armhf.deb ...
> Unpacking linux-headers-next-rockchip (5.73) over (5.73) ...
> Setting up pivccu-modules-dkms (1.0.22) ...
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area....
> make KERNELRELEASE=4.19.18-rockchip ARCH=arm all....(bad exit status: 2)
> Error! Bad return status for module build on kernel: 4.19.18-rockchip (armv7l)
> Consult /var/lib/dkms/pivccu/1.0.22/build/make.log for more information.
> dpkg: error processing package pivccu-modules-dkms (--configure):
>  subprocess installed post-installation script returned error exit status 10
> dpkg: dependency problems prevent configuration of pivccu3:
>  pivccu3 depends on pivccu-modules-dkms (>= 1.0.10); however:
>   Package pivccu-modules-dkms is not configured yet.
> 
> dpkg: error processing package pivccu3 (--configure):
>  dependency problems - leaving unconfigured
> Setting up linux-headers-next-rockchip (5.73) ...
> Compiling headers - please wait ...
> Errors were encountered while processing:
>  pivccu-modules-dkms
>  pivccu3
> piVCCU: DTB rk3288-miniarm.dtb was already patched
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> root@tinkerboard:~# sudo apt install --reinstall pivccu-modules-dkms pivccu3
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> 0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 2 not upgraded.
> 2 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> E: Internal Error, No file name for pivccu-modules-dkms:armhf

**Comment by alexreinert** [comment]
```
cd /usr/src/linux-headers-4.19.18-rockchip/
make scripts
sudo apt install --reinstall pivccu-modules-dkms pivccu3
```

**Comment by overfl0w72** [comment]
> root@tinkerboard:~# cd /usr/src/linux-headers-4.19.18-rockchip/
> root@tinkerboard:/usr/src/linux-headers-4.19.18-rockchip# make scripts
> root@tinkerboard:/usr/src/linux-headers-4.19.18-rockchip# sudo apt install --reinstall pivccu-modules-dkms pivccu3
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> 0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 2 not upgraded.
> 2 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> E: Internal Error, No file name for pivccu-modules-dkms:armhf

**Comment by alexreinert** [comment]
sudo dpkg --configure -a

**Comment by overfl0w72** [comment]
![screenshot_1](https://user-images.githubusercontent.com/38362085/52369935-05881500-2a52-11e9-9054-86a4707c52e8.png)

**Comment by alexreinert** [comment]
Richtige Option mit den Cursor Tasten auswählen und mit Entee bestätigen.

**Comment by overfl0w72** [comment]
Wow, schon mal vielen vielen Dank.
Habe nun den ersten gewählt, da ich folgendes Modul habe: https://www.elv.de/homematic-funkmodul-fuer-raspberry-pi-bausatz.html

Im Anschluss bekomme ich:

> 
> DKMS: install completed.
> Created symlink from /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service to /lib/systemd/system/pivccu-dkms.service.
> Created symlink from /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service to /lib/systemd/system/pivccu-dkms.service.
> Setting up pivccu3 (3.41.11-17) ...
> Installing new version of config file /lib/systemd/system/pivccu.service ...
> Created symlink from /etc/systemd/system/multi-user.target.wants/pivccu.service to /lib/systemd/system/pivccu.service.
> Job for pivccu.service failed because a configured resource limit was exceeded. See "systemctl status pivccu.service" and "journalctl -xe" for details.

**Comment by alexreinert** [comment]
Reboot, danach

sudo pivccu-info

**Comment by overfl0w72** [comment]
> root@tinkerboard:~# sudo pivccu-info
> piVCCU version: 3.41.11-17
> Kernel modules: Available
> Raw UART dev:   Available
> HMRF Hardware:  HM-MOD-RPI-PCB
> HMIP Hardware:  HM-MOD-RPI-PCB
> Board serial:   OEQ0307189
> Radio MAC:      0x5840fe
> SGTIN:          3014F711A061A7D7098E17F5
> State:          RUNNING
> PID:            1872
> IP:             2003:d4:2bcd:4800:d834:d5ff:fe71:5f91
> CPU use:        0.38 seconds
> BlkIO use:      2.01 MiB
> Memory use:     4.31 MiB
> KMem use:       1.21 MiB
> Link:           vethpivccu
>  TX bytes:      602 bytes
>  RX bytes:      8.48 KiB
>  Total bytes:   9.07 KiB
>

**Comment by overfl0w72** [comment]
![image](https://user-images.githubusercontent.com/38362085/52370369-fb1a4b00-2a52-11e9-8fd5-bfbfa197c49c.png)

Läuft, Danke Danke Danke

**Comment by alexreinert** [comment]
Idealerweise dann zukünftig halbwegs zeitnah Updates einspielen, über ein Jahr an Updates überspringen ist schon ein Wort. ;-)
