### ISSUE TITLE
Homematic IP Tinker Board S

### ISSUE THREAD

**Issue by BalduT** [alexreinert/piVCCU#128]
nach installation des Images "Armbian_5.68_Tinkerboard_Debian_Stretch_next_piVCCU3_2019-01-08.img"
im eMMC können keine meiner Homematic IP 140733A0 Fenster- und Türkontakte angelernt werden; 
nach dem anlernen auf einem RP3 mit dem gleichen Funk Modul und der Datenübernahme vom RP3 auf das Tinker Board S können die Kontakte genutzt werden. Wann wird es möglich sein IP Geräte direkt 
anlernen zu können??

**Comment by alexreinert** [comment]
Seit der allerersten Version können HmIP Geräte angelernt werden und von den genannten Geräten habe ich hier welche selbst im Einsatz.
Falls man auf dem Tinkerboard aber das alte Funkmodul HM-MOD-RPI-PCB im Einsatz hat, sollte man auf jeden Fall eine externe Antenne nutzen, da hier einiges mehr an Störstrahlung vom SBC erzeugt wird, welches genau zu einem solchen Fehlerbild führt, mit der externen Antenne bekommt man das aber in den Griff.

**Comment by BalduT** [comment]
das alte Funkmodul HM-MOD-RPI-PCB mit externer Antenne wurde verbaut; nach Einsatz eines Ferrit Rings in der Netzteilzuleitung funktionierte auch das anlernen.
