### ISSUE TITLE
Unable to install addon hm2mqtt

### ISSUE THREAD

**Issue by M0ebiu5** [alexreinert/piVCCU#13]
The addon hm2mqtt does not work - it does not show up in the control panel after installation (also there is no error message). 

Should it be possible to install addons?
piVCCU version: 2.29.23-18

**Comment by alexreinert** [comment]
Can you please try 2.29.23-19 (released a couple of hours ago)? There is a fix in that version, which addresses a simular issue.

**Comment by M0ebiu5** [comment]
Installation working with version 2.29.23-19.
Thanks!
