### ISSUE TITLE
Armbian with Kernel 4.19.20 on Orangepi Plus 2E

### ISSUE THREAD

**Issue by darkman242** [alexreinert/piVCCU#131]
Hi Alex, with armbian-update 5.75 the kernel changed to 4.19.20. pivccu does not start and the 'apt install pivccu-modules-dkms' breaks with error. I'm using stretch.

[make.log](https://github.com/alexreinert/piVCCU/files/2850372/make.log)

Thx

**Comment by alexreinert** [comment]
Please try:

```
sudo apt install bison flex
cd /usr/src/linux-headers-4.19.20-sunxi
sudo make scripts
sudo apt install pivccu-modules-dkms
```

**Comment by darkman242** [comment]
make scripts failed with error...

scripts/kconfig/conf  --syncconfig Kconfig
net/Kconfig:89: can't open file "net/wireguard/Kconfig"
scripts/kconfig/Makefile:69: recipe for target 'syncconfig' failed
make[2]: *** [syncconfig] Error 1
Makefile:539: recipe for target 'syncconfig' failed
make[1]: *** [syncconfig] Error 2
Makefile:635: recipe for target 'include/config/auto.conf' failed
make: *** [include/config/auto.conf] Error 2
root@xxxxxx:/usr/src/linux-headers-4.19.20-sunxi#

**Comment by alexreinert** [comment]
I will take a look at it at the evening. Until then, I would suggest a downgrade to the 5.73 kernel:
```
sudo apt install linux-image-next-sunxi=5.73 linux-headers-next-sunxi=5.73 linux-dtb-next-sunxi=5.73
```
Followed by a reboot.

**Comment by darkman242** [comment]
downgrade works fine

thx

**Comment by alexreinert** [comment]
Seems to be an upstream issue in Armbian kernel package, that also affects other boards.
Right now, the only solution is to downgrade to kernel 5.73

**Comment by darkman242** [comment]
Thx for support and information.

**Comment by jgantenberg** [comment]
Same issue here on the same platform. Downgrade worked fine and saved my piVCCU3. Thx for support.

**Comment by alexreinert** [comment]
Please note armbian/build#1278

**Comment by alexreinert** [comment]
I added a workaround to the modules package, update to current kernel package are now working.
