### ISSUE TITLE
Kein Zugriff auf WebUI nach HTTP Authentifizierung in pivCCU3

### ISSUE THREAD

**Issue by oberschmuh** [alexreinert/piVCCU#133]
Hallo Alex,
erst mal ein fettes Dankeschön für die tolle Arbeit! Nach der Aktivierung der HTTP Authentifizierung in der CCU Oberfläche und abschliessenden Neustart der CCU wird die WebUI nicht mehr geladen.
So bald ich folgende Befehle ausführe funktioniert die WebUI sofort:
sudo pivccu-attach /etc/init.d/S50lighttpd stop
sudo pivccu-attach /etc/init.d/S50lighttpd start
Eine log Datei habe ich mal angehängt. Das Problem hat auch mein Kollege, installiert ist:
ARMBIAN 5.73 stable Debian GNU/Linux 9 (stretch) 4.19.17-sunxi auf einem OrangePi Zero

Vielleicht ist das Problem ja bekannt und du kannst uns ja weiterhelfen?
Beste Grüße
Werner
[pivCCU3.log](https://github.com/alexreinert/piVCCU/files/2859640/pivCCU3.log)

**Comment by alexreinert** [comment]
Ist auch ioBroker im Einsatz?

**Comment by oberschmuh** [comment]
Nein.

**Comment by oberschmuh** [comment]
Also schon, aber auf einem anderen System.

**Comment by alexreinert** [comment]
Dann ist es sehr vermutlich ein Known Issue zwischen ioBroker und CCU3 (auch original) seit Firmware 3.41.x an welchem ich nicht ändern kann. Bitte einfach mal den hmrpc Adapter in ioBroker pausieren und dann die CCU neu starten, Wenn dann kein Problem auftaucht, dann ist verifiziert, dass es daran hängt.
Siehe auch https://homematic-forum.de/forum/viewtopic.php?f=69&t=44721&start=10#p489897 + folgende Einträge

**Comment by oberschmuh** [comment]
Du hast Recht, es verhält sich genau so, ich konnte das reproduzieren. Vielen Dank für die Erklärung.
