### ISSUE TITLE
Failed to start piVCCU nach update

### ISSUE THREAD

**Issue by Philip52** [alexreinert/piVCCU#137]
Hallo,
nachdem ich gestern ein update über die Konsole gemacht habe, läuft die CCU nicht mehr. Ich habe daraufhin die sd Karte neu formatiert und alles von vorne installiert. Nach der installation läuft die CCU (Armbian_5.68_Tinkerboard_Debian_Stretch_next_piVCCU3_2019-01-08) 

piVCCU version: 3.41.11-15
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   OEQ0303416
Radio MAC:      0x583000
SGTIN:          3014F711A061A7D7098E0938
State:          RUNNING
PID:            3659
IP:             192.168.178.77
CPU use:        16.25 seconds
BlkIO use:      59.24 MiB
Memory use:     151.79 MiB
KMem use:       3.76 MiB
Link:           vethpivccu
 TX bytes:      149.43 KiB
 RX bytes:      180.58 KiB
 Total bytes:   330.01 KiB

dann das Tinkerboard geupdated und dann kommt direkt dass:
piVCCU version: 3.41.11-17
Kernel modules: Not available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   OEQ0303416
Radio MAC:      0x583000
SGTIN:          3014F711A061A7D7098E0938
State:          STOPPED

auch ein  sudo apt install --reinstall pivccu3 brachte leider keinen Erfolg.
Das sieht so aus:

Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 103 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://www.pivccu.de/piVCCU stable/main armhf pivccu3 armhf 3.41.11-17 [103 MB]
Fetched 103 MB in 1min 47s (950 kB/s)
Preconfiguring packages ...
(Reading database ... 78282 files and directories currently installed.)
Preparing to unpack .../pivccu3_3.41.11-17_armhf.deb ...
Removed /etc/systemd/system/multi-user.target.wants/pivccu.service.
Unpacking pivccu3 (3.41.11-17) over (3.41.11-17) ...
Setting up pivccu3 (3.41.11-17) ...
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu.service → /lib/systemd/system/pivccu.service.
Job for pivccu.service failed because of unavailable resources or another system error.
See "systemctl status pivccu.service" and "journalctl -xe" for details.
piVCCU: DTB rk3288-tinker.dtb was already patched
root@tinkerboard:~# systemctl status pivccu.service
● pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: enabled)
   Active: failed (Result: resources) since Fri 2019-02-22 13:38:20 UTC; 2min 2s ago
  Process: 19125 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, status=0/SUCCESS)
 Main PID: 3649 (code=exited, status=1/FAILURE)
      CPU: 577ms

Feb 22 13:37:45 tinkerboard start_container.sh[19125]: modprobe: FATAL: Module rpi_rf_mod_led n
Feb 22 13:37:45 tinkerboard start_container.sh[19125]: kernel.sched_rt_runtime_us = -1
Feb 22 13:37:50 tinkerboard start_container.sh[19125]: lxc-start: tools/lxc_start.c: main: 366
Feb 22 13:37:50 tinkerboard start_container.sh[19125]: lxc-start: tools/lxc_start.c: main: 368
Feb 22 13:37:50 tinkerboard start_container.sh[19125]: lxc-start: tools/lxc_start.c: main: 370
Feb 22 13:37:50 tinkerboard systemd[1]: pivccu.service: PID file /var/run/pivccu3.pid not reada
Feb 22 13:38:20 tinkerboard systemd[1]: pivccu.service: Daemon never wrote its PID file. Failin
Feb 22 13:38:20 tinkerboard systemd[1]: Failed to start piVCCU.
Feb 22 13:38:20 tinkerboard systemd[1]: pivccu.service: Unit entered failed state.
Feb 22 13:38:20 tinkerboard systemd[1]: pivccu.service: Failed with result 'resources'.
lines 1-17/17 (END)

Nach einem reboot sieht es dann so aus:
piVCCU version: 3.41.11-17
Kernel modules: Not available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          STOPPED

und jetzt die berühmte Frage: Wie bekomme ich das wieder zum laufen? :)

Danke im Voraus

**Comment by alexreinert** [comment]
Das hängt vermutlich an einem Bug in den Kernel Headern von Armbian.

```
sudo apt install bison flex
cd /usr/src/linux-headers-4.19.20-rockchip
sudo mkdir -p net/wireguard
sudo touch net/wireguard/Kconfig
sudo touch net/wireguard/Makefile
sudo make scripts
sudo dpkg-reconfigure pivccu-modules-dkms
sudo reboot
```

Der Pfad in der zweiten Zeile muss ggf. angepasst werden.

**Comment by Philip52** [comment]
Wow. Danke für die schnelle Antwort. Probiere ich gleich aus wenn ich wieder zurück bin.👍

**Comment by Philip52** [comment]
Hat funktioniert.
Danke für deine Mühe👏👏👏

**Comment by alexreinert** [comment]
Gerne.

**Comment by Animizio** [comment]
Hey, bei mir funktioniert
sudo make scripts
leider nicht. Ich bekomm da immer einen Fehler.
Und ist es nicht möglich ,dafür dauerhaft eine Lösung zu finden? Das ist ja nervig, da nach jedem Update wieder machen zu müssen.

Lg
