### ISSUE TITLE
Pivccu-modules-dkms (1.0.24) installierungsfehler

### ISSUE THREAD

**Issue by krobipd** [alexreinert/piVCCU#138]
Serwus

Hab gerade ein Update auf die aktuelle Version gemacht (vorher 1.0.23) und folgende Fehlermeldung bekommen

<pre><Code>scripts/sortextable.c:31:32: fatal error: tools/be_byteshift.h: Datei oder Verzeichnis nicht gefunden
 #include <tools/be_byteshift.h>
                                ^
compilation terminated.
scripts/Makefile.host:102: die Regel für Ziel „scripts/sortextable“ scheiterte
make[1]: *** [scripts/sortextable] Fehler 1
Makefile:572: die Regel für Ziel „scripts“ scheiterte
make: *** [scripts] Fehler 2</Code></pre>

**Comment by alexreinert** [comment]
Welches OS?
Und bitte komplette Ausgabe, nicht nur den Ausschnitt.

**Comment by krobipd** [comment]
Ähm ja sorry

Raspbian, raspberry pi 3+
Es funktioniert aber soweit alles einwandfrei.

Blöde Frage wie komme ich jetzt, nachträglich, an das log?

**Comment by alexreinert** [comment]
Gar nicht, aber dann versuch ich das mal nachzustellen.
Ich hatte es hier ebenfalls auf Raspbian durchgetestet, aber nicht auf einen deutschen System. Kannst du mir noch deinen Kernel sagen (uname -a)?

**Comment by krobipd** [comment]
4.14.98-v7

**Comment by alexreinert** [comment]
Ich konnte es nachstellen, es hängt irgendwie am Raspberry Kernel Paket, welches vor ein paar Tagen erst rauskam. Ich hatte noch mit dem Kernel davor getestet.
Die Fehlermeldung ist an der Stelle aber komplett unkritisch und kann ignoriert werden, die Kernel Module werden komplett gebaut.
