### ISSUE TITLE
Fehler beim update von pivccu-modules-dkms

### ISSUE THREAD

**Issue by ettanin** [alexreinert/piVCCU#139]
Leider kann ich 'pivccu-modules-dkms' im Moment nicht updaten. Irgendeine Idee ?

**sudo apt-get upgrade -V**
Die folgenden Pakete sind zurückgehalten worden:
   pivccu-modules-dkms (1.0.21 => 1.0.24)

**sudo apt-get dist-upgrade**

E: Fehlschlag beim Holen von https://www.pivccu.de/piVCCU/pool/main/p/pivccu-modules-dkms/pivccu-modules-dkms-1.0.24.deb  404  Not Found

Rapsi 3+
Linux raspimatic 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

**Comment by alexreinert** [comment]
apt update machen, die 1.0.24 ist nicht mehr aktuell, ich habe heute morgen die 1.0.25 hochgeladen.

**Comment by ettanin** [comment]
Nach einem apt update wurde das Paket immer noch zurückgehalten  jetzt halt 1.0.25.
Mit  apt-get dist-upgrade ging's dann

Danke

**Comment by alexreinert** [comment]
Idealerweise sollte man nicht mehr apt-get nutzen, sondern apt. Das macht weniger Probleme  mit zurückgehaltenen Probleme.
