### ISSUE TITLE
where can I set a different Homematic Home ID?

### ISSUE THREAD

**Issue by EsOmEs** [alexreinert/piVCCU#14]
According to public docs  the Homematic HM-ID is in the config file /usr/local/etc/config/rfd/BidCoS-RF.dev . In pivCCU this file does not exist. How or where can i modify my Home ID?

**Comment by alexreinert** [comment]
Which documentation is that? Google find for that file only some hits in the FHEM forum.

As far as I know, the id is set in /etc/config/ids in current CCU firmware versions.

**Comment by EsOmEs** [comment]
THe one i read was https://wiki.fhem.de/wiki/HomeMatic

If i change the file you mention and reboot the pivCCU the ids file in /var still contains the original one. Is it auto generated?

**Comment by alexreinert** [comment]
In that docu is nowhere said, that you can change your id using the BidCoS-RF.dev file...

The /var/ids is generated on each boot using the current hardware values. The /etc/config/ids is inside a normal backup and remain unchanged if you change between CCUs. But I'm not sure, if this is the only file you have to change. But this is not a piVCCU issue, it is a Homematic CCU issue, piVCCU will behave exactly the same as the original CCU2 on this. Maybe you could ask for that in the (german speaking) homematic-forum.de

**Comment by EsOmEs** [comment]
Danke, das werde ich machen. Gibt es einen anderen Weg, Dinge mit Ihnen zu diskutieren als einen Bug report zu öffnen?

**Comment by alexreinert** [comment]
Am besten im Homatic Forum, für reine piVCCU Sachen gibt es dort auch ein Unterforum.
