### ISSUE TITLE
Openhabian und piVCCU

### ISSUE THREAD

**Issue by Jproject986** [alexreinert/piVCCU#140]
Ich habe auf dem openHABin-Image versucht piVCCU zu installieren. Seit dem startet mein Raspberry nicht mehr. Kann ich piVCCU nur auf ein normales Debian-Stretch-Imge installieren?

**Comment by alexreinert** [comment]
OpenHabian basiert auf Raspbian und das wird unterstützt. Um helfen zu können, sind das aber massiv zu wenig Informationen.

**Comment by Jproject986** [comment]
Hallo, danke für die schnelle Antwort. 
Vermutlich habe ich den Fehler gefunden, nach dem ich sudo apt update und sudo apt upgrade ausgeführt habe, verlief die Installation reibungslos.
