### ISSUE TITLE
Check if HB-RF-USB is mounted correctly

### ISSUE THREAD

**Issue by darkspirit510** [alexreinert/piVCCU#144]
Hi Alex,

I just flashed pivccu3-image to my SD card and started my raspberry pi 2. WebUI comes up. I'm using [HB-RF-USB](https://www.telekom.de/zuhause/smarthome/geraete/funkstick-homematic-ip)

dmesg says:

> [    2.180702] usb 1-1.4: New USB device found, idVendor=1b1f, idProduct=c020
> [    2.184256] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [    2.187649] usb 1-1.4: Product: eQ-3 HmIP-RFUSB
> [    2.190928] usb 1-1.4: Manufacturer: Silicon Labs
> [    2.194141] usb 1-1.4: SerialNumber: 3014F711A061A7C00010CECF
> [...]
> [   11.077567] usbcore: registered new interface driver usbserial
> [   11.077643] usbcore: registered new interface driver usbserial_generic
> [   11.077704] usbserial: USB Serial support registered for generic
> [   11.084406] usbcore: registered new interface driver cp210x
> [   11.084530] usbserial: USB Serial support registered for cp210x
> [   11.101154] cp210x 1-1.4:1.0: cp210x converter detected
> [   11.105351] usb 1-1.4: cp210x converter now attached to ttyUSB0

I ran **sudo dpkg-reconfigure pivccu3**. Can I check if the USB device can be used? To be honest, this is my first try with homematic so I'm not sure if I'm doing it right. I got [this one](https://www.amazon.de/Homematic-IP-140280A0-Heizk%C3%B6rperthermostat-140280/dp/B00ZQG6OTO) which should be in paring mode right after start.

Thanks in advance for any help!

**Comment by alexreinert** [comment]
You do not have a HB-RF-USB. You have a HmIP-RFUSB. This stick can be used, but it does not support HmRF nor HmIP Wired.

You can use 
```
sudo pivccu-info
```
to check, if the stick was detected by piVCCU. Referring to the dmesg log, I would assume, that it was detected.

P.S. Mounting is not the right wording in that case, only storage usb sticks can be mounted.

**Comment by darkspirit510** [comment]
Oh, okay, sorry for the misunderstanding. I only want to control HmIP-Devices, so this is no problem for me. 

Yesterday I was not able to find my device. This morning I woke up because the heater was running - the pairing happend over the night without pairing mode enabled. Since the logfile contained some undervoltage entries, I ordered a stronger power unit. Your given command says

> sudo pivccu-info
> piVCCU version: 3.43.16-20
> Kernel modules: Available
> Raw UART dev:   Available
> HMRF Hardware:  FAKE_HMRF
> HMIP Hardware:  HMIP-RFUSB
> Board serial:   FKE1659008
> Radio MAC:      0xd47976
> SGTIN:          3014F5AC94000416FB5330AD
> State:          RUNNING
> PID:            640
> IP:             192.168.178.45
> CPU use:        660.09 seconds
> BlkIO use:      51.30 MiB
> Link:           vethpivccu
>  TX bytes:      44.29 MiB
>  RX bytes:      16.07 MiB
>  Total bytes:   60.36 MiB

After the restart, pairing seems to be impossible again. A little antenna symbol is blinking on the device and it stays offline in the CCU web-ui. At least no more undervoltage warnings in the logfile.

Are there any more debugging features to see where the problem might come from?

PS: Oops, the more you know. Thank you :-)

**Comment by alexreinert** [comment]
Undervoltage causes a reset of the USB port of the Raspberry which results in a lot of trouble with the HmIP-RFUSB.
Are you sure, that the device is not paired with an other CCU? Normally the blinking antenna is only shown on paired devices. Maybe you should try a full reset of the device.

**Comment by darkspirit510** [comment]
Wow, what a fast reply! I just removed the device and did a reset. Let's see, if this works already.

**Comment by darkspirit510** [comment]
> Are you sure, that the device is not paired with an other CCU? Normally the blinking antenna is only shown on paired devices. Maybe you should try a full reset of the device.

It was already paired this morning (before restart)

**Comment by darkspirit510** [comment]
No, sorry. No "magical" pairing over night. Any other ideas?

**Comment by alexreinert** [comment]
1. Use a good power source. If there is any undervoltage logged, you will not get a stable system.
2. Full reset of the Homematic device.
3. Remove power from device
4. Start pairing mode in WebUI
5. Power the device, do not touch any buttons
6. Wait until pairing mode in WebUI stops
7. Take a look in the inbox

A magical pairing will not occur.

**Comment by darkspirit510** [comment]
1. I got a new one, no more undervoltage warnings in my logfiles
2. - 6. Done
7. Nothing

I'll try again tomorrow, but if this doesn't work, i'll send my stuff back. Thank you anyway!

PS: "Magical Pairing" - damit meinte ich nur, dass nichts funktioniert hat, aber am nächsten Tag - OHNE Paring-Mode" - der Thermostat mit der CCU (und das trotz Undervoltage) verbunden war. Kommt wohl auf Englisch nicht rüber :-)

**Comment by alexreinert** [comment]
Ich habe das so verstanden. Aber es gibt kein Pairing ohne Pairing Mode. Das Pairing passiert während des Pairing Modus der WebUI oder gar nicht. Es könnte höchstens sein, dass da irgendein Caching Problem der WebUI dazu kommt und das Pairing als solches geklappt hat, aber aus irgendwelchen Gründen die WebUI nicht korrekt angezeigt wurde.
Oder was natürlich auch sein kann: Wenn das Gerät einmal gepairt ist und dann nicht komplett aus der CCU rausgeschmissen wird, dann wird es beim Neuanlernen auch nicht im Posteingang landen, sondern befindet sich schon bei den Geräten.

**Comment by alexreinert** [comment]
Wie wurde den der Werksreset gemacht? Da passieren regelmäßig auch Benutzerfehler.

**Comment by darkspirit510** [comment]
Gut, dann auf Deutsch weiter. Nicht, dass die Widerrufsfrist verstreicht :-).

Das Gerät war (vermutlich) nicht gepairt. Taucht auch nicht mehr in den Geräten auf. Habe einen Werksreset wie folgt gemacht:

- Batterie raus
- blaues Quadrat gedrückt halten
- Warten, bis "res" angezeigt wird
- Knopf loslassen
- Noch mal gedrückt halten
- Warten, bis es grün wird
- Loslassen und auf den Neustart warten
- Gerät ist zurückgesetzt ([Quelle](https://files.elv.com/Assets/Produkte/14/1402/140280/Downloads/140280_thermostat_um.pdf)

Habe irgendwo gelesen, dass das bei den Geräten zwei mal hintereinander gemacht werden muss - nichts. Bei Undervoltage ging es, mit neuem 2.5A Netzteil und ohne Warnings nicht? Seltsam...

Ich kann höchstens noch mal versuchen, das pivccu neu aufzuspielen.

**Comment by darkspirit510** [comment]
Bin ganz drüber weggekommen, hier zu antworten. Nachdem auch der mehrfache Reset nichts gebracht hat, habe ich den Pi noch mal neu gestartet. Dann hat es geklappt. Danke für die Unterstützung!
