### ISSUE TITLE
Kann kein Backup aus einem RaspberryMatic einspielen

### ISSUE THREAD

**Issue by tampara** [alexreinert/piVCCU#145]
Hallo,
auf meiner RaspberryMatic habe ich alle Addons deinstalliert und anschließend ein Backup erstellt.
Spiele ich dieses Backup nun in einem frisch installierten und geupdaten ioBroker-AllInOne inkl. piVCCU ein, dann erhalte ich nach der Eingabe des Sicherheitsschlüssel das folgende Fenster:
${transferUserBackupTitle}
${transferUserBackupContent}
<<Ladebalken>>
OK-Schaltfläche

Der Ladebalken macht eine Endlos-Runde und auch nach mehreren Minuten gibt es kein Feedback. Was habe ich falsch gemacht?
Vielen Dank für eure Hilfe.
Gruß
Stefan

**Comment by alexreinert** [comment]
Welche Versionen von RaspberryMatic und piVCCU sind im Einsatz?

**Comment by tampara** [comment]
piVCCU mit Version 2.41.9
RaspberryMatic mit Version 3.41.11.20190126
Habe das RPI-RF-MOD Modul installiert.

**Comment by alexreinert** [comment]
Das kann so nicht funktionieren. RaspberryMatic in def Version entspricht der CCU3 und das kann nicht in eine CCU2 Version von piVCCU eingespielt werden. Daher müsste man vorher auf eine piVCCU3 wechseln.

**Comment by tampara** [comment]
Vielen Dank für Ihre Hilfe. Habe auf piVCCU3 gewechselt und anschließend ein Werksreset durchgeführt. Danach konnte ich das Backup einwandfrei einspielen.
