### ISSUE TITLE
Daemon never wrote its PID file. Failing.

### ISSUE THREAD

**Issue by ZiIMoIN** [alexreinert/piVCCU#146]
Hi, leider startet der viccu-service nicht, da er die Datei mit der PID nicht findet.
Es handelt sich hierbei um eine komplett neue Installation.

Das Vorgehen aus #137  habe ich bereits versucht und hatte leider keinen Erfolg.

```
sudo systemctl status pivccu.service
● pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: enabled)
   Active: failed (Result: resources) since Wed 2019-03-27 10:29:05 GMT; 18s ago
  Process: 639 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, status=0/SUCCESS)
      CPU: 1.341s

Mar 27 10:28:28 raspberrypi start_container.sh[639]: <12>Mar 27 10:28:28 piVCCU3: HMIP hardware was not detected
Mar 27 10:28:29 raspberrypi start_container.sh[639]: kernel.sched_rt_runtime_us = -1
Mar 27 10:28:34 raspberrypi start_container.sh[639]: lxc-start: tools/lxc_start.c: main: 366 The container failed to start.
Mar 27 10:28:34 raspberrypi start_container.sh[639]: lxc-start: tools/lxc_start.c: main: 368 To get more details, run the container in foreground mode.
Mar 27 10:28:34 raspberrypi start_container.sh[639]: lxc-start: tools/lxc_start.c: main: 370 Additional information can be obtained by setting the --logfile and --logpriority options.
Mar 27 10:28:34 raspberrypi systemd[1]: pivccu.service: PID file /var/run/pivccu3.pid not readable (yet?) after start: No such file or directory
Mar 27 10:29:05 raspberrypi systemd[1]: pivccu.service: Daemon never wrote its PID file. Failing.
Mar 27 10:29:05 raspberrypi systemd[1]: Failed to start piVCCU.
Mar 27 10:29:05 raspberrypi systemd[1]: pivccu.service: Unit entered failed state.
Mar 27 10:29:05 raspberrypi systemd[1]: pivccu.service: Failed with result 'resources'.
```

Die pivccu-info sieht wie folgt aus:
```
sudo pivccu-info 
piVCCU version: 3.43.16-20
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          STOPPED
```

Die Kernel version sollte eigentlich aus passen:
```
uname -a
Linux raspberrypi 4.14.98+ #1200 Tue Feb 12 20:11:02 GMT 2019 armv6l GNU/Linux
```

Vielen Dank schon mal im Vorhinein.
Gruß,

Simon

**Comment by alexreinert** [comment]
Welche Funkhardware wird verwendet? Weil da keine bei pivccu-info gefunden wird.

**Comment by ZiIMoIN** [comment]
Es wird das Funkmodul HM-MOD-RPI-PCB verwendet. Dies sollte auch ordnungsgemäß angeschlossen sein.

**Comment by alexreinert** [comment]
Die Erkennung des Funkmoduls funktioniert normallerweise sehr zuverlässig und es wird nicht erkannt. Bitte daher mal prüfen, ob das Funkmodul wirklich korrekt montiert ist und ob es wirklich funktionsfähig ist.
(z.B. mit einem fertigen piVCCU Image oder einem RaspberryMatic Image)

**Comment by ZiIMoIN** [comment]
Leider habe ich das ganze mit einem RaspberryPi Version 1 versucht, da ich fälschlicher meinte es wäre einer der Version 2. Mit einem anderen funktioniert es problemlos.
Vielen Dank für die Umsetzung dieses super Projekts.

**Comment by shred** [comment]
Ich hänge gerade an einer ähnlichen Stelle und komme nicht weiter. Tinkerboard S und RPI-RF-MOD, alles frisch zusammengebaut, das Armbian-Tinkerboard-CCU3-Image installiert, dann `apt update` und `apt upgrade` ausgeführt. Seitdem habe ich das gleiche Problem: pivccu startet nicht wegen `Module rpi_rf_mod_led not found in directory /lib/modules/4.19.69-rockchip`.

Ich habe die Schritte aus #137 ausgeführt. `dpkg-reconfigure pivccu-modules-dkms` scheitert 
allerdings:

```
Error! Your kernel headers for kernel 4.19.69-rockchip cannot be found.
Please install the linux-headers-4.19.69-rockchip package,
```

Ein Paket `linux-headers-4.19.69-rockchip` scheint es nicht zu geben, allerdings habe ich auch gar keine Erfahrung mit Armbian, vielleicht suche ich nur an der falschen Stelle.

Hast du eine Idee?

**Comment by shred** [comment]
Um die Frage selbst zu beantworten: In der Paketliste existiert nur `linux-headers-next-rockchip` in Version 5.68 für einen älteren Kernel.

Nachdem ich folgende Zeilen als root ausgeführt habe, geht es wieder:

```
wget https://apt.armbian.com/pool/main/l/linux-4.19.69-rockchip/linux-headers-next-rockchip_5.95_armhf.deb
dpkg -i linux-headers-next-rockchip_5.95_armhf.deb
dpkg-reconfigure pivccu-modules-dkms
reboot
```

Ob das der eleganteste Weg ist, sei dahingestellt. :wink:
