### ISSUE TITLE
Can I access HMIP AP via App 

### ISSUE THREAD

**Issue by olli0815** [alexreinert/piVCCU#149]
Hi Alex,

thanks a lot for the image!
I run it on C2 using HMIP-RFUSB, works fine.  
But I do have a question; is it possible to register the virtual HMIP instance as "ordinary" Access Point like a origin HM-IP AP to use the HM Mobile App, using the SGTIN number form the instance?

**Comment by alexreinert** [comment]
The official HmIP app does only support the HmIP Access Point.
If you use any CCU solution, you cannot use the app. But there are several other apps using the CCU as backend.
