### ISSUE TITLE
Support for LAN Gateway mode

### ISSUE THREAD

**Issue by M0ebiu5** [alexreinert/piVCCU#15]
Are there any plans to emulate a Homematic LAN Gateway?

**Comment by alexreinert** [comment]
https://homematic-forum.de/forum/viewtopic.php?f=69&t=40873

**Comment by M0ebiu5** [comment]
Thanks, but there is no conclusion...did you get the ok?

**Comment by alexreinert** [comment]
Not yet. But you can just install it by your own, the binaries are available there.

**Comment by alexreinert** [comment]
I did not get any answer by the author of the LAN GW code at all, so it seems, that he is not interessted in a cooperation.
