### ISSUE TITLE
Alle Bewegungsmelder HmIP-SMI 1x täglich Gerätekommunikation gestört

### ISSUE THREAD

**Issue by tomgreg0** [alexreinert/piVCCU#150]
Hallo, ich bin gerade erst am Einrichten meiner Homematic Komponenten mit einem Raspi3 mit RPI-RF-MOD, aber bei allen 3 meiner Bewegunsmelder HmIP-SMI (Firmware 1.4.8) bekomme ich min 1 mal am Tag gleichzeitig die Servicemeldung "Gerätekommunikation gestört" (getestet mit pivccu3 3.41.11 und 3.45.5). Meldung geht erst weg nach Neustart Homematic oder wenn man z.B. Sabotagekontakt am Bewegungsmelder durch Öffnen des Batteriefachs auslöst. Alle anderen Komponenten laufen ohne Störung weiter.
Ich habe testweise einen davon an einem Raspi mit aktuellen Raspberrymatic angemeldet, dort kommen keine Störungen in der Kommunikation.
Hat jemand ähnliche Probleme?

**Comment by alexreinert** [comment]
Bitte mal mit der 3.45.7 testen, da gab es wohl einige Umbauten bzgl. einiger HmIP Geräte.

**Comment by tomgreg0** [comment]
Update auf 3.45.7 hat leider nichts gebracht, immer noch das gleiche Problem

**Comment by tomgreg0** [comment]
Nach löschen aller Bewegungsmelder und nochmals anlernen, scheint es jetzt zu funktionieren. Hatte ich zwar unter der 3.41.11 auch schon probiert, da hatte es nichts gebracht. Danke
