### ISSUE TITLE
Package pivccu3 is not available, but is referred to by another package.

### ISSUE THREAD

**Issue by DutchmanNL** [alexreinert/piVCCU#153]
sudo apt install pivccu3 returns error Package pivccu3 is not available, but is referred to by another package.

Also entwerfe source oder docu falsch ? :)

**Comment by alexreinert** [comment]
Ich würde sagen, weder das eine, noch das andere sind falsch, das zeigen die Download Logs ziemlich eindeutig.
Wie sieht die /etc/apt/sources.list.d/pivccu.list aus? Was ist die Ausgabe bei ```sudo apt update```?

**Comment by DutchmanNL** [comment]
> Wie sieht die /etc/apt/sources.list.d/pivccu.list aus?

`deb https://www.pivccu.de/piVCCU stable main
`
> Was ist die Ausgabe bei `sudo apt update`

`Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease     
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease       
Hit:4 https://www.pivccu.de/piVCCU stable InRelease                     
Hit:5 http://archive.ubuntu.com/ubuntu bionic-security InRelease        
Reading package lists... Done `

**Comment by alexreinert** [comment]
Ubuntu? Ist das ein x64 System?

**Comment by DutchmanNL** [comment]
> Ubuntu? Ist das ein x64 System?

correct 

`Linux vm_master 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by alexreinert** [comment]
Zitat aus dem Readme:

> Prequisites
> Debian or Ubuntu based distribution
> armhf or arm64 architecture (x64 is not supported right now)
> At least kernel 4.14

Es dürfte also klar sein, warum das nicht geht, oder?

**Comment by DutchmanNL** [comment]
> Es dürfte also klar sein, warum das nicht geht, oder?

wer lesen kan ist klar im Vorteil, ja eindeutig sorry
