### ISSUE TITLE
Laufwerk in CCU3 einbinden

### ISSUE THREAD

**Issue by Siggi0904** [alexreinert/piVCCU#154]
Hallo,

ich habe einen Ordner meines NAS unter /media/nas als cifs gemountet.

Ist die Einbindung als USB-Laufwerk im CCU3 bzw. pivccu3 möglich?
Was wäre alternativ eine Lösung um die Daten zentral zu speichern?

Edit:
Ich habe nun auch einen USB Stick eingebunden und dem Verzeichnis /media/usb gemountet.
Muss der Stick speziell formatiert sein, aktuell als vfat (Fat32) formatiert.
Bei Aufruf von `sudo dpkg-reconfigure pivccu3` wird keine USB-Auswahl angezeigt/ausgeführt.

Danke.

**Comment by alexreinert** [comment]
Siehe https://homematic-forum.de/forum/viewtopic.php?f=69&t=41819&start=20#p504074
