### ISSUE TITLE
synology docker support

### ISSUE THREAD

**Issue by mainkowitsch** [alexreinert/piVCCU#155]
Hi,

wird es in naher Zukunft möglich sein pivccu3 auch in einem Docker auf einer Synology Diskstation laufen zu lassen? 
DS218+ mit intel CPU in meinem Fall.

Danke.

**Comment by alexreinert** [comment]
Nein. piVCCU basiert auf der Original CCU Fimware und unterstützt daher nur arm Hardware, damit kann es nicht auf Intel CPUs laufen.
