### ISSUE TITLE
Rock64 Image USB Devices are not powered

### ISSUE THREAD

**Issue by lwalpurgis** [alexreinert/piVCCU#156]
Hi Alex,
Thanks for adding the image for the Rock64, which works wunderful with HM-MOD-PCB, also IOBroker works good, but when I add USB Devices (USB-Stick, CUL...) they are not powered and no leds are on and I can't use my Cul... They are also not seen in fdisk... What has to be done to get the USB-Devices in the System? Is there something special with the dev-Kernel? On other Images, USB-Devices are working.
Thanks!
Lars

**Comment by alexreinert** [comment]
Does this problem still occur using the lastest kernel package (Update can be done using apt)

**Comment by lwalpurgis** [comment]
Hi Alex,
I have done the update, but there is already Version 4.20.0-rockchip64 installed and USB-Devices are still not powered. What can I do?
Thanks for help!

**Comment by lwalpurgis** [comment]
Hi Alex,
Ich bin ein Stück weiter gekommen, bei dem alten Image des Rock64 mit pivccu3 [https://www.pivccu.de/images/?dir=piVCCU3/old](url) werden die USB-Anschlüsse mit Strom versogt, der CUL wird gemounted jedoch steht dann in CUxD bei korrekter Konfiguration "no driver" und der nanoCUL wird nicht erkannt. Das Problem habe ich hier genauer beschrieben:
[https://homematic-forum.de/forum/viewtopic.php?f=37&t=51461](url)

Ich bitte um Hilfe!
Dankeschön!
![Rock64PIVCCU](https://user-images.githubusercontent.com/10418543/60383752-5f2ac380-9a75-11e9-9fdd-24e144b175be.JPG)
