### ISSUE TITLE
Raspbian fährt nur manchmal mit funktionierten Netzwerk hoch

### ISSUE THREAD

**Issue by Alveran81** [alexreinert/piVCCU#158]
Hallo,
ich habe mit dem neuesten pivccu3 Image meinen neuen Raspberry 3B+ bespielt.
Danach mit sudo apt-get update und apt-get upgrade alles auf neuesten Stand gebracht. 

Dann mein pivccu Backup über das Homematic Webinterface wieder eingespielt.

Seit dem wieder einspielen des Backups ist es ein Glückspiel ob der Raspberry bei einem neustart sauber hochfährt. 
Konkret fährt er ohne funktionierende Netzwerkverbindung hoch. 
Meldung: **a start job is running for raise network interfaces**

Meine interfaces sehen so aus:
`source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback

iface eth0 inet manual

auto br0
iface br0 inet dhcp
  bridge_ports eth0
`

**Comment by alexreinert** [comment]
Bitte nicht mit apt-get, sondern mit apt arbeiten. apt-get hält gerne mal Pakete zurück.
Ansonsten: Netzwerkkabel mal getauscht? Der 3B+ ist mit seiner GBit Schnittstelle manchmal etwas zickig bei der Aushandlung der Netzwerkgeschwindigkeit. Ggf. hilft auch das fixieren auf 100Mbit auf der Gegenseite.

**Comment by Alveran81** [comment]
Meinst du es liegt an der Aushandlung der Netzwerkgeschwindigkeit? Der Raspberry steckt direkt an meiner etwas älteren Fritz Box, die kann auch nur 100 Mbit. Werde aber mal direkt an meiner Gigabit Switch testen. Da könnte ich gegeben falls den Port fest einstellen.

**Comment by Alveran81** [comment]
Lag tatsächlich an der Aushandlung der Netzwerkgeschwindigkeit.
