### ISSUE TITLE
ubuntu 19

### ISSUE THREAD

**Issue by Goersch** [alexreinert/piVCCU#159]
Hab da leider ein Problem beim übersetzen 

`make -j4 KERNELRELEASE=5.0.0-13-generic ARCH=x86 all...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.0.0-13-generic (x86_64)
Consult /var/lib/dkms/pivccu/1.0.27/build/make.log for more information.
`

Vielleicht kann jemand helfen?

Danke!
Georg

[make.log](https://github.com/alexreinert/piVCCU/files/3132257/make.log)

**Comment by Goersch** [comment]
hab ein bisschen gegoogelt - der Aufruf des macros access_ok hat sich mit Kernel 5 geändert:

#define access_ok(addr, size) __access_ok((unsigned long)(addr), size)

anstatt

#define access_ok(type, addr, size) ({ (void)(type); __access_ok((unsigned long)(addr), size); })

**Comment by alexreinert** [comment]
An Kernel 5.0 arbeite ich noch.
Aber unabhängig davon: x86 wird generell nicht unterstützt.

**Comment by Goersch** [comment]
Ok, danke. Bzgl.  x86 habe ich wohl was falsch verstanden.

**Comment by alexreinert** [comment]
Kernel 5 Support ist jetzt vorhanden.
