### ISSUE TITLE
Migration from YAHM - Step vii

### ISSUE THREAD

**Issue by ecdlguy** [alexreinert/piVCCU#16]
Hi,

I feel unsure what to do while migrating from YAHM to piVCCU:

> If you used YAHM **with without** HmIP (and only then), remove the HmIP keys to avoid migrating duplicate keys (this needs to done, even if you used a new sd card image and after every restore of a YAHM backup) 

cheers,
Thorsten

**Comment by alexreinert** [comment]
Yes, bad typo.

If you used YAHM without HmIP...

**Comment by alexreinert** [comment]
Fixed in Readme

**Comment by ecdlguy** [comment]
Ok, thanks for clarification!
