### ISSUE TITLE
Cannot update CCU2 from v2.31.25-21 to v2.45.7

### ISSUE THREAD

**Issue by clanganke** [alexreinert/piVCCU#160]
Hi Alex, great project, many thanx and kudos for the great work!

I just tried to update to CCU2 v2.45.7, as the current version 2.31.25-21 I use shows that it is available. Your readme says

### **Updating piVCCU to latest version**

Use the normal apt based update mechanism:

`sudo apt update && sudo apt upgrade`

unfortunately, when I do this, pviccu remains at version 2.31.25-21.

What would be the correct way to update ?

TIA Chris

**Comment by alexreinert** [comment]
Please provide the output of the commands.

**Comment by clanganke** [comment]
Hi again, here is the output of the following commands

**dpkg --list | grep pivccu**
[000_dpgk.txt](https://github.com/alexreinert/piVCCU/files/3168974/000_dpgk.txt)

**sudo apt-get -y update**
[001_apt_get_update.txt](https://github.com/alexreinert/piVCCU/files/3168976/001_apt_get_update.txt)

**sudo apt-get -y upgrade**
[002_apt_get_upgrade.txt](https://github.com/alexreinert/piVCCU/files/3168978/002_apt_get_upgrade.txt)

**dpkg --list | grep pivccu**
[003_dpgk.txt](https://github.com/alexreinert/piVCCU/files/3168979/003_dpgk.txt)

TIA, Chris

**Comment by alexreinert** [comment]
Please use apt instead of apt-get as written in the documentation.

**Comment by clanganke** [comment]
Yes, that made a difference, sorry, didn't know that... the update just worked fine this way!

Until now I didn't dare to use apt in favor of apt-get in my upgrade scripts due to the warning of apt:

> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

However, if only apt gets all updates, there is no choice. And at least in this case it worked with no problem in my updated script.

As a difference to the old version, the new firmware represents the physical **HM-MOD-RPI-PCB** board not only in a **HM-RCV-50 BidCoS-RF** device, like the old firmware dird. Now there is another one, **HmIP-RCV-50 61A7D7098E1EFA**, where the hex number seems to represent the serial number of the hardware, as it has the same length as the serial number of the controlled HmIP device.

Is that a known behaviour ?

TIA Chris

**Comment by alexreinert** [comment]
apt-get gets all updates, but it has a very defensive way of handling changed dependencies and hold that packages back. apt handles changed dependecies a little bit smother.

The HmIP-RCV-50 is a new feature of the 3.45.x firmware (not only piVCCU).

**Comment by clanganke** [comment]
Thnx for the support!
