### ISSUE TITLE
compiling kernel modules error

### ISSUE THREAD

**Issue by JimKnopf1503** [alexreinert/piVCCU#161]
sudo apt install --reinstall pivccu-modules-raspberrypi pivccu-modules-dkms

gives me following Log:
KMS make.log for pivccu-1.0.28 for kernel 4.9.35-v7+ (armv7l)
Di 21. Mai 19:29:11 CEST 2019
make -C /lib/modules/4.9.35-v7+/build M=/var/lib/dkms/pivccu/1.0.28/build modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.35-v7+'
  CC [M]  /var/lib/dkms/pivccu/1.0.28/build/eq3_char_loop.o
  CC [M]  /var/lib/dkms/pivccu/1.0.28/build/plat_eq3ccu2.o
  CC [M]  /var/lib/dkms/pivccu/1.0.28/build/generic_raw_uart.o
/var/lib/dkms/pivccu/1.0.28/build/generic_raw_uart.c: In function \u2018generic_raw_uart_get_gpio_pin_number\u2019:
/var/lib/dkms/pivccu/1.0.28/build/generic_raw_uart.c:726:12: error: implicit declaration of function \u2018dev_fwnode\u2019 [-Werror=implicit-function-declaration]
     struct fwnode_handle *fwnode = dev_fwnode(dev);
            ^
/var/lib/dkms/pivccu/1.0.28/build/generic_raw_uart.c:726:36: warning: initialization makes pointer from integer without a cast
     struct fwnode_handle *fwnode = dev_fwnode(dev);
                                    ^
cc1: some warnings being treated as errors
scripts/Makefile.build:299: recipe for target '/var/lib/dkms/pivccu/1.0.28/build/generic_raw_uart.o' failed
make[2]: *** [/var/lib/dkms/pivccu/1.0.28/build/generic_raw_uart.o] Error 1
Makefile:1490: recipe for target '_module_/var/lib/dkms/pivccu/1.0.28/build' failed
make[1]: *** [_module_/var/lib/dkms/pivccu/1.0.28/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.35-v7+'
Makefile:23: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JimKnopf1503** [comment]
Bin für Hilfe an der Stelle sehr dankbar.
Gruß,
Burkhard

**Comment by alexreinert** [comment]
Im Readme: Mind. Kernel 4.14, du hast Kernel 4.9 (vermutlich den Raspbian Jessie Kernel)

**Comment by JimKnopf1503** [comment]
Danke für die schnelle Antwort, dann habe ich die Kernelversionen falsch interpretiert, ich dachte da 4.9 höher ist als 4.14 würde das gehen. Ich mache gerade das Update auf Stretch.
Danke für die Info.
Gruß,
Burkhard

**Comment by JimKnopf1503** [comment]
Nach update auf Stretch ist alles fein. Danke!!!
Gruß,
Burkhard
