### ISSUE TITLE
Support for Raspberry Pi 4

### ISSUE THREAD

**Issue by alexreinert** [alexreinert/piVCCU#166]

**Comment by klepptor** [comment]
Great News!

Will you provide a raspbian buster image containing pivccu3 as well? PLEASE! ;)

**Comment by Semesch** [comment]
Hallo,

läuft die aktuelle Firmware version 2.47.12 bzw. 2.45.7 schon auf dem Pi4?

**Comment by alexreinert** [comment]
> läuft die aktuelle Firmware version 2.47.12 bzw. 2.45.7 schon auf dem Pi4?

Offiziell noch nicht, ich bin hier noch am testen. Unter https://www.pivccu.de/images/?dir=piVCCU3/testing gibt es aber ein Image, bei welchem das schon recht gut aussieht.

**Comment by Semesch** [comment]
Wie ich gesehen hab, hast du etwas geändert. Heißt das jetzt das Pi4 läuft?
Wenn ja, einfach auf dem 3b+ updaten/upgraden und dann kann ich die sd Karte einfach per plug und play  laufen lassen?

**Comment by alexreinert** [comment]
Idealerweise erstmal ein Backup Image der SD machen.
Update von piVCCU und Upgrade auf Raspbian Buster (inkl. Upgrade auf den Buster Kernel). Danach kann die SD Karte auf in den 4er gesteckt werden.
Falls das RPI-RF-MOD genutzt wird, braucht es noch einen Stacking Header, weil das Modul physikalisch nicht aufgesteckt werden kann, weil die Netzwerkbuchse durch die neue Position im Weg ist.
