### ISSUE TITLE
Can´t pair HmIP-RFUSB with HmIP-eTRV-2 (radiator)

### ISSUE THREAD

**Issue by Darkentik** [alexreinert/piVCCU#169]
Hi,
ich habe Proxmox-VE laufen und in einer Debian VM debmatic und IOBroker installiert.
Der USB Stick ist erfolgreich an die VM durchgereicht und ich sehe ihn als CCU in meiner Homematic WebUI.
Jetzt habe ich das Thermostat eingeschaltet und die Adaptierung am Heizkörper fahren lassen.
Bei einer ersten Testinstallation mit einem alten Laptop+Debmatic Ende letzten Jahres haben sich die Geräte irgendwie pairen lassen. Da habe ich das manuelle Anlernen mit KEY+SGTIN benutzt.
Ein manuelles pairen über "Gerät anlernen ohne Internet" mit dem Key und der SGTIN funktioniert scheinbar nicht, da nichts im Posteingang ankommt und ich nirgends das Thermostat finde.

Habt ihr irgendwelche Tipps?

**Comment by alexreinert** [comment]
Hi,

falsches Github Projekt. ;-)

Wenn ein HmIP Gerät gepairt war, kann man es erst wieder pairen, wenn man vorher einen Werksreset gemacht hat.
Handelt es sich bei dem HmIP-eTRV-2 oder bei dem HmIP-RFUSB um ein Telekom Gerät?

**Comment by Darkentik** [comment]
Argh, verdammt. Ich war im falschen Tab. Sry, das war natürlich zum Projekt "Debmatic".
Sind beides freie Geräte von ELV gekauft.

**Comment by alexreinert** [comment]
> Der Tipp war aber Gold wert.

Also hat es damit geklappt?

**Comment by alexreinert** [comment]
Nachdem keine Rückmeldung kommt, gehe ich jetzt einfach mal davon aus, dass das Problem gelöst ist. Falls nicht, bitte wieder aufmachen.
