### ISSUE TITLE
Docker PI4

### ISSUE THREAD

**Issue by MobiusOne91** [alexreinert/piVCCU#170]
Hi

danke für deine Arbeit! Ich habe derzeit eine separaten RPI3 für pivccu laufen. Auf meinem RPI4 verwende ich für alle Dienste Docker. Wäre es möglich, dies auch in Docker auf dem RPI4 zu verwenden?

Vielen Dank!

**Comment by alexreinert** [comment]
Nein, Docker wird nicht unterstützt und kann auch nicht ohne Weiteres unterstützt werden, weil man innerhalb eines Docker Containers diverse Rechte nicht hat, welche allerdings notwendig sind um die Funkhardware anzusprechen. (vor allem, die fehlende Möglichkeit Kernel Module zu laden)
