### ISSUE TITLE
bekomme piVCCU3 auf Raspberry Pi Model B Rev 2 nicht zum laufen

### ISSUE THREAD

**Issue by dave-castle** [alexreinert/piVCCU#172]
Hallo,

ich versuche nun seit zwei Tagen die piVCCU3 mit HM-MOD-RPI-PCB auf einem Raspberry Pi Model B Rev 2 zum Laufen zu bringen, nachdem ich [hier](https://github.com/alexreinert/piVCCU/issues/120) gelesen habe das dies möglich sei.
Ich hatte das Modul vorher auf einem RaspberryPi3 problemlos am laufen, würde diesen aber gerne anderweitig verwenden und wollte auf den Rasp1 umziehen. piVCCU2 lief auch problemlos, gibt es ansonsten eine Möglichkeit das Backup einer cc3 auf eine ccu2 zu bekommen!?

Habe das fertige Image gezogen Raspbian_Buster_Liste_piVCCU3_2019-07-11 sowie die beiden alten Raspbian Stretch Images. 

Bei beiden erhalte ich leider mit `sudo pivccu-info` folgende Info:

> piVCCU version: 3.41.11-15
> Kernel modules: Available
> Raw UART dev:   Available
> HMRF Hardware:  unknown
> HMIP Hardware:  unknown
> Board serial:   unknown
> Radio MAC:      unknown
> SGTIN:          unknown
> State:          STOPPED

**Comment by alexreinert** [comment]
Was den nun? Raspberry 1 oder 2?

**Comment by dave-castle** [comment]
Raspberry Pi Model B Rev 2

**Comment by alexreinert** [comment]
Gut, also ein 1er. Der wird nicht unterstützt. Unterstützt werden der 2B, 3B, 3B+ und 4B.

**Comment by dave-castle** [comment]
schade, habe ich die Möglichkeit irgendwie ein backup aus der ccu3 in die ccu2 zu bekommen?

**Comment by alexreinert** [comment]
Nicht das ich wüsste.

**Comment by dave-castle** [comment]
danke trotzdem!
