### ISSUE TITLE
Homematic IP devices no longer working

### ISSUE THREAD

**Issue by reichert1** [alexreinert/piVCCU#173]
Hi -  

good news first: besides one Homematic IP device that I have (HMIP-SLO light intensity sensor) everything else (around 20 classic devices) is working just fine.

I made two changes to my system after which issues surfaced. I reverted the changes but no difference:
a) installed deconz and had a zigbee stick plugged in on my Pi - uninstalled and removed in the mean time
b) added CCU2 device as a LANGateway - unplugged but issues remained 

Also recent upgrades of pivccu to latest versions didn't improve my situation.

**Issues:**

#1 it's odd, pivccu-info states hardware unknown (although using Pi - HM-MOD-RPI-PCB on PI 3) see result of pivccu-info - is that normal?

`
pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 2.47.15-52
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Not assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          RUNNING
PID:            1031
IP:             192.168.1.52
IP:             2a02:908:1d7:ec00:48ca:a4ff:fe09:6a45
CPU use:        801.64 seconds
BlkIO use:      34.26 MiB
Memory use:     95.78 MiB
KMem use:       3.58 MiB
Link:           vethpivccu
 TX bytes:      93.48 MiB
 RX bytes:      107.03 MiB
 Total bytes:   200.50 MiB
`

**#2 more important** - I would like to have the option to use IP devices again. Homematic also starts up super slow and throws up error msg in WebGUI (Eine Komponente der Homematic Zentrale reagiert nicht mehr//HMIm-RF not working). 
There is also no longer the option to teach in IP devices. 

I have looked into various log files but no real smoking gun (to me as a beginner ;( ).
 **Any hot tip for the log files or ideas what I can do? (worst case I need to do a complete re-install which I would like to avoid).**

messages log contains some errors, not sure whether they are relevant (cause or effect?) and what to do to fix it? 

`pi@raspberrypi:~ $ sudo pivccu-attach cat /var/log/messages
Aug  2 15:32:57 homematic-ccu2 syslog.info syslogd started: BusyBox v1.20.2
Aug  2 15:32:57 homematic-ccu2 user.notice kernel: klogd started: BusyBox v1.20.2 (2019-07-17 11:01:13 CEST)
Aug  2 17:32:57 homematic-ccu2 syslog.info syslogd started: BusyBox v1.20.2
Aug  2 17:32:57 homematic-ccu2 user.notice kernel: klogd started: BusyBox v1.20.2 (2019-07-17 11:01:13 CEST)
Aug  2 15:32:58 homematic-ccu2 daemon.info ifplugd(eth0)[197]: ifplugd 0.28 initializing.
Aug  2 15:32:58 homematic-ccu2 daemon.info ifplugd(eth0)[197]: Using interface eth0/4A:CA:A4:09:6A:45 with driver <veth> (version: 1.0)
Aug  2 15:32:58 homematic-ccu2 daemon.info ifplugd(eth0)[197]: Using detection mode: SIOCETHTOOL
Aug  2 15:32:58 homematic-ccu2 daemon.info ifplugd(eth0)[197]: Initialization complete, link beat detected.
Aug  2 15:32:58 homematic-ccu2 daemon.warn ifplugd(eth0)[197]: Could not open /dev/tty, cannot beep.
Aug  2 15:32:58 homematic-ccu2 daemon.info ifplugd(eth0)[197]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
Aug  2 15:32:58 homematic-ccu2 daemon.warn ifplugd(eth0)[197]: client: net.ipv4.tcp_timestamps = 0
Aug  2 15:32:58 homematic-ccu2 daemon.warn ifplugd(eth0)[197]: client: udhcpc (v1.20.2) started
Aug  2 17:32:58 homematic-ccu2 user.debug setclock: Try to get time from ntp.homematic.com
Aug  2 15:32:58 homematic-ccu2 daemon.warn ifplugd(eth0)[197]: client: Sending discover...
Aug  2 17:32:58 homematic-ccu2 user.debug setclock: Fri Aug 2 17:32:58 CEST 2019
Aug  2 15:32:58 homematic-ccu2 daemon.warn ifplugd(eth0)[197]: client: Sending select for 192.168.1.52...
Aug  2 15:32:58 homematic-ccu2 daemon.warn ifplugd(eth0)[197]: client: Lease of 192.168.1.52 obtained, lease time 864000
Aug  2 15:32:58 homematic-ccu2 daemon.warn ifplugd(eth0)[197]: client: rm: can't remove '/var/etc/resolv.conf': No such file or directory
Aug  2 15:32:58 homematic-ccu2 daemon.warn ifplugd(eth0)[197]: client: udhcpc (v1.20.2) started
Aug  2 15:32:58 homematic-ccu2 daemon.warn ifplugd(eth0)[197]: client: Sending discover...
Aug  2 15:32:59 homematic-ccu2 daemon.warn ifplugd(eth0)[197]: client: Sending select for 192.168.1.52...
Aug  2 15:32:59 homematic-ccu2 daemon.warn ifplugd(eth0)[197]: client: Lease of 192.168.1.52 obtained, lease time 864000
Aug  2 15:32:59 homematic-ccu2 daemon.info ifplugd(eth0)[197]: Program executed successfully.
Aug  2 15:33:03 homematic-ccu2 user.info logger: Updating RF Lan Gateway Coprocessor Firmware
Aug  2 15:33:03 homematic-ccu2 user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
Aug  2 15:33:03 homematic-ccu2 user.info update-coprocessor: performGatewayCoproUpdate(): updating HMLGW2
Aug  2 15:33:05 homematic-ccu2 user.err update-coprocessor: Could not find gateway by unicast with ip 192.168.1.46. Trying search by serial number.
Aug  2 15:33:07 homematic-ccu2 user.err update-coprocessor: Could not determine IP Address of Lan Gateway with serial number HMLGW2
Aug  2 15:33:07 homematic-ccu2 user.err update-coprocessor: Error reading network configuration.
Aug  2 15:33:15 homematic-ccu2 user.err update-coprocessor: Could not connect to Lan Gateway ip: .
Aug  2 15:33:15 homematic-ccu2 user.info logger: Updating RF Lan Gateway Firmware
Aug  2 15:33:15 homematic-ccu2 user.info update-lgw-firmware: LAN Gateway Firmware Update...
Aug  2 15:33:15 homematic-ccu2 user.info update-lgw-firmware: Gateway HMLGW2
Aug  2 15:33:17 homematic-ccu2 user.err update-lgw-firmware: Could not find gateway by unicast with ip 192.168.1.46. Trying search by serial number.
Aug  2 15:33:19 homematic-ccu2 user.err update-lgw-firmware: Could not determine IP Address of Lan Gateway with serial number HMLGW2
Aug  2 15:33:19 homematic-ccu2 user.info update-lgw-firmware: Gateway type is eQ3-HM-CCU2-App
Aug  2 15:33:19 homematic-ccu2 user.err update-lgw-firmware: Wrong type of gateway. Should be HMLGW2, but found 
Aug  2 15:33:19 homematic-ccu2 user.info logger: Updating Wired Lan Gateway Firmware
Aug  2 15:33:19 homematic-ccu2 user.info update-lgw-firmware: No gateway found in config file /etc/config/hs485d.conf
Aug  2 17:33:19 homematic-ccu2 user.info kernel: [   46.581949] eq3loop: created slave ttyS0
Aug  2 17:33:19 homematic-ccu2 user.info kernel: [   46.582376] eq3loop: created slave mmd_bidcos
Aug  2 15:33:24 homematic-ccu2 user.notice kernel: [   51.103945] random: 7 urandom warning(s) missed due to ratelimiting
Aug  2 17:33:24 homematic-ccu2 user.notice kernel: [   51.103932] random: crng init done
Aug  2 17:33:25 homematic-ccu2 user.err multimac: No Coprocessor detected!!! 
Aug  2 17:33:25 homematic-ccu2 user.info kernel: [   52.584366] eq3loop: eq3loop_close_master() mmd_bidcos destroy device
Aug  2 17:33:25 homematic-ccu2 user.info kernel: [   52.584652] eq3loop: eq3loop_close_master() ttyS0 destroy device
Aug  2 15:33:25 homematic-ccu2 user.info kernel: [   52.584353] eq3loop: eq3loop_close_master() mmd_bidcos
Aug  2 15:33:25 homematic-ccu2 user.info kernel: [   52.584646] eq3loop: eq3loop_close_master() ttyS0
Aug  2 17:33:26 homematic-ccu2 user.err rfd: CCU2CommController::improvedInit() - Identify response string not handled: 
Aug  2 17:33:26 homematic-ccu2 user.info kernel: [   52.714927] eq3loop: eq3loop_open_slave() mmd_bidcos
Aug  2 17:33:31 homematic-ccu2 user.err rfd: () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
Aug  2 17:33:52 homematic-ccu2 user.info kernel: [   78.999084] eq3loop: eq3loop_open_slave() ttyS0
Aug  2 17:33:58 homematic-ccu2 user.debug setclock: Try to get time from ntp.homematic.com
Aug  2 17:33:58 homematic-ccu2 user.debug setclock: Fri Aug 2 17:33:58 CEST 2019
Aug  2 17:43:46 homematic-ccu2 local0.err ReGaHss: ERROR: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [error():iseXmlRpc.h:281]
Aug  2 17:43:46 homematic-ccu2 local0.warn ReGaHss: WARNING: XMLRPC 'init': rpcClient.execute() failed (url: xmlrpc://127.0.0.1:9292/groups, params: {"xmlrpc_bin://127.0.0.1:1999","1008"}, result: nil) [CallXmlrpcMethod():iseXmlRpc.cpp:2602]
Aug  2 17:43:46 homematic-ccu2 local0.err ReGaHss: ERROR: XMLRPC 'init' call failed (interface: 1008, params: {"xmlrpc_bin://127.0.0.1:1999","1008"}) [CallInit():iseXmlRpc.cpp:1204]
Aug  2 17:43:46 homematic-ccu2 local0.err ReGaHss: ERROR: failed CallInit() for interface=VirtualDevices [ThreadFunction():iseRTHss.cpp:163]
Aug  2 17:43:46 homematic-ccu2 local0.err ReGaHss: ERROR: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [error():iseXmlRpc.h:281]
Aug  2 17:43:46 homematic-ccu2 local0.warn ReGaHss: WARNING: XMLRPC 'init': rpcClient.execute() failed (url: xmlrpc://127.0.0.1:2010, params: {"xmlrpc_bin://127.0.0.1:1999","1009"}, result: nil) [CallXmlrpcMethod():iseXmlRpc.cpp:2602]
Aug  2 17:43:46 homematic-ccu2 local0.err ReGaHss: ERROR: XMLRPC 'init' call failed (interface: 1009, params: {"xmlrpc_bin://127.0.0.1:1999","1009"}) [CallInit():iseXmlRpc.cpp:1204]
Aug  2 17:43:46 homematic-ccu2 local0.err ReGaHss: ERROR: failed CallInit() for interface=HmIP-RF [ThreadFunction():iseRTHss.cpp:163]
Aug  2 17:43:47 homematic-ccu2 local0.err ReGaHss: ERROR: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [error():iseXmlRpc.h:281]
Aug  2 17:43:47 homematic-ccu2 local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.execute() failed (url: xmlrpc://127.0.0.1:2010, params: {"000D58A9915C44:1","AVERAGE_ILLUMINATION"}, result: nil) [CallXmlrpcMethod():iseXmlRpc.cpp:2602]
Aug  2 17:43:47 homematic-ccu2 local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1009, params: {"000D58A9915C44:1","AVERAGE_ILLUMINATION"}) [CallGetValue():iseXmlRpc.cpp:1435]
Aug  2 17:43:47 homematic-ccu2 local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Aug  2 18:01:20 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  2 18:33:39 homematic-ccu2 user.err rfd: HSSParameter::GetValue() id=DECISION_VALUE failed getting physical value.
Aug  2 18:33:39 homematic-ccu2 user.err rfd: HSSParameter::GetValue() id=DECISION_VALUE failed getting physical value.
Aug  2 18:33:39 homematic-ccu2 user.err rfd: HSSParameter::GetValue() id=DECISION_VALUE failed getting physical value.
Aug  2 18:33:39 homematic-ccu2 local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: xmlrpc_bin://127.0.0.1:2001, params: {"OEQ0578069:7","DECISION_VALUE"}, result: [faultCode:-1,faultString:"Failure"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Aug  2 18:33:39 homematic-ccu2 local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"OEQ0578069:7","DECISION_VALUE"}) [CallGetValue():iseXmlRpc.cpp:1435]
Aug  2 18:33:39 homematic-ccu2 local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.cpp:124]
Aug  2 23:39:13 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  3 01:17:06 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  3 02:23:48 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  3 02:37:10 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  3 03:35:24 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  3 04:00:01 homematic-ccu2 cron.info crond[127]: crond: USER root pid 12191 cmd /usr/sbin/logrotate -f /etc/logrotate.conf || logger -p error -t "logrotate" "logrotate aborted with error $?"
Aug  3 04:12:01 homematic-ccu2 cron.info crond[127]: crond: USER root pid 12430 cmd /bin/setHWClock.sh
Aug  3 04:14:01 homematic-ccu2 cron.info crond[127]: crond: USER root pid 12473 cmd /bin/SetInterfaceClock
Aug  3 05:26:54 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  3 06:11:31 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  3 06:58:23 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  3 11:27:16 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  3 14:05:50 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  3 14:30:40 homematic-ccu2 user.err rfd: CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
Aug  3 16:50:18 homematic-ccu2 local0.err ReGaHss: ERROR: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [error():iseXmlRpc.h:281]
Aug  3 16:50:18 homematic-ccu2 local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.execute() failed (url: xmlrpc://127.0.0.1:2010, params: {"000D58A9915C44:1","CURRENT_ILLUMINATION"}, result: nil) [CallXmlrpcMethod():iseXmlRpc.cpp:2602]
Aug  3 16:50:18 homematic-ccu2 local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1009, params: {"000D58A9915C44:1","CURRENT_ILLUMINATION"}) [CallGetValue():iseXmlRpc.cpp:1435]
Aug  3 16:50:18 homematic-ccu2 local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Aug  3 16:50:18 homematic-ccu2 local0.err ReGaHss: ERROR: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [error():iseXmlRpc.h:281]
Aug  3 16:50:18 homematic-ccu2 local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.execute() failed (url: xmlrpc://127.0.0.1:2010, params: {"000D58A9915C44:1","LOWEST_ILLUMINATION"}, result: nil) [CallXmlrpcMethod():iseXmlRpc.cpp:2602]
Aug  3 16:50:18 homematic-ccu2 local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1009, params: {"000D58A9915C44:1","LOWEST_ILLUMINATION"}) [CallGetValue():iseXmlRpc.cpp:1435]
Aug  3 16:50:18 homematic-ccu2 local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Aug  3 16:50:18 homematic-ccu2 local0.err ReGaHss: ERROR: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [error():iseXmlRpc.h:281]
Aug  3 16:50:18 homematic-ccu2 local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.execute() failed (url: xmlrpc://127.0.0.1:2010, params: {"000D58A9915C44:1","HIGHEST_ILLUMINATION"}, result: nil) [CallXmlrpcMethod():iseXmlRpc.cpp:2602]
Aug  3 16:50:18 homematic-ccu2 local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1009, params: {"000D58A9915C44:1","HIGHEST_ILLUMINATION"}) [CallGetValue():iseXmlRpc.cpp:1435]
Aug  3 16:50:18 homematic-ccu2 local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
pi@raspberrypi:~ $ 
`

sudo pivccu-attach cat /var/log/hmserver.log   extract only:

`Aug 3 17:16:19 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-5] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Aug 3 17:16:26 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: long-lasting deployment, check deployment configuration - currently deployed 17 out of 22 
Aug 3 17:16:26 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [legacy.api.worker][connector.open]) 
Aug 3 17:16:26 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-7] SYSTEM ADVICE: pre-conditions for deployment of LegacyAPIWorker still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Aug 3 17:16:26 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-5] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Aug 3 17:16:26 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-6] SYSTEM ADVICE: pre-conditions for deployment of LegacyNotificationHandler still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Aug 3 17:16:26 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-4] SYSTEM ADVICE: pre-conditions for deployment of LegacyBackendNotificationHandler still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
`

Thank you for any help! 
Kurt

**Comment by alexreinert** [comment]
```Rasp.Pi3 UART: Not assigned to GPIO```

This means, that the (Hardware) UART of the Raspberry is not assigned to the GPIO pins, instead it is assigned to the bluetooth module.
Because of that, the Homematic radio module is not detected.

To fix this, see step 5 of the Raspberry Pi installation instructions and reboot your system.

**Comment by reichert1** [comment]
Super - that was it. Thank you so much!!! (should have asked directly and not wasted hours to trouble shoot myself :) )

So the Zigbee stick (Conbee) during install added the following line into /boot/config.txt
# for conbee2
enable_uart=1                                                             
dtoverlay=pi3-miniuart-bt-overlay

So even after uninstalling deconz it still caused the issues because of that.

Now that I understand that, I need to see how I can get both, Conbee and Pivccu to coexist on one Pi device. 
Unless someone tried that already and advises strongly against it ... Happy to take any recommendation! 

Kurt
