### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by real-easy** [alexreinert/piVCCU#174]
hallo,

nachdem ich nun alle meine ccu´s aktualisiert habe, bin ich auf dein problemchen gestoßen.
ich habe 2x pi mit pivccu (ccu3) und eine richtige ccu2.
alle nun mit der aktuellen version 3.47.15 (bzw 2.47.15 für die ccu2).

zusätzlich habe ich noch ein pihole laufen der den dns-zugriff NUR auf das lokale netz beschränkt.
nach dem alle ccu´s aktualisiert waren, habe ich sowohl den raspi´s als auch den virtuellen ccu´s und der realen ccu, die pihole-ip als dns eingetragen.
damit sind sie quasi für das dns nicht mehr im i-net, aber lokal erreichbar.

im log vom pihole sind nun viele anfragen von den virtuellen ccu´s zur adresse "goole.com".
ca 1-3 pro minute von jeder der vituellen ccu´s.
von der realen ccu kommt diese anfrage nicht.

außerdem tauchte zyklisch noch eine zweite geblockte adrese auf "hmgtw.homematic.com".
sobald diese adresse geblockt wird, dauert der start sehr lange.
danach ist das fenster der allemeinen einstellungen in der systemsteuerung nicht zu öffnen.

ich habe dann den mediola-kram deinstalliert, damit war diese anfrage nicht mehr zu sehen.
auch der start ging wieder schneller und das fenster allgemeine einstellungen ging wieder.
damit kann ich gut leben.

die anfrage zu "google.com" ist jedoch immer noch vorhanden.
es ist bisher zwar keine verzögeurng zu erkennen, aber evtl könnte man diese abfrage ja auch irgendwie deaktivieren.
das stört im log und dem pi würde es sicher auch gefallen.

ich habe nun zum weiteren test noch eine dritte virtuelle ccu aufgesetzt.
hier sind keine geräte angelernt.
trotz des blockens geht der start auch mit dem mediola hier zügig, und die anfrage nach hmgtw.homematic tauch hier nicht auf.

dafür aber eine andere überraschung, das hier "s3-eu-west-1.amazonaws.com".
der cloudspeicher von amazon, das ist überhaupt nicht gut.

es ist mir sicher bewust das dies die original firmware von homematic ist die im pivccu läuft.
aber evtl. kann mir jemand dieses verhalten bestätigen oder hat andere lösungen. (die ccu mit goolge reden zu lassen ist keine!)
der support von homematic ist ja nicht für lösungen bekannt.

danke schon mal im vorraus.
easy

**Comment by alexreinert** [comment]
Wie du selbst bereits geschrieben hast, piVCCU basiert auf der CCU Firmware. Ich habe bewusst so wenig wie möglich Änderungen eingebaut und das ist einer der Punkte, der von den Nutzern sehr geschätzt wird. Es braucht daher gute Gründe für eine Anpassung und ein einfaches "Mag ich nicht", wird dafür nicht reichen.
Die Abfragen zu Google kommen von der Internet-Prüfung, diese pingt regelmäßig Google an, das "mit Google reden" ist daher relativ zu sehen.
hmgtw.homematic.com habe ich bisher noch nie gesehen, diese kann auch gar nicht aufgelöst werden. Kann es sein, dass du das mit secgtw.homematic.com verwechselst? Das ist der Keyserver für HmIP und der wird benötigt nach dem Einspielen eines Backups für das Rekeying von HmIP (dauert durchaus mal 1-2 Stunden nach dem Einspielen des Backups, je nach Anzahl der HmIP Geräten und dem DC) und beim Anlernen von HmIP Geräten über Internet. Im normalen Betrieb braucht es den nicht.
Amazon S3 dürfte von Mediola kommen, mindestens mal deren Updateprüfung läuft darüber.

**Comment by real-easy** [comment]
hallo, 

ja es war tatsächlich der secgtw.homematic.com. 
wenn er nur nach dem backup genraucht wird ist nun auch klar warum ich den dann nicht wieder gefunden habe. 
danke für die erklärung. 

ist nur merkwürdig warum die richtige ccu2 das internet nicht so prüft, soll aber auch egal sein. 
reden oder nicht meine ip landet so zyklisch bei google, das muss ja nun wirklich nicht sein. 
(nein ich benutze keinen chrome ich benutze iron von srware.net ) 

und nein das war kein wunsch einer änderung. 
war sicher die falsche ecke für den post, aber ich wusse das ich hier sofort eine fachlich geniale antwort bekomme. 
beim hm support hätte das sicher ewig gedauert. 

also besten dank dafür. 

beste grüße 
easy 




Von: "Alexander Reinert" <notifications@github.com> 
An: "alexreinert/piVCCU" <piVCCU@noreply.github.com> 
CC: "mail" <mail@easys-web.de>, "Author" <author@noreply.github.com> 
Gesendet: Freitag, 23. August 2019 15:04:14 
Betreff: Re: [alexreinert/piVCCU] google.com (#174) 



Wie du selbst bereits geschrieben hast, piVCCU basiert auf der CCU Firmware. Ich habe bewusst so wenig wie möglich Änderungen eingebaut und das ist einer der Punkte, der von den Nutzern sehr geschätzt wird. Es braucht daher gute Gründe für eine Anpassung und ein einfaches "Mag ich nicht", wird dafür nicht reichen. 
Die Abfragen zu Google kommen von der Internet-Prüfung, diese pingt regelmäßig Google an, das "mit Google reden" ist daher relativ zu sehen. 
hmgtw.homematic.com habe ich bisher noch nie gesehen, diese kann auch gar nicht aufgelöst werden. Kann es sein, dass du das mit secgtw.homematic.com verwechselst? Das ist der Keyserver für HmIP und der wird benötigt nach dem Einspielen eines Backups für das Rekeying von HmIP (dauert durchaus mal 1-2 Stunden nach dem Einspielen des Backups, je nach Anzahl der HmIP Geräten und dem DC) und beim Anlernen von HmIP Geräten über Internet. Im normalen Betrieb braucht es den nicht. 
Amazon S3 dürfte von Mediola kommen, mindestens mal deren Updateprüfung läuft darüber.
