### ISSUE TITLE
Einspielen von YAHM-Backup in piVCCU: "Es ist kein Coprozessor verfügbar."

### ISSUE THREAD

**Issue by Tutmanichtun** [alexreinert/piVCCU#175]
Hi,

ich bin heute (bzw. gestern ;) ) gezwungenermaßen von YAHM auf piVCCU umgestiegen. Die Einrichtung war ein Traum, aber beim Punkt e der Anleitung (Restore the system backup using the CCU web interface) hänge ich fest: wenn ich das aus dem YAHM-Container erstellte Backup der CCU (also per Weboberfläche erstellt) wieder per Weboberfläche einspielen möchte, bekomme ich diese Meldung:

Beim Einspielen des System-Backups ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut. Falls dieser Fehler wiederholt auftritt, wenden Sie sich mit der folgenden Fehlermeldung an den Kundenservice: Es ist kein Coprozessor verfügbar.

Ich habe versucht, das Backup zu entpacken und die Innereien händisch zu sezieren (umbenennen der *.sbk-Datei in *.zip, danach weiter mit Packprogrammen.) Das hat soweit auch funktioniert, als das ich die Änderungen durchführen konnte, aber entweder habe ich beim verpacken einen Fehler gemacht oder die Datei "signature" enthält eine Prüfsumme, die natürlich jetzt nicht mehr stimmt. Auf jeden Fall nimmt die Web-UI das Backup nicht an.
Frage: wie funktioniert Schritt e?

**Comment by alexreinert** [comment]
Ich vermute, dass das durch die nei eingeführte Prüfung der HmIP Einstellungen kmin der CCU Firmware kommt. Welche Version von YAHM und piVCCU sind/waren im Einsatz? Welche Funkhardware war bei YAHM im Einsatz, welche ist jetzt bei piVCCU im Einsatz? Könnte ich das SBK haben, um das bei mir mal nachzustellen?

**Comment by Tutmanichtun** [comment]
Die Hardware war in beiden Fällen dieselbe:
-Raspberry Pi 3B+
-Funkmodul HM-MOD-RPI-PCB

Software:
Raspbian Stretch, Kernel 4.14.34 (auf neuerem Kernel ließ sich YAHM nicht einrichten)
YAHM: 1.9
CCU-Firmware: 2.35.16 (das Image ist inzwischen leider nicht mehr zu bekommen)
piVCCU: 2.47.15-52

Das Backup kommt per Mail. ;)

**Comment by Tutmanichtun** [comment]
Ich habe jetzt auf einer zweiten SD-Karte wieder eine YAHM-Installation lauffähig, falls mir das Komplett-Backup weiterhilft...
Im Installationspfad des LXC-Containers liegt die gesuchte Dateistruktur ja ebenfalls vor (/var/lib/lxc/yahm/rootfs/usr/local/etc/config/ im Vergleich zu /var/lib/piVCCU/userfs/etc/config/). Ich könnte jetzt also das Full_Backup überspielen und die Dateien bearbeiten.

**Comment by alexreinert** [comment]
Ich vermute, es liegt an den fehlenden HmIP Einstellungen im Backup. Aber das ist aktuell nur eine Vermutung und noch nicht verifiziert.

**Comment by alexreinert** [comment]
Ich konnte das Backup sowohl in piVCCU als auch in piVCCU3 einspielen, wobei ich mir das System dann nicht im Detail anschauen konnte mangels Zugangsdaten für die WebUI.
Ich habe aber noch zwei Ideen: 
- Wurde die piVCCU Installation auf einem frischen Raspbian gemacht oder auf dem bisherigen YAHM System? Falls YAHM System, dann bitte mal auf einer frischen Raspbian Installation probieren.
- Kann es sein, dass beim ersten Einspielen des Backups das Funkmodul noch nicht aufgesteckt war? Dann bitte mal folgendes Versuchen: Systemreset der piVCCU Installation über die WebUI. Neustart des gesamten Pis. Mit ```sudo pivccu-info``` prüfen, ob das Funkmodul korrekt erkannt wurde. Backup erneut einspielen. Weitere Schritte aus Readme durchführen.

**Comment by Tutmanichtun** [comment]
So, nachdem der Versuch gestern Abend irgendwie an der Netzwerkkonfiguration gescheitert ist, heute ein neuer Versuch.
* wie muss die Ausgabe von `sudo pivccu-info` denn aussehen? Für mich sieht es soweit brauchbar aus:
`pi@Badezimmer-Pi:~ $ sudo pivccu-info
piVCCU version: 2.47.15-53
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   PEQ0175273
Radio MAC:      0x6715fc
SGTIN:          3014F711A061A7D8A98C14A9
State:          RUNNING
PID:            1178
IP:             192.168.230.34
CPU use:        29.75 seconds
BlkIO use:      116.00 KiB
Memory use:     93.25 MiB
KMem use:       3.59 MiB
Link:           vethpivccu
 TX bytes:      8.95 KiB
 RX bytes:      47.21 KiB
 Total bytes:   56.16 KiB`

Neuinstallation von Raspbian war aber ein guter Tipp. Ja, in der Tat hatte ich das vorher installierte YAHM einfach nur gemäß der Anleitung runtergeschmissen.
Läuft jetzt ganz wunderbar, vielen Dank! :)
