### ISSUE TITLE
dw_apb_raw_uart: unknown interrupt iid 0c

### ISSUE THREAD

**Issue by jens-maus** [alexreinert/piVCCU#176]
Hallo Alex,

zufällig habe ich gerade folgende Ausgaben in meiner `dmesg` Ausgabe auf meinem produktiven TinkerboardS mit RaspberryMatic gesehen. Kannst du dir diese erklären bzw. ergründen ob es sich dabei um etwas kritisches handelt?

```
[Thu Aug 22 05:09:22 2019] dw_apb_raw_uart ff190000.serial: unknown interrupt iid 0c
[Thu Aug 22 05:09:22 2019] dw_apb_raw_uart ff190000.serial: unknown interrupt iid 0c
[Thu Aug 22 05:09:22 2019] dw_apb_raw_uart ff190000.serial: unknown interrupt iid 0c
```

diese Ausgabe ist in dmesg hundertfach zu sehen. Ich kann mich allerdings auch nicht dran erinnern zu diesem Zeitpunkt ein Problem mit der produktiven CCU festgestellt zu haben?!?

Als Linux kernel wurde dort 4.19.66 mit aktuellen armbian patchset eingesetzt.

**Comment by jens-maus** [comment]
Sieht wohl so aus als ob es sich bei dem nicht behandelten interrupt um den `UART_IIR_RX_TIMEOUT` handelt. Siehe:

https://github.com/alexreinert/piVCCU/blob/master/kernel/dw_apb_raw_uart.c#L264
https://elixir.bootlin.com/linux/v4.6/source/include/uapi/linux/serial_reg.h#L43

Ob und inwieweit das natürlich kritisch ist kannst momentan nur du entscheiden. Offensichtlich kommt es aber hin/wieder zu diesem interrupt und dann wäre die frage was daraufhin passieren sollte im raw-uart?

**Comment by jens-maus** [comment]
Vielleicht hilft dir ja auch das folgende noch weiter:

https://elixir.bootlin.com/linux/latest/source/drivers/tty/serial/8250/8250_dw.c#L261

der original designware 8250 Treiber scheint hier an der selben stelle im handle_irq zumindest in der Dokumentation darauf einzugehen das es wohl unter bestimmten Vorraussetzungen zu diesem `UART_IIR_RX_TIMEOUT` interrupt kommen kann. Und dort haben die wohl ein workaround eingebaut:

```
    /*
     * There are ways to get Designware-based UARTs into a state where
     * they are asserting UART_IIR_RX_TIMEOUT but there is no actual
     * data available.  If we see such a case then we'll do a bogus
     * read.  If we don't do this then the "RX TIMEOUT" interrupt will
     * fire forever.
     *
     * This problem has only been observed so far when not in DMA mode
     * so we limit the workaround only to non-DMA mode.
     */
```

Denkst du es wäre sinnvoll den selben workaround auch in den raw-uart einzubauen denn ich sehe hier in der Tat wenn es zu diesen `unknown interrupt` Meldungen kommt (welche sehr selten sind) dann kommen diese zumindest hundertfach hintereinander.

**Comment by alexreinert** [comment]
Ich schau am Wochenende mal drauf

**Comment by alexreinert** [comment]
Fixed in commit 8cc927e33fe10471816e8793b2da7802926ced0b
