### ISSUE TITLE
ist hier ein bug?

### ISSUE THREAD

**Issue by MathiasJZ** [alexreinert/piVCCU#177]
ich habe die pivccu image auf einer SD-Karte geflasht und wollte gleich ein Update der FW machen.
Beim Upgrade bekam ich dann die Meldung:

`Creating symlink /var/lib/dkms/pivccu/1.0.35/source ->
                 /usr/src/pivccu-1.0.35

DKMS: add completed.
Error! echo
Your kernel headers for kernel 4.19.58-v7l+ cannot be found at
/lib/modules/4.19.58-v7l+/build or /lib/modules/4.19.58-v7l+/source.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service                                                                                                                                                              → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service →                                                                                                                                                              /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service                                                                                                                                                              → /lib/systemd/system/pivccu-dkms.service.
Setting up pivccu3 (3.47.15-30) ...
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu.service → /li                                                                                                                                                             b/systemd/system/pivccu.service.
Setting up libraspberrypi-doc (1.20190819-1) ...
Setting up libraspberrypi-bin (1.20190819-1) ...
Setting up libraspberrypi-dev (1.20190819-1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
`
Dann habe ich
`sudo pivccu-info`
eingegeben und bekam das zurück:
`piVCCU version: 3.47.15-30
Kernel modules: Not available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
HMIP Hardware:  RPI-RF-MOD
Board serial:   58A9A70B41
Radio MAC:      unknown
SGTIN:          3014F711A0001F58A9A70B41
State:          STOPPED
`
Wenn ich es nur einmal probiert hätte, würde ich ja einsehen, daß das mein Fehler war.
Ich versuche aber schon die ganze Woche, piVCCU zum laufen zu bringen.
Gruß,
Mathias
P.S. ich benutze dazu den Raspberry PI4B

**Comment by alexreinert** [comment]
Nein, kein Bug. Die Module werden immer für den aktuell aktiven Kernel erstellt. Durch das Update kamen aber auch ein neuer Kernel und die Header für diesen neuen. Der Kernel ist aber erst mit dem nächsten Reboot wird dieser aktiv. Leider löscht Raspbian in dem Zuge auch schon die aktuell aktiven Header, dadurch kommen die o.g. Fehlermeldungen. Bei nächsten Reboot werden die Module aber automatisch mit den neuen Headern für den neuen Kernel gebaut.

**Comment by MathiasJZ** [comment]
Nur hat ein reboot leider nichts gebracht.
Erst ein Shutdown, Kabel ziehen und Kabel stecken brachte (zumindest in 
meinem Fall) den gewünschten Erfolg.
Naja egal. Hauptsache er läuft jetzt.
Gruß,
Mathias

Am 7. September 2019 17:22:21 schrieb Alexander Reinert 
<notifications@github.com>:

**Comment by alexreinert** [comment]
Nach dem Reboot lange genug gewartet? Ich habe es grade nochmal probiert, lief einwandfrei.
