### ISSUE TITLE
piVCCU3 does not start

### ISSUE THREAD

**Issue by GitHobi** [alexreinert/piVCCU#178]
I've tried to install piVCCU3 on a Raspberry Pi 2b - but did not succeed.  I followed the steps, using fake_hmrf.  Everything seems to be fine, but lxc does not seem to be able to start the container.

pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.47.15-30
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  FAKE_HMRF
HMIP Hardware:  FAKE_HMRF
Board serial:   FKE4496284
Radio MAC:      0xab96e4
SGTIN:          unknown
State:          STOPPED

The log sais:

Sep 10 19:39:19 raspberrypi systemd[1]: Starting piVCCU DKMS Modules...
Sep 10 19:39:19 raspberrypi systemd[1]: pivccu-dkms.service: Succeeded.
Sep 10 19:39:19 raspberrypi systemd[1]: Started piVCCU DKMS Modules.
Sep 10 19:39:19 raspberrypi systemd[1]: Starting piVCCU...
Sep 10 19:39:20 raspberrypi systemd[1]: var-lib-piVCCU3-rootfs-dev.mount: Succeeded.
Sep 10 19:39:20 raspberrypi systemd[635]: var-lib-piVCCU3-rootfs-dev.mount: Succeeded.
Sep 10 19:39:20 raspberrypi systemd[1]: var-lib-piVCCU3-rootfs-proc.mount: Succeeded.
Sep 10 19:39:20 raspberrypi systemd[635]: var-lib-piVCCU3-rootfs-proc.mount: Succeeded.
Sep 10 19:39:23 raspberrypi start_container.sh[1457]: kernel.sched_rt_runtime_us = -1
Sep 10 19:39:23 raspberrypi kernel: [  494.178667] br0: port 2(vethpivccu) entered blocking state
Sep 10 19:39:23 raspberrypi kernel: [  494.178689] br0: port 2(vethpivccu) entered disabled state
Sep 10 19:39:23 raspberrypi kernel: [  494.179511] device vethpivccu entered promiscuous mode
Sep 10 19:39:23 raspberrypi kernel: [  494.188951] IPv6: ADDRCONF(NETDEV_UP): vethpivccu: link is not ready
Sep 10 19:39:24 raspberrypi kernel: [  494.250766] eth0: renamed from vethCEDW5Q
Sep 10 19:39:24 raspberrypi kernel: [  494.253492] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Sep 10 19:39:24 raspberrypi kernel: [  494.253579] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sep 10 19:39:24 raspberrypi kernel: [  494.253952] IPv6: ADDRCONF(NETDEV_CHANGE): vethpivccu: link becomes ready
Sep 10 19:39:24 raspberrypi kernel: [  494.254190] br0: port 2(vethpivccu) entered blocking state
Sep 10 19:39:24 raspberrypi kernel: [  494.254209] br0: port 2(vethpivccu) entered forwarding state
Sep 10 19:39:24 raspberrypi start_container.sh[1457]: lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 842 Received container state "ABORTING" instead of "RUNNING"
Sep 10 19:39:24 raspberrypi start_container.sh[1457]: lxc-start: lxc: tools/lxc_start.c: main: 330 The container failed to start
Sep 10 19:39:24 raspberrypi start_container.sh[1457]: lxc-start: lxc: tools/lxc_start.c: main: 333 To get more details, run the container in foreground mode
Sep 10 19:39:24 raspberrypi start_container.sh[1457]: lxc-start: lxc: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfile and --logpriority optio                           ns
Sep 10 19:39:24 raspberrypi systemd[1]: Started piVCCU.
Sep 10 19:39:24 raspberrypi kernel: [  494.466584] br0: port 2(vethpivccu) entered disabled state
Sep 10 19:39:24 raspberrypi kernel: [  494.469005] device vethpivccu left promiscuous mode
Sep 10 19:39:24 raspberrypi kernel: [  494.469034] br0: port 2(vethpivccu) entered disabled state
Sep 10 19:39:24 raspberrypi systemd[1]: pivccu.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 19:39:24 raspberrypi systemd[1]: pivccu.service: Failed with result 'exit-code'.

My knowledge about lxc is too limited - any hints on how to get picvccu3 up?

thanks!

**Comment by alexreinert** [comment]
Which version of Raspbian are you running? (```cat /etc/os-release```)
Which kernel is running (```uname -a```)

**Comment by Berti510** [comment]
Hi Alex,
ich klinke mich hier mal ein. Erstmal vielen Dank für die super Arbeit.
Ich möchte PivCCU3 in Verbindung mit ioBroker auf einem Tinker Board S nutzen. Dazu habe ich mir das aktuelle Image von iobroker.net geladen. das funktionierte erstmal auch. Nach `sudo apt update && sudo apt upgrade` war der Container nicht mehr erreichbar. Genau das gleiche nach aktuellem Armbian Focal mainline based kernel 5.4.46 Image von https://www.armbian.com/tinkerboard/ und manueller PivCCU3 Installation nach deiner Anleitung.

`sudo pivccu-info`
piVCCU version: 3.51.6-40
Kernel modules: Not available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          STOPPED

`cat /etc/os-release`
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

`uname -a`
Linux tinkerboard 5.4.46-rockchip #20.05.4 SMP PREEMPT Mon Jun 15 02:37:52 CEST 2020 armv7l armv7l armv7l GNU/Linux

Wo ist mein Fehler?
Danke
