### ISSUE TITLE
HmIP-RFUSB not working in pivccu3

### ISSUE THREAD

**Issue by DenisMtfl** [alexreinert/piVCCU#180]
Geräte anlernen funktioniert nicht aber lauf Info ist die Hardware gefunden worden.
Was kann ich tun?

piVCCU version: 3.47.15-30
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  FAKE_HMRF
HMIP Hardware:  HMIP-RFUSB
Board serial:   FKE8563373
Radio MAC:      0x35181c
SGTIN:          3014F711A000041709ADFBD8
State:          RUNNING
PID:            26587
IP:             192.168.1.155
CPU use:        38.34 seconds
BlkIO use:      19.88 MiB
Memory use:     131.68 MiB
KMem use:       5.23 MiB
Link:           vethpivccu
 TX bytes:      4.53 MiB
 RX bytes:      1.74 MiB
 Total bytes:   6.28 MiB

**Comment by DenisMtfl** [comment]
Ist das so richtig? Kein TTY ?

  USB 1-1 - USB2.0 Hub [HUB] - Sat Sep 14 11:29:44 2019
  USB 1-1.3 - eQ-3 HmIP-RFUSB [FF] - no tty - Sat Sep 14 11:29:44 2019
  Kein TTY-Device connected!



HM_HMIP_ADDRESS='0x35181c'
HM_HMIP_DEV='HMIP-RFUSB'
HM_HMIP_DEVNODE='/dev/mmd_hmip'
HM_HMIP_SERIAL='FKE8563373'
HM_HMIP_SGTIN='3014F711A000041709ADFBD8'
HM_HMIP_VERSION=''
HM_HMRF_ADDRESS='0x35181c'
HM_HMRF_DEV='HM-MOD-RPI-PCB'
HM_HMRF_DEVNODE='/dev/raw-uart'
HM_HMRF_SERIAL='FKE8563373'
HM_HMRF_VERSION='2.8.6'
HM_HOST='rpi3'
HM_HOST_GPIO_RESET=''
HM_HOST_GPIO_UART='/dev/raw-uart'
HM_LED_GREEN=''
HM_LED_RED=''
HM_LED_YELLOW=''
HM_MODE='NORMAL'
HM_RTC=''

**Comment by alexreinert** [comment]
Welches Gerät kann nicht angelernt werden und wie ist die exakte Vorgehensweise?

**Comment by DenisMtfl** [comment]
Hat sich erledigt. Neustart und reinstall von pivccu3 und dann gings.
