### ISSUE TITLE
After update to version 3.47.18 still version 3.47.15 detected in ccu3

### ISSUE THREAD

**Issue by Markus1970** [alexreinert/piVCCU#182]
Hi,S

tried the Update to the latest Version 3.47.18 today with "sudo apt update && sudo apt upgrade" but in CCU3 is still Version 3.47.15 detected.
System is running on Raspberry 3B. System reboot was done.
Any idea how I can get the CCU3 on the latest Version?

THX
Markus

**Comment by alexreinert** [comment]
Right now version 3.47.18 is only abailable in the testing apt repository. If there are no big issues I will copy it to stable in about two weeks. If you want to update ealier, you have to switch to the testing apt repository.

**Comment by alexreinert** [comment]
Do you still have any questions or can this be closed?
