### ISSUE TITLE
Nanopi M4 - piVCCU: Error! Hardware platform is not supported after update

### ISSUE THREAD

**Issue by mac-miller** [alexreinert/piVCCU#183]
Hallo,
ich habe das fertige Image Armbian_5.68_Nanopim4_Debian_Stretch_dev_piVCCU3_2019-01-08.zip benutzt und nach einem apt update und apt upgrade wurde der Kernel 5.3.0-rc4-rk3399 installiert.
Von diesem Zeitpunkt an kam immer die Meldung: piVCCU: Error! Hardware platform is not supported
Nach Änderung von piVCCU/dts/armbian/detect_board.inc :

friendlyelec,nanopi-m4)
        OVERLAY_MODE='patch'

in

friendlyarm,nanopi-m4)
        OVERLAY_MODE='patch'

funktioniert bisher wieder alles, weiß aber nicht, ob an anderer Stelle noch etwas geändert werden muß.

In /proc/device-tree/compatible steht bei mir:
friendlyarm,nanopi-m4.rockchip,rk3399.

Viele Grüße,
Markus

**Comment by alexreinert** [comment]
Fixed und released in testing und stable
