### ISSUE TITLE
Rockpro64 Image

### ISSUE THREAD

**Issue by Yetiberg** [alexreinert/piVCCU#184]
Hallo,
gibt es ein fertiges Rockpro64 Image?
Ich finde nur eins für den Rock64.
Grüße Yetiberg

**Comment by alexreinert** [comment]
Aktuell leider nein

**Comment by Yetiberg** [comment]
Ich suche mir einen Wolf wie ich an ein Image mit einem >4.13 Image komme.
DEV Kernel über Armbian bietet mir zwar ein Upgrade auf 5.3.0 an aber damit läuft kein Bluetooth Dongle mit.
Wo bekommt man ein Armbian Image mit wenigstens 4.14 her?

**Comment by alexreinert** [comment]
Das Image mit dem Dev Kernel.

**Comment by alexreinert** [comment]
Sind noch Fragen offen oder kann hier zugemacht werden?
