### ISSUE TITLE
homematic ip gestört

### ISSUE THREAD

**Issue by arto5754** [alexreinert/piVCCU#186]
Hallo!
habe genau wie #181 (pivccu on external hdd, homematic ip gestört) dieses Problem seit 2-3- Wochen. Die ganze Woche lauft es ohne Problem und plötzlich ist ein Senden zu den HMIP Geräten nicht mehr möglich .Am nächsten Tag lief es wieder und nun schon wieder.  Es kommt zu einer Systemmeldung, dass die Datenkommunikation gestört ist. Alle anderen Geräte laufen perfekt. Das System läuft seit etwa 1 Jahr auf einem ASUS Tinkerboard mit externer USB Disk und lief ohne Probleme. Alle HMIP Geräte sind von Homematic. CCU3 hat die Firmware 3.47.15.
Es ist ein aktives System, was das ganze Haus für Rolladen, Heizung, Alarmanlage und Licht steuert . Weis mir keinen Rat mehr, was ich überprüfen oder mache sollte.

**Comment by alexreinert** [comment]
Verstehe ich es richtig, dass das Problem ein spezielles Gerät betrifft, nicht dauerhaft vorhanden ist und in keinem zeitlichen Zusammenhang mit dem Update auf 3.47.15 steht?

Um welches Gerät handelt es sich? Sind Batteriegeräte vorhanden, welche ggf. langsam leer werden (Nicht nur Homematic, sondern alles auf 868 MHz)? Sind auf Direktverknüpfungen mit dem Gerät betroffen? Wie weit ist das Gerät von der Zentrale entfernt, was für Hindernisse sind vorhanden? Welches Funkmodul? Externe Antenne vorhanden?

**Comment by arto5754** [comment]
es betrifft alle HMIP Geräte (10x HmIP-FDT , das sind  LED Dimmer Aktoren,, keine Batterigeräte) und steht nicht im Zusammenhang mit der  Firmware 3.47.15. Status werden noch von den Geräte empfangen z.B Dimmerwert, aber wenn ich z.B. den Dimmerwert erhöhe gibt es einen Timeout und in der  Systemmeldung einen Datenkommunikationsfehler. Heute morgen waren Alle wieder ansprechbar. 
Hatte schon an den Duty Cycle gedacht, der liegt aber immer zwischen 5% - 9%.
Im Fehlerprotokoll der pivCCU3 steht z.B.
Sep 28 22:29:09 ccu3 local0.warn ReGaHss: WARNING: XMLRPC 'setValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"0008D709ABFD70:4","LEVEL",0.000000}, result: [faultCode:-1,faultString:"Generic error (TIMEOUT)"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Sep 28 22:29:09 ccu3 local0.err ReGaHss: ERROR: XMLRPC 'setValue' call failed (interface: 1009, params: {"0008D709ABFD70:4","LEVEL",0.000000}) [CallSetValue():iseXmlRpc.cpp:1505]
Sep 28 22:29:09 ccu3 local0.err ReGaHss: ERROR: rpc.CallSetValue failed; address = 0008D709ABFD70:4 [WriteValue():iseDOMdpHSS.cpp:76]

Das System läuft zusammen mit iobroker auf einem ASUS Tinkerboard und ist auf dem aktuellen Stand.
![hm_mode](https://user-images.githubusercontent.com/55930750/65829048-8e81e400-e2a1-11e9-9571-d7ac35d54904.png)

**Comment by arto5754** [comment]
Hallo Alexander,
bisher ist das Problem 3mal aufgetreten, dass alle HMIP Geräte  nicht mehr ansteuerbar  waren. Um das Licht dann auszuschalten musste die entsprechende Stromsicherung ausgeschaltet werden.
Wenn es nochmal auftreten sollte, kann ich irgendwas machen, um das Problem einzugrenzen?

**Comment by arto5754** [comment]
wieder Freitag und alle HMIP Geräte nehmen keine Sendebefehle an. Status erkennbar, d.h. Änderung der Helligkeit per Taster (Direktverknüpfung) wird angezeigt. Neustart --> keine Änderung. Heute morgen geht wieder Alles. Habe nur HMIP Dimmer und die funktionieren zum Glück auch noch per Taster. Das Problem tritt seit ca. 3 Wochen auf, da habe ich die Firmware auf 3.47.15 eingespielt. Kann es evtl. damit zusammenhängen?
Wann kommt die 3.47.18 als stable Version? Habe eine Info gelesen, dass damit evtl. auch Probleme gibt und Version 20 kommen wird.

**Comment by janbrummer** [comment]
Leider kann ich mich nun offenbar auch in die Reihe einreihen. Mit dem Update auf die aktuelle Version läuft der Datenverkehr zwischen piVCCU (RPI) und Schaltern stark verlangsamt, bzw gar nicht. Duty-Cycle ist mit 5% sehr niedrig, Fensterkontakte liefern aber scheinbar ihre Information in normaler Zeit. Gibt es irgendwelche Debug-Logs mit weiteren Informationen?

**Comment by alexreinert** [comment]
Diese Woche soll eine 3.47.22 kommen, welche Probleme bei HmIP addressiert. Ich hoffe, dass eQ-3 damit die ganzen Probleme in den Griff bekommt. Mangels Zugriff auf den Sourcecode kann ich da leider weder gescheit debuggen noch irgendwie etwas fixen. :-(

**Comment by janbrummer** [comment]
Habe meins soeben gefunden: Ein Bewegungsmelder war komplett leer und wurde als Störung gemeldet. Neue Batterien und das GESAMTE System funktioniert wieder reibungslos.... jetzt bin ich sprachlos...

**Comment by alexreinert** [comment]
Siehe mein erstes Posting: Ich habe nicht umsonst gefragt, ob es Batteriegeräte gibt. Das nennt sich Babbling Idiot und ist leider durchaus verbreitet (nicht nur bei Homematic).

**Comment by janbrummer** [comment]
Danke für deinen schnellen Support.

**Comment by alexreinert** [comment]
@arto5754 Bitte mal probieren, ob das Problem mit der 3.47.22 immer noch besteht.

**Comment by arto5754** [comment]
habe 3.47.22 seit ein paar Tagen schon installiert (von testing).  Muss abwarten, ob noch Probleme auftreten .

**Comment by arto5754** [comment]
@alexreinert 
   bis jetzt keine Probleme mit HmIP.
   Danke für deine Unterstützung!
