### ISSUE TITLE
piVCCU mit OpenHAB auf einem PI - IPKonfiguration

### ISSUE THREAD

**Issue by MarcoVolker** [alexreinert/piVCCU#187]
Hallo,
ich aber als Anfänger via Noobs auf einem PI mit dem ELV Funkmodul ein raspbian aufgespielt, obenhab installiert, pivccu installiert und stehe nun vor dem folgenden Sachverhalt.

1.- über dhcpcd.conf habe ich der eth0 eine feste IP-Adresse zugewiesen unter der ich openHAB2 via http über Port 8080 auch aufrufen kann. 

2.- die berühmt berüchtigte Datei /etc/network/interfaces ist im "Originalzustand"

3.- die Datei /var/lib/piVCCU/userfs/etc/config/netconfig habe ich ferner dahingehend geändert, als das auch piVCCU eine statische IP bekommen soll

Irgendwo habe ich großes Pech beim Denken und verstehe noch nicht die Abhängigkeiten von dhcpcd.conf, interfaces und der netconfig von piVCUU

Ein sudo pivccu-info sagt mir ...
piVCCU version: 2.47.15-53
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
HMIP Hardware:  RPI-RF-MOD
Board serial:   58a9a71a1e
Radio MAC:      unknown
SGTIN:          3014f711a0001f58a9a71a1e
State:          RUNNING
PID:            1158
IP:             192.<Inhalt aus netconfig>
CPU use:        36.45 seconds
BlkIO use:      40.69 MiB
Memory use:     93.10 MiB
KMem use:       3.77 MiB
Link:           vethpivccu
 TX bytes:      25.29 KiB
 RX bytes:      19.48 KiB
 Total bytes:   44.77 KiB

Ich kann aber die IP nicht anpingen weder mich auf die WebGUI schalten

Ferner sehe ich bei sudo ifconfig auch keine Bridge br0 ??

Bin über jeden Tip dankbar...

**Comment by alexreinert** [comment]
Die Installatinsanweisung gibt es nicht einfach so zum Spaß, wenn die nicht beachtet wird, braucht man sich nicht wundern, wenn es nicht klappt.

**Comment by MarcoVolker** [comment]
Hallo,
der Installationsanweisung bin gefolgt und hatte danach kein dhcp service mehr, mit der Folge das mein kompletter PI nicht mehr online war.
Daher habe ich versucht das zu umgehen.

Kann mir trotzdem geholfen werden?

**Comment by alexreinert** [comment]
Schön das dass mit keinem Wort erwähnt war...

Wenn man der Installationsanweisung komplett folgt, dann hat man hinterher kein dhcpd mehr, weil der mit den Bridges inkompatibel ist. Je nachdem, was man in Schritt 7 gewählt hat, mit DHCP oder mit einer statischen IP.
Der Weg in der Installationsanweisung ist mehrfach überprüft und aktuell der einfachste Weg. Ich kann nicht anders helfen, als zu sagen, bitte so machen.
Alternativ ein fertiges piVCCU Image runterladen (Welches aber auch einfach nur ein Raspbian Image mit den Schritten aus der Installationsanleitung als Custom Step im Raspbian Builder ist).

**Comment by MarcoVolker** [comment]
Hallo, 
ich bin ja ein recht demütiges Kerlchen und nehme die volle Schuld auf meine Schultern. 
Auch in Anbetracht dem Respekt gegenüber deiner Arbeit ... meine ich Ernst

Der Hinweis mit der Inkompatibilität zwischen dhcpcd.conf und interfaces hat den Durchbruch gebracht. (in vielen Beitragen unterliegt man der Vermutung, dass es eine Koexistenz beider Lösungen geben kann ... wohl aber nichts für Anfänger)

Die Installations.Schritte gemäß Anleitung also inkl. Nr.7 durchgeführt ... dhcpcd5 deinstalliert und nehme die komplette IP Konfiguration in einer angepassten interface Datei vor.

Ergebnis:
** PI bootet und ist online
** Openhab auf statischer Adresse am Port 8080 via http ansprechbar
** piVCCU WebGui auf statischer Adresse via http ansprechbar

Jetzt ein schnell ein Image ... :-)

Danke für deinen Hinweis

**Comment by gelsas** [comment]
Hi Marco,

könntest du evtl. einmal den Inhalt deiner Interface datei hier posten.

Stehe vor dem selben Problem und bin mir nicht ganz sicher wie die interface datei jetzt aussehen muss.

**Comment by alexreinert** [comment]
So, wie es in der Installationsanleitung drin steht.

**Comment by gelsas** [comment]
Also damit openhab auch weiter funktioniert auf der ip addresse müsste es also so aussehen ?

Will lieber nachfragen, da ich quasi nie mit linux arbeite und immer angst habe was zu zerschießen...

```
sudo apt remove dhcpcd5
sudo apt install bridge-utils
sudo bash -c 'cat << EOT > /etc/network/interfaces
source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address 192.168.1.61
    netmask 255.255.255.0
    gateway 192.168.1.1

auto br0
iface br0 inet static
  bridge_ports eth0
  address 192.168.1.62
  netmask 255.255.255.0
  gateway 192.168.1.1
EOT'
```

**Comment by alexreinert** [comment]
Nein, dass ist nicht, was in der Anleitung steht. eth0 muss auf nanual gestellt werden und bekommt keine IP. br0 bekommt die IP vom Pi zugeteilt (und hat eth0 und den piVCCU Container angeschlossen). Der piVCCU Container startet mit DHCP und kann über die WebUI auf eine statisch Adresse umkonfiguriert werden.

**Comment by gelsas** [comment]
Und was muss ich machen wenn ich auf einen Raspberry Pi 4 schon openhab drauf installiert und laufen habe und jetzt zusätlich dazu Homematic (pivCCU) nutzen will (auf dem selben Raspberry Pi4) ?

**Comment by alexreinert** [comment]
Das, was in der Anleitung steht, ob da bereits OpenHab installiert ist, ist irrelevant.
Vorher ein Backup zu machen bietet sich natürlich an, aber das sollte man unabhängig von der Installation ja immer haben.

**Comment by gelsas** [comment]
Okay, ich habe die Anleitung 1 zu 1 befolgt inklusive Schritt 7 und dann `sudo reboot` gemacht. Nun startet der RaspberryPi auf dem openhabianpi (Raspian Buster - https://github.com/openhab/openhabian/releases) installiert ist gar nicht mehr und ist auch nicht über SSH zu erreichen.

Ich entschuldige mich für meine doofen Fragen, leider weiß ich es nicht besser was falsch gelaufen ist und brauche weitere Hilfe.

**Comment by alexreinert** [comment]
Wurde im ersten Befehl von Schritt 7 auch eth0 angezeigt? Wenn nein, wurde das an allen Stellen der folgenden Befehle abgeändert? Wie sah der Befehl für die Anpassung der Interfaces Datei genau aus? Wie ieht die Interfaces Datei jetzt aus (lokaler Login mit Monitor und Tastatur)

**Comment by gelsas** [comment]
Ja eth0 wurde angezeigt.

sudo apt remove dhcpcd5
sudo apt install bridge-utils
sudo bash -c 'cat << EOT > /etc/network/interfaces
source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback

iface eth0 inet manual

auto br0
iface br0 inet dhcp
  bridge_ports eth0
EOT'

Jetzt sieht die Interface Datei so aus:

source-directory /etc/network/interfaces.d
auto lo
iface lo inet loopback

iface eth0 inet manual

auto br0
iface br0 inet dhcp
  bridge_ports eth0

**Comment by alexreinert** [comment]
Kann es sein, dass das System per DHCP jetzt einfach eine andere IP zugewiesen bekommen hat? Bitte mal im Router prüfen.

**Comment by gelsas** [comment]
Stimmt genau das war der Fall.

(Hatte bei meinem ersten Versuch wohl irgendwo einen Tipp ge
