### ISSUE TITLE
Update 3.47.15 auf 3.47.18

### ISSUE THREAD

**Issue by CP-12** [alexreinert/piVCCU#188]
Hi everyone,

until now I could easily update the firmware using sudo apt-update and sudo apt-upgrade. but at the moment i can run the update process several times without that it changes the pivCCU version I am stuck on 3.47.15. During the process it says pivccu stable in release, but does not download anything. Can I somehow force it to do the update?

Christian

**Comment by alexreinert** [comment]
Right now the 3.47.18 is only available in the testing apt repository. You can either switch to the testing apt repository or wait until the weekend, when I will copy it to the stable apt repository, too.

**Comment by alexreinert** [comment]
I just realeased 3.47.18 in the stable apt repo, too.
