### ISSUE TITLE
Image Raspbian_Buster_Liste_piVCCU3_2019-07-11.zip not working

### ISSUE THREAD

**Issue by egmontr** [alexreinert/piVCCU#189]
My Paspberry Pi 4 2GB is not starting with the image:
https://www.pivccu.de/images/piVCCU3/Raspbian_Buster_Liste_piVCCU3_2019-07-11.zip

I tried with different SD cards. But not starting.
Once I saw a short message "resizing..." and that was it.

The original image 2019-09-26-raspbian-buster-lite.zip is working very well.

Greetings 
Egmont

**Comment by alexreinert** [comment]
Strange. On my Pi 4 (only 1GB) it is working very well and the image is built using the same toolchain as the official images.

**Comment by egmontr** [comment]
Can I help you with some logs or so?

**Comment by egmontr** [comment]
I think, reboot after resizing the partition is not working.
I waited 5 minutes, then I unplugged the RPI and plugged it inagain. Then it suddenly started to work.
Very strange.

**Comment by Hofei90** [comment]
Hello,
check under the following link if the bootloader works correctly. 
"**Is the bootloader working correctly?**"  :
https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md

**Comment by egmontr** [comment]
Hi,

I checkes and all seems fine.
Other SD Cards with stock Buster are booting fine.

Regards
Egmont

Am Mi., 9. Okt. 2019 um 12:50 Uhr schrieb Hofei90 <notifications@github.com

**Comment by egmontr** [comment]
Hi,

I checked and all seems fine.
Other SD cards with stock Buster are booting fine.

Regards

Am Mi., 9. Okt. 2019 um 12:50 Uhr schrieb Hofei90 <notifications@github.com
