### ISSUE TITLE
Error installing piVCCU3 on RPI 4

### ISSUE THREAD

**Issue by egmontr** [alexreinert/piVCCU#190]
I followed your guide https://github.com/alexreinert/piVCCU/blob/0dd35fa2f3c1b176733851e24747ac8f25922dcb/docs/setup/raspberrypi.md and got an error at point 3.
Want to use HM-MOD-RPI-PCB.

```
DKMS: add completed.
Error! echo
Your kernel headers for kernel 4.19.75-v7l+ cannot be found at
/lib/modules/4.19.75-v7l+/build or /lib/modules/4.19.75-v7l+/source.

```
I continued to install, but no success. 
How can I fix the setup?

**Comment by egmontr** [comment]
I tried:
**sudo apt-get install raspberrypi-kernel-headers**
but didn't help.

**Comment by alexreinert** [comment]
Is the Kernel at the same version as the headers and did you reboot after updating the kernel?

**Comment by egmontr** [comment]
I rebooted more times.

```
dpkg -s raspberrypi-kernel | grep Version
Version: 1.20190925-1
dpkg -s raspberrypi-kernel-headers | grep Version
Version: 1.20190819-1

```

**Comment by topaDev** [comment]
Same problem here...
I think there is no up-to-date raspberrypi-kernel-headers in the repo at the moment. Other projects are affected, too:
https://github.com/respeaker/seeed-voicecard/issues/183
https://www.reddit.com/r/pihole/comments/dclpuc/trouble_with_wg_after_rpiupdate_kernel_issues/

**Comment by alexreinert** [comment]
As discussed in the FHEM forum, this is likely an issue with the Raspberry Pi Kernel Repository which seems to be resolved.

**Comment by topaDev** [comment]
Yes, seems to be OK again. Thanks
