### ISSUE TITLE
Update not possible since 3.47.15

### ISSUE THREAD

**Issue by dave-castle** [alexreinert/piVCCU#191]
Hi there,

since version 3.47.15 on a Pi3 Model B+, I'm not able to update, I get the following errors:
Any ideas?!

```
pi@raspberrypi:~ $ sudo apt update && sudo apt upgrade
Get:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian stretch InRelease [25.4 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages [11.7 MB]  
Hit:4 https://deb.nodesource.com/node_8.x stretch InRelease                           
Get:5 https://www.pivccu.de/piVCCU stable InRelease [13.6 kB]
Get:6 http://archive.raspberrypi.org/debian stretch/main armhf Packages [221 kB]                  
Get:7 https://www.pivccu.de/piVCCU stable/main armhf Packages [6,309 B]                       
Fetched 11.9 MB in 7s (1,607 kB/s)                                                                                                                                                  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  pivccu-devicetree-armbian pivccu3
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 107 MB/107 MB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 https://www.pivccu.de/piVCCU stable/main armhf pivccu3 armhf 3.47.18-31 [107 MB]
Fetched 107 MB in 16s (6,286 kB/s)                                                                                                                                                  
Reading changelogs... Done
Preconfiguring packages ...
(Reading database ... 94219 files and directories currently installed.)
Preparing to unpack .../pivccu3_3.47.18-31_armhf.deb ...
Removed /etc/systemd/system/multi-user.target.wants/pivccu.service.
Unpacking pivccu3 (3.47.18-31) over (3.47.15-30) ...
Preparing to unpack .../pivccu-devicetree-armbian_1.0.25_all.deb ...
piVCCU: Error! Hardware platform is not supported
Unpacking pivccu-devicetree-armbian (1.0.25) over (1.0.24) ...
dpkg: error processing archive /var/cache/apt/archives/pivccu-devicetree-armbian_1.0.25_all.deb (--unpack):
 unable to make backup link of './boot/overlay-user/pivccu-bananapi-m1.dtbo' before installing new version: Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/pivccu-devicetree-armbian_1.0.25_all.deb
piVCCU: Error! Hardware platform is not supported
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Thanks in advance!

**Comment by alexreinert** [comment]
The package pivccu-devicetree-armbian should not be installed on a Raspberry Pi. Please uninstall it.

**Comment by alexreinert** [comment]
Any update?

**Comment by dave-castle** [comment]
I decided to do a clean install, which worked! thx anyway.

**Comment by dave-castle** [comment]
very strange, there is no update for me even piVCCU is currently on version 3.47.22	

`pi@raspberrypi:~ $ sudo apt-get update && sudo apt-get upgrade
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease        
Hit:3 https://www.pivccu.de/piVCCU stable InRelease                 
Reading package lists... Done                 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  raspi-config
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.47.15-30
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   OEQ0308051
Radio MAC:      0x583da2
SGTIN:          3014F711A061A7D7098E1B53
State:          RUNNING
PID:            700
IP:             XXX
IP:             XXX
IP:             XXX
CPU use:        6467.35 seconds
BlkIO use:      78.75 MiB
Memory use:     174.81 MiB
KMem use:       5.81 MiB
Link:           vethpivccu
 TX bytes:      376.92 MiB
 RX bytes:      859.08 MiB
 Total bytes:   1.20 GiB
pi@raspberrypi:~ $ 
`

**Comment by alexreinert** [comment]
No, this is not strange. The 3.47.22 is currently available in the testing apt only. Like every release, there is a test period of about 2 weeks before it comes to stable.

**Comment by alexreinert** [comment]
As said, the 3.47.22 is only available in the testings apt repository at the moment.
The update check in the WebUI uses the orignal CCU3 check url.
