### ISSUE TITLE
Problem with actual update

### ISSUE THREAD

**Issue by bastelfeak** [alexreinert/piVCCU#194]
Hello,
I tried yesterday a few times to install a fresh Buster with pivccu. It's not possible. Then I load the ready image from the repository and start: It's working. After an update & upgrade: The pivccu is not working anymore.

I have no idea why but maybe you find out the root cause.

**Comment by alexreinert** [comment]
Which hardware are you using? Was there a kernel update and if yes, did you do a reboot after it? Please provide the output of pivccu-info.

**Comment by bastelfeak** [comment]
Hey, I'm using Raspi 3 with Buster Lite. As I described: If I start your image like it is it will work. If do the update and upgrade the pivccu will not eotk anymore.
pivccu Info I will share tomorrow morning.

**Comment by bastelfeak** [comment]
How it looks before the update, out of the image :)

`
piVCCU version: 3.47.10-28
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   NEQ0231575
Radio MAC:      0x47021e
SGTIN:          3014F711A061A7D5698CF097
State:          RUNNING
PID:            864
IP:             192.168.178.26
CPU use:        22.60 seconds
BlkIO use:      56.84 MiB
Memory use:     146.84 MiB
KMem use:       4.74 MiB
Link:           vethpivccu
 TX bytes:      14.61 KiB
 RX bytes:      114.38 KiB
 Total bytes:   128.99 KiB

`
This is the status after the update:

`piVCCU version: 3.47.15-30
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   NEQ0231575
Radio MAC:      0x47021e
SGTIN:          3014F711A061A7D5698CF097
State:          RUNNING
PID:            2320
IP:             192.168.178.26
CPU use:        20.84 seconds
BlkIO use:      53.53 MiB
Memory use:     133.89 MiB
KMem use:       4.15 MiB
Link:           vethpivccu
 TX bytes:      11.97 KiB
 RX bytes:      28.80 KiB
 Total bytes:   40.77 KiB
`
It looks like the topic was a very special thing...okay it's working now :)

**Comment by alexreinert** [comment]
Maybe this was the same issue as in #190 where the Raspberry Pi kernel headers did not match the installed kernel.
