### ISSUE TITLE
Automatisches update stoppt

### ISSUE THREAD

**Issue by brgbrg** [alexreinert/piVCCU#195]
Hi,

I run pivccu3 on a Raspberry Pi 2. 
At certain times, an update script tries to install all updates and upgrades with:
  apt-get -y dist-upgrade 
This also tried to update pivccu3, but stopped when the backup question came (see log below).
Now I cannot install or remove the package with apt-get.

- Q1: Is there a possibility to explicitely start the pivccu3 install scripts?
- Q2: Can I skip the Yes/No question somehow or should I rather exclude the pivccu3 from automatic upgrade?

Kind regards

  Rolf

Log output:
```
   Preparing to unpack .../pivccu3_3.47.18-31_armhf.deb ...
   Removed /etc/systemd/system/multi-user.target.wants/pivccu.service.
   debconf: unable to initialize frontend: Dialog
   debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
   debconf: falling back to frontend: Readline
   Configuring pivccu3
   -------------------
    A new CCU firmware version is to be installed.
    It is recommended that you create a backup before installing a new CCU firmware 
version.
    Do you have a backup?
   [yes/no]

```

remove log:
```
pi@rollladenserver:~ $ sudo apt-get remove pivccu3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  liblxc1 lxc python3-lxc
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  pivccu3
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
dpkg: error processing package pivccu3 (--remove):
 package is in a very bad inconsistent state; you should
 reinstall it before attempting a removal
Errors were encountered while processing:
 pivccu3
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by alexreinert** [comment]
First: Automatic updates using apt-get dist-upgrade are very dangerous. I hope, you know what you are doing.

This question cannot be skipped.
You can exclude packages from upgrade using ```apt-mark hold $PACKAGE```

**Comment by brgbrg** [comment]
Ok, I will exclude the pivccu3 from automatic upgrade. 
Is there any chance to re-execute the install scripts again to close the pivccu3 update correctly?

**Comment by alexreinert** [comment]
```apt install --reinstall pivccu3```

**Comment by brgbrg** [comment]
Thanks, everything now is working again. Support here is better than on most commercial products. I have thrown something into your PayPal box  :-)

**Comment by alexreinert** [comment]
Thanks a lot.
