### ISSUE TITLE
"Raspbian_Buster_Liste_piVCCU3_2019-07-1" leads to -->Curl SSL Certificate Problem

### ISSUE THREAD

**Issue by jaddel** [alexreinert/piVCCU#197]
`sudo curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
`
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (60) SSL certificate problem: unable to get local issuer certificate
> More details here: https://curl.haxx.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above.

This is what happens when i try to install node by nvm.
I tried it with the original rasbian img without running into this problem. 

I believe there is something wrong with your img. Can you have a look in to it?

**Comment by alexreinert** [comment]
Which image are you using? Did you call the command inside the host or inside the container?

**Comment by jaddel** [comment]
Raspbian_Buster_Liste_piVCCU3_2019-07-1

**Comment by jaddel** [comment]
I just tried this img:  Raspbian_Stretch_Lite_piVCCU3_2019-01-05.zip and didn't run in to the problem.

**Comment by jaddel** [comment]
> nd inside

i called the command inside the host 
Raspbian_Buster_Liste_piVCCU3_2019-07-1

**Comment by alexreinert** [comment]
The image was build using the same build tool which is used for the official Raspbian images. Maybe there was an issue this the first Raspbian images, too.
I will rebuild new images soon, until then please use the manual setup.

**Comment by jaddel** [comment]
If I follow the manual installation I get stuck after the first reboot. I
can access the ccu, but not the host anymore.

I followed the dhcp steps.

Alexander Reinert <notifications@github.com> schrieb am Di., 15. Okt. 2019,
13:30:

**Comment by alexreinert** [comment]
Root cause identified: RPi-Distro/pi-gen#281

**Comment by synth3** [comment]
First of all: Thanks a lot for for the work you put in piVCCU! ...this has become on of the fundamentals of my digital home! 👍

I'm currently trying to switch from pi 3 to pi 4 was happy that there is a ready image and then ran into the same problem.

Personally I would consider the image (`Raspbian_Buster_Liste_piVCCU3_2019-07-11`) damaged - maybe it is a good idea to remove it from the list of stable images as it may save many people time debugging this issue (and probably other issues)?
