### ISSUE TITLE
Firmware 3.47.22 - STABLE

### ISSUE THREAD

**Issue by smooty1970** [alexreinert/piVCCU#199]
Hallo,

ist die neue Firmware für pivCCU3 schon im Verzeichnis STABLE abgelegt oder dauert das ein paar Tage? Ich bekommen die Meldung, eine neue Firmware steht bereit, aber mit sudo apt update && sudo apt upgrade am RPI findet er noch nichts.

Danke

**Comment by alexreinert** [comment]
Nein, die neue Version ist noch nicht in Stable, ich warte damit immer ca. 2 Wochen. Das hat sich in der Vergangenheit auch mehrfach bewährt.

**Comment by alexreinert** [comment]
die 3.47.22 ist jetzt auch im stable apt Repo.
