### ISSUE TITLE
Add Support for Rock64

### ISSUE THREAD

**Issue by alexreinert** [alexreinert/piVCCU#2]

**Comment by alexreinert** [comment]
Needs to be checked,  if GPIO2-A3 can work as Output Pin (Reset Pin of HM-MOD-RPI-PCB)

**Comment by alexreinert** [comment]
The UART only works with the fiq-debugger module and only with a rate of 1.5m baud.
Because of that the HM-MOD-RPI-PCB can not be used on the rock64.

**Comment by leonsio** [comment]
hi Alex

meinst du die firefly version hat die gleichen Einschränkungen?
Bzw. hast du rausgefunden ob es am Chipsatz oder an der SW liegt?

https://de.aliexpress.com/item/ROC-RK3328-CC-Quad-Core-64-Bit-CPU-1GB-2GB-DDR4/32844692297.html?spm=a2g0x.10010108.1000016.1.56d04d48YJHq3p&isOrigTitle=true

https://www.cnx-software.com/2017/12/05/libre-computer-renegade-sbc-features-rockchip-rk3328-processor-with-up-to-4gb-ddr4-ram-crowdfunding/

https://www.indiegogo.com/projects/renegade-arm-computer-with-usb-3-on-android-linux#/

**Comment by alexreinert** [comment]
Das der GPIO2_A3 nicht als Out Pin arbeitet, liegt in der Hardware. Ob der bei den anderen Boards aber auch als Pin 12 rausgeführt ist, keine Ahnung. Aber das wäre ja auch recht einfach lösbar, wenn man da einen HW Mod macht und einen andere PIN für Reset verwendet.
Das Thema mit dem UART liegt imho im Bootloader. Da könnte es natürlich sein, dass es bei den anderen Boards besser ist, aber ich vermute eher nicht, da kümmert sich ja kaum einer um Bootloader und Kernel, das lassen die ja alles beim CPU Hersteller liegen.

**Comment by leonsio** [comment]
hi alex
ich habe mich etwas mit rock64 beschäftigt und habe das Funkmodul zum laufen bekommen
Zumindest läuft es in der "Basis" Version ohne IP auf dem aktuellen ayufan-rock64 stable build

habe dazu im device tree fiq-debugger deaktiviert und serial2 aktiviert, daraufhin kann ich über ttyS2 auf das Gerät zugreifen

Es gab mit dem letzten Kernel Update paar Änderungen in Hinblick auf GPIOs, das GPIO2_A3 ist nun unter der Adresse 1067 erreichbar, inwieweit es jetzt als Output arbeitet, kann ich nicht beurteilen.

sofern Interesse besteht, kann ich dir Remote Zugriff auf die Kiste geben, oder kannst du so beurteilen, dass es nichts bringt? 

```shell
/var/log # rfd -l 1 -c -s
Config file is /etc/config/rfd.conf
2018/01/31 16:14:09.983 <Info> BidCoS-Service started
2018/01/31 16:14:09.984 <Info> XmlRpc Server is listening on TCP port 2001
2018/01/31 16:14:09.986 <Debug> CCU2CommController::init() - Legacy initialization.
2018/01/31 16:14:14.987 <Debug> () CCU2CommController::startCoprocessorApp(): Trying to start coprocessor application
2018/01/31 16:14:15.925 <Debug> () CCU2CommController::handleIdentifyEvent(): Coprocessor entered application. Life is good.
2018/01/31 16:14:15.992 <Info> CCU2CommController::init(): Coprocessor Bootloader Version is: 1.0.3
2018/01/31 16:14:15.993 <Info> CCU2CommController::init(): Coprocessor Firmware Version is: 1.2.1
2018/01/31 16:14:15.997 <Info> () CCU2CommController::setCSMACAEnabled(): CSMA/CA disabled.
2018/01/31 16:14:16.005 <Debug> Default interface is now OEQ0607943
2018/01/31 16:14:16.007 <Debug> CCU2BidcosRemoteInterface::StartInterface(): addr=59 db ea 
2018/01/31 16:14:16.011 <Debug> (OEQ0607943) Response status: OK.
```

was ich aber so erkennen kann, ist dass der Port wohl noch immer mit 150k arbeitet, das wird wohl für HMIP nicht reichgen?

```shell
# dmesg | grep -E 'serial|console|fiq|ttyS2'
[    0.000000] earlycon: Early serial console at MMIO32 0xff130000 (options '')
[    0.000000] bootconsole [uart0] enabled
[    0.000000] Kernel command line: rockchip_jtag earlyprintk=uart8250-32bit,0xff130000 earlycon=uart8250,mmio32,0xff130000 rw root=LABEL=linux-root rootwait rootfstype=ext4 init=/sbin/init coherent_pool=1M ethaddr=be:75:5c:f2:ae:71 eth1addr=be:75:5c:f2:ae:91 serial=1c6067242e4b8a9
[    0.002057] console [tty0] enabled
[    0.002380] bootconsole [uart0] disabled
[    0.223188] fiq-debugger is disabled in device tree
[    0.923164] ff130000.serial: ttyS2 at MMIO 0xff130000 (irq = 13, base_baud = 1500000) is a 16550A
[  427.281871] of_dma_request_slave_channel: dma-names property of node '/serial@ff130000' missing or empty
[  427.282434] ttyS2 - failed to request DMA
[16:23:16][root@rock64:~]
# 
```

**Comment by leonsio** [comment]
Also das Funkmodul geht mit Testsystem ohne Probleme seit 2 Tagen auch mit diversen Funktionen wie FW-Update des Moduls oder der Gerate

ich weiß, du willst es gern unter armbian zum Laufen bekommen, aber ggf. schaust du es dir doch an.
habe versucht im device tree die gleichen Einstellungen zu setzen, wie bei anderen Boards, dein Treiber wird auch beim start sofort geladen /dev/raw-uart wird aber nicht angelegt. Fehlermeldungen sind keine zu finden.

Da ich in Device Tree nicht so tief stecke, werde ich an der Stelle abbrechen.
Ich persönlich brauche den Support nicht, da ich nicht vor habe Funkmodul auf dem rock64 zu betreiben, für andere User wäre aber das Gerät bestimmt interessant

```
    serial@ff130000 {
        compatible = "rockchip,rk3328-uart", "snps,dw-apb-uart", "pivccu,dw_apb";
        reg = <0x0 0xff130000 0x0 0x100>;
        interrupts = <0x0 0x39 0x4>;
        clocks = <0x2 0x28 0x2 0xd4>;
        clock-names = "baudclk", "apb_pclk";
        reg-shift = <0x2>;
        reg-io-width = <0x4>;
        dmas = <0xb 0x6 0xb 0x7>;
        #dma-cells = <0x2>;
        pinctrl-names = "default";
        pinctrl-0 = <0x33>;
        status = "okay";
        pivccu,gpio_pin = <1067>;
    };
```

wie gesagt bevor du dir das Ding bestellst, kannst du gern Remote auf die Kiste drauf
