### ISSUE TITLE
Support for modules other than HM-MOD-RPI-PCB

### ISSUE THREAD

**Issue by ThomDietrich** [alexreinert/piVCCU#20]
Hey,
I take it your software only supports the HM-MOD-RPI-PCB? I own an SCC so that is too bad but understandable. This issue is primarily here to answer this question. Maybe that should be emphasized on the REAMDE file. Best!

**Comment by alexreinert** [comment]
Last point of prequisites in the Readme, if you don't read the prequisites, i hve no idea where to put it.

And SCC cannot be used as it is not supported by the underlying CCU2 firmware.
