### ISSUE TITLE
Firmware 3.47.22 und HmIP-SRH

### ISSUE THREAD

**Issue by smooty1970** [alexreinert/piVCCU#203]
Hallo,

mit der neuen Firmware spinnen plätzlich einzelne 5 oder 6 von 18 HmIP-SRH Fenstersensoren. Entweder ändert sich der Status in der CCU extrem verzögert, manchmal bis zu 60 Sekunden oder überhaupt nicht. Gibt es ähnliche Meldungen dazu?
Kann man ein Downgrade auf die Firmware 3.47.15 machen, wenn ja, wie?
Vielen Dank

**Comment by alexreinert** [comment]
Dazu gibt es keine Meldungen, eher im Gegenteil.
Downgrade kann per apt erfolgen:
```sudo apt install pivccu3=3.47.15-30```
Ich glaube aber weniger an ein Problem in der Version, sondern eher an einen Störsender oder ein DC Problem.

**Comment by smooty1970** [comment]
Hallo Alex.
Danke für prompte Rückmeldung. Richtig, auch mit der alten FW das selbe Problem. Unmittelbar nach Neustart der CCU reagieren die Devices und senden den richten State an die CCU. Nach einigen Stunden dann wieder das Problem: Fenster offen - obwohl geschlossen. Ich habe als erstes mal bei den betreffenden Devices die Batterien gegen neue Markenbatterien getauscht und beobachte weiter,

Meine Umgebung: 9 HM Devices über FLGW, 93 HmIP Devices - in Kombination mit LoxOne via XMLRPC, mit CCU auf Basis vipccu auf RPI4 mit HB-RF-USB Funkmodul und DC um die 30

**Comment by alexreinert** [comment]
Es empfiehlt sich, nicht nur die betroffenen Geräte zu prüfen, sondern alle Batteriegeräte. HmIP macht ein Listen Before Talk, wenn da irgendjemand anderes sendet, dann fangen sie nicht an zu senden. Und grade Batteriegeräte mit fast leeren Batterien neigen dazu, zu Störsendern zu werden (unabhängig davon, ob es HmIP, HM oder komplett andere Geräte im 868MHz Band sind)

**Comment by alexreinert** [comment]
Ist hier noch was offen?

**Comment by smooty1970** [comment]
Hallo Andreas,

nein – alles erledigt.

Danke

[cid:image001.jpg@01D5B01B.F027E690]<http://www.itbcs.consulting/>
JENS LUMPE​
CEO
.
itbcs – it business consulting & solutions e. U.
.
5270
Burgkirchen
Wollöster 45

[cid:image002.png@01D5B01B.F027E690]
+43 (7724) 20995<tel:+43%20(7724)%2020995>
[cid:image003.png@01D5B01B.F027E690]
+43 (664) 1419628
[cid:image004.png@01D5B01B.F027E690]
+43 (7724) 20995 89

[cid:image005.png@01D5B01B.F027E690]
 jens.lumpe@itbcs.consulting
[cid:image006.png@01D5B01B.F027E690]
 www.itbcs.consulting<http://www.itbcs.consulting/>
Life is too short for a bad service

​itbcs ‑ ITIL V3 Service Manager – zertifizierter ITIL V3 Expert

​Auf Grund der EU‑DSGVO nutzen wir KAIZALA<https://products.office.com/en/business/microsoft-kaizala> von<threema://add/?id=W2A29XBH> Microsoft.
​WhatsApp <https://www.horizont.at/home/news/detail/datenschutz-whatsapp-als-risiko-fuer-unternehmen.html> dürfen wir aus datenschutzrechtlichen Gründen nicht mehr verwenden.

​itbcs – it business consulting & solutions e. U. achtet Ihre Privatsphäre. Um mehr zu erfahren können Sie unsere Datenschutzbestimmung Online lesen: Datenschutz
<https://www.itbcs.at/datenschutz/>

​Diese Nachricht und die darin enthaltenen Informationen sowie Daten in angehängten Dateien können vertraulich oder rechtlich privilegiert sein.
​Falls Sie diese Nachricht versehentlich erhalten haben sollten, ist die Verwendung des Inhalts oder Weitergabe an Dritte strengstens untersagt.
​Bitte informieren Sie uns über die falsche Zustellung und löschen Sie diese e‑mail. Vielen Dank.
​Wir übernehmen keine Haftung für Schäden, die durch einen Virus entstehen, der mit dieser e‑mail verschickt worden sein könnte.

​This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed.
​If you have received this email in error please notify the system manager.
​Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.
​Finally, the recipient should check this email and any attachments for the presence of viruses.
​The company accepts no liability for any damage caused by any virus transmitted by this email.


​​itbcs – it business consulting & solutions e. U. ist ein Unternehmen registriert in Österreich beim Landesgericht Ried im Innkreis ​unter der
​Firmenbuchnummer 398119w ​und der Gewerberegisternummer 40416221
​Sitz: Österreich | 5270 Burgkirchen | Wollöster 45

Von: Alexander Reinert <notifications@github.com>
Gesendet: Dienstag, 10. Dezember 2019 09:24
An: alexreinert/piVCCU <piVCCU@noreply.github.com>
Cc: jens.lumpe@itbcs.at; Author <author@noreply.github.com>
Betreff: Re: [alexreinert/piVCCU] Firmware 3.47.22 und HmIP-SRH (#203)


Ist hier noch was offen?
