### ISSUE TITLE
[Frage] Pin Mapping ändern

### ISSUE THREAD

**Issue by Hofei90** [alexreinert/piVCCU#204]
Hallo,
vorab erstmal großes Lob und Danke für das piVCCU Projekt.
Hab es jetzt einen Monat im Einsatz und bin sehr zufrieden damit. 

Ich verwende das RPI-RF-MOD Funkmodul, möchte dieses jedoch mit Kabel am Pi verbinden und nicht aufstecken. Ist es möglich, die verwendeten Pins zu ändern, wenn ja an welcher Stelle muss ich dies tun?

**Comment by alexreinert** [comment]
Es braucht dafür ein eigenes Device Tree Overlay, Details kann man in der Datei create_modules_raspberrypi.sh und dts/pivccu-raspberrypi.dts sehen.
Allerdings kann man nur einen Teil der Pins umbiegen, weil die Pins für UART und I2C hardwareseitig fix zugeordnet sind.
Je nach Anforderung würde ich da mal einen Blick auf die Platine HB-RF-USB werfen, ggf. löst dass dein Problem ohne Bastelei, damit kann man das RPI-RF-MOD dann per USB an den Pi anschließen.

**Comment by alexreinert** [comment]
Ist die Frage damit beantwortet, oder ist noch was offen?

**Comment by Hofei90** [comment]
Hallo,
danke für deine schnelle Antwort.
Meine Frage ist vorerst beantwortet ja. Habe es nur noch nicht umgesetzt. Werde ich aber schon hinbekommen.
Vielen Dank für die schnelle Hilfestellung.
