### ISSUE TITLE
Raspbian system/ssh login not working anymore after installing piVCCU

### ISSUE THREAD

**Issue by d4rkd3v1l** [alexreinert/piVCCU#206]
I installed piVCCU on a Raspberry Pi 3, Raspbian according to the manual provided here: https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md

Unfortunately I'm not able to login in either via ssh nor "physically" using my previous default login (pi). So basically I'm only able to access the CCU Webinterface, but have no way to login to the pi itself, which kinda really sux :(

**Comment by alexreinert** [comment]
Kinda strange as there are no changes made to all of the security settings.
Just to confirm: Which IP are you using for the SSH connection, the IP if the host or the IP of the CCU container?
And for the local login: Did this work before or are there maybe some characters i n the password which are keyboard layout dependant like y/z or the special characters?

**Comment by d4rkd3v1l** [comment]
Thanks for you fast follow up.

Turned out restoring backup led to static network settings being enforced and causing this issue. I "just" had to disable static network settings in CCU, reboot and everything got back working.
