### ISSUE TITLE
Raspberry4 +piVCCU erkennt kein CUL- Stick

### ISSUE THREAD

**Issue by mopetfahrer** [alexreinert/piVCCU#207]
Hallo,
Habe einen Raspberry4 mit fertig Image von IOBrocker +Pivccu und RPI-RF-MOD.
Anlernen eines CUL-Stick funktioniert nicht. Andere CCU Komponenten normale Funktion.

Meldung CUxD
USB 1-1 - USB2.0 Hub [HUB] - Sun Nov 24 11:29:38 2019
USB 1-1.3 - Ultra Fit [STORAGE] - Sun Nov 24 11:29:38 2019
USB 1-1.4 - CUL868 [COMM] - no tty - Sun Nov 24 11:29:38 2019
Kein TTY-Device connected!

Erfolgreich mit HomeMatic-CCU 127.0.0.1:8183 verbunden!

als RPC-Server(INIT) von HomeMatic-CCU (1935) angefordert!

Diese Web-Seite wurde aufgerufen von: 192.168.183.26

CUxD-Uptime(2.3.4): 0 Tag(e) 01:31:18, 203744 Bytes belegt, Compiled Sep 18 2019 17:32:06
CCU-Uptime(3.47.22): 0 Tag(e) 16:01:23, load-average: 0.00 0.00 0.00, 10s-cpu-load: 2.4%
Speicher: Total 3999780k Used 860440k Free 3139340k (Cached 445988k) Available 3541392k
CPU(1): ARMv7 Processor rev 3 (v7l) [108.00 bogomips]
CPU(2): ARMv7 Processor rev 3 (v7l) [108.00 bogomips]
CPU(3): ARMv7 Processor rev 3 (v7l) [108.00 bogomips]
CPU(4): ARMv7 Processor rev 3 (v7l) [108.00 bogomips]
Linux version 4.19.75-v7l+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1270 SMP Tue Sep 24 18:51:41 BST 2019
aktive CCU-Prozesse: ReGaHss(1) rfd(1) hs485d(0) java(1)

sudo pivccu-info
piVCCU version: 3.47.22-32
Kernel modules: Available
Raw UART dev: Available
HMRF Hardware: RPI-RF-MOD
HMIP Hardware: RPI-RF-MOD
Board serial: 58A9A71FFE
Radio MAC: unknown
SGTIN: 3014F711A0001F58A9A71FFE
State: RUNNING
PID: 15033
IP: 192.168.183.29
CPU use: 37.39 seconds
BlkIO use: 48.11 MiB
Memory use: 232.35 MiB
KMem use: 14.84 MiB
Link: vethpivccu
TX bytes: 2.07 MiB
RX bytes: 2.41 MiB
Total bytes: 4.48 MiB

sudo dpkg-reconfigure pivccu3
Mehrfach ausgeführt, ohne Erfolg, weder Cul noch USB

Können Sie mir helfen?
Gruß Mopetfahrer

**Comment by gimbli** [comment]
Hallo Mopetfahrer,

bei der Vorgängerversion (pivccu) gab es unter /etc/pivccu eine post-start.sh in der das entsprechende /dev/ eingetragen wurde.

Bei der pivccu3 funktioniert das leider nicht. Vielleicht hilft es dir aber den Fehler weiter einzugrenzen.

Ich habe bis jetzt leider auch noch keine Lösung gefunden. 

Gruß 

Gimbli

**Comment by alexreinert** [comment]
Wird der Stick bei dpkg-reconfigure? Wenn ja, wurde der Stick da auch markiert, bevor der Dialog mit OK beendet wurde?

**Comment by mopetfahrer** [comment]
Der Stick wird korrekt erkannt in dpkg-reconfigure. Er kann über den Cursor ausgewählt werden und ich habe dann mit enter bestätigt. Der Dialog wurde ohne auf OK zu gehen beendet. Anschießen erscheint 
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu.service → /lib/systemd/system/pivccu.service.

**Comment by alexreinert** [comment]
Das ist ein Multiselect Dialog. Mit Enter beendest du den Dialog. Mit Leertaste kann man einzelne Option an- bzw abhaken.

**Comment by mopetfahrer** [comment]
Danke für die Hilfe. Hab bei PayPal was geschickt.
Gruß mopetfahrer

**Comment by DanielReichelt** [comment]
Habe ziemlich ähnliches Problem - verstehe aber nicht die Lösungsbeschreibung.

Habe Homematic und Homematic IP Geräte eingebunden auf einem Raspi 3. Die Homematic Geräte habe ich noch unter FHEM eingebunden mit einem CUL (Busware CC1101-USB-Lite (CUL). Die IP Geräte nutze ich in der piVCCU über das HMIP-RFUSB Funkmodul. Nun möchte ich gerne FHEM auflösen und alle Homematic Geräte unter der piVCCU einbinden. Nach meinem Verständnis müßte ich nur die CUL auf piVCCU einbinden. Doch hier komme ich nicht weiter.
Zunächst einmal die Frage: Geht das überhaupt zusammen oder brauche ich eh ein anderes Funkmodul?

Hier meine pivccu-info

piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  FAKE_HMRF
 Connected via:  (/dev/)
 Board serial:  FKE4614339
 Radio MAC:     0x70e660
HMIP Hardware:  HMIP-RFUSB-TK
 SGTIN:         3014F5AC94000416FB533E0C
 Radio MAC:     0xB041CB
State:          RUNNING
PID:            5010
IP:             192.168.178.60
CPU use:        70.34 seconds
BlkIO use:      1.21 MiB
Memory use:     109.97 MiB
KMem use:       4.59 MiB
Link:           vethpivccu
 TX bytes:      1.33 MiB
 RX bytes:      1.49 MiB
 Total bytes:   2.81 MiB

Habe "sudo dpkg-reconfigure pivccu3" ausgeführt und HmIP ausgewählt und unter USB das ausgewählt "/dev/ttyACM0"

Doch wenn ich mich per SSH auf die pivccu finde ich es auch unter den mounts wieder:
devtmpfs on /dev/ttyACM0 type devtmpfs (rw,relatime,size=469544k,nr_inodes=117386,mode=755)

Wie kann ich nun die Funktion überprüfen? Ich kann zumindest keine neuen Homematic Geräte anlernen.

**Comment by alexreinert** [comment]
Im Readme sind die verschiedenen unterstützten Funkmodule aufgeführt inkl. der Protokolle, welche dann jeweils unterstützt werden. Der CUL gehört nicht dazu.

**Comment by DanielReichelt** [comment]
Ah, besten Dank für die prompte Antwort!
Jetzt verstehe ich auch den Abschnitt Supported Radio modes ein wenig besser. ;-)
Verstehe ich es demnach richtig, dass wenn ich in Zusammenhang mit einem HmIP-RFUSB USB-Stick nur HmRF Geräte einbinden mit einem HM-LGW-O-TW-W-EU Gerät? Oder funktioniert ein HM-MOD-RPI-PCB für HmRF Geräte in Zusammenhang mit dem HmIP-RFUSB auch?
Oder anders herum gefragt: Möchte man HmRF und HmIP Geräte verwenden, benötigt man beide Adapter HM-MOD-RPI-PCB and RPI-RF-MOD?

**Comment by alexreinert** [comment]
- HM-MOD-RPI-PCB kann (gleichzeitig) HmIP (Funk) und HmRF
- RPI-RF-MOD kann (gleichzeitig) HmIP (Funk) und HmRF und nur damit ist es möglich einen HmIP-HAP und HmIPW-DRAP zu nutzen
- HmIP-RFUSB kann nur HmIP Funk
- HM-LGW-O-TW-W-EU kann nur HmRF

Wenn du also beide (Funk) Welten willst, brauchst du entweder ein HM-MOD-RPI-PCB oder ein RPI-RF-MOD oder die Kombination HmIP-RFUSB und HM-LGW-O-TW-W-EU.

**Comment by DanielReichelt** [comment]
Besten Dank für die Klarstellung!
