### ISSUE TITLE
Firmware 3.47.22 webui

### ISSUE THREAD

**Issue by T1mey** [alexreinert/piVCCU#208]
Kann es sein, dass es Probleme mit der Version 3.47.22 gibt.
Bei mir hängt sich die Webui ständig (alle 30 Sekunden) auf und ich muss die Session neu starten. 

Running on rpi3 mit buster.

**Comment by alexreinert** [comment]
Wäre mir absolut nichts zu bekannt. Aber mit so wenig Informationen ist es auch unmöglich irgendetwas zu sagen.

**Comment by T1mey** [comment]
Das UI friert einfach ein und ist komplett grau hinterlegt.

**Comment by T1mey** [comment]
Nach ein paar sekunden kommt die Meldung

Eine Komponente der Homematic Zentrale reagiert nicht mehr.
Hierfür kann es eine Reihe von Ursachen geben:

es besteht keine Netzwerk-Verbindung
die Stromversorung der HomeMatic Zentrale wurde unterbrochen
mindestens eine Komponente der HomeMatic Zentrale ist abgestürzt
Überprüfen Sie die Netzwerk-Verbindung und die Stromversorgung der HomeMatic Zentrale. Starten Sie ggf. die HomeMatic Zentrale neu.

**Comment by alexreinert** [comment]
Das ist ja jetzt schonmal etwas konkreter. Die WebUI friert also nicht ein, sondern es wird ein Dialog modal angezeigt. Wie ist der Titel des Dialogs? Was ergibt pivccu-info auf dem Host? Welches Funkmodul ist angeschlossen? Wie erfolgt die Stromversorgung?

**Comment by real-easy** [comment]
nur ne idee am rande, den browser-cache hast du nach dem update aber schon mal gelöscht ? 



Von: "T1mey" <notifications@github.com> 
An: "alexreinert/piVCCU" <piVCCU@noreply.github.com> 
CC: "Subscribed" <subscribed@noreply.github.com> 
Gesendet: Dienstag, 26. November 2019 12:31:46 
Betreff: Re: [alexreinert/piVCCU] Firmware 3.47.22 webui (#208) 



Nach ein paar sekunden kommt die Meldung 

Eine Komponente der Homematic Zentrale reagiert nicht mehr. 
Hierfür kann es eine Reihe von Ursachen geben: 

es besteht keine Netzwerk-Verbindung 
die Stromversorung der HomeMatic Zentrale wurde unterbrochen 
mindestens eine Komponente der HomeMatic Zentrale ist abgestürzt 
Überprüfen Sie die Netzwerk-Verbindung und die Stromversorgung der HomeMatic Zentrale. Starten Sie ggf. die HomeMatic Zentrale neu.

**Comment by alexreinert** [comment]
Ohne Antworten auf meine Fragen kann ich nicht wirklich helfen...

**Comment by alexreinert** [comment]
Keine Rückmeldung --> Closed.
Bitte ggf. wieder aufmachen.
