### ISSUE TITLE
Fehlermeldung nach CCU3 install

### ISSUE THREAD

**Issue by Radix1975** [alexreinert/piVCCU#209]
Hi Leute Ich habe mir eine Respberry 4 gekauft.

ab Schritt  5 weis ich nicht mehr weiter  der Googel übersetzer geht nicht für die Seite 
Frage dashalb 
: Benötige ich schritt 5?
: Benötige ich schritt 6: ?
Benötige ich schritt  7:?
Zu Schritt 7 der hat ja 3 Punkte muss ich alle 3 machen oder nur 1 und 3 für feste IP
muss ich bei der 3 meine IP Daten eintragen? müssen die <> bleiben und die IP dort rein?
bekomme folgende Fehlermeldung bei Schritt 9 sudo apt install pivccu3
 ### Netzwerkbrücke nicht gefunden und ### Modul nicht erkannt was mache ich falsch?

Gibt es eine Möglichkeit  ohne neues aufsetzen des Kompletten IMAGE + Einrichtung auf Der Raspie   pivccu3 nochmal  neu zu installieren?

Danke für die Antworten

**Comment by alexreinert** [comment]
Schritt 5 und 6 müssen durchgeführt werden, wenn ein Funkmodul auf den GPIO Header aufgesteckt wird. Bei Schritt 5 hat man dabei zwei Optionen: Bluetooth deaktivieren oder Bluetooth an den Software UART binden.
Schritt 7 muss durchgeführt werden. Der erste Punkt auf jeden Fall um zu prüfen, ob die Netzwerkschnittstelle wirklich eth0 heißt. Danach dann entweder Punkt 2 oder 3, je nachdem, ob man DHCP oder fixe Adressen will. Die spitzen Klammern müssen ersetzt werden, das ist die "normale" Schreibweise für Pflichtparameter.

Komplett neu aufsetzen ist normalerweise nicht notwendig, einfach die Schritte nachholen und danach neu starten.

**Comment by Radix1975** [comment]
bekomme folgende Fehlermeldung was kann ich machen?

dpkg: Fehler beim Bearbeiten des Paketes postfix (--configure):
 »installiertes postfix-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 75 zurück
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von nginx:
 nginx hängt ab von nginx-full (<< 1.14.2-2+deb10u1.1~) | nginx-light (<< 1.14.2-2+deb10u1.1~) | nginx-extras (<< 1.14.2-2+deb10u1.1~); aber:
  Paket nginx-full ist noch nicht konfiguriert.
  Paket nginx-light ist nicht installiert.
  Paket nginx-extras ist nicht installiert.
 nginx hängt ab von nginx-full (>= 1.14.2-2+deb10u1) | nginx-light (>= 1.14.2-2+deb10u1) | nginx-extras (>= 1.14.2-2+deb10u1); aber:
  Paket nginx-full ist noch nicht konfiguriert.
  Paket nginx-light ist nicht installiert.
  Paket nginx-extras ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes nginx (--configure):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Fehler traten auf beim Bearbeiten von:
 nginx-full
 postfix
 nginx

**Comment by alexreinert** [comment]
Weder postfix noch nginx sind Teil oder Abhängigkeit von piVCCU, so dass ich dazu keinen Support geben kann.

Ist zur ursprünglichen Anfrage alles geklärt?

**Comment by Radix1975** [comment]
Zu Punkt 5 ich habe ja eine Raspberry  4 ist er auch hier erforderlich?

Enable UART GPIO pins (only on Enable UART GPIO pins (only on Raspberry Pi 3)
 
Allgemeine Frage kann es sein das Ich nach der Installation  Kein HDMI Bild  mehr  bekomme ?
Ich habe dort einen Monitor den ich gerne nutzen würde.

**Comment by alexreinert** [comment]
Punkt 5: Bitte auch bei 4er durchführen.

Am HDMI wird eigentlich nichts verändert.

**Comment by Radix1975** [comment]
Hi Leute ich hab jetzt die Raspberry soweit das er  das Funckodul findet und es blinkt auch blau :-)
allerdings seht sie nicht in der Fritzbox und ist auch unter der von mir angegebenen Aderesse
nicht zu erreichen ( IP:  192.168.1.XXX die x sind von mir fürs Forum gesetzt es sind eigendlich Zahlen)

Außerdem mußte ich mir Rootrechte verschaffen um die ursprüngliche IP Adresse  in der /var/lib/piVCCU3/userfs/etc/config/netconfg ändern zu können


Warum komme ich nicht auf die Webseite der Homematic was ist hier noch falsch ?   
Radio MAC:      unknown  ?
sudo pivccu-info

piVCCU version: 3.47.22-32
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
HMIP Hardware:  RPI-RF-MOD
Board serial:   58A9A72ADA
Radio MAC:      unknown
SGTIN:          3014F711A0001F58A9A72ADA
State:          RUNNING
PID:            888
IP:             192.168.1.XXX
CPU use:        39.39 seconds
BlkIO use:      44.08 MiB
Memory use:     136.16 MiB
KMem use:       4.55 MiB
Link:           vethpivccu
 TX bytes:      84.94 KiB
 RX bytes:      38.76 KiB
 Total bytes:   123.70 KiB

**Comment by alexreinert** [comment]
Wie sieht die Datei netconfig jetzt genau aus? Was liefert ifconfig auf dem Host?

**Comment by Radix1975** [comment]
Inhalte stimmen nicht überein der Inhalt der Netconfic soll meine IP werden 192.168.1226

netconfic
HOSTNAME=ccu3-webui
MODE=MANUAL
CURRENT_IP=192.168.1.226
CURRENT_NETMASK=255.255.255.0
CURRENT_GATEWAY=192.168.1.1
CURRENT_NAMESERVER1=192.168.1.1
CURRENT_NAMESERVER2=0.0.0.0
IP=192.168.1.226
NETMASK=255.255.255.0
GATEWAY=192.168.1.1
NAMESERVER1=192.168.1.1
NAMESERVER2=0.0.0.0
CRYPT=0

sudo ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.14  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::d3e6:eb13:edd3:2110  prefixlen 64  scopeid 0x20<link>
        inet6 2a02:810a:1c0:55b:6eee:dda:3a6:51d4  prefixlen 64  scopeid 0x0<global>
        ether dc:a6:32:49:ae:73  txqueuelen 1000  (Ethernet)
        RX packets 4360  bytes 558172 (545.0 KiB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 1241  bytes 477037 (465.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Lokale Schleife)
        RX packets 33  bytes 1964 (1.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 33  bytes 1964 (1.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethpivccu: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.18.55  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::fc09:10ff:fed1:3fb2  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::3191:c5b2:5226:631c  prefixlen 64  scopeid 0x20<link>
        ether fe:09:10:d1:3f:b2  txqueuelen 1000  (Ethernet)
        RX packets 556  bytes 24148 (23.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 51  bytes 13026 (12.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.40  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 2a02:810a:1c0:55b:5d48:6f21:6032:d491  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::fb34:1250:4630:51fc  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:49:ae:74  txqueuelen 1000  (Ethernet)
        RX packets 4618  bytes 499034 (487.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 81  bytes 11151 (10.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
@alexreinert

**Comment by alexreinert** [comment]
Schritt 7 nicht beachtet oder danach keinen Reboot gemacht.

**Comment by Radix1975** [comment]
ok und jetzt Schritt 7 wiederholen? @alexreinert

**Comment by alexreinert** [comment]
ja und danach einen Reboot

**Comment by Radix1975** [comment]
Ok ich melde mich Später ob es geklappt hat ist das ein Sicherheitsproblem wenn meine IP Daten hier stehen?

**Comment by alexreinert** [comment]
Bei IPs aus dem Range 192.168.x.x nur, wenn man Aluhutträger ist.

**Comment by Radix1975** [comment]
So irgendwie ist es jetzt so das sowohl die Raspberry  als auch das piVCCU3 die  gleiche Adresse  192.168.1.255 haben  deshalb kann ich nichts aufrufen.
Wo muss ich das ändern? Adressbereich Fritz Box bis max 255  ich hätte gerne 200 für die CCU und z.B 201 für die Raspberry

**Comment by alexreinert** [comment]
In den genannten Config Dateien.

**Comment by Radix1975** [comment]
So die HomeMatic geht jetzt erstmal Danke dafür.
Allerdings hab ich jetzt keinen Internetzugang an der Raspberry  mehr und das WIFI Land läst sich nicht dauerhaft setzen .

**Comment by alexreinert** [comment]
Dass meine Anleitung nicht 1:1 genutzt wurde, ist ja offensichtlich. Und da ich nicht weiß, was du alles gemacht hast, ist es schwer zu helfen.

**Comment by alexreinert** [comment]
Scheinbar nicht, Closed
