### ISSUE TITLE
Tinkerboard und er aktuelle Kernel

### ISSUE THREAD

**Issue by Psycho0verload** [alexreinert/piVCCU#213]
Hallo,

vielen Dank für deine Arbeit in piVCCU! Seit dem ich die Software benutze ist mein Leben mit Homematic deutlich leichter :)

Seit dem 19.11.2019 gibt es für Tinkerboard Armbian den Kernel 5.3.11 und das funktionierende Image mit Kernel 4.19.57 ist nicht mehr verfügbar und wird auch nicht mehr zum download angeboten. 

Siehst du eine Möglichkeit, dass piVCCU in Zukunft auf dem Tinkerboard läuft?

Vielen Dank für deine Arbeit.

LG Psycho0verload

**Comment by Psycho0verload** [comment]
Ich habe zum Glück im Netz noch ein Torrent gefunden mit dem letzten funktionierenden Armbian. [rmbian_5.90_Tinkerboard_Debian_buster_next_4.19.57.7z](http://mirror.psycho0verload.de/Tinkerboard/Linux/Armbian/Armbian_5.90_Tinkerboard_Debian_buster_next_4.19.57.7z)

**Comment by alexreinert** [comment]
piVCCU läuft schon sehr lange auch auf dem Kernel 5.3.
Leider braucht die Armbian Header mal wieder eine extra Einladung. Ich habe die Anleitung für die Installation etwas optimiert, mit dieser funktioniert die Installation dann auch problemlos mit dem Image vom 19.11.

**Comment by Psycho0verload** [comment]
Vielen Dank für die Ergänzung, damit konnte ich mein Problem lösen!

```
sudo apt install build-essential bison flex libssl-dev
sudo apt install "dpkg --get-selections | grep 'linux-image-' | grep '\sinstall' | sed -e 's/linux-image-\([a-z0-9-]\+\).*/linux-headers-\1/'"
sudo dpkg-reconfigure pivccu-modules-dkms
sudo apt install --reinstall pivccu
```

P.s.: Ticket kann damit zu :)
