### ISSUE TITLE
HM-MOD-RPI-PCB not detected

### ISSUE THREAD

**Issue by xentity** [alexreinert/piVCCU#214]
Fresh Raspian 10 installation with:

- Raspberry Pi 3
- HMIP is HM-MOD-RPI-PCB
- Bluetooth bound to softUART
- PiVCCU3
- Installation with unbound brigde and NAT

If I reconfigure pivccu3, I choose `HM-MOD-RPI-PCB or HM-RF-MOD`. On the next screen, the device is not listed (an other UART stick for cheap plugs only, but I also tried to boot without plugged in CUL stick).

I tried the sdcard and the module also with an other Raspi (same model and revision) with no difference. The module is supplied with 3.3V .

```
<12>Dec 12 13:18:48 piVCCU3: HMRF hardware was not detected
<12>Dec 12 13:18:48 piVCCU3: HMIP hardware was not detected
```

Any ideas to debug this issue?

**Comment by alexreinert** [comment]
The module will not be shown on the second screen, as it is no USB device.
To debug a little bit deeper: Please provide the output of pivccu-info

**Comment by xentity** [comment]
```
$ sudo pivccu-info
piVCCU version: 3.47.22-32
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown <-------
HMIP Hardware:  unknown <-------
Board serial:   unknown <-------
Radio MAC:      unknown <-------
SGTIN:          unknown
State:          STOPPED
```
I was able to access the web interface once (but with no module). The marked part was always the same.

```
$ sudo service pivccu restart
$ sudo journalctl -xe

Dec 12 15:02:27 homecon01 piVCCU3[1348]: HMIP hardware was not detected
Dec 12 15:02:27 homecon01 start_container.sh[1318]: <12>Dec 12 15:02:27 piVCCU3: HMIP hardware was not detected
Dec 12 15:02:28 homecon01 start_container.sh[1318]: kernel.sched_rt_runtime_us = -1
Dec 12 15:02:28 homecon01 kernel: br0: port 1(vethpivccu) entered blocking state
Dec 12 15:02:28 homecon01 kernel: br0: port 1(vethpivccu) entered disabled state
Dec 12 15:02:28 homecon01 kernel: device vethpivccu entered promiscuous mode
Dec 12 15:02:28 homecon01 kernel: IPv6: ADDRCONF(NETDEV_UP): vethpivccu: link is not ready
Dec 12 15:02:28 homecon01 kernel: eth0: renamed from vethK0TEYF
Dec 12 15:02:28 homecon01 systemd-networkd[148]: vethpivccu: Gained carrier
Dec 12 15:02:28 homecon01 systemd-networkd[148]: br0: Gained carrier
Dec 12 15:02:28 homecon01 kernel: IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Dec 12 15:02:28 homecon01 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Dec 12 15:02:28 homecon01 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethpivccu: link becomes ready
Dec 12 15:02:28 homecon01 kernel: br0: port 1(vethpivccu) entered blocking state
Dec 12 15:02:28 homecon01 kernel: br0: port 1(vethpivccu) entered forwarding state
Dec 12 15:02:28 homecon01 start_container.sh[1318]: lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 842 Received container state "ABORTING" instead of "RUNNING"
Dec 12 15:02:28 homecon01 start_container.sh[1318]: lxc-start: lxc: tools/lxc_start.c: main: 330 The container failed to start
Dec 12 15:02:28 homecon01 start_container.sh[1318]: lxc-start: lxc: tools/lxc_start.c: main: 333 To get more details, run the container in foreground mode
Dec 12 15:02:28 homecon01 start_container.sh[1318]: lxc-start: lxc: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfile and --logpriority options
Dec 12 15:02:28 homecon01 systemd[1]: Started piVCCU.
-- Subject: A start job for unit pivccu.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit pivccu.service has finished successfully.
-- 
-- The job identifier is 594.
Dec 12 15:02:28 homecon01 sudo[1306]: pam_unix(sudo:session): session closed for user root
Dec 12 15:02:28 homecon01 systemd[1]: pivccu.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit pivccu.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 12 15:02:28 homecon01 systemd[1]: pivccu.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit pivccu.service has entered the 'failed' state with result 'exit-code'.
Dec 12 15:02:28 homecon01 systemd-networkd[148]: vethpivccu: Lost carrier
Dec 12 15:02:28 homecon01 systemd-networkd[148]: vethpivccu: Removing non-existent address: fe80::fc20:bbff:fef0:1589/64 (valid forever), ignoring
Dec 12 15:02:28 homecon01 kernel: br0: port 1(vethpivccu) entered disabled state
Dec 12 15:02:28 homecon01 kernel: device vethpivccu left promiscuous mode
Dec 12 15:02:28 homecon01 kernel: br0: port 1(vethpivccu) entered disabled state
Dec 12 15:02:29 homecon01 systemd-networkd[148]: br0: Lost carrier
Dec 12 15:02:35 homecon01 sudo[1538]:       pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/bin/journalctl -xe
```

**Comment by alexreinert** [comment]
Please provide content of /boot/config.txt and the output of this command:
`dpkg --get-selections | grep pivccu`

**Comment by xentity** [comment]
```
$ more /boot/config.txt | grep -Ev "^([#\s])"
dtparam=audio=on

[pi4]
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
enable_uart=1
dtoverlay=pi3-miniuart-bt
enable_uart=1
force_turbo=1
core_freq=250
```
and 

```
$ dpkg --get-selections | grep pivccu
pivccu-modules-dkms				install
pivccu-modules-raspberrypi			install
pivccu3						install
```

**Comment by alexreinert** [comment]
This is not the full /boot/config.txt but it seems, that you removed the line dtoverlay=pivccu-raspberrypi which is added by the package pivccu-modules-raspberrypi.
To fix this:
`sudo apt install --reinstall pivccu-modules-raspberrypi` followed by a reboot. After that in pivccu-info the Raw UART dev and the radio module should be found.

**Comment by xentity** [comment]
```
$ sudo pivccu-info
piVCCU version: 3.47.22-32
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   PEQ2216793
Radio MAC:      0x6be060
SGTIN:          3014F711A061A7D8A9AB3B59
State:          RUNNING
PID:            846
IP:             192.168.253.2
CPU use:        24.92 seconds
BlkIO use:      55.31 MiB
Memory use:     147.20 MiB
KMem use:       4.46 MiB
Link:           vethpivccu
 TX bytes:      15.85 KiB
 RX bytes:      17.37 KiB
 Total bytes:   33.21 KiB
```

Great. Many thanks. Works great!! I guess I removed it when I tried from one bluetooth method to the other.



By the way: when I deinstalled dhcpcd, the device stopped networking, which may be a pain for headless RPis. In the manual the paragraph should be look like this:
```
$ systemctl disable dhcpcd.service
$ systemctl enable networking
``` 
After that, `/etc/network/interfaces` is respected again.

My run-at-once file looks like this:```

$ more install_pivccu.sh
#/bin/bash

wget -q -O - https://www.pivccu.de/piVCCU/public.key | sudo apt-key add -
sudo bash -c 'echo "deb https://www.pivccu.de/piVCCU stable main" > /etc/apt/sources.list.d/pivccu.list'
sudo apt update
sudo apt install raspberrypi-kernel-headers pivccu-modules-dkms pivccu-modules-raspberrypi

bash -c 'cat << EOT >> /boot/config.txt
dtoverlay=pi3-miniuart-bt
enable_uart=1
force_turbo=1
core_freq=250
EOT'

sudo sed -i /boot/cmdline.txt -e "s/console=serial0,[0-9]\+ //"
sudo sed -i /boot/cmdline.txt -e "s/console=ttyAMA0,[0-9]\+ //"


###########################
# Networking              #
###########################
# Hint: enable networking is important!!
#

systemctl disable dhcpcd.service
systemctl enable networking

sudo apt install bridge-utils
sudo bash -c 'cat << EOT > /etc/network/interfaces
source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback

EOT'

sudo bash -c 'cat << EOT > /etc/wpa_supplicant/wpa_supplicant.conf
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=DE

network={
	ssid="<yourssid>"
	psk="<yourPSK>"
	key_mgmt=WPA-PSK
}
EOT'


sudo bash -c 'cat << EOT > /etc/network/interfaces.d/wlan0
allow-hotplug wlan0
auto wlan0
iface wlan0 inet static
	wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
	address 192.168.5.64
	netmask 255.255.255.0
	gateway 192.168.5.1
	dns-nameservers 192.168.5.1

EOT'

sudo bash -c 'cat << EOT > /etc/network/interfaces.d/br0
auto br0
iface br0 inet static
  bridge_ports none
  bridge_fd    0
  address      192.168.253.1
  netmask      255.255.255.0
EOT'


sudo systemctl stop pivccu
sudo bash -c 'cat << EOT > /var/lib/piVCCU3/userfs/etc/config/netconfig
HOSTNAME=homematic-ccu2
MODE=MANUAL
CURRENT_IP=192.168.253.2
CURRENT_NETMASK=255.255.255.0
CURRENT_GATEWAY=192.168.253.1
CURRENT_NAMESERVER1=8.8.4.4
CURRENT_NAMESERVER2=8.8.8.8
IP=192.168.253.2
NETMASK=255.255.255.0
GATEWAY=192.168.253.1
NAMESERVER1=8.8.4.4
NAMESERVER2=8.8.8.8
CRYPT=0
EOT'

sudo bash -c 'cat << EOT > /etc/network/if-up.d/pivccu
#!/bin/sh

HOST_IF=wlan0
BRIDGE=br0
HOST_IP=192.168.253.1
CCU_IP=192.168.253.2

if [ "\$IFACE" = "\$BRIDGE" ]; then
  echo 1 > /proc/sys/net/ipv4/ip_forward
  iptables -A FORWARD -i \$IFACE -s \$HOST_IP/24 -m conntrack --ctstate NEW -j ACCEPT
  iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  iptables -A POSTROUTING -t nat -j MASQUERADE

  iptables -t nat -A PREROUTING -p tcp -i \$HOST_IF --dport 80 -j DNAT --to-destination \$CCU_IP:80
  iptables -t nat -A PREROUTING -p tcp -i \$HOST_IF --dport 1999 -j DNAT --to-destination \$CCU_IP:1999
  iptables -t nat -A PREROUTING -p tcp -i \$HOST_IF --dport 2000 -j DNAT --to-destination \$CCU_IP:2000
  iptables -t nat -A PREROUTING -p tcp -i \$HOST_IF --dport 2001 -j DNAT --to-destination \$CCU_IP:2001
  iptables -t nat -A PREROUTING -p tcp -i \$HOST_IF --dport 2002 -j DNAT --to-destination \$CCU_IP:2002
  iptables -t nat -A PREROUTING -p tcp -i \$HOST_IF --dport 2010 -j DNAT --to-destination \$CCU_IP:2010
  iptables -t nat -A PREROUTING -p tcp -i \$HOST_IF --dport 8181 -j DNAT --to-destination \$CCU_IP:8181
  iptables -t nat -A PREROUTING -p tcp -i \$HOST_IF --dport 8183 -j DNAT --to-destination \$CCU_IP:8183
  iptables -t nat -A PREROUTING -p tcp -i \$HOST_IF --dport 8700 -j DNAT --to-destination \$CCU_IP:8700
  iptables -t nat -A PREROUTING -p tcp -i \$HOST_IF --dport 8701 -j DNAT --to-destination \$CCU_IP:8701
fi
EOT'
sudo chmod +x /etc/network/if-up.d/pivccu
```
Instead of port forwarding I'm thinking about to create a sub IP (say 192.168.5.65) and forward everything to 192.168.253.2 and masq everything to this sub IP. What do you think?

**Comment by alexreinert** [comment]
I did the installation several times and my network never went down.

**Comment by xentity** [comment]
@alexreinert I'm not sure, if it is relevant for Debian Jessy only (since it is not supported by this project it may be irrelevant at all), but in my last installation it ignored the interfaces file, it expected to be configured via dhcpcd.conf .
Reference: [https://superuser.com/a/1182667](https://superuser.com/a/1182667)
