### ISSUE TITLE
Anlernen klappt nicht

### ISSUE THREAD

**Issue by Saboti** [alexreinert/piVCCU#216]
Hallo Alex,

habe auf meinem Orangepiplus2e pivccu installiert. 
Als Hardware habe ich einen HmIP-RFUSB zusammengebaut.
Pivccu läuft und ich komme auf die Webseite. 
Ausgabe pivccu-info:
`piVCCU version: 3.47.22-32
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  FAKE_HMRF
HMIP Hardware:  HMIP-RFUSB
Board serial:   FKE3318691
Radio MAC:      0xdc42d9
SGTIN:          3014F711A000041709ADFCF1
State:          RUNNING
PID:            1572
IP:             192.168.0.129
CPU use:        204.11 seconds
BlkIO use:      47.79 MiB
Memory use:     113.85 MiB
KMem use:       5.58 MiB
Link:           vethpivccu
 TX bytes:      5.63 MiB
 RX bytes:      18.99 MiB
 Total bytes:   24.62 MiB`

Wollte nun ein Gerät anlernen. 
Zuerst abgemeldet im Gateway und auf Werkseinstellungen zurückgesetzt. 
Dann auf Geräte anlernen und Hmip anlernen angeklickt. 
Timer läuft. Im Gerät Batterie rein. 
Taucht aber nichts im Posteingang auf.

Evtl. Hast Du ja noch eine Idee? 

Gibt es eine Möglichkeit den Stick zu testen, nicht das meine Anfänger Lötarbeit das Problem ist.

Hier Bilder des Aufbaus:
![IMG_20191222_121145](https://user-images.githubusercontent.com/4627676/71321276-64fae200-24b7-11ea-81f7-40101374549b.jpg)
![IMG_20191222_121152](https://user-images.githubusercontent.com/4627676/71321281-78a64880-24b7-11ea-97c6-a47cff9f715c.jpg)

Gruß Tobias

**Comment by alexreinert** [comment]
Die Bilder sind leider nicht ganz scharf, aber ich sehe da ein paar Lötstellen mit Lötkugeln, welche Potential für kalte Lötstellen haben. Ich würde die alle nochmal sauber nachlöten.
Was für ein Gerät versuchst du anzulernen?

**Comment by Saboti** [comment]
Alles klar danke, dann versuche ich die nochmal sauber nachzulöten.
Ich hab versucht ein HmIP-SWDM-B2 anzulernen.

**Comment by Saboti** [comment]
Habe nun nochmal nachgelötet und nun klappt es mit dem anlernen :)
Danke Dir! 
Gruß Tobias

**Comment by alexreinert** [comment]
Super, danke für die Rückmeldung.
