### ISSUE TITLE
Werteabfrage schlägt bei einem Doppelkanal fehl

### ISSUE THREAD

**Issue by hausbus** [alexreinert/piVCCU#217]
Hallo!
Wir haben einen kombinierten Temperatur/Luftfeuchtigkeitssensor verbaut in unseren Homematic Wired Tastern. Die beiden Werte dieses Sensors werden beide in einem Kanal vom Typ Wetter gemeldet. Lernt man den Taster an, funktioniert alles völlig ohne Probleme und beide Werte werden gemeldet. Wenn man dann die piVCCU neu startet, bleibt der zweite Wert immer 0. Der erste Wert wird weiter normal gemeldet.

In den Logs habe ich folgenden Fehler gefunden.
Irgend eine Idee ? Aufgetreten mit Firmware 3.47.22

Dec 22 20:06:12 ccu3-webui user.debug hs485d: LGW_RPL_RESPONSE
Dec 22 20:06:12 ccu3-webui user.debug hs485d: 00000000: tx_counter=1, SYN=1, stored rx_counter=0, CheckRxCounter=true
Dec 22 20:06:12 ccu3-webui user.err hs485d: HSSParameter::GetValue() id=LEVEL failed getting physical value.
Dec 22 20:06:12 ccu3-webui local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: xmlrpc_bin://127.0.0.1:32000, params: {"HBW0000888:15","LEVEL"}, result: [faultCode:-1,faultString:"Failure"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Dec 22 20:06:12 ccu3-webui local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1390, params: {"HBW0000888:15","LEVEL"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 22 20:06:12 ccu3-webui local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 22 20:06:12 ccu3-webui local0.info ReGaHss: Info: interface name= BidCos-Wired for ID=1390 [GetInterfaceByID():iseXmlRpc.cpp:2552]
Dec 22 20:06:12 ccu3-webui local0.info ReGaHss: Info: XMLRPC 'getDeviceDescription': rpcClient.execute() succeeded (url: xmlrpc_bin://127.0.0.1:32000, params: {"HBW0000888"}, result: [ADDRESS:"HBW0000888",AVAILABLE_FIRMWARE:"2.55",CHILDREN:{"HBW0000888:0","HBW0000888:1","HBW0000888:2","HBW0000888:3","HBW0000888:4","HBW0000888:5","HBW0000888:6","HBW0000888:7","HBW0000888:8","HBW0000888:9","HBW0000888:10","HBW0000888:11","HBW0000888:12","HBW0000888:13","HBW0000888:14","HBW0000888:15","HBW0000888:16","HBW0000888:17","HBW0000888:18","HBW0000888:19","HBW0000888:20","HBW0000888:21","HBW0000888:22","HBW0000888:23","HBW0000888:24","HBW0000888:25","HBW0000888:26","HBW0000888:27","HBW0000888:28","HBW0000888:29","HBW0000888:30","HBW0000888:31","HBW0000888:32"},FIRMWARE:"2.55",FLAGS:1,PARAMSETS:{"MASTER"},PARENT:"",TYPE:"HBW-SD6-Multikey-v1",UPDATABLE:1,VERSION:1]) [CallXmlrpcMethod():iseXmlRpc.cpp:2613]
Dec 22 20:06:12 ccu3-webui local0.info ReGaHss: Info: interface name= BidCos-Wired for ID=1390 [GetInterfaceByID():iseXmlRpc.cpp:2552]

Hier auf das gesamte Logfile

[ccu3-webui-2019-12-22.log](https://github.com/alexreinert/piVCCU/files/3992902/ccu3-webui-2019-12-22.log)

**Comment by alexreinert** [comment]
Wie verhält sich das bei einer original CCU3?

**Comment by hausbus** [comment]
Hallo Alex,
danke für die schnelle Reaktion.
Eine CCU3 konnte ihr ehrlich gesagt gar nicht testen, weil ich keine habe, aber bisher haben uns keinerlei Kunden Probleme mit der Luftfeuchtigkeit gemeldet, weshalb ich schon glaube, dass der Fehler spezifisch für RaspberryMatic und piVCCU ist.

Kann man dem den irgendwie auf die Spur kommen? Gibt es noch weitere Logs ?
Vor allem ists ja seltsam, dass es nach dem Anlernen immer problemlos läuft und nur nach einem CCU Neustart nicht mehr.

Herm

Von: Alexander Reinert <notifications@github.com>
Gesendet: Sonntag, 22. Dezember 2019 20:38
An: alexreinert/piVCCU <piVCCU@noreply.github.com>
Cc: hausbus <info@haus-bus.de>; Author <author@noreply.github.com>
Betreff: Re: [alexreinert/piVCCU] Werteabfrage schlägt bei einem Doppelkanal fehl (#217)


Wie verhält sich das bei einer original CCU3?

**Comment by alexreinert** [comment]
Da piVCCU die gleichen Binaries verwendet, wie die CCU3 glaube ich nicht dran, dass das Problem spezifisch bei piVCCU auftritt.
Ich bin auch ehrlich gesagt etwas irritiert, das ihr Produkte für HMW entwickelt und dann keine CCU3 zum Testen habt.
Mangels Testgeräten kann ich auch nicht ansatzweise nachvollziehen, woher dieses Problem kommen kann, aber selbst mit Testgeräten muss ich mich fragen, warum ich euch kostenlosen Support für eure kommerziellen Produkte geben sollte?

**Comment by hausbus** [comment]
Nein, musst du natürlich nicht.
Wir machen das als Hobby neben dem eigentlichen Job und alles Open Source. Aber du brauchst da keine Zeit investieren. Ich hatte nur gehofft, dass du spontan eine Idee hast.

Danke,
Herm


-------- Ursprüngliche Nachricht --------
Von: Alexander Reinert <notifications@github.com>
Datum: 22.12.19 21:01 (GMT+01:00)
An: alexreinert/piVCCU <piVCCU@noreply.github.com>
Cc: hausbus <info@haus-bus.de>, Author <author@noreply.github.com>
Betreff: Re: [alexreinert/piVCCU] Werteabfrage schlägt bei einem Doppelkanal fehl (#217)


Da piVCCU die gleichen Binaries verwendet, wie die CCU3 glaube ich nicht dran, dass das Problem spezifisch bei piVCCU auftritt.
Ich bin auch ehrlich gesagt etwas irritiert, das ihr Produkte für HMW entwickelt und dann keine CCU3 zum Testen habt.
Mangels Testgeräten kann ich auch nicht ansatzweise nachvollziehen, woher dieses Problem kommen kann, aber selbst mit Testgeräten muss ich mich fragen, warum ich euch kostenlosen Support für eure kommerziellen Produkte geben sollte?

**Comment by alexreinert** [comment]
Mir war nicht bewusst, dass ihr das Opensource macht, das ändert meine Motivation deutlich.
Aber leider kann ich nicht wirklich sagen, was da schiefgeht und ohne Testgerät ist es halt leider nicht nachstellbar.

**Comment by hausbus** [comment]
Ich schätze, dass es irgend ein Bug mit Kanälen ist, die zwei Werte liefern.
Wenn wir es nicht rauskriegen, werden wir wohl zwei Einzelkanäle draus machen müssen. Das ist eigentlich kein Problem, aber die Hardwarebeschreibungs XML wird durch solche Aktionen irgendwie immer inkompatibel. Schauen wir Mal.
Ich könnte dir auch problemlos Mal einen Taster schicken, aber wahrscheinlich müsste wirklich EQ3 ändern.
Irgendwo hab ich da auch noch ein paar Kontakte von der Usergroup.

Grüße
Herm


-------- Ursprüngliche Nachricht --------
Von: Alexander Reinert <notifications@github.com>
Datum: 22.12.19 21:43 (GMT+01:00)
An: alexreinert/piVCCU <piVCCU@noreply.github.com>
Cc: hausbus <info@haus-bus.de>, Author <author@noreply.github.com>
Betreff: Re: [alexreinert/piVCCU] Werteabfrage schlägt bei einem Doppelkanal fehl (#217)


Mir war nicht bewusst, dass ihr das Opensource macht, das ändert meine Motivation deutlich.
Aber leider kann ich nicht wirklich sagen, was da schiefgeht und ohne Testgerät ist es halt leider nicht nachstellbar.
