### ISSUE TITLE
Kopplung von Geräten klappt nicht (Raspi4B/piVCCU3)

### ISSUE THREAD

**Issue by Chippolin** [alexreinert/piVCCU#220]
Hi Alex Reinert,

nach viel Lob meines Umfeldes für das piVCCU Projekt habe ich mich über die Feiertage drangemnacht und wollte es selbst versuchen. 
Leider bisher ohne Erfolg... ich habe nun 4 Tage lang mein System mehrfach neu aufgesetzt, da alle Kopplungsversuche mit der PIVCCU3 nicht klappen... Da auch die Suche in diversen Foren mir leider keine Hilfe liefern, melde ich mich einfach mal direkt selbst...

Folgendes System habe ich aufgesetzt:
Raspi 4B mit 4GB
Funkmodul RPI-RF-MOD (Komplett - kein Bausatz)
Samsung SD 32 GB
Image von ioBroker "ioBroker_Image_RPi_2-3-4_piVCCU_20190723_buster"

Als Kopplungsgeräte sind getestet worden:
Original Homematic Thermostat HmIO-eTRV-2
Original Homematic FensterKontakt HMIP-SWDO

Das update/upgrade habe ich durchgeführt und die Pakete aktualisiert.

Das System bootet tadellos.
Die CCU Seite ist aufrufbar.

Die Kopplung habe ich sowohl über "ohne IP", "mit IP" und mit SGTIN Nummer versucht.
Alles läuft ins Leere...

Nach Start des Kopplungsversuches leuchtet die LED der Funkplatine nicht mehr dauerhaft blau, sondern wechselt zwischen blau und grün.

Das Fehlerlog gibt mir nun reihenweise Fehler aus mit denen ich leider nichts anfangen kann:
[ccu3-webui-2019-12-30 (1).log](https://github.com/alexreinert/piVCCU/files/4010353/ccu3-webui-2019-12-30.1.log)

Gibt es einen Tipp, was ich falsch mache?

LG und schöne Feiertage
Martin

**Comment by alexreinert** [comment]
Wie wurden die Geräte genau angelernt? (Wirklich Schritt für Schritt)

**Comment by Chippolin** [comment]
Guten Morgen,

nach meinem Verständnis und der Anleitung ja. Bei beiden Geräten ist ja nur der Synchronisationsknopf zu drücken, das gelb-orange blinken anzuwarten und dann sollte es klappen.
Auch einen "Werksreset" (Warten auf das rote-Aufblinken) habe ich erfolgreich durchgeführt. Obwohl die Aktoren komplett neu und nicht gebraucht gekauft wurden.

Die Basis (Raspi) habe ich auch mal etwas entfernt vom PC/Monitor um Störungen zu minimieren...

**Comment by alexreinert** [comment]
Habe ich mir fast gedacht. Besseres Vorgehen bei HmIP wäre:
- Werksreset am Gerät machen, auch bei neu gekauften Geräten
- Gerät vom Strom trennen bzw. Batterien raus nehmen
- In der CCU Anlernvorgang starten
- Gerät wieder mit Strom versorgen, nichts drücken
- Warten, bis Countdown abgelaufen ist

Beim Pi4 kommt hinzu, dass der USB3 Controller extrem viel Störstrahlung erzeugt, welche das Funkmodul ziemlich stark negativ beeinflusst, daher sollte man vermeiden, Geräte per USB3 anzuschließen, wenn das Funkmodul räumlich nicht abgesetzt ist.

**Comment by Chippolin** [comment]
Hi,

das probiere ich aus und melde mich.

**Comment by Chippolin** [comment]
Super... hat funktioniert.

Alle USB Anschlüsse abgezogen und Gerät nochmals einen Meter weiter weg gestellt.
Werksreset durchgeführt und nur die Batterie eingesetzt.
Kopplung hat funktioniert!

Lieben Dank und ein erfolgreich 2020
