### ISSUE TITLE
komme nach PIVCCU Installation nicht mehr ins Internet

### ISSUE THREAD

**Issue by mnennstiel** [alexreinert/piVCCU#221]
Hallo,
Ich hab deine Anleitung für LAN probiert. In der Versionen komme ich nicht mehr ins Internet. CCU2 läuft und Kommunikation steht. Ich komme aber nicht mehr auf meine Fritzbox also auch nicht mehr ins Internet!
Eigentlich wollte ich es mit WLAN einstellen - nur das hat nicht funktioniert.
Welche Auszüge brauchst du um zu sehen woran es hängt?

**Comment by alexreinert** [comment]
Ich habe dir gestern bereits im HM Forum geantwortet. Wenn du das ignorierst und dann hier mit weniger Infos einen neuen Issue aufmachst, meinst du wirklich, dass das hilft?
