### ISSUE TITLE
Fehler beim installieren von pivccu-modules-dkms [Tinkerboard][Armbian] 

### ISSUE THREAD

**Issue by Psycho0verload** [alexreinert/piVCCU#222]
Hallo,

ich habe mir aufgrund von neuer Hardware heute das neuste Image von Armbian für das Tinkerboard gezogen und wie im letzten Issues die geänderte Installation durchgelaufen doch da kommt folgender Fehler bei der Installation von pivccu-modules-dkms:
```
Error! Your kernel headers for kernel 5.4.6-rockchip cannot be found.
Please install the linux-headers-5.4.6-rockchip package,
or use the --kernelsourcedir option to tell DKMS where it's located
```
Da es mit:
Armbian Buster with Linux 5.3.11-rockchip
Armbian Buster with Linux 5.3.15-rockchip
funktioniert werde ich bis zur Lösung meinen Kernel downgraden.

Grüße

**Comment by alexreinert** [comment]
Es müssen die zum Image passenden Kernel Header installiert werden. Leider passiert es kmmer mal wieder, dass Armbian Images erstellt, ohne dass die passenden Header bereitgestellt werden, da kann ich aber leider nichts dran ändern.

**Comment by Psycho0verload** [comment]
Frohes neues Jahr!
Das heißt, dass es ein Problem von Armbian ist. Dann schreibe ich mal dort mein Issue.

Vielen Dank!
