### ISSUE TITLE
keine zyklische Statusabfrage 

### ISSUE THREAD

**Issue by mnennstiel** [alexreinert/piVCCU#223]
Hallo,
mein I/O Device d_ccu ist zwar im RUNNING/OK aber die DEVICES werden nicht zyklisch aktuallisiert. Manuell über get devstate und get update funktioniert es. 
Habe das I/O Device schon mehrfach neu angelegt und die IP - Devices auch!

**Comment by alexreinert** [comment]
?

**Comment by alexreinert** [comment]
Kommt hier noch eine Info?

**Comment by alexreinert** [comment]
Scheinbar nicht, daher mache ich zu. Falls noch Bedarf ist, bitte mit entsprechenden Infos wieder aufmachen.
