### ISSUE TITLE
Mininalöffnung der Heizkörperthermostate

### ISSUE THREAD

**Issue by MeinzIsAs** [alexreinert/piVCCU#225]
Hallo!

Ist es möglich eine Minimalöffnung der Heizkörperthermostate in die Einstellungen einzubauen?
Grund: Es arbeiten nicht alle Heizkörperventile gleich gut/schlecht. Bei manchen ist noch kein Durchfluss, wenn nur ein kleiner Wert geöffnet wird.

Vielen Dank

**Comment by alexreinert** [comment]
piVCCU basiert auf der CCU Firmware und hat als eines der Hauptziele maximal kompatibel zu sein. Eine entsprechende Änderung ist daher nur möglich, wenn das auch in der Original CCU kommt. Allerdings bin ich mir nicht sicher, ob es für diese Änderung nicht sogar eine Anpassung in den Heizkörperthermostaten selbst bräuchte, ansonsten könnte man durch lokale Bedienung unter den Minimalwert kommen. Insgesamt wäre also eQ-3 der richtige Ansprechpartner für den Featurewunsch.
