### ISSUE TITLE
MapleCun HM-MOD-Uart

### ISSUE THREAD

**Issue by Banabas** [alexreinert/piVCCU#227]
Hallo,
ich habe Probleme bei der Erkennung von meinem HM-Mod-Uart.
Nutze einen Raspberry 3 und hab den HM-MOD-UART auf einer MapleCun Platine verlötet.
Hab ihn dann gestern einmal in FHEM definiert.
`define myRemoteHmUART HMUARTLGW /dev/serial/by-id/usb-STM32_MapleCUL_1675cbb0-if02 ### Die zweite Serielle`

hat auch geklappt und mir wurde die ID usw angezeigt.
Firmware update hat auch funktioniert. Ist jetzt glaub ich auf 1.4.1

hab die Definition dann wieder gelöscht weil der HM-Mod-Uart für mich über FHEM erreichbar war.

Hab jetzt ein sauberes Buster Image genommen und nach Anleitung piVCCU3 installiert.
Schritt 4 5 und 6 hab ich ausgelassen da ich nicht die GPIO nutzen möchte sondern die 2.Schnittstelle vom Maple "ttyACM2" welcher über USB am Raspberry hängt.

`lrwxrwxrwx 1 root root 13 Jan 15 20:25 usb-STM32_MapleCUL_1675cbb0-if00 -> ../../ttyACM1
lrwxrwxrwx 1 root root 13 Jan 15 20:25 usb-STM32_MapleCUL_1675cbb0-if02 -> ../../ttyACM2
lrwxrwxrwx 1 root root 13 Jan 15 20:25 usb-STM32_MapleCUL_1675cbb0-if04 -> ../../ttyACM3`

Wenn dann im Installer die Frage nach dem Modul kommt wähle ich doch 
"HM-MOD-Rpi_PCB" oder?

**Comment by alexreinert** [comment]
MapleCUN wird nicht unterstützt. Es wird unterstützt, was im Readme steht.

**Comment by Banabas** [comment]
Okay danke. 
Dachte es wäre möglich.
Besten Dank
