### ISSUE TITLE
rpi_rf_mod_led kernel module not kernel 5.4.x compatible

### ISSUE THREAD

**Issue by jens-maus** [alexreinert/piVCCU#228]
I am currently evaluating the possibilities to bump RaspberryMatic to kernel 5.4.x. Thus, I recognized that while the `generic_raw_uart` seem to compile fine with kernel 5.4 headers/sources, the `rpi_rf_mod_led` kernel module seem to not be compatible to kernel 5.4.x. See here:

```
ERROR: "led_classdev_unregister" [xxx/generic_raw_uart-8cc927e33fe10471816e8793b2da7802926ced0b/kernel/rpi_rf_mod_led.ko] undefined!
ERROR: "led_classdev_register_ext" [xxx/generic_raw_uart-8cc927e33fe10471816e8793b2da7802926ced0b/kernel/rpi_rf_mod_led.ko] undefined!
```

So is there any patch you might have at hand to get this led kernel module compiled with a kernel 5.4.x environment?

**Comment by alexreinert** [comment]
I just tested it on an Ubuntu 18.04 with 5.4 kernel and had no issues (after updating to GCC 8):

```
root@dev:~# modinfo rpi_rf_mod_led
filename:       /lib/modules/5.4.0-050400-generic/updates/dkms/rpi_rf_mod_led.ko
alias:          rpi_rf_mod_led
license:        GPL
version:        1.5
description:    GPIO LED driver for RPI-RF-MOD
author:         Alexander Reinert <alex@areinert.de>
srcversion:     9FF3C1A3D78A19A0E610ECF
depends:
retpoline:      Y
name:           rpi_rf_mod_led
vermagic:       5.4.0-050400-generic SMP mod_unload
parm:           red_gpio_pin:GPIO Pin of red LED
parm:           green_gpio_pin:GPIO Pin of green LED
parm:           blue_gpio_pin:GPIO Pin of blue LED
```

**Comment by jens-maus** [comment]
Was this an ARM system you tried compiling rpi_rf_mod_led for kernel 5.4?

**Comment by alexreinert** [comment]
No, it was on x64. But there are AFAIK no platform dependent parts on that stuff.
Do you have a full build log?
And just to get it fully curious: led_classdev_register_ext was introduced in kernel 5.4. In the rpi_rf_mod_lef module I use the led_classdev_register method, which is remapped to the new function inside the kernel.

**Comment by jens-maus** [comment]
Ok, after some more investigation I found the reason for the compile issue being that kernel 5.4 comes with a new `CONFIG_NEW_LEDS` top-level kernel config option which, if not set, disables the whole `CONFIG_LEDS_XXXX`  options. And since I was coming from 4.19.x this new kernel option was missing and thus the whole LED stuff was simply disabled. So sorry for the confusion and thanks for your own tests!
