### ISSUE TITLE
Error! Bad return status for module build on kernel: 4.19.93-v7+

### ISSUE THREAD

**Issue by Ewies** [alexreinert/piVCCU#230]
Hallo,

ich hatte heute schon mal geschrieben das ich eine menge Probleme mit Python hatte.

Diese habe ich gelöst aber jetzt bekomme ich pivccu3 nicht mehr zum laufen.

Hier mal die Fehler:
`pi@RiessHomeServer:/ $ cat /var/lib/dkms/pivccu/1.0.36/build/make.log
DKMS make.log for pivccu-1.0.36 for kernel 4.19.93-v7+ (armv7l)
Wed Jan 22 19:36:13 CET 2020
make -C /lib/modules/4.19.93-v7+/build M=/var/lib/dkms/pivccu/1.0.36/build modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.93-v7+'
Segmentation fault
Segmentation fault
  CC [M]  /var/lib/dkms/pivccu/1.0.36/build/eq3_char_loop.o
  CC [M]  /var/lib/dkms/pivccu/1.0.36/build/plat_eq3ccu2.o
  CC [M]  /var/lib/dkms/pivccu/1.0.36/build/generic_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.36/build/pl011_raw_uart.o
gcc: internal compiler error: Segmentation fault signal terminated program as
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
make[2]: *** [scripts/Makefile.build:309: /var/lib/dkms/pivccu/1.0.36/build/plat_eq3ccu2.o] Error 4
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/pivccu/1.0.36/build/eq3_char_loop.c: In function 'eq3loop_create_slave_dev':
/var/lib/dkms/pivccu/1.0.36/build/eq3_char_loop.c:802:32: warning: pointer targets in assignment from 'unsigned char *' to 'char *' differ in signedness [-Wpointer-sign]
  channel->master2slave_buf.buf = channel->_master2slave_buf;
                                ^
/var/lib/dkms/pivccu/1.0.36/build/eq3_char_loop.c:803:32: warning: pointer targets in assignment from 'unsigned char *' to 'char *' differ in signedness [-Wpointer-sign]
  channel->slave2master_buf.buf = channel->_slave2master_buf;
                                ^
/var/lib/dkms/pivccu/1.0.36/build/generic_raw_uart.c: In function 'generic_raw_uart_set_dummy_rx8130_loader':
/var/lib/dkms/pivccu/1.0.36/build/generic_raw_uart.c:959:15: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
     int load, ret;
               ^~~
gcc: internal compiler error: Segmentation fault signal terminated program as
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
make[2]: *** [scripts/Makefile.build:309: /var/lib/dkms/pivccu/1.0.36/build/pl011_raw_uart.o] Error 4
In function 'eq3loop_create_slave_dev.isra.2',
    inlined from 'eq3loop_ioctl_ctrl' at /var/lib/dkms/pivccu/1.0.36/build/eq3_char_loop.c:441:10,
    inlined from 'eq3loop_ioctl' at /var/lib/dkms/pivccu/1.0.36/build/eq3_char_loop.c:570:10:
/var/lib/dkms/pivccu/1.0.36/build/eq3_char_loop.c:780:2: warning: 'strncpy' output may be truncated copying 31 bytes from a string of length 63 [-Wstringop-truncation]
  strncpy( channel->name, name, sizeof(channel->name)-1 );
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc: internal compiler error: Segmentation fault signal terminated program as
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
gcc: internal compiler error: Segmentation fault signal terminated program as
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
make[2]: *** [scripts/Makefile.build:309: /var/lib/dkms/pivccu/1.0.36/build/generic_raw_uart.o] Error 4
make[2]: *** [scripts/Makefile.build:309: /var/lib/dkms/pivccu/1.0.36/build/eq3_char_loop.o] Error 4
make[1]: *** [Makefile:1522: _module_/var/lib/dkms/pivccu/1.0.36/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.93-v7+'
make: *** [Makefile:23: all] Error 2`

`pi@RiessHomeServer:/ $ sudo pivccu-info
piVCCU version: 3.49.17-33
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          STOPPED`

`piVCCU: Error! Hardware platform is not supported`

was könnte ich jetzt machen, sieht hier jemand vielleicht den Fehler?

Mfg Steffen

**Comment by alexreinert** [comment]
Segmentation fault klingt erstmal stark nach kaputtem Filesystem oder kaputter SD Karte.

**Comment by Ewies** [comment]
ich hatte auch echt zu Kämpfen mit dem python aber habe nach und nach alle Fehler beseitigen können.

Dann dachte ich es läuft wieder alles, bis ich gesehen habe das es bei pivccu nicht so ist.

Gibt es da vielleicht eine Idee was man noch versuchen könnte?

Mfg Steffen

**Comment by alexreinert** [comment]
Filesystem prüfen, SD Karte prüfen.

**Comment by Ewies** [comment]
Ich hatte ja beim Installieren von Certbot den Python fehler bekommen, voher lief alles und sonst laufen auch noch alle andere Dienste deswegen würde ich von einer Defekten SdKarte erstmal nicht ausgehen.

Kennst du ein paar gute Befehle um das Filesystem Prüfen zu lassen???

Was mich sehr ägert ist, das ich wirklich lange gebraucht hatte Python zu reparieren und dann scheitert es jetzt danach daran...

Mfg Steffen
