### ISSUE TITLE
RaspMatic -> PiVCCU --- Es ist kein Coprozessor verfügbar

### ISSUE THREAD

**Issue by prossi77** [alexreinert/piVCCU#233]
Hallo Alex,
ich habe dein Video von der piVCCU/DebMatic gesehen und war so begeisterte, dass ich mir einen Rasp 4 zugelegt habe und auch gleich eine Spende vollzogen habe.
Ich möchte mich bei dieser Gelegenheit gleich nochmal für die wirklich außerordentliche Arbeit von dir, Jens Maus und vielen anderen bedanken. 

Jetzt wollte ich von meiner laufenden RaspberryMatic (Rasp 3) 3.49.17.20191225 auf den Rasp 4 mit PiVCCU und IoBroker umsteigen.
Lt. Anleitung Backup erstellt (mit und ohne AddOns) und auf der PiVCCU eingespielt -> Leider doch nicht, denn ich bekommen den Fehler "Es ist kein Coprozessor verfügbar".

Ich habe auch schon versucht ältere sbk-Dateien einzuspielen.
Weiters habe ich das System (Rasp 4) mit "sudo apt-get update && sudo apt-get upgrade" auf die neueste Version gebracht. Alles leider ohne Erfolg. Immer wieder die gleiche Fehlermeldung.

Weißt du vielleicht, woran es liegen kann?
Danke schon im Voraus
SG Martin

**Comment by alexreinert** [comment]
Welches Funkmodul nutzt du, was liefert `sudo pivccu-info`?

**Comment by prossi77** [comment]
Hallo Alex,
Danke für deine Antwort.
Ich benutze das Funkmodul HM-OCCU-SDK

Weiters habe ich jetzt zum Testen die DebMatic lt. deiner Anleitung von der Seite "https://github.com/alexreinert/debmatic/blob/master/docs/setup/raspberrypi.md"
installiert. Lief alles problemlos ;o) Danke auch hierfür.
Danach ist das Einspielen der sbk-Datei möglich.
Ich habe meine Programme mit dem NEO Automationsmanager geschrieben.
Funktionieren diese auf der DebMatic?

Für Deine Antwort bedanke ich mich bereits im Voraus.
SG Martin

**Comment by prossi77** [comment]
Habe gerade unter den unterstützen Modulen das HM-OCCU-SDK nicht gefunden.
Bringt man das irgendwie zum Laufen oder muss ich mir ein HM-MOD-RPI-PCB oder ein RPI-RF-MOD zulegen?
Für Deine Antwort bedanke ich mich bereits im Voraus.
SG Martin

**Comment by alexreinert** [comment]
Neo funktioniert aktuell nicht als Addon unter debmatic. Als kostenloses Open Source Projekt sehe ich aber auch nicht ein, dass ich ein kommerzielles Addon ohne jegliche Unterstützung des Herstellers portiere.

Das HM-OCCU-SDK ist Software, das hast du sicher nicht als Funkmodul. Kann es sein, dass du das HM-MOD-RPI-PCB hast? Da steht nämlich einiges zum SDK in der mitgelieferten (Bau-)Anleitung.

**Comment by prossi77** [comment]
Hallo Alex,
das mit Neo war mir so nicht bewusst, verstehe ich aber natürlich.

Ja, stimmt, es ist ein HM-MOD-RPI_PCB.
Ich kann mit sudo dpkg-reconfigure pivccu3 zwar das Modul auswählen bekomme aber nach einem Reboot oder Shutdown und nach ca. 10 Minuten wieder starten folgendes unter sudo pivccu-info

piVCCU version: 3.49.17-35
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          RUNNING
PID:            3488
IP:             192.168.178.30
CPU use:        0.98 seconds
BlkIO use:      5.04 MiB
Memory use:     9.03 MiB
KMem use:       2.64 MiB
Link:           vethpivccu
 TX bytes:      5.64 KiB
 RX bytes:      9.70 KiB
 Total bytes:   15.34 KiB

Kann es am Raspi 4 liegen. Ich habe es auch mit dem von dir bereit gestellten Test-Image probiert. Gleiches Ergebnis. Ich glaube ich lege das pivccu -Projekt wieder auf Eis und bleibe beim Rasp3 mit Raspmatic.

Ich habe abschließend eigentlich nurmehr 2 Fragen.
- ich habe 3 LAN-Gateways -> benötige ich da das HM-MOD-RPI_PCB überhaupt?
- mit welchem Programm erstellst du die HomeMatic-Programme (WebUi, Redmatic, IP-Syncom, ...)?

Für Deine Antwort bedanke ich mich bereits im Voraus.
SG Martin

**Comment by alexreinert** [comment]
Bist du sicher, dass das Funkmodul koreekt gelötet und korrekt aufgesteckt ist? Alle Einstellungen auf dem Pi sind korrekt, aber das Funkmodul wird nicht erkannt. Mach doch mal Fotos vom aufgesteckten Modul und von den Lötstellen auf Ober- und Unterseite.
Mit der Option der Software-Emulation und deinen LAN GWs könntest du auch ohne HM-MOD-RPI-PCB arbeiten. Aber dann geht kein HmIP, weil die LAN GWs das nicht können.

Ich selber nutze OpenHab in Verbindung mit debmatic, wobei da sämtliche Logik entweder in Direktverknüpfungen oder innerhalb von JSR223 Regeln in OpenHab liegt.

**Comment by prossi77** [comment]
Hallo Alex, 
Danke für deine Antwort.

anbei die Fotos.
![659595302](https://user-images.githubusercontent.com/60525738/73604748-03d62c00-4596-11ea-83b9-68f8608c1fec.png)
![713994263](https://user-images.githubusercontent.com/60525738/73604749-03d62c00-4596-11ea-98f7-c111e6e75db8.png)
![460588753](https://user-images.githubusercontent.com/60525738/73604750-046ec280-4596-11ea-83b8-32ab3d5610d2.png)

Ich hoffe das mit den Fotos klappt. Ist das erste mal, dass ich so etwas mache ;o/

SG Martin

**Comment by alexreinert** [comment]
Auch wenn die Bilder sehr unscharf sind, kann ich eine Sache erkennen: Das Funkmodul ist leider falsch zusammengebaut, vergleich mal die Position der SMD Bauteile bei dir und in der Anleitung.

**Comment by prossi77** [comment]
stimmt, das darf nicht wahr sein, Asche über mein Haupt.
Mir fehlen jetzt die Worte.
Danke für den Hinweis.

**Comment by prossi77** [comment]
Hallo Alex,

geht doch ->
piVCCU version: 3.49.17-35
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   OEQ0309159
Radio MAC:      0x584667
SGTIN:          3014F711A061A7D7098E1FA7
State:          RUNNING
PID:            816
IP:             10.208.80.32
IP:             192.168.178.43
CPU use:        39.03 seconds
BlkIO use:      89.24 MiB
Memory use:     243.95 MiB
KMem use:       6.80 MiB
Link:           vethpivccu
 TX bytes:      1.17 MiB
 RX bytes:      757.24 KiB
 Total bytes:   1.90 MiB

Vielen Dank nochmals für deine Hilfe.

Ich wünsche Dir noch ein schönes Wochende.
Martin
