### ISSUE TITLE
pivCCU/pivCCU3 browser Einstellungen nicht möglich

### ISSUE THREAD

**Issue by Maximilian4711** [alexreinert/piVCCU#237]
Mein Versuch, pivCCU oder piVCCU3 auf einem Raspi 4 mit 4gb die "Allgemeinen Einstellungen" oder "Kopplungen" aufzurufen scheitert mit "eine Komponente der Homematic Zentrale reagiert nicht mehr". Manchmal bleibt der browser auch grau. Beim Neuladen der Seite wird die Startseite angezeigt.
Debian buster lite, Homematic Antenne über USB angeschlossen.
Bitte um Unterstützung.

**Comment by alexreinert** [comment]
Browser Cache geleert und mit Strg+F5 einen Forced Refresh gemacht?
Was liefert `sudo pivccu-info`?

**Comment by alexreinert** [comment]
Kommt hier noch eine Rückmeldung?

**Comment by jh2k19** [comment]
Hallo Alex, habe auch seit dem letzten update/upgrade auf meinem Nanopi M4 das Problem die CCU nicht mehr per Weboberfläche zu erreichen. Ping auf die IP bringt 100% Verlust. Komisch ist nur, dass der Zugriff über ioBroker offensichtlich noch funktioniert. Daten wie z.B. Thermostatwerte können hier noch geschrieben und empfangen wedern.
sudo pivccu-info bringt:

piVCCU version: 3.49.17-35
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   PEQ0530673
Radio MAC:      0x6a62d3
SGTIN:          3014F711A061A7D8A99180F1
State:          RUNNING
PID:            1607
IP:             192.168.1.63
IP:             2002:4e2b:3ca2:0:688b:32ff:fe9d:a989
CPU use:        38.87 seconds
BlkIO use:      76.08 MiB
Memory use:     214.45 MiB
KMem use:       10.67 MiB
Link:           vethpivccu
 TX bytes:      557.71 KiB
 RX bytes:      190.14 KiB
 Total bytes:   747.85 KiB
root@nanopim4:~#

Hast du eine Idee?

**Comment by wendy2702** [comment]
Das habe ich in Verbindung mit ioBroker auch hin und wieder. Stoppe mal deine RPC und Rega Adapter. Starte PIVCCU neu und warte 5 Minuten. Dann Probieren ob die Weboberfläche erreichbar ist. Wenn ja kannst du RPC und Rega nacheinander wieder starten.

Bei mir hilft es.

**Comment by jh2k19** [comment]
Danke für deinen Tipp. Leider hat es bei mir nicht geholfen. Das Problem besteht weiterhin.

**Comment by jh2k19** [comment]
So, habe den Fehler gefunden. Ich war selbst schuld. Eine Docker Instalation hat da was verbogen. Hilfe habe ich dazu im Homematic Forum gefunden. 
/etc/piVCCU/lxc.config anpassen:
lxc.network.link = br0
