### ISSUE TITLE
piVCCU on Arch Linux

### ISSUE THREAD

**Issue by df8oe** [alexreinert/piVCCU#239]
Hi,
I do not like Debian based distributions like Raspbian because my Raspberry has many different tasks configured and using Debian based distributions I have to throw away my grown configurations and installations every ~2 years. So I prefer a rolling release since two years and want to install piVCCU3 there. But when I try to browse debian packages via browser at https://www.pivccu.de/piVCCU/ I only get a "403 forbidden" error... How can I access the .deb without apt (which is not available on ArmArch)?

**Comment by alexreinert** [comment]
First: There is no need to throw away your installation on Raspbian when there is a new release, the normal Debian way for upgrading is working fine.
The deb of the current stable version is located at http://www.pivccu.de/piVCCU/pool/main/p/pivccu3/pivccu3-3.49.17-35-armhf.deb But just to say: I will provide no support to install piVCCU on Arch.

**Comment by df8oe** [comment]
Thanks for your reply. I never asked and will never aks for support for Arch - it is an experiment and if it works I will follow your new versions and possibly create an AUR for that. I can drop you an information if you want. Many thanks for this nice project - it is amazing.
