### ISSUE TITLE
Error installing piVCCU on RaspberryPi

### ISSUE THREAD

**Issue by mrehker** [alexreinert/piVCCU#24]
When installing piVCCU via apt install i get the following error. I am using "testing".

Where is my mistake :-(.

` CC [M]  /var/lib/dkms/pivccu/1.0.7/build/generic_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.7/build/pl011_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.7/build/dw_apb_raw_uart.o
/var/lib/dkms/pivccu/1.0.7/build/generic_raw_uart.c: In function ‘generic_raw_uart_probe’:
/var/lib/dkms/pivccu/1.0.7/build/generic_raw_uart.c:711:3: error: implicit declaration of function ‘device_property_read_u32’ [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
/usr/src/linux-headers-3.6-trunk-common/scripts/Makefile.build:313: recipe for target '/var/lib/dkms/pivccu/1.0.7/build/generic_raw_uart.o' failed
make[4]: *** [/var/lib/dkms/pivccu/1.0.7/build/generic_raw_uart.o] Error 1
make[4]: *** Waiting for unfinished jobs....
/var/lib/dkms/pivccu/1.0.7/build/dw_apb_raw_uart.c:28:25: fatal error: linux/reset.h: No such file or directory
compilation terminated.
/usr/src/linux-headers-3.6-trunk-common/scripts/Makefile.build:313: recipe for target '/var/lib/dkms/pivccu/1.0.7/build/dw_apb_raw_uart.o' failed
make[4]: *** [/var/lib/dkms/pivccu/1.0.7/build/dw_apb_raw_uart.o] Error 1
/usr/src/linux-headers-3.6-trunk-common/Makefile:1208: recipe for target '_module_/var/lib/dkms/pivccu/1.0.7/build' failed
make[3]: *** [_module_/var/lib/dkms/pivccu/1.0.7/build] Error 2
Makefile:130: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.6-trunk-rpi'
Makefile:16: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by alexreinert** [comment]
Can you please provide your kernel version?

And can you please provide a list of the directories in /lib/modules?

**Comment by mrehker** [comment]
Wow, you are incredibly fast. Two main points, the first very important, the second not so much:
1) your module is great!!
2) the problem has two ears. 

I tried to switch from stable to testing because all my HM IP refused to work in OH2. The HM were fine. The HM IP were ONLINE, then offline after a while. When listing "Geräte" in CCU2, nothing happened any more. 

What I did here was to remove "pivccu-modules-raspberrypi", then change apt source, then reboot. Then I checked the bridge config etc. and did "install pivccu" which fails. I restarted again, removed everything via apt and followed instructions. It works, also the problem described before is solved. 

Maybe that could be a point to state in the instructions - to do the full thing of "install pivccu-modules-raspberrypi" / "reboot" / "install pivccu" when switching sources.

What I do not understand: why the heck are all items back in CCU2? I thought I did a clean install? And the bridge in OH is getting online, but all items are in 

I close this now, if you have any idea, what is happening, I would be more then happy to learn.

**Comment by alexreinert** [comment]
On my systems a switch from stable to testing worked absolutly fine. Without a reboot.
Are you now on stable or on testing?

When removing the package I do not delete the user directory (mainly for security reasons). And on a new install all data is available again.
