### ISSUE TITLE
ccu3-webui nicht mehr erreichbar

### ISSUE THREAD

**Issue by jfrostmsc** [alexreinert/piVCCU#241]
Hallo,
ich habe gestern das Image `https://www.pivccu.de/images/piVCCU3/Raspbian_Buster_Liste_piVCCU3_2019-07-11.zip` (Ich denke, es sollte wohl Buster_Lite heissen?) auf meinen raspberry pi gepackt. Nach allen updates und upgrades und Konfiguration hat es etwas gedauert, aber dann war das Webinterface erreichbar und ich habe schon mal diesen Willkommensbildschirm und die Firewall Konfiguration durchgeführt (noch alles neu für mich).
Dann habe ich Docker und darin portainer, pihole, node-red, eclipse-mosquitto und zigbee2mqtt installiert.
Als dann alles lief war das ccu3-webui nicht mehr erreichbar.
`sudo cat /var/lib/piVCCU3/userfs/etc/config/netconfig`
`HOSTNAME=ccu3-webui
MODE=DHCP
CURRENT_IP=192.168.1.35
CURRENT_NETMASK=255.255.255.0
CURRENT_GATEWAY=192.168.1.1
CURRENT_NAMESERVER1=192.168.1.1
CURRENT_NAMESERVER2=0.0.0.0
IP=192.168.1.225
NETMASK=255.255.255.0
GATEWAY=192.168.1.1
NAMESERVER1=192.168.1.1
NAMESERVER2=0.0.0.0
CRYPT=0`
Die IP 192.168.1.35 hat er in meiner Fritzbox den Namen ccu3-webui gegeben. Ist aber jetzt als nicht aktiv angezeigt und ist auch nich anpingbar.
Vielen Dank für die Hilfe!
Gruß,
Jan

**Comment by jfrostmsc** [comment]
Achso, ich habe das HM-MOD-RPI-PCB noch nicht aufgesteckt. Ist bestellt und wird erst noch geliefert. Ich hoffe das macht nichts aus... Da Web Interface war ja auch schon erreichbar.

**Comment by alexreinert** [comment]
Ohne Funkmodul dauert es teilweise ewig, bis die Weboberfläche gestartet wird.

Bei Verwendung von Docker auf dem gleichen System richtet Docker fehlerhafte Firewallregeln ein, siehe z.B. https://forum.fhem.de/index.php/topic,77047.msg1024109.html#msg1024109

**Comment by jfrostmsc** [comment]
Sehr gut!
nach dem
`sudo iptables -F FORWARD
sudo iptables -P FORWARD ACCEPT`
geht der ping wieder durch und über das Web Interface kommt ein bitte warten.
Laut Deinem Link ist das wohl nicht permanent. Hast Du eine Idee, wie ich das permanent machen kann?

**Comment by jfrostmsc** [comment]
Ich habe mittlerweile das Funkmodul bekommen und angesteckt. Ich bekomme es aber nicht ans laufen.
`pi@raspberrypi:~ $ sudo dpkg-reconfigure pivccu3
Removed /etc/systemd/system/multi-user.target.wants/pivccu.service.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu.service → /lib/systemd/system/pivccu.service.
pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.49.17-35
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          RUNNING
PID:            5049
IP:             192.168.1.35
CPU use:        1.41 seconds
BlkIO use:      1.23 MiB
Memory use:     7.41 MiB
KMem use:       2.90 MiB
Link:           vethpivccu
 TX bytes:      13.02 KiB
 RX bytes:      20.32 KiB
 Total bytes:   33.34 KiB
`
Was kann ich noch machen um das Problem zu analysieren?

**Comment by alexreinert** [comment]
Mach bitte mal (scharfe) Bilder vom Funkmodul, Oberseite, Unterseite und aufgesteckt auf dem Pi.

**Comment by jfrostmsc** [comment]
Ich hab noch ein wenig sauber gebürstet und sogar noch mal nachgelötet. Bilder sind per eMail raus.

**Comment by alexreinert** [comment]
Nach Sichtung der Bilder muss ich leider sagen, dass sich meine Vermutung bestätigt hat, das Modul ist falsch zusammengelötet: Das eigentlich Funkmodul ist von der falschen Seite aus bestückt worden.

**Comment by jfrostmsc** [comment]
Was bin ich nur für ein Rindvieh. Hab die Bilder angesehen und es doch falsch gemacht. War etwas abgelenkt an dem Abend. Ich hoffe ich bekomme es noch einmal ab und es ist noch nicht kaputt.
Vielen Dank auf jeden Fall. Ich melde mich noch mal, wenn es funktioniert.

**Comment by jfrostmsc** [comment]
Und wieder einmal bewahrheitet sich: Kaum macht man es richtig, geht es!
Ich danke Dir für Deine Hilfe!
