### ISSUE TITLE
Probleme während Update nach backup Abfrage

### ISSUE THREAD

**Issue by tom8184** [alexreinert/piVCCU#242]
Hallo,

da ich letzt nicht sicher war, ob und wo ich ein Backup der piVCCU3 hatte habe ich während des Updates die Frage nach einem vorhandenen Backup mit nein beantwortet.
Wie erwartet hat das zu einem Abbruch des Updates geführt nur habe ich keinen Weg gefunden, die piVCCU3 wieder ans laufen zu bekommen.

Ist hier ein Fehler im Skript oder wie hätte ich weiter vorgehen müssen?

Da ich das Backup gefunden hatte, habe ich die SDCard neu erstellt und das Backup eingespielt um mein System wieder ans laufen zu bekommen.

**Comment by alexreinert** [comment]
Ich habe das grade nochmal ausprobiert, ich kann das nicht nachvollziehen, der Mechanismus funktioniert hier einwandfrei.
Welche Version war denn vorher installiert?

**Comment by tom8184** [comment]
Das kann ich leider nicht mehr sagen. Jetzt läuft 3.49.17, davor war es die 3.47.10 wenn ich mich richtig erinnere.

**Comment by alexreinert** [comment]
Wenn du parallel den Kernel, die Kernel Header, die piVCCU Kernel Module und piVCCU aktualisierst, könnte es sein, dass piVCCU nach dem Abruch nicht mehr sofort startet. In dem Fall würde dann aber ein Reboot ausreichen um das Problem zu lösen.

**Comment by tom8184** [comment]
Leider half damals leider auch kein reboot und längerer Shutdown mit Stromabschaltung.
Wie könnte man piVCCU vom Update ausschließen?

**Comment by tom8184** [comment]
Leider half damals auch kein reboot und längerer Shutdown mit Stromabschaltung.
Wie könnte man piVCCU vom Update ausschließen?
