### ISSUE TITLE
piVCCU will not start after kernel update using rpi-update | Failed to verify kernel headers v71, v8

### ISSUE THREAD

**Issue by CreaaZ** [alexreinert/piVCCU#243]
Hi Alex,

I wanted to switch my RPi 4 over to 64-bit kernels for some reasons, but cannot get my piVCCU back to work after doing so.  I installed the latest firmware and kernel headers using `rpi-update` and switched to 64-bit by setting `arm_64bit=1` in my `/boot/config.txt`.

uname -a
`Linux raspberrypi 4.19.102-v8+ #1295 SMP PREEMPT Thu Feb 6 15:55:54 GMT 2020 aarch64 GNU/Linux`

sudo systemctl status pivccu-rpi-modules.service
```
Feb 17 23:33:21 raspberrypi systemd[1]: Starting piVCCU RPi Kernel loader...
Feb 17 23:33:22 raspberrypi ensure_headers.sh[503]: /boot/.firmware_revision does not match active kernel version.
Feb 17 23:33:22 raspberrypi systemd[1]: pivccu-rpi-modules.service: Main process exited, code=exited, status=1/FAILURE
Feb 17 23:33:22 raspberrypi systemd[1]: pivccu-rpi-modules.service: Failed with result 'exit-code'.
Feb 17 23:33:22 raspberrypi systemd[1]: Failed to start piVCCU RPi Kernel loader.
```
The error messages indicates, that there is a mismatch between kernel versions. However, there is not.

In your ensure_headers.sh I can see, that you verify the Git Hash. I tried to follow along and identified, that the lookup for my firmware revision only returns the v7 Kernel, because you explictly ask for it (uname_string7). Hence, the validation fails.
https://raw.githubusercontent.com/Hexxeh/rpi-firmware/23acc388b495f74e65175c30889cb81aaf731618/uname_string7

Does that mean, that you don't support the usage of v8 kernels yet? Are there any configuration possibilities how I can force to use the v8 kernels? 

I cannot even use the v71 kernels, because of the same issue as GitHub returns 4.19.102-v7+ and uname returns 4.19.102-v71+.

In your documentation, you state, that basically rpi-udapte would be somehow "supported" so I was wondering where the issue is. 

Running piVCCU version: 3.49.17-35

Thanks!

**Comment by alexreinert** [comment]
v8 kernel is not supported as the required 64-bit toolchain is not available on Raspbian, even if the required headers or source would be available on the system.
for the v7l kernel I will do some changes to support it.
Why are you using rpi-update? It is clearly stated that this should not be used if there are no special requirements for it.

**Comment by CreaaZ** [comment]
Thanks for your reply. 
Would be great if you could mention ith the v8 kernel somewhere to your documentation :-) 

I'm using the RPi for more than just piVCCU and did some experiments around the 64-bit possibilities for other use-cases, which somehow led me to perform the rpi-update.

Anyway, I reverted to the stable kernel already (piVCCU is working fine again) and will migrate piVCCU to a standalone RPi in near future to have my main RPi 4 running with 64-bit.
