### ISSUE TITLE
Verbindungsprobleme HomematicIP bei RaspberryPi4 + piVCCU3 +HM-MOD-RPI-PCB 

### ISSUE THREAD

**Issue by DSL75** [alexreinert/piVCCU#244]
Ich verwende bisher einen RaspberryPi3 mit piVCCU3 (aktuelles Image für SD-Karte) und HM-MOD-RPI-PCB und kann dort sowohl Homematic (z.B. Schaltsteckdose) als auch Homematic IP (z.B. Wassersensor) -Komponenten an- und abmelden.
Parallel habe ich einen RaspberryPi4 mit gleicher Konfiguration aufgebaut. Die Homematic-Komponenten lassen sich weiterhin an- und abmelden, aber die Homematic IP - Komponenten reagieren nicht.
Ich habe dazu bisher keine Fehlermeldungen gefunden. Gibt es jemanden, bei dem die zweite Konfiguration funktioniert oder kennt jemand diesen Fehlerfall schon?

**Comment by alexreinert** [comment]
Homematic IP Geräte können jeweils nur an einer Zentrale angemeldet sein und im Gegensatz zu HM Classic Geräten äußert sich das bereits beim Anmelden. Wurde ein Werksreset an den HmIP Geräten gemacht, bevor die am Pi 4 angelernt wurden?
Ansonsten: Der Pi 4 erzeugt massiv Störstrahlung insb. wenn ein USB Port genutzt wird und das betrifft ganz besonders HmIP mit dem Listen Before Talk. Hier hilft dann nur Absetzen des gesamten Funkmoduls z.B. durch Verwendung der Platine HB-RF-USB.

**Comment by CreaaZ** [comment]
@DSL75 
Ich habe genau diese Kombination im Einsatz und kann bestätigen, dass sie funktioniert. Ich kann aber auch bestätigen, dass die Konstruktion sehr empfindlich ist, insbesondere, da ich noch eine USB 3.0 SSD und ein USB Hub mit angeschlossenem ZigBee Adapter am selben Pi verwende. Zu nah an anderen elektronischen Geräten (z.B. Modem, Router, NAS) und die Gerätekommunikation zu den HM-IP Komponenten ist gestört. In meinem konkreten Fall von heute hat die CCU weiterhin konstant Werte empfangen, aber ich konnte von der CCU keine Werte auf den angeschlossenen Geräten setzen. Wieder 20cm vom Router weggerückt und es läuft wieder alles.

Probiere mal zum Testen den Pi soweit weg von anderen Geräten zu stellen, wie es irgend möglich ist. Für angeschlossene USB Geräte auch ein USB Verlängerungskabel bzw. USB Hub verwenden.
Das das wichtig ist zeigt das Beispiel als mein ZigBee (ConBee II) Modul keine ZigBee Kommunikation aufbauen konnte, als es direkt im Pi gesteckt hat. Seit das Modul am Verlängerungskabel hängt, funktioniert es ohne Probleme.

**Comment by DSL75** [comment]
Vielen Dank für die Hinweise. Es liegt auch bei mir an Störungen. Ich habe eine Zusatzantenne verbaut und vom USB-Port weg positioniert. Daraufhin konnte ich die Homematic IP Geräte anmelden. Bei Verwendung eines Metallgehäuses und einer zusätzlichen Ummantelung der Antennenzuleitung sollte das Problem dauerhaft lösbar sein.
