### ISSUE TITLE
No Connection to HMIP-RFUSB after reboot

### ISSUE THREAD

**Issue by reschix** [alexreinert/piVCCU#245]
Version: piVCCU3
Issue: No Connection to HMIP-RFUSB after reboot ("HMIP-Hardware: unknown")

Manual steps to make it work:
- sudo systemctl restart pivccu

Tried:
- Fresh install of Raspian and piVCCU3

Please help :-)

**Comment by alexreinert** [comment]
This could be an issue, there the modemmanager blocks the access to the stick on the startup of the system. I added some udev rules to prevent that. Can you please test version 3.51.6-37 in the testing apt repository?

**Comment by reschix** [comment]
Thanks for the quick response & help! 👍 

Unfortunately it didn't resolve it.
I upgraded to the test version,
rebooted -> worked,
rebooted -> unknown again.

**Comment by alexreinert** [comment]
Unfortunatly there was an issue in the updated package, can you please try again with the latest update (3.51.6-38) in the testing repository?

**Comment by reschix** [comment]
Tried latest update. Still "Unknown" after every reboot. This time already after the first reboot.

**Comment by alexreinert** [comment]
Please provide the output of
```
sudo pivccu-info
sudo systemctl status pivccu
lsusb
dmesg | grep usb
```

**Comment by reschix** [comment]
Here are the requested outputs after a "fresh" `sudo reboot`
(In the outputs you can see that there is also a remote keyboard/mouse dongle connected; tried without it, also no success)

`sudo pivccu-info
piVCCU version: 3.51.6-38
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  FAKE_HMRF
HMIP Hardware:  unknown
Board serial:   FKE3083407
Radio MAC:      0xbd66d0
SGTIN:          3014F711A061A7D5699DAB52
State:          RUNNING
PID:            1159
IP:             192.168.0.5
CPU use:        1.08 seconds
BlkIO use:      4.34 MiB
Memory use:     8.26 MiB
KMem use:       2.39 MiB
Link:           vethpivccu
 TX bytes:      1.14 KiB
 RX bytes:      35.33 KiB
 Total bytes:   36.48 KiB`

`sudo systemctl status pivccu
pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-03-05 16:09:03 CET; 35s ago
  Process: 655 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, status=0/SUCCESS)
 Main PID: 1154 (lxc-start)
    Tasks: 1 (limit: 2305)
   Memory: 8.0M
   CGroup: /system.slice/pivccu.service
           └─1154 /usr/bin/lxc-start --lxcpath /var/lib/piVCCU3 --name lxc --pidfile /var/run/pivccu3.pid --daemon

Mar 05 16:08:58 raspberrypi systemd[1]: Starting piVCCU...
Mar 05 16:09:02 raspberrypi piVCCU3[947]: HMIP hardware was not detected
Mar 05 16:09:02 raspberrypi start_container.sh[655]: <12>Mar  5 16:09:02 piVCCU3: HMIP hardware was not detected
Mar 05 16:09:03 raspberrypi start_container.sh[655]: kernel.sched_rt_runtime_us = -1
Mar 05 16:09:03 raspberrypi systemd[1]: Started piVCCU.`

`lsusb
Bus 001 Device 005: ID 1b1f:c020 eQ-3 Entwicklung GmbH 
Bus 001 Device 004: ID 0e8f:00a6 GreenAsia Inc. 
Bus 001 Device 006: ID 0424:7800 Standard Microsystems Corp. 
Bus 001 Device 003: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`

`dmesg | grep usb
[    0.104973] usbcore: registered new interface driver usbfs
[    0.105027] usbcore: registered new interface driver hub
[    0.105123] usbcore: registered new device driver usb
[    0.348725] usbcore: registered new interface driver lan78xx
[    0.348783] usbcore: registered new interface driver smsc95xx
[    0.376666] dwc_otg 3f980000.usb: base=(ptrval)
[    0.777948] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.777983] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.778020] dwc_otg 3f980000.usb: irq 56, io mem 0x00000000
[    0.778340] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.19
[    0.778351] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.778361] usb usb1: Product: DWC OTG Controller
[    0.778370] usb usb1: Manufacturer: Linux 4.19.97-v7+ dwc_otg_hcd
[    0.778379] usb usb1: SerialNumber: 3f980000.usb
[    0.779967] usbcore: registered new interface driver usb-storage
[    0.784625] usbcore: registered new interface driver usbhid
[    0.784631] usbhid: USB HID core driver
[    1.206843] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.447211] usb 1-1: New USB device found, idVendor=0424, idProduct=2514, bcdDevice= b.b3
[    1.447229] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.766836] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.897216] usb 1-1.1: New USB device found, idVendor=0424, idProduct=2514, bcdDevice= b.b3
[    1.897233] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.216869] usb 1-1.1.2: new low-speed USB device number 4 using dwc_otg
[    2.394703] usb 1-1.1.2: New USB device found, idVendor=0e8f, idProduct=00a6, bcdDevice= 3.11
[    2.394719] usb 1-1.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.394729] usb 1-1.1.2: Product: 2.4G RX
[    2.394738] usb 1-1.1.2: Manufacturer: DaKai
[    2.408340] input: DaKai 2.4G RX as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0/0003:0E8F:00A6.0001/input/input0
[    2.477503] hid-generic 0003:0E8F:00A6.0001: input,hidraw0: USB HID v1.10 Keyboard [DaKai 2.4G RX] on usb-3f980000.usb-1.1.2/input0
[    2.509020] input: DaKai 2.4G RX Mouse as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.1/0003:0E8F:00A6.0002/input/input1
[    2.509433] input: DaKai 2.4G RX System Control as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.1/0003:0E8F:00A6.0002/input/input2
[    2.577206] input: DaKai 2.4G RX Consumer Control as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.1/0003:0E8F:00A6.0002/input/input3
[    2.577400] input: DaKai 2.4G RX as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.1/0003:0E8F:00A6.0002/input/input4
[    2.577574] input: DaKai 2.4G RX Keyboard as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.1/0003:0E8F:00A6.0002/input/input5
[    2.578050] hid-generic 0003:0E8F:00A6.0002: input,hiddev96,hidraw1: USB HID v1.10 Mouse [DaKai 2.4G RX] on usb-3f980000.usb-1.1.2/input1
[    2.676875] usb 1-1.1.3: new full-speed USB device number 5 using dwc_otg
[    2.826948] usb 1-1.1.3: New USB device found, idVendor=1b1f, idProduct=c020, bcdDevice= 1.00
[    2.826967] usb 1-1.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.826976] usb 1-1.1.3: Product: eQ-3 HmIP-RFUSB
[    2.826985] usb 1-1.1.3: Manufacturer: Silicon Labs
[    2.826994] usb 1-1.1.3: SerialNumber: 3014F711A061A7C00010CECF
[    3.136929] usb 1-1.1.1: new high-speed USB device number 6 using dwc_otg
[    3.267582] usb 1-1.1.1: New USB device found, idVendor=0424, idProduct=7800, bcdDevice= 3.00
[    3.267618] usb 1-1.1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    5.432904] usbcore: registered new interface driver brcmfmac
[   31.990145] usbcore: registered new interface driver usbserial_generic
[   31.990181] usbserial: USB Serial support registered for generic
[   32.010146] usbcore: registered new interface driver cp210x
[   32.010187] usbserial: USB Serial support registered for cp210x
[   32.029223] usb 1-1.1.3: cp210x converter now attached to ttyUSB0`

**Comment by alexreinert** [comment]
Can you please retry using the lastest update?

**Comment by reschix** [comment]
It works! 🥇 
The service now seems to stay stopped for a few seconds after booting and this fixes the issue. I just tried several reboots and the RFUSB always got detected.

Thank you very much for the quick help. I love this project.
Btw I am now using piVCCU on a single Raspi3B+ with Pihole, Openhab and other services. Works just fine.
