### ISSUE TITLE
Beschleunigungssensor HmIP-SAM fehlerhaftes Verhalten

### ISSUE THREAD

**Issue by maloross** [alexreinert/piVCCU#246]
Seit dem Update auf 3.51.6 sind bei dem Neigungssensor folgende Auffälligkeiten aufgetreten:

Wenn Bewegung erkannt wird, blinkt die LED zum Abschluss 1x rot auf - lt. Code für "Befehl nicht bestätigt". 
Auf der Bedienungsseite des Sensor wird jedoch die Zustandsänderung erkannt und angezeigt. Allerdings steht jetzt im geöffneten Zustand "keine Bewegung/waagerecht", im geschlossenen Zustand "Bewegung erkannt/geneigt"

Konfigurationen werden nicht mehr an den Sensor übertragen - LED blinkt zum Abschluss 1x rot auf

piVCCU läuft auf einem Rapsberry Pi 4. 

Probiert habe ich erfolglos folgendes:
- Neustart
- Batterieaustausch
- Sensor näher an Raspi

Ablernen und Werksreset nicht durchgeführt, da ich befürchte, dass das Gerät evtl. nicht mehr eingebunden werden kann.

**Comment by alexreinert** [comment]
Das klingt für mich danach, dass der Raspberry keine HmIP Befehle raussenden kann. Da der Pi4 jede Menge Störstrahlung absondert, welche das Listen Before Talk vom Funkmodul durcheinander bringt, würde ich als erstes in die Richtung forschen. Sind irgendwelche USB Geräte am Pi angesteckt? Hat das Funkmodul eine externe Antenne? Hast du ggf. einen Pi 3 rumliegen, in welchem du die SD Karte testweise betreiben könntest und die Störstrahlung vom Pi 4 als Problem auszuschließen? Wie sieht dein DutyCycle aus?
Ansonsten kann ich an der Stelle leider kaum weiterhelfen: Die komplette Kommunikation von HmIP liegt innerhalb von Closed Source, auf welchen ich keinen Zugriff habe, ich kann an der Stelle nur dafür sorgen, dass die Verbindung dieser Prozesse mit dem Funkmodul korrekt hergestellt wird und das ist bei dir ja offensichtlich in Ordnung, da du die Statusupdates empfängst.

**Comment by maloross** [comment]
Hallo Alex,
danke für die Rückmeldung. 
Andere HmIP-Komponenten funktionieren komischerweise völlig unproblematisch. Keine weiteren USB-Geräte angesteckt, das mit den Störstrahlen wusste ich nicht, probiere das morgen mit einem alten Pi3.
Das Modul hat eine externe Antenne und DC liegt unter 10%.
Weil es ja bis auf die Konfiguration funktioniert, könnte ich so damit leben. Ich teste aber mal die nächsten Tage ein paar Sachen und gebe Rückmeldung.

**Comment by maloross** [comment]
Rückmeldung: bezüglich des Verhaltens hat sich leider nichts verändert, auch auf dem Pi3 bleibt es gleich.
Da es ansonsten mit den kleinen Einschränkungen funktioniert, lasse ich es so bestehen. Notfalls gehe ich auf eine frühere Version zurück.
Danke für die Unterstützung.
