### ISSUE TITLE
Startup mode in systemd

### ISSUE THREAD

**Issue by ingoha** [alexreinert/piVCCU#247]
When starting another service that depends on piVCCU (in my case home-assisstant), systemd signals that piVCCU is ready as soon as start_container.sh has been invoked.
This should be changed so that systemd signals piVCCU ready when the container has been started.
I have a working solution but could not find the systemd service file here in the repo(?)

**Comment by agross** [comment]
Perhaps do the connection check in a totally separate systemd service and bind Home Assistant to that service.

**Comment by frank-f** [comment]
> I have a working solution but could not find the systemd service file here in the repo(?)

I don't know why nobody answered this, but the files you are looking for should be here: https://github.com/alexreinert/piVCCU/tree/master/pivccu/host3
