### ISSUE TITLE
piVCCU funktioniert nicht mit openhab 2 (error 500)

### ISSUE THREAD

**Issue by schorschi1981** [alexreinert/piVCCU#249]
Hallo Alex,

ich habe piVCCU (CCU3) auf dem gleichen System wie openhab 2 laufen. Wenn ich Homematic als Thing hinzufügen möchte, bekomme ich einen Error 500 im PaperUI (openhab 2).

Ich benutze piVCCU aktuell ohne Modul am Raspberry PI.

**Comment by alexreinert** [comment]
piVCCU braucht ein Funkmodul. Entweder Funkmodul nutzen oder auf Software Emulation umstellen.

**Comment by schorschi1981** [comment]
Hatte mir so etwas schon gedacht. Danke für die schnelle Antwort und tolle Arbeit.

**Comment by schorschi1981** [comment]
Eine Frage dazu habe ich noch. Kann man ohne neuinstallation vom Fake Modul auf ein richtiges wechseln? Wenn ja wie macht man das?

**Comment by alexreinert** [comment]
Siehe Readme: https://github.com/alexreinert/piVCCU#supported-radio-modes

**Comment by alexreinert** [comment]
Sind noch Fragen offen?

**Comment by schorschi1981** [comment]
Nein denke nicht. Vielen Dank.
