### ISSUE TITLE
seit Installation von piVCCU kein Bluetooth

### ISSUE THREAD

**Issue by mnennstiel** [alexreinert/piVCCU#251]
Hallo Alex, 
meine VCCU nach deinen Anweisungen läuft. 
Kann es sein das mein fehlendes Bluetooth etwas mit der Installation zu tun hat?
Wenn ich auf der Desktop-Oberfläche vom Raspberry auf das Bluetooth und WiFi Icon in der Menüleiste gehen steht dort "No Bluetooth adapter found" bzw. "No wireless interfaces found"
Mein Bluetooth funktioniert definitiv nicht mehr - mein WLAN funktioniert aber ohne Probleme!

Maik

**Comment by alexreinert** [comment]
In der Anleitung stehen zwei Wege, einer davon deaktiviert Bluetooth (und das steht da auch dabei). Welchen hast du genutzt?

**Comment by mnennstiel** [comment]
Ich habe die Wireless Variante gewählt.
Gibt es da keine Möglichkeit Bluetooth weiter zu benutzen? Habe ein paar Bluetooth Thermometer die jetzt nicht mehr funktionieren!

**Comment by alexreinert** [comment]
Welche Wireless Variante?
Ich meinte unter https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md#installation den Schritt 5. Wenn du da Option 1 wählst, dann wird die Bluetooth Hardware komplett deaktiviert, bei Option 2 bleibt sie weiter an, allerdings ist da der Stromverbrauch und die Temperaturentwicklung schlechter, weshalb ich das nur empfehle, wenn man Bluetooth braucht.

**Comment by mnennstiel** [comment]
OK Prima hatte die 2 Varianten nicht mehr aus dem Schirm. Hatte wirklich Variante 1 damals gewählt. In /boot/config.txt alles nach Variante 1 geändert und es läuft wieder. Danke
