### ISSUE TITLE
piVCCU3 3.51.6-36 not working on current ODROID C2 (Kernel 5.4.27) and HM-MOD-RPI-PCB

### ISSUE THREAD

**Issue by ahessling** [alexreinert/piVCCU#252]
Hi!

After upgrading from kernel 4.19.x to the latest kernel 5.4.27 (official Armbian repository), piVCCU fails to start using "HM-MOD-RPI-PCB".
I re-installed the correct kernel headers and re-installed pivccu-modules-dkms and pivccu-devicetree-armbian. Below are some outputs for debugging. I already rebooted several times, but the hardware does not get detected.

The output of pivccu-info is:
piVCCU version: 3.51.6-36
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          STOPPED

 /var/lib/piVCCU3/start_container.sh
<12>Mar 25 14:29:32 piVCCU3: HMRF hardware was not detected
<12>Mar 25 14:29:32 piVCCU3: HMIP hardware was not detected
kernel.sched_rt_runtime_us = -1
lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 842 Received container state "ABORTING" instead of "RUNNING"
lxc-start: lxc: tools/lxc_start.c: main: 330 The container failed to start
lxc-start: lxc: tools/lxc_start.c: main: 333 To get more details, run the container in foreground mode
lxc-start: lxc: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfile and --logpriority options

/etc/os-release:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

uname -a:
Linux homeautomation 5.4.27-meson64 #20.02.5 SMP PREEMPT Sat Mar 21 15:17:05 CET 2020 aarch64 GNU/Linux

sudo dpkg-reconfigure pivccu-modules-dkms
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.36
Kernel:  5.4.27-meson64 (aarch64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
rmdir: konnte 'updates/dkms' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
rmdir: konnte 'updates/dkms' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
rmdir: konnte 'updates/dkms' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
rmdir: konnte 'updates/dkms' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
rmdir: konnte 'updates/dkms' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
rmdir: konnte 'updates/dkms' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
rmdir: konnte 'updates/dkms' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
rmdir: konnte 'updates/dkms' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
rmdir: konnte 'updates/dkms' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
rmdir: konnte 'updates/dkms' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
rmdir: konnte 'updates/dkms' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.27-meson64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod....

DKMS: uninstall completed.

------------------------------
Deleting module version: 1.0.36
completely from the DKMS tree.
------------------------------
Done.

Creating symlink /var/lib/dkms/pivccu/1.0.36/source ->
                 /usr/src/pivccu-1.0.36

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.4.27-meson64 ARCH=arm64 all.......
cleaning build area...

DKMS: build completed.

dummy_rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

dw_apb_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

eq3_char_loop.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

fake_hmrf.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

generic_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

hb_rf_usb.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

led_trigger_timer.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

meson_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

pl011_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

plat_eq3ccu2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

rpi_rf_mod_led.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

rtc-rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.27-meson64/updates/dkms/

depmod...

DKMS: install completed.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service                                                                                                                                → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service →                                                                                                                                /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service                                                                                                                                → /lib/systemd/system/pivccu-dkms.service.

What is going wrong?

Thanks!
André

**Comment by Lemocin** [comment]
I just switched from a Raspberry to the Odroid and have the same issue. The installation says "WARNUNG: Das raw uart Interface konnte nicht gefunden werden." and that i should reboot. I did that but with no success. I have now flashed the image from the pivccu.de page and its working. 
Is the 5.4 kernel too new?

**Comment by eloo** [comment]
Same for me with the following kernel "5.8.16-meson64"

Are there any updates here? or maybe a workaround/solution?

**Comment by Lemocin** [comment]
I'm using the image from here https://www.pivccu.de/images/?dir=piVCCU3 with kernel 4.19.69-meson64 and it's working with pivccu3 version 3.51.6-41. It works flawlessly since april but the 3.53 version is not working for me.

**Comment by vigeland** [comment]
ERROR: modpost: "__stack_chk_guard" [/var/lib/dkms/pivccu/1.0.45/build/rtc-rx8130.ko] undefined!
Take a look at https://homematic-forum.de/forum/viewtopic.php?f=69&t=61372

It a known gcc / kernel problem.

What do do: ( workaround )
1) search with bash command find / -name hb_rf_eth.c -print . Two path found by the command.
2) go to both paths 
     /usr/src/pivccu-1.0.45/hb_rf_eth.c
     /var/lib/dkms/pivccu/1.0.45/build/hb_rf_eth.c
and run following script:
 for i in `ls *.c`; do echo "unsigned long __stack_chk_guard;
void __stack_chk_guard_setup(void)
{
__stack_chk_guard = 0xB233A44D;
}

void __stack_chk_fail(void) 
{

}">>$i; done
3 ) dpkg-reconfigure pivccu-modules-dkms

Do not remove and reinstall the package. You have to do the steps above again.

**Comment by alexreinert** [comment]
It is not clear, if this workaround is fully working: The guard hex identifier should be the same same over the whole kernel, there could be issues when using multiple CPUs/cores.
Best solution at the moment is to use a system based on Ubuntu focal, as the compiler will be the same for the kernel package and the local build modules.

**Comment by vigeland** [comment]
I read the issue comments, but it is real a c++ source problem or more gcc implementation assembler task ?
On my point of view, it should crash very fast in real live. The change use the same ID like kernel 32/64 Bit Value goes near zero. So every call with stack check should crash. 
  
My system has an uptime about one Week, Rock PI 4 Model C / USB

**Comment by alexreinert** [comment]
It is a issue inside the make file. Depending on the initial kernel config on the initial build, the gcc is called with a special parameter, which is not available in gcc 8.

**Comment by alexreinert** [comment]
There is an updated kernel module package in the testing APT Repo, which fixes this issue.

**Comment by ahessling** [comment]
Thank you! Working now flawlessly on Armbian 20.11.3 Buster (Kernel 5.9.14).
