### ISSUE TITLE
Attach another container

### ISSUE THREAD

**Issue by killtheartsoul** [alexreinert/piVCCU#255]
Hi Alex,

I installed your pivccu3 without any problems. I can enter the homematic webui and I connected already two homematicIP devices. Everything works fine. My next step would be to create another lxc-container for FHEM, but I struggle to get it done. When I search for existing containers with the command "lxc-ls" I get no output back. Now I am confused if the pivccu3 is running in a lxc-container or not and how to get another container for FHEM connected to the existing system.

Thank you for all your hard work ;o)

Kind regards

**Comment by alexreinert** [comment]
piVCCU is using a lxc container, but it is not using the default folder for the configuration files as the startup needs to be done outside lxc. Therefore you will not find it this lxc-ls using the default settings.
But there is issue in creating a new container for FHEM using the default paths, so just continue.

**Comment by alexreinert** [comment]
Can this be closed?
