### ISSUE TITLE
Keine WLAN Verbindung nach pivccu installation

### ISSUE THREAD

**Issue by Guddeee** [alexreinert/piVCCU#256]
Hallo Herr Reinert
Ich habe nach der Installationanleitung pivccu von Ihnen installiert. 
Nach dem reboot konnte keine WLAN-Verbindung hergestellt werden, da keine Router gefunden werden, obwohl dieser funktionierte. 
Mir fiel auch auf, dass ich in Ihrer Anleitung ausversehen Aspekte der _wired network bridging_ installiert habe.
Danach habe ich Ihre Anweisungen bzgl des WLAN bridging/routing befolgt. 

_Auszug aus der Anleitung_
Add network bridge (if you are using wifi please refer to the debian documentation how to configure the network and the bridge)

Verify, that eth0 is the name of your primary network interface:

sudo ip link show | cut -d' ' -f2 | cut -d: -f1 | grep -e '^e.*'
Update your config. (Replace eth0 if necessary)

sudo apt remove dhcpcd5
sudo apt install bridge-utils
sudo bash -c 'cat << EOT > /etc/network/interfaces
source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback

iface eth0 inet manual

auto br0
iface br0 inet dhcp
  bridge_ports eth0
EOT'
You can use an static IP address, too. In that case use instead:

sudo apt remove dhcpcd5
sudo apt install bridge-utils
sudo bash -c 'cat << EOT > /etc/network/interfaces
source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback

iface eth0 inet manual

auto br0
iface br0 inet static
  bridge_ports eth0
  address <address>
  netmask <netmask>
  gateway <gateway>
  dns-nameservers <dns1> <dns2>
EOT'
To use Wireless LAN, please take a look here

Reboot the system

Ich würde mich sehr freuen, wenn Sie mir bei meinem Fehler weiterhelfen könnten, da ich den Raspberry Pi 3b+ nun erst seit einer Woche kennenlernen darf.
Vielen Dank und einen schönen Tag

**Comment by alexreinert** [comment]
Ich fphl mich mal angesprochen, auch wenn ich nicht Reichert heiße. ;-)

Wenn man die Anleitung für eine Kabelgebundende Anbindung (Wired) ist es nicht so verwunderlich, dass eine Kabelose Funkanbindung (Wireless) nicht mehr geht. Daher bitte die richtige Anleitung nehmen.

Unabhängig davon: Für eine Gausautomatisierung kann ich von Wireless nur abraten, Kabelgebunden ist deutlich stabiler.

**Comment by Guddeee** [comment]
Verzeihung Herr Reinert,
Die autokorrektur spielt mir manchmal in die Hände.
Können Sie mir bei der Wiederherstellung behilflich sein?
Ich bevorzuge nun eine kabelgebundene Variante, jedoch würde es mich freuen die wlan einstellungen wiederherzustellen.
Vielen Dank schon einmal

**Comment by alexreinert** [comment]
Es sollte funktioneren, dass man die Anleitung für WLAN durchführt. Das muss man dann halt nicht per SSH machen, sondern mit lokaler Tastatur/Monitor.

**Comment by alexreinert** [comment]
Ist hier noch was offen?

**Comment by Guddeee** [comment]
Hallo,
Nein habe das raspbian noch einmal neu aufgesetzt

**Comment by bekulini** [comment]
Hallo Alex, ich hoffe das ist okay wenn wir "Duzen" :-) als erstes vielen herzlichen dank für deine tolle Arbeit, ich bin auch neu hier, daher vielleicht kommen mal "dumme" Fragen :-P
Ich habe IoBroker und piVCCU3 auf einem Raspberry pi installiert, als LAN. Jetzt überlege ich die Position des RaspPi zu ändern und via WLAN kommunizeren zu lassen. Da ich die WIRED Anleitung genommen habe, kann ich jetzt keine WLAN verbindung aufbauen. 
Daher meine Frage: kann ich das irgendwie nachträglich ändern oder muss ich komplettes setup von Raspian / Iobroker / piVCCU neu aufsetzen? 
Vielen Dank für deine Antwort.
Viele Grüße aus Eschborn
Bek

**Comment by alexreinert** [comment]
Ja, man kann das ändern, aber das ist kein Thema für einen Issue Tracker, erst recht nicht in einem Ticket, welches ein anderes Thema hat und bereits geschlossen ist. Besser wäre sowas in einem Forum aufgehoben.

**Comment by bekulini** [comment]
Sorry, werde drauf achten im richtigen "Raum" zu schreiben. Ich habe gerade nach eiem Forum hier auf Github gesucht, leider aber nichts zu piVCCU auf Github.community gefunden. Wäre super wenn Du mir einen Link schicken könntest. Danke!
