### ISSUE TITLE
HM-MOD-RPI-PCB wird nicht erkannt Raspberry pi 4B 2GB piVCCU3

### ISSUE THREAD

**Issue by Chrischan20** [alexreinert/piVCCU#258]
Hallo Alex,

ich bin neu hier und habe sehr wenige Erfahrungen mit Raspberry und der Programmierung.
Seit Tagen versuche ich erfolglos das piVCCU3 auf meinem Raspberry pi 4B 2GB mit dem Modul HM-MOD-RPI-PCB zu installieren. Leider wird das Modul nicht erkannt:
```
HMRF Hardware:  unknown
HMIP Hardware:  unknown
```

Zuerst habe ich das Image „Raspbian_Buster_Liste_piVCCU3_2019-07-11.img“ installiert.
Der pi startet normal hoch, die Homematic Webseite kann ich nach ein paar Minuten öffnen, das Passwort vergeben und mich einloggen.
Dann erscheint jedoch folgende Meldung:

> Eine Komponente der Homematic Zentrale reagiert nicht mehr.
> Hierfür kann es eine Reihe von Ursachen geben:
> es besteht keine Netzwerk-Verbindung
> die Stromversorung der HomeMatic Zentrale wurde unterbrochen
> mindestens eine Komponente der HomeMatic Zentrale ist abgestürzt
> Überprüfen Sie die Netzwerk-Verbindung und die Stromversorgung der HomeMatic Zentrale. Starten Sie ggf. die HomeMatic Zentrale neu.

Nun habe ich das Update durchgeführt `„sudo apt update && sudo apt upgrade“` und rebootet.

Im Raspberry selbst steht: 
```
„sudo pivccu-info“
piVCCU version: 3.51.6-39
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          RUNNING
PID:            2377
IP:             192.168.178.41
IP:             2a04:xxx
CPU use:        12.17 seconds
BlkIO use:      33.96 MiB
Memory use:     105.28 MiB
KMem use:       4.42 MiB
Link:           vethpivccu
 TX bytes:      1.83 MiB
 RX bytes:      433.54 KiB
 Total bytes:   2.26 MiB
```

Jetzt habe ich `“sudo apt install --reinstall pivccu-modules-raspberrypi“` durchgeführt und ein reboot gemacht. Leider auch ohne Erfolg pivccu-info wie oben.

Das Hardwaremodul und mein Raspberry läuft problemlos, wenn ich das Rasberrymatic Image „RaspberryMatic-3.51.6.20200229-rpi4.zip“ verwende.

Die Manuelle Installation „/docs/setup/raspberrypi.md“ stellt mich vor dasselbe Problem. 

Ich habe mehrfach das Image neu installiert, auch die manuelle Installation mehrfach durchgeführt (seit einer Woche beschäftige ich mich Abends mit nichts anderem mehr...) neu gestartet, den Raspberry nach der Installation auch über Nacht laufen gelassen, leider alles ohne Erfolg.

Mache ich irgendeinen Fehler oder woran kann das liegen?
Hoffentlich kannst du helfen.
Viele Grüße Christian

Hier noch ein paar Details, die in anderen Chats abgefragt wurden:

```
pi@raspberrypi:~ $ dpkg --get-selections | grep pivccu
pivccu-modules-dkms              install
pivccu-modules-raspberrypi   install
pivccu3                                        install
```

config.txt:
```
`# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
dtoverlay=pi3-miniuart-bt
enable_uart=1
force_turbo=1
dtoverlay=pivccu-raspberrypi
`

```

**Comment by alexreinert** [comment]
Softwareseitig sieht das alles erstmal gut aus. Kannst du bitte mal hochauflösende Bilder der Funkmoduls posten (Ober- und Unterseite und wie es auf den Pi aufgesteckt ist. Leider passiert es häufig, dass das Modul nicht korrekt gelötet wird.

**Comment by Chrischan20** [comment]
Danke für die rasche Antwort!
Schande auf mein Haupt... ich habe offensichtlich beim vielen probieren und auf und abstecken des Moduls beim letzten Mal das Modul versetzt eingebaut, nur eine Reihe war gesteckt. Im Gehäuse ist mir das nicht aufgefallen. 
Nun funktioniert es einwandfrei!
Vielen vielen Dank und sorry für die "dämliche" Anfrage...
