### ISSUE TITLE
Homematic USB Konfigurations-Adapter HM-CFG-USB-2

### ISSUE THREAD

**Issue by roesl** [alexreinert/piVCCU#26]
Hi,

is the Homematic USB Konfigurations-Adapter HM-CFG-USB-2 supported ?

regards
Georg

**Comment by alexreinert** [comment]
Not right now and as I have no test device, I'm not sure how to add support.

**Comment by alexreinert** [comment]
I have now an idea how to add support. But to implement that, I need a test device.

**Comment by leonsio** [comment]
Von Jens
Inkl Code hab’s mit einem device getestet und validiert. 


Das mache ich gerne. Also im Grunde musst du folgendes tun:

1) Erkennen das der HmIP-RFUSB eingesteckt ist und dann das cp210x kernel Modul laden:

https://github.com/jens-maus/RaspberryM ... #L112-L127

Danach solltest du dann ein /dev/ttyUSB0 vorfinden.

2) Dann ggf. das FirmwareUpdate auf die neueste Firmware des Sticks loslassen:

https://github.com/jens-maus/RaspberryM ... e#L94-L121

3) Dann beim Starten des HMIPServer.jar (aus /etc/init.d/S62HMServer) einfach /dev/ttyUSB in die crRFD.conf datei an die "Adapter.1.Port = XXX" stelle schreiben bevor HMIPServer gestartet wird:

https://github.com/jens-maus/RaspberryM ... er#L40-L43

Das sollte dann im Grunde reichen das der HmIP-RFUSB korrekt als HmIP Funkmodul erkannt wird und auch korrekt funktioniert.

Gruß 

Leo


Von meinem iPhone gesendet

**Comment by alexreinert** [comment]
Maybe you should read a little bit better. The topic is HM-CFG-USB-2 and not the HmIP-RFUSB.

**Comment by leonsio** [comment]
This device is EOL and i dont see any reason to support it. 
In the jens code some Lines above you can find the needed code for this device too 

Von meinem iPhone gesendet

> Am 29.01.2018 um 14:23 schrieb Alexander Reinert <notifications@github.com>:
> 
> HM-CFG-USB-2

**Comment by alexreinert** [comment]
At least two users are interested. So there are reasons.
And I know the code of Jens, but I prefer a proper quality assurance.

**Comment by mkunzmann** [comment]
When using this SW https://git.zerfleddert.de/cgi-bin/gitweb.cgi/hmcfgusb it should just work. This makes it look like a HM-CFG-LAN.

**Comment by alexreinert** [comment]
It is not that easy: the rfd of the original CCU firmware is not able to communicate with usb or user space applications. it only communicate with kernel space char devices.

**Comment by SchmollTroll** [comment]
> At least two users are interested.
Believe me - more than two users are interested  :-)

**Comment by daw87** [comment]
I am also - very - interested. I am coming from homegear where the USB stick worked without issues. I tried this workaround:

> When using this SW https://git.zerfleddert.de/cgi-bin/gitweb.cgi/hmcfgusb it should just work. This makes it look like a HM-CFG-LAN.

which really looks promising. I can connect to the hmlan daemon in the piVCCU webinterface (it is configured as HM Configuration Tool LAN and shows "connected") but I just cannot learn any device. I can start the learning process but nothing shows up in my CCU inbox. The hmlan daemon works flawlessly according to the port output (netcat localhost 1000).
Any ideas? Do I have to change the configuration in rfd.conf or anything else?

**Comment by dersimn** [comment]
How exactly did you configure the piVCCU and `hmland`?

Specifying just the IP in `Settings -> Control Panel -> LAN Gateway configuration` doesn't work for me.  
I started `hmland` with `-p 1000 -D` to see any output. When connecting with netcat there are lines flying through the terminal window, but the CCU doesn't seem to cause any traffic.

**Comment by PhilmacFLy** [comment]
Having the same Problem here, netcat gives me an output but CCU doesnt seem to want to talk with me. Any solutions for this yet? @dersimn

**Comment by dersimn** [comment]
I gave up on that.  
Probably the best approach would be to use an HB-RF-USB or similar

**Comment by sorryusernameisalreadytaken** [comment]
@PhilmacFLy @dersimn Did you try hmland with the I Flag?
See here: https://git.zerfleddert.de/cgi-bin/gitweb.cgi/hmcfgusb under "**Important compatibility information:**"

"_impersonate a LAN-interface (this replaces the identity string HM-USB-IF with HM-LAN-IF)_"
I could imagine that this could help and perhaps this was something what perhaps this is the config-key that differs from yours and @daw87 config.

**Comment by dersimn** [comment]
> @PhilmacFLy @dersimn Did you try hmland with the I Flag?

Actually I didn't 🤔

But meanwhile I gave up on this for real. These devices are obsolete and @alexreinert build a much better tool with his [HB-RF-USB (-2)](https://github.com/alexreinert/PCB#hb-rf-usb-2). There are options as well if you want to have some USB-Stick-like form factor: 
- [@stan23/HB-MOD-UART-USB](https://github.com/stan23/myPCBs/tree/master/HB-MOD-UART-USB)
- [@dersimn/HB-RF-USB-STICK](https://github.com/dersimn/HB-RF-USB-STICK)

---
@alexreinert 
> Not right now and as I have no test device, I'm not sure how to add support.

Do you want to have mine? I 'think' it still works, so you can have it for free - it's much better use in your hands, then laying here on my desk waiting to get old enough to be thrown away without bad conscience.

**Comment by PhilmacFLy** [comment]
Same here I didnt either and I gave up aswell. Started using zigbee2mqtt and mqtt stuff for the things I wanted to control
