### ISSUE TITLE
pivccu nicht mehr erreichbar

### ISSUE THREAD

**Issue by KarelPuhli** [alexreinert/piVCCU#263]
Hallo!
Meine pivccu auf dem Pi4 ist nicht mehr erreichbar. 

pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.51.6-39
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  FAKE_HMRF
HMIP Hardware:  HMIP-RFUSB
Board serial:   FKE9888633
Radio MAC:      0xb1966e
SGTIN:          3014F5AC94000416FB533CD6
State:          STOPPED

Das ganze muss über nacht passiert sein. Gestern Abend lief noch alles... 
sudo apt update
sudo apt upgrade 
ohne Erfolg. 

Das Gerät lässt sich auch nicht mehr anpingen. (Zielhost nicht erreichbar). 

Was kann ich tun? Vielen Dank im Voraus!

**Comment by alexreinert** [comment]
Ich würde darauf tippen, dass da ein neuer Kernel installiert wurde und noch kein Neustart gemacht wurde, kann das sein?

**Comment by KarelPuhli** [comment]
Sudo reboot habe ich gemacht. Leider kein Erfolg.

**Comment by alexreinert** [comment]
Ja, aber das wird nichts bringen, weil die notwendigen Kernel Module fehlen.

Was kommt bei
`sudo dpkg-reconfigure pivccu-modules-dkms`
Falls da auf ein Log verwiesen wird, dann bitte auch den Inhalt des Logs angeben.

**Comment by KarelPuhli** [comment]
pi@raspberrypi:~ $ sudo dpkg-reconfigure pivccu-modules-dkms
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.36
Kernel:  4.19.118+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118+/kernel/drivers/pivccu/
rmdir: konnte Verzeichnis 'kernel/drivers' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.36
Kernel:  4.19.118-v7+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7+/kernel/drivers/pivccu/
rmdir: konnte Verzeichnis 'kernel/drivers' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.36
Kernel:  4.19.118-v7l+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/
rmdir: konnte Verzeichnis 'kernel/drivers' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

------------------------------
Deleting module version: 1.0.36
completely from the DKMS tree.
------------------------------
Done.

Creating symlink /var/lib/dkms/pivccu/1.0.36/source ->
                 /usr/src/pivccu-1.0.36

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.19.118-v7l+ ARCH=arm all......
cleaning build area...

DKMS: build completed.

dummy_rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

dw_apb_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

eq3_char_loop.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

fake_hmrf.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

generic_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

hb_rf_usb.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

led_trigger_timer.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

meson_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

pl011_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

plat_eq3ccu2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

rpi_rf_mod_led.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

rtc-rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.118-v7l+/kernel/drivers/pivccu/

depmod...

DKMS: install completed.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.

**Comment by alexreinert** [comment]
Gut, dann jetzt bitte mal
`sudo pivccu-info`
Wenn da bei Kernel Modules available steht und bei Status stopped, dann bitte
`sudo systemctl start pivccu`

**Comment by KarelPuhli** [comment]
Hat funktioniert!
Super, vielen Dank!
Vielleicht noch einmal für mein Verständnis, was ich da nun genau gemacht habe.

**Comment by alexreinert** [comment]
Du hast die Kernel Module neu gebaut. Vor dem Reboot waren die nicht da (vermutlich durch das Kernel Update). Nach dem Reboot werden die von selbst neu gebaut (bei Bedarf), aber das dauert etwas. Du warst da vermutlich etwas zu ungeduldig. Als du den Befehl für das neu erstellen angesetzt hast (dpkg-reconfigure), waren die nämlich schon wieder da.

**Comment by KarelPuhli** [comment]
Alles klar! Herzlichen Dank für Deine Hilfe!!!
