### ISSUE TITLE
pivccu und docker

### ISSUE THREAD

**Issue by wolver79** [alexreinert/piVCCU#264]
Hallo Alex und Konsorten,

ich hätte mal eine Frage zu meinem pivccu3. Kurz eine Einleitung:
Aus Zeitmangel habe ich mir ein fertiges Pi4 pivccu System bei Smartkram gekauft. Hier läuft meines Wissens der iobroker auf dem Host selbst und pivccu ist containerisiert? So weit so gut. Zu erst habe ich dem System ein paar Update verbraten (mit apt und dem iobroker). Jetzt kam ich auf die glorreiche Idee noch pihole auf der Kiste laufen zu lassen. 
Ich stand vor der Entscheidung auf dem Host direkt oder als Docker. Ich habe mich für die Dockervariante entschieden. 

Gut oder weniger gut? :)

Am Ende hat das aber wohl dazu geführt, dass ich ein wenig die Netzwerkkonfiguration auf dem Pi geschrottet habe. 
Der Pi selbst ist noch per ssh erreichbar aber die pivccu leider nicht mehr. Jetzt wäre natürlich die Frage, wie ich das wieder fixen kann. Ich bin zwar ein wenig in Linux bewandert, aber wenn es um Container und das ganze Bridging geht bin ich dann doch raus. 

Was habe ich schon gemacht:
1. Der pivccu eine feste IP zugewiesen. Danach war die pivccu vom pihost aus "pingbar" (vorher war alles auf dhcp)

Ich habe schon ein wenig im Internet gestöbert und würde nach meinen Recherchen auf ein Bridgingproblem tippen?!?

Die Ausgabe von pivccu-info sieht so aus:
piVCCU version: 3.51.6-39
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
HMIP Hardware:  RPI-RF-MOD
Board serial:   5A4993EF8C
Radio MAC:      unknown
SGTIN:          3014F711A0001F5A4993EF8C
State:          RUNNING
PID:            1726
IP:             192.168.188.70
IP:             2a02:908:182:e880:c8a9:b8ff:fe91:f0d2
CPU use:        241.79 seconds
BlkIO use:      108.65 MiB
Memory use:     271.31 MiB

KMem use:       9.11 MiB
Link:           vethpivccu
 TX bytes:      2.81 MiB
 RX bytes:      7.27 MiB
 Total bytes:   10.08 MiB

brctl show sieht so aus:
bridge name     bridge id               STP enabled     interfaces
br0             8000.dca63259937b       no              eth0
                                                        vethpivccu
docker0         8000.0242b4b7ff0d       no

ein ifconfig ergibt folgendes:
br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.188.68  netmask 255.255.255.0  broadcast 192.168.188.255
        inet6 2a02:908:182:e880:dea6:32ff:fe59:937b  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::dea6:32ff:fe59:937b  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:59:93:7b  txqueuelen 1000  (Ethernet)
        RX packets 232968  bytes 59459088 (56.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 174695  bytes 22027294 (21.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:b4:b7:ff:0d  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether dc:a6:32:59:93:7b  txqueuelen 1000  (Ethernet)
        RX packets 279917  bytes 69319306 (66.1 MiB)
        RX errors 0  dropped 775  overruns 0  frame 0
        TX packets 161242  bytes 18882366 (18.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 2797582  bytes 893026219 (851.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2797582  bytes 893026219 (851.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethpivccu: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc0d:43ff:feca:693b  prefixlen 64  scopeid 0x20<link>
        ether fe:0d:43:ca:69:3b  txqueuelen 1000  (Ethernet)
        RX packets 24383  bytes 2977618 (2.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 58714  bytes 7701252 (7.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Kann ich hier einen Hinweis bekommen, wie ich das ganze Ding wieder ans Fliegen bekomme ggf. auch mit einem funktionierenden Docker?

Gruß
Julian

**Comment by alexreinert** [comment]
Für Support von kommerziell vertriebenen Systemen sollte man sich bitte an den Händler wenden, das Konzept Händler verdient Geld und die Opensource Entwickler haben die Arbeit und sonst nichts, funktioniert langfristig nicht.

Docker hängt leider diverse Firewall (iptables) Regeln auf alle Netzwerkinterfaces, welche dafür sorgen, dass sämtliche LXC Container kein Netzwerk mehr bekommen.

**Comment by dicer** [comment]
Was den Support angeht hat @alexreinert natuerlich voellig recht. Frag am besten da mal nach. Als kleiner Hinweis: Der docker daemon in neuerer Version kennt eine Option "--iptables=false". Aber mehr will ich in einem piVCCU issue dann auch nicht offtopic gehen

**Comment by wolver79** [comment]
Erst mal danke für den Hinweis. Was den Support betrifft, so wollte ich niemanden auf die Füße treten. Mir war nicht bewusst, dass der Kauf eines vorbespielten Raspis so auf Kritik stößt. Bei mir ist es mehr aus der Not heraus geboren, da der Nachwuchs sehr anspruchsvoll ist. Vor 20 Jahren hätte ich noch selbst den Lötkolben rausgeholt und die Einzelteile alle selbst bestellt, zusammen gebastelt und danach den Kram selbst installiert. So wollte ich den Weg ein wenig abkürzen.

Zum Fachlichen zurück:
Ich habe einfach den Dockerkram weggekegelt und danach ging es wieder. Und ihr hattet recht mit den iptables. Ein iptables-save vor und nach dem Dockerunfall haben gezeigt, dass der Docker durchaus Regeln anlegt, die verschwinden wenn man den Kram wieder in die Tonne tritt. 
Ich werde mir jetzt einfach erst mal einen anderen Weg suchen vielleicht über LXC o.ä.

Trotzdem noch mal Danke an Alex für dieses coole Stück Software. Mir ist durchaus bewusst, dass man da nebenberuflich noch viel Zeit investieren muss.

**Comment by nameless66** [comment]
# piVCCU + Docker on Rapsi 3 
- Make iptables rules persistant, see https://blog.mxard.com/persistent-iptables-on-raspberry-pi-raspbian
- "Add Docker on a router" iptables rule, see https://docs.docker.com/network/iptables/#docker-on-a-router
- Bind lxc.network.link to br0, see https://github.com/alexreinert/piVCCU/blob/master/docs/setup/wlan.md

```
## Update System
sudo apt update && sudo apt upgrade

## Install iptables-persistent
sudo apt-get install iptables-persistent # Save current rules for v4 & v6

## Add Docker on a router iptables rule
sudo nano /etc/iptables/rules.v4
*filter
:DOCKER-USER - [0:0]
-I DOCKER-USER -i br0 -o br0 -j ACCEPT
COMMIT

## Bind lxc.network.link to br0
sudo sed -i '/lxc.network.link/c\lxc.network.link \= br0' /etc/piVCCU3/lxc.config
```
