### ISSUE TITLE
pivccu-modules-raspberrypi lässt sich nicht installieren

### ISSUE THREAD

**Issue by glidingplane** [alexreinert/piVCCU#265]
Hallo Alex!

Ich verwende Ubuntu 19.10 auf einen Raspberry Pi 4 mit 4Gbyte und möchte die piVCCU3 mit dem HM-MOD-RPI-PCB verwenden um meine neuen Homematic IP Geräte in FHEM verwenden zu können.

FHEM ist installiert und dort nutze ich seit Jahren bereits das HM-MOD-RPI-PCB erfolgreich auf unterschiedlichen Pi (angefangen von Pi 2 bis eben jetzt Pi 4 mit 4GByte RAM) seit Ubuntu 16.x. Dh. Einrichtung des HM-MOD-RPI-PCB bisher erfolgreich wie ich meine, sonst würde es in FHEM nicht gehen.

Installation piVCCU lt. Anleitung von Dir soweit in Ordnung, allerdings lassen sich die pivccu-modules-raspberrypi nicht installieren mit folgender Meldung:

```
apt install pivccu-modules-raspberrypi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pivccu-modules-raspberrypi:armhf : Depends: raspberrypi-kernel-headers:armhf but it is not installable
                                    Depends: pivccu-modules-dkms:armhf but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Installation pivccu-modules-dkms und pivccu3 geht soweit einwandfrei durch.

Hast Du eine Idee was ich noch machen könnte, außer Neustart :-)

Vielen Dank im Voraus!
Markus

Hier ein paar Rand Infos:

```
apt-get install pivccu-modules-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pivccu-modules-dkms is already the newest version (1.0.36).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

apt-get install raspberrypi-kernel-headers
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package raspberrypi-kernel-headers:armhf is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'raspberrypi-kernel-headers:armhf' has no installation candidate

uname -a
Linux spies4b4 5.3.0-1027-raspi2 #29-Ubuntu SMP Wed May 27 10:47:51 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

pivccu-info 
piVCCU version: 3.51.6-39
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          STOPPED

/var/lib/piVCCU3/start_container.sh
<12>Jun 15 18:41:44 piVCCU3: HMRF hardware was not detected
<12>Jun 15 18:41:44 piVCCU3: HMIP hardware was not detected
kernel.sched_rt_runtime_us = -1
lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 850 Received container state "ABORTING" instead of "RUNNING"
lxc-start: lxc: tools/lxc_start.c: main: 329 The container failed to start
lxc-start: lxc: tools/lxc_start.c: main: 332 To get more details, run the container in foreground mode
lxc-start: lxc: tools/lxc_start.c: main: 334 Additional information can be obtained by setting the --logfile and --logpriority options

dpkg --list | grep pivccu
ii  pivccu-devicetree-armbian          1.0.27                             all          piVCCU DeviceTree files for armbian
ii  pivccu-modules-dkms                1.0.36                             all          DKMS package for kernel modules needed for Homematic
ii  pivccu3                            3.51.6-39                          arm64        piVCCU - Homematic CCU LXC container

ls -l /usr/src/
total 20
drwxr-xr-x  6 root root 4096 May 29 06:45 linux-headers-5.3.0-1026-raspi2
drwxr-xr-x  6 root root 4096 Jun 10 22:53 linux-headers-5.3.0-1027-raspi2
drwxr-xr-x 24 root root 4096 May 29 06:45 linux-raspi2-headers-5.3.0-1026
drwxr-xr-x 24 root root 4096 Jun 10 22:53 linux-raspi2-headers-5.3.0-1027
drwxr-xr-x  2 root root 4096 Jun 14 14:49 pivccu-1.0.36

vi /etc/boot/firmware/usercfg.txt
[pi4]
kernel=uboot_rpi_4.bin
max_framebuffers=2
[pi2]
kernel=uboot_rpi_2.bin
[pi3]
kernel=uboot_rpi_3.bin
[all]
arm_64bit=1
device_tree_address=0x03000000
dtoverlay=vc4-fkms-v3d
cmdline=btcmd.txt
dtparam=i2c_arm=on
dtparam=spi=on
dtparam=audio=on
#ergaenzt fuer HM-MOD-RPI-PCB (FHEM)
enable_uart=1
dtoverlay=pivccu-raspberrypi
dtoverlay=pi3-miniuart-bt
core_freq=250
#Alternativ kann auch dieser Eintrag gesetzt werden
#force_turbo=1
#Fuer Nutzung RPII2C Device innerhalb FHEM (fuer SUSV benoetigt)
# siehe auch CommandRef von FHEM, Suche nach RPII2C
device_tree_param=i2c0=on,i2c1=on

vi /boot/firmware/btcmd.txt
net.ifnames=0 dwc_otg.lpm_enable=0 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait
```

**Comment by alexreinert** [comment]
Vorraussetzung für die Nutzung des Funkmoduls auf einem Pi ist Raspbian. Das liegt nicht an der Hardware, sondern daran, dass man für die Ansteuerung der Dual CoPro Firmware des Funkmoduls zwingen eigene Kernel Module und ein Device Tree Overlay braucht. Bis jetzt hat mir hier einfach die Zeit gefehlr, dass von Raspbian auch auf Ubuntu zu portieren.

**Comment by glidingplane** [comment]
Guten Morgen Alex!

Auch wenn ich technisch gesehen kaum etwas davon verstehe was Du da schreibst so ist mir jetzt dennoch klar warum ich es nicht schaffe das HM-MOD-RPI-PCB bzw. die piVCCU zum Laufen zu bringen :-) Übrigens, habe interessehalber so einen HM-IP USB-Stick für mein oben beschriebenes System geordert, mit dem geht die piVCCU sofort. Allerdings hilft mir das für meine Installation aus mehreren Gründen insgesamt leider nicht weiter.

Ich habe mir erlaubt Dir aus Deiner Amazon-Wunschliste eine kleine Bestechung zukommen zu lassen, sollte morgen ankommen ...

Bitte sag Bescheid wenn Du Zeit für die Portierung finden konntest was mir echt sehr viel helfen täte. Würde es ja selbst machen, bin dazu aber viel zu wenig gut drauf.

Beste Grüße und vielen Dank, dass Du das Projekt piVCCU machst!
Markus

**Comment by JanHBade** [comment]
ich klink mich hier mal ein...

ich verwende nicht direkt piVCCU sondern den Docker-Container, der benötigt aber die Module von dir :)

Ich verwende Ubuntu Server 64Bit auf einem RPi 4 mit 8GiB RAM...

**Comment by glidingplane** [comment]
Hallo Alex!
Bist Du schon dazu gekommen die Vorbereitungen für Ubuntu für das pivccu-modules-raspberrypi zu portieren?
Danke!
Markus

**Comment by alexreinert** [comment]
Ich habe bereits angefangen, aber ich konnte es noch nicht finalisieren.

**Comment by hyra-soe** [comment]
Hallo Alexander,

ich klinke mich hier auch mal ein. Mein Anliegen ist im Prinzip das gleiche wie bei JanHBade. Auf meinem Pi-4 habe ich bereits Docker mit Container für OpenHub, zigbee2mqtt und Mosquitto. Für die Einbindung der HM-Rolladenaktoren wird Homematic nun der nächste. Voraussetzung ist aber, dass das Funkmodul HM-MOD-RPI-PCB angesprochen werden kann. 
Ich hoffe, dass du bei der Entwicklung schon ein Stück weiter gekommen bist. Zur Aufheiterung und als kleinen Ansporn versuche ich es auch mal mit einer kleinen Bestechung aus deiner Wunschliste  ;-) 

Viele Grüße

Hier noch einige Systeminfos:
``` bash
$ uname -a
Linux raspberrypi 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
$
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$
$ ll /usr/src/
insgesamt 32
drwxr-xr-x  8 root root 4096 Okt 24 14:28 .
drwxr-xr-x 11 root root 4096 Mai 27 18:27 ..
drwxr-xr-x 17 root root 4096 Sep  1 16:01 hello_pi
drwxr-xr-x 23 root root 4096 Okt 24 14:26 linux-headers-5.4.72+
drwxr-xr-x 23 root root 4096 Okt 24 14:26 linux-headers-5.4.72-v7+
drwxr-xr-x 23 root root 4096 Okt 24 14:26 linux-headers-5.4.72-v7l+
drwxr-xr-x  2 root root 4096 Okt 18 16:41 pivccu-1.0.45
drwxr-xr-x  3 root root 4096 Mai 27 18:28 sense-hat
```

**Comment by alexreinert** [comment]
Ich habe eben ein Update für das Paket pivccu-modules-raspberrypi ins testing APT Repository geladen, mit welcher theoretisch eine Installation unter Ubuntu 20.04 64 Bit für den Raspbbery Pi möglich ist. Was allerdings noch fehlt ist die komplette Doku dafür, zum einen die Abweichungen bei den Befehlen für die Anpassung der config.txt und zum anderen die komplett abweichenden Schritte für die Einrichtung der Network Bridge.

**Comment by JanHBade** [comment]
Es scheint zu laufen...

Jedenfalls kann ich Geräte anlernen (der Counter kommt und das soll ja schon ein ganz guter Test sein).

Ich muss die Tage mal ein ein Gerät an die Zentrale anlernen, mal gucken obs dann läuft...

Anpassung bei den linux-headers ist notwendig (nur der Name anders) ebenso bei der config.txt (Ubuntu arbeitet mit einer extra Datei für User Einträge)

(ich verwende deine Software mit einem Docker Container für Homematic)

**Comment by boppbo** [comment]
```
sudo cat /boot/firmware/usercfg.txt
# Place "config.txt" changes (dtparam, dtoverlay, disable_overscan, etc.) in
# this file. Please refer to the README file for a description of the various
# configuration files on the boot partition.
dtoverlay=disable-bt
```

```
sudo cat /boot/firmware/cmdline.txt
net.ifnames=0 dwc_otg.lpm_enable=0 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc
```

```
/etc/multimacd.conf:
Coprocessor Device Path = /dev/ttyAMA0
```
XRef: https://github.com/alexreinert/debmatic/issues/131

**Comment by alexreinert** [comment]
/dev/ttyAMA0 in der /dev/multimacd.conf ist falsch, es muss für den multimacd ein raw-uart verwendet werden. Ein normales tty kann einige ioctls nicht und hat eine massiv zu hohe Latenz.

**Comment by JanHBade** [comment]
muss leider meinen Eintrag wieder zurückziehen...

Ohne Grund lief auf einmal der HM IP Teil gar nicht mehr, ich kann keine IP Geräte mehr anlernen...auch ein Neustart bringt keine Abhilfe...

Werde wohl doch einen extra Pi spendieren mit rasperrymatic drauf...

(d.h. nicht das es allgemein nicht geht, nur bei mir mit docker plus den dkms Teil von hier scheint es nicht zu laufen)

**Comment by alexreinert** [comment]
Nur so eine Idee: Du hast vor kurzem ein Gerät an einen der USB3 Ports gehängt und ungefähr seit dem Zeitpunkt gehen die HmIP Geräte nicht mehr?

Im Übrigen: Genau die Kernel Module werden auch in RaspberryMatic verwendet (und eine ältere Version der Kernel Module auch in der Original CCU3).

**Comment by JanHBade** [comment]
Seit dem Neustart haben die USB Buchsen keine Geräte gesehen....

Ich kann gerne noch weitere Tests machen/ Logs posten wenn das was hilft 

Mit RasperryMatic hätte ich aber wieder 32Bit und weniger Komponenten die da noch mit rumzicken...




Sonntag, 27. Dezember 2020, 13:41 +0100 von notifications@github.com  <notifications@github.com>:

**Comment by jollyjinx** [comment]
Mal als kurzes positives Feedback hier für das tolle pivccu kernel modul.

Ich habe es unter ubuntu 20.04 64-Bit auf einem Raspberry Pi 8GB installiert und  lasse da drauf Raspberry Matic in einem docker container mit einem HM-MOD-RPI-PCB laufen und es läuft bisher tadellos. 
Einzig beim Installieren des kernelmoduls habe ich 'ewig' warten müssen so dass ich einige Male bei der Testinstallation abgebrochen hatte, weil ich wirre fehler während der Installation im syslog sah. Aber als ich mal bei der Testinstallation 'ne viertel Stunde weg war , lief es dann doch irgendwann durch.

Meine aktuelle Konfiguration:

```
root@ubuntu:/# cat /boot/firmware/cmdline.txt 
net.ifnames=0 dwc_otg.lpm_enable=0 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc
root@ubuntu:/# cat /boot/firmware/usercfg.txt 
dtparam=audio=off
enable_uart=1
dtoverlay=disable-bt
dtoverlay=pivccu-raspberrypi
```

Kommandos bei der installation waren:

```
sudo wget -q -O - https://www.pivccu.de/piVCCU/public.key | sudo apt-key add -
sudo bash -c 'echo "deb https://www.pivccu.de/piVCCU testing main" > /etc/apt/sources.list.d/pivccu.list'

sudo apt install -y net-tools pivccu-modules-dkms

sudo sh -c 'echo eq3_char_loop >/etc/modules-load.d/eq3_char_loop.conf'
sudo modprobe eq3_char_loop

sudo apt install pivccu-modules-raspberrypi

sudo service pivccu-dkms start
sudo apt install docker.io
sudo usermod -aG docker ${USER}


docker run --tty --interactive --name ccu --volume=$HOME/hmccu2/ccu_data:/usr/local --privileged --restart=always --stop-timeout=30   --device=/dev/raw-uart:/dev_org/ttyAMA0:rwm --hostname homematic-raspi ghcr.io/jens-maus/raspberrymatic:snapshot
```

Also nochmal Dank' an @alexreinert
