### ISSUE TITLE
keine richtiger Duty Cycle-Wert auf Hauptseite mit HmIP-RFUSB

### ISSUE THREAD

**Issue by Hirsch-DE** [alexreinert/piVCCU#266]
Auf der Webseite wird ein Duty Cycle-Wert von 0% immer angezeigt.
Auch mittels devconfig.cgi -> RSSI-Liste ist immer leer.

**Comment by alexreinert** [comment]
Auf der devconfig Seite werden bei der CCU3 generell nur HM Geräte und keine HmIP Geräte angezeigt.
Dem HmIP-RFUSB kann man keine Informationen zum DutyCycle entlocken, daher kann man auch nichts anzeigen.

**Comment by Hirsch-DE** [comment]
Dann kann man hat nichts machen. Schade.
