### ISSUE TITLE
Einbindung eines HM-MOD-RPI-PCB mittels ser2net für HomematicIP-Devices möglich?

### ISSUE THREAD

**Issue by LeelooDallas-github** [alexreinert/piVCCU#267]
Hallo,
da ich nach längere Suche keine für mich verständliche Antwort gefunden habe, hoffe ich auf diesem Weg antworten zu finden.

Hintergrund:
Da Homematic nach und nach die Homematic-Serie (ohne IP) auslaufen lässt, möchte Ich nun neuere Homematic-IP Komponenten in mein bestehendes Smarthome-System einbinden. Auf der Suche nach Informationen bin ich immer wieder, mittels positiver Kommentare, auf dieses Projekt gestoßen. Scheint eine sauber Sache zu sein. Bereits jetzt Glückwunsch dazu.

Meine Fragen zum Projekt:
Kann ich Homematic-IP Komponenten in piVCCU ansteueren, wenn das Funkmodul "HM-MOD-RPI-PCB" auf einer externen Hardware (z.B. einem raspPi) läuft? z.B. über ser2net? Wenn Ja, wie mache ich dies konkret.

Meine aktuelle Sitiation sieht wie folgt aus.
[x-HM-Komponenten] <-> [HM-MOD-RPI-PCB auf raspPi-I] <= ser2net => [FHEM auf VM-1 auf Synology-NAS]

Erweiterungsziel.
[neue HM-IP-Komponenten] <-> [HM-MOD-RPI-PCB auf raspPi-II] <= ser2net => [piVCCU auf VM-1 auf Synology-NAS] <=> [FHEM auf VM-1 auf Synology-NAS]

piVCCU könnte auch auf einer separaten VM laufen. Auf der gleichen VM wie FHEM wäre aber schöner, da hier bereits alles bzgl. Datensicherung etc. eingestellt ist. So könnte alles wichtige auf einen Zug gesichert und wiederhergestellt werden.

Ich hoffe, ich habe den richtigen Kanal gefunden und beanspruche Dich nicht zu sehr.
Bereits jetzt vielen Dank für Deine Hilfe.

Dir eine schönes Wochenende und bleib gesund.

Viele Grüße
Leeloo_Dallas

**Comment by alexreinert** [comment]
piVCCU basiert auf der Original CCU und deren ARM Binaries und läuft daher nur auf ARM Systemen und das schließt die Synology. Das ist der Grund für das Schwesterprojekt debmatic, welchesneben ARM auch x64 unterstützt und direkt sauber innerhalb einer Debian oder Ubuntu Umgebung läuft.
Für den entfernten Anschluss des Funkmoduls habe ich auch schon mal etwas vorbereit: Es gibt die HB-RF-USB bzw. neu seit kurzem die HB-RF-USB-2 Platine, mit welcher man das Funkmodule HM-MOD-RPI-PCB oder RPI-RF-MOD per USB anschließen kann ggf. auch über einen USB over CAT Extender. Demnächst kommt dann noch die HB-RF-ETH dazu, welche über (aktives) Netzwerk angeschlossen werden kann inkl. optionaler PoE Versorgung.

**Comment by LeelooDallas-github** [comment]
Danke, für die schnelle Rückmeldung.
Dein Schwesterprojekt „debmatic“ war mir bis dato noch nicht bekannt, ist dann aber wohl genau der was ich einsetzen möchte. Bereits jetzt vielen Dank für Deine Mühen.
Auch Deine Hinweise zu den Platinen HB-RF-USB, HB-RF-USB-2 sind für die Zukunft interessant, wobei eine HB-RF-ETH Platine wohl am interessantesten ist.
Da ich jedoch bereits einen freien raspPi3 sowie ein HM-MOD-RPI-PCB Modul besitze, nochmals eine Frage zur ser2net Anbindung von HM-IP-Devices. 
Funktioniert diese Variante auch im Kontext Deines debmatic –Projektes?

Hier Auszüge aus dem FHEM-Wiki, welche ggf. zur besseren Einordnung meine Frage dienen.
=====> Auszüge aus 
https://wiki.fhem.de/wiki/HM-MOD-RPI-PCB_HomeMatic_Funkmodul_f%C3%BCr_Raspberry_Pi#Verwendung

Variante mit ser2net
Diese Installation auf dem Pi mit dem HM-MOD-RPI-PCB Modul bitte im Kontext sudo su ausführen. 
apt-get install ser2net
echo "4000:raw:0:/dev/ttyAMA0:115200 NONE 1STOPBIT 8DATABITS HANGUP_WHEN_DONE" >> /etc/ser2net.conf
# Den Dienst neu starten
systemctl restart ser2net
…..
Wurde dagegen das Gerät über WLAN oder LAN durch das UART-Modul angebunden, erfolgt die Einbindung in FHEM durch 
 define WLAN_HmUART HMUARTLGW uart://<IP-Adresse>:<Portnummer>
……
<===== ENDE  Auszüge

Besteht die Möglichkeit, dass die HM-IP Geräte über diese Art und Weise innerhalb Deines Projekts angesprochen werden können?

Dir eine gute und gesunde Woche.

CU
Leeloo

**Comment by alexreinert** [comment]
Nein, ser2net funktioniert nicht und kann auch nicht funktionieren, da dort durch Buffering ein zu hohe Latenz erzeugt wird (max. 5ms vom etsten gesendeten Byte eines Rrquests bis zum letzten empfangenen Byte einer Response, wobei das Funkmodul alleine schon eine Latenz von 2ms hat). Das ist auch der Grund für die HB-RF-ETH, wäre es mit einem Pi möglich, hätte ich mir den nicht gerade geringen Aufwand der eigenen Platine erspart.

**Comment by LeelooDallas-github** [comment]
Vielleicht lohnt sich der Aufwand ja zukünftig. Ich wäre z.B. am Kauf einer solchen Hardware interessiert. Als Komplett-Set oder als Selbstbau-Set. Wie sehen da Deine Pläne aus?

**Comment by alexreinert** [comment]
Wie geschrieben, es ist mit ser2net nicht möglich, das ist keine Frage des Aufwandes, es geht einfach technisch nicht.

Die HB-RF-ETH werde ich wie meine anderen Platinen als Open Source veröffentlichen. Sehr wahrscheinlich wird es aber auch die Möglichkeit geben, diese teilbestückt kaufen zu können, allerdings nicht durch mich, der Handel mit Elektronik ist mir in Deutschland einfach viel zu kompliziert.

**Comment by LeelooDallas-github** [comment]
Ok, cool. Ich werde dann wohl demnächst loslegen und mich intensiver mit Deinen Projekten beschäftigen.
Danke nochmals für Deine Hilfe.
