### ISSUE TITLE
password for Raspbian_Stretch_Lite_piVCCU_2017-12-18.zip  does not work

### ISSUE THREAD

**Issue by derknut23** [alexreinert/piVCCU#27]
The following user credentials as mentioned in the Readme.MD file for the raspberry pi image https://www.pivccu.de/images/Raspbian_Stretch_Lite_piVCCU_2017-12-18.zip do not work.
user: pi
password: raspberry

Could you please upload a new image with the default rasbian login credentials as mentioned in Readme.MD

**Comment by alexreinert** [comment]
It does work, last tested a week ago.
maybe you use a german keyboard and y and z are switched?

**Comment by derknut23** [comment]
Thank's for the hint. You are right, could login now.
