### ISSUE TITLE
HmIPUSB not detected

### ISSUE THREAD

**Issue by phrogg** [alexreinert/piVCCU#270]
Thanks for this great project, it has been of service the last years. I now wanted to rebuild my whole SmartHome from scratch and currently trying to get piVccu3 to work. My problem is that my stick which worked the last two years does not get recognized when I run `sudo dpkg-reconfigure pivccu3`. However when I run `ls- la /dev/serial/by-id` I get this: `lrwxrwxrwx 1 root root 13 Jul  4 19:13 usb-Silicon_Labs_eQ-3_HmIP-RFUSB_3014F711A061A7C00010CECF-if00-port0 -> ../../ttyUSB0`. I don't if I configured something wrong, or could it be that my stick isn't working correctly maybe? Any idea on how to check if the stick works normally? I must add to that the other serial sticks like my zigbee stick gets detected during the reconfigure. Maybe I need an UDEV rule or something?
Thanks in advance!

**Comment by alexreinert** [comment]
```sudo dpkg-reconfigure pivccu3``` never had a detection of radio modules, so please explain your issue a little more.

**Comment by phrogg** [comment]
I thought that last time when I installed this and ran the reconfigure, I think what I got was this:
![image](https://user-images.githubusercontent.com/1367949/86518194-d127ac80-be2f-11ea-9fe2-d8b553b0eb92.png)
But like I said in the picture there is only my Zigbee coordinator not the HmIP Stick. 

You mean it's normal that it's not coming up anymore? I tried to connect several devices to the **ccu** but unfortunately none of them worked.

**Comment by alexreinert** [comment]
There are two dialogs: First one is for the radio module (but without a real detection), second one (your image) is for (additional) USB devices, that should be available inside the container. The HmIP-RFUSB will be not in this list, as it is not supported to attach it as USB device to the container, instead it will be used to emulate a RPI-RF-MOD inside the container.

**Comment by phrogg** [comment]
Ahh, so that means the odds are good that my stick is working? But there is no way to test that?

**Comment by alexreinert** [comment]
You can use pivccu-info.

**Comment by phrogg** [comment]
> You can use pivccu-info.

I actually tried that, but there was no difference when the HmIP was plugged to when it was not plugged in...
