### ISSUE TITLE
CCU2 Systemsteuerung fehlt

### ISSUE THREAD

**Issue by niwre2019** [alexreinert/piVCCU#272]
Hallo,
ich habe mir piVCCU um meinem Raspberry PI 2 B installiert mit einem Funkmodul RPI-RF-MOD und es läuft soweit alles super. Wenn ich allerdings die Systemsteuerung aufrufe, dann ist der Inhalt leer.
Danach habe ich nochmal alles neu installiert und mein Backup zurückgespielt, und alles hat incl. der Systemsteuerung einwandfrei funktioniert.
Nach ein paar Stunden wollte ich die Systemsteuerung wieder aufrufen, allerdings ist der Inhalt jetzt wieder leer.
Hast du eine irgendeine Idee, woran das liegen könnte und wie ich das wieder reparieren kann, ohne gleich wieder alles neu zu installieren?
Für Hilfe wäre ich wirklich sehr dankbar.
Viele Grüße 
Erwin

**Comment by alexreinert** [comment]
Welche Version (pivccu-info)? Browser-Cache gelöscht und Seite mit Strg+F5neu geladen? Ist irgendein Adblocker, JS-Blocker, etc. im Browser installiert?

**Comment by niwre2019** [comment]
Browser-Cache habe ich mehrfach gelöscht, Seite neu laden versucht, jegliche Blocker habe ich deaktiviert. Auf der originalen CCU2 hatte ich damit nie Probleme und auch mit piVCCU kann ich die Seite direkt nach einer Neuinstallation mit meiner Konfiguration völlig problemlos aufrufen. Die neueste Version von piVCCU habe ich auch versucht, die macht bei mir aber nur Probleme, deshalb bin ich wieder auf die 2.47.20 zurück. Ansonsten läuft alles einwandfrei incl. der Plugins Homeputer CL und CL Webserver.

pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 2.47.20-55
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
HMIP Hardware:  RPI-RF-MOD
Board serial:   5a4994029d
Radio MAC:      unknown
SGTIN:          3014f711a0001f5a4994029d
State:          RUNNING
PID:            15140
IP:             192.168.178.9
IP:             2a02:810d:9340:5d5c:e808:caff:fef9:e851
CPU use:        1737.62 seconds
BlkIO use:      170.79 MiB
Memory use:     118.14 MiB
KMem use:       5.21 MiB
Link:           vethSHN19F
 TX bytes:      143.49 MiB
 RX bytes:      53.43 MiB
 Total bytes:   196.92 MiB

**Comment by alexreinert** [comment]
Mir ist bisher so ein Problem nie zu Ohren gekommen.
Ich hoffe es ist verständlich, dass ich für eine solch alte Version auch nur eingeschränkt Support leisten kann.
Was sinnvoll wäre zu prüfen: Auf dem Pi mit SSH einloggen, mit ```pivccu-attach``` in den Container wechseln und dort schauen, ob beim Aufruf der Systemsteuerung unter /tmp Dateien cgimail* angelegt werden. Mit diesen könnte mas Problem weiter eingrenzen. Ebenfalls interessant wären /var/log/messages und /var/log/hmserver.log

**Comment by niwre2019** [comment]
Ja, das ist mir klar und ich bin für jede Hilfe natürlich dankbar.


[hmserver.log](https://github.com/alexreinert/piVCCU/files/4897747/hmserver.log)

[documents.zip](https://github.com/alexreinert/piVCCU/files/4897749/documents.zip)

Unter /tmp werden beim Aufruf der Systemsteuerung leider keine cgimail* angelegt.

**Comment by niwre2019** [comment]
Hallo Alex,

konntest du noch etwas in den Log-Datein finden?

Eine kleine weitere Frage, ich habe unter /usr/local/crontabs/root einen Eintrag hinzugefügt, leider wird der Job nicht zu ausgeführt, muss ich da noch etwas neu starten oder ist das die falsche Stelle?

Gruß
Erwin

**Comment by niwre2019** [comment]
Das mit dem Cronjob hat sich erledigt, funktioniert auf einmal problemlos, war wohl zu ungeduldig.
Sorry

**Comment by alexreinert** [comment]
Ich kam leider erst heute dazu, allerdings ist die Zip-Datei leer.

**Comment by niwre2019** [comment]
Ich habe mir die ZIP-Datei gerade selbst nochmal runtergeladen, mir sind die zwei Dateien enthalten, das ist jetzt allerdings merkwürdig.  Ich lade sie einfach nochmal hoch.

[hmserver.log](https://github.com/alexreinert/piVCCU/files/4910761/hmserver.log)
[messages.txt](https://github.com/alexreinert/piVCCU/files/4910762/messages.txt)

**Comment by alexreinert** [comment]
Mir kommen ein paar Dinge im Log komisch vor, u.A. ein Eintrag mit der AES Chalange, welcher auf ein Problem mit dem Funkmodul oder der Stromversorgung des Funkmoduls hindeuten könnte. Aber wirklich erkennen kann ich leider nichts.
Ich würde ja ein Update empfehlen. (Und die dabei aufgetretenen Probleme lösen anstatt zurückzurollen)

**Comment by niwre2019** [comment]
Hallo Alex,

vielen Dank fürs anschauen. Die Fehler mit der AES Chalange sind mir auch aufgefallen, die haben sich von alleine erledigt, nachdem ich den Raspi an seinen richtigen Platz mit dem optimalen Empfang gestellt habe. 
Derzeit läuft piVCCU aus der fehlenden Systemsteuerung ohne sonstige Probleme.

Wenn ich ein Update mache, dann aber gleich auf piVCCU3, dann bin ich wenigstens ganz aktuell. Ich hoffe nur, dass mein Raspi 2B das noch vernünftig packt. 

Wenn ich mit dem Update soweit bin und damit auch die gleichen oder ähnliche Probleme habe, dann melde ich mich wieder. Solange schließe ich den Beitrag hier erstmal.

Vielen Dank für deine Unterstützung.

Gruß
Erwin
