### ISSUE TITLE
Sporadischer Netzwerkverlust - LED auf Funkmodul blinkt schnell blau

### ISSUE THREAD

**Issue by luigik666** [alexreinert/piVCCU#273]
Hallo Alex,

folgendes Problem auf meinem Tinkerboard mit piVCCU habe ich sporadischen Netzwerkverlust. Ein Zugriff auf das sowohl Webinterface der CCU3 als auch auf das TB (DHCP, bekommt aber von der Fritzbox immer dieselbe IP .38 zugewiesen) selber funktionieren nicht mehr. Abhilfe nur durch Trennen vom Netzteil.
Die CCU3 habe ich mit fixer IP Adresse (.42) konfiguriert, da sie sich bei gelegentlichem Anmelden mit anderer MAC Adresse meldet und dann von der Fritzbox eine andere IP bekommt. Dann kann ich sie mit anderen Diensten nicht mehr erreichen, darum die fixe Adresse. Heute sporadischer Versuch der CCU einer neuen Netzwerkverbindung:

15.07.2020 17:40:15 | Homematix | 192.168.178.42 | 6A:8B:32:9D:A9:89 | LAN 1
15.07.2020 17:48:55 | PC-192-168-178-42 | 192.168.178.42 | 6A:8B:CE:FB:A9:89 |  
15.07.2020 18:00:05 | PC-192-168-178-42 | 192.168.178.42 | 6A:8B:73:33:A9:89 |
15.07.2020 18:47:47 | PC-192-168-178-42 | 192.168.178.42 | 6A:8B:08:A9:A9:89 |  
15.07.2020 18:55:45 | tinkerboard | 192.168.178.38 | 88:D7:F6:C3:02:B0 | LAN 1
15.07.2020 19:21:45 | tinkerboard | 192.168.178.38 | 88:D7:F6:C3:02:B0 | LAN 1
15.07.2020 19:32:46 | tinkerboard | 192.168.178.38 | 88:D7:F6:C3:02:B0 | LAN 1
15.07.2020 19:34:55 | PC-192-168-178-42 | 192.168.178.42 | 6A:8B:F1:18:A9:89
15.07.2020 19:42:26 | PC-192-168-178-42 | 192.168.178.42 | 6A:8B:99:97:A9:89 |  
15.07.2020 19:42:45 | PC-192-168-178-38 | 192.168.178.38 | 88:D7:FA:0B:02:B0
15.07.2020 19:48:15 | PC-192-168-178-42 | 192.168.178.42 | 6A:8B:76:3E:A9:89
15.07.2020 19:50:45 | PC-192-168-178-38 | 192.168.178.38 | 88:D7:AC:2C:02:B0 |

Danach Neustart, Tinkerboard ist jetzt wieder mit .38 verbunden MAC 88:D7:F6:C3:02:B0, CCU3 mit .42 verbunden MAC 6A:8B:32:9D:A9:89.

In der lx.config steht <mac_auto> (siehe issue 118), mit einer Änderung hier verspreche ich mir aber nichts, das wird ja nicht der Grund für die Netzwerkunterbrechungen und die (nicht gelungenen) reconnects sein.

Manchmal läuft das System Tage bis Wochen durch, manchmal bekomme ich schon nach wenigen Stunden Abbrüche und muss dann komplett neu starten.

Die CCU3 läuft problemlos weiter, die homebridge (auf dem tinkerboard installiert) ist halt nicht mehr erreichbar.

Hast Du eine Idee, woran das liegen könnte?
Gruß, Johannes

**Comment by alexreinert** [comment]
Wie erfolgt die Stromversorgung? Ist der Kernel vom Host aktuell?

**Comment by luigik666** [comment]
Ist das DVE Netzteil (DSA-13PFC-05 FEU) von ELV, sind 2,5A Output zu schwach?
Kernel ist 4.19.69-rockchip

**Comment by luigik666** [comment]
Tritt immer noch gelegentlich (seltener?) auf, evtl. auch ein Temperaturproblem des Tinkerboard (teilweise >70°C). Ich schließe jetzt mal diesen Issue.
