### ISSUE TITLE
Räume Umbenennung wird nicht übernommen!

### ISSUE THREAD

**Issue by neostreamer** [alexreinert/piVCCU#277]
piVCCU3
Aktuelle Firmwareversion: 3.51.6

Hallo Alex, mir ist gerade folgender Fehler in der Weboberfläche aufgefallen:

Habe den Standard Raum "Badezimmer" meinem Thermostat und Sensor zugeordnet.

Einstellungen -> Räume
Danach den Raum Badezimmer in "Badezimmer OG" geändert und noch ein neues "Badezimmer DG" angelegt!

Bei den Geräte Zuordnungen wurde danach nach wie vor nur "Badezimmer" angezeigt!?
Weder OG noch der neue Raum DG, auch nicht bei Räumen mit dem Filter!
Auch ein Aufheben der Zuordnungen ("Badezimmer") zu den Geräten hatte nichts gebracht! 
Erst das Löschen beider Räume und dem darauf folgenden neu Anlegen hatte funktioniert.
Einen zwischenzeitlichen Neustart habe ich allerdings nicht durchgeführt.

Andere Räume die ich schon mal abgeändert hatte haben mir bisher keine solche Fehler verursacht!

Ist jetzt kein schwerwiegender Fehler, aber ich wollte es mal mitteilen!
Danke für deine ganze Mühe, ich bin gerade erst von Homematic IP zur piVCCU3 von dir gewechselt.
Hoffe ich kann konstruktiv helfen.

**Comment by alexreinert** [comment]
Das Verhalten kann ich bestätigen, allerdings auch auf einer Original CCU3.
Damit ist kein piVCCU Issue, sondern ein Problem in der Original Firmware und müsste dort zuerst behoben werden.

**Comment by neostreamer** [comment]
Danke für die schnelle Rückmeldung!
Hoffe der Hersteller weiß das bereits und arbeitet daran.

Danke
