### ISSUE TITLE
piVCCU3 startet nicht automatisch beim Hochfahren;  Active: failed (Result: timeout)

### ISSUE THREAD

**Issue by thomasszavuly** [alexreinert/piVCCU#278]
Hallo, 

folgender Pi wird verwendet: Raspberry Pi 3 Model B ARM-Cortex-A53
pivCCU3 laut Ihrer Anleitung installiert
Solange ich als Radio Module die Fake Emulation genutzt habe, startete die CCU automatisch und war sofort da. Seit dem ich es auf HmIP-RFUSB umgestellt, rennt die CCU auf einen timeout und ich muss sie jedes Mal dann wieder manuell anstoßen. Folgendes Funkmodul wird benutzt: https://de.elv.com/elv-homematic-ip-arr-bausatz-rf-usb-stick-fuer-alternative-steuerungsplattformen-hmip-rfusb-fuer-smart-home-hausautomation-152306?fs=3108996018

Weitere Infos: 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/33428596/89902902-4fbdf980-dbe7-11ea-8c4f-d19a0970ac6d.png">
<img width="762" alt="image" src="https://user-images.githubusercontent.com/33428596/89903126-93b0fe80-dbe7-11ea-94b8-eef2f5ba4f0b.png">
<img width="762" alt="image" src="https://user-images.githubusercontent.com/33428596/89903375-de327b00-dbe7-11ea-9482-9aba876e5247.png">
<img width="684" alt="image" src="https://user-images.githubusercontent.com/33428596/89903505-0326ee00-dbe8-11ea-9040-70cefe3e60ac.png">

Der Befehl "sudo dpkg-reconfigure pivccu-modules-dkms" liefert auch keine Fehlermeldung...

**Comment by alexreinert** [comment]
Wie ist der Inhalt der Datei /etc/default/pivccu3

**Comment by thomasszavuly** [comment]
PIVCCU_HMRF_MODE="Fake-HmRF"
PIVCCU_HMIP_MODE="HmIP-RFUSB"
PIVCCU_USB_DEVICES=""
PIVCCU_FAKE_SERIAL="FKE9060657"
PIVCCU_FAKE_RADIO_MAC="0xb7bce3"

**Comment by alexreinert** [comment]
Ist CUxD installiert?

**Comment by alexreinert** [comment]
Oder irgendeine andere Software, welche versucht auf TTY Geräte zuzugreifen?

**Comment by thomasszavuly** [comment]
Nein vorerst ist keine zusätzliche Software installiert, im späteren Verlauf würde ich CUxD installieren wollen

**Comment by alexreinert** [comment]
Hat der Stick schon mal funktioniert? Sind da alle Lötstellen zur eigentlichen Funkplatine sauber verlötet? Im Zweifel gerne mal Bilder posten.

**Comment by thomasszavuly** [comment]
ja wurde auf einem Raspberry 2 eingesteckt wo dann das Radio Module auf HmIP RFUSB umgestellt wurde und dort war nach dem Hochfahren des PI's sofort die CCU da. 
Beim ersten automatisierten Versuch kommt der timeout und wenn ich danach den Befehl "sudo systemctl status pivccu.service" ausführe wäre die CCU wieder einsatzbereit.

**Comment by alexreinert** [comment]
Das verstehe ich jetzt nicht. systemctl status zeigt nur der Status an, aber startet nichts. Was ist damit gemeint
> wäre die CCU wieder einsatzbereit

**Comment by thomasszavuly** [comment]
sorry, falschen Befehl kopiert; mit "sudo systemctl start pivccu.service" funktioniert dann die CCU.

**Comment by alexreinert** [comment]
ok, dann macht es mehr Sinn.
Kann es sein, dass eine recht langsame SD Karte verwendet wird? Ich konnte den Fehler bei mir nachstellen, allerdings nur mit einer einzigen meiner SD Karten, von welcher ich weiß, dass sie langsam ist.
In dem Fall könnte man als Workaround probieren, die Datei /lib/systemd/system/pivccu.service zu editieren und in der Sektion `[Service]` die Zeile `TimeoutStartSec=300` aufzunehmen.

**Comment by thomasszavuly** [comment]
wunderbar, mit diesem Workaround wird die CCU nun ohne zusätzlichen Befehl hochgefahren. Lag also offensichtlich wirklich an einer langsamen SD-Karte. Werde nun aber auf eine schnellere SD-Karte wechseln.
Vielen Dank!!
