### ISSUE TITLE
Using CUxD and USB devices ???

### ISSUE THREAD

**Issue by real-easy** [alexreinert/piVCCU#28]
how i make that the PI is loading "etc/piVCCU/post-start.sh" at startup ?

i put it in init.d but after reboot the usb devices (cul cux device) are hidden.
i must detach the cul and attach again and strart the script to see the cul in cux.
is it possible to automate this ?

thx 
easy

**Comment by real-easy** [comment]
hier noch ergänzend was ich zusätzlich noch rausgefunden habe.

der cul-stick möchte nach dem neustart des PI nochmal ab und angesteckt werden, damit er funktioniert.
anschließend muss man dann die post-start.sh nochmals ausführen.

also scheint das ganze im init.d doch zu funzen, allerdings ist der cul noch nicht richtig bereit.
ähnliches hatte ich bei yahm auch schon. allerdings hatte es da dann gereicht den stick ab und an zu stecken.

gut wäre es wenn es einfach so geht, nach dem power on.

(hab übrigens selbstbau cul´s mit 1.66 firmware)

schönes we
easy

**Comment by alexreinert** [comment]
Die post-start.sh darf nicht in init.d eingebunden werden. Diese wird von piVCCU automatisch nach dem Start des Containers ausgeführt (sofern sie denn vorhanden und executable ist).

Im init.d selber wäre das vermutlich auch zu früh, weil der Container dafür schon gestartet sein sollte.

Ich habe hier keinen CUL, aber zwei andere USB Geräte und bei denen funktioniert das exakt so, wie beschrieben. Also post-start.sh anlegen und entsprechenden pivccu-device Aufruf reinmachen.

**Comment by real-easy** [comment]
ok danke für die info, klingt ja auch irgendwie logischer....

mein problem ist wohl wirklich der cul oder der PI3.
nach einem neustart ist der cul nicht in der liste der devices.
erst nachdem ich ihn ab und wieder angesteckt habe taucht er dort auf.

bis vor einem halben jahr hatte ich nur PI2 im einsatz, dort hatte ich das problem nicht.
der cul war der selbe und wurde nicht aktualisiert.

so.. habs nebenbei noch gefunden.

es scheint ein problem mit dem FTDI chip des cul´s zu sein.
der PI2 war da wohl gädiger als der PI3.

hier gibts eine lösung..
https://forum.pimatic.org/topic/3063/solved-usb-loss-after-raspberry-pi-3-restart/5

ich habe auf die schnelle mal einen cul mit einem CH340 chip angesteckt.
und siehe da es läuft ohne probleme.

nun muss ich also nur meine cul´s umbauen.

danke für die hilfe.

**Comment by alexreinert** [comment]
Der FDTI als solches funktioniert bei mir einwandfrei, allerdings nicht auf Arduino Basis.
So wie ich es aus der verlinkten Diskussion verstanden habe, reicht es, zwei Pins vom Chip zu verlöten, was bei einigen Clons nicht gemacht wurde, steht auch etwas ausführlicher hier https://ketturi.kapsi.fi/2014/04/how-to-fix-moody-arduino-nano/

**Comment by real-easy** [comment]
ja die seite hatte ich auch gesehen, die andere aber zuvor derher der fairness halber der andere link.

so, der erste test mit einem richtigen (clon) FTDI arduino mit gebrückten pins war nun auch erfolgreich.
also alles läuft wie es soll.
(es ist immer wieder beeindrucken wie es die chinesen das hin bekommen die eigentliche funktion bei ihrer clonerei von artikeln auszubauen.)

super projekt, derzeit wohl das einzigste welches von NULL auf 100 sofort problemlos funzt wenn es um CCU auf dem PI3 geht.

weiter so...
