### ISSUE TITLE
RockPro64 dkms

### ISSUE THREAD

**Issue by Pocky2507** [alexreinert/piVCCU#282]
Moin
Mit Armbian 5.7.15 lassen sich die Kernelmodule nicht bauen.
Ist da etwas bekannt?

**Comment by Pocky2507** [comment]
Danke für NICHTS

**Comment by alexreinert** [comment]
Sorry, der Issue ist mir durchgerutscht. Aber anstatt dann nochmal nachzufragen wird rumgestänkert. Schön, dass man dafür seine Freizeit opfert und das ganze kostenlos weitergibt.
Abgesehen davon, Detailsinfos wären sinnvoll gewesen um was sagen zu können.

**Comment by Pocky2507** [comment]
Es war nicht meine Absicht rumzustänkern.
Ich würdige Deine Arbeit und Du machst einen tollen Job.
Nimm es mir nicht krumm.
Entschuldigung
