### ISSUE TITLE
Anlernen des geflashten HMIP-HAP an die piVCCU3 klappt nicht.

### ISSUE THREAD

**Issue by volkergbenner** [alexreinert/piVCCU#287]
Hallo, erstmal vielen Dank für die tolle Arbeit und die schnelle Umsetzung des letzten FW-Updates.
Das Ändern der Firmware auf dem HMIP-HAP klappt ganz normal über das WebUI der piVCCU. Der SystemLeuchtKnopf des HAP leuchtet türkis und wird von der CCU nicht mehr als HAP erkannt. 
Er läßt sich aber nicht anlernen.

Haben das Problem noch andere? Ich lese nur , dass es Probleme beim Flashen gibt, aber das funzt ja bei mir.

Gruß
Volker

**Comment by alexreinert** [comment]
Was liefert pivccu-info?

**Comment by volkergbenner** [comment]
`piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Board serial:  MEQ0xxxxxx
 Radio MAC:     0x3D1xxx
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7D3C9xxxxxxxxx
 Radio MAC:     0xB93xxx
State:          RUNNING
PID:            715
IP:             192.168.2.109
CPU use:        1513.67 seconds
Link:           vethpivccu
 TX bytes:      24.55 MiB
 RX bytes:      27.29 MiB
 Total bytes:   51.84 MiB
`

**Comment by alexreinert** [comment]
Das HM-MOD-RPI-PCB wurde bisher von eQ-3 leider nicht mit einer passenden Firmware bedacht, welche die notwendigen Kryptofunktionen bereitstellt. Im Moment kann leider nur das RPI-RF-MOD dafür genutzt werden.

**Comment by volkergbenner** [comment]
Aber nach dem Anmelden des HAP an der CCU arbeitet der HAP dann als LAN-Gateway ? Empfinde ich sehr verwirrend, dass der HAP erst über Funk angemeldet werden muss, um dann über LAN mit der CCU zu kommunizieren.

**Comment by alexreinert** [comment]
Die Anmeldung und später auch die Kommunikation mit dem HAP läuft nicht per Funk, es werden aber Kryptofunktionen des RPI-RF-MOD benötigt.

**Comment by volkergbenner** [comment]
RPI-RF-MOD ist bestellt.
