### ISSUE TITLE
HMRF/HMIP hardware was not detected with ttyUSB0

### ISSUE THREAD

**Issue by frank-f** [alexreinert/piVCCU#288]
Hi!

I have a HM-MOD-UART board attached to a CP2102 USB module. The general communication works:

```
root@lxc:~# pivccu-attach /bin/eq3configcmd update-coprocessor -p /dev/ttyUSB0 -c -v
2020/09/24 23:19:14.910 <Info> Version: 2.8.6

root@lxc:~# pivccu-attach /bin/eq3configcmd update-coprocessor -p /dev/ttyUSB0 -c -se
2020/09/24 23:19:18.881 <Info> SerialNumber: QEQ0410xxx
root@lxc:~#
```

Unfortunately piVCCU does not seem to like this setup:

```
root@lxc:~# pivccu-info
piVCCU version: 3.51.6-41
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          RUNNING
PID:            979
IP:             192.168.0.30
CPU use:        16.58 seconds
Link:           vethpivccu
 TX bytes:      57.35 KiB
 RX bytes:      326.53 KiB
 Total bytes:   383.88 KiB
root@lxc:~#
```

Accordingly piVCCU does not work:

```
-- Logs begin at Thu 2019-02-14 11:11:59 CET, end at Thu 2020-09-24 23:17:01 CEST. --
Sep 24 23:14:03 lxc.home systemd[1]: Starting piVCCU...
Sep 24 23:14:31 lxc.home piVCCU3[790]: HMRF hardware was not detected
Sep 24 23:14:31 lxc.home start_container.sh[647]: <12>Sep 24 23:14:31 piVCCU3: HMRF hardware was not detected
Sep 24 23:14:31 lxc.home piVCCU3[791]: HMIP hardware was not detected
Sep 24 23:14:31 lxc.home start_container.sh[647]: <12>Sep 24 23:14:31 piVCCU3: HMIP hardware was not detected
Sep 24 23:14:31 lxc.home start_container.sh[647]: kernel.sched_rt_runtime_us = -1
Sep 24 23:14:32 lxc.home systemd[1]: Started piVCCU.
```

I have tried running dpkg-reconfigure pivccu. I select "HM-MOD-RPI-PCB or RPI-RF-MOD" and then "/dev/ttyUSB0" (which is the only option), but piVCCU still does not start.

Is my setup (using the CP2102 adapter) not supported?

**Comment by alexreinert** [comment]
You can see the supported hardware in the Readme. A generic CP210x adapter is not supported and will not be supported as there are special timing requirements which cannot be achived this the normal linux TTY kernel modules.

**Comment by frank-f** [comment]
I am confused. Your HB-RF-USB-2 uses a CP2102(N) as well. Where's the difference to a generic CP2102 adapter?

**Comment by alexreinert** [comment]
It is flashed differentially and uses special kernel modules.

**Comment by frank-f** [comment]
Ah, and I presume that firmware is not open source by chance?

**Comment by alexreinert** [comment]
It is, but you need a CP2102N and the same schematic as the HB-RF-USB-2. And the USB ID is only allowed to be used with the HB-RF-USB-2, so you need your own USB ID and have to patch the kernel modules for that USB ID.

**Comment by frank-f** [comment]
That sounds like a lot more effort than I thought. Thank you for the answers!
