### ISSUE TITLE
Iobroker nicht mehr erreichbar

### ISSUE THREAD

**Issue by Semesch** [alexreinert/piVCCU#290]
Hallo, ich komme leider nicht mehr weiter, mir fehlt hier einfach das Know-how.
Nach einem Stromausfall startet iobroker nicht mehr. Homematic startet problemlos. Ich bekomme auch keinen Zugriff mehr auf Iobroker per SSH.
In der fritzbox finde ich aber beide IP-Adressen als online.

Gruß Semesch

**Comment by alexreinert** [comment]
Dann wäre es sinnvoll nicht hier nachzufragen, sondern im ioBroker Forum.

**Comment by Semesch** [comment]
OK, danke, dachte nur weil es deine pivccu ist, kannst du mir vll helfen. Schönen Abend.

**Comment by alexreinert** [comment]
Wieso meine piVCCU? piVCCU ist einfach nur eine Software, welche an auf Raspbian oder Armbian installieren kann und kein komplettes Betriebssystem. Mit ioBroker hat es dann erstmal gar nichts zu tun, außer das beide Systeme gut zusammenarbeiten und sich gut ergänzen.
