### ISSUE TITLE
Minimal resource footprint installation?

### ISSUE THREAD

**Issue by frank-f** [alexreinert/piVCCU#291]
Hi!

I used to run a setup with OpenHAB and Homegear. Since OH is a resource hog, I was pleased that Homegear's resource footprint is rather small. Now I need to add HMIP devices to my home which Homegear does not support natively.

I installed piVCCU3 (to replace HG) which is working well so far, but I also notice it starts quite a few processes. Are all of those really needed, if I'm using OH for the daily business? Or can some of those be started on demand (by me) if say I want to perform a backup?

**Comment by alexreinert** [comment]
These are all the services of a original CCU. Some of them are not really required in all cases, but as one of the piVCCU goal is, to emulate the CCU as much as possible, there is no official way to disable them.

**Comment by frank-f** [comment]
I understand your effort to create an as close as possible clone, but can you maybe provide a short description which service does what, so I can try to figure out myself which ones I may not need in my setup?

I see the following processes:
/bin/eq3-uds-services
/bin/eq3configd
/bin/hss_led
/bin/multimacd
/bin/ReGaHss.community
/bin/rfd
/usr/sbin/lighttpd-angel and /usr/sbin/lighttpd - already figured out that I need this for API access
/opt/HMServer/HMIPServer.jar - the main program, I assume?

**Comment by alexreinert** [comment]
It is not only just a short description, if you deactivate some of the services, you have to change config files and startup files, too. Writing down all of the dependencies between the services and the config files would take hours, if I describe that in a way, that a beginner understands that. I have to say sorry, but this is nothing I can provide you right now.

**Comment by alexreinert** [comment]
Any questions left?

**Comment by frank-f** [comment]
Yes
