### ISSUE TITLE
HMIP-RFUSB: Inoperable after upgrade from 3.51.6-41 to 3.53.30-47

### ISSUE THREAD

**Issue by sbyx** [alexreinert/piVCCU#292]
Hey guys, I'm running pivccu3 for a while on my Pi4 with Ubuntu 20.04 (aarch64). Thanks a lot for the great effort.

However when upgrading to the latest stable version (3.53.30-47) the CCU3 boots up in an inoperable state and no devices are visible. I'm getting error messages about VirtualDevices, BidCos-RF and HMIP-RF being not available and I am not seeing any of my paired devices. This is fixed simply by downgrading (just pivccu3 package) to 3.51.6-41 but upgrading again gets me in the same error situation. I am running with HMIP-RFUSB only.

```
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  FAKE_HMRF
 Connected via:  (/dev/)
 Board serial:  FKE1023235
 Radio MAC:     0xeef52a
HMIP Hardware:  HMIP-RFUSB
 SGTIN:         ****
 Radio MAC:     0x****
State:          RUNNING
PID:            26124
IP:             192.168.178.11
IP:             2003:****
CPU use:        4.76 seconds
BlkIO use:      56.00 KiB
Link:           vethpivccu
 TX bytes:      1.02 MiB
 RX bytes:      561.81 KiB
 Total bytes:   1.57 MiB
```

Would be happy to get this working with the latest pivccu3 version again. Do you have any pointers for me on what I could try?

**Comment by jens-maus** [comment]
As RaspberryMatic seem to suffer from similar issues with using a HmIP-RFUSB with 3.53.x (https://github.com/jens-maus/RaspberryMatic/issues/372) my guess is that this is a probably a general issue with the 3.53.x version of the HMIPServer, thus eQ3 being responsible for these type of issues.

**Comment by sbyx** [comment]
Thanks for the quick reply. I guess I will wait for the next CCU3 release and pi CCU3 adaptation then and see if it makes a difference. Let's hope support for hmip-rfusb has not been dropped otherwise I guess I need to get a
HM-MOD-RPI-PCB or something.

**Comment by jh2k19** [comment]
Habe die gleichen Probleme wie sbyx oben beschreibt.

Ich verwende allerdings die HM-MOD-RPI-PCB.

RPC-Adapter hat keine Verbindung mehr zu der CCU.
In der CCU sind die einzelnen Geräte nicht mehr bedienbar bzw. haben keine Verbindung mehr.
Auch die Allgemeine Einstellungen in der CCU gehen nicht.
Es kommt auch eine Maske mit einer Fehlermelung bzgl. VirtualDevice.

Gibt es eine Möglichkeit des Downgrades auf 3.51.6 oder sonst eine Lösung


VG Jürgen

**Comment by alexreinert** [comment]
@jh2k19 Das HM-MOD-RPI-PCB macht mit dem neuen Release keine (allgemeinen) Probleme. Mach mal einen neuen Issue auf und gib dort bitte gleich die Ausgabe von `sudo pivccu-info` an.

**Comment by sbyx** [comment]
HMIP-RFUSB scheint mit 3.53.34-49 wieder wie gewohnt zu funktionieren.

**Comment by alexreinert** [comment]
Danke für die Rückmeldung, dann hat eQ-3 das scheinbar still und heimlich gefixt.
