### ISSUE TITLE
HM-ES-TX-WM, Fehler beim externen Zugriff auf verschiedene Endpoints

### ISSUE THREAD

**Issue by d3m0nxxl** [alexreinert/piVCCU#293]
Hallo zusammen,

Ich nutze pivccu3 3.53.30-47 und openhab 2.5.9 unter Raspbian auf einem 3b+.

Beim Zugriff über das homematic-binding von OH bekomme ich HM-ES-TX-WM nicht zum laufen, der Fehler ist auch bei mindestens einem anderen Nutzer bekannt.

Nach Diskussionen in
https://community.openhab.org/t/homematic-hm-es-tx-wm-not-working-properly/105421/12

kam der Verdacht, dass die Ursache in pivccu liegen könnte. Mit homegear soll es mit dem LED-Sensor (s.u.) funktionieren.
Beim Discovery wird werden für das HM-ES-TX-WM Entpoints, wie z.B. GAS_POWER oder GAS_ENERGY_COUNTER zurückgegeben, der Zugriff darauf schlägt aber fehl.

Im CCU-Log sieht das dann wie folgt aus:
```
Oct  3 13:37:32 ccu3-webui user.err rfd: HSSParameter::GetValue() id=GAS_ENERGY_COUNTER failed getting physical value.
Oct  3 13:37:32 ccu3-webui user.err rfd: HSSParameter::GetValue() id=GAS_POWER failed getting physical value.
Oct  3 13:39:26 ccu3-webui user.err rfd: HSSParameter::GetValue() id=GAS_ENERGY_COUNTER failed getting physical value.
Oct  3 13:39:26 ccu3-webui user.err rfd: HSSParameter::GetValue() id=GAS_POWER failed getting physical value.
Oct  3 13:39:27 ccu3-webui user.err rfd: HSSParameter::GetValue() id=IEC_ENERGY_COUNTER failed getting physical value.
Oct  3 13:39:27 ccu3-webui user.err rfd: HSSParameter::GetValue() id=IEC_POWER failed getting physical value.
```

An das HM-ES-TX-WM können verschiedene Sensoren angeschlossen werden, u.a. ein Gas Meter Sensor und ein LED-Sensor für Stromzähler. das HM-ES-TX-WM erkennt die Sensoren selbstständig beim Booten und legt dann die entsprechenden Endpoints fest. D.h. sie sind anscheinend je nach Konfiguration unterschiedlich und nicht fix.

Ich habe den LED-Sensor, d.h. die Endpoints für GAS_POWER und GAS_ENERGY_POWER existieren bei mir nicht. Vielleicht ist das das Problem?

**Comment by d3m0nxxl** [comment]
Ich habe mir nun einen Gas-Sensor besorgt und das scheint meine Vermutung zu bestätigen.
Schließt man den Gas-Sensor an, existieren die Endpoints und alles funktioniert wie gewohnt.
Die Frage ist, liegt es am pivccu3 oder kommt der Fehler auch bei der Original CCU3? Leider habe ich keine CCU3, um das zu testen...

**Comment by d3m0nxxl** [comment]
Kleines Update:
Ich habe nun ein Firmware-Update des HM-ES-TX-WM von 1.0 auf 1.2 durchgeführt.
Nach dem Update erscheinen nun plötzlich beim Status weitere Parameter:

![grafik](https://user-images.githubusercontent.com/72307488/95425161-251cc280-0944-11eb-9abb-6fe941d27d28.png)

Das führt leider dazu, dass die CCU nun wieder Probleme mit nicht vorhandenen Endpoints:

OH:
```
2020-10-08 08:46:37.690 [hingStatusInfoChangedEvent] - 'homematic:HM-ES-TX-WM:PEQXXXXXXX:REQXXXXXXX' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): -1 Failure (sending <?xml version="1.0" encoding="ISO-8859-1"?>
<methodCall><methodName>getValue</methodName>
<params><param><value>REQXXXXXXX:1</value></param><param><value>POWER</value></param></params></methodCall>)
```

CCU:
`Oct  8 08:47:21 ccu3-webui user.err rfd: HSSParameter::GetValue() id=POWER failed getting physical value.`

Leider finde ich nirgends eine Original FW Version 1.0 zum Download, so dass das Device für mich nun unbrauchbar geworden ist. :-(

**Comment by alexreinert** [comment]
Das dürfte kein piVCCU3 spezifisches Thema sein, da hier nur Software Komponenten im Spiel sind, welche 1:1 so auf der der Original CCU3 laufen. Es würde Sinn machen, mit dem Thema auch im Homematic Forum aufzuschlagen.
Ich persönlich habe leider keine passenden Testgeräte um das näher zu untersuchen.

**Comment by d3m0nxxl** [comment]
Hi @alexreinert,

ich habe nun meine alte CCU2 (ich habe leider keine CCU3...) herausgekramt: Da funktioniert das Gerät mit beiden Sensoren problemlos.

Wenn ich es richtig sehe, gibt es dann ja anscheinend nur zwei Möglichkeiten:
1. Es ist doch ein pivccu(2 und oder 3?)-spezifisches Problem
2. Es ist ein CCU3-spezifisches Problem

Gibt es einen Weg, wie ich helfen kann, um das Problem zu identifizieren oder näher einzugrenzen?
Schön wäre es ja, wenn man zumindest 1. ausschließen könnte. Dann würde ich das an das Homematic-Forum weitergeben und hoffe, dass es da eine Lösung gibt.

Viele Grüße
Thorsten

**Comment by alexreinert** [comment]
Welche Firmware Version hattest du auf deiner CCU2? Ich will mal nicht außschließen, dass das Problem mit der Unterstützung der 2.x Firmware des HM-ES-TX-WM reinkam.

**Comment by d3m0nxxl** [comment]
Auf der CCU2 die 2.53.27, auf den beiden HM-ES-TX-WM jeweils die 1.2 (>2.x geht ja nur bei den IEC-Zählern).

**Comment by martinschaller** [comment]
Habe hier das gleiche Problem mit HM-ES-TX-WM. Hatte funktioniert und nach Update der FW versucht er auch Endpoints zu lesen die es nicht gibt.
Gibt es mittlerweile eine Lösung / Workaround?

**Comment by d3m0nxxl** [comment]
@alexreinert : Hast du denn eine Idee, wo der Fehler liegen könnte?

**Comment by alexreinert** [comment]
Ich habe absolut keine Idee, wo der Fehler liegen kann, aber wie gesagt, das ist irgendwo in den Internas vom RFD zu suchen und der ist leider Closed Source. Selbst wenn ich ein Testgerät hätte, könnte ich also nur sehr eingeschränkt nach einer Lösung suchen.

**Comment by martinschaller** [comment]
Hat zufällig jemand noch die Firmware <1.1 für ein Downgrade?

**Comment by d3m0nxxl** [comment]
Ich leider nicht, ich hab nur die 1.2er. Online bin ich nicht fündig geworden. Gibt es eine Möglichkeit die Firmwares von den Geräten auszulesen (falls jemand noch eine alte auf einem Gerät hat...)?
Ich hab mich jetzt damit beholfen, parallel zu meiner pivccu3 noch eine alte CCU2 für die beiden HM-ES-TX-WM einzusetzen. Extrem nervig aber zurzeit für mich die einzige Lösung... :-)

**Comment by d3m0nxxl** [comment]
> [...] Selbst wenn ich ein Testgerät hätte [...]

Also das würde man ja noch hinbekommen, könnte dir eins testweise zukommen lassen... ;-)

**Comment by martinschaller** [comment]
> Ich hab mich jetzt damit beholfen, parallel zu meiner pivccu3 noch eine alte CCU2 für die beiden HM-ES-TX-WM einzusetzen. Extrem nervig aber zurzeit für mich die einzige Lösung... :-)

Hab es über einen anderen Workaround zum Laufen bekommen ohne eine zusätzlichen CCU2 verwenden zu müssen: Bediene mich dabei einer Systemvariable in pivccu3, die automatisch mit dem aktuellen Wert des HM-ES-TX-WM aktualisiert wird. Diese Systemvariable lese ich dann in Openhab aus.

**Comment by d3m0nxxl** [comment]
> 
> 
> > Ich hab mich jetzt damit beholfen, parallel zu meiner pivccu3 noch eine alte CCU2 für die beiden HM-ES-TX-WM einzusetzen. Extrem nervig aber zurzeit für mich die einzige Lösung... :-)
> 
> Hab es über einen anderen Workaround zum Laufen bekommen ohne eine zusätzlichen CCU2 verwenden zu müssen: Bediene mich dabei der Systemvariablen in pivccu3, die automatisch mit dem aktuellen Wert des HM-ES-TX-WM aktualisiert wird. Diese Systemvariable lese ich dann in Openhab aus.

Das hört sich interessant an! Kannst du das näher beschreiben?
