### ISSUE TITLE
dpkg Error beim Installieren von piVCCU3 auf OpenHABian

### ISSUE THREAD

**Issue by massenmensch** [alexreinert/piVCCU#295]
Hallo,

ich versuche gerade strikt nach Anleitung piVCCU3 unter OpenHABian auf meinem Pi 3B+ zu installieren, scheitere jedoch immer in Schritt 10. wenn ich den CCU Container installiere. Es wird folgender Fehler gelogt, mit dem ich leider gar nichts anfangen kann: 

```pivccu3 (3.53.30-47) wird eingerichtet ...
dpkg: Fehler beim Bearbeiten des Paketes pivccu3 (--configure):
 »installiertes pivccu3-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 255 zurück
Fehler traten auf beim Bearbeiten von:
 pivccu3
```

Ich freue mich über jegliche Hilfe.

**Comment by alexreinert** [comment]
Nur mit der Fehlermeldung kann man leider nichts anfangen, man bräuchte die die gesamten Ausgaben von dem Schritt um mehr sagen zu können.

**Comment by massenmensch** [comment]
Hallo Alex, danke für deine Antwort, nachdem ich ein piVCCU3 Image aufgespielt hatte und dann openHAB per apt nachträglich aufgespielt habe klappt jetzt alles ohne Probleme.

Danke trotzdem!
