### ISSUE TITLE
Installatin einer bestimten Version von pivccu

### ISSUE THREAD

**Issue by jh2k19** [alexreinert/piVCCU#296]
Hallo Alex,
gibt es eine Mölichkeit eine bestimmte Version z.B. 3.51.6 zu installieren 
oder von der 3.41.11 upzudaten?

Bei "sudo apt install pivccu3=3.51.6-36" kommt nur:
 
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '3.51.6-36' for 'pivccu3' was not found

VG Jürgen

**Comment by alexreinert** [comment]
`sudo apt-cache madison pivccu3` liefert alle verfügbaren Version, `sudo apt install pivccu3=VERSION` installiert die entsprechende Version.
Es sei aber gleich gesagt: Ich supporte und teste nur die jeweils aktuelle Version, es kann gut sein, dass die alten Versionen nicht mehr 100% funktionieren mit aktuellen Kernel Modulen und/oder Raspbian Versionen.

**Comment by jh2k19** [comment]
Super, hat funktioniert.
Vielen Dank.
