### ISSUE TITLE
Nach einem Neustart Startet PIVCCU nicht automatisch

### ISSUE THREAD

**Issue by Peter1980FFM** [alexreinert/piVCCU#297]
Hallo Alex,
immer wenn ich meinen Raspi neu Starten muss, muss ich manuell
sudo systemctl start pivccu eingeben, damit die CCU wieder hoch kommt....
Das Modul ist über die USB Platine angeschlossen.
sudo apt install --reinstall pivccu3 pivccu-modules-raspberrypi pivccu-modules-dkms
habe ich ohne erfolg schon Probiert
nach der Eingabe vonsudo systemctl start pivccu:
● pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: e
   Active: active (running) since Sun 2020-10-11 15:11:32 CEST; 3min 55s ago
  Process: 6762 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, stat
 Main PID: 8000 (lxc-start)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/pivccu.service
           └─8000 /usr/bin/lxc-start --lxcpath /var/lib/piVCCU3 --name lxc --pid

Okt 11 15:10:23 io-conbee-homematic systemd[1]: Starting piVCCU...
Okt 11 15:11:30 io-conbee-homematic piVCCU3[7829]: HMIP hardware was not detecte
Okt 11 15:11:30 io-conbee-homematic start_container.sh[6762]: <12>Oct 11 15:11:3
Okt 11 15:11:32 io-conbee-homematic start_container.sh[6762]: kernel.sched_rt_ru
Okt 11 15:11:32 io-conbee-homematic systemd[1]: Started piVCCU.

Eine IDEE?

**Comment by Peter1980FFM** [comment]
Ich habe jetzt mal
sudo dpkg-reconfigure pivccu3
dann das Modul ausgewählt und alle 4 Vorgeschlagenen USB Anschlüsse ausgewählt
Dann sieht das nun so vor dem Neustart aus:
● pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: e
   Active: active (running) since Sun 2020-10-11 15:29:48 CEST; 1min 53s ago
  Process: 27481 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, sta
 Main PID: 28352 (lxc-start)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/pivccu.service
           └─28352 /usr/bin/lxc-start --lxcpath /var/lib/piVCCU3 --name lxc --pi

Okt 11 15:29:11 io-conbee-homematic systemd[1]: Starting piVCCU...
Okt 11 15:29:48 io-conbee-homematic start_container.sh[27481]: kernel.sched_rt_r
Okt 11 15:29:48 io-conbee-homematic systemd[1]: Started piVCCU.
[](url)

Nach dem Neustart:
● pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-10-11 15:35:02 CEST; 26s ago
  Process: 671 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, status=0/SUCCESS)
 Main PID: 2264 (code=exited, status=1/FAILURE)

Okt 11 15:34:59 io-conbee-homematic piVCCU3[1954]: HMIP hardware was not detected
Okt 11 15:34:59 io-conbee-homematic start_container.sh[671]: <12>Oct 11 15:34:59 piVCCU3: HMIP hardware was not detected
Okt 11 15:35:01 io-conbee-homematic start_container.sh[671]: kernel.sched_rt_runtime_us = -1
Okt 11 15:35:01 io-conbee-homematic start_container.sh[671]: lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 842 Received container sta
Okt 11 15:35:01 io-conbee-homematic start_container.sh[671]: lxc-start: lxc: tools/lxc_start.c: main: 330 The container failed to start
Okt 11 15:35:01 io-conbee-homematic start_container.sh[671]: lxc-start: lxc: tools/lxc_start.c: main: 333 To get more details, run the container
Okt 11 15:35:01 io-conbee-homematic start_container.sh[671]: lxc-start: lxc: tools/lxc_start.c: main: 336 Additional information can be obtained
Okt 11 15:35:01 io-conbee-homematic systemd[1]: Started piVCCU.
Okt 11 15:35:02 io-conbee-homematic systemd[1]: pivccu.service: Main process exited, code=exited, status=1/FAILURE
Okt 11 15:35:02 io-conbee-homematic systemd[1]: pivccu.service: Failed with result 'exit-code'.
Nach Manuellen Starten
sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Board serial:  58A992F7E0
 Radio MAC:     0xFFF7E0
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A992F7E0
 Radio MAC:     0xB08B1F
State:          RUNNING
PID:            5400
IP:             192.168.122.27
CPU use:        2.34 seconds
BlkIO use:      23.81 MiB
Link:           vethpivccu
 TX bytes:      12.16 KiB
 RX bytes:      26.82 KiB

systemctl status pivccu.service
● pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: e
   Active: active (running) since Sun 2020-10-11 15:37:31 CEST; 44s ago
  Process: 4428 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, stat
 Main PID: 5387 (lxc-start)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/pivccu.service
           └─5387 /usr/bin/lxc-start --lxcpath /var/lib/piVCCU3 --name lxc --pid

Okt 11 15:36:41 io-conbee-homematic systemd[1]: Starting piVCCU...
Okt 11 15:37:31 io-conbee-homematic start_container.sh[4428]: kernel.sched_rt_ru
Okt 11 15:37:31 io-conbee-homematic systemd[1]: Started piVCCU.

**Comment by alexreinert** [comment]
Wie ist das Funkmodul an den Pi angschlossen? Welches OS läuft auf dem Pi?

**Comment by Peter1980FFM** [comment]
Die Platine ist auf deinen Neuen USB Adapter per Kabel am USB 2 Anschluss,
das Betriebssystem ist das neueste Rasperian Desktop was es gibt mit allen
Update



Alexander Reinert <notifications@github.com> schrieb am Mo., 12. Okt. 2020,
08:30:

**Comment by alexreinert** [comment]
Ist das Problem mit der aktuellen Version noch vorhanden?

**Comment by Peter1980FFM** [comment]
Guten Morgen,
nach dem ich im io Broker mein Script abgeschaltet hatte und alles übers
Terminal geupdatete habe scheint es nun zu Funktionieren.
Wo war das Problem?
Die CCU Brauch jetzt ein wenig Länger zum Starten habe ich das Gefühl
Gruß Peter


Alexander Reinert <notifications@github.com> schrieb am Mi., 9. Dez. 2020,
08:07:

**Comment by alexreinert** [comment]
Klingt gut, dass es jetzt klappt. In der Zeit sind einige Dinge passiert, u.A. das Update auf 3.53.34 und eine Optimierung der Erkennung des Funkmoduls. Was es jetzt genau war, kann ich aber nicht sagen.
