### ISSUE TITLE
Probleme mit CCU 3.53.30-47

### ISSUE THREAD

**Issue by jh2k19** [alexreinert/piVCCU#298]
Habe die gleichen Probleme wie von sbxy unter #292 HMIP-RFUSB: Inoperable after upgrade from 3.51.6-41 to 3.53.30-47  beschrieben.

Ich verwende allerdings die HM-MOD-RPI-PCB auf einem NanopiM4.

RPC-Adapter hat keine Verbindung mehr zu der CCU.
In der CCU sind die einzelnen Geräte nicht mehr bedienbar bzw. haben keine Verbindung mehr.
Auch die Allgemeine Einstellungen in der CCU gehen nicht.
Es kommt auch eine Maske mit einer Fehlermelung bzgl. VirtualDevice und HmIP-RF

Die Verbindung vom ioBroker über den hm-rpc Adapter (XML-RPC) geht auch nicht mehr. 
Im ioBroker Log kommt: (1979) init error: Error: Unknown XML-RPC tag 'TITLE'

Mit einem Downgrade auf 3.51.6-41 läft alles wieder.

root@nanopim4:~# sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Board serial:  PEQ0530673
 Radio MAC:     0x6A62D3
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7D8A99180F1
 Radio MAC:     0xBBE4CD
State:          RUNNING
PID:            1590
IP:             192.168.1.63
CPU use:        4.13 seconds
BlkIO use:      18.82 MiB
Memory use:     41.95 MiB
KMem use:       5.54 MiB
Link:           vethpivccu
 TX bytes:      345.97 KiB
 RX bytes:      101.74 KiB
 Total bytes:   447.72 KiB
root@nanopim4:~#

**Comment by alexreinert** [comment]
Wie ist der Inhalt der Datei /var/log/hmserver.log innerhalb des Container ca. 5-10 Minuten nach dem Start?

**Comment by jh2k19** [comment]
In diesem Verzeichnis habe ich leider auch nach längerer Wartezeit keine hmserver.log Datei.

**Comment by vigeland** [comment]
Das wird das Java Problem sein.
Siehe https://homematic-forum.de/forum/viewtopic.php?f=69&t=61372&start=20#p612756
Dann kommt nie das hmserver.log

**Comment by alexreinert** [comment]
Das dort beschriebene Java Problem ist bereits seit einiger Zeit gefixt.

**Comment by vigeland** [comment]
Hatte ich nur geschrieben, damit du den Punkt vielleicht schließen kannst.
