### ISSUE TITLE
rock64   Armbian 20.08.9 Buster KERNELRELEASE=5.8.13-rockchip64 ARCH=arm64 all..(bad exit status: 2)

### ISSUE THREAD

**Issue by v0r73x** [alexreinert/piVCCU#299]
Hallo Alex,

ich habe immernoch das Problem das ich, trotz genutzter testing Repo die dkms-module nicht installieren kann (siehe Screenshot). ich habe die richtigen source/header files und habe mehrmals die pakete gepurged sodass sie komplett sauber installieren müssten. Geht aber nicht ;( 

Hast Du eine Idee ? 

![image](https://user-images.githubusercontent.com/48632087/95733215-1571e680-0c82-11eb-93fe-eac0fe6b8f45.png)

**Comment by alexreinert** [comment]
Was stehe in der im Screenshot angegeben make.log?

**Comment by v0r73x** [comment]
Hi Alex,

folgende info lese ich da:

![image](https://user-images.githubusercontent.com/48632087/95734378-ae553180-0c83-11eb-9a28-bf55aa65fcb0.png)

**Comment by v0r73x** [comment]
Im Forum hatte das gleiche Problem mit einem rockpi4 - aber ich hab nicht ganz geblickt wo er welche Funktion gesetzt hat. 

![image](https://user-images.githubusercontent.com/48632087/95735041-99c56900-0c84-11eb-8cdf-5aac96bbc363.png)

**Comment by alexreinert** [comment]
Das scheint ein Armbian Problem mit Buster zu sein. Die gesetzten Kernel Config Parameter passen nicht zum verfügbaren GCC Compiler unter Buster. Das trifft nicht nur die piVCCU Kernel Module, sondern z.B. auch die ZFS Kernel Module.

**Comment by v0r73x** [comment]
Kannst Du eine andere Armbian Distri empfehlen die gehen sollte? Ich muss eh gerade from scratch aufsetzen aber würde das schon gerne mit dem rock64 umsetzen wegen der emmc (bzgl. schreibzyklen etc.) das ARMBIAN 5.67 user-built Debian GNU/Linux 9 (stretch) 4.19.0-rockchip64 funktioniert ja im prinzip aber ist halt schon sehr "alt". Daher würde ich gern ein neues erstellen und dachte ich nehme gleich mal das neueste Armbian bit 13er Kerlensource & Header :( 

p.s. kannst Du Dir ein Reim darauf machen wo Vigeland den code eingesetzt hat ? Wenn es dann trotz quick6dirty läuft wäre mir das erstmal genug ;) 
gruß aus Berlin,

Robert

**Comment by v0r73x** [comment]
p.s. ich habe es jetzt die pivccu3 auf dem rock64 mit kernel Armbian 20.08.10 Buster with Linux 5.8.14-rockchip64 zum laufen bekommen. ganz grosses Dankeschön an vigeland der mir hier mit rat & tat zur Seite stand.

wenn interesse an einem aktuellen img für den rock64 besteht teile ich es gern ;) 

vorraussetzung: rock64 mit HM-MOD-RPI-PCB & 64gb emmc
