### ISSUE TITLE
ccu3-webui bzw. IP-Adresse nicht mehr erreichbar

### ISSUE THREAD

**Issue by thorstenheinz** [alexreinert/piVCCU#302]
Hallo Alex,
kurz was ich vorhabe: RPI 3 mit pivccu3 in den Keller und Deine  HB-RF-ETH + Funkplatine an zentraler Stelle anbringen. HB-RF-ETH ist fertig und funktioniert, wie beschrieben.
Nun habe ich den RPI3 wie in den Anleitungen beschrieben aufgesetzt und gestartet.
Es gibt wie beschrieben die beiden IP-Adressen und die zwei Namen: ccu3-webui und raspberry (habe ich auf ccu3-rpi3 umbenannt).
Beim ersten Starten erreiche ich die webui und auch die ccu3-rpi per putty. Bei der Webui habe ich mich als admin angemeldet und die Express Installation ausgewählt. Danach bin ich auf die Startseite der Homematic Zentrale gekommen. Ich habe mich abgemeldet und das Fenster geschlossen. Ich habe kein Backup der CCU2 Zentale (von eq3) eingespielt!
Danach habe ich per Putty den Befehl: sudo apt update && sudo apt upgrade ausgeführt.
Hat eine ganze Weile gedauert und ich habe auch das Y gedrückt.

Nach Fertigstellung wie beschrieben, erneut die webui aufrufen wollen, diese antwortet aber nicht mehr. Per putty erreiche ich aber ccu3-rpi3. Der IP Scanner zeigt keine webui und/oder IP-Adresse mehr an.

Dies habe ich nun schon zweimal gemacht und jedesmal das Gleiche. Ich komme nicht mehr auf die CCU3 drauf.

Wo liegt der Fehler?
Leider bin ich nicht der Linux Spezialist und auch kein Coder. Ich mache alles nach Anleitung, kann mir aber keinen Fehler erklären.

Vielen Dank für Deine Hilfe!

Gruß
Thorsten

**Comment by alexreinert** [comment]
Was liefert `sudo pivccu-info`?

**Comment by thorstenheinz** [comment]
Last login: Thu Oct 15 20:45:32 2020 from 192.168.133.41
pi@ccu3-rpi3:~ $ sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins

**Comment by alexreinert** [comment]
Wie sieht das ganze aus nach dem Befehl `sudo systemctl start pivccu`?

**Comment by alexreinert** [comment]
Ist aktuell ein Funkmodul angeschlossen? Oder ist das nur auf der HB-RF-ETH vorhanden? Ist das Paket für die HB-RF-ETH installiert auf dem Pi? Kann man vom Pi aus die HB-RF-ETH anpingen?

**Comment by thorstenheinz** [comment]
Befehl abgesetzt, keine Änderung. 
Funkmodul ist nur auf dem HB-RF-ETH vorhanden. Das Paket habe ich nicht installiert. Da habe ich wohl was übersehen, bzw. das nicht gefunden,
Ping:
pi@ccu3-rpi3:~ $ ping 192.168.133.54
PING 192.168.133.54 (192.168.133.54) 56(84) bytes of data.
64 bytes from 192.168.133.54: icmp_seq=1 ttl=255 time=1.17 ms
64 bytes from 192.168.133.54: icmp_seq=2 ttl=255 time=0.509 ms
64 bytes from 192.168.133.54: icmp_seq=3 ttl=255 time=0.460 ms
64 bytes from 192.168.133.54: icmp_seq=4 ttl=255 time=0.518 ms
64 bytes from 192.168.133.54: icmp_seq=5 ttl=255 time=0.444 ms
64 bytes from 192.168.133.54: icmp_seq=6 ttl=255 time=0.507 ms
64 bytes from 192.168.133.54: icmp_seq=7 ttl=255 time=0.608 ms
64 bytes from 192.168.133.54: icmp_seq=8 ttl=255 time=0.444 ms
64 bytes from 192.168.133.54: icmp_seq=9 ttl=255 time=0.444 ms
64 bytes from 192.168.133.54: icmp_seq=10 ttl=255 time=0.536 ms
64 bytes from 192.168.133.54: icmp_seq=11 ttl=255 time=0.449 ms
64 bytes from 192.168.133.54: icmp_seq=12 ttl=255 time=0.442 ms
64 bytes from 192.168.133.54: icmp_seq=13 ttl=255 time=0.489 ms
^C
--- 192.168.133.54 ping statistics ---
13 packets transmitted, 13 received, 0% packet loss, time 455ms
rtt min/avg/max/mdev = 0.442/0.539/1.165/0.188 ms

**Comment by thorstenheinz** [comment]
Paket installiert
nochmal den o. g. Befehl abgesetzt
jetzt schaut es so aus:
pi@ccu3-rpi3:~ $ sudo systemctl start pivccu
pi@ccu3-rpi3:~ $ sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Board serial:  5A4993F4CD
 Radio MAC:     0xFFF4CD
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F5A4993F4CD
 Radio MAC:     0x1E99B4
State:          RUNNING
PID:            1664
CPU use:        1.77 seconds
Link:           vethpivccu
 TX bytes:      726 bytes
 RX bytes:      10.12 KiB
 Total bytes:   10.82 KiB

**Comment by alexreinert** [comment]
Gut, dann dürfte es das erklären, ohne Funkmodul kann es schnell man zu einem Timeout beim Starten kommen.
Damit das HB-RF-ETH genutzt werden kann, muss man es mit einer festen IP versorgen (entweder statisch in der Weboberfläche der HB-RF-ETH konfiguriert oder per fixer DHCP Zuweisung im Router) und auf die aktuellste Firmware bringen.
Danach muss auf dem Pi mit apt das Paket hb-rf-eth installiert werden und piVCCU danach neu gestartet werden.

**Comment by alexreinert** [comment]
Wie lange hast du zwischen dem Start und dem neuen pivccu-info Aufruf gewartet? Bis der Container komplett gestartet ist und auch eine IP bekommen hat, dauert es schon ein paar Sekunden bis Minuten.
Auf jeden Fall wird der Container jetzt schonmal gestartet und auch das Funkmodul wurde gefunden.

**Comment by thorstenheinz** [comment]
jetzt schaut es gut aus!!!
WebUI ist wieder da!! Und ich kann auf die Zentrale zugreifen.

Paket habe ich installiert. Und die Firmware ist 1.2.3

Vielen herzlichen Dank!!!

**Comment by thorstenheinz** [comment]
Jetzt ist leider schon wieder Schluß.

Ich habe der HB-RF-ETH eine feste IP vergeben, dann beide Geräte Stromlos gemacht. Erst die HB-RF-ETH angesteckt, nach 20 sek den PI. 
Nun gehts wieder nicht mehr:

pi@ccu3-rpi3:~ $ sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
/var/lib/piVCCU3/detect_hardware.inc: line 65: echo: write error: Connection timed out
/var/lib/piVCCU3/detect_hardware.inc: line 65: echo: write error: Connection timed out
/var/lib/piVCCU3/detect_hardware.inc: line 65: echo: write error: Connection timed out
/var/lib/piVCCU3/detect_hardware.inc: line 65: echo: write error: Connection timed out
/var/lib/piVCCU3/detect_hardware.inc: line 65: echo: write error: Connection timed out

**Comment by alexreinert** [comment]
Wenn du die IP änderst, musst du die Netzwerkerkennung vom Paket hb-rf-eth neu ausführen:
`sudo dpkg-reconfigure hb-rf-eth` und danach neu starten.

**Comment by thorstenheinz** [comment]
OK, das wars!
Danke nochmal!
