### ISSUE TITLE
Feature - WebUI add RSSI column in DeviceOverview

### ISSUE THREAD

**Issue by MalteHillmann** [alexreinert/piVCCU#303]
Hello, 

is it possible to implement the [RSSI row from RaspberryMatic](https://github.com/jens-maus/RaspberryMatic/pull/373) in piVCCU, too?
I'm loving piVCCU because it runs much faster than RM, but I miss this feature from RM.

Kind regards
Malte

**Comment by alexreinert** [comment]
One important goal of piVCCU is to be as compatibel to the original CCU as possible. The downside of this is, that such features are only get included, when they will be implemented in the original CCU firmware.
