### ISSUE TITLE
Geräte temporär inaktiv setzen

### ISSUE THREAD

**Issue by bs0001** [alexreinert/piVCCU#304]
Hallo,

es wäre prima, wenn man Geräte temporär auf inaktiv setzen könnte, damit diese in dem Zeitraum keine Servicemeldungen von sich geben. 
In Raspberrymatic scheint dies bereits implementiert worden zu sein. 
https://technikkram.net/blog/2018/11/13/raspberrymatic-neue-funktion-zum-verhindern-von-servicemeldungen-fuer-inaktive-geraete/

Viele Grüße 
Bernd

**Comment by alexreinert** [comment]
Es wäre schön, wenn dieses Feature in der CCU3 mal richtig implementiert werden würde, auch in RaspberryMatic ist es nur halbherzig umgesetzt, weil da die Meldungen in der WebUI ausgeblendet werden, aber das RPI-RF-MOD dennoch blinkt.

Ein klares Ziel von piVCCU ist aber, eine möglichst hohe Kompatibilität zur CCU3 zu bieten, d.h. aber im Gegenzug dann auch, dass solche Anpassungen nur dann eingeführt werden, wenn sie auch in der CCU reinkommen.

Ich würde momentan folgendes Projekt von Jérôme empfehlen: https://homematic-forum.de/forum/viewtopic.php?f=76&t=45210
