### ISSUE TITLE
pivccu startet nicht mehr

### ISSUE THREAD

**Issue by HLM0815** [alexreinert/piVCCU#305]
Hi,

seit Monaten läuft pivccu3 problemlos neben iobroker auf ner PI4 (Netboot)!
Seit ein Paar Tagen, nach nem Javascript-Update für iobroker gab es Probleme mit dem empfang diverser Homematik-Module, hab ich ein 
sudo apt-get update && sudo apt-get upgrade -y

durchgeführt und seit dem starte pivccu3 nicht mehr:

sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Board serial:  58A9A71002
 Radio MAC:     0xFF1002
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A9A71002
 Radio MAC:     0xBB1723
State:          STOPPED

sudo systemctl status pivccu
● pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-10-18 12:57:28 CEST; 9min ago
  Process: 511 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, status=0/SUCCESS)
 Main PID: 879 (code=exited, status=1/FAILURE)

Oct 18 12:57:21 ioBroker-Pi3 systemd[1]: Starting piVCCU...
Oct 18 12:57:28 ioBroker-Pi3 start_container.sh[511]: kernel.sched_rt_runtime_us = -1
Oct 18 12:57:28 ioBroker-Pi3 start_container.sh[511]: lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 842 Received container state "ABORTING" instead ofOct 18 12:57:28 ioBroker-Pi3 start_container.sh[511]: lxc-start: lxc: tools/lxc_start.c: main: 330 The container failed to start
Oct 18 12:57:28 ioBroker-Pi3 start_container.sh[511]: lxc-start: lxc: tools/lxc_start.c: main: 333 To get more details, run the container in foreground mode
Oct 18 12:57:28 ioBroker-Pi3 start_container.sh[511]: lxc-start: lxc: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfileOct 18 12:57:28 ioBroker-Pi3 systemd[1]: Started piVCCU.
Oct 18 12:57:28 ioBroker-Pi3 systemd[1]: pivccu.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 12:57:28 ioBroker-Pi3 systemd[1]: pivccu.service: Failed with result 'exit-code'.

Hab schon 

sudo dpkg-reconfigure pivccu-modules-dkms

ausgeführt, aber ohne Erfolg!

Woran kann das liegen?

Gruß

Markus

**Comment by alexreinert** [comment]
Wurde der gesamte Pi nach dem Updates mal neu gestartet?

**Comment by HLM0815** [comment]
reboot, poweroff, Stecker raus, alles ausprobiert!

sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Board serial:  58A9A71002
 Radio MAC:     0xFF1002
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A9A71002
 Radio MAC:     0xBB1723
State:          STOPPED

**Comment by HLM0815** [comment]
sudo apt install --reinstall pivccu-modules-dkms pivccu3 ausgeführt:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  avahi-utils bc
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/119 MB of archives.
After this operation, 0 B of additional disk space will be used.
Preconfiguring packages ...
(Reading database ... 139740 files and directories currently installed.)
Preparing to unpack .../pivccu-modules-dkms_1.0.45_all.deb ...
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.45
Kernel:  5.4.51-v7l+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_eth.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb-2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/
rmdir: failed to remove directory 'kernel/drivers': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod.....

DKMS: uninstall completed.

------------------------------
Deleting module version: 1.0.45
completely from the DKMS tree.
------------------------------
Done.
Unpacking pivccu-modules-dkms (1.0.45) over (1.0.45) ...
Setting up pivccu-modules-dkms (1.0.45) ...

Creating symlink /var/lib/dkms/pivccu/1.0.45/source ->
                 /usr/src/pivccu-1.0.45

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=5.4.51-v7l+ ARCH=arm all.........
cleaning build area....

DKMS: build completed.

dummy_rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

dw_apb_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

eq3_char_loop.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

fake_hmrf.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

generic_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

hb_rf_eth.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

hb_rf_usb-2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

hb_rf_usb.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

led_trigger_timer.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

meson_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

pl011_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

plat_eq3ccu2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

rpi_rf_mod_led.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

rtc-rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.51-v7l+/kernel/drivers/pivccu/

depmod...

DKMS: install completed.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
(Reading database ... 139740 files and directories currently installed.)
Preparing to unpack .../pivccu3_3.53.30-47_armhf.deb ...
Removed /etc/systemd/system/pivccu.service.wants/monitor-hb-rf-eth.service.
Removed /etc/systemd/system/multi-user.target.wants/pivccu.service.
Unpacking pivccu3 (3.53.30-47) over (3.53.30-47) ...
Setting up pivccu3 (3.53.30-47) ...
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu.service → /lib/systemd/system/pivccu.service.
Created symlink /etc/systemd/system/pivccu.service.wants/monitor-hb-rf-eth.service → /lib/systemd/system/monitor-hb-rf-eth.service.

**Comment by HLM0815** [comment]
danach direkt
sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Board serial:  58A9A71002
 Radio MAC:     0xFF1002
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A9A71002
 Radio MAC:     0xBB1723
State:          RUNNING
PID:            31599
IP:             169.254.8.244
CPU use:        91.57 seconds
BlkIO use:      0 bytes
Link:           vethpivccu
 TX bytes:      673.33 KiB
 RX bytes:      2.99 KiB
 Total bytes:   676.31 KiB

dann reboot:

sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Board serial:  58A9A71002
 Radio MAC:     0xFF1002
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A9A71002
 Radio MAC:     0xB00048
State:          STOPPED

???

**Comment by alexreinert** [comment]
Hast du irgendwelche USB Geräte, welche in die VM durchgereicht werden? Oder irgendwelche Eintragungen in den Hook Scripts? Ist das System "normal" auf einer SD Karte installiert oder gibt es da irgendwelche Spezialitäten?

Kannst du den Container jetzt mit "sudo systemctl start pivccu" manuell starten?

**Comment by alexreinert** [comment]
Und aufgrund der IP 169.254.x.x: Ist das System am Netzwerk angebunden? Läuft der DHCP Server korrekt? Wie sieht die /etc/network/interfaces aus? Zusätzlich noch Docker installiert, welches sich auch in die Netzwerksettings drängt?

**Comment by HLM0815** [comment]
Das System läuft ohne SD per Netboot auf nem NAS.

cat /etc/network/interfaces
source-directory /etc/network/interfaces.d
auto lo
iface lo inet loopback

iface eth0 inet dhcp

#auto br0
#iface br0 inet dhcp
#  bridge_ports eth0
auto br0
iface br0 inet static
  bridge_ports none
  bridge_fd    0
  address      192.168.253.1
  netmask      255.255.255.0

**Comment by HLM0815** [comment]
sudo systemctl start pivccu "endet" ohne Meldung

sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Board serial:  58A9A71002
 Radio MAC:     0xFF1002
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A9A71002
 Radio MAC:     0xB00048
State:          STOPPED

**Comment by HLM0815** [comment]
Welche Log's sollte ich mir ansehen?

**Comment by HLM0815** [comment]
sudo systemctl start pivccu

syslog:
Oct 21 15:13:56 ioBroker-Pi3 kernel: [11622.244247] device eth0 entered promiscuous mode
Oct 21 15:14:01 ioBroker-Pi3 systemd[1]: Started Session c3 of user markus.
Oct 21 15:14:02 ioBroker-Pi3 kernel: [11628.178376] device eth0 left promiscuous mode
Oct 21 15:14:13 ioBroker-Pi3 systemd[1]: Starting piVCCU DKMS Modules...
Oct 21 15:14:13 ioBroker-Pi3 systemd[1]: pivccu-dkms.service: Succeeded.
Oct 21 15:14:13 ioBroker-Pi3 systemd[1]: Started piVCCU DKMS Modules.
Oct 21 15:14:13 ioBroker-Pi3 systemd[1]: Starting piVCCU...
Oct 21 15:14:13 ioBroker-Pi3 kernel: [11639.863014] raw-uart raw-uart: Reset radio module
Oct 21 15:14:18 ioBroker-Pi3 start_container.sh[28823]: kernel.sched_rt_runtime_us = -1
Oct 21 15:14:18 ioBroker-Pi3 kernel: [11644.663435] br0: port 1(vethpivccu) entered blocking state
Oct 21 15:14:18 ioBroker-Pi3 kernel: [11644.663442] br0: port 1(vethpivccu) entered disabled state
Oct 21 15:14:18 ioBroker-Pi3 kernel: [11644.663571] device vethpivccu entered promiscuous mode
Oct 21 15:14:18 ioBroker-Pi3 kernel: [11644.851555] eth0: renamed from vethOL1B6X
Oct 21 15:14:18 ioBroker-Pi3 start_container.sh[28823]: lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 842 Received container state "ABORTING" instead of "RUNNING"
Oct 21 15:14:18 ioBroker-Pi3 start_container.sh[28823]: lxc-start: lxc: tools/lxc_start.c: main: 330 The container failed to start
Oct 21 15:14:18 ioBroker-Pi3 start_container.sh[28823]: lxc-start: lxc: tools/lxc_start.c: main: 333 To get more details, run the container in foreground mode
Oct 21 15:14:18 ioBroker-Pi3 start_container.sh[28823]: lxc-start: lxc: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfile and --logpriority options
Oct 21 15:14:18 ioBroker-Pi3 systemd[1]: Started piVCCU.
Oct 21 15:14:18 ioBroker-Pi3 kernel: [11644.906345] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Oct 21 15:14:18 ioBroker-Pi3 kernel: [11644.906461] IPv6: ADDRCONF(NETDEV_CHANGE): vethpivccu: link becomes ready
Oct 21 15:14:18 ioBroker-Pi3 kernel: [11644.906531] br0: port 1(vethpivccu) entered blocking state
Oct 21 15:14:18 ioBroker-Pi3 kernel: [11644.906538] br0: port 1(vethpivccu) entered forwarding state
Oct 21 15:14:18 ioBroker-Pi3 systemd[1]: Condition check resulted in Monitor HB-RF-ETH being skipped.
Oct 21 15:14:19 ioBroker-Pi3 systemd[1]: pivccu.service: Main process exited, code=exited, status=1/FAILURE
Oct 21 15:14:19 ioBroker-Pi3 systemd[1]: pivccu.service: Failed with result 'exit-code'.
Oct 21 15:14:19 ioBroker-Pi3 kernel: [11645.026594] br0: port 1(vethpivccu) entered disabled state
Oct 21 15:14:19 ioBroker-Pi3 kernel: [11645.045384] device vethpivccu left promiscuous mode
Oct 21 15:14:19 ioBroker-Pi3 kernel: [11645.045395] br0: port 1(vethpivccu) entered disabled state
Oct 21 15:14:25 ioBroker-Pi3 kernel: [11651.461039] debugfs: File 'le_min_key_size' in directory 'hci0' already present!
Oct 21 15:14:25 ioBroker-Pi3 kernel: [11651.461048] debugfs: File 'le_max_key_size' in directory 'hci0' already present!
Oct 21 15:14:26 ioBroker-Pi3 kernel: [11652.254658] device eth0 entered promiscuous mode
Oct 21 15:14:32 ioBroker-Pi3 kernel: [11658.184359] device eth0 left promiscuous mode
Oct 21 15:14:55 ioBroker-Pi3 kernel: [11681.460390] debugfs: File 'le_min_key_size' in directory 'hci0' already present!
Oct 21 15:14:55 ioBroker-Pi3 kernel: [11681.460400] debugfs: File 'le_max_key_size' in directory 'hci0' already present!
Oct 21 15:14:56 ioBroker-Pi3 kernel: [11682.154793] device eth0 entered promiscuous mode
Oct 21 15:15:02 ioBroker-Pi3 kernel: [11688.085860] device eth0 left promiscuous mode

**Comment by HLM0815** [comment]
Hab mein System neu aufgesetzt mit nem Image All-in-One für Raspberry Pi4 – piVCCU3, Homebridge und ioBroker.
Image auf SD-Karte ->alles läuft!

sudo apt update
sudo apt upgrade

damit ich mein Backup mit der entsprechenden Version aufspielen kann!

sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Board serial:  58A9A71002
 Radio MAC:     0xFF1002
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A9A71002
 Radio MAC:     0xBB1723
State:          RUNNING
PID:            24866
IP:             192.168.253.2
IP:             2003:da:e728:9300:a86a:a0ff:feb8:7675
CPU use:        72.47 seconds
BlkIO use:      4.20 MiB
Link:           vethpivccu
 TX bytes:      51.34 KiB
 RX bytes:      2.21 MiB
 Total bytes:   2.26 MiB

sudo systemctl status pivccu
● pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-10-31 13:12:23 GMT; 53min ago
  Process: 24629 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, status=0/SUCCESS)
 Main PID: 24855 (lxc-start)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/pivccu.service
           └─24855 /usr/bin/lxc-start --lxcpath /var/lib/piVCCU3 --name lxc --pidfile /var/run/pivccu3.pid --daemon

Oct 31 13:12:02 raspberrypi systemd[1]: Starting piVCCU...
Oct 31 13:12:23 raspberrypi start_container.sh[24629]: kernel.sched_rt_runtime_us = -1
Oct 31 13:12:23 raspberrypi systemd[1]: Started piVCCU.

Über Webui (jetzt funzt es noch), spiele ich das Backup ein. Alles scheint ok!

Aber die webui ist nicht mehr erreichbar?!? 

Verstehe ich nicht

sudo pivccu-info
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Board serial:  58A9A71002
 Radio MAC:     0xFF1002
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A9A71002
 Radio MAC:     0xBB1723
State:          RUNNING
PID:            24866
IP:             192.168.253.2
IP:             2003:da:e728:9300:a86a:a0ff:feb8:7675
CPU use:        83.56 seconds
BlkIO use:      4.89 MiB
Link:           vethpivccu
 TX bytes:      59.86 KiB
 RX bytes:      2.61 MiB
 Total bytes:   2.67 MiB

???

**Comment by HLM0815** [comment]
root@ioBroker-Pi3:/etc/lxc# sudo systemctl start pivccu.service
root@ioBroker-Pi3:/etc/lxc# journalctl -xe
Nov 03 17:00:45 ioBroker-Pi3 kernel: eth0: renamed from vethD4QW51
Nov 03 17:00:45 ioBroker-Pi3 start_container.sh[32694]: lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 842 Received container state "ABORTING" instead 
Nov 03 17:00:45 ioBroker-Pi3 start_container.sh[32694]: lxc-start: lxc: tools/lxc_start.c: main: 330 The container failed to start
Nov 03 17:00:45 ioBroker-Pi3 start_container.sh[32694]: lxc-start: lxc: tools/lxc_start.c: main: 333 To get more details, run the container in foreground mode
Nov 03 17:00:45 ioBroker-Pi3 start_container.sh[32694]: lxc-start: lxc: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfiNov 03 17:00:45 ioBroker-Pi3 systemd[1]: Started piVCCU.
-- Subject: A start job for unit pivccu.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit pivccu.service has finished successfully.
-- 
-- The job identifier is 866.
Nov 03 17:00:45 ioBroker-Pi3 systemd[1]: Condition check resulted in Monitor HB-RF-ETH being skipped.
-- Subject: A start job for unit monitor-hb-rf-eth.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit monitor-hb-rf-eth.service has finished successfully.
-- 
-- The job identifier is 912.
Nov 03 17:00:45 ioBroker-Pi3 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Nov 03 17:00:45 ioBroker-Pi3 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethpivccu: link becomes ready
Nov 03 17:00:45 ioBroker-Pi3 kernel: br0: port 1(vethpivccu) entered blocking state
Nov 03 17:00:45 ioBroker-Pi3 kernel: br0: port 1(vethpivccu) entered forwarding state
Nov 03 17:00:45 ioBroker-Pi3 sudo[32689]: pam_unix(sudo:session): session closed for user root
Nov 03 17:00:46 ioBroker-Pi3 kernel: br0: port 1(vethpivccu) entered disabled state
Nov 03 17:00:46 ioBroker-Pi3 systemd[1]: pivccu.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit pivccu.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Nov 03 17:00:46 ioBroker-Pi3 systemd[1]: pivccu.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit pivccu.service has entered the 'failed' state with result 'exit-code'.
Nov 03 17:00:46 ioBroker-Pi3 kernel: device vethpivccu left promiscuous mode
Nov 03 17:00:46 ioBroker-Pi3 kernel: br0: port 1(vethpivccu) entered disabled state

**Comment by HLM0815** [comment]
--logfile

lxc-start lxc 20201103161642.513 ERROR    start - start.c:__lxc_start:1951 - Failed to spawn container "lxc"
lxc-start lxc 20201103162229.821 ERROR    conf - conf.c:mount_autodev:1131 - Read-only file system - Failed to create "/dev" directory
lxc-start lxc 20201103162229.821 ERROR    conf - conf.c:lxc_setup:3553 - Failed to mount "/dev"
lxc-start lxc 20201103162229.821 ERROR    start - start.c:do_start:1275 - Failed to setup container "lxc"
lxc-start lxc 20201103162229.823 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
lxc-start lxc 20201103162229.863 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "ABORTING" instead of "RUNNING"
lxc-start lxc 20201103162229.863 ERROR    start - start.c:__lxc_start:1951 - Failed to spawn container "lxc"
lxc-start lxc 20201103162229.863 ERROR    lxc_start - tools/lxc_start.c:main:330 - The container failed to start
lxc-start lxc 20201103162229.863 ERROR    lxc_start - tools/lxc_start.c:main:333 - To get more details, run the container in foreground mode
lxc-start lxc 20201103162229.863 ERROR    lxc_start - tools/lxc_start.c:main:336 - Additional information can be obtained by setting the --logfile and --logpriority options

**Comment by HLM0815** [comment]
Thema Netboot Raspberry Pi und die daraus resultierenden Probleme (Berechtigungs-Probleme) hab ich ad acta gelegt und somit schliesse ich das Ticket (mache aber gleich ein neues auf ;)).
