### ISSUE TITLE
pivccu3 - Installation unter Armbian mit Fehlermeldung

### ISSUE THREAD

**Issue by ebin-dev** [alexreinert/piVCCU#307]
Bei der Installation von pivccu3 (oder Debmatic) auf einem RK3399 unter Armbian gibt es leider Probleme (siehe [Thread im HomeMatic Forum](https://homematic-forum.de/forum/viewtopic.php?f=69&t=62022)). Es tritt an vielen Stellen der Fehler auf 'piVCCU: Error! Hardware platform is not supported’.

Der Fehler ist bekannt und tritt bei der Installation z.B. des Pakets pivccu-modules-dkms nicht mehr auf, wenn man ans Ende von jeder .c Datei folgendes einfügt (siehe [Beitrag von vigeland im HomeMatic Forum](https://homematic-forum.de/forum/viewtopic.php?f=69&t=61372&hilit=pivccu+armbian#p608408)):

unsigned long __stack_chk_guard;
void __stack_chk_guard_setup(void)
{
__stack_chk_guard = 0xB233A44D;
}

void __stack_chk_fail(void) 
{

}

Die Fehlermeldung tritt auch bei der Installation der Pakete hm-rf-eth und pivccu3 auf und ist vermutlich ähnlich zu beheben.

Ich bin gerne jederzeit bereit Änderungen zu testen.

Beim RasPi 4 läuft alles reibungslos. Vielen Dank jedenfalls für die hervorragenden Arbeit.

**Comment by eloo** [comment]
@ebin-dev schau doch mal hier mit rein #289

**Comment by alexreinert** [comment]
Duplikat zu #289 --> Daher hier erstmal zu.
