### ISSUE TITLE
Keine Kanaleinstellung mehr sichtbar bei HmIP-eTRV-2 und HmIP-WTH-2

### ISSUE THREAD

**Issue by xxschottexx** [alexreinert/piVCCU#308]
Es werden mir bei HmIP-eTRV-2 und HmIP-WTH-2 keine Konfigurationsparameter mehr angezeigt, ab und anlernen hat nichts gebracht.

pivccu firmware 3.53.30
HmIP-eTRV-2 firmware 2.2.8
HmIP-WTH-2 firmware 2.6.0

besten dank im voraus

**Comment by alexreinert** [comment]
Glaskugel: Update durchgeführt und Browsercache nicht gelöscht und keinen Forced Refresh mit Strg+F5 gemacht?

Ansonsten bitte genauer beschreiben.

**Comment by xxschottexx** [comment]
Schande über mein Haupt... danke für die schnelle hilfe... alles wieder da
