### ISSUE TITLE
Support for CC1101 module

### ISSUE THREAD

**Issue by forvalak** [alexreinert/piVCCU#31]
Hallo,

wird CC1101 Modul unterstützt (z.B.: https://allgeek.de/2017/09/23/cc1101-spi-adapter-mit-u-fl-antennenbuchse/).
Wie kann es konfiguriert werden?

Grüße
Andreas

**Comment by leonsio** [comment]
wie stellst du es dir vor?
CCU2-FW unterstützt dies nicht, also wird es nicht funktionieren.

**Comment by alexreinert** [comment]
Sobald jemand eine für den CC1101 eine Firmware schreibt, welche Kompatibel mit den HM-MOD-RPI-PCB ist und eine solche Platine preislich deutlich günstiger ist, als das originale HM-MOD-RPI-PCB, werde ich den Support gerne einbauen. Bis dahin wird das nichts werden.
