### ISSUE TITLE
piVCCU erkennt RPI-RF-MOD Funkmodul nicht bzw blaue LED leuchtet nicht

### ISSUE THREAD

**Issue by neueWeltX** [alexreinert/piVCCU#311]
Hallo zusammen 
ich habe einen Raspi3b mit dem RPI-RF-MOD und einem ConbeeStick und Iobroker der tadellos läuft nur das Funkmodul scheint nicht richtig zu laufen. Habe es auch nach Anweisung hier mehr oder weniger installiert. Wenn ich das RasberryMatic laufen lasse funktioniert Das Funkmodul aber da habe ich das Problem mit den Conbeestick Migration.

**Comment by alexreinert** [comment]
Was liefert ```sudo pivccu-info```?
Was heißt mehr oder weniger nach Anweisung installiert?

**Comment by neueWeltX** [comment]
Das wird ausgespuckt bei sudo piccu-info:

piVCCU version: 3.47.10-28
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   QEQ0682125
Radio MAC:      0x000000
SGTIN:          3014F711A0001F5A4993D08D
State:          RUNNING
PID:            919
IP:             192.168.178.32
CPU use:        104.21 seconds
Link:           vethpivccu
 TX bytes:      92.14 KiB
 RX bytes:      6.18 MiB
 Total bytes:   6.27 MiB

Bei einem Befehl kam Hinweis irgendwas mit Sicherheit tut mir leid das weis ich jetzt nicht mehr und er wurde nicht ausgeführt.

**Comment by neueWeltX** [comment]
Was auch noch interessant ist dass die webui nach kurzer Zeit eingefriert sich aufhängt. 


Uhrzeit:15:23Datum:04.11.2020Sonnenaufgang:07:17Sonnenuntergang:16:23Aktuelle Firmwareversion:3.47.10CCU-Update:Firmware 3.53.34 ist verfügbar |   |   | Uhrzeit: | 15:23 | Datum: | 04.11.2020 | Sonnenaufgang: | 07:17 | Sonnenuntergang: | 16:23 | Aktuelle Firmwareversion: | 3.47.10 | CCU-Update: | Firmware 3.53.34 ist verfügbar
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Uhrzeit: | 15:23
Datum: | 04.11.2020
Sonnenaufgang: | 07:17
Sonnenuntergang: | 16:23
Aktuelle Firmwareversion: | 3.47.10
CCU-Update: | Firmware 3.53.34 ist verfügbar

**Comment by alexreinert** [comment]
Wie bzw. auch wann wurde das installiert? Die Version ist mal richtig alt.

**Comment by neueWeltX** [comment]
Hallo vor 2 Tagen habe das Image von hier (Github). Hier die Fehlermeldung beim aktualisieren:

hier habe ich jetzt die Fehlermeldung beim aktualisieren:

pi@IOBROKER-PI:~ $ OK:3 http://phoscon.de/apt/deconz buster InRelease
-bash: OK:3: Kommando nicht gefunden.
pi@IOBROKER-PI:~ $ OK:4 https://deb.nodesource.com/node_10.x buster InRelease
-bash: OK:4: Kommando nicht gefunden.
pi@IOBROKER-PI:~ $ Ign:5 https://www.pivccu.de/piVCCU stabile InRelease
-bash: Ign:5: Kommando nicht gefunden.
pi@IOBROKER-PI:~ $ Fehl:6 https://www.pivccu.de/piVCCU stabile Release
-bash: Fehl:6: Kommando nicht gefunden.
pi@IOBROKER-PI:~ $   404  Not Found [IP: 95.216.13.95 443]
-bash: 404: Kommando nicht gefunden.
pi@IOBROKER-PI:~ $ Paketlisten werden gelesen... Fertig
-bash: Paketlisten: Kommando nicht gefunden.
pi@IOBROKER-PI:~ $ E: Das Depot »https://www.pivccu.de/piVCCU stabile Release« enthält keine Release-Datei.
-bash: E:: Kommando nicht gefunden.
pi@IOBROKER-PI:~ $ N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
-bash: N:: Kommando nicht gefunden.
pi@IOBROKER-PI:~ $ N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
-bash: Syntaxfehler beim unerwarteten Wort `('

Grüße

**Comment by alexreinert** [comment]
Aktualisieren erfolgt mit ```apt update && apt upgrade```. Die Fehlermeldungen kommen dadurch, dass hier die Ausgabe der Befehle vermutlich per Copy&Paste auch auf der Konsole ausgeführt wurden und er mit der Ausgabe logischerweise nichts anfangen kann.

**Comment by neueWeltX** [comment]
Hallo und Danke. Ich habe den Befehl jetzt mit "Hand" eigegeben.
pi@IOBROKER-PI:~ $ apt update && apt upgrade
Paketlisten werden gelesen... Fertig
E: Sperrdatei /var/lib/apt/lists/lock konnte nicht geöffnet werden. - open (13: Keine Berechtigung)
E: Das Verzeichnis /var/lib/apt/lists/ kann nicht gesperrt werden.
W: Problem beim Entfernen (unlink) der Datei /var/cache/apt/pkgcache.bin - RemoveCaches (13: Keine Berechtigung)
W: Problem beim Entfernen (unlink) der Datei /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Keine Berechtigung)

Grüße

**Comment by alexreinert** [comment]
Ok, mein Fehler, es braucht da noch sudo, wenn man nicht als root Benuter angemeldet ist, also ```sudo apt update && sudo apt upgrade```

**Comment by neueWeltX** [comment]
Danke aber wider eine Fehlermeldung:
pi@IOBROKER-PI:~ $ sudo apt update && sudo apt upgrade
OK:1 http://phoscon.de/apt/deconz buster InRelease
Holen:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15,0 kB]
OK:3 http://archive.raspberrypi.org/debian buster InRelease
OK:4 https://deb.nodesource.com/node_10.x buster InRelease
Ign:5 https://www.pivccu.de/piVCCU stabile InRelease
Fehl:6 https://www.pivccu.de/piVCCU stabile Release
  404  Not Found [IP: 95.216.13.95 443]
Paketlisten werden gelesen... Fertig
E: Das Depot »https://www.pivccu.de/piVCCU stabile Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).

**Comment by neueWeltX** [comment]
Sind das die neusten Image ? 
https://www.pivccu.de/images/
FileSizeLast Modified
 piVCCU-2018-10-09 11:06:31
 piVCCU3-2019-07-14 08:33:33

**Comment by wendy2702** [comment]
Was steht in deinem „sources“ File?

Ich glaube du hast da einen Fehler und dort steht „stabile“ statt „stable“

Mach mal

`sudo cat /etc/apt/sources.list.d/pivccu.list `

**Comment by neueWeltX** [comment]
Hallo dann kommt 👍 
pi@IOBROKER-PI:~ $ sudo cat /etc/apt/sources.list.d/pivccu.list
deb https://www.pivccu.de/piVCCU stabile Hauptleitung

**Comment by neueWeltX** [comment]
ist es normal dass wenn ich den Link anklicke403  Forbidden bekomme ?

pi@IOBROKER-PI:~ $ sudo cat /etc/apt/sources.list.d/pivccu.list
deb https://www.pivccu.de/piVCCU stabile Hauptleitung

**Comment by alexreinert** [comment]
Die Zeile muss ```deb https://www.pivccu.de/piVCCU stable main``` lauten.

Kann es sein, dass du die Anleitung erst über einen Übersetzer laufen lassen hast? In dem Fall würde ich einmal komplett von vorne mit der englischen Anleitung starten, ich könnte mir vorstellen, dass da noch andere Dinge durch die Übersetzung fehlerhaft sind.

**Comment by neueWeltX** [comment]
Also ich fange am besten nochmal von vorne an ich hab ja Zeit. Also das hier ist das neuste Image in meinem Fall 
 piVCCU3-2019-07-14 08:33:33  ? 

Grüße

**Comment by wendy2702** [comment]
Images liegen hier:

`https://www.pivccu.de/images/?dir=piVCCU3`

Anleitung dazu hier:

https://github.com/alexreinert/piVCCU

Wenn dein Single Board Computer Modell bei den fertigen Images nicht dabei ist oder du noch andere Spezielle Sachen mit dem Rechner machen willst solltest du auch über eine manuelle Installation nach denken.

**Comment by neueWeltX** [comment]
Hallo und vielen Dank für die bisherige Hilfe
ich habe jetzt das ganze neu installiert weil ich es ehrlich gesagt auch nicht mehr verstanden habe und zu viel Eingaben drauf gebügelt habe.

Habe diese Image Raspian Buster Liste piVCCU3_2019-07-11.mg + update und upgrade gemacht.
Hurra die blaue LED leuchtet und ist Betriebsbereit das anlernen hat jedoch noch nicht geklappt keine Ahnung warum.
Erst wenn das geklappt hat muss ich noch den iobroker und conbee Stick integrieren.
