### ISSUE TITLE
Install VCCU3 on a ATOM processor (Synology NAS VM)

### ISSUE THREAD

**Issue by lobocobra** [alexreinert/piVCCU#312]
I would like to install VCCU3 on a synology NAS and use my  CCU3 as reapeater only.
=> I tried it and I could install the software  but the CCU GUI never showed up.

The NAS has an Intel Atom C2538 CPU.

There is an entry for a "fake" installation in the menu but I did not manage it got get it working.Background is that I want to have the ccu-logic on the same server like my OH2 (which is on my synology) and have 2 CCU3 in the house distributed for good connection.

Anyone could help me to make this happen? Can I recomplie the kernel modules or what is missing? Best would be of course if it would work with the USB homematic adapter but this is not a must. I only want to have the GUI on my NAS (ps yes I have a PI4 but I do not want that solution).

**Comment by alexreinert** [comment]
piVCCU is based on the original CCU firmware which is ARM. So there is no chance to run it on x86/x64.
Maybe you have a look at debmatic, which runs on x86 and x64, too.

**Comment by lobocobra** [comment]
many thanks, I will give it a try :-) 
=> I also found an info about Raspberrymatic „ova“-Version

I will give both options a try and report here how it worked...

**Comment by lobocobra** [comment]
With above link you can really install homematic on a Synology VMM! It work perfectly.
=> The only problem I have is that the CCU Gateway does not forward homematicIP signals.
=> The newest firmeware seems to fix that problem, but you seem to need a homaticIP central.

Still testing but this is a good start for half a day...
