### ISSUE TITLE
RAW URAT dev: Not available

### ISSUE THREAD

**Issue by IHC353** [alexreinert/piVCCU#313]
Hallo Zusammen,
ich bin neu hier und beschäftige mich seit geraumer Zeit mit der PIVCCU und habe die auf einem Pi installiert. Leider meldet dieser o.g. Fehlerbild. Somit kann ich nicht auf die CCU zugreifen und dort arbeiten. Vllt. kann mir jemand aus dem Blog helfen. Vielen Dank schonmal im Voraus.

**Comment by alexreinert** [comment]
Welcher Blog? ;-)

Was liefert ```sudo pivccu-info```?
Wurden alle Schritte der Anleitung inkl. der Reboots eingehalten?

**Comment by IHC353** [comment]
Hallo,

ja. Die Schritte wurden nach der Anleitungen für den Pi durchgeführt und die Reboots habe ich gemacht.
pivccu-info liefert folgendes:
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
 Connected via:  (/dev/raw-uart5)
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
State:          STOPPED

**Comment by IHC353** [comment]
Hallo Alex,

hast du eine Idee was da nicht passt?

**Comment by alexreinert** [comment]
Bitte mal den Inhalt der /boot/config.txt

**Comment by IHC353** [comment]
Hallo Alex,

anbei der Verlauf.

  GNU nano 3.2                    /boot/config.txt                              

# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus

**Comment by alexreinert** [comment]
Entweder wurde die /boot/config.txt nach der Installation überschrieben oder mind. die Schritte 5 und 6 der Anleitung nicht oder mit Fehler ausgeführt.

**Comment by IHC353** [comment]
Hallo Alex, habe die Schritte nochmals vollzogen. Das Problem müsste somit gelöst sein. Vielen Dank nochmal
