### ISSUE TITLE
"java" (2550) uses deprecated CP15 Barrier instruction

### ISSUE THREAD

**Issue by vigeland** [alexreinert/piVCCU#319]
Derzeit logged das ccm meinen Kern.log mit den Meldungen voll.
Wie ist die Meldung zu bewerten? 

Weg bekommt man die mit, aber sollte man das Überhaupt ? 
echo 2 >/proc/sys/abi/setend
echo 2 >/proc/sys/abi/cp15_barrier
oder
abi.cp15_barrier = 2
abi.setend = 2 
in sysctl.conf

**Comment by alexreinert** [comment]
Fixed mit Commit 17edc78967

**Comment by ebin-dev** [comment]
Den Issue können wir schließen - seit dem letzten Commit gibt es keine CP15 Barrier Meldungen im syslog mehr.
