### ISSUE TITLE
Rasbian Stretch with Desktop don't work :-(

### ISSUE THREAD

**Issue by dr-apple** [alexreinert/piVCCU#32]
Hello i have installed pivccu oh a Rasbian Stretch lite all good and works fine, but then i install it on a the desktop version it dosen't wont to work:

pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 2.31.25-23
Kernel modules: Available
Raw UART dev:   Not available
Board serial:   Unknown
lxc doesn't exist

Why ?

**Comment by alexreinert** [comment]
Please provide the output of the follwing commands:

sudo dpkg --get-selections | grep pivccu
sudo cat /boot/config.txt

Did you reboot after the installation of the package pivccu-modules-raspberrypi?

**Comment by dr-apple** [comment]
pi@raspberrypi:~ $ sudo dpkg --get-selections | grep pivccu
pivccu						install
pivccu-modules-dkms				install
pivccu-modules-raspberrypi			install

pi@raspberrypi:~ $ sudo cat /boot/config.txt
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on
enable_uart=0
dtoverlay=pivccu-raspberrypi
dtoverlay=pi3-disable-bt


Yes have reboot ;-)

**Comment by alexreinert** [comment]
Please try to switch the order of the last dtoverlay lines and reboot.

**Comment by alexreinert** [comment]
And enable_uart=0 is a bad idea, this should be 1

**Comment by dr-apple** [comment]
Thank you very much ! enable_uart=0 have change to enable_uart=1 and reboot, it works !!!
