### ISSUE TITLE
Gerät an pivccu anlernen funktioniert nicht

### ISSUE THREAD

**Issue by peter-co** [alexreinert/piVCCU#322]
Ich bin Anfänger und möchte auf einem Raspi 4B mittels pivccu eine HomematicIP- 
Hausautomatisierung realisieren. 
Die Einrichtung des Systems hat (inzwischen) auch reibungslos funktioniert.
Das System scheint zu laufen:

pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.53.34-49
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  FAKE_HMRF
 Connected via:  (/dev/)
 Board serial:  FKE4795264
 Radio MAC:     0xffebb3
HMIP Hardware:  HMIP-RFUSB
 SGTIN:         3014F711A000041BE99B378C
 Radio MAC:     0x1AF2F4
State:          RUNNING
PID:            1181
IP:             192.168.178.53
CPU use:        364.84 seconds
BlkIO use:      64.84 MiB
Link:           vethpivccu
 TX bytes:      16.47 MiB
 RX bytes:      8.19 MiB
 Total bytes:   24.66 MiB

pi@raspberrypi:~ $ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 1b1f:c020 eQ-3 Entwicklung GmbH 
Bus 001 Device 003: ID 046d:c534 Logitech, Inc. Unifying Receiver
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

und ich kann mich erwartungsgemäß via Webbrowser anmelden. 

Leider gelingt es mir aber nachhaltig nicht, ein erstes Gerät (Schalt-Mess-Steckdose) 
anzulernen. Ich kann auch nicht entscheiden, ob das Problem an 
- der Systeminstallation 
- dem HmIP-RFUSB
- oder der Schalt-Mess-Steckdose 
liegt. Alle Komponenten sind Neuware.

Wie kann ich das Problem weiter eingrenzen?

**Comment by alexreinert** [comment]
Was für ein Gerät ist das konkret? Wie ist dein genaues Vorgehen beim Anlernen? In welchem USB Port ist der HmIP-RFUSB eingesteckt, ist der direkt eingesteckt oder mittels Verlängerung?

**Comment by peter-co** [comment]
Vielen Dank für die kurzfristige Anwort!

Das Gerät trägt die Bezeichnung HMIP-PSM//154520//V1.0(04/2019)

Anlernen erfolgt direkt an der CCU: Vom Webbrowser aus "Anlernen"
anklicken, es öffnet sich das Popup mit den beiden Anlernfunktionen für
HmIP-Geräte mit und ohne Internetzugang. Weder das Anlernen mit Hilfe der
Anlerntaste am Gerät, noch die Eingabe von Key und SGTIN führen zu einer
erkennbaren Reaktion an der CCU. Die Anlernzeit läuft ohne jede Reaktion ab.

Der HmIP-RFUSB wurde bereits in jedem der beiden USB2-Ports des Raspi
betrieben, meist mit dem mitgelieferten (kurzen) Verlängerungskabel. Aber
auch ein Versuch ohne dieses Kabel endet nach der 20s dauernden Blinkphase
des anzulernenden Geräts mit einem kurzen Aufleuchten der roten Signal-LED
am Gerät und negativem Ergebnis an der CCU.

Außerdem: in meiner Geräteliste befinden sich die beiden Geräte HM-RCV-50
BidCoS-RF und HmIP-RCV-50/HmIP-RCV-1 mit jeweils 50 Schaltfunktionen, deren
Herkunft und Bedeutung ich nicht interpretieren kann.

Beste Grüße

Am Mo., 23. Nov. 2020 um 18:27 Uhr schrieb Alexander Reinert <
notifications@github.com>:

**Comment by alexreinert** [comment]
Ich habe bewusst nach dem genauen Weg des Anmeldens gefragt, weil hier häufig etwas falsch gemacht wird. Auch wenn es hier nicht genau beschrieben wurde, die Bezeichnung Anlerntaste deutet auf ein falsches Vorgehen hin.

Korrektes Vorgehen:
- Werksreset vom HmIP-PSM (auch wenn der frisch geliefert wurde)
- HmIP-PSM vom Strom trennen
- Anlernmodus in der CCU starten
- Stromversorgung wiederherstellen
- Warten, nichts am Gerät drücken

Nach Ablauf der 30 Sekunden befindet sich das Gerät dann normalerweise im Posteingang.

Die beiden 50 Kanal Geräte sind korrekt, in einem Issue-Tracker zu erläutern, wofür die sind, führt aber zu weit. Ich empfehle hier entsprechende Tutorials zur CCU3 oder einen Blick ins Homematic Forum.

**Comment by peter-co** [comment]
Leider blieb auch dieser Versuch ohne Erfolg.

Das Gerät wurde gemäß Bedienungsanleitung auf www.homematic-ip.com auf
Werkseinstellungen zurückgesetzt (das dem Gerät als Anleitung beiliegende
Faltblatt ist bezüglich Anlernen stark irreführend!). Anschließend Gerät
vom Strom getrennt und zunächst Anlernmodus in CCU gestartet. Nach
Wiederherstellen der Stromversorgung des Geräts blinkt die Systemtaste des
Geräts alle 10s kurz orange (--> Anlernmodus gemäß Bedienungsanleitung).
Einzige zu beobachtende Reaktion der CCU ist, dass im Zentrum der während
des Anlernens ausgegrauten oberen Bedienleiste des Homematic Web UI in
unregelmäßigen(?) Abständen ein kurzes Aufblinken eines ringförmigen
Symbols, ca. 1cm Durchmesser, zu erkennen ist.



Am Di., 24. Nov. 2020 um 09:29 Uhr schrieb Alexander Reinert <
notifications@github.com>:

**Comment by alexreinert** [comment]
Gut, dann bitte mal den HmIP-RFUSB so weit wie möglich vom Raspberry Pi entfernen, grade der 4er ist leider für seine Störstrahlung bekannt.
Beim HmIP-RFUSB handelt es sich vermutlich um den Bausatz, daher bitte mal Bilder vom Innenleben, auf welchen man die Lötstellen gut erkennen kann.

**Comment by peter-co** [comment]
Auch Abstand >1m zwischen Raspi und HmIP-RFUSB zeigt keine Änderung.

Im Anhang die Bilder der Lötstellen.

Am Di., 24. Nov. 2020 um 12:39 Uhr schrieb Alexander Reinert <
notifications@github.com>:

**Comment by alexreinert** [comment]
Mail Anhänge werden von Github ausgefiltert, daher bitte anderweitig hochladen und hier verlinken.

**Comment by peter-co** [comment]
![20201124_133344](https://user-images.githubusercontent.com/74924569/100099469-c6fa5f00-2e5f-11eb-803d-8b65020c3d3f.jpg)
![20201124_133435](https://user-images.githubusercontent.com/74924569/100099533-dd081f80-2e5f-11eb-9fdb-f2cf55b7f268.jpg)
Sind die Fotos jetzt verfügbar?

**Comment by alexreinert** [comment]
Mind. die Lötverbindung von Gnd hat hohes Potential für eine kalte Lötstelle, aber auch die anderen Lötstellen am TRX Modul könnte ich mir Probleme vorstellen. Bitte mal alle Lötstellen nacharbeiten.

**Comment by peter-co** [comment]
Guten Morgen, die Überarbeitung der Lötstellen hat geholfen. Vielen
herzlichen Dank ! und ich melde mich nochmal via Paypal. Schöne Grüße

Am Di., 24. Nov. 2020 um 14:31 Uhr schrieb Alexander Reinert <
notifications@github.com>:

**Comment by alexreinert** [comment]
Freut mich, das es jetzt klappt. Und Danke!
