### ISSUE TITLE
Low_Bat in Heizungsgruppen

### ISSUE THREAD

**Issue by MeinzIsAs** [alexreinert/piVCCU#323]
Ich habe mehrere Heizungsgruppen eingerichtet. Jeweils mit Raumthermostat, Heizkörperthermostat und Fensterkontakt.
Bei einer Low_Bat Meldung eines der Geräte in der Gruppe wird die Low_Bat Meldung der Gruppe nur sporadisch gesetzt. Sprich diese kommt, geht, kommt......
Die Einzelmeldung des Gerätes bleibt immer anstehen. 
Da ich die Low_Bat Meldung der Gruppe in iobroker auswerte, wäre es super, wenn die Meldung der Gruppe auch bleiben würde.

Ich verwende die Version: 3.53.34

Vielen Dank

**Comment by alexreinert** [comment]
Gebe ich dir vollkommen recht, aber da das ein Problem innerhalb des Closed Source von eQ-3 ist, kann ich da leider nichts dran ändern.

**Comment by MeinzIsAs** [comment]
Ok. Trotzdem vielen Dank
