### ISSUE TITLE
pivccu3 - Kommunikationsproblem zwischen HB-RF-ETH/RPI-RF-MOD und Helios64

### ISSUE THREAD

**Issue by ebin-dev** [alexreinert/piVCCU#324]
Auch mit der aktuellen pivccu3 Version (testing) klappt die Kommunikation zwischen HB-RF-ETH/RPI-RF-MOD und Helios64 leider nicht. Getestet habe ich das mit den aktuellsten Armbian Focal und Armbian Buster testing Versionen für den Helios64 vom 22. November. Pivccu3 läuft ansonsten fehlerfrei auf dem Helios64, wenn das 'fake hardware module' konfiguriert ist.

Das stack_chk_guard Problem unter Armbian Buster ist mit dem heutigen Update behoben - die Installation läuft unter Buster und Focal fehlerfrei durch. Die Warnung "Warning: Could not locate raw uart interface..."  bei der Ersteinrichtung der pivccu3 kommt weiterhin. Auf einem RasPi4 (32bit OS) läuft die aktuelle pivccu3 testing Version einwandfrei mit HB-RF-ETH/RPI-RF-MOD als Antennenlösung.

Armbian 20.11.0-trunk.41 Focal with Linux 5.9.10-rockchip64:

Nov 24 11:01:24 localhost systemd[1]: Starting piVCCU DKMS Modules...
Nov 24 11:01:24 localhost systemd[1]: pivccu-dkms.service: Succeeded.
Nov 24 11:01:24 localhost systemd[1]: Finished piVCCU DKMS Modules.
Nov 24 11:01:24 localhost systemd[1]: Starting piVCCU...
Nov 24 11:01:25 localhost kernel: [  503.421276] hb-rf-eth hb-rf-eth: Trying to connect to xx.xx.xx.32
Nov 24 11:01:25 localhost kernel: [  503.529216] hb-rf-eth hb-rf-eth: Successfully connected to xx.xx.xx.32
Nov 24 11:01:25 localhost kernel: [  503.615072] raw-uart raw-uart: Reset radio module
Nov 24 11:01:43 localhost piVCCU3: HMRF hardware was not detected
Nov 24 11:01:43 localhost start_container.sh[3987]: <12>Nov 24 11:01:43 piVCCU3: HMRF hardware was not detected
Nov 24 11:01:43 localhost piVCCU3: HMIP hardware was not detected
Nov 24 11:01:43 localhost start_container.sh[3988]: <12>Nov 24 11:01:43 piVCCU3: HMIP hardware was not detected
Nov 24 11:01:44 localhost start_container.sh[4259]: kernel.sched_rt_runtime_us = -1
Nov 24 11:01:44 localhost kernel: [  522.851954] br0: port 2(vethpivccu) entered blocking state
Nov 24 11:01:44 localhost kernel: [  522.851969] br0: port 2(vethpivccu) entered disabled state
Nov 24 11:01:44 localhost kernel: [  522.852228] device vethpivccu entered promiscuous mode
Nov 24 11:01:44 localhost kernel: [  522.852837] br0: port 2(vethpivccu) entered blocking state
Nov 24 11:01:44 localhost kernel: [  522.852847] br0: port 2(vethpivccu) entered listening state
Nov 24 11:01:44 localhost kernel: [  522.853770] br0: port 2(vethpivccu) entered disabled state
Nov 24 11:01:44 localhost kernel: [  522.855743] eth0: renamed from vethZseq0G
Nov 24 11:01:44 localhost NetworkManager[765]: <info>  [1606212104.5652] manager: (vethpivccu): new Veth device (/org/freedesktop/NetworkManager/Devices/7)
Nov 24 11:01:44 localhost systemd-udevd[4276]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Nov 24 11:01:44 localhost systemd-udevd[4276]: Using default interface naming scheme 'v245'.
Nov 24 11:01:44 localhost kernel: [  522.896249] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Nov 24 11:01:44 localhost kernel: [  522.896437] IPv6: ADDRCONF(NETDEV_CHANGE): vethpivccu: link becomes ready
Nov 24 11:01:44 localhost kernel: [  522.896656] br0: port 2(vethpivccu) entered blocking state
Nov 24 11:01:44 localhost kernel: [  522.896666] br0: port 2(vethpivccu) entered listening state
Nov 24 11:01:44 localhost NetworkManager[765]: <info>  [1606212104.6072] device (vethpivccu): carrier: link connected
Nov 24 11:01:44 localhost start_container.sh[4260]: lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 851 Received container state "ABORTING" instead of "RUNNING"
Nov 24 11:01:44 localhost start_container.sh[4260]: lxc-start: lxc: tools/lxc_start.c: main: 308 The container failed to start
Nov 24 11:01:44 localhost start_container.sh[4260]: lxc-start: lxc: tools/lxc_start.c: main: 311 To get more details, run the container in foreground mode
Nov 24 11:01:44 localhost start_container.sh[4260]: lxc-start: lxc: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
Nov 24 11:01:44 localhost systemd[1]: Started piVCCU.
Nov 24 11:01:44 localhost systemd[1]: Started Monitor HB-RF-ETH.
Nov 24 11:01:44 localhost systemd[1]: pivccu.service: Main process exited, code=exited, status=1/FAILURE
Nov 24 11:01:44 localhost systemd[1]: pivccu.service: Failed with result 'exit-code'.
Nov 24 11:01:44 localhost kernel: [  523.027366] br0: port 2(vethpivccu) entered disabled state
Nov 24 11:01:44 localhost kernel: [  523.030133] device vethpivccu left promiscuous mode
Nov 24 11:01:44 localhost kernel: [  523.030151] br0: port 2(vethpivccu) entered disabled state
Nov 24 11:01:44 localhost NetworkManager[765]: <info>  [1606212104.7664] device (vethpivccu): released from master device br0

pivccu-info:

piVCCU version: 3.53.34-49
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
 Connected via:  (/dev/raw-uart5)
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
State:          STOPPED

Armbian 20.11.0-trunk.41 Buster with Linux 5.9.10-rockchip64:
 	
Nov 24 11:37:14 localhost systemd[1]: Starting piVCCU DKMS Modules...
Nov 24 11:37:14 localhost systemd[1]: pivccu-dkms.service: Succeeded.
Nov 24 11:37:14 localhost systemd[1]: Started piVCCU DKMS Modules.
Nov 24 11:37:14 localhost systemd[1]: Starting piVCCU...
Nov 24 11:37:14 localhost kernel: [  302.693432] hb-rf-eth hb-rf-eth: Trying to connect to xx.xx.xx.32
Nov 24 11:37:14 localhost kernel: [  302.801192] hb-rf-eth hb-rf-eth: Successfully connected to xx.xx.xx.32
Nov 24 11:37:14 localhost kernel: [  302.887766] raw-uart raw-uart: Reset radio module
Nov 24 11:37:32 localhost piVCCU3: HMRF hardware was not detected
Nov 24 11:37:32 localhost start_container.sh[3521]: <12>Nov 24 11:37:32 piVCCU3: HMRF hardware was not detected
Nov 24 11:37:32 localhost piVCCU3: HMIP hardware was not detected
Nov 24 11:37:32 localhost start_container.sh[3521]: <12>Nov 24 11:37:32 piVCCU3: HMIP hardware was not detected
Nov 24 11:37:33 localhost start_container.sh[3521]: kernel.sched_rt_runtime_us = -1
Nov 24 11:37:33 localhost kernel: [  321.830262] br0: port 2(vethpivccu) entered blocking state
Nov 24 11:37:33 localhost kernel: [  321.830291] br0: port 2(vethpivccu) entered disabled state
Nov 24 11:37:33 localhost kernel: [  321.830553] device vethpivccu entered promiscuous mode
Nov 24 11:37:33 localhost systemd-udevd[3724]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Nov 24 11:37:33 localhost systemd-udevd[3724]: Using default interface naming scheme 'v240'.
Nov 24 11:37:33 localhost systemd-udevd[3724]: Could not generate persistent MAC address for vethOA16T3: No such file or directory
Nov 24 11:37:33 localhost NetworkManager[926]: <info>  [1606214253.4381] manager: (vethOA16T3): new Veth device (/org/freedesktop/NetworkManager/Devices/7)
Nov 24 11:37:33 localhost systemd-udevd[3725]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Nov 24 11:37:33 localhost systemd-udevd[3725]: Using default interface naming scheme 'v240'.
Nov 24 11:37:33 localhost NetworkManager[926]: <info>  [1606214253.4435] manager: (vethpivccu): new Veth device (/org/freedesktop/NetworkManager/Devices/8)
Nov 24 11:37:33 localhost kernel: [  321.907737] eth0: renamed from vethOA16T3
Nov 24 11:37:33 localhost kernel: [  321.939974] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Nov 24 11:37:33 localhost kernel: [  321.940071] IPv6: ADDRCONF(NETDEV_CHANGE): vethpivccu: link becomes ready
Nov 24 11:37:33 localhost kernel: [  321.940151] br0: port 2(vethpivccu) entered blocking state
Nov 24 11:37:33 localhost kernel: [  321.940155] br0: port 2(vethpivccu) entered listening state
Nov 24 11:37:33 localhost NetworkManager[926]: <info>  [1606214253.5461] device (vethpivccu): carrier: link connected
Nov 24 11:37:33 localhost start_container.sh[3521]: lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 842 Received container state "ABORTING" instead of "RUNNING"
Nov 24 11:37:33 localhost start_container.sh[3521]: lxc-start: lxc: tools/lxc_start.c: main: 330 The container failed to start
Nov 24 11:37:33 localhost start_container.sh[3521]: lxc-start: lxc: tools/lxc_start.c: main: 333 To get more details, run the container in foreground mode
Nov 24 11:37:33 localhost start_container.sh[3521]: lxc-start: lxc: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfile and --logpriority options
Nov 24 11:37:33 localhost systemd[1]: Started piVCCU.
Nov 24 11:37:33 localhost systemd[1]: Started Monitor HB-RF-ETH.
Nov 24 11:37:33 localhost systemd[1]: pivccu.service: Main process exited, code=exited, status=1/FAILURE
Nov 24 11:37:33 localhost systemd[1]: pivccu.service: Failed with result 'exit-code'.
Nov 24 11:37:33 localhost kernel: [  322.013553] br0: port 2(vethpivccu) entered disabled state
Nov 24 11:37:33 localhost kernel: [  322.014588] device vethpivccu left promiscuous mode
Nov 24 11:37:33 localhost kernel: [  322.014604] br0: port 2(vethpivccu) entered disabled state
Nov 24 11:37:33 localhost NetworkManager[926]: <info>  [1606214253.6490] device (vethpivccu): released from master device br0

pivccu-info:
piVCCU version: 3.53.34-49
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
 Connected via:  (/dev/raw-uart5)
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
State:          STOPPED

**Comment by vigeland** [comment]
len = kernel_sendmsg(sock, &header, &vec, 1, len);
    set_fs(oldmm);

    if (len < 0)
      dev_err(dev, "Error %d on sending packet\n", (int)len);
  }

**Comment by vigeland** [comment]
Hier wird nicht geprüft ob len wirklich die Anzahl der Bytes die man senden will ist.
Da würde niemand merken wenn man 1500 Bytes verschicken will und das System wegen z.b. MTU Size nur 800 rausgehen.

**Comment by alexreinert** [comment]
Nein, es können maximal TX_CHUNK_SIZE = 1468 Zeichen in die Methode reingehen. Mit UDP Header kommt das genau auf die 1500 Zeichen, welche bei Ethernet die MTU sind. Und alles andere als Ethernet wird wg. der Latenz sowieso nicht funktionieren.

**Comment by vigeland** [comment]
Ja, das ist der Ansatz der Umsetzung. Das hatte ich verstanden.
Aber dennoch muss len der Rückgabe ( ich denke es sind Bytes ) nicht gleich dem len in dem Aufruf sein.
In 1500 Bytes , return 1200.  kernel_sendmsg darf das. Nur wird die Situation nicht abgefangen.

**Comment by ebin-dev** [comment]
Nach dem Update von detect-radio-module auf 1.0.4 tritt das Kommunikationsproblem weiterhin auf. 

Das hat zwar nichts damit zu tun, aber ich habe mal den network-manager ersetzt durch systemd-networkd, aber auch das liefert keine neuen Erkenntnisse im syslog.

dpkg -s detect-radio-module
Package: detect-radio-module
Status: install ok installed
Priority: extra
Section: misc
Maintainer: Alexander Reinert <alex@areinert.de>
Architecture: arm64
Version: 1.0-4
Description: detect_radio_module
  This package contains a tool to identify Homematic radio modules
Homepage: https://github.com/alexreinert/piVCCU

**Comment by alexreinert** [comment]
das ist kein Wunder, die Änderung im detect-radio-module bezieht sich rein darauf, dass man per Option auch alle gesendeten und empfangenen Frames auf der Konsole ausgeben kann.
Das Problem beim Helios liegt irgendwo im Kernel, das hatte ich bei der Debugsession auf deinem Helios ja bereit festgestellt.

**Comment by alexreinert** [comment]
Ich bin ein Stück weiter gekommen, ich konnte das Problem auf weiteren Geräten reproduzieren. Das Problem existiert schon bei der Kommunikation mit der HB-RF-ETH, daher habe ich bisher bei meinen Tests piVCCU komplett außen vor gelassen und habe nur die Kernel Module betrachtet, allerdings auf einer debmatic Installation. Da klappt alles. Auf einer Installation mit piVCCU klappt es dagegen nicht. Der große Unterschied auf unterster Ebene zwischen den beiden Systemen ist die Linux Bridge und die ist bei dem Problem beteiligt, weil ein Teil der UDP Pakete nicht innerhalb der Bridge weitergeleitet werden:

Diese 3 Pakete werden vom hb-rf-eth Kernel Modul an die Bridge gegeben und werden bei einem tcpdump auch ausgegeben.
```
09:08:50.273810 IP (tos 0x0, ttl 64, id 46326, offset 0, flags [DF], proto UDP (17), length 32)
    192.168.20.111.35946 > 192.168.20.94.3008: [udp sum ok] UDP, length 4
        0x0000:  8caa b5ab 8e03 f228 01ac f662 0800 4500  .......(...b..E.
        0x0010:  0020 b4f6 4000 4011 dbb8 c0a8 146f c0a8  ....@.@......o..
        0x0020:  145e 8c6a 0bc0 000c 3df2 02aa 7cf1       .^.j....=...|.
09:08:50.395474 IP (tos 0x0, ttl 64, id 46343, offset 0, flags [DF], proto UDP (17), length 40)
    192.168.20.111.35946 > 192.168.20.94.3008: [udp sum ok] UDP, length 12
        0x0000:  8caa b5ab 8e03 f228 01ac f662 0800 4500  .......(...b..E.
        0x0010:  0028 b507 4000 4011 db9f c0a8 146f c0a8  .(..@.@......o..
        0x0020:  145e 8c6a 0bc0 0014 47b0 07ab fd00 03fe  .^.j....G.......
        0x0030:  0201 981d d304                           ......
09:08:51.373819 IP (tos 0x0, ttl 64, id 46512, offset 0, flags [DF], proto UDP (17), length 32)
    192.168.20.111.35946 > 192.168.20.94.3008: [udp sum ok] UDP, length 4
        0x0000:  8caa b5ab 8e03 f228 01ac f662 0800 4500  .......(...b..E.
        0x0010:  0020 b5b0 4000 4011 dafe c0a8 146f c0a8  ....@.@......o..
        0x0020:  145e 8c6a 0bc0 000c 3dfc 02ac 7ce5       .^.j....=...|.
```

Auf dem physikalischen Ethernet Adapter kommt das mittlere Paket aber nicht an, weder bei einem tcpdump auf der gleichen Maschine, noch wenn man sich das "extern" per Port Mirroring mitschneidet.
Kurzfristiger Workaround: Nutzung von debmatic, weil man da keine Bridge braucht.

**Comment by alexreinert** [comment]
Problem sollte mit dem letzten Commit erledigt sein, eine entsprechend aktualisierte Version ist im testing APT Repo.

**Comment by ebin-dev** [comment]
Hallo Alex - das Kommunikationsproblem ist mit dem letzten Commit erledigt !

Ich habe meine pivccu3  Installation bereits vom RasPi4 auf den Helios64 übertragen und es funktioniert alles: Homematic und Homematic IP (bei mir läuft die Logik über Node-Red). Die Bridge habe ich über systemd-networkd realisiert - es geht aber auch mit dem network-manager.

Meinen ganz herzlichen Dank für Deinen Einsatz und an @vigeland für seine Unterstützung. Wenn ich das richtig sehe, sollte die pivccu3 mit HB-RF-ETH/RPI-RF-MOD als Antennenlösung jetzt auf allen Armbian Systemen mit aktuellem Kernel laufen. Wow ! Ich werde entsprechend Werbung dafür machen.

Das einzige, was noch zu tun wäre, ist die Flut an "CP15 Barrier" Meldungen aus dem syslog zu verbannen (@vigeland in issue [#319](https://github.com/alexreinert/piVCCU/issues/319) ).

Zuletzt noch der syslog:
Nov 27 07:29:37 grid systemd[1]: Starting piVCCU DKMS Modules...
Nov 27 07:29:37 grid systemd[1]: pivccu-dkms.service: Succeeded.
Nov 27 07:29:37 grid systemd[1]: Started piVCCU DKMS Modules.
Nov 27 07:29:37 grid systemd[1]: Starting piVCCU...
Nov 27 07:29:37 grid kernel: [ 1736.782033] hb-rf-eth hb-rf-eth: Trying to connect to xx.xx.xx.32
Nov 27 07:29:38 grid kernel: [ 1736.891017] hb-rf-eth hb-rf-eth: Successfully connected to xx.xx.xx.32
Nov 27 07:29:38 grid kernel: [ 1736.964587] raw-uart raw-uart: Reset radio module
Nov 27 07:29:41 grid start_container.sh[6827]: kernel.sched_rt_runtime_us = -1
Nov 27 07:29:41 grid kernel: [ 1740.190855] br0: port 2(vethpivccu) entered blocking state
Nov 27 07:29:41 grid kernel: [ 1740.190970] br0: port 2(vethpivccu) entered disabled state
Nov 27 07:29:41 grid systemd-udevd[6835]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Nov 27 07:29:41 grid systemd-udevd[6835]: Using default interface naming scheme 'v240'.
Nov 27 07:29:41 grid systemd-udevd[6835]: Could not generate persistent MAC address for veth919NBG: No such file or directory
Nov 27 07:29:41 grid systemd-udevd[6833]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Nov 27 07:29:41 grid systemd-udevd[6833]: Using default interface naming scheme 'v240'.
Nov 27 07:29:41 grid kernel: [ 1740.191316] device vethpivccu entered promiscuous mode
Nov 27 07:29:41 grid networkd-dispatcher[801]: WARNING:Unknown index 10 seen, reloading interface list
Nov 27 07:29:41 grid kernel: [ 1740.273847] eth0: renamed from veth919NBG
Nov 27 07:29:41 grid systemd-networkd[448]: vethpivccu: Gained carrier
Nov 27 07:29:41 grid kernel: [ 1740.303812] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Nov 27 07:29:41 grid kernel: [ 1740.303934] IPv6: ADDRCONF(NETDEV_CHANGE): vethpivccu: link becomes ready
Nov 27 07:29:41 grid kernel: [ 1740.304104] br0: port 2(vethpivccu) entered blocking state
Nov 27 07:29:41 grid kernel: [ 1740.304110] br0: port 2(vethpivccu) entered forwarding state
Nov 27 07:29:41 grid systemd[1]: Started piVCCU.
Nov 27 07:29:41 grid systemd[1]: Started Monitor HB-RF-ETH.
Nov 27 07:29:41 grid kernel: [ 1740.603543] cp15barrier_handler: 40357 callbacks suppressed
Nov 27 07:29:41 grid kernel: [ 1740.603560] "java" (7191) uses deprecated CP15 Barrier instruction at 0xf7a618c8
Nov 27 07:29:41 grid kernel: [ 1740.603564] "java" (7191) uses deprecated CP15 Barrier instruction at 0xf7a618f0
Nov 27 07:29:41 grid kernel: [ 1740.607762] "java" (7191) uses deprecated CP15 Barrier instruction at 0xf7bd8890
Nov 27 07:29:41 grid kernel: [ 1740.607805] "java" (7191) uses deprecated CP15 Barrier instruction at 0xf7a3b5b0
Nov 27 07:29:41 grid kernel: [ 1740.607810] "java" (7191) uses deprecated CP15 Barrier instruction at 0xf7a3b5cc
Nov 27 07:29:41 grid kernel: [ 1740.607837] "java" (7191) uses deprecated CP15 Barrier instruction at 0xf7c9dca8
Nov 27 07:29:41 grid kernel: [ 1740.607841] "java" (7191) uses deprecated CP15 Barrier instruction at 0xf7c9dcc8
Nov 27 07:29:41 grid kernel: [ 1740.607845] "java" (7191) uses deprecated CP15 Barrier instruction at 0xf7c9dd58
Nov 27 07:29:43 grid avahi-daemon[790]: Joining mDNS multicast group on interface vethpivccu.IPv6 with address fe80::xxxx:xxxx:xxxx:xxxx.
Nov 27 07:29:43 grid avahi-daemon[790]: New relevant interface vethpivccu.IPv6 for mDNS.
Nov 27 07:29:43 grid systemd-networkd[448]: vethpivccu: Gained IPv6LL
Nov 27 07:29:43 grid avahi-daemon[790]: Registering new address record for fe80::xxxx:xxxx:xxxx:xxxx on vethpivccu.*.

**Comment by alexreinert** [comment]
Ein Fix für die barrier Meldungen ist bereits in Arbeit bzw. eigentlich schon fertig, aber in dem Release kommt noch etwas mehr Kleinkram mit, welchen ich erst noch komplett durchtesten muss (z.B. auch die fehlerhafte Meldung wg. dem raw-uart bei der Installation bei Verwendung der HB-RF-ETH)

**Comment by vigeland** [comment]
Wenn man fragen darf.
War es das tasklet_schedule oder das set_fs und hat der Kernel einen anderen len zurückgeliefert ?

**Comment by alexreinert** [comment]
Das set_fs ist bei aktueller Hardware nicht mehr nötig, es war früher bei x86 mal notwendig.
Irgendwas im Kernel hat dafür gesorgt, dass das Senden der UDP Pakete nicht im Kontext vom tx_chars nicht durch die Bridge weitergeleitet wurde. Durch das tasklet sorge ich indirekt dafür, dass das in deinem definierten Kontext ausgeführt wird. Theoretisch würde auch ein eigener Thread mit wait_queue funktionieren, aber ein tasklet hat eine höhere Prio und damit eine geringere Latenz.
Die Länge war von Anfang an nicht das Problem, das hatte ich ganz am Anfang schon mal geprüft, man konnte ja auch sehen, dass es auf der Bridge korrekt ankam, nur halt nicht weitergeleitet wurde.

**Comment by ebin-dev** [comment]
Mit den letzten Updates läuft auch alles wunderbar. Nochmals vielen Dank !
Ich schließe dann mal den Issue.
