### ISSUE TITLE
HMIP hardware wird nach update nicht mehr erkannt.

### ISSUE THREAD

**Issue by flow23** [alexreinert/piVCCU#325]
Hi,

habe ein Update mittels apt-get upgrade durchgeführt und neugestartet.
Leider wird meine Hardware nun nicht mehr erkannt.
Kannst du weiterhelfen?

pi@raspberrypi:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

pi@raspberrypi:~ $ sudo pivccu-info 
piVCCU version: 3.47.10-28
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  FAKE_HMRF
HMIP Hardware:  unknown
Board serial:   FKE2690736
Radio MAC:      0xab1dab
SGTIN:          3014F711A061A7D5699DAB52
State:          RUNNING
PID:            769
IP:             10.0.1.219
CPU use:        17.82 seconds
Link:           vethpivccu
 TX bytes:      36.43 KiB
 RX bytes:      170.65 KiB
 Total bytes:   207.08 KiB

pi@raspberrypi:~ $ sudo pivccu-attach cat /var/log/messages
Nov 28 13:00:44 piVCCU syslog.info syslogd started: BusyBox v1.29.2
Nov 28 13:00:44 piVCCU user.notice kernel: klogd started: BusyBox v1.29.2 (2019-06-21 09:16:48 CEST)
Nov 28 13:00:46 piVCCU syslog.info syslogd exiting
Nov 28 13:00:46 ccu3-webui syslog.info syslogd started: BusyBox v1.29.2
Nov 28 13:00:46 ccu3-webui user.notice kernel: klogd started: BusyBox v1.29.2 (2019-06-21 09:16:48 CEST)
Nov 28 13:00:46 ccu3-webui daemon.err udhcpc[182]: started, v1.29.2
Nov 28 13:00:46 ccu3-webui daemon.err udhcpc[182]: sending discover
Nov 28 13:00:47 ccu3-webui daemon.err udhcpc[182]: sending select for 10.0.1.219
Nov 28 13:00:47 ccu3-webui daemon.err udhcpc[182]: lease of 10.0.1.219 obtained, lease time 86400
Nov 28 13:00:48 ccu3-webui user.info firewall: iptables v1.6.2: invalid port/service `310000' specified Try `iptables -h' or 'iptables --help' for more information.
Nov 28 13:00:48 ccu3-webui user.info firewall: ip6tables v1.6.2: invalid port/service `310000' specified Try `ip6tables -h' or 'ip6tables --help' for more information.
Nov 28 13:00:48 ccu3-webui user.info firewall: configuration set
Nov 28 13:00:48 ccu3-webui daemon.info ifplugd(eth0)[287]: ifplugd 0.28 initializing.
Nov 28 13:00:48 ccu3-webui daemon.info ifplugd(eth0)[287]: Using interface eth0/2A:5E:35:7A:6F:A7 with driver <veth> (version: 1.0)
Nov 28 13:00:48 ccu3-webui daemon.info ifplugd(eth0)[287]: Using detection mode: SIOCETHTOOL
Nov 28 13:00:48 ccu3-webui daemon.info ifplugd(eth0)[287]: Initialization complete, link beat detected.
Nov 28 13:00:48 ccu3-webui daemon.warn ifplugd(eth0)[287]: Could not open /dev/tty, cannot beep.
Nov 28 13:00:48 ccu3-webui daemon.info ifplugd(eth0)[287]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
Nov 28 13:00:48 ccu3-webui daemon.warn ifplugd(eth0)[287]: client: ifup: interface eth0 already configured
Nov 28 13:00:48 ccu3-webui daemon.info ifplugd(eth0)[287]: Program executed successfully.
Nov 28 13:00:57 ccu3-webui daemon.notice ntpdate[295]: step time server 131.188.3.220 offset -0.456006 sec
Nov 28 13:00:57 ccu3-webui daemon.notice ntpd[296]: ntpd 4.2.8p12@1.3728-o Fri Jun 21 07:15:18 UTC 2019 (1): Starting
Nov 28 13:00:57 ccu3-webui daemon.info ntpd[296]: Command line: /usr/sbin/ntpd -g 0.de.pool.ntp.org 1.de.pool.ntp.org 2.de.pool.ntp.org 3.de.pool.ntp.org
Nov 28 13:00:57 ccu3-webui daemon.info ntpd[298]: proto: precision = 0.417 usec (-21)
Nov 28 13:00:57 ccu3-webui daemon.info ntpd[298]: Listen and drop on 0 v6wildcard [::]:123
Nov 28 13:00:57 ccu3-webui daemon.info ntpd[298]: Listen and drop on 1 v4wildcard 0.0.0.0:123
Nov 28 13:00:57 ccu3-webui daemon.info ntpd[298]: Listen normally on 2 lo 127.0.0.1:123
Nov 28 13:00:57 ccu3-webui daemon.info ntpd[298]: Listen normally on 3 eth0 10.0.1.219:123
Nov 28 13:00:57 ccu3-webui daemon.info ntpd[298]: Listen normally on 4 lo [::1]:123
Nov 28 13:00:57 ccu3-webui daemon.info ntpd[298]: Listening on routing socket on fd #21 for interface updates
Nov 28 13:00:57 ccu3-webui daemon.info ntpd[298]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
Nov 28 13:00:57 ccu3-webui daemon.info ntpd[298]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
Nov 28 13:00:57 ccu3-webui daemon.err xinetd[317]: Unable to read included directory: /etc/config/xinetd.d [file=/etc/xinetd.conf] [line=14]
Nov 28 13:00:57 ccu3-webui daemon.crit xinetd[317]: 317 {init_services} no services. Exiting...
Nov 28 13:00:57 ccu3-webui user.info root: Updating RF Lan Gateway Coprocessor Firmware
Nov 28 13:00:57 ccu3-webui user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
Nov 28 13:00:57 ccu3-webui user.info root: Updating RF Lan Gateway Firmware
Nov 28 13:00:57 ccu3-webui user.info update-lgw-firmware: No gateway found in config file /etc/config/rfd.conf
Nov 28 13:00:59 ccu3-webui user.info kernel: [   39.697520] eq3loop: eq3loop_open_slave() mmd_bidcos
Nov 28 13:06:11 ccu3-webui local0.err ReGaHss: ERROR: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [error():iseXmlRpc.h:281]
Nov 28 13:06:11 ccu3-webui local0.warn ReGaHss: WARNING: XMLRPC 'init': rpcClient.execute() failed (url: xmlrpc://127.0.0.1:39292/groups, params: {"xmlrpc_bin://127.0.0.1:31999","1008"}, result: nil) [CallXmlrpcMethod():iseXmlRpc.cpp:2602]
Nov 28 13:06:11 ccu3-webui local0.err ReGaHss: ERROR: XMLRPC 'init' call failed (interface: 1008, params: {"xmlrpc_bin://127.0.0.1:31999","1008"}) [CallInit():iseXmlRpc.cpp:1204]
Nov 28 13:06:11 ccu3-webui local0.err ReGaHss: ERROR: failed CallInit() for interface=VirtualDevices [ThreadFunction():iseRTHss.cpp:163]
Nov 28 13:06:11 ccu3-webui local0.err ReGaHss: ERROR: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [error():iseXmlRpc.h:281]
Nov 28 13:06:11 ccu3-webui local0.warn ReGaHss: WARNING: XMLRPC 'init': rpcClient.execute() failed (url: xmlrpc://127.0.0.1:32010, params: {"xmlrpc_bin://127.0.0.1:31999","1009"}, result: nil) [CallXmlrpcMethod():iseXmlRpc.cpp:2602]
Nov 28 13:06:11 ccu3-webui local0.err ReGaHss: ERROR: XMLRPC 'init' call failed (interface: 1009, params: {"xmlrpc_bin://127.0.0.1:31999","1009"}) [CallInit():iseXmlRpc.cpp:1204]
Nov 28 13:06:11 ccu3-webui local0.err ReGaHss: ERROR: failed CallInit() for interface=HmIP-RF [ThreadFunction():iseRTHss.cpp:163]

pi@raspberrypi:~ $ sudo pivccu-attach cat /etc/config/rfd.conf
# TCP Port for XmlRpc connections
Listen Port = 32001

Log Destination = Syslog
Log Identifier = rfd
Log Level = 1

Persist Keys = 1

# PID File = /var/rfd.pid
# UDS File = /var/socket_rfd

Device Description Dir = /firmware/rftypes
Device Files Dir = /etc/config/rfd
Key File = /etc/config/keys
Address File = /etc/config/ids
Firmware Dir = /firmware
Replacemap File = /firmware/rftypes/replaceMap/rfReplaceMap.xml
Fire NACK Error Events = true
Improved Coprocessor Initialization = true

[Interface 0]
Type = CCU2
ComPortFile = /dev/mmd_bidcos
#AccessFile = /dev/null
#ResetFile = /dev/ccu2-ic200

Nov 28 13:01:14 de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization ERROR [vert.x-eventloop-thread-7] Error 'LOCAL_ADAPTER_NO_SUCH_PORT' while trying to open port '/dev/mmd_hmip': 
de.eq3.cbcs.lib.commdevice.CommDeviceException: Exception while trying to open serial port. Check configured port '/dev/mmd_hmip'
	at de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice.open(SerialCommDevice.java:105)
	at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.open(HomeMaticIPTRXCommAdapter.java:727)
	at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.<init>(HomeMaticIPTRXCommAdapter.java:98)
	at de.eq3.cbcs.server.local.base.internal.ShareableHomeMaticIPTRXCommAdapter.<init>(ShareableHomeMaticIPTRXCommAdapter.java:20)
	at de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization.start(LocalServerAdapterInitialization.java:177)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: gnu.io.NoSuchPortException
	at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:294)
	at de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice.open(SerialCommDevice.java:96)
	... 12 more
Nov 28 13:01:14 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-7] SYSTEM: start of AccessPointAuthorisationHandler succeeded (c6622d38-3686-44f6-9048-9844bc800f02) 
Nov 28 13:01:14 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-4] SYSTEM: start of LocalServerAdapterInitialization succeeded (784d50c8-0943-4af4-87d5-74d0d7a77688) 
Nov 28 13:01:15 de.eq3.cbcs.lib.remotecommadapter.AccessPointCommDevice INFO  [vert.x-eventloop-thread-6] SYSTEM: Started Access Point WebSocket server with port 9293 
Nov 28 13:01:15 de.eq3.cbcs.lib.remotecommadapter.AccessPointCommDevice INFO  [vert.x-eventloop-thread-6] SYSTEM: connector open 
Nov 28 13:01:17 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Nov 28 13:01:18 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: pre-conditions for deployment of LanRoutingWorker still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Nov 28 13:01:18 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-3] SYSTEM ADVICE: pre-conditions for deployment of LegacyBackendNotificationHandler still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Nov 28 13:01:18 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-7] SYSTEM ADVICE: pre-conditions for deployment of LegacyNotificationHandler still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Nov 28 13:01:18 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-2] SYSTEM ADVICE: pre-conditions for deployment of LegacyAPIWorker still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Nov 28 13:01:18 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-4] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [legacy.api.worker][connector.open]) 
Nov 28 13:01:24 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: long-lasting deployment, check deployment configuration - currently deployed 26 out of 32 
Nov 28 13:01:24 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Nov 28 13:01:25 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: pre-conditions for deployment of LanRoutingWorker still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Nov 28 13:01:25 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-3] SYSTEM ADVICE: pre-conditions for deployment of LegacyBackendNotificationHandler still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Nov 28 13:01:25 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-7] SYSTEM ADVICE: pre-conditions for deployment of LegacyNotificationHandler still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Nov 28 13:01:25 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-2] SYSTEM ADVICE: pre-conditions for deployment of LegacyAPIWorker still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Nov 28 13:01:25 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-4] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [legacy.api.worker][connector.open]) 
Nov 28 13:01:31 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Nov 28 13:01:32 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: pre-conditions for deployment of LanRoutingWorker still not met - check deployment configuration  (still unfulfilled: [connector.open])

**Comment by alexreinert** [comment]
Für Updates bitte wie in der Doku apt verwenden und nicht apt-get. So alt, wie die Installation ist, sollte danach dann auch ein Neustart gemacht werden, da ist garantiert auch ein Kernel Update fällig gewesen.

Welche Hardware wird verwendet?

**Comment by flow23** [comment]
Super,
hat geholfen.
Danach hat es gereicht den Service durchzustarten.
Leider starten alle Heizungen jetzt auf AUS anstatt auf AN und AUTO nach jedem Neustart.
Eine Idee?

Hardware ist das Modul RPI-RF-MOD mit Rapsberry Pi 3+.

**Comment by alexreinert** [comment]
Das ist ein alt bekanntes Problem im Closed Source von eQ-3. Die CCU merkt sich bei einem Neustart nicht die aktuellen Werte von HmIP Geräten. Sobald die Geräte sich wieder bei der CCU melden, korrigiert sich die Anzeige. Das kann entwederbei einer Aktion am Gerät sein oder über die zyklischen Meldungen.
