### ISSUE TITLE
PIVCCU3 frisch auf RaspPI4 nach Backup laden nicht mehr aufzurufen

### ISSUE THREAD

**Issue by lioncar2000** [alexreinert/piVCCU#326]
Hallo,
habe die pivCCU3 frisch auf einem PI4 4GB installiert. Hat alles super geklaptt.

Dann habe ich mein Backup laden wollen und danach war die pivCCU3 nicht mehr über die IP4 Adress zu erreichen.

Nach Prüfung des PIVCCU Status über "sudo pivcuu-info" kam:

`pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.53.34-49
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Board serial:  PEQ0530411
 Radio MAC:     0x6A63E6
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7D8A9917FEB
 Radio MAC:     0xBC15C2
State:          RUNNING
PID:            910
IP:             2a02:908:1c17:d400:c81a:86ff:feb5:f054
CPU use:        1.68 seconds
BlkIO use:      38.11 MiB
Link:           vethpivccu
 TX bytes:      602 bytes
 RX bytes:      5.28 KiB
 Total bytes:   5.87 KiB
pi@raspberrypi:~ $ `

Unter IP steht nun plötzlich eine IPV6, wo vorher eine IPV4 stand!?!?
Die PIVCUU scheint schon mit dem Update zu laufen, denn Aktoren reagieren schon!

Hoffe auf Eure Hilfe.

Gruß
Timo

**Comment by alexreinert** [comment]
Woher stammt das Backup? Läuft das Gerät vielleicht noch, von dem das Backup stammt? Ist der DHCP Server erreichbar? War der Pi beim starten mit dem Netzwerk verbunden? Was liefert `sudo brctl show`?

**Comment by lioncar2000** [comment]
Ja, es läuft zurzeit pivccu in der Version 3.47.10 auf einem PI3 mit 1GB. Aber nicht parallel, soabld der neue getestet wird.
Vor dem einspielen des Backup auf den neuen PI4 4GB lief die aktuelle PIVCCU einwandfrei (komplette jungfreuliche Installation mit Buster lite, IOBroker und PIVCCU in aktueller Version. Ohne Neustart o.ä. wurde "nur" das Backup was auf oben genanten PI3 erstellt wurde, eingespielt. Dann klappte das wiederanmelden an der PIVCCU nicht, sodass nur ein Neustart bieb!? Danach das Phänomen! LAN war verbunden, DHCP lief.

alles IO (direkt nach Neuinstallation:
`pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.53.34-49
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Board serial:  PEQ0530411
 Radio MAC:     0x6A63E6
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7D8A9917FEB
 Radio MAC:     0xBC15C2
State:          RUNNING
PID:            1975
IP:             192.168.178.46
CPU use:        16.02 seconds
BlkIO use:      148.00 KiB
Link:           vethpivccu
 TX bytes:      13.74 KiB
 RX bytes:      48.59 KiB
 Total bytes:   62.33 KiB
pi@raspberrypi:~ $ sudo brctl show
bridge name     bridge id               STP enabled     interfaces
br0             8000.dca632de6e84       no              eth0
                                                        vethpivccu
pi@raspberrypi:~ $`

nachdem das Backup eingespielt wurde:
`pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.53.34-49
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Board serial:  PEQ0530411
 Radio MAC:     0x6A63E6
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7D8A9917FEB
 Radio MAC:     0xBC15C2
State:          RUNNING
PID:            4003
IP:             2a02:908:1c17:d400:c81a:86ff:feb5:f054
CPU use:        12.48 seconds
BlkIO use:      112.00 KiB
Link:           vethpivccu
 TX bytes:      602 bytes
 RX bytes:      16.72 KiB
 Total bytes:   17.30 KiB
pi@raspberrypi:~ $ sudo brctl show
bridge name     bridge id               STP enabled     interfaces
br0             8000.dca632de6e84       no              eth0
                                                        vethpivccu
pi@raspberrypi:~ $`

Ohne Neustart zwischendurch

**Comment by alexreinert** [comment]
Ist eine feste IP in der CCU eingerichtet, aus welcher das Backup stammt?
Die Ausgabe bitte nochmal mit den originalen Zeilenumbruchen, die Ausgabe von brctl ist so nicht eindeutig.

**Comment by lioncar2000** [comment]
Habe der FritzBox gesagt das immer dieselbe IP verwendet werden soll.

In den CUU in den Netzwerkeinstellungen ist in den:
1. IP Einstellungen: der Hostname = "ccu3-webui", Haken für "folgende IP-Adresse verwenden" ist deaktiviert.
2. Zertifikat erstellen: Dort ist im Hostnamen die IP eingetragen!?
Kann das der Grund sein? 

`pi@raspberrypi:~ $ sudo pivccu-info`
`piVCCU version: 3.53.34-49 `
`Kernel modules: Available`
`UART dev: Available Rasp.Pi`
`UART: Assigned to GPIO pins`
`HMRF Hardware: HM-MOD-RPI-PCB`
`Board serial: PEQ0530411`
`Radio MAC: 0x6A63E6`
`HMIP Hardware: HM-MOD-RPI-PCB`
`SGTIN: 3014F711A061A7D8A9917FEB`
`Radio MAC: 0xBC15C2`
`State: RUNNING`
`PID: 4003`
`IP: 2a02:908:1c17:d400:c81a:86ff:feb5:f054`
`CPU use: 12.48 seconds`
`BlkIO use: 112.00 KiB`
`Link: vethpivccu`
`TX bytes: 602 bytes`
`RX bytes: 16.72 KiB`
`Total bytes: 17.30 KiB`
`pi@raspberrypi:~ $ sudo brctl show`
`bridge name bridge id STP enabled interfaces br0 8000.dca632de6e84 no eth0 vethpivccu`
`pi@raspberrypi:~ $`

**Comment by alexreinert** [comment]
Bitte 15 Minuten nach einem Neustart die Ausgabe folgender Befehle hier posten:
```
sudo pivccu-attach cat /var/log/messages
sudo pivccu-attach cat /etc/config/netconfig
sudo pivccu-attach ifconfig
sudo pivccu-attach ls -la /var/status/hasLink
sudo pivccu-attach ls -la /var/status/hasInternet
sudo pivccu-attach ls -la /var/status/hasIP
```

**Comment by lioncar2000** [comment]
Hallo Alex,

ich bin den Weg nicht mehr gegangen, da mein PI4 einmal frisch ohne Probleme lief und ich krampfhaft versucht habe meinen alten PI3 bzw. die CCU dadrauf zum laufen zu krriegen. Thema Downgrade. Außerdem dachte ich mir, das eine komplette frische Neueinrichtung vielleicht das Beste ist...

Wenn mein neuer PI4 komplett fertig ist, werde ich das aber nochmal machen, denn dann habe ich eine SD Karte über..
So kann ich die jetzt laufende SD mit dem Image drauf unberührt lassen.
