### ISSUE TITLE
pivccu not working after upgrade - Firmware 1098, kernel 4.9.80, rpi

### ISSUE THREAD

**Issue by Buzz2912** [alexreinert/piVCCU#33]
Hi,

habe eben ein dist-upgrade durchgeführt. Dabei wurde der Kernel und die Firmware des RPI aktualisiert. Die Pivccu startet nicht mehr.

Kernel version: Linux 4.9.80-v7+ armv7l

Firmware: #1098

sudo pivccu-info
piVCCU version: 2.31.25-23
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi3 UART:  Assigned to GPIO pins
Board serial:   Unknown
State:          STOPPED

Ein forced reinstall der kernel modules brachte keine Besserung.

Gruss Sebastian 

P.S.: Danke für pivccu! Funktioniert super!

**Comment by alexreinert** [comment]
Versuch mal
sudo apt update && sudo apt upgrade
(apt ohne -get)

**Comment by Buzz2912** [comment]
Habs nochmal mit einem Backup Image probiert. Macht keinen Unterschied.
Das passiert während des Upgrades:
Vorbereitung zum Entpacken von .../22-raspberrypi-kernel_1.20180313-1_armhf.deb ...
run-parts: executing /etc/kernel/prerm.d/dkms 4.9.59+ /boot/kernel.img
/etc/kernel/prerm.d/dkms:
dkms: removing: pivccu 1.0.9 (4.9.59+) (armv7l)

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.9
Kernel:  4.9.59+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod....

DKMS: uninstall completed.
run-parts: executing /etc/kernel/prerm.d/dkms 4.9.59-v7+ /boot/kernel7.img
/etc/kernel/prerm.d/dkms:
dkms: removing: pivccu 1.0.9 (4.9.59-v7+) (armv7l)

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.9
Kernel:  4.9.59-v7+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59-v7+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59-v7+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59-v7+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59-v7+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59-v7+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.59-v7+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod....

DKMS: uninstall completed.

------------------------------
Deleting module version: 1.0.9
completely from the DKMS tree.
------------------------------
Done.


Danach funktioniert nach reboot keine pivccu.
Habe dann pivccu deinstalliert inkl. Kernel-modules.

Nach Neuinstallation pivccu läuft wieder alles.

Gruss Sebastian

**Comment by alexreinert** [comment]
Es ist vollkommen normal, dass bei der Deinstallation des bisherigen Kernels auch die Kernel Module für diesen Kernel entfernt werden. Das ist normales Verhalten bei Kernel Modulen, welche über DKMS bereitgestellt werden.
Spätestens beim nächsten Neustart läuft aber normalerweise per systemd service pivccu-dkms ein Skript, welches bei Bedarf die Module für einen neuen Kernel baut.
Alternativ kann man dies auch manuell antriggern, indem man `sudo dpkg-reconfigure pivccu-modules-dkms` ausführt.
Ich habe das grade auch nochmal mit einem alten Raspbian Image durchgespielt: Beim Update des Kernels werden die Module entfernt, nach dem Reboot ist alles einwandfrei am Laufen. Ich bekomme dein Problem also nicht nachgestellt.
