### ISSUE TITLE
pivCCU3 mit HMIP-RF-USB - Anlernen funktioniert nicht

### ISSUE THREAD

**Issue by jasmin2509** [alexreinert/piVCCU#330]
Moin zusammen,
ich habe auf einem Raspberry Pi 4B pivCCU3 installiert und einen HMIP-RF-USB angeschlossen. Die Ausgabe von sudo pivccu-info sieht wie folgt aus:
```
piVCCU version: 3.53.34-49
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  FAKE_HMRF
 Connected via:  (/dev/)
 Board serial:  FKE3166372
 Radio MAC:     0xffad16
HMIP Hardware:  HMIP-RFUSB
 SGTIN:         3014F711A000041BE99B37CA
 Radio MAC:     0xB27D80
State:          RUNNING
PID:            1844
IP:             192.168.178.50
CPU use:        471.16 seconds
BlkIO use:      62.27 MiB
Link:           vethpivccu
 TX bytes:      15.31 MiB
 RX bytes:      17.88 MiB
 Total bytes:   33.19 MiB
```

Das klingt für mich, als ob der Stick soweit erkannt wird und alles gut ist. In der Weboberfläche taucht er bei Geräten aber nicht auf. Ich bin ehrlich gesagt totaler Anfänger bzgl. Homematic und weiß daher nicht, wie und ob der Stick da normalerweise auftauchen sollte. Aber das Anlernen von meinen HMIP Geräten (verschiedene Geräte, HmIP-SWDM, eTRV-B, BROLL etc.) funktioniert weder über das automatische Anlernen noch über KEY und SGTIN. Kann mir jemand helfen? Wie kann ich testen, ob der RF-USB wirklich funktioniert? Eventuell sind da noch Treiber notwendig o.Ä., aber ich weiß gar nicht wirklich von ich mit debuggen anfangen soll...

Danke schonmal!

**Comment by alexreinert** [comment]
Der Stick wird korrekt erkannt, sonst könntest du auch gar nicht das Anlernen auf der Weboberfläche starten. Wie lernst du die Geräte genau an, häufig wird das falsch gemacht.

Korrektes Vorgehen:
- Werksreset vom anyulernenden Gerät (auch wenn es frisch geliefert wurde)
- Gerät vom Strom trennen bzw. Batterien rausnehmen
- Anlernmodus in der CCU starten
- Stromversorgung wiederherstellen
- Warten, nichts am Gerät drücken, nichts in der Weboberfläche klicken
- Nach Ablauf der 30 Sekunden in den Posteingang wechseln

**Comment by jasmin2509** [comment]
Vielen Dank schon mal für die super schnelle Antwort. Na das ist ja schon mal was, wenn der Stick funktioniert. Leider habe ich das mit dem Anlernen auch schon gelesen gehabt und auch genauso ausprobiert. Eben nochmal mit zwei Fenstersensoren. Werksreset (Batterie raus, 4 Sek Knopf, loslassen, 4 Sek. Knopf > grüne LED zeigt, dass es geklappt hat, anschließend startet der Sensor neu), Batterie raus, Anlernmodus starten (bei mir 60 Sekunden, nicht 30 Sekunden?), Batterie rein. Nach 60 Sekunden, Posteingang immer noch leer... Ich werde wohl mal alle anderen Geräte auch durchprobieren müssen... Aber an dem Stick/der CCU Installation kann es nicht liegen, ja? Definitiv Anwenderfehler bzw. Problematik am Endgerät?

**Comment by alexreinert** [comment]
Es kann auch am Stick liegen: Wenn die Lötstellen zum Funkmodul innerhalb des Sticks nicht passen, dann wird ein Anlernen (und auch sämtliche andere Funkkommunikation) nicht klappen. Leider "informiert" der Stick aber nicht über dieses Problem. Es macht also Sinn, die Lötverbindungen nochmals zu prüfen, gerne kann auch hier ein Bild gepostet werden.

**Comment by jasmin2509** [comment]
Tatsächlich habe ich den Stick ziemlich unsauber gelötet, da ich es eilig hatte. Ich sehe zwar keine fehlenden Verbindungen, aber ich gehe da nochmal in Ruhe ran und mache es schön :-) Danke auf jeden Fall schonmal, ich melde mich nochmal (dann auch mit Foto, so ist etwas peinlich) falls es dann immer noch nicht geht.

Viele Grüße

**Comment by alexreinert** [comment]
Gibt es irgendeine neue Erkenntnis?

**Comment by jasmin2509** [comment]
Hi, danke der Nachfrage. Leider kam ich erst gestern Abend dazu es wieder zu versuchen. Mit negativem Ergebnis, ich habe die Lötstellen nochmal kontrolliert und etwas sauberer gearbeitet, das Ergebnis bleibt dasselbe. Ich habe es mit dem Unterputz-Rolladenaktor, drei verscheidenen Fensterkontakten und einem Thermostat versucht - alle auf Werkeinstellungen zurückgesetzt und dann exakt die genannten Schritte befolgt (außer, dass ich den Rolladenschalter nicht vom Strom getrennt habe - alle anderen Geräte aber schon) - mit dem Ergebnis, dass der Posteingang leer bleibt. Auch über SGTIN und Key habe ich es bei zwei Geräten versucht - ohne Ergebnis. Ich bin ein wenig am Verzweifeln, da ich einfach auch nicht weiß, was ich noch versuchen soll :-(

**Comment by alexreinert** [comment]
Könntest du vielleicht ein Bild posten?

**Comment by jasmin2509** [comment]
![IMG_20201208_113847](https://user-images.githubusercontent.com/7899264/101632834-b97bd200-3a26-11eb-9724-b3db6552ac70.jpg)
![IMG_20201208_113908](https://user-images.githubusercontent.com/7899264/101632841-baacff00-3a26-11eb-9c4d-a31ec10257b1.jpg)

**Comment by alexreinert** [comment]
Mind. die äußeren Pins solltest du nochmal nacharbeiten. Das sind Gnd und VCC und die haben für mich das Potential für eine kalte Lötstelle.

**Comment by jasmin2509** [comment]
Alles klar, mache ich nochmal. Habe leider nur eine ziemlich dicke Lötspitze parat, deshalb gestaltet sich das als nicht so einfach :-) Aber ich geb mein bestes. Allerdings habe ich echt genau hingeschaut und bin eigentlich ziemlich sicher, dass da überall Kontakt ist. Naja, ich arbeite die Tage nochmal nach und melde mich. Du scheinst ja ziemlich sicher zu sein, dass hier das Problem liegt.

**Comment by T1mey** [comment]
Habe ein ähnliches Problem. Aber mit dem HM-MOD-RPI-PCB.
Alle nicht IP Geräte funktionieren und können angelernt werden. 

Allesdings bekomme ich keinen HM IP Dimmer angelernt. 
Konnte ihn auch nicht in einem Backup bedienen,. (da war er schonmal angelernt)

Bin auf 3.53.34 über das vorgefertigte Image.

**Comment by petervflocke** [comment]
@jasmin2509 

Did you mange to get it running? I have the same issue on my home assistant with a rasberrymatic docker.
The stick works fine on RPI 3 and in a virtual box. It stops working when I try to use it on RPI4.

Regards
Peter

**Comment by jasmin2509** [comment]
Nope, unfortunality not :-( gave up after several days... Sorry.

petervflocke ***@***.***> schrieb am Mi., 15. Dez. 2021,
20:31:

**Comment by petervflocke** [comment]
> Nope, unfortunality not :-( gave up after several days... Sorry.

Thanks for your quick response - that's so ..... frustrating. I just did not want to have another device just for a few HomeMatic devices and HA with Docker looked so promising. 

Anyway, thx & take care!
Cheers
Peter

**Comment by jasmin2509** [comment]
Yepp, that's what I thought, too... If you find a solution, I would be very
thankful if you could share it!
Have a good day and good luck :-)

Regards
Jasmin

petervflocke ***@***.***> schrieb am Mi., 15. Dez. 2021,
20:37:
