### ISSUE TITLE
Question: Can I easily switch from HM-MOD-RPI-PCB to RPI-RF-MOD without a change?

### ISSUE THREAD

**Issue by dm82m** [alexreinert/piVCCU#335]
Hey guys,

again: thank you very much for all this!

I am using pivccu more than a year now. Started with the HM-MOD-RPI-PCB. The last couple of days I was adding a few more HomematicIP devices in my basement and having connection issues there. So initially I thought about replacing the antenna but I also read that it is not allowed due to laws. So I ordered the RPI-RF-MOD and want to switch to it shortly. The description says, that the new transmitter is having a better range. Hope that is true and works for me.

Now the question: can I just shutdown my PI, remove the HM-MOD-RPI-PCB and add the RPI-RF-MOD, start the system again and thats it? Cause "sudo dpkg-reconfigure pivccu3" is just giving me both of them in a single entry - so no need to decide between either or.

And a last question: If I try to access the RSSI list it just shows an empty list:
![image](https://user-images.githubusercontent.com/736311/101599634-5b38fa00-39fa-11eb-9207-d90a97bfa8f6.png)
Any idea what is happening here? Would be great to see the connection strength to my devices, just to make sure that the switch from HM-MOD-RPI-PCB to RPI-RF-MOD is giving me better connection.

Best,
Dirk

**Comment by alexreinert** [comment]
You can just switch the radio modules. For HmIP devices there is a need of a key exchange, which will run automatically in the backgroud. This key exchange requires internet access to the eQ-3 key servers and depending on the count of devices, it could take several hours. You should not restart in this time.

The RSSI shows only BidCos devices and not HmIP devices.

**Comment by dm82m** [comment]
Thank you @alexreinert once more!
