### ISSUE TITLE
FATAL: Module rpi_rf_mod_led not found in directory /lib/modules/5.4.79-v7+

### ISSUE THREAD

**Issue by ladidadida** [alexreinert/piVCCU#336]
Ich habe vorhin das aktuelle pivccu3 update auf meine Pi aufgespielt. Leider läuft seitdem die CCU nicht mehr an.
Folgendes habe ich auf die Schnelle herausgefunden.

**sudo service pivccu status**
Dez 09 22:11:03 raspberrypi start_container.sh[5445]: <12>Dec  9 22:11:03 piVCCU3: HMIP hardware was not detected
Dez 09 22:11:03 raspberrypi start_container.sh[5445]: modprobe: FATAL: Module rpi_rf_mod_led not found in directory /lib/modules/5.4.79-v7+
Dez 09 22:11:04 raspberrypi start_container.sh[5445]: kernel.sched_rt_runtime_us = -1
Dez 09 22:11:05 raspberrypi start_container.sh[5445]: lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 842 Received container state "ABORTING" instead of "RUNNING"
Dez 09 22:11:05 raspberrypi start_container.sh[5445]: lxc-start: lxc: tools/lxc_start.c: main: 330 The container failed to start
Dez 09 22:11:05 raspberrypi start_container.sh[5445]: lxc-start: lxc: tools/lxc_start.c: main: 333 To get more details, run the container in foreground mode
Dez 09 22:11:05 raspberrypi start_container.sh[5445]: lxc-start: lxc: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfile and --logpriority options
Dez 09 22:11:05 raspberrypi systemd[1]: Started piVCCU.
Dez 09 22:11:05 raspberrypi systemd[1]: pivccu.service: Main process exited, code=exited, status=1/FAILURE
Dez 09 22:11:05 raspberrypi systemd[1]: pivccu.service: Failed with result 'exit-code'.

**sudo pivccu3-info**
piVCCU version: 3.53.34-51
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
State:          STOPPED

Kann ich sonst noch etwas herausfinden?

**Comment by alexreinert** [comment]
Ich vermute mal, das mit dem Update auch ein neuer Kernel und neue Kernel Header kamen? In dem Fall muss ein Reboot gemacht werden. Ist dieser erfolgt?

**Comment by ladidadida** [comment]
Mittlerweile habe ich mehrer reboots gemacht. Mit dem Kernel hast du aber recht. Es waren gleich einige Updates.

Kernel ist jetzt: 
Linux raspberrypi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux

**Comment by alexreinert** [comment]
Und was liefert `sudo pivccu-info` jetzt?

**Comment by ladidadida** [comment]
piVCCU version: 3.53.34-51
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
State:          STOPPED

**Comment by ladidadida** [comment]
● pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-12-09 23:06:42 CET; 22s ago
  Process: 19026 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, status=0/SUCCESS)
 Main PID: 19209 (code=exited, status=1/FAILURE)

Dez 09 23:06:41 raspberrypi start_container.sh[19026]: <12>Dec  9 23:06:41 piVCCU3: HMIP hardware was not detected
Dez 09 23:06:41 raspberrypi start_container.sh[19026]: modprobe: FATAL: Module rpi_rf_mod_led not found in directory /lib/modules/5.4.79-v7+
Dez 09 23:06:42 raspberrypi start_container.sh[19026]: kernel.sched_rt_runtime_us = -1
Dez 09 23:06:42 raspberrypi start_container.sh[19026]: lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 842 Received container state "ABORTING" i
Dez 09 23:06:42 raspberrypi start_container.sh[19026]: lxc-start: lxc: tools/lxc_start.c: main: 330 The container failed to start
Dez 09 23:06:42 raspberrypi start_container.sh[19026]: lxc-start: lxc: tools/lxc_start.c: main: 333 To get more details, run the container in foreground m
Dez 09 23:06:42 raspberrypi start_container.sh[19026]: lxc-start: lxc: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the 
Dez 09 23:06:42 raspberrypi systemd[1]: Started piVCCU.
Dez 09 23:06:42 raspberrypi systemd[1]: pivccu.service: Main process exited, code=exited, status=1/FAILURE
Dez 09 23:06:42 raspberrypi systemd[1]: pivccu.service: Failed with result 'exit-code'.

**Comment by alexreinert** [comment]
Was liefert `sudo dpkg-reconfigure pivccu-modules-dkms`? Falls da ein Logfile genannt wird, dann bitte auch den Inhalt davon.

**Comment by ladidadida** [comment]
sudo dpkg-reconfigure pivccu-modules-dkms
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.51
Kernel:  5.4.79+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_eth.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb-2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79+/kernel/drivers/pivccu/
rmdir: konnte Verzeichnis 'kernel/drivers' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod.....

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.51
Kernel:  5.4.79-v7+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_eth.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb-2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/
rmdir: konnte Verzeichnis 'kernel/drivers' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod.....

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.51
Kernel:  5.4.79-v7l+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_eth.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb-2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte 'kernel/drivers/pivccu' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.79-v7l+/kernel/drivers/pivccu/
rmdir: konnte Verzeichnis 'kernel/drivers' nicht entfernen: Das Verzeichnis ist nicht leer
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod.....

DKMS: uninstall completed.

------------------------------
Deleting module version: 1.0.51
completely from the DKMS tree.
------------------------------
Done.

Creating symlink /var/lib/dkms/pivccu/1.0.51/source ->
                 /usr/src/pivccu-1.0.51

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=5.4.79-v7+ ARCH=arm all..........
cleaning build area...

DKMS: build completed.

dummy_rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

dw_apb_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

eq3_char_loop.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

fake_hmrf.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

generic_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

hb_rf_eth.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

hb_rf_usb-2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

hb_rf_usb.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

led_trigger_timer.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

meson_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

pl011_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

plat_eq3ccu2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

rpi_rf_mod_led.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

rtc-rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.79-v7+/kernel/drivers/pivccu/

depmod...

DKMS: install completed.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.

**Comment by ladidadida** [comment]
sudo pivccu-info
piVCCU version: 3.53.34-51
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  OEQ2299984
 Radio MAC:     0x651773
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7D709AC8050
 Radio MAC:     0xBD816B
State:          RUNNING
PID:            811
IP:             192.168.178.13
CPU use:        1.24 seconds
Link:           vethpivccu
 TX bytes:      4.92 KiB
 RX bytes:      10.88 KiB
 Total bytes:   15.80 KiB

Es läuft wieder. Da hat sich wohl beim Update ein Fehler eingeschlichen den ich übersehen hatte.

**Comment by alexreinert** [comment]
Klingt gut. Nach einem Kernel Update braucht es einfach immer einen Reboot und dann etwas Geduld, weil die Kernel Module dann erst neu gebaut werden müssen. Notfalls kann man das dann über das dpkg-reconfigure auch manuell anstoßen.
