### ISSUE TITLE
Nachträgliches verändern des Funkmoduls

### ISSUE THREAD

**Issue by skwasimo** [alexreinert/piVCCU#339]
Hi,
auf welche Weise ist es möglich die Setup-Optionen nach der Installation zu verändern? Bei der Installation der piVCCU2 habe ich das Fake-Modul ausgewählt, weil ich noch keins Besitze. Ich wollte nur kurz die Lage checken, bevor ich das Modul kaufe. 
Sollte ich an der Stelle lieber sofort die piVCCU3 installieren? Hab einen Raspi2b und keine Hm-CCU, nur den AP. Habe parallel auf dem raspi Homebridge laufen.
Grüße
Simon

**Comment by alexreinert** [comment]
Ein Wechsel zwischen Emulation und echtem Funkmodul  ist per `sudo dpkg-reconfigure pivccu` möglich. Was in dem Kontext mit HM-CCU und AP gemeint ist, erschließt sich mir nicht ganz.

Einen Wechsel auf piVCCU3 muss man in dem Zuge nicht durchführen, aber über kurz oder lang wird es da vermutlich keine Updates von eQ-3 mehr geben, so dass man allgemein mal über einen Wechsel nachdenken sollte.

**Comment by skwasimo** [comment]
Danke, ich habe das bestimmt im allgemeinem readme überlesen.
Die Aussage mit der CCU und dem AP bezog sich darauf, dass die piVCCU meine erste CCU ist, da ich derzeit nur den Homematic AP habe. Ich möchte gerne damit eine Homekit-Integration ermöglichen. Bringt mir der AP nach der Installation des HM-MOD-RPI-PCB und der Anbindung aller Geräte über die piVCCU überhaupt noch einen Mehrwert?
Grüße

**Comment by alexreinert** [comment]
Ich glaube hier gibt es ein großes Missverständnis: Die Geräte können immer nur an eine zentrale angemeldet werden, also entweder AP oder CCU, aber nicht an beides gleichzeitig.

**Comment by alexreinert** [comment]
Wenn jetzt frisch mit piVCCU komplett frisch angefangen wird, dann bitte gleich mit piVCCU3.

**Comment by skwasimo** [comment]
Danke für die Empfehlung. Ich bin gerade auf piVCCU3 umgestiegen. Klappt auch wunderbar auf dem Raspi2b. Warte nur noch auf die Lieferung des Funkmoduls.
Den AP habe ich mit dem HM System bekommen, hat mich keinen Cent extra gekostet. Anscheinend gibt es die Möglichkeit den AP zusätzlich an die CCU 3 anzulernen, um Reichweite zu vergrößern. Siehe Technikkram [https://technikkram.net/blog/2020/09/27/homematic-ip-access-point-als-lan-router-auf-ccu3-installieren-und-anlernen/](url)

**Comment by alexreinert** [comment]
Das geht aber nur, wenn man das RPI-RF-MOD verwendet. Und dann geht das dann auch mit piVCCU3.

**Comment by skwasimo** [comment]
Dann werde ich die Bestellung abändern. Fragestunde beendet. Danke für die Unterstützung!

**Comment by alexreinert** [comment]
Gerne. Falls es noch Fragen gibt, bitte einfach wieder aufmachen.
Ansonsten kann ich für Anfänger das Homematic Forum empfehlen, die CCU hat ja doch so manche Spezialität und dort tummeln sich etliche erfahrene Nutzer.
