### ISSUE TITLE
Fehler in Webseite von eq-3 bei Version 3.55.5

### ISSUE THREAD

**Issue by Hirsch-DE** [alexreinert/piVCCU#340]
Leider hat der Hersteller das Semikolon hinter der Versionsnummer vergessen, so dass ich keine Einstellungen vornehmen konnte.
Die Datei liegt unter "/var/lib/piVCCU3/rootfs/www/rega/pages/index.htm"

`   <script type="text/javascript">

      /*########################################################################*/
      /*# Konstanten                                                           #*/
      /*########################################################################*/

      PLATFORM = "Central";
    WEBUI_VERSION = "3.55.5";

      /**
       * Flags
       **/
`

**Comment by alexreinert** [comment]
Das ist schon seit zig Versionen so, bisher gab es da nie Probleme. Was für Probleme hast du da genau?
Fixen müsste es an sich auch eQ-3.

**Comment by Hirsch-DE** [comment]
Ich konnte ein paar Einstellungen von Geräten nicht vornehmen, da die Werte nicht alle Angezeigt wurden. Es scheint aber nicht daran zu liegen!
Es ist nur Traurig, dass eQ-3 das bis heute nicht geschafft hat, diesen Fehler abzustellen!
