### ISSUE TITLE
WebUI nicht erreichbar, weil keine IP vergeben werden kann

### ISSUE THREAD

**Issue by lukaszelek** [alexreinert/piVCCU#342]
Hallo,

ich habe vor einigen Tagen Home Assistant sowie pivccu auf meinem Raspberry 4 installiert. Home Assistant läuft soweit ohne Probleme, allerdings gibt es Schwierigkeiten bei PIVCCU. Scheinbar scheint etwas in der Konfiguration fehlgeschlagen zu sein, weshalb keine IP zugewiesen wird. Die Anleitung habe ich soweit befolgt, auch das Einstellen der Interfaces. Ein Fehler meinerseits möchte ich lieber nicht ausschließe ;)

Würde mich über Hilfe sehr freuen.

$ sudo pivccu-info
> piVCCU version: 3.53.34-51
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  FAKE_HMRF
 Board serial:  FKE1832890
 Radio MAC:     0xffc6ea
HMIP Hardware:  HMIP-RFUSB
 SGTIN:         3014F711A000041BE99B38D8
 Radio MAC:     0xBA6342
State:          RUNNING
PID:            7596
IP:             169.254.10.84
CPU use:        22.72 seconds
BlkIO use:      57.18 MiB
Link:           vethpivccu
 TX bytes:      124.47 KiB
 RX bytes:      54.23 KiB
 Total bytes:   178.70 KiB

$ sudo pivccu-attach cat /var/hm_mode
> HM_HMIP_ADDRESS='0xBA6342'
HM_HMIP_DEV='HMIP-RFUSB'
HM_HMIP_DEVNODE='/dev/mmd_hmip'
HM_HMIP_SERIAL='FKE1832890'
HM_HMIP_SGTIN='3014F711A000041BE99B38D8'
HM_HMIP_VERSION=''
HM_HMRF_ADDRESS='0xffc6ea'
HM_HMRF_DEV='HM-MOD-RPI-PCB'
HM_HMRF_DEVNODE='/dev/raw-uart'
HM_HMRF_SERIAL='FKE1832890'
HM_HMRF_VERSION='2.8.6'
HM_HOST='rpi3'
HM_HOST_GPIO_RESET=''
HM_HOST_GPIO_UART='/dev/raw-uart'
HM_LED_GREEN=''
HM_LED_RED=''
HM_LED_YELLOW=''
HM_MODE='NORMAL'
HM_RTC=''

$ sudo pivccu-attach cat /var/log/messages
>Dec 23 12:39:04 piVCCU syslog.info syslogd started: BusyBox v1.29.2
Dec 23 12:39:04 piVCCU user.notice kernel: klogd started: BusyBox v1.29.2 (2020-10-13 10:15:05 CEST)
Dec 23 12:39:06 piVCCU syslog.info syslogd exiting
Dec 23 12:39:06 ccu3-webui syslog.info syslogd started: BusyBox v1.29.2
Dec 23 12:39:06 ccu3-webui user.notice kernel: klogd started: BusyBox v1.29.2 (2020-10-13 10:15:05 CEST)
Dec 23 12:39:06 ccu3-webui daemon.err udhcpc[188]: started, v1.29.2
Dec 23 12:39:07 ccu3-webui daemon.err udhcpc[188]: sending discover
Dec 23 12:39:10 ccu3-webui daemon.err udhcpc[188]: sending discover
Dec 23 12:39:13 ccu3-webui daemon.err udhcpc[188]: sending discover
Dec 23 12:39:15 ccu3-webui daemon.err udhcpc[188]: sending discover
Dec 23 12:39:18 ccu3-webui daemon.err udhcpc[188]: sending discover
Dec 23 12:39:21 ccu3-webui daemon.err udhcpc[188]: sending discover
Dec 23 12:39:24 ccu3-webui daemon.err udhcpc[188]: sending discover
Noch mehr sending discover...
Dec 23 12:44:02 ccu3-webui user.err kernel: [  364.574097] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
Dec 23 12:44:04 ccu3-webui daemon.err udhcpc[188]: sending discover
Dec 23 12:44:07 ccu3-webui daemon.err udhcpc[188]: sending discover
Dec 23 12:44:10 ccu3-webui daemon.info avahi-autoipd(eth0)[196]: Found user 'avahi' (UID 1000) and group 'avahi' (GID 1000).
Dec 23 12:44:10 ccu3-webui daemon.info avahi-autoipd(eth0)[196]: Successfully dropped root privileges.
Dec 23 12:44:10 ccu3-webui daemon.info avahi-autoipd(eth0)[196]: Starting with address 169.254.10.84
Dec 23 12:44:16 ccu3-webui daemon.info avahi-autoipd(eth0)[196]: Callout BIND, address 169.254.10.84 on interface eth0
Dec 23 12:44:20 ccu3-webui daemon.info avahi-autoipd(eth0)[196]: Successfully claimed IP address 169.254.10.84
Dec 23 12:44:20 ccu3-webui daemon.err udhcpc[188]: no lease, forking to background
Dec 23 12:44:20 ccu3-webui user.info firewall: configuration set
Dec 23 12:44:20 ccu3-webui daemon.info ifplugd(eth0)[258]: ifplugd 0.28 initializing.
Dec 23 12:44:20 ccu3-webui daemon.info ifplugd(eth0)[258]: Using interface eth0/CA:B6:82:E0:A7:79 with driver <veth> (version: 1.0)
Dec 23 12:44:20 ccu3-webui daemon.info ifplugd(eth0)[258]: Using detection mode: SIOCETHTOOL
Dec 23 12:44:20 ccu3-webui daemon.info ifplugd(eth0)[258]: Initialization complete, link beat detected.
Dec 23 12:44:20 ccu3-webui daemon.warn ifplugd(eth0)[258]: Could not open /dev/tty, cannot beep.
Dec 23 12:44:20 ccu3-webui daemon.info ifplugd(eth0)[258]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
Dec 23 12:44:20 ccu3-webui daemon.warn ifplugd(eth0)[258]: client: ifup: interface eth0 already configured
Dec 23 12:44:20 ccu3-webui daemon.info ifplugd(eth0)[258]: Program executed successfully.
Dec 23 12:44:20 ccu3-webui daemon.err ntpdate[266]: name server cannot be used: Temporary failure in name resolution (-3)
Dec 23 12:44:20 ccu3-webui daemon.notice ntpd[267]: ntpd 4.2.8p12@1.3728-o Tue Oct 13 08:13:31 UTC 2020 (1): Starting
Dec 23 12:44:20 ccu3-webui daemon.info ntpd[267]: Command line: /usr/sbin/ntpd -g 0.de.pool.ntp.org 1.de.pool.ntp.org 2.de.pool.ntp.org 3.de.pool.ntp.org
Dec 23 12:44:20 ccu3-webui daemon.info ntpd[269]: proto: precision = 4.037 usec (-18)
Dec 23 12:44:20 ccu3-webui daemon.info ntpd[269]: Listen and drop on 0 v6wildcard [::]:123
Dec 23 12:44:20 ccu3-webui daemon.info ntpd[269]: Listen and drop on 1 v4wildcard 0.0.0.0:123
Dec 23 12:44:20 ccu3-webui daemon.info ntpd[269]: Listen normally on 2 lo 127.0.0.1:123
Dec 23 12:44:20 ccu3-webui daemon.info ntpd[269]: Listen normally on 3 eth0:avahi 169.254.10.84:123
Dec 23 12:44:20 ccu3-webui daemon.info ntpd[269]: Listen normally on 4 lo [::1]:123
Dec 23 12:44:20 ccu3-webui daemon.info ntpd[269]: Listening on routing socket on fd #21 for interface updates
Dec 23 12:44:20 ccu3-webui daemon.info ntpd[269]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
Dec 23 12:44:20 ccu3-webui daemon.info ntpd[269]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
Dec 23 12:44:20 ccu3-webui daemon.err xinetd[287]: Unable to read included directory: /etc/config/xinetd.d [file=/etc/xinetd.conf] [line=14]
Dec 23 12:44:20 ccu3-webui daemon.crit xinetd[287]: 287 {init_services} no services. Exiting...
Dec 23 12:44:20 ccu3-webui user.info root: Updating RF Lan Gateway Coprocessor Firmware
Dec 23 12:44:21 ccu3-webui user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
Dec 23 12:44:21 ccu3-webui user.info root: Updating RF Lan Gateway Firmware
Dec 23 12:44:21 ccu3-webui user.info update-lgw-firmware: No gateway found in config file /etc/config/rfd.conf
Dec 23 12:44:21 ccu3-webui user.info kernel: [  382.962060] eq3loop: created slave mmd_bidcos
Dec 23 12:44:23 ccu3-webui user.info kernel: [  385.052977] eq3loop: eq3loop_open_slave() mmd_bidcos
Dec 23 12:44:41 ccu3-webui daemon.err udhcpc[204]: sending discover
Noch mehr sending discover...
Dec 23 12:49:18 ccu3-webui user.err kernel: [  680.575989] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
Dec 23 12:49:20 ccu3-webui daemon.err udhcpc[204]: sending discover
Dec 23 12:49:23 ccu3-webui daemon.err udhcpc[204]: sending discover
Dec 23 12:49:26 ccu3-webui daemon.err udhcpc[204]: sending discover
Dec 23 12:49:29 ccu3-webui daemon.err udhcpc[204]: sending discover
Dec 23 12:49:32 ccu3-webui daemon.err udhcpc[204]: sending discover
Noch mehr sending discover...
Dec 23 12:54:34 ccu3-webui user.err kernel: [  996.608356] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
Dec 23 12:54:36 ccu3-webui daemon.err udhcpc[204]: sending discover
Dec 23 12:54:39 ccu3-webui daemon.err udhcpc[204]: sending discover
Dec 23 12:54:42 ccu3-webui daemon.err udhcpc[204]: sending discover
Dec 23 12:54:45 ccu3-webui daemon.err udhcpc[204]: sending discover
Dec 23 12:54:49 ccu3-webui daemon.err udhcpc[204]: sending discover
Dec 23 12:54:52 ccu3-webui daemon.err udhcpc[204]: sending discover
Dec 23 12:54:55 ccu3-webui daemon.err udhcpc[204]: sending discover
Noch mehr sending discover...
Dec 23 12:59:50 ccu3-webui user.err kernel: [ 1312.581585] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
Dec 23 12:59:52 ccu3-webui daemon.err udhcpc[204]: sending discover
Noch mehr sending discover...

**Comment by alexreinert** [comment]
Wird Docker verwendet?

**Comment by lukaszelek** [comment]
Ja, Home Assistant läuft über Docker.

**Comment by alexreinert** [comment]
Dann siehe #341

**Comment by lukaszelek** [comment]
Leider auch mit IPTable Regeln keine Besserung. 

Folgendes habe ich angewendet:

`sudo iptables -I DOCKER-USER -i br0 -j ACCEPT
sudo iptables -I DOCKER-USER -o br0 -j ACCEPT
sudo iptables -I DOCKER-USER -i vethpivccu -j ACCEPT
sudo iptables -I DOCKER-USER -o vethpivccu -j ACCEPT`

Lässt sich auch wiederfinden:

sudo iptables --list-rules
> -P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-A INPUT -i lxcbr0 -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -i lxcbr0 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i lxcbr0 -p tcp -m tcp --dport 67 -j ACCEPT
-A INPUT -i lxcbr0 -p udp -m udp --dport 67 -j ACCEPT
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o hassio -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o hassio -j DOCKER
-A FORWARD -i hassio ! -o hassio -j ACCEPT
-A FORWARD -i hassio -o hassio -j ACCEPT
-A FORWARD -o lxcbr0 -j ACCEPT
-A FORWARD -i lxcbr0 -j ACCEPT
-A DOCKER -d 172.30.32.6/32 ! -i hassio -o hassio -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i hassio ! -o hassio -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o hassio -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -o vethpivccu -j ACCEPT
-A DOCKER-USER -i vethpivccu -j ACCEPT
-A DOCKER-USER -o br0 -j ACCEPT
-A DOCKER-USER -i br0 -j ACCEPT
-A DOCKER-USER -j RETURN

Trotzdem weiterhin

> Dec 23 14:31:40 piVCCU syslog.info syslogd started: BusyBox v1.29.2
Dec 23 14:31:40 piVCCU user.notice kernel: klogd started: BusyBox v1.29.2 (2020-10-13 10:15:05 CEST)
Dec 23 14:31:43 piVCCU syslog.info syslogd exiting
Dec 23 14:31:43 ccu3-webui syslog.info syslogd started: BusyBox v1.29.2
Dec 23 14:31:43 ccu3-webui user.notice kernel: klogd started: BusyBox v1.29.2 (2020-10-13 10:15:05 CEST)
Dec 23 14:31:43 ccu3-webui daemon.err udhcpc[188]: started, v1.29.2
Dec 23 14:31:43 ccu3-webui daemon.err udhcpc[188]: sending discover
Mehr sending discover...
Dec 23 14:36:39 ccu3-webui user.err kernel: [  364.573936] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
Dec 23 14:36:40 ccu3-webui daemon.err udhcpc[188]: sending discover
Dec 23 14:36:43 ccu3-webui daemon.err udhcpc[188]: sending discover
Dec 23 14:36:46 ccu3-webui daemon.info avahi-autoipd(eth0)[197]: Found user 'avahi' (UID 1000) and group 'avahi' (GID 1000).
Dec 23 14:36:46 ccu3-webui daemon.info avahi-autoipd(eth0)[197]: Successfully dropped root privileges.
Dec 23 14:36:46 ccu3-webui daemon.info avahi-autoipd(eth0)[197]: Starting with address 169.254.10.84
Dec 23 14:36:52 ccu3-webui daemon.info avahi-autoipd(eth0)[197]: Callout BIND, address 169.254.10.84 on interface eth0
Dec 23 14:36:56 ccu3-webui daemon.info avahi-autoipd(eth0)[197]: Successfully claimed IP address 169.254.10.84
Dec 23 14:36:56 ccu3-webui daemon.err udhcpc[188]: no lease, forking to background
Dec 23 14:36:56 ccu3-webui user.info firewall: configuration set
Dec 23 14:36:56 ccu3-webui daemon.info ifplugd(eth0)[259]: ifplugd 0.28 initializing.
Dec 23 14:36:56 ccu3-webui daemon.info ifplugd(eth0)[259]: Using interface eth0/CA:B6:82:E0:A7:79 with driver <veth> (version: 1.0)
Dec 23 14:36:56 ccu3-webui daemon.info ifplugd(eth0)[259]: Using detection mode: SIOCETHTOOL
Dec 23 14:36:56 ccu3-webui daemon.info ifplugd(eth0)[259]: Initialization complete, link beat detected.
Dec 23 14:36:56 ccu3-webui daemon.warn ifplugd(eth0)[259]: Could not open /dev/tty, cannot beep.
Dec 23 14:36:56 ccu3-webui daemon.info ifplugd(eth0)[259]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
Dec 23 14:36:56 ccu3-webui daemon.warn ifplugd(eth0)[259]: client: ifup: interface eth0 already configured
Dec 23 14:36:56 ccu3-webui daemon.info ifplugd(eth0)[259]: Program executed successfully.
Dec 23 14:36:56 ccu3-webui daemon.err ntpdate[267]: name server cannot be used: Temporary failure in name resolution (-3)
Dec 23 14:36:56 ccu3-webui daemon.notice ntpd[268]: ntpd 4.2.8p12@1.3728-o Tue Oct 13 08:13:31 UTC 2020 (1): Starting
Dec 23 14:36:56 ccu3-webui daemon.info ntpd[268]: Command line: /usr/sbin/ntpd -g 0.de.pool.ntp.org 1.de.pool.ntp.org 2.de.pool.ntp.org 3.de.pool.ntp.org
Dec 23 14:36:56 ccu3-webui daemon.info ntpd[270]: proto: precision = 2.704 usec (-18)
Dec 23 14:36:56 ccu3-webui daemon.info ntpd[270]: Listen and drop on 0 v6wildcard [::]:123
Dec 23 14:36:56 ccu3-webui daemon.info ntpd[270]: Listen and drop on 1 v4wildcard 0.0.0.0:123
Dec 23 14:36:56 ccu3-webui daemon.info ntpd[270]: Listen normally on 2 lo 127.0.0.1:123
Dec 23 14:36:56 ccu3-webui daemon.info ntpd[270]: Listen normally on 3 eth0:avahi 169.254.10.84:123
Dec 23 14:36:56 ccu3-webui daemon.info ntpd[270]: Listen normally on 4 lo [::1]:123
Dec 23 14:36:56 ccu3-webui daemon.info ntpd[270]: Listening on routing socket on fd #21 for interface updates
Dec 23 14:36:56 ccu3-webui daemon.info ntpd[270]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
Dec 23 14:36:56 ccu3-webui daemon.info ntpd[270]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
Dec 23 14:36:56 ccu3-webui daemon.err xinetd[287]: Unable to read included directory: /etc/config/xinetd.d [file=/etc/xinetd.conf] [line=14]
Dec 23 14:36:56 ccu3-webui daemon.crit xinetd[287]: 287 {init_services} no services. Exiting...
Dec 23 14:36:57 ccu3-webui user.info root: Updating RF Lan Gateway Coprocessor Firmware
Dec 23 14:36:57 ccu3-webui user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
Dec 23 14:36:57 ccu3-webui user.info root: Updating RF Lan Gateway Firmware
Dec 23 14:36:57 ccu3-webui user.info update-lgw-firmware: No gateway found in config file /etc/config/rfd.conf
Dec 23 14:36:57 ccu3-webui user.info kernel: [  382.368195] eq3loop: created slave mmd_bidcos
Dec 23 14:36:59 ccu3-webui user.info kernel: [  384.457886] eq3loop: eq3loop_open_slave() mmd_bidcos
Dec 23 14:37:16 ccu3-webui daemon.err udhcpc[205]: sending discover
Mehr sending discover...
