### ISSUE TITLE
RPI-RF-MOD auf frischen Raspberry Pi OS nicht erkannt

### ISSUE THREAD

**Issue by asteinba** [alexreinert/piVCCU#345]
Hi Alex,

ich bin mir ziemlich sicher, dass es aktuell ein generelles Problem mit der Erkennung des RPI-RF-MOD auf einem aktuellen (oder vielleicht nur einem frisch installierten) Raspberry PI OS gibt. Ich beschreibe mal kurz, wie ich darauf komme, weil ich schon seit einigen Tagen wie doof versuche Debmatic auf meinem Pi 4 mit RPI-RF-MOD zum laufen zu bekommen. Da, soweit ich verstanden habe, Debmatic zum Teil auf piVCCU setzt und ich auch das nicht zum laufen bekommen habe, denke ich liegt das Problem bei piVCCU. Jetzt schon mal sorry für die lange Beschreibung!

Eigentlich wollte ich nur von meinem ELV Charly mit Raspberrymatic auf einen Pi 4 mit 4GB + Debmatic wechseln. Also Backup gemacht, den 3B ausgeschaltet und den RPI-RF-MOD mit Stacking Header auf den Pi 4 gesteckt. Auf einer neuen SD das aktuellste Raspberry PI OS installiert und Debmatic penibel nach Anleitung installiert. Pustekuchen, LED auf dem MOD leuchtet nicht. Ich bin jegliche alte Issues in dem Debmatic Repo durchgegangen nichts hat geholfen (config.txt passt, Kernel-Module sind installiert und wurden auch korrekt gebaut). Also habe ich den MOD noch mal auf den 3B gesetzt und auch hier ein frisches Raspberry PI OS installiert und wieder penibel nach Debmatic Anleitung installiert. Nach diversen versuchen habe ich gedacht, probiere ich doch mal piVCCU weil Debmatic ja irgendwie die Kernel-Module davon nutzt. Aber auch hier wird das Modul mit frischem Raspi OS auf dem Pi 4 und dem 3B nicht erkannt. 

Den Output der diversen Diagnose-Befehle (wie z.B. pivccu-info) poste ich jetzt nicht, da ich die selben Outputs wie in dem Issue habe: https://github.com/alexreinert/piVCCU/issues/329. Auch mein UART-RAW Device wird erkannt aber ab der Zeile "HMRF Hardware" alles nur noch "unknown".

Leider hat der User durch wildes rumprobieren es dann auch zum laufen bekommen, aber er weiß leider nicht was genau geholfen hat. Seine 3 Lösungen habe ich erfolglos getestet. Ich vermute irgendetwas ist bei einem frischen bzw. aktuellen Raspi OS anders und das verhindert die Erkennung bzw. Kommunikation mit der MOD. 

Weil ich weder piVCCU noch Debmatic auf dem Pi 3B oder dem Pi 4 zum laufen bringen konnte habe ich schon befürchetet der RPI-RF-MOD ist defekt, daher mal RaspberryMatic getestet. Läuft mit dem 4er sowie dem 3B. Dann habe ich gesehen, dass es auch fertige Raspi OS Images mit piVCCU gibt. Das aktuellste Image funktioniert weder auf meinem Pi 4 noch auf meinem 3B. Auch hier bekommt man bei pivccu-info ab der Zeile "HMRF Hardware" nur "unknown". Dann habe ich einfach mal ein altes piVCCU Image (Raspbian_Buster_Liste_piVCCU3_2019-07-11.zip) genommen und siehe da es läuft auf beiden Pi's. 

Jetzt die Frage kannst du (oder irgendjemand anderes der das liest) das reproduzieren, dass der RPI-RF-MOD auf dem aktuellen, fertigem piVCCU Image auf dem 3B und dem 4er nicht läuft?

Ich nutze jetzt erst mal weiter RaspberryMatic aber ich unterstütze gern so gut es geht bei der Fehlersuche!

**Comment by alexreinert** [comment]
Es ist das erste mal, dass ich davon höre, dass das aktuelle piVCCU3 Image ein Problem macht. Ich möchte nicht ausschließen, dass es aber wieder mal eine neue Charge RPI-RF-MOD gibt, welche sich anders als die mir bekannten verhalten.

Wäre es möglich, dass du mir das einen SSH Zugang auf dem Pi 3B mit aufgestecktem Funkmodul und aktuellem piVCCU3 Image gibst?

**Comment by asteinba** [comment]
Hi Alex, klar das bekommen wir hin. Magst du mir einen SSH Public Key schicken? Dann trage ich den auf dem Pi ein.

**Comment by asteinba** [comment]
Hi Alex,

ich fresse einen Besen. Jetzt funktioniert es. Habe gerade den Pi 3B für dich vorbereitet und siehe da es läuft. Dann noch mal piVCCU auf dem 4er getestet, läuft auch. Jetzt habe ich gerade die SD mit der Debmatic-Installation drauf (die vor ein paar Tagen definitiv **nicht** funktioniert hat) in den Pi 4 gesteckt und siehe da selbst das funktioniert!

Entweder mein RPI-RF-MOD hat einen Wackeligen oder kann es sein, dass sich der RPI-RF-MOD irgendwie weggehangen hat und durch den Goldcap zwischen den Umbauten "am Leben erhalten" wurde?

Jedenfalls sorry für den Fehlalarm und einen guten Rutsch wünsche ich dir!
