### ISSUE TITLE
HM-Sec-SCo zeigt Status nicht in CCU an

### ISSUE THREAD

**Issue by DennisGaida** [alexreinert/piVCCU#346]
Ich weiß leider nicht ob es ein piVCCU Problem oder ein CCU Problem ist.

Ich habe mehrere HmIP Geräte und auch HM Geräte im Einsatz. Funktioniert alles. Die HM-Sec-SCo funktionieren aber gar nicht: Ich kann diese anlernen, aber sie geben einfach nie ihren Status wieder. Ich habe ein Testgerät bereits komplett auf Werkseinstellungen zurückgesetzt und neu angelernt - keine Änderung.

Das komische ist: In einer parallelen FHEM Installation mit einem CUL-USB Stick werden die Statusänderungen (auf/zu) sofort(!) erkannt. Ich weiß also dass die HM-Sec-SCo funktionieren nur dass CCU den Status nicht mitbekommt.

im `/var/log/hmserver.log` und in `/var/log/messages` steht nichts zum aktuellen Zeitpunkt. Gibt es eine Art Debug-Logging wo ich alles sehen kann was die CCU empfängt?

**Comment by alexreinert** [comment]
Welche Version von piVCCU nutzt du?

Hat die parallele FHEM Installation die gleiche Radio MAC und Serial? Sind die Die HM-Sec-SCo gleichzeitig an FHEM und piVCCU angelernt?

**Comment by DennisGaida** [comment]
pivccu: `3.53.34-51`

Ich habe das Problem "behoben", wüsste aber trotzdem gerne wieso es sich so verhält: Wenn ich den CUL Stick physikalisch herausziehe funktionert das Update des HM-SEC-SCo devices in piVCCU. Wenn ich den CUL Stick wieder reinstecke bekommt nur dieser (≙ FHEM) die Updates mit.

Ich habe nur die BidCoS-Address gleichgesetzt zwischen CCU & CUL unter `/var/lib/piVCCU3/userfs/etc/config/ids`. Du schreibst auch die Serial muss gleich sein? Ich wüsste gar nicht wo der CUL eine Serial hat bzw. wie ich die auslese. Über `dmesg` sehe ich `SerialNumber=0` für den CUL.

**Comment by alexreinert** [comment]
Ein Gerät darf immer nur an einer Zentrale angelernt sein, sonst kommt es genau zu solchen Problemen, vor allem, wenn es um gesicherte/verschlüsselte Nachrichten geht.
Das mit der Serial (und BidCos ID) hast du falsch verstanden, die sollte eben grade unterschiedlich sein.

**Comment by DennisGaida** [comment]
👍 das hatte ich dann falsch verstanden in anderen Forenposts - ich dachte man könnte Gerät über die gleiche BidCos ID an mehreren Zentralen haben. Macht aber natürlich Sinn. Da dies nur eine temporäre Lösung ist und ich komplett auf piVCCU umsteige passt das auch alles so.

Dank' dir für den Input und einen guten Rutsch!
