### ISSUE TITLE
"Zentrale dem Keyserver unbekannt" nach Umstieg auf piVCCU3

### ISSUE THREAD

**Issue by brischy-j** [alexreinert/piVCCU#347]
Ich habe an meinem Pi3 B+ eine HM-mod-rpi-pcb Kasrte angebaut und wollte damit meine CCU2 (Fw 2.55)ablösen.
Da ich eine laufende ioBroker installation habe, habe ich mich für die "Hand" Installation entschieden.
Die Installation hat soweit gut geklappt, (dank hier schonmal an die einfache Anleitung) 
Nach dem Versuch das Backup (das Backup wurde erstellt, nachdem ich auf der CCU2 alle Erweiterungen deinstalliert hatte) einzuspielen gab es die Fehlermeldung " Zentrale dem Keyserver unbekannt", dabei wurde aber ein teil der Konfig übernommen. (auf den ersten Blick, alle nicht HmIP Geräte) Die lassen sich auch von der piVCCU3 aus bedienen. 
Ich habe auch schon einmal versucht nach dem Werksreset eine einzelne HmIP Steckdose anzulernen, aber auch das klappt nicht.
Leider habe ich zwar gelöste Probleme ähnlicher Art gefunden, aber die passten dann doch nicht auf meine Konfig.
Es sieht so aus als ob der piVCCU3 den Server bei eq3 nicht erreichen kann, aber ich habe keine Idee woran das liegen könnte.
Firewall usw. habe ich nicht.  
Hier einige Auzüge aus der Systemconfig und Logfiles:

`
$ lsb_release -a`
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

`$ uname -a`
Linux piiobroker 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux

`$ sudo pivccu-info`
piVCCU version: 3.53.34-51
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  REQ0915400
 Radio MAC:     0x71C546
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7DBE9975FC8
 Radio MAC:     0xBC92CE
State:          RUNNING
PID:            789
IP:             192.168.178.51
CPU use:        33.26 seconds
Link:           vethpivccu
 TX bytes:      140.44 KiB
 RX bytes:      222.73 KiB
 Total bytes:   363.16 KiB

 `
$ sudo pivccu-attach cat /var/hm_mode`

HM_HMIP_ADDRESS='0xBC92CE'
HM_HMIP_DEV='HM-MOD-RPI-PCB'
HM_HMIP_DEVNODE='/dev/raw-uart'
HM_HMIP_SERIAL='REQ0915400'
HM_HMIP_SGTIN='3014F711A061A7DBE9975FC8'
HM_HMIP_VERSION='2.8.6'
HM_HMRF_ADDRESS='0x71C546'
HM_HMRF_DEV='HM-MOD-RPI-PCB'
HM_HMRF_DEVNODE='/dev/raw-uart'
HM_HMRF_SERIAL='REQ0915400'
HM_HMRF_VERSION='2.8.6'
HM_HOST='rpi3'
HM_HOST_GPIO_RESET=''
HM_HOST_GPIO_UART='/dev/raw-uart'
HM_LED_GREEN=''
HM_LED_RED=''
HM_LED_YELLOW=''
HM_MODE='NORMAL'
HM_RTC=''

`
$ sudo pivccu-attach cat /var/log/messages`

Jan  2 12:52:47 piVCCU syslog.info syslogd started: BusyBox v1.29.2
Jan  2 12:52:47 piVCCU user.notice kernel: klogd started: BusyBox v1.29.2 (2020-10-13 10:15:05 CEST)
Jan  2 12:52:47 piVCCU syslog.info syslogd exiting
Jan  2 12:52:47 ccu3-webui syslog.info syslogd started: BusyBox v1.29.2
Jan  2 12:52:47 ccu3-webui user.notice kernel: klogd started: BusyBox v1.29.2 (2020-10-13 10:15:05 CEST)
Jan  2 12:52:47 ccu3-webui daemon.err udhcpc[189]: started, v1.29.2
Jan  2 12:52:47 ccu3-webui daemon.err udhcpc[189]: sending discover
Jan  2 12:52:47 ccu3-webui daemon.err udhcpc[189]: sending select for 192.168.178.51
Jan  2 12:52:47 ccu3-webui daemon.err udhcpc[189]: lease of 192.168.178.51 obtained, lease time 864000
Jan  2 12:52:49 ccu3-webui user.info firewall: iptables v1.6.2: invalid port/service `310000' specified Try `iptables -h' or 'iptables --help' for more information.
Jan  2 12:52:49 ccu3-webui user.info firewall: ip6tables v1.6.2: invalid port/service `310000' specified Try `ip6tables -h' or 'ip6tables --help' for more information.
Jan  2 12:52:49 ccu3-webui user.info firewall: configuration set
Jan  2 12:52:49 ccu3-webui daemon.info ifplugd(eth0)[329]: ifplugd 0.28 initializing.
Jan  2 12:52:49 ccu3-webui daemon.info ifplugd(eth0)[329]: Using interface eth0/DA:B1:EA:FA:A1:F5 with driver <veth> (version: 1.0)
Jan  2 12:52:49 ccu3-webui daemon.info ifplugd(eth0)[329]: Using detection mode: SIOCETHTOOL
Jan  2 12:52:49 ccu3-webui daemon.info ifplugd(eth0)[329]: Initialization complete, link beat detected.
Jan  2 12:52:49 ccu3-webui daemon.warn ifplugd(eth0)[329]: Could not open /dev/tty, cannot beep.
Jan  2 12:52:49 ccu3-webui daemon.info ifplugd(eth0)[329]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
Jan  2 12:52:49 ccu3-webui daemon.warn ifplugd(eth0)[329]: client: ifup: interface eth0 already configured
Jan  2 12:52:49 ccu3-webui daemon.info ifplugd(eth0)[329]: Program executed successfully.
Jan  2 12:53:10 ccu3-webui daemon.notice ntpdate[337]: step time server 131.188.3.223 offset 11.098814 sec
Jan  2 12:53:10 ccu3-webui daemon.notice ntpd[338]: ntpd 4.2.8p12@1.3728-o Tue Oct 13 08:13:31 UTC 2020 (1): Starting
Jan  2 12:53:10 ccu3-webui daemon.info ntpd[338]: Command line: /usr/sbin/ntpd -g 0.de.pool.ntp.org 1.de.pool.ntp.org 2.de.pool.ntp.org 3.de.pool.ntp.org
Jan  2 12:53:11 ccu3-webui daemon.info ntpd[340]: proto: precision = 0.520 usec (-21)
Jan  2 12:53:11 ccu3-webui daemon.info ntpd[340]: Listen and drop on 0 v6wildcard [::]:123
Jan  2 12:53:11 ccu3-webui daemon.info ntpd[340]: Listen and drop on 1 v4wildcard 0.0.0.0:123
Jan  2 12:53:11 ccu3-webui daemon.info ntpd[340]: Listen normally on 2 lo 127.0.0.1:123
Jan  2 12:53:11 ccu3-webui daemon.info ntpd[340]: Listen normally on 3 eth0 192.168.178.51:123
Jan  2 12:53:11 ccu3-webui daemon.info ntpd[340]: Listen normally on 4 lo [::1]:123
Jan  2 12:53:11 ccu3-webui daemon.info ntpd[340]: Listening on routing socket on fd #21 for interface updates
Jan  2 12:53:11 ccu3-webui daemon.info ntpd[340]: kernel reports TIME_ERROR: 0x41: Clock Unsynchronized
Jan  2 12:53:11 ccu3-webui daemon.info ntpd[340]: kernel reports TIME_ERROR: 0x41: Clock Unsynchronized
Jan  2 12:53:11 ccu3-webui daemon.err xinetd[360]: Unable to read included directory: /etc/config/xinetd.d [file=/etc/xinetd.conf] [line=14]
Jan  2 12:53:11 ccu3-webui daemon.crit xinetd[360]: 360 {init_services} no services. Exiting...
Jan  2 12:53:11 ccu3-webui auth.info sshd[382]: Server listening on 0.0.0.0 port 22.
Jan  2 12:53:11 ccu3-webui auth.info sshd[382]: Server listening on :: port 22.
Jan  2 12:53:11 ccu3-webui user.info root: Updating RF Lan Gateway Coprocessor Firmware
Jan  2 12:53:11 ccu3-webui user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
Jan  2 12:53:11 ccu3-webui user.info root: Updating RF Lan Gateway Firmware
Jan  2 12:53:11 ccu3-webui user.info update-lgw-firmware: No gateway found in config file /etc/config/rfd.conf
Jan  2 12:53:37 ccu3-webui user.info kernel: [   60.397779] eq3loop: eq3loop_open_slave() mmd_hmip
Jan  2 12:53:37 ccu3-webui user.info kernel: [   60.398052] eq3loop: eq3loop_close_slave() mmd_hmip
Jan  2 12:53:37 ccu3-webui user.info kernel: [   60.402187] eq3loop: eq3loop_open_slave() mmd_hmip
Jan  2 12:53:37 ccu3-webui user.info kernel: [   60.402400] eq3loop: eq3loop_close_slave() mmd_hmip
Jan  2 12:53:37 ccu3-webui user.info kernel: [   60.413904] eq3loop: eq3loop_open_slave() mmd_hmip
Jan  2 13:23:30 ccu3-webui user.info kernel: [ 1853.155062] eq3loop: eq3loop_open_slave() mmd_hmip
Jan  2 13:23:30 ccu3-webui user.info kernel: [ 1853.155269] eq3loop: eq3loop_close_slave() mmd_hmip
Jan  2 13:23:30 ccu3-webui user.info kernel: [ 1853.159361] eq3loop: eq3loop_open_slave() mmd_hmip
Jan  2 13:23:30 ccu3-webui user.info kernel: [ 1853.159542] eq3loop: eq3loop_close_slave() mmd_hmip
Jan  2 13:23:33 ccu3-webui user.info kernel: [ 1856.266157] eq3loop: eq3loop_close_slave() mmd_hmip
Jan  2 13:23:45 ccu3-webui user.info kernel: [ 1868.020107] eq3loop: eq3loop_open_slave() mmd_hmip
Jan  2 13:23:45 ccu3-webui user.info kernel: [ 1868.020295] eq3loop: eq3loop_close_slave() mmd_hmip
Jan  2 13:23:45 ccu3-webui user.info kernel: [ 1868.031172] eq3loop: eq3loop_open_slave() mmd_hmip

**Comment by alexreinert** [comment]
Für das Rekeying von HmIP braucht es leider Keyserver von eQ-3. Wenn der das Funkmodul nicht kennt, kann ich nichts machen. Vermutlich wurde vergessen, die Charge der Funkmodule dort aufzunehmen. Da kann einzig und allein eQ-3 helfen.

**Comment by brischy-j** [comment]
Vielen Dank trotzdem für die schnelle Antwort. Dann werde ich mich an eQ-3 wenden.
