### ISSUE TITLE
CCU nach STOPPED und nicht erreichbar // Module rpi_rf_mod_led not found in directory /lib/modules/5.4.79-v7+

### ISSUE THREAD

**Issue by visix-group** [alexreinert/piVCCU#348]
Hallo in die Runde, Hallo @alexreinert 

Ich mag dieses grundlegend Projekt sehr! Danke Alex für dein Engagement.
Leider ist mir nach einem _sudo apt update && sudo apt upgrade_ auch nach Stunden bei 13% stecken gebliebenen update, die CCU einer ELV/Charly/Raspi 3 Kombi mit iobroker Image völlig unreachable.

Auch nach diversen ersuchten bugfixes wie 
sudo apt update
sudo apt install --reinstall raspberrypi-bootloader raspberrypi-kernel raspberrypi-kernel-headers

->
Hier eine Sammlung an outputs mir bekannter bzw. hier in anderen issues erspähten Befehlen.

Gibt es eine Idee?
Wollte von der 3.47.10. auf aktuell.
Danke euch...
gesundes Neues!

_________________
pi@raspberrypi:~ $ sudo systemctl start pivccu
führt über 10min lang zu gar keinem Feedback
____________________
pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.53.34-51
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
State:          STOPPED
______________
pi@raspberrypi:~ $ sudo pivccu-attach
piVCCU is not running, cannot attach.
____
pi@raspberrypi:~ $ systemctl status pivccu.service
● pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2021-01-03 00:37:05 CET; 6s ago
  Process: 21018 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, status=0/SUCCESS)
 Main PID: 21207 (code=exited, status=1/FAILURE)

Jan 03 00:37:04 raspberrypi start_container.sh[21018]: <12>Jan  3 00:37:04 piVCCU3: HMIP hardware was not detected
Jan 03 00:37:04 raspberrypi start_container.sh[21018]: modprobe: FATAL: Module rpi_rf_mod_led not found in directory /lib/modules/5.4.79-v7+
Jan 03 00:37:05 raspberrypi start_container.sh[21018]: kernel.sched_rt_runtime_us = -1
Jan 03 00:37:05 raspberrypi start_container.sh[21018]: lxc-start: lxc: lxccontainer.c: wait_on_daemonized_start: 842 Received container state "ABORTING" instead of "RUNNING"
Jan 03 00:37:05 raspberrypi start_container.sh[21018]: lxc-start: lxc: tools/lxc_start.c: main: 330 The container failed to start
Jan 03 00:37:05 raspberrypi start_container.sh[21018]: lxc-start: lxc: tools/lxc_start.c: main: 333 To get more details, run the container in foreground mode
Jan 03 00:37:05 raspberrypi start_container.sh[21018]: lxc-start: lxc: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfile and --logpriority options
Jan 03 00:37:05 raspberrypi systemd[1]: Started piVCCU.
Jan 03 00:37:05 raspberrypi systemd[1]: pivccu.service: Main process exited, code=exited, status=1/FAILURE
Jan 03 00:37:05 raspberrypi systemd[1]: pivccu.service: Failed with result 'exit-code'.
~
~
~
~
~
~
lines 1-16/16 (END)

**Comment by alexreinert** [comment]
```
sudo dpkg-reconfigure pivccu-modules-dkms
```

**Comment by alexreinert** [comment]
Bitte Ausgabe davon hier posten, falls dort eine Logdatei  genannt wird, auch den Inhalt davon posten.

**Comment by visix-group** [comment]
Dann die Ausgabe... weil lang, gern als link https://www.dropbox.com/s/duk7m530z92b2hv/piVCCU%20rapsi%20answer%2001.rtf?dl=0

Ein wahrer Zauberspruch!

denn, direkt nach reboot, dann:

pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.53.34-51
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  5A4993E282
 Radio MAC:     0xFFE282
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F5A4993E282
 Radio MAC:     0xB3AE33
State:          RUNNING
PID:            943
IP:             192.168.50.127
CPU use:        43.41 seconds
Link:           vethpivccu
 TX bytes:      222.67 KiB
 RX bytes:      219.71 KiB
 Total bytes:   442.38 KiB

und die CCU ist erreichbar und läuft.
Leider verliert sie weiter, permanent die connection zum iobroker.
Aber dazu wohl lieber ein neuer issue.

Danke für die fixe Hilfe, Alex!
ich schau mal auf deiner wishlisht vorbei. 🥇
