### ISSUE TITLE
pivccu startet nicht

### ISSUE THREAD

**Issue by Primus919** [alexreinert/piVCCU#349]
Hallo,
ich habe meinen jungfräulichen Pi geupdatet, danach startete pivccu nicht mehr. das funkmodul ist noch nicht angeschlossen.
pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.55.5-53
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
cat: /sys/class/net//address: No such file or directory
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
State:          STOPPED

**Comment by alexreinert** [comment]
Welches OS? Wie sieht die /etc/network/interfaces aus? Wurden die Rebbots gemacht, so wie sie in der Anleitung stehen?
Zusätzlich: Ohne Funkmodul wird es generell nicht funktionieren, wenn man nicht die Funkmodulemulation nutzt.

**Comment by Primus919** [comment]
Hallo,
erstmal ein gesundes Neues, entschuldigt die kurze Fehlerbeschreibung heute Nachmittag.
Der Pi ist folgender:
https://smartkram.de/produkt/ccu3-elv-charly-asus-tinker-board-s-externe-antenne-netzteil-mit-pivccu3-kopie/
Folgendes OS:
pi@raspberrypi:~ $ sudo uname -a
Linux raspberrypi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux

Der Aufbau ist folgender: Ich baue gerade ein Haus, kann aber wegen Corona Quarantäne zur Zeit nicht hin, Netzwerk steht soweit und ein Nachbar hat seinen Laptop im Rohbau stehen. Somit habe ich nur über Teamviewer Zugriff. Mittels DynDNS und Port Forwarding kam ich auf die WebUI, dort hatte ich aber keinen Button Access Point hinzufügen. piVCCU 5.53.xx hatte ich drauf, nach Google Suche kam ich zur Lösung das Update zu fahren,  gelesen getan, erst die Stable, kein start der piVCCU, dann die testing, jetzt habe ich immer noch das Problem. Das Funkmodul kann ich erst nach meiner Quarantäne anschließen, ich möchte aber während der Quarantäne über die WebUI alle Aktoren und Eingänge Konfigurieren. Der DRAP läuft  und hängt am selben Switch wie der Pi.
Ich hoffe hier weiterhelfen.
Vielen Dank

**Comment by Primus919** [comment]
Achso, Debian Version, falls wichtig, 10.7

**Comment by alexreinert** [comment]
Support für kommerzielle Images kann der leisten, welcher Geld dafür verlangt und bekommen hat.
Aber eine Sache kann ich schon abkürzen: Den DRAP kan  man nur anlernen und nutzen, wenn ein RPI-RF-MOD angeschlossen ist.
Und noch ein Tipp: Der Hinweis beim ersten Start, dass man kein Portforwarding nutzen soll, sollte beherzigt werden.

**Comment by Primus919** [comment]
Hallo,

kommerzielle Images, dachte immer piVCCU ist kein kommerzielles Image. Ich habe mir praktisch das Paket gekauft um mir das Löten und Aufsetzen zu ersparen. Auch hier habe ich übrigens immer das gemacht, was ich bei Open Source mache, den Entwicklern Spenden, bevor ich die Hilfe brauche… (Marco Kupferschmied, 02.01.2021). Denn eines verstehe ich immer noch nicht, warum startet die pvCCU nicht? Habe ich das andere richtig verstanden, ich kann den DRAP nicht ohne Funkmodul anlernen? Startet piVCCU vielleicht einfach sobald das Funkmodul angeschlossen ist? Der erste Start erfolgte damals bei mir in der Wohnung ohne PF und ohne Funkmodul (Funktionstest), nach dem Update war der Zugriff auch über den lokalen Lappi und Teamviewer. PF ist nur für die nachfolgende Konfiguration gedacht.

Über einen Tipp würde ich mich sehr freuen.

MfG

 

Von: Alexander Reinert <notifications@github.com> 
Gesendet: Montag, 4. Januar 2021 21:32
An: alexreinert/piVCCU <piVCCU@noreply.github.com>
Cc: Primus919 <marco_kupferschmied@web.de>; Author <author@noreply.github.com>
Betreff: Re: [alexreinert/piVCCU] pivccu startet nicht (#349)

 

Support für kommerzielle Images kann der leisten, welcher Geld dafür verlangt und bekommen hat.
Aber eine Sache kann ich schon abkürzen: Den DRAP kan man nur anlernen und nutzen, wenn ein RPI-RF-MOD angeschlossen ist.
Und noch ein Tipp: Der Hinweis beim ersten Start, dass man kein Portforwarding nutzen soll, sollte beherzigt werden.

**Comment by alexreinert** [comment]
Der oben verlinkte Link sagt was von All-In-Image aus. Smartkram hat das Image erstellt, ich habe keine Ahnung wie das aufgebaut ist und kann alleine deswegen keinen Support dafür geben.

Es kann sehr gut sein, dass es aufgrund des fehlenden Funkmofuls nicht läuft (wie in der ersten Antwort von mir erwähnt) aufgrund der Fehlermeldung mit /sys/class/net kann es aber auch der Netzwerkconfig liegen (Daher auch die Frage nach dieser in der ersten Antwort von mir, welche nicht beantwortet wurde).
Aber auch wenn du piVCCU gestartet bekommst, du wirst nicht weiterkommen, die Kommunikation mit dem DRAP funktioniert nur mit angeschlossenem RPI-RF-MOD.

Zwecks Port Forwarding: Such z.B. im Homematic Forum, mit entsprechendem Hintergrundwissen kann eine CCU innerhalb von Sekunden übernommen werden.
