### ISSUE TITLE
Kosmetischer Bug in pivccu-device.sh

### ISSUE THREAD

**Issue by Elix-g** [alexreinert/piVCCU#35]
Hi Alex,

nachdem mein gestriger Umstieg von YAHM auf piVCCU dank deiner großartigen Dokumentation quasi problemfrei abgelaufen ist, habe ich einen kleinen Fehler in pivccu-device.sh wahrgenommen, der sich allerdings nicht weiter auswirkt. Das Script produziert beim Auflisten der verfügbaren Geräte folgende Ausgabe):

/usr/sbin/pivccu-device: line 55: net.ifnames=0: command not found
/dev/ttyACM0 - 03eb_AT91USBSerial1

Hängt anscheinend mit dem Parsen von cmdline.txt zusammen. Dort habe ich den Parameter net.ifnames=0 gesetzt, so dass unter Stretch die klassischen anstatt der neumodischen, MAC-basierenden Namen für Netzwerkadapter verwendet werden.

Gruß,
Elix

![output_pivccu-device](https://user-images.githubusercontent.com/37552418/37613889-153b35dc-2ba1-11e8-9c9d-5d614ea48797.jpg)

**Comment by alexreinert** [comment]
Danke für den Hinweis, schau ich mir an.
