### ISSUE TITLE
Raw UART dev:   Not available / Probleme mit der pivccu

### ISSUE THREAD

**Issue by KarelPuhli** [alexreinert/piVCCU#350]
Hallo Alex und frohes Neues!

Ich habe seit Tagen Probleme mit meiner pivccu. Diese läuft auf einem Pi4 mit mehreren Tür-/ Fensterkontakten. Neuerdings habe ich immer extrem schlechten Empfang zwischen meinen Kontakten und der pivccu. Laut Objekten im ioBroker liegen die Werte teilweise bei über 80 db. Ab und an bricht der Kontakt gänzlich ab. Meldung in der WebUI: gestörte Gerätekommunikation. 

Heute ist mir aufgefalllen, dass die Kontakte erst orange blinken und dann einmal länger rot leuchten, wenn ich ein Fenster öffne oder schließe. Die Werte (Status) werden allerdings korrekt im ioBroker angezeigt. Für mich sieht das so aus, als käme kein Rückgabewert. 

piVCCU version: 3.53.34-51
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  FAKE_HMRF
 Board serial:  FKE3078222
 Radio MAC:     0x454d5a
HMIP Hardware:  HMIP-RFUSB-TK
 SGTIN:         3014F5AC94000416FB533CD6
 Radio MAC:     0xB50EE6
State:          RUNNING
PID:            20943
IP:             10.146.26.13
CPU use:        18.36 seconds
BlkIO use:      70.31 MiB
Link:           vethpivccu
 TX bytes:      12.95 KiB
 RX bytes:      109.26 KiB
 Total bytes:   122.20 KiB

Ich würde mich über Hilfe sehr freuen!

Beste Grüße!

**Comment by alexreinert** [comment]
Definiere "Neuerdings"

Ganz allgemein muss man leider sagen, dass der Raspi 4 ein massiver Störsender im 868MHz Bandist, vor allem wenn USB3 genutzt wird oder HDMI. Da hilft regelmäßignur ein Anstand von 0,5-1m zwischen Pi und Funkmodul.

Andere bekannte Quelle für solche Probleme sind sterbende HM Geräte oder Geräte mit fast leeren Batterien, welche unkontrolliert im 868MHz Band senden bzw. stören.

**Comment by KarelPuhli** [comment]
Naja, das ganze geht jetzt so ca. 1 Monat würde ich sagen. Vorher nie Probleme. Das Funkmodul ist an USB2 angeschlossen. Allerdings hängt eine Platte an USB3. 
Was hat es denn mit <<Raw UART dev: Not available>> auf sich?

**Comment by alexreinert** [comment]
Das Raw UART Dev ist ein entsprechend konfigutierter GPIO Header oder eine HB-RF-USB/HB-RF-USB-2/HB-RF-ETH Platine. Für den HmIP-RFUSB Stick ist das nicht notwendig.

Und idealerweise mal alle Batterien checken.

Versuch mal Abstand zwischen Pi und Funkmodul zu bringen, idealerweise deutlich mehr als 0,5m.

**Comment by KarelPuhli** [comment]
> 
> 
> Das Raw UART Dev ist ein entsprechend konfigutierter GPIO Header oder eine HB-RF-USB/HB-RF-USB-2/HB-RF-ETH Platine. Für den HmIP-RFUSB Stick ist das nicht notwendig.
> 
> Und idealerweise mal alle Batterien checken.
> 
> Versuch mal Abstand zwischen Pi und Funkmodul zu bringen, idealerweise deutlich mehr als 0,5m.

Ich probiere das mal mit einer USB Verlängerung aus. Dann kann ich den Abstand deutlich vergrößern! Danke Dir schon mal! Ich gebe ne Rückmeldung!

**Comment by KarelPuhli** [comment]
Hi Alex!
Hier mal eine Rückmeldung nach ein paar Tagen!
Ich habe das Kabel verlängert, der Pi steht jetzt gut 1,5 Meter weg vom Funkmodul. Der Empfang ist laut ioB ungefähr gleich geblieben. Die Störungen in der Gerätekommunikation traten allerdings nicht mehr auf. Von daher denke ich war die Maßnahme zielführend. Vielen Dank für deine Hilfe! Ich schließe den Thread. 
Beste Grüße!
