### ISSUE TITLE
Status LED

### ISSUE THREAD

**Issue by jankem2** [alexreinert/piVCCU#352]
Hi together, 

I was wondering it there are other people out there facing the problem of the quite shiny status-led - i don't know if it is possible but for me it would be a nice addon it one could just switch off or on the status light in the webinterface.

For me i found a solution here: [https://www.verdrahtet.info/2020/06/02/ccu3-led-via-programm-aktivieren-und-deaktivieren/](https://www.verdrahtet.info/2020/06/02/ccu3-led-via-programm-aktivieren-und-deaktivieren/)

but to get this running with the piVCCU one has to slightly change the directory.
in the directory:
`cd /var/lib/piVCCU3/userfs/etc/config`
one has to create the new file disableLED :
`touch disableLED`
or delete the file to switch it on 
`rm disableLED`

i thought its possible that other people are facing the same problem- have fun.

**Comment by alexreinert** [comment]
Nope, you do not need to change the path, you just need to login to the right place. The CCU has its own IP and SSH server. Login to this console and all paths are identical to the original CCU.

As piVCCU has the main goal to be as equal to the original CCU as possible, there will be an option for this in the WebUI right when the original CCU gets this option.
