### ISSUE TITLE
Suchfunktion leer bei "Access Points mit inkompatibler FW"

### ISSUE THREAD

**Issue by xerion3800** [alexreinert/piVCCU#354]
Wenn ich den Button "Access Points mit inkompatibler FW" betätige, dann wird der Bildschirm nur etwas heller aber es wird nicht gesucht.
![IMG_20210109_134429](https://user-images.githubusercontent.com/46169403/104091910-dd7a3f80-5280-11eb-8682-960bc72e3baa.jpg)

Firmware- Version ist 3.55.5

**Comment by alexreinert** [comment]
Ist ein RPI-RF-MOD angeschossen? Dieses wird leider zwingend gebraucht, um eine HmIP-HAP an einer CCU zu nutzen, weil das HM-MOD-RPI-PCB von eQ-3 nicht das erforderliche Firmware Update bekommen hat.

**Comment by xerion3800** [comment]
leider habe ich nur ein HM-MOD-RPI-PCB verbaut. Bedeutet also es liegt daran und ist kein Bug. Schade.
