### ISSUE TITLE
Speichern von Geräteeinstellungen mit PIVCCU3  3.55.5

### ISSUE THREAD

**Issue by Piri22** [alexreinert/piVCCU#357]
Moin,
eventuell bin ich auf ein Problem in der PIVCCU3 Firmware gestoßen.
Ich nutze einen Raspberry PI 4B 8GB und und einem 64bit PiOS.
Ich besitze einen Funk-Kombisensor (OC3) HM-WDS100-C6-O-2.
In diesem kann ich über die GUI eine Sonnenscheinschwelle einstellen. Dabei bin ich schier verzweifelt. Egal, was ich eingestellt habe, der Wert sprang nach der Einstellung immer auf 50 zurück (merkwürdigerweise scheinen sich nur Werte in Eingabezeilen nicht ändern zu lassen. Dropdownmenues oder Checkboxen funktionieren).
Gerade habe ich das selbe noch einmal mit der aktuellen Raspberrymatic versucht und siehe da, es funktioniert!
Selbes habe ich bisher nicht bei anderen Homematic Komponenten getestet

Ein Nachtrag, etwa 15 Minuten später: scheinbar lassen sich auch bei anderen Komponenten die Werte in Eingabezeilen nicht ändern.
Ausserdem ist der oben beschriebene Wert des Funk-Kombisensors nach der korrekten Einstellung unter raspberrymatic bei der Nutzung der pivccu3 sofort wieder auf 50 zurückgesprungen.

**Comment by alexreinert** [comment]
Das ist ein Fehler in der CCU3 Firmware und einer der Gründe, warum ich die 3.55.5 bisher nicht in das stable Repository übernommen habe, da es dafür bisher von eQ-3 noch keinen Fix gibt.

**Comment by Piri22** [comment]
Ich verstehe, danke :-)
