### ISSUE TITLE
RPI-RF-MOD wird nicht mehr via HB-RF-USB-2 erkannt

### ISSUE THREAD

**Issue by tknaller** [alexreinert/piVCCU#359]
Hallo,

ich hatte ein gutes Monat lang die RPI-RF-MOD mit piVCCU3 auf einem Raspberry Pi 4 mit Ubuntu 20.04 laufen - via HB-RF-USB-2.

Seit einiger Zeit wir das Modul aber nicht mehr richtig erkannt.

Anstecken des USB-Moduls in `dmesg`:
```
[  125.482719] usb 1-1.1: new full-speed USB device number 7 using xhci_hcd
[  125.591946] usb 1-1.1: New USB device found, idVendor=10c4, idProduct=8c07, bcdDevice= 1.01
[  125.591956] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  125.591961] usb 1-1.1: Product: HB-RF-USB-2
[  125.591966] usb 1-1.1: Manufacturer: Alexander Reinert
[  125.591970] usb 1-1.1: SerialNumber: a6621378632bea118bb6e859cc54a361
[  125.617464] usb 1-1.1: Found HB-RF-USB-2 at usb-0000:01:00.0-1.1
[  125.620403] usbcore: registered new interface driver hb_rf_usb_2
```

ein `sudo pivccu-info` bleibt dann da kurtz stehen;
```
ubuntu@ubuntu:~$ sudo pivccu-info
piVCCU version: 3.55.5-53
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Not assigned to GPIO pins
```
dann das im dmesg:
```
[  164.618355] raw-uart raw-uart: Reset radio module
```

dann etwas später erst kommt der Rest von pivccu-info:
```
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
State:          STOPPED
```

und der LXC-Container will nicht starten....

Bitte um Hilfe. Ich vermute ja, dass ich die HB-RF-USB-2 irgendwie geschossen habe - die RPI-RF-MOD habe ich inzwischen neu gekauft - mit demselben verhalten...

**Comment by alexreinert** [comment]
Bitte bei angestecktem HB-RF-USB-2 mal die Ausgabe von
```
ls -la /dev/raw-uart*
sudo bash -c "echo 1 > /sys/class/raw-uart/raw-uart/reset_radio_module"
sudo detect_radio_module --debug /dev/raw-uart
```

Wenn die HB-RF-USB-2 angesteckt wird, leuchtet die dann initial gelb?

**Comment by tknaller** [comment]
die HB-RF-USB-2 hat eine LED?
die RPI-RF-MOD leuchtet immer nur gelb

```
ubuntu@ubuntu:~$ ls -la /dev/raw-uart*
crw------- 1 root root 506, 0 Jan 22 07:32 /dev/raw-uart
ubuntu@ubuntu:~$ sudo bash -c "echo 1 > /sys/class/raw-uart/raw-uart/reset_radio_module"
ubuntu@ubuntu:~$ sudo detect_radio_module --debug /dev/raw-uart
Sending HM frame: fd 00 03 fe 00 01 14 1e
Received HM frame: fd 00 0f 00 fe 00 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c 68
Sending HM frame: fd 00 03 00 01 00 9e 03
Received HM frame: fd 00 04 00 01 04 03 99 25
Sending HM frame: fd 00 03 fe 02 01 98 1d
Received HM frame: fd 00 0f fe 02 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c ea c6
Sending HM frame: fd 00 03 fe 03 01 1e 1e
Received HM frame: fd 00 0f fe 03 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c 6b c4
Sending HM frame: fd 00 03 fe 04 03 0c 12
Received HM frame: fd 00 04 fe 04 05 01 07 46
Sending HM frame: fd 00 03 00 05 00 06 00
Sending HM frame: fd 00 03 fe 06 01 00 1e
Sending HM frame: fd 00 03 00 07 00 8a 03
Sending HM frame: fd 00 03 fe 08 01 a4 1d
Sending HM frame: fd 00 03 00 09 00 2e 00
Error: Radio module was not detected
ubuntu@ubuntu:~$
```

**Comment by alexreinert** [comment]
Ich sollte nicht vor dem ersten Kaffee kommentieren, war blöd formuliert. Ich meinte die LED vom RPI-RF-MOD, die HB-RF-USB-2 hat keine LED.

**Comment by alexreinert** [comment]
Wie man sieht, kann grundsätzlich mit dem Funkmodul kommuniziert werden, allerdings sind da Zeichenfehler drin. Kannst du mal die Lötstellen vom Pinheader auf der HB-RF-USB-2 kontrollieren? Was für ein USB Kabel wird verwendet? Stromversorgung des Funkmoduls läuft hoffentlich nur per USB? Wie erfolgt die Stromversorgung vom Raspberry? Gab es da möglicherweise im dmesg Hinweise auf Undervoltage?

**Comment by tknaller** [comment]
Lötstellen Pinheader: habe die Platine fixfertig bei Smartkram gekauft. 

So sieht es aus:
![IMG_20210122_080040 (1)](https://user-images.githubusercontent.com/25546953/105458828-882f2c80-5c89-11eb-8c80-8a70f346a957.jpg)


Die Ersatz RPI-RF-MOD habe ich dann bei ELV direkt bestellt und das Auflöten des Goldcap ohne Kurzschluss war schon eine Challenge für mich 😂


Stromversorgung Raspberry ist ein Mean Well HDR-30-5 Din-Schiene Netzteil 15 W, 5 V, 3 A

Undervoltage im dmesg mal Laienhaft gesucht - "erfolg"los:
```
ubuntu@ubuntu:~$ dmesg | grep -i unde
ubuntu@ubuntu:~$ dmesg | grep -i volt
ubuntu@ubuntu:~$ 
```

**Comment by alexreinert** [comment]
Ich erkenne es auf dem Bild leider nicht richtig, aber kann es sein, dass bei Pin 8 (4. Lötstelle oben rechts) eine Kugelbildung der Lötstelle ist? Pin 9 und 25 sind auf jeden Fall Schrott.

**Comment by tknaller** [comment]
ja kann gut sein. also am besten bei allen, die nicht "normal" aussehen, nochmal ran? 

hoffentlich mach ich nichts noch weiter kaputt 😬

**Comment by alexreinert** [comment]
Pin 9 und 25 sind vermutlich nicht ganz so problematisch, das sind redundante GND Verbindungen. Das kann in der Theorie zum schwingen führen, aber bei den an sich sehr langsamen Signalen ist das eher unwahrscheinlich.
Wenn Pin 8 eine Kugelbildung hat, dann einfach ohne zusätzlichen Lötzinn einfach den Lötkolben ein paar Sekunden dran halten.
Du kannst ja grade nochmal ein Bild von der Seite aus machen, dann erkennt man es vermutlich besser, ob da Nacharbeiten notwendig sind.

**Comment by tknaller** [comment]
ach ja USB-Kabel: Amazon Basics USB 3.0 - hab ich schon mal getauscht und auch ein anderes Modell probiert

Stromversorgung des Funkmoduls läuft natürlich nur per USB

Lötstellen Seitenansicht:
![IMG_20210122_104853](https://user-images.githubusercontent.com/25546953/105475635-dd763880-5c9f-11eb-9d7a-2b4bc87749fb.jpg)
![IMG_20210122_104915](https://user-images.githubusercontent.com/25546953/105475658-e5ce7380-5c9f-11eb-9186-fc1706c216b4.jpg)

**Comment by tknaller** [comment]
also hab mal mit einem Multimeter den Widerstand von Pins 8 und 10 Richtung dem CP2102N gemessen und die kommen schon schön getrennt von einander mit 0 Ohm dort an...aber mehr kann ich als Laie leider auch nicht machen; die Lötstellen schauen für mich Anfänger ja auch gut aus (bis auf, wie du gesagt hast, 25 und 9, die sind echt komisch)

Einzig komisch für mich ist - das mag aber an der Natur einer solchen Platine liegen, womit ich mich leider nicht wirklich auskenne - zwischen manchen Pins am 40er Connector hüpft der Widerstand beim anbringen des Multimeters ganz kurz auf eine Zahl >0, dann verschwindets wieder auf -1 = kein Kontakt
