### ISSUE TITLE
Fehlendes tty-Device nach Neustart

### ISSUE THREAD

**Issue by Elix-g** [alexreinert/piVCCU#36]
Hallo Alex,

ich nutze neben dem HM-MOD-RPI-PCB ein USB-Funkmodul für die Verwendung im cuxd-AddOn. Auf dem Host taucht der Stick als /dev/ttyACM0 auf. Zur Nutzung in piVCCU, steht in /etc/piVCCU/post-start.sh gemäß Doku folgendes:

#!/bin/bash
pivccu-device add /dev/ttyACM0

Das Ganze funktioniert soweit auch einwandfrei. Wird allerdings die Zentrale durch z.B. die Installation eines AddOns neu gestartet, wird der Stick von cuxd nicht mehr erkannt. Ein Blick in den Container zeigt, dass das vorher sauber durchgereichte Gerät /dev/ttyACM0 nicht mehr existiert. Abhilfe schafft der Neustart der Zentrale via systemd oder das manuelle Ausführen des post-start.sh Scripts.

Besteht die Chance, post-start.sh auch bei einem Neustart der aus der Zentrale selbst erfolgt auszuführen?

Danke und Gruß,
Elix

**Comment by alexreinert** [comment]
Leider geht das aktuell bei LXC 2.x nich ohne Weiteres.

Ich habe aber sowieso vor das ganze Handling von pivccu-device etwas zu verändern, so dass man bei der Installation der Pakete (bzw. später mit dpkg-reconfigure) die Geräte auswählt, welche durchgereicht werden sollen, so dass der Umweg über das Hook-Script nicht mehr notwendig ist.

**Comment by Elix-g** [comment]
Hi Alex,

danke für deine Antworten!

Auf die Gefahr hin, dass du den Artikel bereits kennst:

https://forum.fhem.de/index.php?topic=82767.0

Habe ich ehrlich gesagt gerade nur schnell überflogen, sieht aber für meine Begriffe zutreffend aus. Werde mich am WE damit näher auseinander setzen.

Gruß,
Elix

**Comment by alexreinert** [comment]
Hi,

den kannte ich noch nicht. Aber as grundsätzliche Virgehen darin schon.
Das kannst auch genau so in piVCCU umsetzen, in dem du die /etc/piVCCU/lxc.config anpasst.

Für ein allgemeines Vorgehen sehe ich es aber problematisch, weil dadurch weitere Mounts kommen, welche ich aus Gründen der Kompatibilität cur CCU2 vermeiden will.

Das was ich machen will, wird über den gleichen Mechanismuss laufen, mit dem ich jetzt schon die dev-Nodes für das Funkmodul erstelle: die lxc config bekommt dynamisch die cgroup Einträge rein und im start hook vom Container werden dann die dev-Nodes erstellt (ohne Mount)

Viele Grüße
Alex

**Comment by martinschaller** [comment]
Aktuell funktioniert bei mir das Einbinden eines USB-Funkmoduls für die Verwendung in CUxD gar nicht mehr. Vor Update auf 2.31.25-24 hat alles wunderbar funktioniert. Eingebunden wird über /etc/piVCCU/post-start.sh gemäß Doku.

**Comment by alexreinert** [comment]
Ein allgemeines Problem kann das nicht sein, zum einen, weil sich an der Stelle zwischen der -23 und der -24 nichts geändert hat, zum anderen, weil das bei mir selber problemlos läuft.

Kannst du bitte mal die Ausgabe folgender Befehler posten (jeweils Zeile für Zeile ausgeführt):
```
ls -la /etc/piVCCU/post-start.sh
cat /etc/piVCCU/post-start.sh
sudo pivccu-attach ls -la /dev
sudo /etc/piVCCU/post-start.sh
sudo pivccu-attach ls -la /dev
```

**Comment by Elix-g** [comment]
Hi Alex,

habe das Ganze jetzt mal ganz simpel umgesetzt. Hier Infos zum Funkstick (Homematic HM-CFG-USB2 mit alternativem Bootloader und a-cul Firmware/nanoCUL):

![pivccu_usb_info](https://user-images.githubusercontent.com/37552418/37924850-96600d64-3122-11e8-820c-abcb5087b352.jpg)

Hier die originalen Mounts innerhalb des Containers:

![pivccu_container_mounts_classic](https://user-images.githubusercontent.com/37552418/37924906-be7a8a2c-3122-11e8-9a0e-2ce3b043a565.jpg)

Basierend auf den Infos im ersten Bild, folgende Zeilen in /etc/piVCCU/lxc.conf hinzugefügt:

lxc.mount.entry: /dev/ttyACM0 dev/ttyACM0 none bind,optional,create=file
lxc.cgroup.devices.allow: c 166:* rwm

Zur Übersicht das gesamte File:

![pivccu_lxc_conf](https://user-images.githubusercontent.com/37552418/37924993-0158716a-3123-11e8-826e-eb9fd1efa5d2.jpg)

Und nochmal die Mounts innerhalb des Containers mit dem Funkstick via cgroup:

![pivccu_container_mounts_cgroup](https://user-images.githubusercontent.com/37552418/37925031-20f169a0-3123-11e8-9cdc-35dc27ee7c27.jpg)

Sowohl die Steuerung der Homematic-Komponenten via HM-MOD-RPI-UART als auch das Schalten weiterer Funk-Aktoren via cuxd ist völlig problemfrei bisher. Und das Ganze bedeutet lediglich ein zusätzliches tty-Device im Container, so dass die Kompatiblität zur CCU2 hoffentlich gewahrt bleibt.

Btw: Die verpixelten Bereiche in den Bildern sind lediglich NFS-Mounts die hier keine Rolle spielen. Das gesamte Host-OS liegt auf einer NFS-Freigabe auf einem anderen RPI.

Gruß,
Elix

**Comment by alexreinert** [comment]
In piVCCU3 branch habe ich einen neuen Mechanismus umgesetzt, so dass die durchgereichten Geräte jetzt im Installer ausgewählt werden. Um keinen Breaking Change reinzubringen, werde ich das aber nicht zu piVCCU2 backporten.

**Comment by Elix-g** [comment]
Ich habe vor wenigen Tagen den Wechsel auf die piVCCU3 vollzogen. Nette Variante ohne LXC Mount und dem Anpassen der Startdateien des Containers vor dem eigentlichen Start!

Danke für deine Arbeit im Übrigen!

**Comment by alexreinert** [comment]
CUxD kann mit dem Stick kommunizieren, das ist also kein piVCCU Problem, sondern eines in CUxD. Ich tippe drauf, dass die Einstellungen von CUxD nicht vollständig übernommen wurden beim Wechsel zur CCU3. Im Homematic Forum sind da einige Erfahrungswerte mit ähnlich klingenden Problemen (auch bei der Original CCU3). Vielleicht schaust du die dir mal an,ob das bei dir auch zur Lösung führst oder machst dort einen neuen Thread auf, da sind Leute unterwegs die definitiv mehr Ahnung von CUxD haben, als ich.

**Comment by TAOGde** [comment]
> CUxD kann mit dem Stick kommunizieren, das ist also kein piVCCU Problem, sondern eines in CUxD. Ich tippe drauf, dass die Einstellungen von CUxD nicht vollständig übernommen wurden beim Wechsel zur CCU3. Im Homematic Forum sind da einige Erfahrungswerte mit ähnlich klingenden Problemen (auch bei der Original CCU3). Vielleicht schaust du die dir mal an,ob das bei dir auch zur Lösung führst oder machst dort einen neuen Thread auf, da sind Leute unterwegs die definitiv mehr Ahnung von CUxD haben, als ich.

kann es übrigens sein, dass deine pivccu3 keine Internetverbindung nach aussen hat?
ich habe den syslogserver eingerichtet wie immer aber es gehen garkeine meldungen an meinen externen server raus.
