### ISSUE TITLE
Q: HmIP-HAP an piVCCU3 ohne Funkmodul (oder emuliert) möglich? 

### ISSUE THREAD

**Issue by Lykon2k** [alexreinert/piVCCU#361]
Hallo,

ich würde gerne einen HmIP-HAP als GW nutzen, ohne ein Funkmodul auf dem Raspberry mit piVCCU3 zu haben.
Hierzu würde piVCCU mit einem emulierten Funkmodul betrieben werden.

Die Fragen die sich mir stellen sind daher folgende:
1. Brauche ich für das Pairing zwischen CCU und Access Point zwangsweise die Funkverbindung?
    (Vermutung: Ja das Pairing geht nur über das Air Interface; tbc)

2. Könnte das Funkmodul nach erfolgreicher Konfiguration/Pairing des HmIP-HAP wieder entfernt werden bzw. das emulierte Funkmodul wieder genutzt werden? 
  (Ab diesem Zeitpunkt sollte der Traffic ja nicht mehr über das Air Interface laufen sondern direkt im LAN)

Danke schön.

**Comment by alexreinert** [comment]
Zum Betrieb eines HmIP-HAP oder HmIPW-DRAP braucht es zwingend ein angeschlossenes RPI-RF-MOD, weil die für HmIP notwendigen Kryptofunktionen dahin ausgelagert sind. Eine Anpassung daran könnte nur durch eQ-3 erfolgen, es ist aber unwahrscheinlich, dass das passiert.
