### ISSUE TITLE
Fixed IP for Raspbian Buster

### ISSUE THREAD

**Issue by cheak1974** [alexreinert/piVCCU#362]
Hi Everybody,

I was wondering that no one seems to have that problem. I want to have a fixed IP address for the underlying Raspbian Buster OS. But as I started the piVCCU image I realized there is no instance of dhcpcd running. Also the ifconfig shows the eth0 without an IP address. Additionally there are two interface (br0 which gets an IP from my router and is the Raspbian and vethpivccu which is the CCU3).

I am a little scared to fiddle with /etc/network/interfaces.d and also to enable the dhcpcd service as I do not know what will be the results with regards to the bridged interface and the virtual interface.

Changing IP of the VCCU3 is easy. Go to the WebUI and change it as usual.
But is there an easy and hasslefree way to change the IP for the Raspbian?

regards
Chris

**Comment by alexreinert** [comment]
Just change the file /etc/network/interfaces and enter a static ip for the interface br0 like:

```
auto br0
iface br0 inet static
  bridge_ports eth0 address <address>
  netmask <netmask>
  gateway <gateway>
  dns-nameservers <dns1> <dns2> 
```

**Comment by alexreinert** [comment]
Issue solved?

**Comment by cheak1974** [comment]
Yes, now it is solved. Just one Enter was missing.

auto br0
iface br0 inet static
  bridge_ports eth0 
  address <address>
  netmask <netmask>
  gateway <gateway>
  dns-nameservers <dns1> <dns2> 

Thanks a lot for the quick help.

regards
Chris
