### ISSUE TITLE
Statische IP der CCU führt zum DHCP Konflikt

### ISSUE THREAD

**Issue by majuss** [alexreinert/piVCCU#363]
Ich verwende die pivccu3 mit dem neuesten Raspbian auf einem 4B.
Der Pi hat vom Speedport hybrid (der kann keine statischen IP's setzen) die 192.168.2.19 bekommen.

```
auto lo
iface lo inet loopback

iface eth0 inet manual

auto br0
iface br0 inet static
  bridge_ports eth0
  address 192.168.2.25
  netmask 255.255.255.0
  gateway 192.168.2.1
  dns-nameservers 192.168.2.1
```

Diese Konfiguration führt dazu, dass die MAC Adresse des physischen LAN Ports des Pi's und die pivccu die 192.168.2.25 bekommen, und der Pi dadurch nicht mehr erreichbar ist. Die CCU dagegen ist dagegen auf der .25 anzutreffen.
Auch folgendes brachte kein Erfolg:

```
auto lo
iface lo inet loopback

iface eth0 inet static
  address 192.168.2.19
  netmask 255.255.255.0
  gateway 192.168.2.1
  dns-nameservers 192.168.2.1

auto br0
iface br0 inet static
  bridge_ports eth0
  address 192.168.2.25
  netmask 255.255.255.0
  gateway 192.168.2.1
  dns-nameservers 192.168.2.1
```

**Comment by alexreinert** [comment]
Die zweite Konfiguration ist auf jeden Fall falsch. Das Interface eth0 darf nicht konfiguriert werden, nur das Interface br0. Dieses Interface ist das des Raspberrys. Die IP der eigentlichen CCU wird nicht innerhalb des Hosts konfiguriert, sondern per WebUI.

Mit ist aber nicht klar, was überhaupt erreicht werden soll. Falls eine statische IP gesetzt werden soll, welche im DHCP Lease Bereich liegt: Ja, das gibt einen Konflikt. Aber das ist per Definition so und kein piVCCU spezifisches Problem.

**Comment by majuss** [comment]
Ahhh ok verstanden! Danke hab den Wald vor lauter Bäumen nicht mehr gesehen.
