### ISSUE TITLE
Probleme mit HB-RF-USB-2 auf RPPI 4 8GB und ZRAM

### ISSUE THREAD

**Issue by Ltty** [alexreinert/piVCCU#364]
Hi Alexander,

seit dem letzten Kernel Update unterstützt der PI4 8GB endlich ZRAM. Das Problem das ich dabei habe ist, dass der Pi nach der Aktivierung in eine Boot Loop läuft, das heißt während dem Start von OH und der CCU3 abstürzt und sich neu startet. Anfangs habe ich gedacht, dass es nach wie vor Probleme mit den 8GB Versionen gibt, habe aber festgestellt, dass das System normal startet wenn ich die HB-RF-USB-2 mit der RPI-RF-MOD vom System abhänge. Zusammengefasst:

* Nach der Aktivierung von ZRAM auf einem Pi4 mit 8GB stürzt das System beim Boot der CCU3 und OH ab
* Der Vorgang endet in einer Bootloop, bis ich die HB-RF-USB-2 vom System abhänge
* Ohne ZRAM läuft das System stabil (suboptimal für die Lebensdauer meiner Speichermedien)

Ist dir dazu etwas bekannt bzw. kannst du dieses Prolem reproduzieren?

Liebe Grüße,
Florian

**Comment by alexreinert** [comment]
Ich habe hier leider keinen Pi 4 mit 8GB. Mit meinem 1GB Testgerät läuft piVCCU3 mit HB-RF-USB-2 und RPI-RF-MOD auch problemlos nach Aktivierung von ZRAM. Openhab ist auf dem System aber nicht drauf.
Sinnvoll wäre daher das Problem systematisch anzugehen:
- Das automatische Starten von piVCCU und Openhab deaktivieren
- Neu starten
- Manuell piVCCU starten
- Manuell openHab starten

**Comment by Ltty** [comment]
Vielen Dank, werd mir das genauer ansehen. ZRAM war bis vor kurzem auf den 8GB Systemen noch ein Problem, vielleicht gibt's hier noch Kinderkrankheiten...
