### ISSUE TITLE
Device communication disturbed for all HMIP devices after fresh setup

### ISSUE THREAD

**Issue by Ltty** [alexreinert/piVCCU#365]
Hi,
I recently moved away from HM-MOD-RPI-PCB to HB-RF-USB-2 with RPI-RF-MOD. I was already running on pivccu3 at the same version on the old system, did a backup, turned off the old CCU and module, and imported the backup on the new Pi.

First days, everything looked good, no status warnings, all devices available, showing correct values. Then I figured out, whenever I try to change a parameter on any HMIP device, the device instantly goes into "Device communication disturbed". The error disappears after some time. Removing the devices from their power source and bringing them back only also resets them, and I see the reset values in the CCU. As soon as I try to change a parameter, the device communication immediately is disturbed again.

All non-IP devices operate without errors, I can update them, control them, no issues. 

Are there any known issues or has anybody experienced and solved a similar problem? Any advice on how to identify the root cause for this issue? 

By the way, I also tried updating to 3.55.10 cause I read that there are some issues with setting the values of IP devices. Upgrading unfortunately didn't solve the issue. Can't control any of my temperature sensors.

Thanks,
Florian

**Comment by Ltty** [comment]
Hi @alexreinert,

ich hab jetzt mein altes System mit der HM-MOD-RPI-PCB hochgefahren und initial bei gleicher Firmware-Version denselben Fehler gesehen. Reset der Aktoren hat aber alle Probleme behoben. Altes System wieder runter gefahren, neues System mit HB-RF-USB-2 und RPI-RF-MOD wieder hochgefahren und dann einen Hardware Error entdeckt (davor lief das Modul problemlos):

![image](https://user-images.githubusercontent.com/3204769/107150513-62c74180-695e-11eb-882b-b2a31965e7f8.png)

Bevor ich jetzt gleich eine neue Platine kaufe, wollte ich dich fragen, ob es eine Möglichkeit gibt heraus zu finden, was kaputt ist. Hast du eine Idee? Ich könnte natürlich das HM-MOD-RPI-PCB auf die HB-RF-USB-2 stecken, hab aber Angst, dass ich mir auch das Backup Modul zerschieße...

LG,
Florian

**Comment by Ltty** [comment]
Ok, die Probleme haben keinen Zusammenhang gehabt. Der USB Fehler kommt davon, wenn das Board nicht beim Boot bereits am Pi angesteckt ist. Bin jetzt leider zurück beim ursprünglichen Problem:

Ich kann alle Geräte bis auf HMIP steuern. Ich sehe die IP Geräte, ich bekomme Updates nachdem ich die Spannung entfernt habe, sobald ich steuern probiere bekomme ich "Device Communication Disturbed"

Ich hab die USB Hardware jetzt gegen das alte HM-MOD-RPI-PCB auf dem GPIO Port getauscht, alles läuft wie es soll.

Was ich nicht verstehe: Kann es sein, dass es bei den Lötstellen was hat oder ist das ein Software Problem?

**Comment by alexreinert** [comment]
Ich rate jetzt einfach mal: Raspberry Pi 4 und die HB-RF-USB-2 war an einem USB3 Anschluss dran? Dann bitte deutlich mehr Abstand zwischen den Raspberry und die HB-RF-USB-2.
Anderes mögliches Problem: Beim Wechsel des Funkmoduls brauch es ein Re-Keying. Dafür braucht es (freien) Internetzugriff auf die Keyserver von eQ-3 und durchaus mal einige Stunden Zeit, bis das zu allen HmIP Geräten übertragen ist.
Fehler beim Rekeying kann man in der /var/log/hmserver.log innerhalb des CCU Containers erkennen.

**Comment by Ltty** [comment]
Danke, klingt beides vernünftig. Das mit den Keys war mir nicht bewusst, heißt aber die werden aktiv neu abgerufen, richtig?

Was ist das Problem mit dem USB3 Port und besteht das Problem bei USB2 Ports auch?

**Comment by alexreinert** [comment]
Der USB3 Controller erzeugt massiv Störstrahlung auch auf 868MHz und stört vor allem HmIP mit dem Listen-Before-Talk, sobald ein Gerät an einem USB3 Port hängt.

Die Keys werden nur beim Anlernen und beim Neustart nach einem Wechsel des Funkmoduls abgerufen, dann aktiv per HTTPS Request an die Keyserver von eQ-3.

Du könntest auch einfach mal das alte Funkmodul auf die HB-RF-USB-2 stecken, dann bleibt das Funkmodul ja gleich und es braucht kein Rekeying. Wenn das dann stabil läuft in einem zweiten Schritt das Funkmodul tauschen.

**Comment by Ltty** [comment]
Ok, super danke, kenne mich aus. Bzgl. den Interferenzen, könnte ein Ferritring hier helfen?

**Comment by alexreinert** [comment]
Nein, es ist nicht auf das Kabel eingekoppelt, sondern wird richtiggehend ausgesendet.

Die HB-RF-USB-2 hat auch bereits einen enrsprechenden LC Filter, welcher per Kabel eingekoppelte Störungen weitgehend ausfiltert.

**Comment by Ltty** [comment]
Danke für die Hilfe, das hat das Problem gelöst!
