### ISSUE TITLE
Hometic IP Gerät wird nicht gefunden - HmIP-BSM

### ISSUE THREAD

**Issue by DerT94** [alexreinert/piVCCU#366]
Hallo zusammen,

ich hatte die ganze Zeit eine funktionierende Raspberry-Matic Instanz.
Diese habe ich nun auf eine piVCCU umgezogen da ich den PI noch für das senden und Empfangen von 433mhz Signalen nutzen möchte. Als Funkmodul habe ich einen "HM-MOD-RPI-PCB"

Wie bin ich vorgegangen.

1. Backup der RaspberryMatic Instanz gemacht.
2. piVCCU installiert
3. Backup eingespielt

Danach hat auch alles wunderbar funktioniert.
Außer eben der besagte Schalter.

Nun habe ich ihn schon auf Werkseinstellungen zurückgesetzte aber in der piVCCU wird er nicht gefunden.
Welche Möglichkeiten habe ich noch? Gibt es Logs die mir Details dazu ausgeben?

Danke und Gruß
T

**Comment by Ltty** [comment]
Funktionieren deine anderen IP Devices?

**Comment by alexreinert** [comment]
Was für einen Pi hast du? Welches Funkmodul? Was liefert `sudo pivccu-info`?

**Comment by SirBen88** [comment]
Hallo,
ich habe vorgestern ein Update gemacht und seit dem funktioniert HMIP nicht mehr. Die HM Geräte funktionieren alle normal. Ich habe leider nur ein HMIP Gerät (HMIP-SPI). Dieses lässt sich nicht mehr anlernen bzw. steuern. Es ist erst 2 Wochen alt, daher sind die Batterien auch neu. 
Ich habe bereits pivccu3 komplett deinstalliert mittels `sudo apt purge pivccu pivccu-modules-raspberrypi pivccu-modules-dkms` und alles neu aufgesetzt. Ohne Erfolg. Auch ein manuelles anlernen hat nicht funktnioniert. 
Den Präsenzmelder (HMIP-SPI) habe ich bereits auf Werkseinstellungen zurück gesetzt. Die Anzeigelampe blinkt so wie sie soll im Anlernmodus.

sudo pivccu-info gibt bei mir:

> piVCCU version: 3.55.10-54
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  QEQ0408500
 Radio MAC:     0x6D0597
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7DA498FA3B4
 Radio MAC:     0xBD3E55
State:          RUNNING
PID:            16337
IP:             192.168.0.4
CPU use:        301.31 seconds
BlkIO use:      19.16 MiB
Link:           vethpivccu
 TX bytes:      21.68 MiB
 RX bytes:      14.04 MiB
 Total bytes:   35.72 MiB

Ich habe einen Raspberry Pi 4 mit Raspbian Buster.
Wo könnte das Problem liegen?

Vielen Dank und Gruß
Ben

**Comment by SirBen88** [comment]
Ich habe die USB 3 Geräte mal entfernt und siehe da, HMIP wird wieder erkannt. 
Habe den Tipp von Alex an anderer Stelle gefunden. 

Allerdings stellt sich mir die Frage, warum 2 Wochen lang alles gut war (ich zeichne die Helligkeitswerte kontinuierlich auf) und nach dem Update nichts mehr ging. 
Liegt vielleicht an irgendwelchen Stromspar-Methoden beim USB 3 (Festplattenspindown etc.).
Jedenfalls sind die Störungen sofort wieder da, wenn ich USB 3 nutze.

Hat eventuell jemand eine Idee, wie man trotz angeschlossener USB 3 Geräte die Störungen minimieren kann?

**Comment by alexreinert** [comment]
HB-RF-USB-2 oder HB-RF-ETH

**Comment by DerT94** [comment]
Hi,

entschuldigt die unglaublich späte Rückmeldung.
Allerddings habe ich den Fehler gefunden.

Scheinbar waren die beiden Funkmodule (433mhz und HM-MOD-RPI-PCB) zu nah aneinander platziert.
Ich habe es nun alles etwas versetzt aufgebaut und nun funktioniert alles ohne Probleme.

Trotzdem Danke und ein schönes Wochenende.

Gruß
T

**Comment by SirBen88** [comment]
Und ich habe aus einem Netzwerkkabel eine 50cm Verlängerung für das HM-MOD-RPI-PCB gebaut. Funktioniert jetzt alles fehlerfrei. 
Gruß
Ben
