### ISSUE TITLE
Fehler beim Update

### ISSUE THREAD

**Issue by toste64** [alexreinert/piVCCU#367]
Hallo zusammen,

beim Update ist die Verbindung zum Raspberry abgebrochen. Nun weiß ich nicht was passiert ist, aber piVCCU3 startet nicht mehr automatisch. Ich kann es aber händisch starten. Insoweit funktioniert es noch.
Bei erneuten Update Versuch bekomme ich folgende Meldung:

> Setting up pivccu-modules-raspberrypi (2.0-14) ...
Removing 'diversion of /var/lib/piVCCU/dtb/overlays/pivccu-raspberrypi.dtbo to /usr/share/rpikernelhack/overlays/pivccu-raspberrypi.dtbo by rpikernelhack'
dpkg-divert: error: error checking '/var/lib/piVCCU/dtb/overlays/pivccu-raspberrypi.dtbo': No such file or directory
dpkg: error processing package pivccu-modules-raspberrypi (--configure):
 installed pivccu-modules-raspberrypi package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 pivccu-modules-raspberrypi
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by alexreinert** [comment]
```
sudo apt install --reinstall raspberrypi-bootloader raspberrypi-kernel raspberrypi-kernel-headers
sudo reboot
sudo apt install --reinstall pivccu-modules-raspberrypi
sudo reboot
```

**Comment by DennisGaida** [comment]
Ich habe ähnliches. Muss jetzt fixen mit `dpkg --configure -a`. Work-in-progress, jetzt erstmal den Pi fixen ;-)

```
Setting up pivccu-modules-raspberrypi (2.0-14) ...
Removing 'diversion of /var/lib/piVCCU/dtb/overlays/pivccu-raspberrypi.dtbo to /usr/share/rpikernelhack/overlays/pivccu-raspberrypi.dtbo by rpikernelhack'
dpkg-divert: error: error checking '/var/lib/piVCCU/dtb/overlays/pivccu-raspberrypi.dtbo': No such file or directory
dpkg: error processing package pivccu-modules-raspberrypi (--configure):
 subprocess installed post-installation script returned error exit status 2
```

**Comment by toste64** [comment]
Hallo Alex,
habe das ausgeführt und das gleiche Ergebnis wie Dennis.

**Comment by DennisGaida** [comment]
Ich kann noch mehr berichten dass der initiale Fehler auch auf ein fehlerhaftes Update zurückzuführen war. Ich machte ein apt update/upgrade und irgendwo im Prozess ist piVCCU stecken geblieben. Ich sah noch einen `whiptail` Prozess der festhing. Vielleicht kam irgendein Firmware Upgrade mit dem Update mit und das hat sich aufgehängt?

**Comment by DennisGaida** [comment]
What a mess, es läuft wieder und ich hab die neue Version 😊. Hier kommt die Magic:
```
sudo apt remove pivccu-modules-raspberrypi
sudo apt upgrade pivccu3
sudo apt install pivccu-modules-raspberrypi
reboot
```
Ich nehme an irgendeine Reihenfolge ging nicht klar beim automatischen update oder der Firmware upgrade Dialog der beim piVCCU mitkommt [(3.55.10-54) over (3.53.34-51)] hat irgendwie komisch reingefunkt im gesamten Prozess.

Ich bekam es nicht hin die pivccu-modules-raspberrypi zu (re-)installieren mit oben genannten Fehlern. Was klappt ist diese komplett zu deinstallieren, dann das piVCCU upgrade inkl. Firmware Upgrade machen, dann wieder zu installieren. Ich nehme aber an dass man hier noch etwas optimieren könnte?

**Comment by toste64** [comment]
@DennisGaida Muss ich dann das Backup einspielen?

**Comment by DennisGaida** [comment]
Außer irgendwas schlimmeres geht schief - nein.

**Comment by toste64** [comment]
@DennisGaida Danke dir. Hat funktioniert!
