### ISSUE TITLE
Fehler beim Start mit Image

### ISSUE THREAD

**Issue by Noranius** [alexreinert/piVCCU#37]
ich wollte gerade die Anleitung nachvollziehen und bin schon bei der Image gescheitert. Kurz zur Konfiguration:

Raspberry Pi 3 B+
HMIP-RFUSB

Ich habe das Image Raspbian_Stretch_Lite_piVCCU_2018-03-14.zip gezogen und auf die SD per Etcher installiert. Beim Hochfahren des PI kamen mehrere Fehlermeldungen:

Failed To start Configure Bluetooth Modems Connected by UART
Failed to start LOAD/SAVE RF Kill Switch Status
Failed to start OpenBSD Secure Shell server
Failed to start Raise Network interfaces
Failed to start Hostname Service

Was ist da schief gelaufen?

Gruß Noran

**Comment by alexreinert** [comment]
Mir fehlt aktuell ein Testgerät um das Nachzustellen,
Was ich aber auf jeden Fall schonmal sagen kann: der HmIP-RFUSB wird aktuell nur in der testing-Version unterstützt und noch nicht von dem Image, d.h. unabhängig vom Problem mit den Services müsste man ein Upgrade auf das testing-Repo machen.

**Comment by Noranius** [comment]
OK. Ich habe gerade bei deinen Branches kein Testing gesehen. Welches Repo müsste ich denn dafür nehmen bzw. kannst du mir sogar die Befehle sagen die ich brauche?

**Comment by alexreinert** [comment]
Du musst die Datei /etc/apt/sources.list.d/pivccu.list editieren und dort stable durch testing ersetzen.
Dann ein `sudo apt update && sudo apt upgrade`
Danach einmal `sudo dpkg-reconfigure` um auf den HmIP-RFUSB umzustellen und dann abschließend einen Reboot.

**Comment by Noranius** [comment]
Ok. Ich war gestern schon mal bis dahin gekommen piVCCU zu installieren, aber dann trat ein anderer Fehler auf --> da frag ich in einem neuen issue nochmal. Ansonsten konnte ich piVCCU konfigurieren.

**Comment by alexreinert** [comment]
Heute wurde ein neuer Stable Kernel released. Ich bin grade am Testen, wenn das erfolgreich läuft werde ich heute oder morgen ein neues Image bauen.

**Comment by alexreinert** [comment]
Ich habe das neue Image grade erstellt und hochgeladen.
