### ISSUE TITLE
apt install pivccu-modules-dkms results in connection timeout while waiting for deamon

### ISSUE THREAD

**Issue by PhilThal** [alexreinert/piVCCU#371]
Hi I am trying to install pivccu-modules-dkms on my ubuntu server 64 bit 20.04 lts on my raspberry pi 3 as I want to docker the raspberry matic. Unfortunately as the installation goes through at one point i am always getting `Failed to wait for daemon to reply: Connection timed out`. First I installed all neccessary things with `sudo apt install build-essential bison flex libssl-dev` and then I ran `sudo apt install pivccu-modules-dkms`. Then this messages appears. Any ideas regarding this issue or is it normal ? Its at 78% installing. If I proceed with this installation the raspberry matic is unable to detect my RPI-RF-MOD on startup.

Some more logs:

```
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.0-1028-raspi/updates/dkms/

depmod.....

DKMS: install completed.
Failed to wait for daemon to reply: Connection timed out
Failed to wait for daemon to reply: Connection timed out
Failed to wait for daemon to reply: Connection timed out
Failed to wait for daemon to reply: Connection timed out
Failed to wait for daemon to reply: Connection timed out
Failed to wait for daemon to reply: Connection timed out
Failed to wait for daemon to reply: Connection timed out
Failed to wait for daemon to reply: Connection timed out
Failed to wait for daemon to reply: Connection timed out
Failed to wait for daemon to reply: Connection timed out
Failed to wait for daemon to reply: Connection timed out
Failed to wait for daemon to reply: Connection timed out
```

Thanks in advance.

**Comment by Snom** [comment]
Also if I try it with raspberry os I am not able to start the service pivccu-dkms. It starts and then immediatly stops. Is this an issue because I am always getting the message like `The currently running kernel version is 5.10.11-v7+ which is not the expected kernel version 5.10.11-v8+.` ?
