### ISSUE TITLE
Pivccu3 Instalation geht nicht

### ISSUE THREAD

**Issue by Peter1980FFM** [alexreinert/piVCCU#377]
Die folgenden NEUEN Pakete werden installiert:
  pivccu3
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen noch 0 B von 119 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 0 B Plattenplatz zusätzlich benutzt.
Vorkonfiguration der Pakete ...
Vormals nicht ausgewähltes Paket pivccu3 wird gewählt.
(Lese Datenbank ... 233654 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../pivccu3_3.57.4-56_armhf.deb ...
Entpacken von pivccu3 (3.57.4-56) ...
pivccu3 (3.57.4-56) wird eingerichtet ...
Neue Version der Konfigurationsdatei /lib/systemd/system/pivccu.service wird installiert ...
dpkg: Fehler beim Bearbeiten des Paketes pivccu3 (--configure):
 »installiertes pivccu3-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 1 zurück
Fehler traten auf beim Bearbeiten von:
 pivccu3
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Peter1980FFM** [comment]
sudo apt install pivccu3
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  arch-test busybox-static cloud-image-utils debootstrap detect-radio-module
  distro-info dns-root-data dnsmasq-base genisoimage liblxc1 libpam-cgfs lxc
  lxc-templates lxcfs qemu-utils uidmap uuid-runtime wait-sysfs-notify
Vorgeschlagene Pakete:
  cloud-utils-euca ubuntu-archive-keyring squid-deb-proxy-client shunit2 wodim
  cdrkit-doc btrfs-progs lvm2 python3-lxc qemu-block-extra
Die folgenden Pakete werden ENTFERNT:
  busybox
Die folgenden NEUEN Pakete werden installiert:
  arch-test busybox-static cloud-image-utils debootstrap detect-radio-module
  distro-info dns-root-data dnsmasq-base genisoimage liblxc1 libpam-cgfs lxc
  lxc-templates lxcfs pivccu3 qemu-utils uidmap uuid-runtime wait-sysfs-notify
0 aktualisiert, 19 neu installiert, 1 zu entfernen und 0 nicht aktualisiert.
Es müssen 123 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 12,1 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] J
Holen:1 http://archive.raspberrypi.org/debian buster/main armhf dnsmasq-base armhf 2.80-1+rpt1+deb10u1 [400 kB]
Holen:2 https://www.pivccu.de/piVCCU stable/main armhf detect-radio-module armhf 1.0-4 [261 kB]
Holen:4 https://www.pivccu.de/piVCCU stable/main armhf wait-sysfs-notify armhf 1.0-2 [3.436 B]
Holen:5 https://www.pivccu.de/piVCCU stable/main armhf pivccu3 armhf 3.57.4-56 [119 MB]
Holen:6 http://mirror.de.leaseweb.net/raspbian/raspbian buster/main armhf liblxc1 armhf 1:3.1.0+really3.0.3-8 [262 kB]
Holen:3 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf uuid-runtime armhf 2.33.1-0.1 [92,4 kB]
Holen:7 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf lxc armhf 1:3.1.0+really3.0.3-8 [626 kB]
Holen:8 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf arch-test all 0.15-2+deb10u1 [12,9 kB]
Holen:11 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf distro-info armhf 0.21 [17,6 kB]
Holen:9 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf busybox-static armhf 1:1.30.1-4 [748 kB]
Holen:13 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf genisoimage armhf 9:1.1.11-3 [315 kB]
Holen:10 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf debootstrap all 1.0.114 [73,4 kB]
Holen:12 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf dns-root-data all 2019031302 [5.396 B]
Holen:14 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf libpam-cgfs armhf 1:3.1.0+really3.0.3-8 [47,1 kB]
Holen:15 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf lxc-templates armhf 3.0.4-0+deb10u1 [83,5 kB]
Holen:16 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf lxcfs armhf 3.0.3-2 [38,9 kB]
Holen:17 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf qemu-utils armhf 1:3.1+dfsg-8+deb10u8 [766 kB]
Holen:18 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf uidmap armhf 1:4.5-1.1 [255 kB]
Holen:19 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf cloud-image-utils all 0.29-1 [23,7 kB]
Es wurden 123 MB in 27 s geholt (4.495 kB/s).
Vorkonfiguration der Pakete ...
(Lese Datenbank ... 218617 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von busybox (1:1.30.1-4) ...
Vormals nicht ausgewähltes Paket uuid-runtime wird gewählt.
(Lese Datenbank ... 218609 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../uuid-runtime_2.33.1-0.1_armhf.deb ...
Entpacken von uuid-runtime (2.33.1-0.1) ...
Vormals nicht ausgewähltes Paket detect-radio-module wird gewählt.
Vorbereitung zum Entpacken von .../detect-radio-module_1.0-4_armhf.deb ...
Entpacken von detect-radio-module (1.0-4) ...
Vormals nicht ausgewähltes Paket wait-sysfs-notify wird gewählt.
Vorbereitung zum Entpacken von .../wait-sysfs-notify_1.0-2_armhf.deb ...
Entpacken von wait-sysfs-notify (1.0-2) ...
Vormals nicht ausgewähltes Paket liblxc1 wird gewählt.
Vorbereitung zum Entpacken von .../liblxc1_1%3a3.1.0+really3.0.3-8_armhf.deb ...
Entpacken von liblxc1 (1:3.1.0+really3.0.3-8) ...
Vormals nicht ausgewähltes Paket lxc wird gewählt.
Vorbereitung zum Entpacken von .../lxc_1%3a3.1.0+really3.0.3-8_armhf.deb ...
Entpacken von lxc (1:3.1.0+really3.0.3-8) ...
detect-radio-module (1.0-4) wird eingerichtet ...
wait-sysfs-notify (1.0-2) wird eingerichtet ...
liblxc1 (1:3.1.0+really3.0.3-8) wird eingerichtet ...
lxc (1:3.1.0+really3.0.3-8) wird eingerichtet ...
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.
Failed to run 'apparmor_parser -rWT /etc/apparmor.d/lxc-containers'. You will probably need to runn it by hand at some point.
Created symlink /etc/systemd/system/multi-user.target.wants/lxc-net.service → /lib/systemd/system/lxc-net.service.
Created symlink /etc/systemd/system/multi-user.target.wants/lxc.service → /lib/systemd/system/lxc.service.
Vormals nicht ausgewähltes Paket pivccu3 wird gewählt.
(Lese Datenbank ... 218842 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../00-pivccu3_3.57.4-56_armhf.deb ...
Entpacken von pivccu3 (3.57.4-56) ...
Vormals nicht ausgewähltes Paket arch-test wird gewählt.
Vorbereitung zum Entpacken von .../01-arch-test_0.15-2+deb10u1_all.deb ...
Entpacken von arch-test (0.15-2+deb10u1) ...
Vormals nicht ausgewähltes Paket busybox-static wird gewählt.
Vorbereitung zum Entpacken von .../02-busybox-static_1%3a1.30.1-4_armhf.deb ...
Entpacken von busybox-static (1:1.30.1-4) ...
Vormals nicht ausgewähltes Paket debootstrap wird gewählt.
Vorbereitung zum Entpacken von .../03-debootstrap_1.0.114_all.deb ...
Entpacken von debootstrap (1.0.114) ...
Vormals nicht ausgewähltes Paket distro-info wird gewählt.
Vorbereitung zum Entpacken von .../04-distro-info_0.21_armhf.deb ...
Entpacken von distro-info (0.21) ...
Vormals nicht ausgewähltes Paket dns-root-data wird gewählt.
Vorbereitung zum Entpacken von .../05-dns-root-data_2019031302_all.deb ...
Entpacken von dns-root-data (2019031302) ...
Vormals nicht ausgewähltes Paket dnsmasq-base wird gewählt.
Vorbereitung zum Entpacken von .../06-dnsmasq-base_2.80-1+rpt1+deb10u1_armhf.deb ...
Entpacken von dnsmasq-base (2.80-1+rpt1+deb10u1) ...
Vormals nicht ausgewähltes Paket genisoimage wird gewählt.
Vorbereitung zum Entpacken von .../07-genisoimage_9%3a1.1.11-3_armhf.deb ...
Entpacken von genisoimage (9:1.1.11-3) ...
Vormals nicht ausgewähltes Paket libpam-cgfs wird gewählt.
Vorbereitung zum Entpacken von .../08-libpam-cgfs_1%3a3.1.0+really3.0.3-8_armhf.deb ...
Entpacken von libpam-cgfs (1:3.1.0+really3.0.3-8) ...
Vormals nicht ausgewähltes Paket lxc-templates wird gewählt.
Vorbereitung zum Entpacken von .../09-lxc-templates_3.0.4-0+deb10u1_armhf.deb ...
Entpacken von lxc-templates (3.0.4-0+deb10u1) ...
Vormals nicht ausgewähltes Paket lxcfs wird gewählt.
Vorbereitung zum Entpacken von .../10-lxcfs_3.0.3-2_armhf.deb ...
Entpacken von lxcfs (3.0.3-2) ...
Vormals nicht ausgewähltes Paket qemu-utils wird gewählt.
Vorbereitung zum Entpacken von .../11-qemu-utils_1%3a3.1+dfsg-8+deb10u8_armhf.deb ...
Entpacken von qemu-utils (1:3.1+dfsg-8+deb10u8) ...
Vormals nicht ausgewähltes Paket uidmap wird gewählt.
Vorbereitung zum Entpacken von .../12-uidmap_1%3a4.5-1.1_armhf.deb ...
Entpacken von uidmap (1:4.5-1.1) ...
Vormals nicht ausgewähltes Paket cloud-image-utils wird gewählt.
Vorbereitung zum Entpacken von .../13-cloud-image-utils_0.29-1_all.deb ...
Entpacken von cloud-image-utils (0.29-1) ...
genisoimage (9:1.1.11-3) wird eingerichtet ...
distro-info (0.21) wird eingerichtet ...
debootstrap (1.0.114) wird eingerichtet ...
libpam-cgfs (1:3.1.0+really3.0.3-8) wird eingerichtet ...
pivccu3 (3.57.4-56) wird eingerichtet ...
dpkg: Fehler beim Bearbeiten des Paketes pivccu3 (--configure):
 »installiertes pivccu3-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 1 zurück
lxcfs (3.0.3-2) wird eingerichtet ...
Created symlink /etc/systemd/system/multi-user.target.wants/lxcfs.service → /lib/systemd/system/lxcfs.service.
uidmap (1:4.5-1.1) wird eingerichtet ...
lxc-templates (3.0.4-0+deb10u1) wird eingerichtet ...
dnsmasq-base (2.80-1+rpt1+deb10u1) wird eingerichtet ...
dns-root-data (2019031302) wird eingerichtet ...
busybox-static (1:1.30.1-4) wird eingerichtet ...
uuid-runtime (2.33.1-0.1) wird eingerichtet ...
Lege Gruppe »uuidd« (GID 124) an ...
Fertig.
Warnung: Auf das von Ihnen angegebene Home-Verzeichnis /run/uuidd kann nicht zugegriffen werden: No such file or directory
Lege Systembenutzer »uuidd« (UID 116) an ...
Lege neuen Benutzer »uuidd« (UID 116) mit Gruppe »uuidd« an ...
Erstelle Home-Verzeichnis »/run/uuidd« nicht.
Created symlink /etc/systemd/system/sockets.target.wants/uuidd.socket → /lib/systemd/system/uuidd.socket.
qemu-utils (1:3.1+dfsg-8+deb10u8) wird eingerichtet ...
arch-test (0.15-2+deb10u1) wird eingerichtet ...
cloud-image-utils (0.29-1) wird eingerichtet ...
Trigger für dbus (1.12.20-0+deb10u1) werden verarbeitet ...
Trigger für initramfs-tools (0.133+deb10u1) werden verarbeitet ...
Trigger für libc-bin (2.28-10+rpi1) werden verarbeitet ...
Trigger für systemd (241-7~deb10u6+rpi1) werden verarbeitet ...
Trigger für man-db (2.8.5-2) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 pivccu3
E: Sub-process /usr/bin/dpkg returned an error code (1)

 sudo pivccu-info
piVCCU version: 3.57.4-56
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Not assigned to GPIO pins
lxc doesn't exist
/usr/sbin/pivccu-info: Zeile 35: [: ==: Einstelliger (unärer) Operator erwartet.
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
lxc doesn't exist

**Comment by Peter1980FFM** [comment]
Ist ein komplett frischer raspi

**Comment by alexreinert** [comment]
> Rasp.Pi UART: Not assigned to GPIO pins

Seems, that not all steps of the setup instruction are done or there are some special settings inside your /boot/config.txt

**Comment by Peter1980FFM** [comment]
Ich habe alle Schritte ausgeführt wo nicht dabei steht das die für die USB
Platine nicht erforderlich sind...
Und UART ist lt Anleitung nicht notwendig für die USB Platine......


Mit Freundlichen Grüssen aus Wittgenborn.


Peter Scheurich

Wilhelm-Bettenhäuser-Weg 53

63607 Wächtersbach OT Wittgenborn

01777920276



Alexander Reinert ***@***.***> schrieb am Do., 1. Apr. 2021,
15:45:

**Comment by alexreinert** [comment]
Welche USB Platine, es gibt mehrere. Welche Option wurde bei der Installation für das Funkmodul gewählt? Was liefert `lsusb`?

**Comment by Peter1980FFM** [comment]
lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 10c4:8c07 Cygnal Integrated Products, Inc.
Bus 001 Device 050: ID 1a86:e2e3 QinHeng Electronics
Bus 001 Device 085: ID 1cf1:0030 Dresden Elektronik
Bus 001 Device 003: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Habe das HB-RF-USB-2
In der Instalation habe ich die erste der drei Optionen genommen. 
also nicht Software und nicht HMIP

**Comment by alexreinert** [comment]
Welches Funkmodul ist aufgesteckt? Wie ist es aufgesteckt? Wie sehe  die Lötstellen aus? (bitte Fotos).

**Comment by Peter1980FFM** [comment]
RPI-RF-MOD
HB-RF-USB-2@usb-0000:01:00.0-1.4 (/dev/raw-uart1)
das sin die Daten von der SD Karte wo es läuft die ich aber Autauschen muss

**Comment by alexreinert** [comment]
?

**Comment by Peter1980FFM** [comment]
![IMG_20210401_201616](https://user-images.githubusercontent.com/45266139/113336805-34932c00-9327-11eb-87fd-506ae776addf.jpg)
Ich habe dieses Modul, auf einer Fertig zusammen gelöteten gekauften Platine HB-RF-USB-2 Gesteck und diese mit den Raspberry per USB Kabel verbunden.
Ich habe derzeit das mit einer alten Installation am laufen, jedoch stürzt der mir zu Oft ab und ich will jetzt komplett neu aufsetzen.

**Comment by Peter1980FFM** [comment]
Heute nochmal Versucht!
Raspberry 4 mit 4 GB
Raspbery Buster Image Full vom 04.03.2021
nur SSH Aktiviert alle Schritte ausgeführt bei der Installation:
sudo apt install pivccu3
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  arch-test busybox-static cloud-image-utils debootstrap detect-radio-module
  distro-info dns-root-data dnsmasq-base genisoimage liblxc1 libpam-cgfs lxc
  lxc-templates lxcfs qemu-utils uidmap uuid-runtime wait-sysfs-notify
Vorgeschlagene Pakete:
  cloud-utils-euca ubuntu-archive-keyring squid-deb-proxy-client shunit2 wodim
  cdrkit-doc btrfs-progs lvm2 python3-lxc qemu-block-extra
Die folgenden Pakete werden ENTFERNT:
  busybox
Die folgenden NEUEN Pakete werden installiert:
  arch-test busybox-static cloud-image-utils debootstrap detect-radio-module
  distro-info dns-root-data dnsmasq-base genisoimage liblxc1 libpam-cgfs lxc
  lxc-templates lxcfs pivccu3 qemu-utils uidmap uuid-runtime wait-sysfs-notify
0 aktualisiert, 19 neu installiert, 1 zu entfernen und 0 nicht aktualisiert.
Es müssen 123 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 12,1 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] J
Holen:1 http://archive.raspberrypi.org/debian buster/main armhf dnsmasq-base armhf 2.80-1+rpt1+deb10u1 [400 kB]
Holen:3 https://www.pivccu.de/piVCCU stable/main armhf detect-radio-module armhf 1.0-4 [261 kB]
Holen:2 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf uuid-runtime armhf 2.33.1-0.1 [92,4 kB]
Holen:5 https://www.pivccu.de/piVCCU stable/main armhf wait-sysfs-notify armhf 1.0-2 [3.436 B]
Holen:6 https://www.pivccu.de/piVCCU stable/main armhf pivccu3 armhf 3.57.4-56 [119 MB]
Holen:4 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf liblxc1 armhf 1:3.1.0+really3.0.3-8 [262 kB]
Holen:7 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf lxc armhf 1:3.1.0+really3.0.3-8 [626 kB]
Holen:8 http://mirror1.hs-esslingen.de/pub/Mirrors/archive.raspbian.org/raspbian buster/main armhf arch-test all 0.15-2+deb10u1 [12,9 kB]
Holen:9 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf busybox-static armhf 1:1.30.1-4 [748 kB]
Holen:10 http://mirror.de.leaseweb.net/raspbian/raspbian buster/main armhf debootstrap all 1.0.114 [73,4 kB]
Holen:11 http://mirror.de.leaseweb.net/raspbian/raspbian buster/main armhf distro-info armhf 0.21 [17,6 kB]
Holen:12 http://mirror1.hs-esslingen.de/pub/Mirrors/archive.raspbian.org/raspbian buster/main armhf dns-root-data all 2019031302 [5.396 B]
Holen:13 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf genisoimage armhf 9:1.1.11-3 [315 kB]
Holen:14 http://mirror.netzwerge.de/raspbian/raspbian buster/main armhf libpam-cgfs armhf 1:3.1.0+really3.0.3-8 [47,1 kB]
Holen:15 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf lxc-templates armhf 3.0.4-0+deb10u1 [83,5 kB]
Holen:16 http://mirror1.hs-esslingen.de/pub/Mirrors/archive.raspbian.org/raspbian buster/main armhf lxcfs armhf 3.0.3-2 [38,9 kB]
Holen:17 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf qemu-utils armhf 1:3.1+dfsg-8+deb10u8 [766 kB]
Holen:19 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf cloud-image-utils all 0.29-1 [23,7 kB]
Holen:18 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf uidmap armhf 1:4.5-1.1 [255 kB]
Es wurden 123 MB in 24 s geholt (5.108 kB/s).                                  
Vorkonfiguration der Pakete ...
(Lese Datenbank ... 218605 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von busybox (1:1.30.1-4) ...
Vormals nicht ausgewähltes Paket uuid-runtime wird gewählt.
(Lese Datenbank ... 218597 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../uuid-runtime_2.33.1-0.1_armhf.deb ...
Entpacken von uuid-runtime (2.33.1-0.1) ...
Vormals nicht ausgewähltes Paket detect-radio-module wird gewählt.
Vorbereitung zum Entpacken von .../detect-radio-module_1.0-4_armhf.deb ...
Entpacken von detect-radio-module (1.0-4) ...
Vormals nicht ausgewähltes Paket wait-sysfs-notify wird gewählt.
Vorbereitung zum Entpacken von .../wait-sysfs-notify_1.0-2_armhf.deb ...
Entpacken von wait-sysfs-notify (1.0-2) ...
Vormals nicht ausgewähltes Paket liblxc1 wird gewählt.
Vorbereitung zum Entpacken von .../liblxc1_1%3a3.1.0+really3.0.3-8_armhf.deb ...
Entpacken von liblxc1 (1:3.1.0+really3.0.3-8) ...
Vormals nicht ausgewähltes Paket lxc wird gewählt.
Vorbereitung zum Entpacken von .../lxc_1%3a3.1.0+really3.0.3-8_armhf.deb ...
Entpacken von lxc (1:3.1.0+really3.0.3-8) ...
detect-radio-module (1.0-4) wird eingerichtet ...
wait-sysfs-notify (1.0-2) wird eingerichtet ...
liblxc1 (1:3.1.0+really3.0.3-8) wird eingerichtet ...
lxc (1:3.1.0+really3.0.3-8) wird eingerichtet ...
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.
Failed to run 'apparmor_parser -rWT /etc/apparmor.d/lxc-containers'. You will probably need to runn it by hand at some point.
Created symlink /etc/systemd/system/multi-user.target.wants/lxc-net.service → /lib/systemd/system/lxc-net.service.
Created symlink /etc/systemd/system/multi-user.target.wants/lxc.service → /lib/systemd/system/lxc.service.
Vormals nicht ausgewähltes Paket pivccu3 wird gewählt.
(Lese Datenbank ... 218830 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../00-pivccu3_3.57.4-56_armhf.deb ...
Entpacken von pivccu3 (3.57.4-56) ...
Vormals nicht ausgewähltes Paket arch-test wird gewählt.
Vorbereitung zum Entpacken von .../01-arch-test_0.15-2+deb10u1_all.deb ...
Entpacken von arch-test (0.15-2+deb10u1) ...
Vormals nicht ausgewähltes Paket busybox-static wird gewählt.
Vorbereitung zum Entpacken von .../02-busybox-static_1%3a1.30.1-4_armhf.deb ...
Entpacken von busybox-static (1:1.30.1-4) ...
Vormals nicht ausgewähltes Paket debootstrap wird gewählt.
Vorbereitung zum Entpacken von .../03-debootstrap_1.0.114_all.deb ...
Entpacken von debootstrap (1.0.114) ...
Vormals nicht ausgewähltes Paket distro-info wird gewählt.
Vorbereitung zum Entpacken von .../04-distro-info_0.21_armhf.deb ...
Entpacken von distro-info (0.21) ...
Vormals nicht ausgewähltes Paket dns-root-data wird gewählt.
Vorbereitung zum Entpacken von .../05-dns-root-data_2019031302_all.deb ...
Entpacken von dns-root-data (2019031302) ...
Vormals nicht ausgewähltes Paket dnsmasq-base wird gewählt.
Vorbereitung zum Entpacken von .../06-dnsmasq-base_2.80-1+rpt1+deb10u1_armhf.deb ...
Entpacken von dnsmasq-base (2.80-1+rpt1+deb10u1) ...
Vormals nicht ausgewähltes Paket genisoimage wird gewählt.
Vorbereitung zum Entpacken von .../07-genisoimage_9%3a1.1.11-3_armhf.deb ...
Entpacken von genisoimage (9:1.1.11-3) ...
Vormals nicht ausgewähltes Paket libpam-cgfs wird gewählt.
Vorbereitung zum Entpacken von .../08-libpam-cgfs_1%3a3.1.0+really3.0.3-8_armhf.deb ...
Entpacken von libpam-cgfs (1:3.1.0+really3.0.3-8) ...
Vormals nicht ausgewähltes Paket lxc-templates wird gewählt.
Vorbereitung zum Entpacken von .../09-lxc-templates_3.0.4-0+deb10u1_armhf.deb ...
Entpacken von lxc-templates (3.0.4-0+deb10u1) ...
Vormals nicht ausgewähltes Paket lxcfs wird gewählt.
Vorbereitung zum Entpacken von .../10-lxcfs_3.0.3-2_armhf.deb ...
Entpacken von lxcfs (3.0.3-2) ...
Vormals nicht ausgewähltes Paket qemu-utils wird gewählt.
Vorbereitung zum Entpacken von .../11-qemu-utils_1%3a3.1+dfsg-8+deb10u8_armhf.deb ...
Entpacken von qemu-utils (1:3.1+dfsg-8+deb10u8) ...
Vormals nicht ausgewähltes Paket uidmap wird gewählt.
Vorbereitung zum Entpacken von .../12-uidmap_1%3a4.5-1.1_armhf.deb ...
Entpacken von uidmap (1:4.5-1.1) ...
Vormals nicht ausgewähltes Paket cloud-image-utils wird gewählt.
Vorbereitung zum Entpacken von .../13-cloud-image-utils_0.29-1_all.deb ...
Entpacken von cloud-image-utils (0.29-1) ...
genisoimage (9:1.1.11-3) wird eingerichtet ...
distro-info (0.21) wird eingerichtet ...
debootstrap (1.0.114) wird eingerichtet ...
libpam-cgfs (1:3.1.0+really3.0.3-8) wird eingerichtet ...
pivccu3 (3.57.4-56) wird eingerichtet ...
dpkg: Fehler beim Bearbeiten des Paketes pivccu3 (--configure):
 »installiertes pivccu3-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 1 zurück
lxcfs (3.0.3-2) wird eingerichtet ...
Created symlink /etc/systemd/system/multi-user.target.wants/lxcfs.service → /lib/systemd/system/lxcfs.service.
uidmap (1:4.5-1.1) wird eingerichtet ...
lxc-templates (3.0.4-0+deb10u1) wird eingerichtet ...
dnsmasq-base (2.80-1+rpt1+deb10u1) wird eingerichtet ...
dns-root-data (2019031302) wird eingerichtet ...
busybox-static (1:1.30.1-4) wird eingerichtet ...
uuid-runtime (2.33.1-0.1) wird eingerichtet ...
Lege Gruppe »uuidd« (GID 124) an ...
Fertig.
Warnung: Auf das von Ihnen angegebene Home-Verzeichnis /run/uuidd kann nicht zugegriffen werden: No such file or directory
Lege Systembenutzer »uuidd« (UID 116) an ...
Lege neuen Benutzer »uuidd« (UID 116) mit Gruppe »uuidd« an ...
Erstelle Home-Verzeichnis »/run/uuidd« nicht.
Created symlink /etc/systemd/system/sockets.target.wants/uuidd.socket → /lib/systemd/system/uuidd.socket.
qemu-utils (1:3.1+dfsg-8+deb10u8) wird eingerichtet ...
arch-test (0.15-2+deb10u1) wird eingerichtet ...
cloud-image-utils (0.29-1) wird eingerichtet ...
Trigger für dbus (1.12.20-0+deb10u1) werden verarbeitet ...
Trigger für initramfs-tools (0.133+deb10u1) werden verarbeitet ...
Trigger für libc-bin (2.28-10+rpi1) werden verarbeitet ...
Trigger für systemd (241-7~deb10u6+rpi1) werden verarbeitet ...
Trigger für man-db (2.8.5-2) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 pivccu3
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Peter1980FFM** [comment]
Jetzt habe ich solange Experimentiert das ich es hinbekommen habe mit der Platine RPI-RF-MOD
 über HB-RF-USB-2@usb-0000:01:00.0-1.4 (/dev/raw-uart) mit der pivccu Version 3.57.4-56 Zu Instalieren.
 Folgende Schritte habe ich gemacht
wget -q -O - https://www.pivccu.de/piVCCU/public.key | sudo apt-key add -
sudo bash -c 'echo "deb https://www.pivccu.de/piVCCU stable main" > /etc/apt/sources.list.d/pivccu.list'
sudo apt update
sudo apt install build-essential bison flex libssl-dev -y
sudo apt install raspberrypi-kernel-headers pivccu-modules-dkms -y
sudo apt remove dhcpcd5 -y
sudo apt install bridge-utils -y
sudo bash -c 'cat << EOT > /etc/network/interfaces
source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback

iface eth0 inet manual

auto br0
iface br0 inet dhcp
  bridge_ports eth0
EOT'
sudo reboot

sudo apt install pivccu3
--> Auswahl der Option "Softwareemulation des Funkmodul"
sudo dpkg-reconfigure pivccu3
--> Auswahl der Option "HM-MOD-RPI-PCB oder RPI-HF-MOD (Nur auf unterstützen ..."
danach gibt sudo pivccu-info folgendes aus:
sudo pivccu-info
piVCCU version: 3.57.4-56
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB-2@usb-0000:01:00.0-1.4 (/dev/raw-uart)
 Board serial:  58A992F7E0
 Radio MAC:     0xFFF7E0
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A992F7E0
 Radio MAC:     0xB4B020
State:          RUNNING
PID:            11785
IP:             192.168.122.27
CPU use:        1.22 seconds
BlkIO use:      36.00 KiB
Link:           vethpivccu
 TX bytes:      2.71 KiB
 RX bytes:      7.17 KiB
 Total bytes:   9.89 KiB
Und alle geht .....
Hier ist wenn man direkt die  Option "HM-MOD-RPI-PCB oder RPI-HF-MOD (Nur auf unterstützen ..." auswählt ein Bug im Script
