### ISSUE TITLE
Keinen Zugriff mehr auf Web-Ui und IO-Broker nach Update auf 3.57.4

### ISSUE THREAD

**Issue by ManuB1234** [alexreinert/piVCCU#378]
Hallo,
ich bin relativ neu hier und habe auch noch nicht viel Erfahrung. 

Nachdem laut Web-Ui ein Update auf die neueste Firmware zur Verfügung stand, habe ich die Befehle 
sudo apt update && sudo apt upgrade durchgeführt. 

Da ist dann ein Fehler aufgetreten. Daraufhin habe ich einen Neustart gemacht und die Befehle nochmals ausgeführt. 

Jetzt bekomme ich folgenden Ausgabe mit dem fett markierten Fehler.
***********************************************************************
pi@raspberrypi:~ $ sudo apt update && sudo apt upgrade
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Hit:3 https://deb.nodesource.com/node_12.x buster InRelease
Hit:4 https://www.pivccu.de/piVCCU stable InRelease
Fetched 15.0 kB in 1s (11.5 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up pivccu-modules-raspberrypi (2.0-15) ...
Removing 'diversion of /var/lib/piVCCU/dtb/overlays/pivccu-raspberrypi.dtbo to /usr/share/rpikernelhack/overlays/pivccu-raspberrypi.dtbo by rpikernelhack'
**dpkg-divert: error: error checking '/var/lib/piVCCU/dtb/overlays/pivccu-raspberrypi.dtbo': No such file or directory
dpkg: error processing package pivccu-modules-raspberrypi (--configure):**
 installed pivccu-modules-raspberrypi package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 pivccu-modules-raspberrypi
E: Sub-process /usr/bin/dpkg returned an error code (1)
***************************************************************
Leider bringt der Befehl `sudo pivccu-info` nur command not found.

Das Funkmodul leuchtet auch nur noch gelb.

Mein System ist folgendes:
Raspberry Pi 4 B
Funkmodul RPI-RF-MOD
und HB-RF-USB-2
Installiert hatte ich das Rapsberry Pi Image von hier: https://www.pivccu.de/images/?dir=piVCCU3
und den IO-Broker.

In der Fritzbox ist der Raspberry Pi noch gelistet und per SSH kann ich noch zugreifen. Aber die Web-Ui sehe ich nicht mehr.

Wie kann ich den Fehler beheben?

Danke schon im Voraus und schönen Ostersonntag.

**Comment by G-Kraxen** [comment]
Hallo,
ich bin mir nicht sicher, ob der Issue-Titel so zu verstehen ist, das keine Kommunikation zwischen Web-Ui und IO-Broker nach dem Update aufgebaut werden kann. Wenn ja, kann ich das für Openhab2 und 3 bestätigen!
Ich habe in der Installationsbeschreibung von alexreinert leider auch keine Beschreibung gefunden wie man Debmatic inkl. pivccu auf eine frühere Version downgraden kann. @alexreinert kannst du hier helfen? Danke!
