### ISSUE TITLE
node-red-contrib-avr-yamaha empfängt keine Werte - UPNP Problem?

### ISSUE THREAD

**Issue by manoloxxl** [alexreinert/piVCCU#379]
Hallo,

ich habe Probleme mit dem Yamaha Adapter in Node-Red und dem Empfang von Messages. Ist im Pivccu3 Image UPnP aktiv bzw der Port 1900 offen und weitergeleitet?

Ich habe ein Problem mit der Node 
https://github.com/krauskopf/node-red-contrib-avr-yamaha,
der empfängt nichts via UpnP. Mein iObroker hingegen (anderer PC) bekommt alles einwandfrei, es scheint also an der CCU zu liegen.

Danke!

**Comment by alexreinert** [comment]
Das kommt drauf an, ob du den Host oder den CCU Container meinst.
Im CCU Container ist UPNP aktiv, allerdings mit einem eQ-3 spezifischen Daemon und nicht mit Avahi.
Der Host ist ein normales Raspbian Minimal Image, wenn ich mich nicht täusche ist der Avahi Daemon da standardmäßig nicht aktiv, aber kann normal nachinstalliert werden.

**Comment by alexreinert** [comment]
Innerhalb des CCU Containers kommt zusätzlich noch die CCU eigene Firewall ins Spiel, da musst du selber prüfen, was du da eingestellt hast.

**Comment by alexreinert** [comment]
Sind noch Fragen offen?

**Comment by manoloxxl** [comment]
Da scheine ich bei meiner Antwort nicht auf senden geklickt zu haben...

Der Avahi Daemon ist im minimal tatsächlich enthalten, war also keine Nachinstallation notwendig. Die Ports der Firewall hatte ich auch freigegeben.

Ergebnis war aber weiterhin das Gleiche :(

Ich hab mein Vorhaben letztendlich per CRON gelöst und frage nun jede Minute den State einfach ab. Das eigentliche Problem besteht also noch.

**Comment by alexreinert** [comment]
Die initiale Frage ist nicht beantwortet: Reden wir von einer Installation im Host oder innerhalb des CCU Containers.

**Comment by manoloxxl** [comment]
Ich habe RedMatic in der CCU über die GUI installiert - also im Container.

**Comment by alexreinert** [comment]
Gut, wie geschrieben: Im Container läuft der UPNP Daemon von eQ-3 und nicht Avahi. Wen der nicht mit dem Node Red Adapter zusammenarbeitet, dann müsste das von eQ-3 in der CCU3 angegangen werden. Da eQ-3 aktuell kein Interesse an Addons für die CCU zeigt, muss man aber leider davon ausgehen, dass sich da nichts ändern wird.
Innerhalb von piVCCU kann ich nichts ändern, weil sich das mit dem Entwicklungsziel beißen würde, dass piVCCU die original CCU im Container so identisch wie möglich abbildet.
Empfehlung von mir wäre es, Node Red außerhalb des CCU Containers zu installieren, damit löst man auch diverse andere Inkompatibilitäten, weche Redmatic innerhalb der CCU hat.

**Comment by manoloxxl** [comment]
Das schaue ich mir an, danke für deine Tipps.
