### ISSUE TITLE
Keymatic Haustür öffnet ungewollt

### ISSUE THREAD

**Issue by rgies** [alexreinert/piVCCU#38]
Hallo,

habe ein echt krasses Problem. Seit dem ich von einer HM CCU auf pivcc und ein Tinkerboard umgestiegen bin kommt es immer mal wieder vor dass einfach die Haustür auf geht.
An den Programmen habe ich nach dem Umzug nichts verändert. Auf dem Tinkerboard läuft parallel noch ioBroker. Im Systemprotokoll der CCU steht nur:

13:10:19 | 23.03.2018 | Haustürschloss | Schloss entriegelt, Schlosszustand bekannt, Kein Fehler
-- | -- | -- | --
13:10:22 | 23.03.2018 | Haustür | Batterie OK, offen
13:10:37 | 23.03.2018 | Haustür | Batterie OK, geschlossen

Wenn meine Frau die Tür aufschließt sieht das so aus:

13:05:50 | 23.03.2018 | FB Heike Open | Tastendruck kurz
-- | -- | -- | --
13:05:51 | 23.03.2018 | Haustürschloss | Schloss entriegelt
13:05:51 | 23.03.2018 | Alarm Mode | Aus
13:05:51 | 23.03.2018 | Haustürschloss | Schlosszustand bekannt, Kein Fehler
13:05:52 | 23.03.2018 | Haustür | offen, Batterie OK
13:05:57 | 23.03.2018 | Haustür | geschlossen, Batterie OK

Es gibt keine direkten Verknüpfungen mit der Keymatic und nur ein einzelnes Programm, dass die Haustür öffnet, wenn bei einer von drei Fernbedienungen auf öffnen gedrückt wird.

Evtl. hat das gar nichts mit pivcc zu tun. Ich bin gerade etwas verzweifelt und über jeden Hinweis sehr Dankbar. Sonst muss ich die Keymatic abschalten und wieder Schlüssel einführen. :-(

**Comment by alexreinert** [comment]
Ich wüsste nichts, was da in piVCCU anders passieren kann, als bei der original CCU.
Einzig könnte ich mir vorstellen, dass bei einem Neustart der Containers dein Programm unbeabsichtigt ausgeführt wird (weil das ja bei der CCU normal ist, dass die Programme beim Neustart ausgeführt werden) und du z.B. durch ein apt upgrade einen Neustart des Containers ausgelöst hast.

**Comment by alexreinert** [comment]
Ansonsten errinnere ich mich dunkel daran, dass vor einziger Zeit im Homematic Forum ein ähnliches Problem diskutiert wurde (ohne dass da piVCCU beteiligt war). Ich weiß aber nicht, was da das Ergebnis war.

**Comment by rgies** [comment]
Danke, das Problem mit dem öffnen nach einem Neustart hatte ich auch schon mal. Habe aber schon mehrere Neustarts durchgeführt ohne dass sich die Haustür geöffnet hat.
Habe schon in den verschiedensten Foren gesucht und nichts dazu gefunden. Dann suche ich nochmal im Homematic Forum danach.
Gibt es denn irgendein Log wo man etwas genauer nachvollziehen kann was da passiert ist (welche Skripte gelaufen sind etc.?

**Comment by alexreinert** [comment]
Frag da mal am besten die Rega Exporten im Homematic Forum, der Teil ist 1:1 identisch mit der orginal CCU und da habe ich nur recht oberflächiges Wissen.

**Comment by rgies** [comment]
Super, Danke.

**Comment by alexreinert** [comment]
Ist noch was offen, oder kann hier zugemacht werden?

**Comment by rgies** [comment]
Hi Alex, danke. Ich habe eine Vermutung woran es lag. Muss jetzt mal testen ob es behiben ist. Hat aber nichts mit piVCCU zu tun.
