### ISSUE TITLE
Blinkende Sensoren und kein Anlernen möglich nach Neustart Raspberry Pi

### ISSUE THREAD

**Issue by KarelPuhli** [alexreinert/piVCCU#381]
Hi Alex!

Ich habe folgenden Problem. Ich habe heute morgen einen neuen Rolladenaktor HmIP-BROLL installiert. Dazu habe ich den Raspberry herunter gefahren und vom Stromnetzt genommen (Strom aus wegen der Elektroarbeiten). Nach dem Neustart der Pi ist mir aufgefallen, dass die Tür / Fenstersensoren nach Öffnen / Schließen mehrfach organge blinken und dann auf rot schalten. Im der WebUI als auch im ioB wird jedoch alles korrekt angezeigt. Die Status werden gemeldet. Unreach steht auf false. Der neue BROLL lässt sich indes nicht Anlernen, die CCU findet keine neuen Geräte. Danch habe ich über
`udo apt update && sudo apt upgrade`
und anschließendem Reboot die CCU aktualiesiert, jedoch bleibt das Problem bestehen. 
`sudo pivccu-info`
ergibt keine Auffälligkeiten. 

piVCCU version: 3.57.4-56
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  FAKE_HMRF
 Board serial:  FKE8346081
 Radio MAC:     0xfff580
HMIP Hardware:  HMIP-RFUSB-TK
 SGTIN:         3014F5AC94000416FB533CD6
 Radio MAC:     0xB50EE6
State:          RUNNING
PID:            2033
IP:             10.146.26.13
CPU use:        202.75 seconds
BlkIO use:      82.95 MiB
Link:           vethpivccu
 TX bytes:      8.54 MiB
 RX bytes:      25.82 MiB
 Total bytes:   34.36 MiB

Ich danke Dir für Deine Hilfe!

LG und schönen Sonntag! 

Karel

**Comment by alexreinert** [comment]
Mehrfach orange blinken und dann rot bedeutet, dass das Gerät die Statusänderung nicht erfolgreich versenden konnte. Das kann entweder sein, wenn es nicht senden kann (z.B. bei dauerhaft belegtem Sendekanal oder überschrittenem DC) oder wenn nicht von allen direkt verknüpften Geräten und der Zentrale ein Ack empfangen werden kann. Letzeres kann daran liegen, dass die Geräte momentan nicht erreichbar sind oder das sie wiederum Probleme beim Senden haben, wie belegten Sendekanal oder überschrittener DC.
Ein belegter Sendekanal kann auch durch einen Störsender verursacht sein, hier ist grade der Raspberry Pi 4 als massiver Störsender bekannt, je nach Kernel- und Firmwareversion und je nach angeschlossenen Geräten mal mehr und mal weniger. Hier hilft an sich nur mind. 0.5m Abstand zwischen Raspi und Funkmodul (USB Verlängerung).
Grade kurz nach dem Start kann es aber auch sein, dass die Zentrale so viel gesendet hat, dass der DC überschritten ist.
Oder aber es kann auch ein Störsender in Form eines Geräts mit leeren Batterien sein oder ein Schaltnetzteil, welches jetzt durch eine minimale Positionsveränderung vom Pi stärker auf das Funkmodul einwirken kann.

**Comment by KarelPuhli** [comment]
> 
> 
> Mehrfach orange blinken und dann rot bedeutet, dass das Gerät die Statusänderung nicht erfolgreich versenden konnte. Das kann entweder sein, wenn es nicht senden kann (z.B. bei dauerhaft belegtem Sendekanal oder überschrittenem DC) oder wenn nicht von allen direkt verknüpften Geräten und der Zentrale ein Ack empfangen werden kann. Letzeres kann daran liegen, dass die Geräte momentan nicht erreichbar sind oder das sie wiederum Probleme beim Senden haben, wie belegten Sendekanal oder überschrittener DC.
> Ein belegter Sendekanal kann auch durch einen Störsender verursacht sein, hier ist grade der Raspberry Pi 4 als massiver Störsender bekannt, je nach Kernel- und Firmwareversion und je nach angeschlossenen Geräten mal mehr und mal weniger. Hier hilft an sich nur mind. 0.5m Abstand zwischen Raspi und Funkmodul (USB Verlängerung).
> Grade kurz nach dem Start kann es aber auch sein, dass die Zentrale so viel gesendet hat, dass der DC überschritten ist.
> Oder aber es kann auch ein Störsender in Form eines Geräts mit leeren Batterien sein oder ein Schaltnetzteil, welches jetzt durch eine minimale Positionsveränderung vom Pi stärker auf das Funkmodul einwirken kann.

**Comment by KarelPuhli** [comment]
Das ist merkwürdig, denn der Status wird ja gesendet. Die Sensoren zeigen offen oder geschlossen richtig an. Der DC ist immer auf 0%. 
Ich habe den Pi mittels USB Verlängerung schon einen guten Meter vom Funkmodul entfernt platziert.

**Comment by alexreinert** [comment]
Die Routingfunktion der HmIP-PSM kann helfen, muss aber nicht. Es kommt drauf an, ob es ein reines Reichweitenproblem ist oder ob es ein Problem durch Störstrahlung ist. Wenn vom Sensor die Daten korrekt empfangen werden, spricht das eher für ein Problem mit Störstrahlung. Mit einem RPI-RF-MOD könntest du den entsprechenden Carrier Sense Level direkt auslesen, leider bietet der HmIP-RFUSB das nicht an.

**Comment by KarelPuhli** [comment]
Danke für deine Rückmeldung!
Ich habe heute den Pi sowie das Funkmodul etwas zentraler platziert. Und schon sind die Werte besser und alles funktioniert wieder wie gewünscht. Ich werde das ganze im Auge behalten. 
Vielen Dank für deinen Support!
