### ISSUE TITLE
Umzug von Raspberry 3 auf 4: Gerätestörungen

### ISSUE THREAD

**Issue by Ennos1** [alexreinert/piVCCU#382]
Hallo zusammen,
ich bin von einem Raspberry Pi 3 auf den 4 umgezogen. Eingesetzt ist das HM-MOD-RPI-PCB + abgesetzter Antenne. Ich habe die aktuellste Raspberry OS `Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux` auf der SSD und PIVCCU3 nach der Anleitung installiert. Danach habe ich ein aktuelles Backup der HomeMatic-Konfiguration erstellt und dieses eingespielt. Leider kann ich meine Geräte nun nicht mehr steuern. Zustände meiner Geräte werden jedoch zur CCU übertragen! Im Menü "Servicemeldungen" stehen die Geräte auf "Gerätekommunikation gestört", wenn ich an den Fenstergriffsensoren die Batterieabdeckung öffne, wird dort korrekterweise die Sabotage angezeigt.
Kann mir bitte jemand bei der Fehlersuche helfen?

`pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.57.4-56
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  PEQ2216752
 Radio MAC:     0x6BE037
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7D8A9AB3B30
 Radio MAC:     0xBA1DB5
State:          RUNNING
PID:            1425
IP:             192.168.150.16
CPU use:        21.83 seconds
BlkIO use:      65.36 MiB
Link:           vethpivccu
 TX bytes:      60.49 KiB
 RX bytes:      151.04 KiB
 Total bytes:   211.53 KiB
`

**Comment by alexreinert** [comment]
Fehlersuche ist recht einfach: Der Radpberry Pi 4 ist ein massiver Störsender u.A. auch im 868 MHz Bereich.
Einzige wirkliche Lösung: Viel Abstand (mind. 0,5m, besser 1m) zwischen Funkmodul und Pi. Nur die Antenne absetzen reicht dabei nicht, es muss wirklich das ganze Funkmodul sein.

**Comment by Ennos1** [comment]
Vielen Dank für die schnelle Hilfe. Ich habe HM-MOD-RPI-PCB auf eine Lochrasterplatine gesetzt und mit einer Cat. 6A Netzwerkleitung um 3m verlegt. Es funktioniert jetzt wieder ohne Probleme.
