### ISSUE TITLE
pivccu 2.57.5 not available?

### ISSUE THREAD

**Issue by Homoran** [alexreinert/piVCCU#383]
Hope you are fine!

in the code i saw a hint to firmware 2.57.5, a few days behind  3.57.5.
in my Testing system the piVCCU3 3.57.5 is already working, but my life system un piVCCU is still waiting for the update.

I need it for the new firmware of a HmIP-SFD which can only be installed on  2.57.5

Did I misunderstand `Updated to CCU2 firmware 2.57.5`?

Another Info `Updated to CCU3 firmesre 3.57.5` is referenced to piVCCU3 only

**Comment by alexreinert** [comment]
Ich antwortete mal auf Deutsch ;-)

Die 2.57.5 ist im testing APT verfügbar, ich kam noch nicht dazu, sie auch ins stable zu übernehmen, passiert heute oder morgen.

**Comment by Homoran** [comment]
Danke!

**Comment by Homoran** [comment]
Habe sie schon drauf und das Firmware update läuft

nochmals Danke
