### ISSUE TITLE
pivccu3 webui von einem PC nicht erreichbar

### ISSUE THREAD

**Issue by janfleet** [alexreinert/piVCCU#384]
Hallo,
ich habe hier und woanders schon viele Beiträge gelesen bzgl. webui der ccu3 nicht erreichbar, aber mein Fall ist echt anders und ich bitte um Rat.

Mein Setup:
Pi4B 4gb mit Raspberry Pi OS Lite 32-bit, daran das HB-RF-USB-2-Modul mit RPI-RF-MOD (nach der [hiesigen](https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md) Anleitung manuell installiert a la Buster)
Pi-IP-statisch: 192.168.178.39
Pivccu3 erhält immer die 192.168.178.25 (alles was kommt ist unabhängig davon, ob ich in der webui die IP von der fritzbox zuweisen lasse oder diese statisch auf .25 setze)
System läuft einwandfrei (außer daß ich beim neu booten des Pi die ssd erst kurz nach dem start anschließen darf (obwohl oder trotz des extern versorgten USB3.1-Hubs))

PC1 2 Systeme 1x Buster 1x Win10 (verbunden mit gleichem switch wie der Pi auch) 
aus beiden Systemen komme ich auf die webui

PC2 Windows10 only, IP statisch (auch eingetragen in der webui) 
Bei erstem Versuch hing der noch an der Fritzbox, dann habe ich hier gelesen, daß mit Fritzbox dazwischen einige so ihre Probleme und ich habe den PC dann kurzer Hand auch über den gleichen Switch versorgt)
Danach konnte ich genau 2x von dem PC aus auf die webui zugreifen. Danach nicht mehr.

Vom Handy (android,immer gleiche IP, auch in der webui eingetragen als vertrauenswürdig) kann ich auch über das wlan(fritzbox) die webui mit der ip 192.168.178.25 aufrufen. Geht auch.

Ich möchte am liebsten über PC2 mein restliches System einrichten. Aber genau der Hund will nicht.
Auf den Pi komme ich von PC2 per SSH, auf iobroker auch, alle möglichen Clients sind von dem PC erreichbar.
Nur die webui der pivccu3 will nicht.
Ein Ping geht auch nicht durch, was mich sehr erstaunt, aber so ist. (Der ping zum Pi funktioniert allerdings)

Was kann ich tun um die Verbindung vom PC2 zu untersuchen?
Hat jemand eine Idee wo der Hund begraben sein könnte?

Mit freundlichen Grüßen
Jan

**Comment by wendy2702** [comment]
Welcher Browser?

Mal Cache gelöscht und forced reload probiert?

Gibt es irgendwelche Addons im Browser?

Gibt es zusätzlichen Viren/Browser/Webschutz?

**Comment by janfleet** [comment]
Danke für die Antwort,
An PC2:
Ich habe FF und Edge probiert. Danach gepingt.
Ich könnte noch IE6 und Chrome heute Abend adhoc testen.
Ich weiß nicht warum ich nicht dran gedacht habe, aber ich habe den cache nicht gelöscht, sondern bin halt auf edge ausgewichen, den ich eigentlich nie benutze.
Was ist denn "forced" reload? (Cache löschen, Browser schließen, Browser wieder starten und IP wieder aufrufen / so hätte ich das jetzt gemacht)
In FF und Edge meine ich keine relevanten Addons installiert zu haben. Schaue und melde ich nach.

Keine Viren/ og Browser / Webschutz nur was win10 mitbringt.

**Comment by wendy2702** [comment]
Forced Reload = STRG+F5 gleichzeitig drücken

**Comment by wendy2702** [comment]
Wenn du allerdings die CCU nicht pingen kannst wird es nicht daran liegen.

dann mal von PC2 ein traceroute auf die IP der CCU machen und gucken wo es hängt

**Comment by janfleet** [comment]
Hallo Wendy2702,

ich bin Dir wirklich dankbar, besonders mit dem Tip tracert (Windows befehl von traceroute).
Das Ergebnis ist mir peinlich, am liebsten würde ich das ganze issue löschen.
Das Problem sitzt ganz klar vor dem Monitor.
Geräte verstecken und dann anderen Geräten die gleiche IP geben führt dazu, das man manchmal nicht mit dem erwarteten Gerät redet bzw. nicht redet.
Es war ein IP-Adressenkonflikt.
Btw. Ich habe zwei Geräte mit gleicher IP-Adresse, die sogar miteinander Daten austauschen. Hätte ich mehr Zeit würde ich da ja gerne mit rumspielen, aber jetzt geht es weiter mit iobroker und pivccu3.

**Comment by wendy2702** [comment]
👍

dann bitte das issue schließen!
