### ISSUE TITLE
Boot stops @ Update UTMP about System Runlevel Changes

### ISSUE THREAD

**Issue by Norm71** [alexreinert/piVCCU#385]
With all piVCCU3 images i try the boot is stoping at: Started Update UTMP about System Runlevel Changes.

Wrote with Balena etcher your image to the SD Card and booted the first time.
used : RaspberryPiOS_lite_piVCCU3_2020-12-07.zip
RaspberryPi 4B 8GB & HM-MOD-RPI-PCB

Stays for at least 15 Minutes.

Every other image (Raspian/Raspberrymatic/HomeAssistant) is running fine.

**Comment by Norm71** [comment]
Additional information:
Also changing the SD Card is not helping.
WebUi is reachable and login via ssh is working.
Searching for devices dont get any result.

**Comment by alexreinert** [comment]
So with a different SD card the initial issue is not there anymore?

Raspberry Pi 4 has a lot of interfering radiation on 868MHz. Only way to solve this, is getting at least 0.5m space between Pi and Radio Module, e.g. by using a HB-RF-USB-2.

**Comment by Norm71** [comment]
Different SD Card same problem. I worked around it by doing:
Quit the process and did
sudo rm -r /var/lib/apt/lists/*
sudo apt-get clean
sudo apt-get update

Now it is working but dont know if there is now missing some parts.
Also devices got found in WebUi now.
