### ISSUE TITLE
Problems with adding new Homematic IP actors

### ISSUE THREAD

**Issue by jackmenimble0** [alexreinert/piVCCU#386]
Hey Guys,

I'm using a Raspi 4B with pivccu3 and HM-MOD-RPI-PCB. Installation seems to work fine. I get following output: 

`pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.57.5-57
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  OEQ0310424
 Radio MAC:     0x584B55
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7D7098E2498
 Radio MAC:     0xB03ACB
State:          RUNNING
PID:            945
IP:             192.168.178.25
CPU use:        15.06 seconds
BlkIO use:      62.37 MiB
Link:           vethpivccu
 TX bytes:      17.61 KiB
 RX bytes:      35.16 KiB
 Total bytes:   52.77 KiB`

But I can't add Homematic actors. The actors and HM-MOD-RPI-PCB was already working with Raspi 3B. The actors was many times resetet. What could be the problem?

Thanks a lot!

**Comment by alexreinert** [comment]
The Raspi 4B produces a lot of interference at 868MHz, which affects especially HmIP with its Listen-Before-Talk.
You need at least 50cm distance between the HM-MOD-RPI-PCB and the Raspi.

**Comment by jackmenimble0** [comment]
I‘m understandig. But how could I resolve it?

**Comment by alexreinert** [comment]
As said, you need at least 50cm distance between the HM-MOD-RPI-PCB and the Raspi, e.g. using GPIO ribbon cable or using a HB-RF-USB-2 pcb.
