### ISSUE TITLE
Web-UI bleibt im Start-modus

### ISSUE THREAD

**Issue by sapcons** [alexreinert/piVCCU#387]
Guten Morgen,

PIVCCU startet ohne Probleme.

<img width="434" alt="image" src="https://user-images.githubusercontent.com/19777656/125912549-7e1ef72b-4400-4e80-9692-e41d02aa5db9.png">

Leider kann ich über den Browser nicht auf die CCU zugreifen. 

<img width="789" alt="image" src="https://user-images.githubusercontent.com/19777656/125912842-5f42986b-2389-4abe-8ae3-5f35f283cc30.png">

Das System ist jetzt über Monate hin ohne Schwierigkeiten gelaufen. Bewusst habe ich zumindest nichts verändert. 

Vielen Dank für die Unterstützung

**Comment by wendy2702** [comment]
Hi,

mal Browser Cache gelöscht oder forced Reload probiert?

Kein Update oder sonstiges am PI gemacht?

**Comment by sapcons** [comment]
Hallo. Ich habe verschiedene Browser getestet und auch verschiedene Geräte. Überall das gleiche Ergebnis. Wie wird denn ein Forced Reload bei einem MAC mit MS Remote Desktop gemacht? Ich habe via ssh 'sudo service ssh reload' gemacht.... reicht das? danke.
Update habe ich gemacht, NACHDEM ich gemerkt habe, dass ich keinen Zugriff mehr habe.

**Comment by wendy2702** [comment]
Mit Chrome probiert und dort den Cache mal gelöscht?

Forced Reload ist im Browser das gleichzeitige drücken von "STRG+F5"

Was kommt bei:

`sudo pivccu-attach tail -f /var/log/hmserver.log`

**Comment by sapcons** [comment]
da kommt nicht viel 

<img width="510" alt="image" src="https://user-images.githubusercontent.com/19777656/125936343-711a91f7-db4c-47a5-bb7d-654f8de226f7.png">

Browser Cache habe ich gelöscht. leider keine Änderung

**Comment by wendy2702** [comment]
hast du den PI nach dem upgrade mal neu gestartet? Je nachdem von welcher Version zu welcher das Upgrade gemacht wurde bedarf es 2 restarts.

**Comment by sapcons** [comment]
Gerade noch mal neu gestartet. Unverändert.

**Comment by wendy2702** [comment]
Wie lange hast du nach dem restart gewartet? Je nach PI und update werden da einige Module neu gebaut, kann schonmal dauern.

Kannst du dich per SSH oder FTP mit der CCU 192.168.253.2 verbinden und schauen ob du im Verzeichnis 

`/var/log/`

eine oder mehrere Dateien mit dem Namen "hmserver.log" findest.

Was kommt denn jetzt bei:

```
sudo pivccu-info
sudo pivccu-attach cat /var/hm_mode
sudo pivccu-attach cat /var/log/hmserver.log
```

**Comment by sapcons** [comment]
Der Pi ist über WLAN eingebunden und verwendet die Bridge. Die IP ist daher eine andere. hmserver.log gibt es leider nicht. Ansonsten kommt das:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/19777656/125939576-7b5b5add-b698-4d24-b858-76d020108d44.png">

<img width="508" alt="image" src="https://user-images.githubusercontent.com/19777656/125939687-29bcd86a-d6cb-49b5-ac6b-67b5e7fab31f.png">

**Comment by dicer** [comment]
How about `sudo pivccu-attach ps ax` ?

**Comment by sapcons** [comment]
Hello, thanks for all your support. Only a restore could solve the problem. In the meantime, I have also updated the new system to the latest versions (OS and apps) and it's still running without problems. Thanks again.
