### ISSUE TITLE
Update/Upgrade not working?

### ISSUE THREAD

**Issue by scholzmichael** [alexreinert/piVCCU#388]
Hi, I'm running 2.57.5-65 piVCCU on a pi3B+, which is working fine. Now I wanted to upgrade to a 2.59.7.(as shown in github)
But it doesn't update the piVCCU on my system when doing a  "apt update && sudo apt upgrade". Everything else on the pi does the update/upgrade procedure.
When trying to manual do another install with "sudo apt install pivccu" it comes back with:
"pivccu ist schon die neueste Version (2.57.5-65)"
I'm a bit confused....:)

**Comment by alexreinert** [comment]
Normally I have a canary period of 2 weeks after a new release before I copy the version into the stable APT repository. Last week I forgot to do that copy task. Please try again.

**Comment by scholzmichael** [comment]
Thanx, now it's upgrading, perfect.
