### ISSUE TITLE
Install doesn't work

### ISSUE THREAD

**Issue by Jensilein** [alexreinert/piVCCU#39]
Hello, 

I'm not able to install pivccu on my Pi3. Each time I enter "sudo apt install pivccu-modules-raspberrypi" the Pi starts hanging after a while and crashes. Currently I do not have installed the HM-MOD-RPI-PCB in that Pi. Maybe that can be the reason for the crashs?

Kind regards,
Jens

**Comment by alexreinert** [comment]
Missing radio module should not be the reason.
Can you please explain what you exactly mean with hanging and crashing? Do you have an screenshot?

**Comment by Jensilein** [comment]
Hanging/crashing means that the Pi completely freezes and has to be restarted.

**Comment by Jensilein** [comment]
Yes, I did ping it. I currently performe a kernel update as you proposed and will try again to install pivccu then. I will give feedback afterwards.

**Comment by alexreinert** [comment]
ok, in that case I will close here as it is duplicate.

**Comment by Jensilein** [comment]
OK, then I obviously have to wait for a new image...
