### ISSUE TITLE
Not able to add new HmIP devices RPi4 with RPI-RF-MOD

### ISSUE THREAD

**Issue by grisumedia** [alexreinert/piVCCU#391]
Hi everyone,

here is another person having problems to add new HmIP devices to his piVCCU system.
The communication with my existing Hm and HmIP devices is possible without issues (I added them using a backup when I switched to piVCCU), but now I have two new HmIP-SWDO door/window contacts and I am unable to find them using the WebUI, either with or without Internet.
I assume that there is no hardware problem as I installed raspberrymatic on a second card and with that setup I was able to find the new sensors in seconds.

My hardware: Raspberry Pi 4B with PRI-RF-MOD running Raspbian GNU/Linux 10 (buster) and piVCCU 3.59.6

```
~> sudo pivccu-info
piVCCU version: 3.59.6-59
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  5A4993FE77
 Radio MAC:     0xFFFE77
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F5A4993FE77
 Radio MAC:     0xBFA126
State:          RUNNING
PID:            1083
IP:             192.168.255.1
CPU use:        4956.83 seconds
BlkIO use:      173.41 MiB
Link:           vethpivccu
 TX bytes:      532.36 MiB
 RX bytes:      375.55 MiB
 Total bytes:   907.91 MiB
```

in /boot/config.txt
```
[all]
dtoverlay=pi3-disable-bt
dtoverlay=pivccu-raspberrypi
```

I also uploaded a log file of one of the attempts, but I'm not able to identify problems in there. [homematic-ccu3-2021-09-03.log](https://github.com/alexreinert/piVCCU/files/7103530/homematic-ccu3-2021-09-03.log)

If there is any information required beyond that, please let me know.

Thank you very much in advance!

**Comment by alexreinert** [comment]
The Raspi 4B produces a lot of radio interference on 868MHz. As HmIP uses Listen-Before-Talk this interference disrupt transmissions from the Pi to the devices while receiving signals from the devices are still possible. Depending on kernel versions and used hardware this interference is sometime stronger.
Only way to fix this is at least 50cm distance between Rapsi 4B and the radio module.

**Comment by grisumedia** [comment]
Thank you for your quick reply!
But how could I get distance between the RPi4 and the PRI-RF-MOD sitting on the board? I already use an external antenna and the communication with existing devices works without any flaw.
If there is interference, why does it work reproducible to add the devices using raspberrymatic with exactly the same hardware?

**Comment by jens-maus** [comment]
> If there is interference, why does it work reproducible to add the devices using raspberrymatic with exactly the same hardware?

This IMHO is pure coincidence. There are also numerous users with a Pi4 and having the exact same symptoms like you describe here. Thus, the only sensible way to get this resolved is to either switch over to a Pi3 or use any of the great HB-RF-USB  adapter PCB to connect the RPI-RF-MOD either via a long USB cable or (in case of the HB-RF-ETH) via LAN interconnection.

**Comment by grisumedia** [comment]
As so often with technology, you try for days and when you ask for help, it finally works. Wow, that is quite annoying not having changed anything.
The RPi4 is obviously quite flaky. Thank you for your hints how to solve it in the future!

**Comment by jens-maus** [comment]
@grisumedia One additional comment/idea. You could also try to switch off the USB power of a RaspberryPi4 altogether using the `uhubctl` tool (see https://github.com/mvp/uhubctl#raspberry-pi-4b). I don't know if this might help, but you could at least try to see if this lowers the radio interference.

**Comment by grisumedia** [comment]
Disabling USB power will make it impossible to use any USB device, right?
I'd like to use an SSD as system drive connected via USB and especially my ConBee for ZigBee devices which was the main reason I switched from raspberrymatic to piVCCU to be able to use multiple services on one device.
I previously used the USB 3 port of the RPi 4 to connect the SSD (but also the USB Thumb drive I connected for testing), but probably using only the two USB 2 ports is already an improvement. Still a bit disappointing that it is not possible to use the full potential of the RPi 4 without have such issues.

**Comment by jens-maus** [comment]
> Disabling USB power will make it impossible to use any USB device, right?

That's right! Using that command will disable and power-off ALL USB ports on a RaspberryPi4 (so all USB2 und USB3 ports). Nevertheless, it would be great if you could quickly test this in your installation (as you are currently seeing these issues) and then report back if powering the USB ports off helps. This could then at least help users which do not require the USB ports to be active.

> Still a bit disappointing that it is not possible to use the full potential of the RPi 4 without have such issues.

I fully agree here. Even thought the RaspberryPi4 got full CE, etc. approval it seems to be a quite hard radio jammer in its near vicinity and the fact that the RPI-RF-MOD is usually positioned directly on the GPIO makes it quite hard for the RPI-RF-MOD to reach its homematic devices. Therefore, if you require USB connectivity you have to use a HB-RF-USB-2 device to connect the RPI-RF-MOD using a 1-2 meter long USB cable so that the rf module are far enough away from the Pi4 for it to not interfere anymore with the 868MHz communication of the RPI-RF-MOD.

**Comment by jens-maus** [comment]
@grisumedia One further notice (as per discussion here: https://homematic-forum.de/forum/viewtopic.php?f=65&t=69421&p=677426#p677418). Can you please test to simply make sure **nothing** is connected to the blue USB3 ports? As it seems the radio interference is mostly covered by the USB3 connectivity of the Pi4. So please make sure to only use the two black USB2 ports of the Pi4 and see if then you can teach-in HmIP devices correctly. At least my own tests show a positiv change by this.

**Comment by grisumedia** [comment]
I really would like to test this, but now the problem is not reproducible any more, even when USB is switched on and the blue USB3 ports are in use.
But I will definitively keep in mind that I won't use the blue ports again, especially when I'm going to add another device.
Thank you very much for the great support!
