### ISSUE TITLE
pivccu nicht mehr erreichbar nach netzwerk restart

### ISSUE THREAD

**Issue by williwacker** [alexreinert/piVCCU#395]
Hatte gestern wieder das Problem, dass mein Raspberry gelaufen ist, Netzwerk Lampen haben sauber geblinkt, aber ich konnte nicht per SSH und CCU-WebUI darauf zugreifen.
Nach Recherche im RPi Forum hab ich ein script gefunden, welches den Router pingt und bei nicht erreichen das Netzwerk neu startet mit  `/etc/init.d/networking restart`
Danach ist aber die CCU nicht mehr erreichbar.
Was muss ich denn machen, um dieses Netzwerk auch noch neu zu starten?

**Comment by williwacker** [comment]
Hi Alex,
This was a question.  What further activity are you expecting?

**Comment by alexreinert** [comment]
Das ist eine automatische Meldung, wenn in einem Issue zu lange keine Aktivität ist.
`/etc/init.d/networking restart` startet auch die Bridge br0 neu, wodurch der CCU Container komplett vom Netzwerk abgeklemmt wird. Das kann man nur durch einen kompletten Neustart des Containers beheben.

Wenn das Problem nochmal auftritt: Bitte mal `dmesg | less` auf dem Pi ausführen und durchscrollen. Ich vermute stark, dass dort eine Meldung kommen wird mit Undervoltage. Bei dieser Unterspannung werden USB Geräte deaktiviert und bei fast allen Versionen des Pis ist das Netzwerk intern per USB angebunden. In dem Fall ist das Netzteil zu schwach bzw. liefert keine saubere Spannung.
