### ISSUE TITLE
Kein anlernen von HM-IP Produkten

### ISSUE THREAD

**Issue by 19DKS89** [alexreinert/piVCCU#396]
Hallo. Wir können mit der aktuellen (als auch vorherigen) Versionen der pivccu 2.xx Versionen keinerlei IP Produkte anlernen und wissen einfach nicht weiter. Sie lassen sich einfach nicht verbinden. 

Andere Standard HM Akteure sind kein Problem. 

Einmal hat es mit einem Türkontakt geklappt aber die Verbindung war sofort nach dem anlernen weg und wir mussten es manuell wieder rausschmeißen. 

Haben Sie da eine Idee. Vielen Dank VG

**Comment by 19DKS89** [comment]
okay alles klar wird mal versucht. Das sollte aber ggf. aber nur das Problem mit anlernen mit aktiven Internet lösen, dass ganze sollte aber offline ablaufen....Danke für die Mühe

**Comment by 19DKS89** [comment]
Da ist mir noch etwas eingefallen. Ist es möglich mit zwei Antennen am Raspi zu arbeiten und diese so zu konfigurieren das mit HM-MOD-RPI-PCB nur HM Geräte angesprochen werden und mit HmIP-RFUSB nur die IP Geschichten. Normalerweise sollte ja die erstgenannte "Antenne" beides können aber eine Umstellung sollte ja eigentlich ja kein Problem sein oder? Vielen Dank für die Mühe

**Comment by alexreinert** [comment]
Diese Kombination hat bei meinen Tests nicht zuverlässig funktioniert, ist allerdings auch schon eine Weile her, dass ich das getestet habe.
Ganz allgemein ist der HmIP-RFUSB eine ziemliche Krücke und wird von eQ-3 massiv stiefmütterlich behandelt.

**Comment by 19DKS89** [comment]
Ich bin nun wahrscheinlich drauf gekommen, dass nicht nur der 4er Raspi sondern auch andere ziemliche Störquellen sind für die PCB Sendeeinheit. Somit müsste man, wie bekannt, das Sendemodul extra betreiben und da gibt es ja diverse Beispiele wie man das machen kann. Ein anlernen der ip aktoren an eine klassische ccu(2) mit/ohne Internet Verbindung gelingt ja ohne Probleme. Somit bleibt nur das Sendemodul....

**Comment by rjohenne** [comment]
Ich habe exakt dasselbe Problem. Ich habe mal in der Vergangenheit einen HM IP Unterputzaktor angelernt - kein Problem. 

Jetzt der Bewegungsmelder HmIP-SMO-2: kein Objekt im Postkorb. Beide Anlern-Varianten probiert, Anlernvorgang wie oben empfohlen.  Unter /var/lib/piVCCU3/userfs/etc/config/crRFD/data sind Dateien mit der SGTIN erstellt worden, irgendeine Art der Verbindung scheint also statt zu finden.

![image](https://user-images.githubusercontent.com/95145575/143719564-075793f8-0a8d-4b4d-9d1f-dd21b172ae61.png)

**Comment by rjohenne** [comment]
Ich habe exakt dasselbe Problem. Ich habe mal in der Vergangenheit einen HM IP Unterputzaktor angelernt - kein Problem.

Jetzt der Bewegungsmelder HmIP-SMO-2: kein Objekt im Postkorb. Beide Anlern-Varianten probiert, Anlernvorgang wie oben empfohlen. Unter /var/lib/piVCCU3/userfs/etc/config/crRFD/data sind Dateien mit der SGTIN erstellt worden, irgendeine Art der Verbindung scheint also statt zu finden.

![image](https://user-images.githubusercontent.com/95145575/143719664-e445ed96-471e-441c-90bc-dd51a31da9da.png)

**Comment by galaxis1309** [comment]
Hallo Alex, ich habe leider exakt das gleiche Problem, 2 HMIP Geräte versucht anzulernen, ohne Erfolg (HMIP-PSM, HMIP-RC8),
Modul RPI-RF-MOD, auf RPI4, piVCCU3: 3.61.6-62
![image](https://user-images.githubusercontent.com/62621357/144721171-f4400c89-19c4-4ff5-a89f-7ae9c3da09e2.png)

Im Verzeichnis /var/lib/piVCCU3/userfs/etc/config/crRFD/data  werden die dev dateien für die Geräte sofort nach dem Drücken auf "Anlernen" angelegt, d.h. die RF Kommunikation schein zu funktionieren, DNS Server auch schon auf 8.8.8.8 gestellt, mehrmals Werksreset durchgeführt und sogar piVCCU3 komplett neu aufgesetzt.

Gibt es eine Möglichkeit mehr LOG Ausgabe zu produzieren um das Problem weiter einzugrenzen ?

Vielen Dank im Voraus
Martin

**Comment by alexreinert** [comment]
Wie bereits oben geschrieben, der Pi4 ist ein massiver Störsender. HmIP nutzt Listen Before Talk, es wird also nur gesendet, wenn der Funkkanal frei ist und durch den Störnebel vom Pi4 ist der Kanal für das Funkmodul nicht frei und es wird keine Antwort auf den Request vom anzulernenden Gerät gesendet.
Einzige Möglichkeit das (stabil) zu lösen, sind mind 50cm, besser 1m Luft zwischen Pi und Funkmodul, z.B. per HB-RF-USB-2.

**Comment by rjohenne** [comment]
Ich habe für mich das Problem gelöst, aber nicht wirklich die Ursache gefunden. Ich habe am Hardware-Setting oder Lokation nichts geändert. Bisher hatte ich das Image mit Raspberian + piVCCU hier von Alex im Einsatz. Jetzt habe ich mir die letzte aktuelle Raspberian Buster Version genommen, die Installation wie hier von Alex beschrieben angepasst und piVCCU installiert. Jetzt ist koppelt sich mein HmIP Gerät wie erwartet, auch nachdem ich meine Sicherung für die CCU zurückgespielt habe.

**Comment by manoloxxl** [comment]
Habe, nach einem Update der CCU, nun auch das Problem. Den Tipps aus diesem Beitrag bin ich gefolgt, jedoch ohne Besserung.

Neben dem nicht mehr möglichen (neu)anlernen von HMIP Aktoren habe ich zudem bei allen HMIP Aktoren "Gerätekommunikation gestört".

Gibt es weitere Möglichkeiten das Problem einzugrenzen?


@rjohenne Du bist der komplett manuellen Anleitung gefolgt?
https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md

**Comment by rjohenne** [comment]
@manoloxxl Ja, alle Schritte die für mich relevant waren (bezgl. richtigem Funk-Modul, kein Bluetooth, kein WLAN). Das war zwar noch die vorige Version der Anleitung aber im Grundsatz ist es ja das gleiche. Seitdem läuft mein System wieder einwandfrei.

**Comment by manoloxxl** [comment]
Ich muss doch noch mal korrigieren. Es scheint bei mir doch etwas anderes zu sein. Nach dem ich die CCU an anderer Stelle aufgestellt habe, geht es.
Ich hab auch gesehen, das meine Config Einträge zum WLAN & BT deaktivieren weg waren.

Bisher dachte ich, die Nähe zur FRITZ!Box wäre egal, daher völlig andere Frequenzen. Das ein Update das Raspy empfindlicher macht, wäre mir auch neu.

Da muss ich wohl mal schauen, was genau den Fehler auslöst.
