### ISSUE TITLE
Pivccu Bridge Interface / Wirecard VPN

### ISSUE THREAD

**Issue by theghostronaut** [alexreinert/piVCCU#397]
Ich habe auf meinem Raspberry Pi pivCCU installiert und bin der manuellen Installationsanleitung gefolgt. Unter Punkt 8 wird ein Bridge Interface hinzugefügt und eine statische IP vergeben:

```
auto lo
iface lo inet loopback

iface eth0 inet manual

auto br0
iface br0 inet static
  bridge_ports eth0
  address <address>
  netmask <netmask>
  gateway <gateway>
  dns-nameservers <dns1> <dns2>
```

Es funktioniert auch alles problemlos.

Nun möchte ich zusätzlich zu pivCCU ein Wireguard VPN auf meinem Pi laufen lassen.
Dies habe ich über piVPN installiert. Das Problem was ich nun habe, ist: Ich kann, solange das Bridge Interface eingerichtet ist, über den VPN nur auf die IP meines Raspberry Pi zugreifen, nicht auf den Rest des Netzwerks. Das funktioniert laut Wireguard Reddit nicht, weil Wireguard kein Layer 2 Bridging unterstützt.

Wenn ich das Bridge Interface entferne und die statische Adresse ganz normal über eth0 einrichte, funktioniert der VPN – aber eben pivCCU nicht mehr.

Nun meine Frage: Kann ich pivCCU anders einrichten, und auf das Bridge Interface verzichten, damit ich auch mein VPN nutzen kann?

**Comment by alexreinert** [comment]
Welches Interface wurde bei der Installation von piVPN ausgewählt? Wenn hier eth0 gewählt wurde, würde es das Problem erklären. Meines Wissens nach funktioniert es einwandfrei, wenn br0 gewählt wird.
