### ISSUE TITLE
Fehler bei manueller Installation

### ISSUE THREAD

**Issue by kedvsk** [alexreinert/piVCCU#40]
Raspberry PI 3
Debian Jessie lite, 4.9.59-v7+
...
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu.service -> /lib/systemd/system/pivccu.service.
Job for pivccu.service failed because the control process exited with error code.
See "systemctl status pivccu.service" and "journalctl -xe" for details.

systemctl status pivccu.service

* pivccu.service - piVCCU
   Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-04-02 23:33:11 CEST; 1min 34s ago
  Process: 6263 ExecStart=/var/lib/piVCCU/start_container.sh (code=exited, status=1/FAILURE)
      CPU: 16ms

Apr 02 23:33:11 XXX systemd[1]: Starting piVCCU...
Apr 02 23:33:11 XXX start_container.sh[6263]: <11>Apr  2 23:33:11 piVCCU: Could not load kernel modules plat_eq3ccu2 and eq3_char_loop.
Apr 02 23:33:11 XXX systemd[1]: pivccu.service: Control process exited, code=exited status=1
Apr 02 23:33:11 XXX systemd[1]: Failed to start piVCCU.
Apr 02 23:33:11 XXX systemd[1]: pivccu.service: Unit entered failed state.
Apr 02 23:33:11 XXX systemd[1]: pivccu.service: Failed with result 'exit-code'.

journalctl -xe

 Subject: Unit pivccu.service has begun start-up
 Defined-By: systemd
 Support: https://www.debian.org/support

 Unit pivccu.service has begun starting up.
Apr 02 23:33:11 XXX piVCCU[6265]: ***Could not load kernel modules plat_eq3ccu2 and eq3_char_loop***.
Apr 02 23:33:11 XXX start_container.sh[6263]: <11>Apr  2 23:33:11 piVCCU: Could not load kernel modules plat_eq3ccu2 and eq3_char_loop.
Apr 02 23:33:11 XXX systemd[1]: pivccu.service: Control process exited, code=exited status=1
Apr 02 23:33:11 XXX systemd[1]: Failed to start piVCCU.
 Subject: Unit pivccu.service has failed
 Defined-By: systemd
 Support: https://www.debian.org/support

 Unit pivccu.service has failed.

 The result is failed.
Apr 02 23:33:11 XXX systemd[1]: pivccu.service: Unit entered failed state.
Apr 02 23:33:11 XXX systemd[1]: pivccu.service: Failed with result 'exit-code'.

**Comment by alexreinert** [comment]
Wurde nach der Installation der Kernel Module ein Reboot gemacht?

**Comment by kedvsk** [comment]
Ja, genau nach Anleitung.

**Comment by alexreinert** [comment]
Bitte mal die Ausgabe von
```sudo dpkg-reconfigure pivccu-modules-dkms```

**Comment by alexreinert** [comment]
Aif dem Pi sind sowohl Kernel 4.9.59 (alter stable, vermutlich deb Package) als auch 4.14.30 (vermutlich rpi-update) installiert. Allerdings sind nur die Header für 4.14.30 installiert. Die Header für 4.9.59 sind leider nicht mehr als deb Paket verfügbar.
Entweder muss mit apt ein Update auf den aktuellen stable Kernel durchgeführt werden (meine Empfehlung) oder mit rpi-update der testing Kernel aktiviert werden.

**Comment by kedvsk** [comment]
Sieht schon ganz gut aus. Mir ist nur noch nicht klar, warum per DHCP eine neue Adresse gezogen wird. Der Rechner ist weiterhin unter der .222 Adresse erreichbar, hat sich aber zusätzlich eine .35 gezogen. Wird eine zweite Adresse benötigt und wenn ja, warum wird die konfigurierte nicht übernommen?

source-directory /etc/network/interfaces.d                                   
                                                                             
auto lo                                                                      
iface lo inet loopback                                                       
                                                                             
#auto eth0                                                                   
#allow-hotplug eth0                                                          
iface eth0 inet manual                                                       
auto br0                                                                     
iface br0 inet static                                                        
bridge_ports eth0                                                            
address 192.168.178.222                                                      
netmask 255.255.255.0                                                        
gateway 192.168.178.1                                                        
dns-nameservers 192.168.178.1

**Comment by alexreinert** [comment]
Das System hat zwei Adressen: Einmal der Raspi selber und zusätzlich eine für den LXC Container mit der (virtuellen) CCU. Die CCU ist quasi ein Computer im Computer.

Die Adresse der CCU kann über das Webinterface der CCU geändert werden, die Adresse von Raspi selber innerhalb der interfaces Datei.

**Comment by alexreinert** [comment]
Ist noch was offen, oder kann hier zugemacht werden?

**Comment by kedvsk** [comment]
Das Problem im Titel ist behoben.
