### ISSUE TITLE
server certificate verification failed

### ISSUE THREAD

**Issue by Skol6** [alexreinert/piVCCU#401]
Hi,

mach ich hier was falsch oder fehlen Daten am Server
`Err:6 https://www.pivccu.de/piVCCU stable Release server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates                            .crt CRLfile: none
Reading package lists... Done
E: The repository 'https://www.pivccu.de/piVCCU stable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

`

**Comment by alexreinert** [comment]
https://homematic-forum.de/forum/viewtopic.php?t=69901

**Comment by Skol6** [comment]
Vielen Dank! Und ich such seit Tagen...
