### ISSUE TITLE
https://www.pivccu.de/ down

### ISSUE THREAD

**Issue by stahni** [alexreinert/piVCCU#403]
Die Seite ist nicht mehr erreichbar. Schlüssel kann nicht geladen werden.

**Comment by alexreinert** [comment]
Ich kann aktuell keine Störung erkennen. Was ist die genaue Fehlermeldung?

**Comment by stahni** [comment]
Hallo ich hatte es mir Browser (Fehlermeldung nicht erreichbar) und wget
(keine Reaktion) versucht leider war die Seite nicht erreichbar.

Ich versuche es heute Abend nochmal.

MFG Stahn

Alexander Reinert ***@***.***> schrieb am Do., 18. Nov. 2021,
08:10:

**Comment by t0mcat1337** [comment]
Kann ich bestätigen, apt update schlägt fehl:

# apt update
[...]
E: The repository 'https://www.pivccu.de/piVCCU stable Release' does no longer have a Release file.

Evtl. wegen abgelaufenem Zert? Curl sagt jedenfalls so was:

# curl https://www.pivccu.de/piVCCU/public.key
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

# curl https://www.pivccu.de/piVCCU
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

**Comment by t0mcat1337** [comment]
Oha, da könntest du recht haben :D

**Comment by stahni** [comment]
Hallo zusammen,

Seite funktioniert wieder.

Mfg Stahn

t0mcat1337 ***@***.***> schrieb am Do., 18. Nov. 2021, 16:52:

**Comment by gelsas** [comment]
Kann derzeit pivccu.de nicht erreichen. Auch laut downforeveryoneorjustme und vergleichbaren services derzeit nicht erreichbar.

**Comment by alexreinert** [comment]
Neue Probleme in bereits geschlossene Issues einzutragen ist nicht ganz zielführend, weil die dann gerne übersehen werden, bitte beim nächsten Mal einen neuen Issue aufmachen.
pivccu.de läuft wieder.
