### ISSUE TITLE
Certificate is expired

### ISSUE THREAD

**Issue by xeetsh** [alexreinert/piVCCU#404]
The certificate used for the installation seems to be expired.
![grafik](https://user-images.githubusercontent.com/1765166/142782456-f0679d5f-2cc5-486e-b66f-9fc04c6bb0c0.png)

**Comment by alexreinert** [comment]
No, it is not. But your system is missing the current Let's Encrypt root certificate.

**Comment by xeetsh** [comment]
My bad. You are totally right! Works a charm now!
