### ISSUE TITLE
Error during install RPI

### ISSUE THREAD

**Issue by maltejahn** [alexreinert/piVCCU#405]
Hi,

*** After writing the whole text below I did: reboot/uninstall/new install i tried the fake device. The installation worked fine
does this mean its probably a hardware issue? 
if not.......*****

i tried to install a HM-RF-USB2 since a few days. It runs a "volkszähler" image using a FTDI uart bridge to read out a power meter. But I dont see how this should affect piVCCU
> uname -a
Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux

I bought a new powersupply because i got some undervoltage error, now they disappered. Checked with

> dmesg | grep undervoltage

I can see the uart:

> s -la /dev/raw-uart*
crw------- 1 root root 240, 0 Nov 25 15:39 /dev/raw-uart
crw------- 1 root root 240, 1 Nov 25 15:39 /dev/raw-uart1

with 
>sudo cat /dev/raw-uart1
i expected some kind of crazy output - nothing appears

Bridge seems to work?
> ifconfig
br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.247  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::ba27:ebff:feff:ec6d  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:ff:ec:6d  txqueuelen 1000  (Ethernet)
        RX packets 18560  bytes 3222106 (3.0 MiB)
        RX errors 0  dropped 4660  overruns 0  frame 0
        TX packets 12877  bytes 1428564 (1.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

>eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether b8:27:eb:ff:ec:6d  txqueuelen 1000  (Ethernet)
        RX packets 20570  bytes 3692674 (3.5 MiB)
        RX errors 0  dropped 309  overruns 0  frame 0
        TX packets 12891  bytes 1429320 (1.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

>lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 12619  bytes 1954529 (1.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12619  bytes 1954529 (1.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

with 

> cat /etc/network/interfaces
source-directory /etc/network/interfaces.d
auto lo
iface lo inet loopback
iface eth0 inet manual
auto br0
iface br0 inet static
  bridge_ports eth0
  address 192.168.0.247
  netmask 255.255.255.0
  gateway 192.168.0.1
  dns-nameservers 192.168.0.1 8.8.8.8

boot/config.txt content:
>dtparam=i2c_arm=on
dtparam=spi=off
dtparam=audio=on
[pi4]
dtoverlay=vc4-fkms-v3d
max_framebuffers=2
[all]
enable_uart=1
max_usb_current=1
dtoverlay=pi3-disable-bt
dtoverlay=pivccu-raspberrypi`

Trying to install
>sudo apt install pivccu3 

> Which radio module should be used? Tried first option
-> no selection showed, just like i have seen on other peoples (expected to select ..raw-uart1)

gives me a
>dpkg: error processing package pivccu3 (--configure):
 installed pivccu3 package post-installation script subprocess returned error exit status 1
Setting up lxcfs (3.0.3-2) ...
Setting up uidmap (1:4.5-1.1) ...
Setting up lxc-templates (3.0.4-0+deb10u1) ...
Setting up dnsmasq-base (2.80-1+rpt1+deb10u1) ...
Setting up qemu-utils (1:3.1+dfsg-8+deb10u8) ...
Setting up arch-test (0.15-2+deb10u1) ...
Setting up cloud-image-utils (0.29-1) ...
Processing triggers for dbus (1.12.20-0+deb10u1) ...
Processing triggers for libc-bin (2.28-10+rpt2+rpi1) ...
Processing triggers for systemd (241-7~deb10u8+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 pivccu3
E: Sub-process /usr/bin/dpkg returned an error code (1)
W: Operation was interrupted before it could finish

Trying to change setting with
>sudo dpkg-reconfigure pivccu3
/usr/sbin/dpkg-reconfigure: pivccu3 is broken or not fully installed

I tried  to do a new install with
>sudo apt remove --purge pivccu3

but 
>dpkg: error processing package pivccu3 (--configure):
 installed pivccu3 package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 pivccu3
E: Sub-process /usr/bin/dpkg returned an error code (1)

After a reboot i was able to remove it. The last thing i tried was
>sudo dpkg-reconfigure pivccu-modules-dkms
/var/lib/dpkg/info/pivccu-modules-dkms.postinst: line 9: /var/lib/piVCCU/dkms/ensure_modules.sh: No such file or directory

Im totally lost in where to debug this

any concerns about this

> 24.466606] br0: port 2(vethpivccu) entered blocking state
[   24.466614] br0: port 2(vethpivccu) entered forwarding state
[   24.727099] br0: port 2(vethpivccu) entered disabled state

**Comment by alexreinert** [comment]
"Was able to remove" means you deleted the whole folder using rm?
Which radio module are you using on top of the HB-RF-USB-2?

**Comment by maltejahn** [comment]
HI,

so much text but still some things a re missing:
It´s a HB-RF-USB-2
>[    4.224916] usb 1-1.2: new full-speed USB device number 4 using dwc_otg
[    4.244875] NET: Registered protocol family 10
[    4.249209] Segment Routing with IPv6
[    4.344455] systemd[1]: systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
[    4.362341] usb 1-1.2: New USB device found, idVendor=10c4, idProduct=8c07, bcdDevice= 1.01
[    4.363637] systemd[1]: Detected architecture arm.
[    4.372972] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.372985] usb 1-1.2: Product: HB-RF-USB-2
[    4.372997] usb 1-1.2: Manufacturer: Alexander Reinert
[    4.373009] usb 1-1.2: SerialNumber: 1cd..

The command, which now works
>sudo dpkg-reconfigure pivccu-modules-dkms
- Output at the end of this post
- got alot of messages like 
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty

After this i did a "new" sudo apt install pivccu3. Now runs without issues (no selection screen appeared during this installation command):

> sudo pivccu-info
> piVCCU version: 3.59.6-59
> Kernel modules: Available
> Raw UART dev:   Available
> Rasp.Pi UART:   Assigned to GPIO pins
> HMRF Hardware:  FAKE_HMRF
>  Board serial:  FKE9646052
>  Radio MAC:     0xff34d4
> HMIP Hardware:  FAKE_HMRF
>  SGTIN:         3014F711A061A7D5699DAB52
>  Radio MAC:     0xff34d4
> State:          RUNNING
> PID:            1852
> CPU use:        0.73 seconds
> Link:           vethpivccu
>  TX bytes:      4.05 KiB
>  RX bytes:      5.31 KiB
>  Total bytes:   9.36 KiB

Trying so switch to "HmIP-RFUSB (HmIP only)"  with sudo dpkg-reconfigure pivccu3 command (which takes a few minutes until the selection screen appears)
This time i can select something, but this is the FTDI device
>Which USB devices should be available inside the CCU?   [ ] /dev/ttyUSB0 (FTDI_FT232R_USB_UART_A9077Z9G) 
selected nothing

Of course pivccu-info still uses the fake device.

As the usb-uart device doesnt appear in the list, i think it isnt a hardware issue at this point (even if the HM module doenst work properly)?????


Here is the long output mentioned above
>  sudo dpkg-reconfigure pivccu-modules-dkms
> Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.
> Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
> Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
> 
> -------- Uninstall Beginning --------
> Module:  pivccu
> Version: 1.0.64
> Kernel:  5.10.63-v7+ (armv7l)
> -------------------------------------
> 
> Status: Before uninstall, this module version was ACTIVE on this kernel.
> 
> dummy_rx8130.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> dw_apb_raw_uart.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> eq3_char_loop.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> fake_hmrf.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> generic_raw_uart.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> hb_rf_eth.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> hb_rf_usb-2.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> hb_rf_usb.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> led_trigger_timer.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> meson_raw_uart.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> pl011_raw_uart.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> plat_eq3ccu2.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> rpi_rf_mod_led.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove 'kernel/drivers/pivccu': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> 
> rtc-rx8130.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> rmdir: failed to remove directory 'kernel/drivers': Directory not empty
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> 
> depmod....
> 
> DKMS: uninstall completed.
> 
> ------------------------------
> Deleting module version: 1.0.64
> completely from the DKMS tree.
> ------------------------------
> Done.
> 
> Creating symlink /var/lib/dkms/pivccu/1.0.64/source ->
>                  /usr/src/pivccu-1.0.64
> 
> DKMS: add completed.
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area...
> make -j4 KERNELRELEASE=5.10.63-v7+ ARCH=arm all........
> cleaning build area...
> 
> DKMS: build completed.
> 
> dummy_rx8130.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> dw_apb_raw_uart.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> eq3_char_loop.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> fake_hmrf.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> generic_raw_uart.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> hb_rf_eth.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> hb_rf_usb-2.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> hb_rf_usb.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> led_trigger_timer.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> meson_raw_uart.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> pl011_raw_uart.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> plat_eq3ccu2.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> rpi_rf_mod_led.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> rtc-rx8130.ko:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
> 
> depmod...
> 
> DKMS: install completed.
> Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
> Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
> Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
> 
> 


content kernel driver
>pi@raspberrypi:~ $ ls /lib/modules/5.10.63-v7+/kernel/drivers/pivccu/
>dummy_rx8130.ko     eq3_char_loop.ko  generic_raw_uart.ko  hb_rf_usb-2.ko  led_trigger_timer.ko  pl011_raw_uart.ko  rpi_rf_mod_led.ko
>dw_apb_raw_uart.ko  fake_hmrf.ko      hb_rf_eth.ko         hb_rf_usb.ko    meson_raw_uart.ko     plat_eq3ccu2.ko    rtc-rx8130.ko

**Comment by maltejahn** [comment]
I should have startet with this:

Loaded you image RaspberryPiOS_lite_piVCCU3_2020-12-07.img to the Pi. Still RPI-RF-MOD is connected to a HB-RF-USB-2

Loaded you image RaspberryPiOS_lite_piVCCU3_2020-12-07.img to the Pi. Attached the RPI-RF-MOD directly to the RPI Header.
Tried to change using sudo dpkg-reconfigure pivccu3, selected Option 1, dont select anything in the USB screen.

With 

>  sudo pivccu-info
> piVCCU version: 3.53.34-50
> Kernel modules: Available
> Raw UART dev:   Available
> Rasp.Pi UART:   Assigned to GPIO pins
> HMRF Hardware:  unknown
>  Board serial:  unknown
>  Radio MAC:     unknown
> HMIP Hardware:  unknown
>  SGTIN:         unknown
>  Radio MAC:     unknown
> State:          STOPPED
 

Probably the RPI-RF-MOD is dead?

I also disconnected the FTDI device, the LED is red (using GPIO) instead of green when using USB

I will take a closer look to the pcb...

**Comment by maltejahn** [comment]
So, i comment commented comment..

HM-RF-USB2 connected to the pi (USB) with attached HM-RF-MOD

Here at the issue tracker i found some code to get more information out of the pi:

> pi@raspberrypi:~ $ sudo detect_radio_module --debug /dev/raw-uart
> Sending HM frame: fd 00 03 fe 00 01 14 1e
> Sending HM frame: fd 00 03 00 01 00 9e 03
> Sending HM frame: fd 00 03 fe 02 01 98 1d
> Sending HM frame: fd 00 03 00 03 00 12 00
> Sending HM frame: fd 00 03 fe 04 01 8c 1d
> Sending HM frame: fd 00 03 00 05 00 06 00
> Error: Radio module was not detected

> pi@raspberrypi:~ $ sudo detect_radio_module --debug /dev/raw-uart1
> Sending HM frame: fd 00 03 fe 00 01 14 1e
> Received HM frame: fd 00 0f fe 00 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c 68 c7
> Sending HM frame: fd 00 03 fe 01 01 92 1d
> Received HM frame: fd 00 0f fe 01 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c e9 c5
> Sending HM frame: fd 00 03 fe 02 03 18 12
> Received HM frame: fd 00 04 fe 02 05 00 87 3b
> Sending HM frame: fd 00 03 00 03 00 12 00
> Received HM frame: fd 00 04 00 03 04 03 19 0e
> Sending HM frame: fd 00 03 fe 04 01 8c 1d
> Received HM frame: fd 00 0f fe 04 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c ec c0
> Sending HM frame: fd 00 03 fe 05 03 8a 11
> Received HM frame: fd 00 04 fe 05 05 00 07 54
> Sending HM frame: fd 00 03 00 06 00 0c 00
> Received HM frame: fd 00 04 00 06 04 03 19 4a
> Sending HM frame: fd 00 03 fe 07 01 86 1d
> Received HM frame: fd 00 0f fe 07 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c ef c3
> Sending HM frame: fd 00 03 fe 08 03 24 12
> Received HM frame: fd 00 04 fe 08 05 00 87 b3
> Sending HM frame: fd 00 03 00 09 00 2e 00
> Received HM frame: fd 00 04 00 09 04 03 19 86
> Error: Radio module was not detected

For me it looks like the connection between USB/UART Bridge and  RPI-RF-MOD is ok - as something is received. On the other hand no module was detected.

I will try to work on this long thread..
https://github.com/alexreinert/piVCCU/issues/329

**Comment by alexreinert** [comment]
Your RPI-RF-MOD seems to be bricked:
```
Sending HM frame: fd 00 03 fe 02 03 18 12
Received HM frame: fd 00 04 fe 02 05 00 87 3b
```
The first frame should start the App Mode, the received frame states, that the app mode cannot be startet.

**Comment by alexreinert** [comment]
You can try to reflash the module, I will provide you the command line for that later.

**Comment by maltejahn** [comment]
Hi,

just a small reminder? Is there any command to bring the RPI-RF-MOD to life?

If its not possible, do you think the problem is the RPI-RF-MOD or the HM-RF-USB2?

And one last question: Is it possible to forward a HM-RF-USB2/RPI-RF-MOD(installed to a Pi 3B+) to another Pi using a network connection (which runs Raspberrymatic/Debmatic). Like the ETH Version...

**Comment by maltejahn** [comment]
Hi,

hopefully i will never come back.. because of this error. I finally managed to get it back to life:

get the firmware for the device
`https://github.com/eq-3/occu/tree/master/firmware`

also get the update tool
`https://github.com/eq-3/occu/tree/master/HMServer-Beta/opt/HmIP`

The RPI-RF-MOD was directly attached to the pi4 with a buster x64 lite image

in my case i use this command
`sudo java -Dos.arch=armv7l -Dgnu.io.rxtx.SerialPorts=/dev/raw-uart -jar hmip-copro-update.jar -p /dev/raw-uart -o -f dualcopro_update_blhmip-4.4.12.eq3`


FINALLY:

```
pi@raspberrypi:~ $ sudo detect_radio_module /dev/raw-uart
RPI-RF-MOD 5A49940404 3014F711A0001F5A49940404 0xFF0404 0x137548 4.4.12
pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.61.7-69
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
State:          RUNNING
PID:            1266
IP:             192.168.0.29
Link:           vethpivccu
 TX bytes:      74.68 KiB
 RX bytes:      128.66 KiB
 Total bytes:   203.34 KiB


pi@raspberrypi:~ $ sudo detect_radio_module --debug /dev/raw-uart
13:32:30.951239 Sending HM frame:  fd 00 03 fe 00 01 14 1e
13:32:30.955254 Received HM frame: fd 00 11 fe 00 05 01 44 75 61 6c 43 6f 50 72 6f 5f 41 70 70 a2 21
13:32:30.955467 Sending HM frame:  fd 00 03 fe 01 02 92 17
13:32:30.958017 Received HM frame: fd 00 04 fe 01 05 01 07 02
13:32:31.064457 Received HM frame: fd 00 0e fe 00 00 48 4d 49 50 5f 54 52 58 5f 42 6c f4 c2
13:32:31.064599 Sending HM frame:  fd 00 03 fe 02 01 98 1d
13:32:31.067372 Received HM frame: fd 00 0f fe 02 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c ea c6
13:32:31.067457 Sending HM frame:  fd 00 03 fe 03 03 9e 11
13:32:31.261496 Received HM frame: fd 00 04 fe 03 05 01 87 29
13:32:33.158740 Received HM frame: fd 00 10 fe 01 00 44 75 61 6c 43 6f 50 72 6f 5f 41 70 70 b7 36
13:32:33.158982 Sending HM frame:  fd 00 03 01 04 09 00 22
13:32:33.261666 Received HM frame: fd 00 05 01 04 04 01 04 16 36
13:32:33.261838 Sending HM frame:  fd 00 03 01 05 02 06 18
13:32:33.365334 Received HM frame: fd 00 0d 01 05 04 01 04 04 0c 01 00 01 01 3c 00 35 ab
13:32:33.365567 Sending HM frame:  fd 00 03 02 06 01 0c 2e
13:32:33.368003 Received HM frame: fd 00 07 02 06 06 01 13 75 48 19 e1
13:32:33.368225 Sending HM frame:  fd 00 03 fe 07 04 86 03
13:32:33.371694 Received HM frame: fd 00 10 fe 07 05 01 30 14 f7 11 a0 00 1f 5a 49 94 04 04 47 b4
13:32:33.371951 Sending HM frame:  fd 00 03 03 08 08 28 0c
13:32:33.374312 Received HM frame: fd 00 07 03 08 01 01 00 00 00 77 5c
RPI-RF-MOD 5A49940404 3014F711A0001F5A49940404 0xFF0404 0x137548 4.4.12
```


Reattached as a USB device  + reboot

```
pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.61.7-69
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB-2@usb-0000:01:00.0-1.3 (/dev/raw-uart1)
 Board serial:  5A49940404
 Radio MAC:     0xFF0404
HMIP Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB-2@usb-0000:01:00.0-1.3 (/dev/raw-uart1)
 SGTIN:         3014F711A0001F5A49940404
 Radio MAC:     0xB8A621
State:          RUNNING
PID:            1530
IP:             192.168.0.29
Link:           vethpivccu
 TX bytes:      23.11 KiB
 RX bytes:      37.65 KiB
 Total bytes:   60.77 KiB

```
