### ISSUE TITLE
Raspberry Pi 3B with Debian 11 "apt install pivccu-modules-raspberrypi" error

### ISSUE THREAD

**Issue by nobodyman1** [alexreinert/piVCCU#407]
I want to use a HM-MOD-RPI-PCB module on the Raspberry Pi 3B with RaspberryMatic as explaned [here](https://github.com/jens-maus/RaspberryMatic/wiki/Installation-HomeAssistant#using-homeassistant-supervised).
Debian (not Raspberry Pi OS) is supported as documented [here](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#supported-operating-system-system-dependencies-and-versions).
The first steps including `apt install pivccu-modules-dkms` seemed to be working, because there are some modules in `/lib/modules/5.10.0-9-arm64/updates/dkms/` after it.

But `apt install pivccu-modules-raspberrypi` is not working.
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pivccu-modules-raspberrypi : Depends: raspberrypi-kernel-headers but it is not installable or
                                       linux-headers-raspi but it is not installable
E: Unable to correct problems, you have held broken packages.
```

1. How could this be fixed?
2. Which modules are needed to use the HM-MOD-RPI-PCB module?
3. Is there any documentation how to compile the `pivccu-modules-raspberrypi`?

**Comment by alexreinert** [comment]
Sorry, this is not a RaspberryMatic support channel.
