### ISSUE TITLE
RPi3 + Raspbian 9.4 stretch: LXC Container nicht im LAN 

### ISSUE THREAD

**Issue by MFlasskamp** [alexreinert/piVCCU#41]
Hallo,
ich habe piVCCU auf einem RaspberryPi 3 installiert wie in https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md beschrieben. Der LXC Container scheint zu laufen, alle Kernelmodule und das HM-MOD-RPI-PCB werden erkannt:
```
root@rpi3:~# pivccu-info
piVCCU version: 2.31.25-25
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
Board serial:   OEQ0607412
State:          RUNNING
PID:            639
IP:             192.168.1.225
IP:             fd7f:1b00:96f:0:b834:afff:fede:5663
CPU use:        121.68 seconds
BlkIO use:      42.24 MiB
Link:           vethpivccu
 TX bytes:      3.06 MiB
 RX bytes:      56.89 MiB
 Total bytes:   59.95 MiB
```

Allerdings scheint der Container nicht über die Bridge (br0) ins LAN zu kommen.
Weder bekommt er eine IP per DHCP (daher als Fallback nur die Homematic Default IP 192.168.1.225) noch ist ein ping an einen Host im LAN aus dem Container heraus (pivccu-attach, ping) möglich. Die IP der Bridge lässt sich aus dem Container heraus pingen, genauso der Container vom RPi.

Die Bridge br0 auf dem RPi ist angelegt und sowohl eth0 als auch vethpivccu damit verbunden:
```
root@rpi3:~# brctl show
bridge name     bridge id               STP enabled     interfaces
br0             8000.b827eb02583a       yes             eth0
                                                        vethpivccu
docker0         8000.0242d2876241       no              veth0feddc7
```
Die Bridge ist im "forwarding" state:
```
root@rpi3:~# brctl showstp br0
...
eth0 (1)
 port id                8001                    state                forwarding
 ...

vethpivccu (2)
 port id                8002                    state                forwarding
...
```

IP Forwarding ist aktiviert:
```
root@rpi3:~# cat /proc/sys/net/ipv4/ip_forward
1
```

Aus irgendeinem Grund scheint die Bridge keine Pakete zwischen den beiden Interfaces weiterzuleiten. Hat jemand eine Ideen woran das liegen könnte?

**Comment by alexreinert** [comment]
Durch die Docker Installation gibt es zwei Bridges, wodurch die Autoerkennung der Bridge nicht mehr funktioniert.
Bitte die Datei /etc/piVCCU/lxc.config editieren und bei lxc.network.link explizit die Bridge eintragen.

**Comment by MFlasskamp** [comment]
Super, vielen Dank! :-)
Nach ich in /etc/piVCCU/lxc.config die Zeile `lxc.network.link = <bridge_auto>` in `lxc.network.link = br0` geändert habe läuft nach einem Reboot jetzt alles problemlos!

**Comment by 0dev23** [comment]
Ich habe ein ähnliches Problem. Docker und piVCCU installiert, doch leider funktioniert bei mir der Tipp mit lxc.network.link = br0 nicht. Woran kann es noch liegen?

**Comment by 0dev23** [comment]
OK, konnte mir selbst helfen, indem ich in der Datei /etc/sysctl.conf das Kommentarzeichen # 
 aus der folgende Zeile entfernt habe: net.ipv4.ip_forward=1 
Anschließend bekommt der piVCCU container wieder die IP vom dhcp zu gewiesen.

**Comment by chip131001** [comment]
Hallo, ich habe bei mir nachträglich Docker installiert. Seit dem kann ich nicht auf Homematic zugreifen. Das anpassen von lxc.network.link = br0 hat auch keinen Erfolg gebracht. Auch nicht nach einem Neustart. Wie kann ich überprüfen woran es hängt?

**Comment by chip131001** [comment]
Hast du ein Tipp was ich machen kann um das Problem zu lösen?

**Comment by alexreinert** [comment]
z.B. hier: https://www.google.de/amp/blog.daknob.net/debian-firewall-docker/amp/

**Comment by mainkowitsch** [comment]
selbe Problem hier... solange Docker noch keine "Verbindung" aufgebaut hat, ist die ccu erreichbar... danach nicht mehr :( ...
