### ISSUE TITLE
Paket linux-headers-5.10.63-v8 kann nicht gefunden werden

### ISSUE THREAD

**Issue by guny74** [alexreinert/piVCCU#410]
Hallo,

ich versuche Raspberrymatic in einem Docker zu installieren.
Basis OS ist "dietpi" basierend auf Debian bullseye.

Jetzt habe ich verstanden, dass die "kernel" Modules" von Ihnen stammen (sorry wenn falsch).

Ich bekomme einen Fehler "Paket linux-headers-5.10.63-v8 kann nicht gefunden werden.", da beim "uname -r" -->  5.10.63-v8+
Ist hier irgendetwas zu neu ?

Danke

**Comment by alexreinert** [comment]
Ich habe keine Ahnung, bei welchem Schritt diese Fehlermeldung kommt, wenn man die Installation so durchführt, wie es für piVCCU und debmatic dokumentiert ist, dann kann es nicht zu dieser Fehlermeldung kommen.
Andere Systeme, welche meine Software nutzen, kann ich nicht vollumfänglich supporten.

**Comment by guny74** [comment]
Danke, verstehe ich. 

Dann werde ich es mal ins Raspberrymatic "Issue" geben.
