### ISSUE TITLE
LXC mount von devices unterbinden

### ISSUE THREAD

**Issue by DennisGaida** [alexreinert/piVCCU#411]
Ich glaube kein piVCCU Issue per se, sorry für das Verwenden eines GH issues hierfür.

Mein /var/log/messages wird zugespammt von:
```
Dec  9 11:39:12 ccu3-webui daemon.err cuxd[444]: USB(1-1.3) mknod '/dev/ttyUSB0' error!
Dec  9 11:39:12 ccu3-webui daemon.err cuxd[444]: USB(1-1.2) mknod '/dev/ttyACM0' error!
```

An USB0 & ACM0 hängen auch devices, aber keine Devices die ich nach pivccu weiterreichen möchte. Ich habe das issue hier gefunden: https://github.com/alexreinert/piVCCU/issues/36 und weiß dass es vielleicht über cgroups funktioniert in der lxc.conf? Ich wüsste aber nicht wie so eine Regel aussieht.

Ich habe mich probiert an: `lxc.cgroup.devices.deny = c 166:0`, dann startet der Container aber nicht mehr.

Wie kann ich dem pivccu Container verbieten auf /dev/ttyUSB0 & /dev/ttyACM0 zuzugreifen und somit mein Log davon zu befreien?

**Comment by alexreinert** [comment]
Alles was nicht explizit erlaubt wird, ist verboten. Allerdings kann der Container sehen, dass die Geräte grundsätzlich per USB angebunden sind und CUxD versucht diese dann anzulegen, was aber scheitert, weil sie nicht erlaubt sind.
Mit `TTYPARAM=NONE` in der Config von CUxD kann man verhinden, dass CUxD versucht sich alle angeschlossenen USB Geräte zu krallen und dann nur noch die explizit konfigurierten Geräte nutzt und auch nur für diese versucht den Device Node anzulegen, damit bekommt man die Logeinträge weg. Details dazu findet man in der CUxD Anleitung.

**Comment by DennisGaida** [comment]
Super, genau das war es.
