### ISSUE TITLE
dpkg-query: Paket »pivccu« ist nicht installiert und es ist keine Information verfügbar

### ISSUE THREAD

**Issue by wendy2702** [alexreinert/piVCCU#413]
Hi Alex,

habe gerade PiVCCU auf Bullseye neu installiert nach der Anleitung:  https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md

Wenn ich jetzt den Step: Migrating from custom kernel to original Raspbian kernel with custom modules and device tree overlay ausführen will, erhalte ich das:

`pi@pivccu:~ $ sudo dpkg -s pivccu | grep 'Version'
dpkg-query: Paket »pivccu« ist nicht installiert und es ist keine Information verfügbar
Verwenden Sie dpkg --info (= dpkg-deb --info) zum Untersuchen von Archiven.
`

Allerdings gebe ich ehrlich zu das mir nicht zu 100% klar ist ob der Schritt jetzt gemacht werden muss oder nicht.

Unabhängig davon scheint PiVCCU zu laufen:

`pi@pivccu:~ $ sudo pivccu-info
piVCCU version: 3.61.6-62
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  58A992F7B6
 Radio MAC:     0xFFF7B6
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A992F7B6
 Radio MAC:     0xB59330
State:          RUNNING
PID:            1975
IP:             192.168.178.8
Link:           vethpivccu
 TX bytes:      41.27 KiB
 RX bytes:      308.00 KiB
 Total bytes:   349.27 KiB
`

Kannst du mich bitte kurz in die richtige Richtung schubsen.

Danke und Gruß

**Comment by alexreinert** [comment]
Hast du mit rpi-update einen Custom Kernel installiert? Wenn nein, dann betrifft dich der komplette Absatz nicht. Und auch sonst: Mit dem Schritt kannst du prüfen, dass du eine piVCCU2 Version > 2.29.23-12 installierst hast, das dürftest du auch ohne den Befehl perfekt beantworten können. ;-)

**Comment by wendy2702** [comment]
OK. 

Stimmt. So einfach....habe es zu kompliziert gelesen.

Danke für die schnelle Antwort und schöne Feiertage!!!
