### ISSUE TITLE
update - 502  Bad Gateway

### ISSUE THREAD

**Issue by wineworld13** [alexreinert/piVCCU#414]
Hallo Alex,

ich bräuchte dringend deine Hilfe.
Habe meine aktuelle Konfiguration geschrottet und ein älteres image eingespielt.

Jedoch habe ich im image eine ältere Version meiner HomeMatic-Zentrale.
Mein Backup-File für die HomeMatic ist aber neuer.

Nun möchte ich per:
sudo apt update && sudo apt upgrade

wieder auf die neueste HomeMatic Version.

Jedoch erhalte ich sofort nachfolgende Fehler:

 sudo apt update && sudo apt upgrade
Hit:1 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Hit:3 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:4 https://deb.nodesource.com/node_8.x stretch InRelease
Hit:5 https://www.pivccu.de/piVCCU stable InRelease
Ign:6 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Err:7 https://dl.bintray.com/openhab/apt-repo2 stable Release
  502  Bad Gateway
Reading package lists... Done
E: The repository 'https://dl.bintray.com/openhab/apt-repo2 stable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Habe ich etwas übersehen, oder mache ich etwas falsch?

Ich hoffe auf eine schnelle Hilfe, da bei mir alles still steht :-(

Danke dir schon mal.

**Comment by alexreinert** [comment]
Der Fehler kommt beim Abruf des Openhab Repositories, da habe ich leider keine direkte Ahnung, welches du konkret eintragen musst, ist auch abhängig davon, welche Version von Openhab du hast.
Aber du solltest an sich unabhängig davon mit "sudo apt upgrade" die Version von piVCCU aktualisieren können.

**Comment by wineworld13** [comment]
Hallo Alex,

danke für die schnelle Antwort.

"sudo apt upgrade" ist erfolgreich durchgelaufen. 
Aber die piVCCU wurde nicht aktualisiert. -> Habe ich hier etwas übersehen?



Für den "502 - Fehler" habe ich nachfolgendes gefunden:

1. Befehl: wget -qO - 'https://openhab.jfrog.io/artifactory/api/gpg/key/public' | sudo apt-key add -
2. Anpassen in /etc/apt/: deb https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable main

Jetzt läuft gerade "sudo apt update && sudo apt upgrade".

**Comment by alexreinert** [comment]
Und läuft es jetzt?

**Comment by wineworld13** [comment]
Sorry, ja, läuft wieder!

piVCCU wurde aktualisiert. Backup eingespielt. 

Diverse Openhab URLs haben sich geändert...
addon-config musste gelöscht werden.
Nach clear-cache und reboots hats dann endlich alles wieder geklappt. 

Danke dir trotzdem für die schnelle Hilfe!
