### ISSUE TITLE
PiVCCU Servicemeldungen (Diagramme)

### ISSUE THREAD

**Issue by LordMaxse** [alexreinert/piVCCU#415]
Hallo Alex, habe deine Anleitung durchgeführt. Hat alles wunderbar geklappt. Ich würde gerne ein Diagramm wie zuvor in der CCU erstellen. Jedoch geht der USB Stick ja jetzt durch das PiVCCU nicht mehr. Er wird nicht erkannt. Desweiteren habe ich eine Frage zu Servicemeldungen, ich habe eine Servicemeldung die ich weder bestätigen noch löschen kann. Laut Recherche soll ich die Log Datei löschen, kannst du mir evtl. sagen wo diese zu finden ist? (Rasperry Pi 3-2b) 
Leider spreche ich kein Englisch, so das ich hier nur auf Deutsch schreiben kann und bei der Reche sehr eingeschränkt bin. Ich hoffe du oder jemand anderes kann mir hier behilflich sein.

**Comment by alexreinert** [comment]
USB Stick: Diese müssen dem CCU Container bekannt gemacht werden: Auf dem Host `sudo dpkg-reconfigure pivccu3` ausführen und dort dann im zweiten Dialog alle USB Sticks aktivieren (mit der Leertaste, so dass ein X vornedran ist), welche in die CCU durchgereicht werden sollen.

Servicemeldungen: Von welchen Servicemeldungen reden wir? Manche kann man einfach nicht bestätigen. Das mit dem Löschen einer Logdatei ist mir komplett neu, bitte mehr Infos.

**Comment by LordMaxse** [comment]
Hallo, ich danke dir für deine Hilfe du bist echt Spitze. Ein großen daumen Hoch hoch hoch lach, deine Anleitungen machen endlich mal sinn. Voralleim weil hier jemand weiß was er macht. ich habe unzählige Youtube Videos geschaut und alle wollte es dort besser wissen, das kennst du sicher. Bei den Servicemeldungen beziehe ich mich auf oben Rechts in der Ecke, bei der CCU Alarmmeldungen und darunter kommen gleich Servicemeldungen. Laut Recherche gibt es im Docker ein Log der diese Meldungen sammelt, diese müsste man manuell löschen stimmt das? Ich möchte nicht wirklich schon wieder einen Reinfall erleben. Besten Dank dir und Grüße aus Magdeburg, Micha
<img width="324" alt="Screenshot_1" src="https://user-images.githubusercontent.com/96445491/147015125-c389606e-71f4-48cb-a90d-0b7f1e30ada3.png">

**Comment by alexreinert** [comment]
Das du den Button meinst, war mir klar, meine Frage zielt auf die konkreten Meldungen ab. Z.B. eine Meldung, dass ein Gerät eine leere Batterie hat oder aktuell nicht erreichbar ist, kannst du nicht wegklicken. Eine Meldung, dass ein Gerät irgendwann nicht erreichbar war, dagegen schon.
Wo genau hast du das bei deiner Recherche gefunden? Weil Docker mit der CCU mal überhaupt nichts zu tun hat undir auch nichts von einem Log für Service Meldungen bekannt ist.

**Comment by LordMaxse** [comment]
meine meldungen die sich da gesamelt hatten könnte ich nicht bestätigten.  (nicht ereichbar) ich weiß nicht warum. der batten war die gaze zeit nicht aktiv so das ich kliken kontte wie ich wollte aber nix passierte die meldungen bekam ich einfach nicht weg der batten war auch nach einem neustart immer noch nicht da habe sogar das Gerät  abgelernt und trotz allem war die meldung noch da ob wohl das gerät nicht mehr im system war.
