### ISSUE TITLE
RP3+  crashes after manual install

### ISSUE THREAD

**Issue by s0170071** [alexreinert/piVCCU#42]
I tried the manual install with the 2018-03-13 stretch version with desktop. It does not restart after reboot. No error messages until then. All installation steps performed fine.

I also tried to first do an update - before install and before reboot. Same result. 

When it does reboot, the last log output is 

Bluetooth_ RFCOMM ver 1.11

when you leave BT enabled, otherwise the last log entry is: 

Adding 102369k swap on /var/swap...

Whatever stops the boot process comes next...

**Comment by alexreinert** [comment]
Are you using a RaspberryPi 3B+?
In that case: There is currently an issue in the stable Kernel regarding the new lan78xx module in combination with network bridges, which causes a kernel ops on startup. This is fixed in the testing kernel (rpi-update).

If this is not your issue, please provide a full boot log, not only the last line.

**Comment by s0170071** [comment]
Yes, I am using the 3B+, however, I did try to update (also rpi-update) before install. 
Theoretically, at what point during install should I do the update ? 
Has it ever been done with the desktop version or may I be running into an resource problem ?
 
The RPi does show some more SD activity (about 5 minutes) until the screen goes dark.

**Comment by alexreinert** [comment]
I have never tested an installation on a desktop system by myself. But in theory it should work, but 1GB RAM isn't that much. (Firefox sometimes uses more than 200MB + GPU RAM + System + CCU and you are around 1GB)

Kernel update should be done, before the bridge gets active. You could also use a port forwarding setup like it is used for wifi, as the kernel issue only affects bridges on the new lan78xx interface.

**Comment by s0170071** [comment]
update: I succeeded to reboot as requested by the install instructions. I think I may have forgotten to reboot before, right after rpi-update.

And the desktop version is pretty convenient as you can copy and paste the installation commands from the browser to the terminal window ;-)

**Comment by s0170071** [comment]
during installation it now says: could not locate the raw uart interface. After reboot, it seems to work however. Thanks.
