### ISSUE TITLE
After update of pivccu-modules-dkms 1.0.71 module not found

### ISSUE THREAD

**Issue by bbr111** [alexreinert/piVCCU#421]
After update of pivccu-modules-dkms 1.0.71 module not found

piVCCU version: 3.61.7-67
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
State:          RUNNING
PID:            3386
IP:             192.168.30.2
Link:           vethpivccu
 TX bytes:      31.00 KiB
 RX bytes:      26.60 KiB
 Total bytes:   57.60 KiB

HM-MOD-RPI-PCB is installed. Systemhare is running for 1 yesr in this configuration.
no changes made to hardware.

How to debug?

**Comment by alexreinert** [comment]
Closed?

**Comment by bbr111** [comment]
@alexreinert sorry for closing to fast. was too late for me to examine the problem. and found a quick solution that worked for short.

Reopening with correct infos about the issue, which I can now also reproduce.

apt/source - testing chanel

after install of pivccu-modules-dkms 1.0.71

piVCCU version: 3.61.7-67
Kernel modules: Available
Raw UART dev: Not available
Rasp.Pi UART: Assigned to GPIO pins
HMRF Hardware: unknown
HMIP Hardware: unknown
State: RUNNING
PID: 3386
IP: 192.168.30.2
Link: vethpivccu
TX bytes: 31.00 KiB
RX bytes: 26.60 KiB
Total bytes: 57.60 KiB

Rollback to version 1.0.70

piVCCU version: 3.61.7-67
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  OEQ0307330
 Radio MAC:     0x584079
HMIP Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 SGTIN:         3014F711A061A7D7098E1882
 Radio MAC:     0xB39389
State:          RUNNING
PID:            1563
IP:             192.168.30.2
Link:           vethpivccu
 TX bytes:      6.48 KiB
 RX bytes:      9.77 KiB
 Total bytes:   16.25 KiB

system is an raspberrypi 4 with bullseye and kernel 5.10.63-v7l+

**Comment by alexreinert** [comment]
Did you reboot after the installation of the new package? If yes: can you provide the output of `sudo dpkg-reconfigure pivccu-modules-dkms`? If there is a log file referenced, please provide the output of this file, too.

**Comment by bbr111** [comment]
install with apt upgrade
reboot
after reboot
 pivccu-info
piVCCU version: 3.61.7-67
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
State:          RUNNING
PID:            1370
IP:             192.168.30.2
Link:           vethpivccu
 TX bytes:      7.27 KiB
 RX bytes:      11.44 KiB
 Total bytes:   18.71 KiB

dpkg-reconfigure pivccu-modules-dkms
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.71
Kernel:  5.10.63-v7l+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_eth.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb-2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod......

DKMS: uninstall completed.

------------------------------
Deleting module version: 1.0.71
completely from the DKMS tree.
------------------------------
Done.
Error! The module/version combo: pivccu-1.0.71
is not located in the DKMS tree.

Creating symlink /var/lib/dkms/pivccu/1.0.71/source ->
                 /usr/src/pivccu-1.0.71

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.10.63-v7l+ ARCH=arm all......
cleaning build area...

DKMS: build completed.

dummy_rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

dw_apb_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

eq3_char_loop.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

fake_hmrf.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

generic_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

hb_rf_eth.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

hb_rf_usb-2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

hb_rf_usb.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

led_trigger_timer.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

meson_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

pl011_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

plat_eq3ccu2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

rpi_rf_mod_led.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

rtc-rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.63-v7l+/kernel/drivers/pivccu/

depmod.....

DKMS: install completed.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.


no log file referenced found.


maybe this has something to do with the problem:

Error! The module/version combo: pivccu-1.0.71
is not located in the DKMS tree.

**Comment by alexreinert** [comment]
Please retry using the latest update.

**Comment by bbr111** [comment]
Works for me.

**Comment by dampflok2000** [comment]
Hi,

after a new installation of Raspberry Pi Os Lite (Bullseye -> tested on 32- and 64-bit) I have the same error when I try to manually install pivccu3. Is there a workaround available?

Best regards
dampflok2000
