### ISSUE TITLE
Possibility to have pivccu-modules-dkms on fedora

### ISSUE THREAD

**Issue by DutchmanNL** [alexreinert/piVCCU#425]
First of all, thank you for all the work Alex !

I'm trying to setup an efficient as possible base system for docker purposes and would like to use Fedora Core OS as main system and docker host.
As I understood, the current kernel modules are only available for Debian related distributions but expect in generic to work on other linux environments.

Unfortunalty fedora does not use the Debian apt repository's but requires an .rpm package as installation source.

I tried to compile the core modules into a deb package (which worked fine) and rebuild the .deb to an .rpm source (which looked ok) but installation fails based on dependency's

I am wondnering if it would be possible to provide your kernel modules also as an .rpm source allowing us to use non-detain like distro's

Thank you and. have a nice day !

~Dutch

outcome of my test with own compiled package : 

```
sudo dnf install ./pivccu-modules-dkms-1.0.71-2.noarch.rpm 
Last metadata expiration check: 3:55:16 ago on Fri Feb  4 08:48:05 2022.
Dependencies resolved.
==================================================================================================================================
 Package                               Architecture             Version                      Repository                      Size
==================================================================================================================================
Installing:
 pivccu-modules-dkms                   noarch                   1.0.71-2                     @commandline                    57 k

Transaction Summary
==================================================================================================================================
Install  1 Package

Total size: 57 k
Installed size: 246 k
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /lib from install of pivccu-modules-dkms-1.0.71-2.noarch conflicts with file from package filesystem-3.14-7.fc35.x86_64
```

**Comment by alexreinert** [comment]
I'm pretty sure, that the kernel modules will work on other distributions, too. But as I have no experience in building rpm packages, I cannot provide them.
