### ISSUE TITLE
HmIP-RFUSB und Lan-Gateway

### ISSUE THREAD

**Issue by haraldkolb** [alexreinert/piVCCU#427]
Hallo!

Ich nutze den HmIP-RFUSB Stick von eQ3 auf einem Raspi. 
Das von mir favorisierte RPI-RF-MOD ist leider schon seit Monaten nicht lieferbar, laut ELV frühestens ab Mai #22.

Da der Stick ja nun "advanced Routing" unterstützt hab ich mir einen HmIP-HAP dazu gekauft den ich als Lan-Gateway für HmIP nutzen möchte. Eine alte CCU2 habe ich bereits als Lan-Gateway aktiviert.
Aber leider klappt das Anlernen nicht. Schon der Button "Access Points mit inkompatibler FW updaten" in der Systemsteuerung von pivccu3 bringt nicht das Suchfenster sondern nur einen abgeblendeten Bildschirm der nur durch "F5" verlassen werden kann.
Jetzt habe ich in der readme.md folgendes gelesen:

>Use HmIP-RFUSB firmware 4.2.14 without advanced routing for now as …
>…the firmware 4.4.8 has serious issues on newer sticks

Bedeutet das jetzt dass ich (noch) keinen  HAP als Gateway nutzen kann?

Kann ich mit dieser Funktion rechnen? Oder muss ich wirklich bis Mai warten bis ein RPI-RF-Mod vielleicht lieferbar ist?

Vielen Dank für die (ansonsten) SUPER Programmierarbeit!!!!
LG,
Harald

**Comment by alexreinert** [comment]
die aktuelle Version kann das mit dem elv Bausatz vom HmIP-RFUSB.
Was liefert `sudo pivccu-info`?

**Comment by haraldkolb** [comment]
Wow, das ist eine Antwortzeit mit der ich nicht gerechnet hätte!
Hier die Ausgabe:
piVCCU version: 3.61.7-68
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-3f980000.usb-1.2 (/dev/raw-uart1)
 Board serial:  1D89B553EB
 Radio MAC:     0xFFF6EE
HMIP Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-3f980000.usb-1.2 (/dev/raw-uart1)
 SGTIN:         3014F711A000041D89B553EB
 Radio MAC:     0xB98950
State:          RUNNING
PID:            1285
IP:             192.168.121.2
IP:             2003:d6:3737:d100:f818:28ff:fe88:8cd7
CPU use:        1215.82 seconds
Link:           vethpivccu
 TX bytes:      31.72 MiB
 RX bytes:      45.92 MiB
 Total bytes:   77.64 MiB

**Comment by alexreinert** [comment]
ok, Software und Hardware sollten schon mal passen.
Zum Anlernen bitte mal versuchen:
Zweifacher Werksreset des HAP, dann HAP vom Strom trennen. In der CCU den HmIP Anlernmodus starten, den HAP wieder mit Strom versorgen und warten ohne irgendwas zu Kliken oder am HAP zu drücken. Wenn die 60 Sekunden abgelaufen sind in den Posteingan schauen.

**Comment by haraldkolb** [comment]
Leider hat auch das nichts gebracht. Der Posteingang bleibt nach den 60 Sekunden leer. 
An einem anderen System mit RPI-RF-MOD war das Anlernen ein Klacks.  

Könnte es sein dass der Linux „Unterbau“ damit zu tun hat?
Bei apt Upgrades bekam ich da Fehler in der Form 
„dpkg: Warnung: Dateilisten-Datei des Paketes »node-chownr« fehlt; es wird angenommen,
 dass das Paket derzeit keine Dateien installiert hat“

Allerdings läuft das System ansonsten ohne murren oder Abstürze. 
Die bemängelten Pakete habe ich in der Zwischenzeit auch mit „apt-get -reinstall“ nachinstalliert so dass die Meldungen nicht mehr kommen. Das gleiche habe ich mit pivccu mit dem Befehl „sudo apt --reinstall install pivccu-modules-dkms pivccu-modules-raspberrypi pivccu3„ gemacht. 
Aber möglicherweise fehlen trotzdem  irgendwelche Pakete?

Sollte  ich den Raspi neu installieren und pivccu aus einem Backup wiederherstellen damit das mit dem LAN Gateway klappt?

**Comment by alexreinert** [comment]
Bitte bleib bei den richtigen Bezeichnungen, sonst wird es verwirrend: Es gibt ein LAN Gateway für BidCos und es gibt den (hmIP-)HAP für HmIP.

An sich braucht es da keine weiteren Pakete mehr. Wenn ich aber die Fehlermeldung mit der fehlende Dateiliste sehe, dann möchte ich mal nicht ausschließen, dass die SD Karte einen Treffer hat.

Und ich frage nochmal ganz explizit: Hast du direkt zweimal hintereinander den Werksreset gemacht? Und hast du den HAP am anderen System korrekt abgelernt, nicht dass sich das andere System den gleich wieder schnappt, wenn er im Netzwerk auftaucht.

**Comment by haraldkolb** [comment]
Sorry für die falsche Bezeichnung des HAP.

Aber ja, den Reset habe ich zweimal hintereinander vor den Anmeldeversuchen  gemacht. Mit Taste drücken, Strom an,  dann aufs blinken warten, loslassen und wieder drücken bis Grün. Dann hab ich gewartet bis blau (mit Netzwerk) oder orange blinken (ohne Netzwerk)  und das Ganze nochmal. 
Und in dem Netzwerk befindet sich auch keine zweite pivCCU o.ä. 

Raspian läuft auf einer SSD, mit SD Karten hab ich leider schon einiges negatives erlebt. 

Könnte es an den Firewall/Netzwerk Einstellungen liegen? Welcher Port wird da zum suchen genutzt? 
Aber ich habe das auch schon mit „Ports offen“ versucht, ohne Änderung. 

Was mich aber immer noch irritiert ist, wie schon oben beschrieben:
>Der Button "Access Points mit inkompatibler FW updaten" in der Systemsteuerung von pivccu3 bringt nicht >das Suchfenster sondern nur einen abgeblendeten Bildschirm der nur durch "F5" verlassen werden kann.
Offenbar hängt da schon was bei der Erkennung. 

Raspi und HAP hängen übrigens direkte an einer FritzBox. 
Die Installation von Pivccu erfolgte strikt nach der Anleitung mit fester IP. 
Mir gehen so langsam die Ursachen für den Fehler aus…

**Comment by alexreinert** [comment]
Ich habe einen Bug in der aktuellen Version gefunden, welcher möglicherweise dein Problem verursacht. ich werde morgen ein Bugfix Release bereitstellen.

**Comment by alexreinert** [comment]
Bugfix Release liegt im APT Repository bereit, bitte damit mal testen.

**Comment by haraldkolb** [comment]
Hallo!

ES KLAPPTE BEIM ERSTEN ANMELDEVERSUCH!!!
Endlich kann ich das System auch ohne den nicht lieferbaren RPI-RF-MOD erweitern!

Danke für den super Support und die damit verbunden Arbeit. 
Ich habe per Paypal eine Spende als kleines Extras geschickt. 

LG,
Harald
