### ISSUE TITLE
nach wechsel von node js 12 zu 14.19 npm 14.19 lauft  die pivccu nicht mehr an 

### ISSUE THREAD

**Issue by Radix1975** [alexreinert/piVCCU#429]
pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.61.7-67
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
State:          STOPPED
was kann ich tun Neuinstallation über die bestehende hab ich schon nach Anleitung  von https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md  
versucht ohne Erfolg
Auch der Wechsel  der micro SD karte auf eine Beckupkarte hat nichts gebracht

**Comment by alexreinert** [comment]
piVCCU nutzt kein Node, daher dürfte ein reines Node Update keine Auswirkungen haben.
Wurde parallel auch ein Kernel Update durchgeführt?

**Comment by Radix1975** [comment]
ja wurde es

**Comment by Radix1975** [comment]
`pi@raspberrypi:~`` $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.221  netmask 255.255.255.0  broadcast 192.168.1.255
        ether dc:a6:32:49:ae:73  txqueuelen 1000  (Ethernet)
        RX packets 24673  bytes 9245275 (8.8 MiB)
        RX errors 0  dropped 1014  overruns 0  frame 0
        TX packets 29996  bytes 6866742 (6.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Lokale Schleife)
        RX packets 611830  bytes 434169341 (414.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 611830  bytes 434169341 (414.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by alexreinert** [comment]
Und wurde nach dem Kernel Update auch ein Reboot gemacht?

**Comment by Radix1975** [comment]
Reboot habe ich schon mehrfach gemacht auch so wie in der Anleitung
pi@raspberrypi:~ $ netconfig 
bash: netconfig: Kommando nicht gefunden.   ?

**Comment by Radix1975** [comment]
Das Problem liegt auf jeden Fall  an der Raspberry auch der Zweite tausch der Karte hat nix gebracht außerdem fehlt ein Netzwerksymbol auf der GUI Ich habe Debian mit grafischer Oberfläche Installiert

**Comment by alexreinert** [comment]
Einfach um das korrekt zu verstehen: Kannst du bitte mal den Zustand vor den Updates beschreiben (Hardware, Software und Konfiguration) und was du alles gemacht hast.

**Comment by Radix1975** [comment]
Ich habs mit der neuen Karte aufgegeben geht nix.
Ich habe gerade die alte Karte mit dem  node js 12 drauf eingelegt und dort ein Kernelupdategemacht
jetzt geht das pivccu 3 wieder und ich müßte nur noch auf node js 14 updaten ohne alles zu  zerstören.`https://forum.iobroker.net/topic/35090/howto-nodejs-installation-und-upgrades-unter-debian`

**Comment by Radix1975** [comment]
so es läuft  wieder alles und Node Js ist auch auf 14.19 danke fürs helfen.
