### ISSUE TITLE
MQTT broker not reachable

### ISSUE THREAD

**Issue by s0170071** [alexreinert/piVCCU#43]
I installed an mqtt broker on the same RPI that also runs the piVCCU. It is reachable from the RPI itself but not from the outside. 
CCU is up and running and reachable from outside on port 80.
I had the broker up and running on an installation that did not involve piVCCU. 

I think this may be related to the bridging of the network.

**Comment by alexreinert** [comment]
I do not see the piVCCU issue here. Maybe it is an issue ofvthe MQTT Broker you are using or a Raspbian issue.
piVCCU is just some packages on top of a standard Raspbian and requires just some special (but not unnormal) network settings.

**Comment by s0170071** [comment]
You're right, my bad. In fact, it was working all along. What mislead me was that the RasPi was usually available at 

`192.168.1.41 :1883 - RasPI MQTT
`

With piVCCU installed, it is
```
192.168.1.41 :80  - Homematic-CCU2
192.168.1.56  :1883 - RasPI MQTT

```

I somehow assumed that the MQTT service is available at the same address as before, only it now has a different IP while the CCU as the new device was mapped to the old IP.
