### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by 32u-nd** [alexreinert/piVCCU#430]
Good morning. Please do not use "double negation" in point 5 [https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md](https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md) "You can skip this step, if you do not use the HM-MOD-RPI-PCB or RPI-RF-MOD on GPIO header, for the HB-RF-USB(-2) and HB-RF-ETH this step is not neccessary". Please change it to a positive statement, like "For HM-MOD-RPI-PCB or RPI-RF-MOD on GPIO header, please install device tree patches" or similar. Thanks.

**Comment by alexreinert** [comment]
Why?

**Comment by 32u-nd** [comment]
I believe an install instruction by default should focus on items/topics to do and not on items/topics you should not or need not to do. This is just my personal opinion.
