### ISSUE TITLE
Tinkerboard S Armbian 22.02.1 /w 5.15.25-rockchip - no more LED on RPI-RF-MOD

### ISSUE THREAD

**Issue by t-rood** [alexreinert/piVCCU#431]
Hi Alex,

can you look into the **pivccu-modules-dkms** please? My Tinkerboard S R2.0 misbehaves like this:

- using Armbian 22.02.1 /w 5.15.25-rockchip the LED on RPI-RF-MOD remains fully dark
- using Armbian 21.08.1 /w 5.10.60-rockchip the LED on RPI-RF-MOD works as expected (green/blue)

In both cases, pivccu-info shows the module, and antenna transmission to eQ3 devices works fine regardless of LED state on the board.

Repro done with vanilla setup as per your github description for armbian with the above base builds (and frozen headers/kernel for the working one). Your older tinkerboard image is also affected when updating to latest packages.

Thank you
Thorsten

**Comment by alexreinert** [comment]
Most propably this is not an issue with the modules, but some changed paths in the device tree in kernel 5.15. I will look as soon as possible.

**Comment by Pocky2507** [comment]
Auch beim RockPro64 geht nach einem Upgrade gar nichts mehr.
Der HM-MOD-RPI-PCB wird gar nicht mehr erkannt.
Habe eine Sicherung der SSD zurückspielen müssen.

**Comment by Pocky2507** [comment]
Moin Alex
Bist Du am RockPro64 noch dran?
Nach update auf Armbian 5.15 wird das Modul HM-MOD-RPI-PCB nicht mehr erkannt.

**Comment by alexreinert** [comment]
Grundsätzlich ja, aber aus privaten Gründen braucht das noch etwas Zeit.

**Comment by t-rood** [comment]
Hi Alex, wie sieht denn eigentlich die "Tinker"-Planung aus, mal ungeachtet der anderen Ansteuerung abhängig von der Kernelversion? Das Tinker S-R2 hat ja mit dem Tinker 2-S ohnehin einen Nachfolger, bei dem ja ähnliche oder noch mehr Kompatibilitätsprobleme zu erwarten sind. Ich hab mir jetzt "erst mal" ein S-R2 als Sparepart zurück gelegt...
