### ISSUE TITLE
Fehlermeldungen / error message

### ISSUE THREAD

**Issue by 47441** [alexreinert/piVCCU#439]
Vielen Dank für piVCCU3 und Deine Arbeit an dem Projekt.
I habe piVCCU3 auf meinem RasPi4 installiert und die Software scheint zu funktionieren. HM-Komponenten können angelernt werden an der Software, Allerdins klappt das mit HM-IP-Komponenten nicht. Zusätzlich gibt es einige Fehlermeldungen.

Hat jemand eine Idee, wo mein Fehler her kommt...?

Thanks for piVCCU3 and your work on it.
I Installed piVCCU3 in my RasPi 4, using an HM-MOD-RPI-PCB. The Software seems to work, HM-Components can be linked to the Software.
But HM-IP ist not working, and there a some error messages.

Has anybody any idea, what I can do to solve the problem?

![image](https://user-images.githubusercontent.com/105124972/167266464-2d4d791b-c31d-4163-bb44-56337a1371dd.png)

![image](https://user-images.githubusercontent.com/105124972/167266512-87eacd06-f6ab-45d6-aa7d-3e02ff6e3d0c.png)

![image](https://user-images.githubusercontent.com/105124972/167266443-241f6db3-e109-4533-bb56-efd29801774e.png)
![image](https://user-images.githubusercontent.com/105124972/167266450-22eb6d50-6419-41a3-8bca-cd78c5362a36.png)

**Comment by alexreinert** [comment]
Wann kommen die Fehlermeldungen? Sofern noch ein Browserfenster offen ist und die CCU neu gestartet wird, sind die Meldungen normal.

Wie gehst du exakt beim Anlernen der HmIP Geräte vor (Wirklich Schritt für Schritt beschreiben).

Und der Vollständigkeit halber: Der Raspberry Pi 4 erzeugt jede Menge Störstrahlung, welche insb. HmIP stört. Vor allem, wenn ein Gerät am USB3 Port hängt. Da hilft nur Abstand zwischen Funkmodul und Raspberry.

**Comment by 47441** [comment]
Hallo Alex,
die Meldung kommt nach jedem Login in der piVCCu3-Website. Es dauert ca. 30 Sekunden. Es kommen nacheinander die "Virtual Device" und "HMIP-RF". 
Wenn ich per Software die CCU3, oder den RasPi neu starte kommt immer die Meldung. Auch ein Wechsel des Rechners oder des Browsers (von Chrome zu Edge) hilft nicht... ;(

Zum Thema Abstand: Was schlägst Du denn vor? Ich hatte nur Jumperkabel von 40mm Länge. Das reicht nicht. Ich plane den Abstand per Telefonkabel (4x2x0,8) zu Verlängern. Gibt es da eine Maxlänge? 

Ich prüfe mal. welche USB-Ports ich benutze und lasse den USB-3 frei.

Die Frage mit dem HMIP-Anlernen stellt sich nicht, da ich die Auswahl nicht habe:
![Screenshot](https://user-images.githubusercontent.com/105124972/167297454-13ac606a-67b6-448d-984a-76dfbb2415f0.jpg)

Vielen Dank

Martin
