### ISSUE TITLE
sources for susv(python-smbus) for raspberry cannot be found

### ISSUE THREAD

**Issue by Chris5917** [alexreinert/piVCCU#44]
Hi,

I'm currently using YAHM and trying to transition to piVCCU.
In my YAHM(Jessie) Setup I managed to install the SUSV in order to bridge power outages. Works fine.

In the environment of piVCCU I just followed the same Installation process.
Login into the host System:

pi@raspberrypi:~ $ **sudo apt-get install python-smbus**                            
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python-smbus is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**E: Package 'python-smbus' has no installation candidate**
pi@raspberrypi:~ $

When I understood the concept of piVCCU than this is something unexpected.
I'm a bloody Linux user, but for me it looks like the sources are not found here, while in the YHAM environment based on Jessy it worked perfectly.

Is there something I need to do in Addition as piVCCU is based on Stretch lite ?

any help appreciated.

Thanks and BR
  Chris

**Comment by alexreinert** [comment]
This is not a piVCCU issue. piVCCU is build on top of a standard Raspbian (As well as YAHM) and if you cannot install packages in Stretch which were available in Jessie, you should look for support in the Raspbian support channels.

But maybe you are just missing an initial "sudo apt update" to initialize the package list after the first start of an image.

**Comment by Chris5917** [comment]
Hi Alex,

for sure not a piVCCU issue :-) My expectations while switching from YAHM to piVCCU was to get into a  more stable and better/easier configurable Environment - meaning Rasbian Stretch lite.

The sudo apt update + upgrade did not help btw, but just for completeness in case someone will find the issue comment, with the new Image you provided per 19-Apr-2018 it worked very well. The S.USV daemon is working properly now, but I had to activate the i2C manually.

S.USV 2.31 works on piVCCU Image per 19-Apr-2018.

BR
  Chris
