### ISSUE TITLE
PiVCCU Image -- SSH Login falsch

### ISSUE THREAD

**Issue by mandre1904** [alexreinert/piVCCU#440]
Hallo,

ich versuche seit gestern verzweifelt PiVCCU neu zu installieren. Offenbar ist die SD Karte abgeschmiert.

ssh Datei in Boot erzeugt. Per Putty drauf.
Benutzer: pi
PW: raspberry

Access denied. IMMER. x Mal neu aufgespielt. Irgendeine Idee? Ich verzweifle langsam.

Danke und einen schönen Sonntag

**Comment by wendy2702** [comment]
Was genau machst du denn?

Ein fertiges PiVCCU Image auf die SD Karte gespielt oder welches OS auf die SD und PiVCCU manuell nach welcher Anleitung installiert?

**Comment by alexreinert** [comment]
Versuchst du dich zur IP des CCU Containers oder zur IP vom Host zu verbinden?
