### ISSUE TITLE
Kein IPv4 Zugriff unter RaspberryPi Host

### ISSUE THREAD

**Issue by johannesst** [alexreinert/piVCCU#442]
Hallo,

ich habe einen PI mit pivccu3 am Laufen. Eingerichtet habe ich das Netzwerk wie in der Anleitung mit DHCP und der Bridge:
https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md

Das hat auch soweit alles geklappt: Der Pi ist im Netzwerk erreichbar, die CCU auch. Von außen kommt man auch per IPv4 und IPv6 rein. Auf der pivccu-Konsole (sudo pivccu-attach) kommt man auch ohne Probleme mit ipv4 und ipv6 nach draußen:

```

/ # hostname
ccu3-webui
/ # ping6 www.google.de
PING www.google.de (2a00:1450:4001:830::2003): 56 data bytes
64 bytes from 2a00:1450:4001:830::2003: seq=0 ttl=59 time=19.440 ms
^C
--- www.google.de ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 19.440/19.440/19.440 ms
/ # ping www.google.de
PING www.google.de (142.250.74.195): 56 data bytes
64 bytes from 142.250.74.195: seq=0 ttl=115 time=18.338 ms
^C
--- www.google.de ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 18.338/18.338/18.338 ms

```
Auf den pi selbst leider nicht, was z.B. unpraktisch ist, wenn man sich was sich ein github-repo klonen möchte:

```
pi@raspberrypi:~ $ ping www.google.de
PING www.google.de(fra24s22-in-x03.1e100.net (2a00:1450:4001:80b::2003)) 56 data bytes
64 bytes from fra24s22-in-x03.1e100.net (2a00:1450:4001:80b::2003): icmp_seq=1 ttl=59 time=20.5 ms
^C
--- www.google.de ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 20.542/20.542/20.542/0.000 ms
pi@raspberrypi:~ $ ping6 www.google.de
PING www.google.de(fra24s22-in-x03.1e100.net (2a00:1450:4001:80b::2003)) 56 data bytes
64 bytes from fra24s22-in-x03.1e100.net (2a00:1450:4001:80b::2003): icmp_seq=1 ttl=59 time=19.7 ms
^C
--- www.google.de ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 19.686/19.686/19.686/0.000 ms
pi@raspberrypi:~ $ ping4 www.google.de
PING  (142.250.181.227) 56(84) bytes of data.
^C
---  ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1062ms

pi@raspberrypi:~ $ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

````

Ich habe schon die Issues hier und diverse Foreneinträge im Homematic-Forum auf Lösungsansätze durchsucht, aber leider nichts gefunden. Die dortigen User scheinen immer Probleme mit dem IPv4 Zugriff auf die pivccu zu haben. Das Problem habe ich aber ja nun gerade nicht: Es geht um den Host, nicht die vccu und den Zugriff nach außen, nicht nach innen.

Irgendwelche Tipps für Lösungsansätze? Ich habe schon überlegt mein Ethernet statt als Bridge wie ein WLAN-Device (also mit port forwarding etc) einzurichten, allerdings schreibt Alex Reinert ja in der Anleitung für WLAN auch, dass dies eigentlich nicht empfohlen wird.

Danke und mit freundlichen Grüßen, Johannes Starosta.

**Comment by alexreinert** [comment]
Ist da ein Copy&Waste Fehler in der Problembeschreibung, weil ich da nur erfolgreiche Befehle sehe?

**Comment by johannesst** [comment]
Hallo,

ja, war ein copy paste Fehler, jetzt sollte es klar sein, habe es bearbeitet.

Danke fürs Nachfragen und schöne Grüße, Johannes.
