### ISSUE TITLE
CCU Problem auf Tinkerboard nach Update 

### ISSUE THREAD

**Issue by Dott0reAti** [alexreinert/piVCCU#443]
Hallo Alex,
habe heute auf meinem Tinkerboard ein Update von 3.61. auf 3.63 mit apt update und apt upgrade gemacht. Lief laut shell auch fehlerfrei durch. Der nachfolgende Start dauerte aber extrem lange. Zuerst dachte ich kommt gar nicht hoch, aber dann doch.
Erste Ansicht - es wird keine Version angezeigt. Nur Uhrzeit Datum Sonnenauf- und -untergang, Zweiter Blick - alle Geräte bis auf CUxD sind verschwunden
![Homematic1](https://user-images.githubusercontent.com/108345896/176188680-d8b0fd87-96fb-497b-92cc-8e96458b57aa.jpg)
.
Dritter Blick - die Variablen sind vorhanden und unter Zusatzsoftware sind E-Mail, CuxD, XML-API und NEO Server vorhanden.
Was kann da falsch gelaufen sein? Wo muss ich jetzt nach dem verlorenen Inhalt suchen?

**Comment by alexreinert** [comment]
Was liefert pivccu-info auf dem Host? Was für ein Funkmodul wird verwendet und wie ist es angeschlossen? Wurde nach dem Update ein Reboot gemacht?

**Comment by Dott0reAti** [comment]
Welcome to Armbian 22.05.3 Bullseye with Linux 5.15.48-rockchip

System load:   8%               Up time:       9 min
Memory usage:  11% of 1.96G     IP:            192.168.0.75 10.0.3.1
CPU temp:      63°C             Usage of /:    13% of 15G

Last login: Tue Jun 28 08:37:29 2022 from 192.168.0.7
root@tinkerboard:~# pivccu-info
piVCCU version: 3.63.9-71
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
State:          RUNNING
PID:            5796
IP:             192.168.0.13
IP:             2a02:8109:b83f:cd1c:e826:eeff:fec9:15eb
Link:           vethpivccu
 TX bytes:      16.87 MiB
 RX bytes:      109.61 MiB
 Total bytes:   126.48 MiB


Reboot wurde gemacht. Funkmodul das Standardteil von ELV allerdings mit geänderter besserer Antenne  (Hat ja vorher auch funktioniert)
Ach und noch eins ist aufgefallen. Die vorherige IP-Adress hat sich nach dem Update geändert. Ursprünglich hatte sie die 192.168.0.5 - jetzt 192.168.0.13.

Danke Andreas

**Comment by Dott0reAti** [comment]
HMRF Hardware: unknown
HMIP Hardware: unknown

sieht irgendwie nicht gut aus

**Comment by Dott0reAti** [comment]
kann ich Dir erst später sagen, bin nur remote vom Büro aus drauf. Das war vorher ein Raspi mit pivCCU2 dann pivCC§ und dann Wechsel auf Tinkerboard. Hat ja lange Zeit problemlos gespielt - bis zum Update. Ich melde mich 

Danke A.

**Comment by alexreinert** [comment]
Was liefern folgende Befehle:
```
sudo systemctl stop pivccu
sudo detect_radio_module --debug /dev/raw-uart
sudo systemctl start pivccu
```

**Comment by Dott0reAti** [comment]
Last login: Tue Jun 28 08:37:29 2022 from 192.168.0.7
root@tinkerboard:~#
root@tinkerboard:~# systemctl stop pivccu
root@tinkerboard:~# detect_radio_module --debug /dev/raw-uart
08:54:33.739214 Sending HM frame:  fd 00 03 fe 00 01 14 1e
08:54:36.739820 Sending HM frame:  fd 00 03 00 01 00 9e 03
08:54:39.740059 Sending HM frame:  fd 00 03 fe 02 01 98 1d
08:54:42.740325 Sending HM frame:  fd 00 03 00 03 00 12 00
08:54:45.740578 Sending HM frame:  fd 00 03 fe 04 01 8c 1d
08:54:48.740800 Sending HM frame:  fd 00 03 00 05 00 06 00
Error: Radio module was not detected

**Comment by Dott0reAti** [comment]
könnte es sein, dass in der Update  Version der GPIO Connector anders angesprochen (beschaltet) ist?

Wenn der davor funktioniert hat, liegt das irgendwie nahe. Kaputt wird er durch Update sicher nicht sein

**Comment by alexreinert** [comment]
Ich sehe hier zwei Möglichkeiten: Das Funkmodul ist defekt (auch wenn ich das ebenfalls unwahrscheinlich betrachte) oder zusammen mit dem Update kamen auch Armbian Updates, welche irgendwas am Device Tree angepasst haben, so dass der Pinmux der GPIOs nicht mehr passt. Ich versuche das auf meinen Testsystemen mit der Armbian Version nachzustellen.

**Comment by Dott0reAti** [comment]
ich könnte Dir auch den SSH Zugang zugänglich machen, sodass Du da direkt schauen könntest. Bei Bedarf.

**Comment by Dott0reAti** [comment]
Frage am Rande. Ist das Tinkerboard S R2.0 kompatibel mit pivCCU? Eine Ersatzlösung bzw. Backup wäre in so einer Situation nicht verkehrt. Und einen Pi würde ich jetzt nicht unbedingt mehr nehmen wollen

**Comment by alexreinert** [comment]
> Frage am Rande. Ist das Tinkerboard S R2.0 kompatibel mit pivCCU? 

Vielleicht ja, vielleicht nein. Ich konnte bisher leider noch kein Testgerät auftreiben.

**Comment by Dott0reAti** [comment]
https://www.proshop.de/Stationaer-Mini-PC-Barebone/ASUS-Tinker-Board-S-R20/3069633?utm_source=geizhals&utm_medium=cpc&utm_campaign=pricesite**

**Comment by Dott0reAti** [comment]
Tinker Board S R2.0 series features standard maker connectivity options, including a 40-pin GPIO interface that allow for interfacing with a range inputs. Tinker Board S R2.0 series is equipped with one DSI MIPI connection for displays and touchscreens. The secondary CSI MIPI connection is for connection to compatible cameras allowing for computer vision, and much more.

Tinker Board S R2.0 series also features Gbit LAN for Internet and network connectivity. A dedicated bus resource designed for the LAN port ensures consistent Ethernet performance. The integrated Wi-Fi and Bluetooth controller on the Tinker Board S is shielded with a metal cover to ensure minimal interference and improved radio performance. An integrated IPEX antenna header allows for easy antenna replacement or upgrades.

Ich habe mal den GPIO verglichen. Die Farbcodierung zumindest ist identisch.

**Comment by t-rood** [comment]
Ich kann das für euch auflösen: ich habe ein Tinker S R2.0 (nicht verwechseln mit S2) im Einsatz. Von mir stammt der Bugeintrag #431 und da steht auch drin, wie man es prinzipiell behebt. Konkret hast du bei deinem Update den Rockchip-Support auf 5.15 aktualisiert (sagt dein Welcome-Screen aus diesem Thread) und dann wird das nix mehr.

Ich habe 22.02.01 Focal mit Rockchip **5.10.60** und piVCCU 3.63.8 lauffähig. Ich nutze zwar schon das neuere RPI-RF-MOD Modul, aber das Problem liegt ja am Rockchip 5.15 und nicht am Modul selber.

Wenn du downgrade nutzt oder gar neu installierst, solltest du mit armbian 21.08.1 installieren und vor der ganzen Aktualisierungssequenz dann den Kernelkram wie folgt dauerhaft einfrieren, bis Alex eine echte Anpassung auf die GPIO gemacht hat:

```
sudo apt-mark hold armbian-bsp-cli-tinkerboard
sudo apt-mark hold armbian-firmware
sudo apt-mark hold linux-dtb-current-rockchip
sudo apt-mark hold linux-headers-current-rockchip
sudo apt-mark hold linux-image-current-rockchip
sudo apt-mark hold linux-u-boot-tinkerboard-current
```

Mein allerletztes Update steht noch aus, aber ich wollte während der Sommerferien kein eventuelles Chaos anrichten. ;-)

HTH

LG
Thorsten

**Comment by Dott0reAti** [comment]
Hallo Thorsten,
vielen Dank für die Infos. Also grundsätzlich passt Tinkerboard S zu Tinkerboard S R2.0. Das ist schon mal sehr wichtig. 

Das Problem derzeit ist, ich habe momentan keine funktionierende Zentrale, weil das Funkmodul nicht arbeitet. Ein neues flashen auf vorherige Version bedeutet, dass alles noch mal von vorn gemacht werden muss. Backup habe ich irgendwo abgelegt, müsste ich suchen. 
Kann man denn ein downgrade auf Rockchip 5.10.60 bewerkstelligen ohne alles platt zu machen?

**Comment by alexreinert** [comment]
Ich konnte gestern abend mein Tinkerboard S testen. Mit einenm frischen Bullseye Image konnte ich problemlos mit dem Funkmodul kommunizieren. Es muss also irgendwas sein, dass bei einem Update alte Armbian Sachen verbleiben, welche mit dem Armbian Update in Verbindung mit piVCCU nicht kompatibel sind.
Mit welcher Armbian Version hast du begonnen, dann versuch ich das entsprechend nachzustellen.
Da du offensichtlich kein Backup hast, würde ich ungern auf deinem System per SSH probieren, da dabei durchaus die Möglichkeit besteht, dass System hinterher vollständig hinüber ist und nicht mehr bootet.

**Comment by Dott0reAti** [comment]
oh na backup ist schon irgendwo. Ist sicher auf dem Laptop, auf dem ich das alles eingerichtet hatte. Der ist aber zu Hause und ausgeschaltet. Ich würde aber lieber auf Nummer sicher gehen, das es auch tatsächlich dort liegt. Dann kannst Du gern drauf gehen.

Die anfängliche Version war Armbian_Tinkerboard_focal_piVCCU3_2020-12-04.img

**Comment by Dott0reAti** [comment]
er schrieb doch weiter oben, er hat noch kein R2.0 auftreiben können. Also ein wenig Zeit braucht es wohl schon noch

**Comment by Dott0reAti** [comment]
Hier noch als Nachtrag die Detect-Info

`
Welcome to Armbian 22.05.3 Bullseye with Linux 5.15.48-rockchip

System load:   6%               Up time:       4:31
Memory usage:  15% of 1.96G     IP:            192.168.0.75 10.0.3.1
CPU temp:      65°C             Usage of /:    13% of 15G

[ General system configuration (beta): armbian-config ]

root@tinkerboard:~# sudo systemctl stop pivccu
sudo detect_radio_module --debug /dev/raw-uart
sudo systemctl start pivccu
21:47:56.261011 Sending HM frame:  fd 00 03 fe 00 01 14 1e
21:47:56.265722 Received HM frame: fd 00 11 fe 00 05 01 44 75 61 6c 43 6f 50 72 6f 5f 41 70 70 a2 21
21:47:56.265842 Sending HM frame:  fd 00 03 fe 01 02 92 17
21:47:56.268378 Received HM frame: fd 00 04 fe 01 05 01 07 02
21:47:56.510872 Received HM frame: fd 00 0c 00 00 00 43 6f 5f 43 50 55 5f 42 4c 72 51
21:47:56.510985 Sending HM frame:  fd 00 03 fe 02 01 98 1d
21:47:59.511148 Sending HM frame:  fd 00 03 00 03 00 12 00
21:47:59.513722 Received HM frame: fd 00 0d 00 03 04 02 43 6f 5f 43 50 55 5f 42 4c ff 87
21:47:59.513848 Sending HM frame:  fd 00 03 00 04 03 80 09
21:48:00.044402 Received HM frame: fd 00 04 00 04 04 01 19 6e
21:48:00.080539 Received HM frame: fd 00 10 fe 01 00 44 75 61 6c 43 6f 50 72 6f 5f 41 70 70 b7 36
21:48:00.080716 Sending HM frame:  fd 00 03 01 05 09 86 21
21:48:00.182593 Received HM frame: fd 00 05 01 05 04 01 03 02 24
21:48:00.182751 Sending HM frame:  fd 00 03 01 06 02 0c 18
21:48:00.286151 Received HM frame: fd 00 0d 01 06 04 01 02 08 06 01 00 03 01 14 03 72 e8
21:48:00.286314 Sending HM frame:  fd 00 03 02 07 01 8a 2d
21:48:00.388641 Received HM frame: fd 00 07 02 07 06 01 bc bd f4 da 29
21:48:00.388789 Sending HM frame:  fd 00 03 fe 08 04 a4 03
21:48:00.393273 Received HM frame: fd 00 10 fe 08 05 01 30 14 f7 11 a0 61 a7 db e9 97 5c 15 83 23
21:48:00.393426 Sending HM frame:  fd 00 03 03 09 08 ae 0f
21:48:00.396486 Received HM frame: fd 00 07 03 09 01 01 71 c9 19 3f d1
21:48:00.396628 Sending HM frame:  fd 00 03 03 0a 07 a4 2d
21:48:00.400683 Received HM frame: fd 00 0e 03 0a 01 01 52 45 51 30 39 31 34 34 35 33 5a dc
HM-MOD-RPI-PCB REQ0914453 3014F711A061A7DBE9975C15 0x71C919 0xBCBDF4 2.8.6
`

Tinkerboard-CCU hat jetzt auch wieder die richtige IP-Adresse erhalten. Warum sie bei nicht erkanntem Funk-Modul eine andere Ip erhält, ist nicht richtig logisch.

**Comment by Dott0reAti** [comment]
![2022-07-01 (2)](https://user-images.githubusercontent.com/108345896/176837494-fdfe845a-90ce-4257-b021-7a22cbe8143d.png)
nur um das noch klarzustellen. Alex muss nicht immer das Schlimmste denken ;-) Aber war ja nicht notwendig
