### ISSUE TITLE
FATAL: Module eq3_char_loop not found in directory /lib/modules/5.15.32-v8+

### ISSUE THREAD

**Issue by SKB-CGN** [alexreinert/piVCCU#445]
Hi,
since i updated from debian buster to bullseye on my Pi4, i got the above mentioned error.

```
Jul 24 11:35:56 ioBroker systemd[1]: Starting piVCCU...
Jul 24 11:35:56 ioBroker start_container.sh[935]: modprobe: FATAL: Module eq3_char_loop not found in directory /lib/modules/5.15.32-v8+
Jul 24 11:35:56 ioBroker systemd[1]: pivccu.service: Can't open PID file /run/pivccu3.pid (yet?) after start: Operation not permitted
Jul 24 11:35:56 ioBroker systemd[1]: pivccu.service: Failed with result 'protocol'.
Jul 24 11:35:56 ioBroker systemd[1]: Failed to start piVCCU.
```

i already did:

_Please downgrade to the latest provides official kernel deb using
`sudo apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel`
and ensure, that all necessary package are installed using
`sudo apt install lxc bridge-utils systemd`
After that steps you need reboot.
It could be possible that you have to reinstall the module package after that reboot using
`sudo apt-get install --reinstall pivccu-modules-raspberrypi`
and reboot again._

How would i be able to use it again?

Thank you in advance!

**Comment by alexreinert** [comment]
Did you install the 64 bit image of Raspbian or the 32 bit image and just activated the 64 bit kernel?

**Comment by SKB-CGN** [comment]
I installed the 32 bit Version and only activated 64 bit in config.txt

**Comment by alexreinert** [comment]
That does not work as the required header files for the 64 bit kernel are not provided by the header package of the 32 bit image.
You can use the 32 bit kernel on the 32 bit image or the 64 bit image on the 64 bit image, but not mix them.

**Comment by SKB-CGN** [comment]
Ok, is it possible somehow to make a backup of the system and restore it on the 64bit system easily?

Thanks!

**Comment by alexreinert** [comment]
Depends on what you mean with the system.
If you mean just the CCU: Switch to 32 bit kernel and use the backup option in the WebUI.
