### ISSUE TITLE
Missing LEDs in /sys/class/leds/rpi_rf_mod:blue green red

### ISSUE THREAD

**Issue by SuperJojo2001** [alexreinert/piVCCU#446]
Hello,

I have installed the kernel modules with "apt install pivccu-modules-dkms" on my Raspberry Pi3+ (Homematic IP) running an actual Raspberry PI OS in the version 5.15.32. . I am using the OS in 32-Bit operating mode.
My expectation is that once I am installing the device tree patches with "apt install pivccu-modules-raspberrypi" finally that after the reset I am also able to see the LEDs "rpi_rf_mod:..." under /sys/class/leds/ are created as well. 
I see correctly the "pivccu-raspberrypi.dtbo" file present in the "/boot/overlays" folder correctly and I also see the entry "dtoverlay=pivccu-raspberrypi" in the /boot/config.txt file.
Was there maybe something changed/made incompatible when creating LEDs via overlays between OS 4.x to 5.x?

Thx
Armin

**Comment by alexreinert** [comment]
You have to load the kernel module with the correct GPIO numbers, see https://github.com/alexreinert/piVCCU/blob/e4217d1e781d2fd0cfcd837fa957bd71fe32cdd3/pivccu/host3/start_container.sh#L44

**Comment by SuperJojo2001** [comment]
Worked with charme! Thx Armin
