### ISSUE TITLE
Versionsnummern passen nicht ganz

### ISSUE THREAD

**Issue by Frank795** [alexreinert/piVCCU#447]
Hallo, ich nutze meine piVCCU3 zusammen mit IOBroker,da habe ich ein skript laufen welches prüft ob Updates verfägber sind. 
Ich werde aber immer benachrichtigt obwohl kein update verfügbar ist. bin dann mal etwas auf die suche gegangen.
Anbei mal 2 Bilder der piVCCU schon da passt es nicht(ab "-" fehlt).Wird so an den IOBroker übergeben.("hm-rega"Adapter)
Kannst du da was machen oder geht das nicht das die versionsnummer komplett angezeigt wird.

piVCCU Startseite :
![2](https://user-images.githubusercontent.com/53878761/182023425-36acf069-4dfb-42e5-b920-4ac009dd761c.PNG)
piVCCU Zentralenwartung :
![1](https://user-images.githubusercontent.com/53878761/182023428-d998a40e-42b7-4de0-97bd-403c6915267d.PNG)
IOBroker :
![3](https://user-images.githubusercontent.com/53878761/182023427-fe1cdf96-9159-49e1-b158-9d49ea4cab71.PNG)

**Comment by alexreinert** [comment]
Das ist bewusst so, nach außen hin soll sich piVCCU exakt gleich verhalten wie eine CCU3.

**Comment by Frank795** [comment]
Ach so, dann weiß ich bescheid,Danke 👍
