### ISSUE TITLE
jp-hp-devices

### ISSUE THREAD

**Issue by MartinKrause57** [alexreinert/piVCCU#448]
Hallo
Ich wollte das addon 6 installieren. Habe aber übersehen , das dies vor dem update auf 3.65.6 pivccu geschehen ist. Wie kann ich ein update durchführen. Wie gelingt ein upgrade.
Martin

**Comment by alexreinert** [comment]
Mit apt, siehe Readme

**Comment by MartinKrause57** [comment]
Hat geklappt.
Danke
