### ISSUE TITLE
newly registered and configured devices get lost during reboot

### ISSUE THREAD

**Issue by Chris5917** [alexreinert/piVCCU#45]
Hi,

first of all, I don't think this is a piVCCU related Topic as I have found a similar note in the raspberrymatic issue-section, but by my skills I cannot make a deep dive analysis. Maybe it's worth to share my perceptions.

I transitioned 50 devices by hand, using the new build to cleanse my environment. At the beginning I thought Idid something wrong, missed to press the ready button etc. I could register the device, test it, gave it a meaningful name and took it in the operational repository. 

During the transitionphase I rebooted the CCU several times via the syscontrol menu. In some of those reboots a newly (and only newly) registered device disappeared and I needed to re-install it. The device itself was set to factory settings before it was registered, after the reboot and it got lost I had to reset it again.

I'm using the 19-04-2018 Image of piVCCU (latest), HomeMaticFW Release 2.31.25.
Additional installed AddOns: CUxD 2.0.0, email 1.6.8, hmPrint1.2a, quickaccess-2.0b5

khilman describes the  same experience using RaspberryMatic (https://github.com/jens-maus/RaspberryMatic/issues/307).

Does anyone have same/similar experience ?

BR
  Chris

**Comment by alexreinert** [comment]
Sound to me like a bug in the Homematic firmware, especially as the same issue occurs in RaspberryMatic.
So this needs to be fixed in the original firmware.
