### ISSUE TITLE
HomeMatic with HmIP-RFUSB possible?

### ISSUE THREAD

**Issue by carsten12** [alexreinert/piVCCU#458]
Hello,

I understood that piVCCU3 and HmIP-RFUSB are now serving both: HomeMatic and HomMeatic IP (at least according to some information in HomeMatic Forum. Github Readme is saying it only supports HomeMatic IP, so if this is true, I may not have any issue ;-).

But assuming it is also supporting HomeMatic, I gave piVCCU a try with two environments:

**piVCCU** on a T95Z Plus TV box running Armbian Debian Bullseye. Installation was a bit tricky, as this Armbian was cross-compiled but finally I was able to install the modules. Output of pivccu-info is:

```
piVCCU version: 3.65.8-74
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-xhci-hcd.3.auto-2 (/dev/raw-uart)
 Board serial:  1F299EC93D
 Radio MAC:     0xFFAACF
HMIP Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-xhci-hcd.3.auto-2 (/dev/raw-uart)
 SGTIN:         3014F711A000041F299EC93D
 Radio MAC:     0xB7F77A
State:          RUNNING
PID:            2960
IP:             192.168.178.113
Link:           vethpivccu
 TX bytes:      10.24 KiB
 RX bytes:      35.80 KiB
 Total bytes:   46.05 KiB
```

I can connect to the webgui and I have two devices: HM-RCV-50 BidCoS-RF and HmIP-RCV-50 HmIP-RCV-1. I mention this, because in my second environment, there will be an HmIP-RFUSB0 available in addition and I don't know whether this is an issue. 

Second environment is **debmatic** but I did not want to do a cross-post there. Output of debmatic-info is:

```
debmatic version: 3.65.8-95
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-0000:00:12.0-2 (/dev/raw-uart)
 Board serial:  1F299EC93D
 Radio MAC:     0xFFAACF
HMIP Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-0000:00:12.0-2 (/dev/raw-uart)
 SGTIN:         3014F711A000041F299EC93D
 Radio MAC:     0xBDF4F5
```

As said, in this case I have the HmIP-RFUSB0 device in addition, showing 1% Duty Cycle and 0% Carrier Sense. 

In both environments, I tried to learn a HM-Sec-SCo after factory reset. The device will not show up. I use the cable which came with the Stick and placed it as far away as possible of the two mainboards. 

I see some possible root causes:

- piVCCU/debmatic do not support HomeMatic with HmIP-RFUSB. Could be probable as both environments fail
- something went wrong during building modules, hence no HmIP-RFUSB0 in piVCCU as opposed to debmatic
- the stick is not functioning correctly because I did nod solder correctly (unprobable, as we can see the stick's serial, or?)

Can you please give me some hints how to proceed? In the end it would not be a big issue if only HmIP is supported, as I have a running FHEM environment with my classic HomeMatic connected to HM-CFG-LAN. But I found it an interesting project to move FHEM and piVCCU to the Armbian box.

Thanks for your work! 
Carsten.

**Comment by alexreinert** [comment]
Both, debmatic and piVCCU are supporting the HmIP-RFUSB with HM and HmIP dual use. One goal of piVCCU is to emulate the CCU3 as close as possible, because of that there is no additional (visible) device of the radio module by default.

How did you do the factory reset and how did you try to teach in the devices exactly?
Can you provide pictures of the solder joints? If some of them are not correct, you will have issues with transmitting and receiving signals, but unfortunately the stick does not report any errors.

P.S. If you want, we can switch to german.

**Comment by carsten12** [comment]
Hallo, danke für die schnelle Antwort. 

Dann bin ich erstmal beruhigt, dass die Module scheinbar in Ordnung sind, denn die Combo Arbian/piVCCU wäre mein primäres Ziel. Dann lasse ich da auch FHEM drauf laufen und kann es frei platzieren.

Factory Reset des HM-Sec-SCo nach Handbuch: 
  - 5 Sekunden drücken, es blinkt langsam rot
  - nochmals 5 Sekunden drücken, es blinkt schnell rot
  - loslassen, es leuchtet rot, bevor es ausgeht
  
Anlernen:
  - Klick auf Geräte anlernen rechts oben
  - Klick links oben auf HomeMatic Gerät direkt anlernen Knopf HM Gerät anlernen (zählt von 60 runter)
  - Kurzer Klick auf den HM-Sec-SCo (blinkt orange, ca. 20 Sekunden)
  - CCU kommt bei 0 an und nix im Postkasten.

Insofern werde ich jetzt noch mal die Lötstellen überprüfen und durchmessen bzw. nachlöten. Melde mich dann gleich wieder. 

Gruß,
Carsten.

**Comment by carsten12** [comment]
PS: Lötstellen überprüft, nachgelöst und durchgemessen. Wieder an beiden Geräten probiert, gleiches Ergebnis. 
Ich setze das jetzt noch mal ganz von vorne auf, es hat sich gerade irgendwas mit der bridge verstellt.

**Comment by carsten12** [comment]
So, alles mehrfach neu aufgesetzt, viel über bridging geleert, aber hier läuft weiterhin nix. Ich habe leider keine HomeMatic IP Geräte, mit denen ich mal ausprobieren könnte, ob es nur ein Problem mit HomeMatic ist. 

Bin also ziemlich ratlos, was ich noch probieren könnte. Außer den Stick reklamieren und zu schauen, ob da vielleicht ein Defekt vorliegt.

**Comment by jens-maus** [comment]
Ohne hier Werbung machen zu wollen, aber probier doch mal ob der Stick mit einer RaspberryMatic funktioniert. Wenn ja, liegt es an deiner piVCCU Installation und nicht am Stick.

**Comment by carsten12** [comment]
Danke für den Tipp Jens, ich hatte daran schon gedacht, aber funktioniert denn HomeMatic (ohne IP) mit RaspberryMatic und dem HmIP-RFUSB? Ich dachte nämlich, das geht nicht...

**Comment by jens-maus** [comment]
Wenn es wirklich ein HmIP-RFUSB und *kein* HmIP-RFUSB-TK ist, dann geht das, weil es dafür die 4.4.x Firmware gibt die auch bei RaspberryMatic dabei und dann automatisch geflasht wird.

**Comment by carsten12** [comment]
Ich weiß nicht, ob es richtig ist, dass wir hier weiter diskutieren, da aber ja die gleichen Module Verwendung finden, wie für die pivccu3 denke ich, es ist erstmal ok.

Danke für den Tipp Jens, ich habe RaspberryMatic in einem Docker auf einem amd64 Debian installiert. Ich habe dann den Anlernvorgang gestartet und dachte schon: das ist es, als ein Gerät im Postkasten auftauchte. Leider war es aber nur ein HmIP-RFUSB was ich nicht verstehe, der Stick hat sich selber erkannt ?!?

Ich probiere noch ein wenig damit herum, ansonsten schicke ich den zu ELV und hoffe, dass sie ihn tauschen. Löten kann ich eigentlich, sieht perfekt aus.

**Comment by jens-maus** [comment]
> Danke für den Tipp Jens, ich habe RaspberryMatic in einem Docker auf einem amd64 Debian installiert. Ich habe dann den Anlernvorgang gestartet und dachte schon: das ist es, als ein Gerät im Postkasten auftauchte. Leider war es aber nur ein HmIP-RFUSB was ich nicht verstehe, der Stick hat sich selber erkannt ?!?

Tut mir leid, aber das geht hier definitiv zu weit! Das ist ein Bug/Issue Tracker und kein Supportforum. Meld dich bei homematic-forum.de an und finde da Hilfe. Und wenn ich deine Zeilen so bzgl. "der Stick hat sich selber erkannt?" lese würde ich sagen du solltest dich erst einmal mit den Grundzügen/Grundkenntnissen bzgl Homematic bzw. einer CCU vertraut machen und das hier ist definitiv der falsche Platz dazu.

**Comment by carsten12** [comment]
Danke trotzdem.

**Comment by alexreinert** [comment]
> > Danke für den Tipp Jens, ich habe RaspberryMatic in einem Docker auf einem amd64 Debian installiert. Ich habe dann den Anlernvorgang gestartet und dachte schon: das ist es, als ein Gerät im Postkasten auftauchte. Leider war es aber nur ein HmIP-RFUSB was ich nicht verstehe, der Stick hat sich selber erkannt ?!?
> 
> Tut mir leid, aber das geht hier definitiv zu weit! Das ist ein Bug/Issue Tracker und kein Supportforum. Meld dich bei homematic-forum.de an und finde da Hilfe. Und wenn ich deine Zeilen so bzgl. "der Stick hat sich selber erkannt?" lese würde ich sagen du solltest dich erst einmal mit den Grundzügen/Grundkenntnissen bzgl Homematic bzw. einer CCU vertraut machen und das hier ist definitiv der falsche Platz dazu.

Jens, du darfst gerne in deinem Projekt machen, was du willst, aber hier bist du auch nur Gast, also führ dich bitte nicht auf, als wärst du hier ein Maintainer.

**Comment by alexreinert** [comment]
@carsten12 Waren die Geräte schonmal wo anders angelernt und wurde da ggf. ein Sicherheitsschhlüssel gesetzt?

**Comment by carsten12** [comment]
Guten Morgen, die Geräte kommen "frisch aus der Tüte" und waren originalverpackt. Ich habe vorsichtshalbe noch mal Fotos gemacht, man weiß ja nie...
![IMG_0197](https://user-images.githubusercontent.com/1044186/202839962-6e41719e-0481-43a4-b7db-34bd4303075e.jpg)
![IMG_0198](https://user-images.githubusercontent.com/1044186/202839964-1a47080b-a13b-48b6-be60-89274d331372.jpg)

**Comment by carsten12** [comment]
@alexreinert gibt es irgendein Logfile in dem man sehen könnte, dass der Stick irgendeinen Funk empfängt (den er aber ignoriert, weil die piVCCU in der er steckt dafür nicht konfiguriert ist? Ich habe im Haus ja eine laufende FHEM VCCU HomeMatic Installation und mein Nachbar ein paar Häuser weiter hat HomeMatic und HomeMatic IP und dessen Thermostate habe ich auch schon mal in der FHEM/VCCU "gesehen". Also hier wäre schon was zu empfangen.

**Comment by carsten12** [comment]
So, ich habe noch mal den ganzen Tag herum probiert ich schicke es morgen zurück. Lieben Dank für die Hilfe @alexreinert!
