### ISSUE TITLE
Kann Webinterface nicht anzeigen

### ISSUE THREAD

**Issue by miloit** [alexreinert/piVCCU#460]
Habe piVCCU3 nun 2x mal komplett nach Anleitung installiert.
piVCCU läuft, leider kann ich aber auf das Webinterface nicht zugreifen.
Wenn ich es manuell stoppen/starten möchte, wird es auch nicht gefunden/startet nicht.
Pingen des Containers ist möglich auch der Ping innerhalb des Containers auf die "Aussenwelt".

`
root@orangepizero:~# sudo pivccu-info
piVCCU version: 3.65.8-74
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO@1c28400.serial (/dev/raw-uart)
 Board serial:  PEQ2214702
 Radio MAC:     0x6BD839
HMIP Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO@1c28400.serial (/dev/raw-uart)
 SGTIN:         3014F711A061A7D8A9AB332E
 Radio MAC:     0xB59636
State:          RUNNING
PID:            1717
IP:             169.254.12.168
Link:           vethpivccu
 TX bytes:      108.85 KiB
 RX bytes:      6.79 KiB
 Total bytes:   115.64 KiB
`

`root@orangepizero:~# sudo pivccu-attach cat /var/hm_mode
lxc-attach: lxc: terminal.c: lxc_terminal_create_native: 924 Not a directory - Failed to open terminal multiplexer device
HM_HMIP_ADDRESS='0xB59636'
HM_HMIP_ADDRESS_ACTIVE='0xB59636'
HM_HMIP_DEV='HM-MOD-RPI-PCB'
HM_HMIP_DEVNODE='/dev/raw-uart'
HM_HMIP_DEVTYPE='GPIO@1c28400.serial'
HM_HMIP_SERIAL='PEQ2214702'
HM_HMIP_SGTIN='3014F711A061A7D8A9AB332E'
HM_HMIP_VERSION='2.8.6'
HM_HMRF_ADDRESS='0x6BD839'
HM_HMRF_ADDRESS_ACTIVE='0x6BD839'
HM_HMRF_DEV='HM-MOD-RPI-PCB'
HM_HMRF_DEVNODE='/dev/raw-uart'
HM_HMRF_DEVTYPE='GPIO@1c28400.serial'
HM_HMRF_SERIAL='PEQ2214702'
HM_HMRF_VERSION='2.8.6'
HM_HOST='rpi3'
HM_HOST_GPIO_RESET=''
HM_HOST_GPIO_UART='/dev/raw-uart'
HM_LED_GREEN=''
HM_LED_GREEN_MODE1='none'
HM_LED_GREEN_MODE2='none'
HM_LED_RED=''
HM_LED_RED_MODE1='none'
HM_LED_RED_MODE2='none'
HM_LED_YELLOW=''
HM_LED_YELLOW_MODE1='none'
HM_LED_YELLOW_MODE2='none'
HM_MODE='NORMAL'
HM_RTC=''
`

`Nov 21 08:06:56 ccu3-webui daemon.info avahi-autoipd(eth0)[166]: Successfully claimed IP address 169.254.12.168
Nov 21 08:06:56 ccu3-webui daemon.err udhcpc[158]: no lease, forking to background
Nov 21 08:06:57 ccu3-webui user.info firewall: configuration set
Nov 21 08:06:57 ccu3-webui daemon.info ifplugd(eth0)[228]: ifplugd 0.28 initializing.
Nov 21 08:06:57 ccu3-webui daemon.info ifplugd(eth0)[228]: Using interface eth0/FA:F8:43:D8:D4:DD with driver <veth> (version: 1.0)
Nov 21 08:06:57 ccu3-webui daemon.info ifplugd(eth0)[228]: Using detection mode: SIOCETHTOOL
Nov 21 08:06:57 ccu3-webui daemon.info ifplugd(eth0)[228]: Initialization complete, link beat detected.
Nov 21 08:06:57 ccu3-webui daemon.warn ifplugd(eth0)[228]: Could not open /dev/tty, cannot beep.
Nov 21 08:06:57 ccu3-webui daemon.info ifplugd(eth0)[228]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
Nov 21 08:06:57 ccu3-webui daemon.warn ifplugd(eth0)[228]: client: ifup: interface eth0 already configured
Nov 21 08:06:57 ccu3-webui daemon.info ifplugd(eth0)[228]: Program executed successfully.
Nov 21 08:06:57 ccu3-webui daemon.err ntpdate[239]: name server cannot be used: Temporary failure in name resolution (-3)
Nov 21 08:06:57 ccu3-webui daemon.notice ntpd[240]: ntpd 4.2.8p12@1.3728-o Thu Jul 14 12:42:17 CEST 2022 (1): Starting
Nov 21 08:06:57 ccu3-webui daemon.info ntpd[240]: Command line: /usr/sbin/ntpd -g 0.de.pool.ntp.org 1.de.pool.ntp.org 2.de.pool.ntp.org 3.de.pool.ntp.org
Nov 21 08:06:57 ccu3-webui daemon.info ntpd[242]: proto: precision = 0.708 usec (-20)
Nov 21 08:06:57 ccu3-webui daemon.info ntpd[242]: Listen and drop on 0 v6wildcard [::]:123
Nov 21 08:06:57 ccu3-webui daemon.info ntpd[242]: Listen and drop on 1 v4wildcard 0.0.0.0:123
Nov 21 08:06:57 ccu3-webui daemon.info ntpd[242]: Listen normally on 2 lo 127.0.0.1:123
Nov 21 08:06:57 ccu3-webui daemon.info ntpd[242]: Listen normally on 3 eth0:avahi 169.254.12.168:123
Nov 21 08:06:57 ccu3-webui daemon.info ntpd[242]: Listen normally on 4 lo [::1]:123
Nov 21 08:06:57 ccu3-webui daemon.info ntpd[242]: Listening on routing socket on fd #21 for interface updates
Nov 21 08:06:57 ccu3-webui daemon.info ntpd[242]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
Nov 21 08:06:57 ccu3-webui daemon.info ntpd[242]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
Nov 21 08:06:57 ccu3-webui daemon.err xinetd[260]: Unable to read included directory: /etc/config/xinetd.d [file=/etc/xinetd.conf] [line=14]
Nov 21 08:06:57 ccu3-webui daemon.crit xinetd[260]: 260 {init_services} no services. Exiting...
Nov 21 08:07:02 ccu3-webui user.info kernel: [  401.862773] eq3loop: created slave mmd_hmip
Nov 21 08:07:02 ccu3-webui user.info kernel: [  401.863453] eq3loop: created slave mmd_bidcos
Nov 21 08:07:05 ccu3-webui user.info kernel: [  404.081664] eq3loop: eq3loop_open_slave() mmd_bidcos
Nov 21 08:07:16 ccu3-webui daemon.err udhcpc[174]: sending discover
Nov 21 08:07:19 ccu3-webui daemon.err udhcpc[174]: sending discover
Nov 21 08:07:22 ccu3-webui daemon.err udhcpc[174]: sending discover
Nov 21 08:07:25 ccu3-webui daemon.err udhcpc[174]: sending discover
Nov 21 08:07:28 ccu3-webui daemon.err udhcpc[174]: sending discover
Nov 21 08:07:31 ccu3-webui daemon.err udhcpc[174]: sending discover
Nov 21 08:07:32 ccu3-webui user.info kernel: [  431.212286] eq3loop: eq3loop_close_slave() mmd_hmip
Nov 21 08:07:32 ccu3-webui user.info kernel: [  431.219970] eq3loop: eq3loop_open_slave() mmd_hmip
Nov 21 08:07:32 ccu3-webui user.info kernel: [  431.221656] eq3loop: eq3loop_open_slave() mmd_hmip
Nov 21 08:07:34 ccu3-webui daemon.err udhcpc[174]: sending discover
Nov 21 08:07:37 ccu3-webui daemon.err udhcpc[174]: sending discover
Nov 21 08:07:41 ccu3-webui daemon.err udhcpc[174]: sending discover
`

Gibt es eine Hilfe?

**Comment by alexreinert** [comment]
Der Container bekommt per DHCP keine IP.
Ist parallel noch Docker installiert? Das erstellt fehlerhafte iptables Regeln, welche alle Container betreffen und nicht nur die Docker Container.

**Comment by miloit** [comment]
Nein kein Docker parallel installiert

**Comment by alexreinert** [comment]
Welches OS ist installiert? Wie sieht die /etc/network/interfaces aus? Wie ist der Host ans Netzwerk angebunden? Welcher DHCP Server wird verwendet? Welcher Switch wird verwendet?

**Comment by miloit** [comment]
OS ist armbian bullseye
/etc/network/interfaces
`source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback

auto wlx1cbfcec5d687
iface wlx1cbfcec5d687 inet dhcp
  wpa-ssid     "FRITZ!Box 7590 MK"
  wpa-psk      "07015987179473504700"

auto br0
iface br0 inet static
  bridge_ports none
  bridge_fd    0
  address      192.168.253.1
  netmask      255.255.255.0`

Host ist via WLAN stick an eine fritz box angeschlossen.

**Comment by alexreinert** [comment]
Das ist keine Installation nach Anleitung, zumindest nicht nach den Anleitungen hier. Du hast der Brige br0 keinen physikalischen Netzwerkanschluss gegeben, damit kann der Container dann auch nicht mit dem Netzwerk reden.

**Comment by miloit** [comment]
Welchen Schritt habe ich vergessen? Habe es nach 

https://github.com/alexreinert/piVCCU/blob/master/docs/setup/armbian.md

https://github.com/alexreinert/piVCCU/blob/master/docs/setup/wlan.md

Gemacht...

**Comment by alexreinert** [comment]
Der Container ist aber offensichtlich nicht auf Static IP, sondern auf DHCP konfiguriert (Schritt 2 in der WLAN Doku).

**Comment by carsten12** [comment]
@miloit läuft das bei Deiner Armbian Kiste über /etc/network und nicht über nmcli? 

Was sagt brctl show? Steht da die vethpivccu unter der br0? Wenn nicht, probier mal mit systemctl restart pivccu neu zu starten und schaue ob es dann geht. Wenn ja habe ich eine Lösung in einem anderen issue hier beschrieben.
