### ISSUE TITLE
Service pivccu-dkms beendet sich instantan mit Status 0 (SUCCESS)

### ISSUE THREAD

**Issue by totti4ever** [alexreinert/piVCCU#463]
Hallo, ich nutze Raspberrymatic und in dem Kontext den DKMS-Service. Das hat bis vor ein paar Tagen wunderbar funktioniert. Aber plötzlich hatte die raspberrymatic CCU keinerlei Infos mehr zu den Geräten.

Mittlerweile bin ich soweit, dass ich herausgefunden habe, dass der pivccu-dklms Service nicht mehr läuft (und das auch exakt seit dem Zeitpunkt, ab dem die CCU nichts mehr an Home Assistant reported hat). Ich kriege den Service aber nicht wieder zum Laufen.

Was habe ich bereits gemacht:
- Server (Ubuntu 18.04) neugestartet
- Service neugestartet
- Service neuinstalliert & neugestartet

Ich finde leider auch keine hilfreichen logs. `journalctl -xe` bringt nur folgendes zutage:
```
systemd[1]: Starting piVCCU DKMS Modules...
-- Subject: Unit pivccu-dkms.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit pivccu-dkms.service has begun starting up.
Dez 13 11:42:26 kiwi systemd[1]: Started piVCCU DKMS Modules.
-- Subject: Unit pivccu-dkms.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit pivccu-dkms.service has finished starting up.
--
-- The start-up result is RESULT.
```

`service status` bringt:
```
● pivccu-dkms.service - piVCCU DKMS Modules
   Loaded: loaded (/lib/systemd/system/pivccu-dkms.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2022-12-13 11:42:26 CET; 50s ago
  Process: 17569 ExecStart=/var/lib/piVCCU/dkms/ensure_modules.sh (code=exited, status=0/SUCCESS)
 Main PID: 17569 (code=exited, status=0/SUCCESS)
```

Hat irgendjemand eine Idee oder noch einen Tipp, wo ich mehr Details herbekommen könnte?

Besten Dank!

**Comment by alexreinert** [comment]
Der Service läuft nicht dauerhaft, sondern nur beim Boot bei einem neuen Kernel ggf. die Kernel Module per DKMS neu zu bauen.

Bei allgemeinen Problemen mit RaspberryMatic bitte deren Issue Tracker nutzen, ich kann für RaspberryMatic keinen Support leisten.

**Comment by totti4ever** [comment]
@alexreinert, Support zu RaspberryMatic hatte ich mir auch nicht erhofft. Hatte nur gehofft, dass der DKMS Service mein dortiges Problem ist.

Nunja, leider nicht - danke für die prompte Antwort!
