### ISSUE TITLE
Falsche Hysteresewerte und Steuerung der BWTH-Thermostate nach Update auf FW 2.8.10

### ISSUE THREAD

**Issue by Micha-DU** [alexreinert/piVCCU#464]
Hallo zusammen, 

nachdem ich meine HmIP-BWTH (wenn auch erst im Beta-Stadium) auf die FW-Version 2.8.10 aktualisiert habe, um ENDLICH die lang ersehnte Zweipunkt-Regelung zu erhalten, ist die Ernüchterung groß: die Regelung macht mehr oder weniger, was sie will und hält auch die eingestellte Hysterese nicht ein. Mehrere Tests mit einem User, der RaspberryMatic in der aktuellsten Version nutzt, haben ergeben, dass bei ihm alles einwandfrei funktioniert. In den release notes zur RaspberryMatic habe ich dann folgendes gelesen:

CCU/HomeMatic service changes:

    updated [OCCU](https://github.com/eq-3/occu) version to [3.65.11-1](https://github.com/jens-maus/occu/tree/b_3_65) integrating full compatibility to the [CCU3 3.65.11 firmware](https://homematic-ip.com/sites/default/files/other_media/ccu3-changelog-3-65-11.pdf) which comes with the following changes:
        Correction of wrong hysteresis value for 2-point control after HmIP-WTH-2 update to FW 2.8.2.
        Correction for resumption of paused updates for event listeners.
        
Also stellt sich die Frage, ob hier auch ein Update der pivCCU3 in der pipeline ist? ;-)

LG Micha

**Comment by alexreinert** [comment]
Es ist schon lange fertig, aber ich es aufgrund anderer kritischerer Bugs nicht in das stable APT Repository übernommen. Wenn man die Version dennoch möchte, einfach temporär auf das testing APT Repository wechseln.
