### ISSUE TITLE
HmIP-RFUSB with HM-MOD-RPI-PCB together

### ISSUE THREAD

**Issue by Sirmike2** [alexreinert/piVCCU#465]
Hi,

I wanted to use the HmIP-RFUSB with HM-MOD-RPI-PCB together on a raspberry Pi 4, but the piVCCU only use the HM-MOD-RPI-PCB adapter. Both adapters are recognized as /dev/raw-uart and /dev/raw-uart1.

Is it possible to use both adapter with piVCCU3 or is this not possible?

Thanks for answering!

BR

**Comment by alexreinert** [comment]
Both modules are capable of dual Copro mode, why should when two modules be used?
And because of the dual copro, it is not possible two use both modules as this would require two instances of multimacd, which is not possible.

**Comment by Sirmike2** [comment]
Ah ok, thanks for the answer. 

I have a lot of old RF Homematic equipment and some new HmIP stuff. For these things I need a bigger range, that is why I am using the old HM-MOD-RPI-PCB with an external antenna. I only need the HmIP-RFUSB for the HmIP-wired system. The HM-MOD-RPI-PCB could not handle the new wired system, only the normal HmIP equipment.
I think the USB Stick will not have the same range, that I will get all my devices.
That was the reason, why I would like to use both of them.

BR
