### ISSUE TITLE
pivccu-modules-dkms incorrectly builds x86 modules on 64bit systems

### ISSUE THREAD

**Issue by derreisende77** [alexreinert/piVCCU#468]
On my Ubuntu Ubuntu 22.04.1 LTS 64bit machine `sudo apt install pivccu-modules-dkms` successfully builds kernel modules with `ARCH=x86`, which are unusable by the kernel. I am unable to use a HmIP-RFUSB dongle.
Trying to load a module causes following error:
```bash
sudo modprobe eq3_char_loop
modprobe: ERROR: could not insert 'eq3_char_loop': Exec format error
```

dmesg shows the following error:
```
module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc 00000000a65c8f9b, val ffffffffc0fcb91d
```
uname output:
```
Linux thinkpad-ubuntu 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Is there a way to build 64bit kernel modules which can be loaded?

**Comment by derreisende77** [comment]
Added more detailed error description

**Comment by alexreinert** [comment]
This is not an issue with 64 bit, it is an issue with invalid installed headers by the Ubuntu installer (module signing enabled in headers, but not in kernel itself)
Reinstall the kernel headers and reinstall the pivccu-modules-package afterwards.

**Comment by derreisende77** [comment]
Reinstalled all headers and the modules package. Now everything works as expected. Thank you very much!
Maybe this should be documented here for other user who might run into this problem?
