### ISSUE TITLE
WTH-1 lässt sich nicht anlernen

### ISSUE THREAD

**Issue by Toube94** [alexreinert/piVCCU#469]

**Comment by alexreinert** [comment]
Der WTH-1 geht erst ab Version 3.65.11, die gibt es nur im testing APT Repository.

**Comment by alexreinert** [comment]
Die wird wegen anderer Probleme gar nicht in stable kommen, bei eQ-3 scheint aber grade eine Version 3.67.x auf der Zielgeraden zu sein, welche dann hoffentlich wieder in stable landen kann.
Ein Wechsel von testing zu stable ist kein Problem, allerdings wird dabei kein Downgrade gemacht, sondern es passiert dann erst ein Update, wenn es was neueres in stable gibt.
