### ISSUE TITLE
HMIP Kommunikationsprobleme

### ISSUE THREAD

**Issue by webgambler** [alexreinert/piVCCU#470]
Hallo, Leider ist es wohl tatzächlich so das es Probleme mit HMIP gibt. Bei mir läuft folgende Installation:
Rapi P4, mit RPI-RF-MOD

Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Connected via: GPIO@fe201000.serial (/dev/raw-uart)
 Board serial:  9D89AB2A58
 Radio MAC:     0x76FD04
HMIP Hardware:  RPI-RF-MOD
 Connected via: GPIO@fe201000.serial (/dev/raw-uart)
 SGTIN:         3014F711A0001F9D89AB2A58
 Radio MAC:     0xBDEC1C
State:          RUNNING
PID:            5286
IP:             192.168.111.3
Link:           vethpivccu
 TX bytes:      39.93 MiB
 RX bytes:      27.44 MiB
 Total bytes:   67.37 MiB

Parallel dazu den IO Broker

Im prinziep läuft alles gut und ich konnte zu beginn 4 Heizungsmodule vom Type HMIP-StHD anlernen.
aus der "alten" Konfiguration mit Rapi3 und dem Pi HM-MOD-RPI-PCB hatte ich noch 2 6fach Sender mit rübergenommen.
zu beginn lief das ganze Problemlos.
Seit dem Zeitpunkt x ist die Kommunikation von der Zentrale zu dem Komponenten gestört.
Das viel am anfang nicht gleich auf da die Temperaturen weiter zu Zentrale gesendet wurden und die Schaltfunktionen gingen auch
(hier gab es den effect das die Rückmeldung nicht kam gelb und rot blinken am Sender)

Da die Temperatursenden irgendwie in den Manuellen modus gefallen sind lassen sich diese nun nicht umstellen
und die Bude wird langsam kalt :-(

Ich muss mir nun also was einfallen lassen und hoffe Hier auf Hilfe

Gestern Abend habe ich mal einen TempSensor Abgemeldet was auch nur erst durchgeführt wurde nachdem ich den Raspi neu 
gestartet hatte. Ein Anlernen was bisher nicht mehr möglich weder Automatisch noch über Key ...

Welche Informationen kann ich zur Lösungsfindung noch beitragen ?
Danke und Gruß

**Comment by alexreinert** [comment]
Der Raspberry Pi 4 ist ein massiver Störsender auf 868MHz, hier hilft es regelmäßig nur, mind. 1m Abstand zwischen Funkmodul und Raspberry zu bringen. Nur die Antenne absetzen reicht nicht, weil die Störstrahlung auch direkt auf das Funkmodul einwirkt. HmIP mit seinem Listen before Talk ist von dieser Störstrahlung extrem stark betroffen, im Gegensatz zu BidCos, welches ohne Listen before Talk direkt funkt, auch wenn Störstrahlung vorhanden ist.

**Comment by webgambler** [comment]
Hallo

Danke für die schnelle Antwort!
Würde ich das ganze mit dem HB-RF-USB2 verlängern können?



⁣BlueMail for Android herunterladen ​

**Comment by webgambler** [comment]
Danke für den Tip, mit dem Board das ganze getrennt vom PI4 Umbegaut und nun geht es !
hätte ich nicht gedacht. 

Das ist mir ein gutes Bier wert, Prost!
