### ISSUE TITLE
No Firmware Updates

### ISSUE THREAD

**Issue by Nasenloch** [alexreinert/piVCCU#471]
I currently have FW 3.65.8 installed. 
Unfortunately I'm not able to update to the latest FW version.  
The UI doesn't inform about a later, available version 
I tried to update by ssh sudo apt-get update && sudo apt-get upgrade

No later version is installed :-(

**Comment by tschombes** [comment]
Same here, i have 3.65.8, too. 

No updates available when i run apt update.

**Comment by alexreinert** [comment]
The latest version in the stable APT repository is 3.65.8.
In the testing APT repository where are versions 3.65.8 and 3.37.10 available.

**Comment by Nasenloch** [comment]
Ok, so I just wait until it will be stable…

**Comment by alexreinert** [comment]
You do not need to wait, it is in stable since yesterday late evening.
