### ISSUE TITLE
HmIP-SAM Acceleration Sensor does not connect

### ISSUE THREAD

**Issue by quarto4** [alexreinert/piVCCU#473]
Hello alexreinert, 

I was trying to connect the SAM Acceleration sensor but in the phase of teaching-in the device it is not being identified.
Is it supposed to work with piVCCU?

Thanks,
quarto4

**Comment by alexreinert** [comment]
That device should work since years. Can you tell more about your system (Hardware, OS, piVCCU version) and how you try to teach in the device?

**Comment by quarto4** [comment]
Wow thats shocking. Then it looks like the issue is on my end as I've built the device based on a kit. 

Pi 4 8GB, HB-RF-USB-2, RPI-RF-MOD, PiVCCU firmware 3.65.8

Trying to connect by using the Homematic standard functionality 
Teach-in devices > Teaching-in of HmIP devices without Internet connection (bottom right)
Enter KEY and SGTIN based on sticker > Teach-in HMIP device (local)

Think I will try again to solder a new one.

Other topic: Btw would devices HmIP-DRSI4 and HmIP-DRDI3 work with piVCCU?

**Comment by alexreinert** [comment]
How much distance is between the Pi and the radio module? In case of Pi 4 this should be at least 0.5m, better 1m.
Please describe the teach in exactly  step by step.
As piVCCU uses the original CCU3 firmware, every device supported there should be supported, too. This includes the HmIP-DRSI4 and the HmIP-DRDI3.

**Comment by quarto4** [comment]
Distance was less than 0.5, changed now to 1m.

CCU main screen > click on Teach-in devices (main menu top right)
Enter key and SGTIN on bottom right screen > click Teach-in HmIP device (local)
Insert batteries in device
Devices lights orange for a sec and then green for a sec
Device blinks orange every 10 secs
Teach-in mode 60s active (counts down)
Starting a second round by clicking on Teach-in HmIP device (local)
Teach-in mode 60s active (counts down)
Does not appear in Inbox (0 )

**Comment by alexreinert** [comment]
Please try:
- Remove Batteries
- Start teach in mode in WebUI
- Wait for countdown starting
- Insert batteries
- Click nothing in WebUI, do not press anything on the device
- Wait until countdown in finished

**Comment by quarto4** [comment]
I tried but unfortunately that did not solve it.
Maybe there is an issue with the device assembly.
Will check it again.

Thank you for your help.
