### ISSUE TITLE
Vccu3.67.10-77 mit io broker und GPIO Zugriff

### ISSUE THREAD

**Issue by webgambler** [alexreinert/piVCCU#479]
Hallo
Ich brauche mal bitte Hilfe!
Ich habe hier einen Pi mit piVCCU auf einem RASPI4 zum laufen, dazu läuft parallel der io brocker.
Ich wollte heute das Thema Gasverbraucherfassung über den RASPI umsetzen und musste feststellen das die Homatik IP Komponenten
anschließend nicht mehr gingen..
Ich habe für den Eingang des Gaszählers einen GPIO des PI genutzt was auch prinzipiell funktioniert hat!
Nur ich befürche es gibt hier einen Konflikt mit dem HB-RF-USB-2 Board und den GPIO's
Wenn ich den IO-Broker adapter "rpi2"  anhalte gehen die HomaticIP Komponenten wieder ?!

Lässt sich das ganze irgendie auflösen ?
Anderer IO Port oder so ?  (ich nutze im Augenblick den GPIO24)

piVCCU version: 3.67.10-77
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB-2@usb-0000:01:00.0-1.4 (/dev/raw-uart1)
 Board serial:  9D89AB2A58
 Radio MAC:     0x76FD04
HMIP Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB-2@usb-0000:01:00.0-1.4 (/dev/raw-uart1)
 SGTIN:         3014F711A0001F9D89AB2A58
 Radio MAC:     0xBDEC1C
State:          RUNNING
PID:            20727
IP:             192.168.111.3
Link:           vethpivccu
 TX bytes:      2.26 MiB
 RX bytes:      290.42 KiB
 Total bytes:   2.54 MiB

Gruß und Danke!

**Comment by alexreinert** [comment]
Der Treiber registriert im Kernel komplett eigene GPIOs, welche nicht mit den GPIOs des Raspis geshared sind.
Mit der Fehlerbeschreibung habe ich aber keine Ahnung, was hier das Problem sein könnte, vielleicht beschreibst du das Fehlerbild mal etwas genauer?

**Comment by webgambler** [comment]
Hallo Alexander


 


Ich habe die letzten 3 Stunden damit verbracht das ganze von Gestern nachzustellen,


dabei konnte ich den Effect von Gestern zwei mal erzeugen. Wobei ich mir nicht sicher bin, ob es mit den GPIO's zusammenhängt oder eher mit den


mehreren neustartes des PI während der "bastelarbeiten".


 


Heute ist der Effect eher immer im Zusammenhang mit einem neustart des PI aufgetreten.


 


Fact ist jedenfalls das es nur dir Homematic-IP Komponenten betrifft.


Bei den Tastern ist es dann immer so, das diese dauerhaft gelb blinken und kein grün bzw. kein Schaltvorgang stattfindet.


 


Ohne ein handfestes Schema würde ich das ganze erstmal weiter beobachten,


und mich melden wenn ich was genaueres herausgefunden habe!


 


Danke und Gruß !






BlueMail for Android herunterladen
