### ISSUE TITLE
Combination not working  pivccu3 / CUXd / ioBroker /zigbee / USB-Dongle CC2531 - solved

### ISSUE THREAD

**Issue by melzerto** [alexreinert/piVCCU#480]
piVCCU 3.67.10.77, Cux-Daemon 2.9.4
After installing the adapter zegbee.0 and configuring the USB-Dongle to /dev/ttyACM0 with TI Z-Stack/CCxxxx The adapter is going to error with log-entry
error: zigbee.0 (19252) Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
Reason:
The LXC container will grab the ttyACM0 and provide it to Cux-Daemon.
The Cux-Daemon will connect to ttyACM0 and show this port as available at the status page. According to the Cuxd_2.10 manual this is a default behaivor.
Solution: 
Disable this port by adding  TTYASSIGN=ttyACM0:NC in the setup page (cuxd.ini)
In the status page should be then shown 
Kein TTY-Device connected!

**Comment by alexreinert** [comment]
I do not understand your issue. You assign an USB device to the CCU container and complain about the container using it?
Just do not assign it to the container.

**Comment by melzerto** [comment]
The issue is that I dont want to assign the USB port to the LXC container. It does it itself by itself including that Cuxd open the port without any use for it. The more clean way would be of course to block the assignement in the /etc/pivccu3/lxc.config or elsewhere. That could be your final proposed solution.

**Comment by alexreinert** [comment]
And this is already implemented, see the Readme.

**Comment by melzerto** [comment]
Confirmed. After executing sudo **dpkg-reconfigure pivccu3** threre will be the option not to use ttyACM0 device. 
Thank you for hint
