### ISSUE TITLE
Zugriff auf Container

### ISSUE THREAD

**Issue by gbackus** [alexreinert/piVCCU#481]
Hallo Alex Reinert,

vielen Dank für die Erstellung des Projektes piVCCU3.
Homematic und iobroker laufen bei mir seit einigen Wochen super und helfen  bei der Steuerung und Datenerfassung der PV-Anlage. 
Leider habe ich wohl bei der Installation einen Fehler gemacht.
Ich kann mich auf dem Host per pi anmelden und komme auch von dort als root auf die host-Konsole.
Ich kann mich aber nicht mit root auf der Homematic-ip anmelden, da ich wohl das Passwort nicht korrekt angelegt habe. Viele Standardpassworte habe ich schon versucht, aber ohne Erfolg.

Ich bin nicht so der Linux-Insider, deshlab meine Frage, ob ich vom host als pi- oder root-user auch in den CCU3-Container kommen kann, um dort sozusagen als host-root das Passwort des container-root neu zu setzen? Ich habe dazu im Web nicht gefunden.

Beste Grüße,

Gangolf Backus

**Comment by gbackus** [comment]
Sollte jemand anderes als Alex eine Antwort kennen, dann darf der- oder diejenige natürlich auch antworten.

**Comment by alexreinert** [comment]
Das SSH Passwort kann in der WebUI gesetzt werden.
Ansonsten kommt man per `sudo pivccu-attach` vom Host in den Container rein.

**Comment by gbackus** [comment]
Wie einfach, wenn man weiß wie es geht.
Herzlichen Dank.
