### ISSUE TITLE
configure as HMLGW (HM LAN Gateway)

### ISSUE THREAD

**Issue by ioc73** [alexreinert/piVCCU#482]
Hello,
I am facing the issue that after setting the piVCCU into LAN gateway modus status with the HMLGW file in /usr/local/ directory, the system still boots up with the standard webfront end. Also the two systems can not communicate with each other. The status in the master ccu shows "not connected".

Doing this on the RaspberryMatic directly on an PI it worked fine.

Am I doing anything wrong?
Please let me know if any additional information or logs are needed.

thx
Oliver

**Comment by alexreinert** [comment]
HMLGW is not part of piVCCU nor the CCU firmware. But you can install it without piVCCU directly on Raspbian, see https://homematic-forum.de/forum/viewtopic.php?f=18&t=27705

**Comment by ioc73** [comment]
Thx for the feedback. I'll try it with your provided link/description. 
I thought this would work like described here https://homematic-guru.de/raspberrymatic-als-homematic-lan-gateway-einsetzen
Thx
Oliver
