### ISSUE TITLE
Nach Update ist der Raspberry nicht mehr erreichbar

### ISSUE THREAD

**Issue by Tylli** [alexreinert/piVCCU#483]
Moin, moin,
nachdem ich heute ein ganz normales Update (update && upgrade) meines Pis gemacht habe, (war aber größer, die Kernelmodule wurden neu kompiliert) konnte ich den Raspi nach einem Neustart nicht mehr erreichen. Er war zwar noch per PING erreichbar, aber alle Konfigurations-Webseiten (Homematic, PiHole) und auch PIVCCU waren nicht mehr funktionsfähig. 

Nach 2 Stunden Troubleshooting mit Bootloader neu installieren habe ich mich entschlossen das Betriebsystem neu aufzusetzen. Alles hat wieder funktioniert und ich bin dem Tutorial zur manuellen Installation von PIVCCU auf dem Raspberry gefolgt.

Nachdem ich die Bridge-utils installiert, die Bridge Konfiguration nach Anleitung eingetragen und neu gestartet habe, wollte ich PIVCCU installieren. Dies schlug aber leider fehl, weil der Pi keine Hostnamen mehr auflösen konnte. Der Grund, warum ich jetzt noch per SSH drauf zugreifen konnte war eventuell, dass ich vorher "Wait for network on boot" aktiviert hatte. Dies hatte ich jetzt nicht gemacht.

Jedenfalls weiß ich leider nicht mehr weiter, wie ich das Ganze wieder zum Laufen bekomme. 

Es würde mich freuen, wenn Sie mir einen Tipp geben könnten, was hier schief gelaufen ist.

Herzlichen Dank und beste Grüße,
Alexander Tylkowski

**Comment by 47441** [comment]
Hallo Zusammen,

das Problem kenne ich. Ich habe auch von ein paar Tagen ein
`sudo apt-get update && sudo apt-get upgrade`
an meinem RasPi4 durchgeführt.

Ein paar Tage später ist mir aufgefallen, dass ich meine Homematic-Geräte nicht mehr nutzen/schalten kann. Da ist mir aufgefallen, dass auch die Adapter im ioBroker Fehler melden und ich die WebUI nicht aufrufen kann.

Gibt es schon Ideen, wie ich das Ganze wieder in Griff bekommen kann?

Vielen Dank
Martin

**Comment by alexreinert** [comment]
@47441 Deine Problembeschreibung ist eine komplett andere, mach ein neues Ticket auf, bzw. schau erstmal #484 an.

**Comment by tschombe** [comment]
Hallo,
ich habe auch ein ähnlich / gleich geartetes Problem:

Ich habe meinen Raspi komplett neu aufgesetzt mit dem Buster SD Kartenimage.
(leider habe ich die manuelle Anleitung mit Kernel Header und Netzwerk bridge irgendwie nicht hinbekommen).

Anschließend habe ich versucht, den Raspi auf Bullseye hochzuziehen nach dieser Anleitung:
https://forum.iobroker.net/topic/47213/upgrade-von-debian-10-buster-auf-11-bullseye

Nach dem Reboot ist auch der Raspi und viccu nicht mehr erreichbar, 

Es muss irgendwie mit den Einträgen in 
/etc/systemd/system/dhcpcd.service.d/wait.conf  
/etc/network/interfaces.d
/etc/network/interfaces
zu tun haben, aber da verlässt mich mein netzwerk / linux know how um das auf einen nenner zu bringen.

Ein Versuch, /etc/systemd/system/dhcpcd.service.d/wait.conf  zu löschen hat auch nicht weiter geholfen.
Ein Aufruf von "sudo dhclient" verpasst dann immerhin dem raspi eine IP, aber pivccu bekommt anscheinend keine:

`pi@homematicpi:~ $ sudo pivccu-info
piVCCU version: 3.69.7-80
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  Emulated
HMIP Hardware:  Emulated
State:          RUNNING
PID:            874
Link:           vethpivccu
 TX bytes:      18.45 KiB
 RX bytes:      6.61 KiB
 Total bytes:   25.06 KiB
pi@homematicpi:~ $`
