### ISSUE TITLE
3.67.10-78 Nach Update / Upgrade Kernel modules und Raw UART dev not available

### ISSUE THREAD

**Issue by Strathmann** [alexreinert/piVCCU#484]
Guten Abend in die Runde. 
kurz zu mir: 
Philip S. gelernter Elektroinstallateur / Techniker und an sich nicht unbeholfen bei Software Problemen. Gestartet mit CCU2 und dann rauf zum PI mit vccu.

Nach 4 Jahren ohne große Störungen wollte ich heute meinem Raspi einmal updates verpassen und habe es geschafft das pivccu nicht mehr startet.
--------------------------------
Die Infos aus https://github.com/alexreinert/piVCCU/issues/5 
haben mir leider auch nicht weiter geholfen...
Please downgrade to the latest provides official kernel deb using
sudo apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel
and ensure, that all necessary package are installed using
sudo apt install lxc bridge-utils systemd
After that steps you need reboot.
It could be possible that you have to reinstall the module package after that reboot using
sudo apt-get install --reinstall pivccu-modules-raspberrypi
and reboot again.

kann mir eventuell jemand einen Tip geben wie ich das system wieder zum laufen bekomme? Vielen dank für jede info!!!!

----------------------------------------------

nach etwas suchen und viel lesen habe ich folgende Infos schon gesammelt:

`pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 3.67.10-78
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
State:          STOPPED
pi@raspberrypi:~ $ uname -r
6.1.19-v8+
pi@raspberrypi:~ $ systemctl start pivccu.service
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Legitimierung ist zum Starten von »pivccu.service« notwendig.
==== AUTHENTICATION COMPLETE ===
Job for pivccu.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status pivccu.service" and "journalctl -xe" for details.
pi@raspberrypi:~ $ systemctl status pivccu.service
● pivccu.service - piVCCU
     Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: enabled)
     Active: failed (Result: protocol) since Sat 2023-03-18 00:41:37 CET; 14s ago
    Process: 3916 ExecStart=/var/lib/piVCCU3/start_container.sh (code=exited, status=0/SUCCESS)
        CPU: 30ms

Mär 18 00:41:37 raspberrypi systemd[1]: Starting piVCCU...
Mär 18 00:41:37 raspberrypi start_container.sh[3919]: modprobe: FATAL: Module eq3_char_loop not found in directory /lib/modules/6.1.19-v8+
Mär 18 00:41:37 raspberrypi systemd[1]: pivccu.service: Can't open PID file /run/pivccu3.pid (yet?) after start: Operation not permitted
Mär 18 00:41:37 raspberrypi systemd[1]: pivccu.service: Failed with result 'protocol'.
Mär 18 00:41:37 raspberrypi systemd[1]: Failed to start piVCCU.
pi@raspberrypi:~ $ journalctl -xe
░░ The job identifier is 1184.

Wieso ist keine Instanz vorhanden? 

Mär 18 00:41:36 raspberrypi ensure_modules.sh[3798]: Error! There is no instance of pivccu 1.0.80
Mär 18 00:41:36 raspberrypi ensure_modules.sh[3798]: for kernel 6.1.19-v8+ (aarch64) located in the DKMS tree.
Mär 18 00:41:37 raspberrypi ensure_modules.sh[3913]: Error! echo

Wie bekomme ich das wieder hin das der kernel header gefunden wird?

Mär 18 00:41:37 raspberrypi ensure_modules.sh[3913]: Your kernel headers for kernel 6.1.19-v8+ cannot be found at
Mär 18 00:41:37 raspberrypi ensure_modules.sh[3913]: /lib/modules/6.1.19-v8+/build or /lib/modules/6.1.19-v8+/source.
Mär 18 00:41:37 raspberrypi ensure_modules.sh[3913]: You can use the --kernelsourcedir option to tell DKMS where it's located.
Mär 18 00:41:37 raspberrypi systemd[1]: pivccu-dkms.service: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit pivccu-dkms.service has successfully entered the 'dead' state.
Mär 18 00:41:37 raspberrypi systemd[1]: Finished piVCCU DKMS Modules.
░░ Subject: A start job for unit pivccu-dkms.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit pivccu-dkms.service has finished successfully.
░░
░░ The job identifier is 1184.
Mär 18 00:41:37 raspberrypi systemd[1]: pivccu-dkms.service: Consumed 1.043s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit pivccu-dkms.service completed and consumed the indicated resources.
Mär 18 00:41:37 raspberrypi systemd[1]: Starting piVCCU...
░░ Subject: A start job for unit pivccu.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit pivccu.service has begun execution.
░░
░░ The job identifier is 1183.
Mär 18 00:41:37 raspberrypi start_container.sh[3919]: modprobe: FATAL: Module eq3_char_loop not found in directory /lib/modules/6.1.19-v8+
Mär 18 00:41:37 raspberrypi piVCCU3[3920]: Could not load required kernel module eq3_char_loop.
Mär 18 00:41:37 raspberrypi start_container.sh[3920]: <11>Mar 18 00:41:37 piVCCU3: Could not load required kernel module eq3_char_loop.
Mär 18 00:41:37 raspberrypi systemd[1]: pivccu.service: Can't open PID file /run/pivccu3.pid (yet?) after start: Operation not permitted
Mär 18 00:41:37 raspberrypi systemd[1]: pivccu.service: Failed with result 'protocol'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit pivccu.service has entered the 'failed' state with result 'protocol'.
Mär 18 00:41:37 raspberrypi systemd[1]: Failed to start piVCCU.
░░ Subject: A start job for unit pivccu.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit pivccu.service has finished with a failure.
░░
░░ The job identifier is 1183 and the job result is failed.
Mär 18 00:41:37 raspberrypi systemd[1]: Condition check resulted in Monitor HB-RF-ETH being skipped.
░░ Subject: A start job for unit monitor-hb-rf-eth.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit monitor-hb-rf-eth.service has finished successfully.
░░
░░ The job identifier is 1253.
Mär 18 00:41:37 raspberrypi polkitd(authority=local)[544]: Unregistered Authentication Agent for unix-process:3756:135646 (system bus name :1.43, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale de_DE.UTF-8) (disconne>
lines 3155-3216/3216 (END)
`

**Comment by Strathmann** [comment]
Erstes kleines Update: 
via FTP habe ich auf dem PI geschaut was in dem 

ordner /lib/modules/6.1.19-v8+/build 

überhaupt drin ist. dieser Ordner ist aber gar nicht vorhanden!

**Comment by ju2kr** [comment]
Leider exakt dasselbe bei mir....

**Comment by alexreinert** [comment]
Bitte in der /boot/config.txt den 64 Bit Kernel deaktivieren und rebooten.

**Comment by Strathmann** [comment]
Guten Abend Herr Reinert. Vielen dank für die schnelle Rückmeldung. Die Info ist Gold Wert. System läuft wieder!!!

**Comment by Tylli** [comment]
Guten Abend, nach einem apt-get upgrade bin ich ebenfalls mit dem 64bit kernel "geschädigt". Ich habe wie hier beschrieben arm_64bit=0 in die config.txt geschrieben, nach sudo reboot kann der Pi aber nicht mehr hochfahren. Nachdem ich den Kommentar entfernt habe startet der Pi zwar wieder aber PIVCCU funktioniert natürlich nicht mehr. Habt Ihr vielleicht einen Tipp, warum der Pi nicht mehr bootet?

**Comment by alexreinert** [comment]
Hast du vielleicht das reine 64 Bit Image? Ansonsten mal Bildschirm anschließen, da kommt sicherlich eine Fehlermeldung.

**Comment by Tylli** [comment]
Guten Abend Herr Reinert, vielen Dank für die Antwort. Ich habe das 32bit lite OS installiert. Ich habe derzeit leider keinen Micro-HDMI Adapter hier aber ich werde mir morgen einen organisieren. Ich habe gelesen, dass ich die reine 64bit Version jetzt auch nutzen kann? Da ich ein aktuelles Backup habe wäre es vielleicht schneller, einfach eine Neuinstallation auf 64bit zu machen, grade auch was die Zukunft angeht?

**Comment by Homezecke** [comment]
Hallo, muss hier noch einmal nachhaken:

Also bei mir genauso. Raspi geupdatet, danach kein pivccu mehr. Das Ändern der config lässt auch mein System nicht starten. Es kann aber auch gar nicht daran liegen. Ich habe mir ein zweites identisches image (ohne Raspi update) angelegt da ist 64 Bit berits aktiv, und piVCCU funktioniert da trotzdem. Allerdings muss ich dazu noch erwähnen, dass ich noch ccu2 benutze.

Welche pakete sollte ich durch hold vom update ausschließen, damit pivccu auf altem Stand bleibt?
