### ISSUE TITLE
PIVCCU funktioniert nach Upgrade nicht mehr

### ISSUE THREAD

**Issue by IchBinSmart** [alexreinert/piVCCU#485]
Hallo,

leider funktioniert homematic nach einem Upgrade nicht mehr. Die Box gibt kein LED Signal von sich und pivccu-info gibt das folgende aus:
`
sudo pivccu-info
piVCCU version: 3.67.10-78
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
State:          STOPPED
`

Ich habe bereits das folgende versucht: 
`dpkg-reconfigure pivccu3` + reboot und 20min warten ;-)
`reinstall pivccu-modules-dkms` + reboot und 20min warten ;-)

`sudo systemctl start pivccu` liefert nach `journalctl -xe` folgendes:

> raspberrypi start_container.sh[3932]: modprobe: FATAL: Module eq3_char_loop not found in directory /lib/modules/6.1.19-v8+
> raspberrypi piVCCU3[3933]: Could not load required kernel module eq3_char_loop.
> raspberrypi start_container.sh[3933]: <11>Mar 20 18:44:17 piVCCU3: Could not load required kernel module eq3_char_loop.
> raspberrypi systemd[1]: pivccu.service: Can't open PID file /run/pivccu3.pid (yet?) after start: Operation not permitted

Also habe ich versucht wie in diesem Post beschrieben:
[Issue 5](https://github.com/alexreinert/piVCCU/issues/5) 

Leider ist der Fehler danach immer noch der Gleiche. 

Übrigens: Wenn ich eine (etwas ältere) Sicherung anstecke, geht die Box wieder wie gewohnt. Danke vorab für den Support!

Beste Grüße,
 Rainer

**Comment by alexreinert** [comment]
Hilft die Lösung aus #484?

**Comment by IchBinSmart** [comment]
Vielen Dank für die sehr schnelle Reaktion. "WAHNSINN" ;-). 

Tatsächlich ist das Problem damit gelöst - manchmal kann es so einfach sein.

Tausend Dank,
 Rainer
