### ISSUE TITLE
Could not load required kernel module eq3_char_loop.: After today's update, pivccu3 is no more reachable

### ISSUE THREAD

**Issue by 00Ralf** [alexreinert/piVCCU#486]
Today I did a "sudo apt update && sudo apt dist-upgrade" on my RasPi4. After doing this and a reboot, the piVCCU was not reachable, neither by web-Ui nor by ping.

The base installation consists of an iobroker (IP 172.29.19.40) and a piVCCU (IP 172.29.19.41) installed according to https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md

Some status info is in the attachment.

Thank you very much for your help.
Best regards,
Ralf
[pivccu-status.txt](https://github.com/alexreinert/piVCCU/files/11054449/pivccu-status.txt)

**Comment by alexreinert** [comment]
See #484

**Comment by 00Ralf** [comment]
Thank you!
