### ISSUE TITLE
piVCCU3 nach update nicht mehr erreichbar

### ISSUE THREAD

**Issue by 47441** [alexreinert/piVCCU#488]
Hallo Alex,
Hallo Zusammen,

Nach Hinweis von ALex hier ein neues Thema:
Ich habe auch von ein paar Tagen ein
`sudo apt-get update && sudo apt-get upgrade`
an meinem RasPi4 durchgeführt.

Ein paar Tage später ist mir aufgefallen, dass ich meine Homematic-Geräte nicht mehr nutzen/schalten kann. Da ist mir aufgefallen, dass auch die Adapter im ioBroker Fehler melden und ich die WebUI nicht aufrufen kann.

Den Hinweis aus [https://github.com/alexreinert/piVCCU/issues/484](url) habe ich entweder falsch gemacht, oder es hat nicht geholfen:

> Einfach in der /boot/config.txt folgende Zeile hinzufügen dann läuft es wieder:
`arm_64bit=0`

Gibt es schon Ideen, wie ich das Ganze wieder in Griff bekommen kann?

Vielen Dank
Martin

PS:
 pi@ioBroker:~ $ sudo pivccu-info piVCCU version: 3.67.10-78 Kernel modules: Not available Raw UART dev:   Not available Rasp.Pi UART:   Assigned to GPIO pins HMRF Hardware:  unknown HMIP Hardware:  unknown State:          STOPPED

**Comment by alexreinert** [comment]
Was liefern `uname -a` und `sudo dpkg-reconfigure pivccu-modules-dkms`? Wie sieht die vollständige /boot/config.txt aus?

**Comment by 47441** [comment]
Hallo Alex,

> uname -a 
`Linux ioBroker 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`

>sudo dpkg-reconfigure pivccu-modules-dkms
`Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.

------------------------------
Deleting module version: 1.0.79
completely from the DKMS tree.
------------------------------
Done.
Error! The module/version combo: pivccu-1.0.79
is not located in the DKMS tree.

Creating symlink /var/lib/dkms/pivccu/1.0.79/source ->
                 /usr/src/pivccu-1.0.79

DKMS: add completed.
Error! echo
Your kernel headers for kernel 6.1.21-v8+ cannot be found at
/lib/modules/6.1.21-v8+/build or /lib/modules/6.1.21-v8+/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service                                                                                                                      → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service →                                                                                                                      /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service                                                                                                                      → /lib/systemd/system/pivccu-dkms.service.`

> vollständige /boot/config.txt 
`# For more options and information see
# http://rpf.io/configtxt
192.168.188.81
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
max_framebuffers=2

# Disable compensation for displays with overscan
disable_overscan=1

[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
otg_mode=1

[all]

[pi4]
# Run as fast as firmware / board allows
arm_boost=1

[all]

dtoverlay=pi3-disable-bt
dtoverlay=pi3-disable-bt

dtoverlay=pivccu-raspberrypi

[64bit Kernel deaktivieren]
arm_64bit=0`

**Comment by alexreinert** [comment]
Steht das "[64bit Kernel deaktivieren]" inkl. der eckigen Klammern so in der config.txt? Dann wird das als konditionaler Block betrachtet und nicht ausgewertet.

**Comment by 47441** [comment]
ups. Das war es. 
Ich kommentiere gerne meine Änderungen, aber nicht bedacht, dass es das # hätte sein müssen... ;(
Entschuldigung für den Aufwand und Danke für die schnelle Hilfe. 

Martin
