### ISSUE TITLE
Nach update kein Zugriff auf WebUi und CCU

### ISSUE THREAD

**Issue by Nasenloch** [alexreinert/piVCCU#491]
Nach Durchführung des aktuellen Updates (sudo apt-get update; sudo apt-get upgrade) erreiche ich die CCU nicht mehr. Auch eine Neuinstallation von pivccu hat nichts gebracht.

sudo pivccu-info bringt diese Info hervor:

,piVCCU version: 3.69.7-80
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
State:          STOPPED

Danke!

**Comment by alexreinert** [comment]
Wurde der während des Updates geforderte Reboot gemacht?

**Comment by Nasenloch** [comment]
Problem gelöst!

journalctl -xe
░░ An ExecStart= process belonging to unit pivccu-dkms.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
May 10 11:10:29 raspberrypi systemd[1]: pivccu-dkms.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit pivccu-dkms.service has entered the 'failed' state with result 'exit-code'.
May 10 11:10:29 raspberrypi systemd[1]: Failed to start piVCCU DKMS Modules.
░░ Subject: A start job for unit pivccu-dkms.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit pivccu-dkms.service has finished with a failure.
░░ 
░░ The job identifier is 516 and the job result is failed.
May 10 11:10:29 raspberrypi systemd[1]: Dependency failed for piVCCU.
░░ Subject: A start job for unit pivccu.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit pivccu.service has finished with a failure.
░░ 
░░ The job identifier is 515 and the job result is dependency.
May 10 11:10:29 raspberrypi systemd[1]: pivccu.service: Job pivccu.service/start failed with result >
May 10 11:10:29 raspberrypi systemd[1]: Condition check resulted in Monitor HB-RF-ETH being skipped.
░░ Subject: A start job for unit monitor-hb-rf-eth.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support


sudo apt install --reinstall raspberrypi-bootloader raspberrypi-kernel raspberrypi-kernel-headers


Neustart und er rennt wieder...

Trotzdem vielen Dank!
