### ISSUE TITLE
piVCCU partially lost connection to HMIP devices

### ISSUE THREAD

**Issue by flipreverse** [alexreinert/piVCCU#494]
Hi folks!

Since my upgrade to Debian 12, my piVCCU cannot reach any HMIP device ~~the three heating valves anymore~~.
The HMIP window sensors are, however, available. Does anyone have an idea where to look first?
Is this even the right place to address this issue?

Regards,
Alex

Here's my current setup as stated by `pivccu-info`
```
piVCCU version: 3.69.7-83
OS:             Raspbian GNU/Linux 12 (bookworm)
Kernel:         6.1.21-v8+ aarch64
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.1 (/dev/raw-uart)
 Board serial:  XXXXX
 Radio MAC:     XXXXX
HMIP Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.1 (/dev/raw-uart)
 SGTIN:         XXXXX
 Radio MAC:     XXXXX
State:          RUNNING
PID:            1625
IP:             192.168.111.205
CPU use:        5912.42 seconds
BlkIO use:      0 bytes
Link:           vethpivccu
 TX bytes:      550.92 MiB
 RX bytes:      315.08 MiB
 Total bytes:   866.00 MiB
```
Raspberry Pi 4 with 4 GB of RAM, Debian 12 armv7 userland and aarch64 kernel

**Comment by alexreinert** [comment]
Is the HmIP-RFUSB directly attached to the Pi, or do you have a distance of at least 1m between Pi and stick?
The Pi 4 produces a lot of radio interference on 868MHz which causes such issues, the only way to solve this is getting a distance of at least 1m.

**Comment by flipreverse** [comment]
I did that. But it didn't really work. However, I restarted piVCCU. Everthing is online again.
:-/
