### ISSUE TITLE
HmIP-RFUSB not detected / working

### ISSUE THREAD

**Issue by GerryHarrison** [alexreinert/piVCCU#495]
Just installed piVCCU (following the official steps of the manual installation from [HERE](https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md)).  on a fresh Raspberry Pi OS Bullseye installation (also fresh) on a Raspi 4 8GB. 

Now I can't get my HmIP-RFUSB working. The dongle is installed via a small USB extension cord. Also tried USB3 port as well as USB2 port. On the previous installation on the same Raspi, same setup, it worked. 

When I enter sudo dpkg-reconfigure pivccu3 I get:
Stop piVCCU ... Done
Disable services ... Done
Remove symlinks ... Done
Reload udev rules ... Done
Create symlinks ... Done
Enable services ... Done
Update APT repository config ... FAILED
sed: can't read /etc/apt/sources.list.d/nodesource.list
/etc/apt/sources.list.d/pivccu.list
/etc/apt/sources.list.d/raspi.list: No such file or directory
Error updating repo https://www.debmatic.de/debmatic in /etc/apt/sources.list.d/nodesource.list
/etc/apt/sources.list.d/pivccu.list
/etc/apt/sources.list.d/raspi.list

First question: is this then more a access right issue = software? I suppose so, but don't know what to do here. 

piVCCU-info reports: 

piVCCU version: 3.69.7-83
OS:             Debian GNU/Linux 11 (bullseye)
Kernel:         6.1.21-v8+ aarch64
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  Emulated
HMIP Hardware:  HMIP-RFUSB-TK
 Connected via: eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.4 (/dev/raw-uart)
 SGTIN:         3014F5AC94000416FB533D28
 Radio MAC:     0xB0E623
State:          RUNNING
PID:            1250
IP:             192.168.178.68
Link:           vethpivccu
 TX bytes:      17.77 KiB
 RX bytes:      73.61 KiB
 Total bytes:   91.38 KiB

Thank you in advance for any hints & tips!

**Comment by alexreinert** [comment]
According to your output of pivccu-info the stick is detected. Please describe your issues with the stick.
If just Homematic classic/BidCos is not working: The Telekom version of the stick does only support HmIP (as stated in the Readme).

**Comment by alexreinert** [comment]
And if it is not working with HmIP as well: The Pi 4 creates a lot of radio interference which affects HmIP. Only solution for that is a distance of at least 1m between the Pi and the stick.

**Comment by GerryHarrison** [comment]
Thank you for the quick reply. I totally mixed up HmIP and HmRF and that it said "emulated" - thought it was the USB device and even didn't test it (supposed it wouldn't work). Your replies made it clear to me. It works, all good.
