### ISSUE TITLE
installation fails with the following error: Could not load kernel modules plat_eq3ccu2 and eq3_char_loop.

### ISSUE THREAD

**Issue by EsOmEs** [alexreinert/piVCCU#5]
After I followed the procedure to install piVCCU on my RaspberryPi 3 i get the following error when the service tries to start:

Could not load kernel modules plat_eq3ccu2 and eq3_char_loop.

the corresponding modprobe in the start script gives: 

modprobe: WARNING: Module plat_eq3ccu2 not found in directory /lib/modules/4.9.67-v7+
modprobe: WARNING: Module eq3_char_loop not found in directory /lib/modules/4.9.67-v7+

What did I do wrong?

I have the HM-MOD-RPI-PCB board (it works, tested it as a device in FHEM on the same RPi)

Kind regards,
EsO

**Comment by alexreinert** [comment]
Can you please Provider the output of "sudo pivccu-info"?

**Comment by EsOmEs** [comment]
The output is as follows:

piVCCU version: 2.29.23-16
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi3 UART:  Assigned to GPIO pins
Board serial:   Unknown
lxc doesn't exist

**Comment by alexreinert** [comment]
Can you please describe how you installed piVCCU?
The pivccu deb file has a dependency to lxc which Sees to be not install es on your system and the module deb has a dependency to the kernel package with Version 4.9.59 and you have 4.9.67 on your system.

**Comment by EsOmEs** [comment]
I followed the procedure on

https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md

which means that I used the apt way of installing it. The edits in steps 3 and 4 were in place already from my Hardware test and FW update of the GPIO board (to 1.4.1)

I noted that i was unable to uninstall the dhcpcd5 package as it was not installed (Iguess Stretch uses a different one) but I guess that this is not the issue.

before i installed this I had run an sudo rpi-update which bumps me to the latest kernel release.

**Comment by alexreinert** [comment]
Please downgrade to the latest provides official kernel deb using
`sudo apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel`
and ensure, that all necessary package are installed using
`sudo apt install lxc bridge-utils systemd`
After that steps you need reboot.
It could be possible that you have to reinstall the module package after that reboot using
`sudo apt-get install --reinstall pivccu-modules-raspberrypi`
and reboot again.

**Comment by EsOmEs** [comment]
Looks better now:

pi@zberry:~ $ sudo pivccu-info
piVCCU version: 2.29.23-16
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
Board serial:   OEQ0607687
State:          RUNNING
PID:            662
IP:             192.168.74.36
IP:             2003:e5:abde:7500:688b:32ff:fe9d:a989
CPU use:        5.72 seconds
BlkIO use:      7.52 MiB
Link:           vethpivccu
 TX bytes:      5.89 KiB
 RX bytes:      41.91 KiB
 Total bytes:   47.81 KiB

I assume that this means that I should refrain from using rpi-update, correct?

I also now have two interfaces. eth0 with a static dhcp adress and the bridge br0 with a static ip. does this hurt?

Thank you for your quick reply!
I will start toying around with the new CCU tomorrow ;-)

**Comment by alexreinert** [comment]
Yes, you should update your kernel only using the apt way. I will provide updates module package for New kernel debs.
Regarding the interfaces: Normally you should just have an address on br0. Can you please post your /etc/network/interfaces and the output of ifconfig?
