### ISSUE TITLE
WEBUI - Connection refused

### ISSUE THREAD

**Issue by kedvsk** [alexreinert/piVCCU#50]
Die Web-Oberfläche der CCU ist nicht (mehr) erreichbar:

> Diese Website ist nicht erreichbar
> 192.168.178.224 hat die Verbindung abgelehnt.
> Versuchen Sie Folgendes:
> 
> Verbindung prüfen
> Proxy und Firewall prüfen
> ERR_CONNECTION_REFUSED
> Bitte überprüfen Sie Ihre Internetverbindung.
> Überprüfen Sie alle Kabel und starten Sie alle verwendeten Router, Modems und anderen Netzwerkgeräte neu.
> Erlauben Sie Chrome in Ihren Firewall- und Virenschutzeinstellungen den Zugriff auf das Netzwerk.
> Falls das Programm schon in der Liste mit erlaubtem Netzwerkzugriff eingetragen ist, entfernen Sie es aus der Liste und fügen Sie es noch einmal hinzu.
> Falls Sie einen Proxyserver verwenden…
> Vergewissern Sie sich, dass der Proxyserver funktioniert. Überprüfen Sie die Proxyeinstellungen oder wenden Sie sich an Ihren Netzwerkadministrator. Falls Sie keinen Proxyserver verwenden möchten, deaktivieren Sie ihn wie folgt: Gehen Sie zum Chrome-Menü > "Einstellungen" > "Erweiterte Einstellungen anzeigen" > "Proxy-Einstellungen ändern…" > "LAN-Einstellungen" und deaktivieren Sie die Option "Proxyserver für LAN verwenden".
> 

- Neue manuelle Installation auf PI 3
- manuelle IP-Adresse gesetzt (ist über ein Ping erreichbar)
- Nach Installation hat soweit alles funktioniert
- Es wurde nichts nachinstalliert - lediglich Geräte angelernt
- Das Problem trat nach einem Reboot auf 

systemctl status pivccu.service

> * pivccu.service - piVCCU
>    Loaded: loaded (/lib/systemd/system/pivccu.service; enabled; vendor preset: enabled)
>    Active: active (running) since Wed 2018-05-16 23:20:33 CEST; 12min ago
>   Process: 504 ExecStart=/var/lib/piVCCU/start_container.sh (code=exited, status=0/SUCCESS)
>  Main PID: 588 (lxc-start)
>       CPU: 530ms
>    CGroup: /system.slice/pivccu.service
>            `-588 /usr/bin/lxc-start --lxcpath /var/lib/piVCCU --name lxc --pidfile /var/run/pivccu.pid --daemon
> 
> Mai 16 23:18:59 SMITH21 systemd[1]: Starting piVCCU...
> Mai 16 23:20:32 SMITH21 start_container.sh[504]: kernel.sched_rt_runtime_us = -1
> Mai 16 23:20:33 SMITH21 systemd[1]: Started piVCCU.
> 

pivccu-info

> piVCCU version: 2.31.25-26
> Kernel modules: Available
> Raw UART dev:   Available
> Rasp.Pi3 UART:  Assigned to GPIO pins
> Board serial:   OEQ0608496
> State:          RUNNING
> PID:            599
> IP:             192.168.178.224
> CPU use:        22.33 seconds
> BlkIO use:      42.28 MiB
> Link:           vethpivccu
>  TX bytes:      31.82 KiB
>  RX bytes:      325.56 KiB
>  Total bytes:   357.38 KiB
> 

pivccu-attach cat /var/log/messages

> May 16 23:20:33 homematic-ccu2 syslog.info syslogd started: BusyBox v1.20.2
> May 16 23:20:33 homematic-ccu2 user.notice kernel: klogd started: BusyBox v1.20.2 (2018-01-15 15:55:20 CET)
> May 16 21:20:39 homematic-ccu2 daemon.info ifplugd(eth0)[140]: ifplugd 0.28 initializing.
> May 16 21:20:39 homematic-ccu2 daemon.info ifplugd(eth0)[140]: Using interface eth0/0A:77:9F:AA:93:62 with driver <veth> (version: 1.0)
> May 16 21:20:39 homematic-ccu2 daemon.info ifplugd(eth0)[140]: Using detection mode: SIOCETHTOOL
> May 16 21:20:39 homematic-ccu2 daemon.info ifplugd(eth0)[140]: Initialization complete, link beat detected.
> May 16 21:20:39 homematic-ccu2 daemon.warn ifplugd(eth0)[140]: Could not open /dev/tty, cannot beep.
> May 16 21:20:39 homematic-ccu2 daemon.info ifplugd(eth0)[140]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
> May 16 21:20:39 homematic-ccu2 daemon.warn ifplugd(eth0)[140]: client: net.ipv4.tcp_timestamps = 0
> May 16 21:20:39 homematic-ccu2 daemon.warn ifplugd(eth0)[140]: client: udhcpc (v1.20.2) started
> May 16 23:20:39 homematic-ccu2 user.debug setclock: Try to get time from ntp.homematic.com
> May 16 23:20:39 homematic-ccu2 user.debug setclock: Wed May 16 23:20:39 CEST 2018
> May 16 21:20:39 homematic-ccu2 daemon.warn ifplugd(eth0)[140]: client: Sending discover...
> May 16 21:20:39 homematic-ccu2 daemon.warn ifplugd(eth0)[140]: client: Sending select for 192.168.178.224...
> May 16 21:20:39 homematic-ccu2 daemon.warn ifplugd(eth0)[140]: client: Lease of 192.168.178.224 obtained, lease time 864000
> May 16 21:20:41 homematic-ccu2 daemon.warn ifplugd(eth0)[140]: client: rm: can't remove '/var/etc/resolv.conf': No such file or directory
> May 16 21:20:41 homematic-ccu2 daemon.warn ifplugd(eth0)[140]: client: udhcpc (v1.20.2) started
> May 16 21:20:42 homematic-ccu2 daemon.warn ifplugd(eth0)[140]: client: Sending discover...
> May 16 21:20:42 homematic-ccu2 daemon.warn ifplugd(eth0)[140]: client: Sending select for 192.168.178.224...
> May 16 21:20:42 homematic-ccu2 daemon.warn ifplugd(eth0)[140]: client: Lease of 192.168.178.224 obtained, lease time 864000
> May 16 21:20:43 homematic-ccu2 daemon.info ifplugd(eth0)[140]: Program executed successfully.
> May 16 21:20:44 homematic-ccu2 user.info logger: Updating RF Lan Gateway Coprocessor Firmware
> May 16 21:20:44 homematic-ccu2 user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
> May 16 21:20:44 homematic-ccu2 user.info logger: Updating RF Lan Gateway Firmware
> May 16 21:20:44 homematic-ccu2 user.info update-lgw-firmware: No gateway found in config file /etc/config/rfd.conf
> May 16 21:20:44 homematic-ccu2 user.info logger: Updating Wired Lan Gateway Firmware
> May 16 21:20:44 homematic-ccu2 user.info update-lgw-firmware: No gateway found in config file /etc/config/hs485d.conf
> May 16 23:20:48 homematic-ccu2 user.info update-coprocessor: Version: 2.8.6
> May 16 23:20:48 homematic-ccu2 user.info update-coprocessor: No update necessary
> May 16 23:21:34 homematic-ccu2 user.info kernel: [  114.187257] eq3loop: eq3loop_open_slave() ttyS0
> May 16 23:21:34 homematic-ccu2 user.info kernel: [  114.191127] eq3loop: eq3loop_open_slave() ttyS0
> May 16 23:21:34 homematic-ccu2 user.info kernel: [  114.201792] eq3loop: eq3loop_open_slave() ttyS0
> May 16 23:21:34 homematic-ccu2 user.notice kernel: [  114.204013] eq3loop: eq3loop_ioctl_slave() ttyS0: unhandled ioctl 0x545D
> May 16 23:21:39 homematic-ccu2 user.debug setclock: Try to get time from ntp.homematic.com
> May 16 23:21:39 homematic-ccu2 user.debug setclock: Wed May 16 23:21:39 CEST 2018
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute result isFault; method =getValue Params = {"000A58A98A0649:0","DUTY_CYCLE"} result= [faultCode:-5,faultString:"Unknown Parameter value for value key: DUTY_CYCLE"] [iseXmlRpc.cpp:260
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallGetValue: CallXmlrpcMethod failed [iseXmlRpc.cpp:1432]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseHssDP::ReadValue: CallGetValue failed; sVal = 0 [iseDOMdpHSS.cpp:130]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute result isFault; method =getValue Params = {"000A58A98A0649:0","LOW_BAT"} result= [faultCode:-5,faultString:"Unknown Parameter value for value key: LOW_BAT"] [iseXmlRpc.cpp:2605]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallGetValue: CallXmlrpcMethod failed [iseXmlRpc.cpp:1432]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseHssDP::ReadValue: CallGetValue failed; sVal = 0 [iseDOMdpHSS.cpp:130]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute result isFault; method =getValue Params = {"000A58A98A0649:0","RSSI_DEVICE"} result= [faultCode:-5,faultString:"Unknown Parameter value for value key: RSSI_DEVICE"] [iseXmlRpc.cpp:2
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallGetValue: CallXmlrpcMethod failed [iseXmlRpc.cpp:1432]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseHssDP::ReadValue: CallGetValue failed; sVal = 0 [iseDOMdpHSS.cpp:130]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute result isFault; method =getValue Params = {"000A58A98A0649:0","RSSI_PEER"} result= [faultCode:-5,faultString:"Unknown Parameter value for value key: RSSI_PEER"] [iseXmlRpc.cpp:2605]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallGetValue: CallXmlrpcMethod failed [iseXmlRpc.cpp:1432]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseHssDP::ReadValue: CallGetValue failed; sVal = 0 [iseDOMdpHSS.cpp:130]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute result isFault; method =getValue Params = {"000A58A98A0649:0","TIME_OF_OPERATION"} result= [faultCode:-5,faultString:"Unknown Parameter value for value key: TIME_OF_OPERATION"] [ise
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallGetValue: CallXmlrpcMethod failed [iseXmlRpc.cpp:1432]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseHssDP::ReadValue: CallGetValue failed; sVal = 0 [iseDOMdpHSS.cpp:130]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute result isFault; method =getValue Params = {"000A58A98A0649:0","UNREACH"} result= [faultCode:-5,faultString:"Unknown Parameter value for value key: UNREACH"] [iseXmlRpc.cpp:2605]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallGetValue: CallXmlrpcMethod failed [iseXmlRpc.cpp:1432]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseHssDP::ReadValue: CallGetValue failed; sVal = 0 [iseDOMdpHSS.cpp:130]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute result isFault; method =getValue Params = {"000A58A98A0649:1","ERROR_CODE"} result= [faultCode:-5,faultString:"Unknown Parameter value for value key: ERROR_CODE"] [iseXmlRpc.cpp:260
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallGetValue: CallXmlrpcMethod failed [iseXmlRpc.cpp:1432]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseHssDP::ReadValue: CallGetValue failed; sVal = 0 [iseDOMdpHSS.cpp:130]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute result isFault; method =getValue Params = {"000A58A98A0649:1","SMOKE_DETECTOR_ALARM_STATUS"} result= [faultCode:-5,faultString:"Unknown Parameter value for value key: SMOKE_DETECTOR
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallGetValue: CallXmlrpcMethod failed [iseXmlRpc.cpp:1432]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseHssDP::ReadValue: CallGetValue failed; sVal = 0 [iseDOMdpHSS.cpp:130]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute result isFault; method =getValue Params = {"000A58A98A0649:1","SMOKE_DETECTOR_TEST_RESULT"} result= [faultCode:-5,faultString:"Unknown Parameter value for value key: SMOKE_DETECTOR_
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallGetValue: CallXmlrpcMethod failed [iseXmlRpc.cpp:1432]
> May 16 23:21:58 homematic-ccu2 local0.err ReGaHss: Error: IseHssDP::ReadValue: CallGetValue failed; sVal = 0 [iseDOMdpHSS.cpp:130]
> 

Wie komme ich hier weiter?

**Comment by alexreinert** [comment]
Es gibt einen Known Issue in der CCU Firmware, dass Sonderzeichen in Gerätenamen dazu führen, dass die WebUI nicht mehr erreichbar ist. Liegt es möglicherweise daran?

**Comment by kedvsk** [comment]
Über den Gerätenamen bin ich nicht weiter gekommen. Seit dem Zurücksetzen auf ein ein Tage altes Image läuft es wieder problemlos.
