### ISSUE TITLE
Web Interface startet nach Update nicht?

### ISSUE THREAD

**Issue by rplc** [alexreinert/piVCCU#502]
Hallo zusammen,
Ich habe soeben auf 3.71.12-85 geupdated.
ioBroker kann sich mit der VCCU (über hm-rpc) verbinden. Das Webinterface lädt allerdings nicht, Chrome bricht dann mit einem ERR_CONNECTION_TIMED_OUT ab.
Ich bin gerade recht ratlos und hoffe hier mal auf Rat, was ich probieren kann. Habe schon mehrfach neugestartet. IP passt. Browser Cache geleert (auch in Temp-Sitzung geöffnet).
Anbei mal die typischen Log Files, in der Hoffnung, dass jemand damit was anfangen kann und mich in die richtige Richtung deuten kann.

[hmserver.txt](https://github.com/alexreinert/piVCCU/files/12439816/hmserver.txt)
[hmMode.txt](https://github.com/alexreinert/piVCCU/files/12439817/hmMode.txt)
[var-log-messages.txt](https://github.com/alexreinert/piVCCU/files/12439818/var-log-messages.txt)
[pivccu-info.txt](https://github.com/alexreinert/piVCCU/files/12439819/pivccu-info.txt)

Ich habe vor kurzem der VCCU über das Webinterface in Network Settings eine fest IP zugewiesen. Potentiell kann natürlich sein, dass ich dabei etwas verkackt habe. Wobei ich eigentlich gedacht hätte, dass es mit der neuen Einstellung dort schon eine Zeit lang lief. Kann mir evtl. jemand sagen, wie ich über die CLI die Network Settings zurück drehen kann (um diese evtl. Ursache auszuschließen)?

Vielen Dank im Voraus.
Grüße Alex

**Comment by alexreinert** [comment]
Mit welcher Adresse greifst du per Browser auf das System zu?
Hast du einen möglicherweise einen Proxyserver im Browser eingetragen?
Schon mal von einem anderen Endgerät versucht zuzugreifen?

**Comment by rplc** [comment]
Ich versuche über die IP Adresse (die mir pivccu-info ausspuckt) drauf zu zugreifen (192.168.5.157). 
Von der Netzwerk Segmentierung her dürfen alle Endgeräte mit denen ich es bisher probiert habe auch dort hin telefonieren (zumal ich an der schön Recht lange nichts mehr geändert habe).
Proxy habe ich nicht in Verwendung/eingetragen. Habe es entsprechend auch mit anderen Endgeräten probiert, selbes Fehlerbild (Connection timed out).
Ich komme mit allen Endgeräten auf den iobroker, der auf der gleichen Kiste läuft, problemlos drauf.
Scheint also mMn kein generelles Netzwerk Problem zu sein sondern eines der pivccu zu sein.
Kann natürlich sein, dass ich in den Netzwerk Einstellungen im Admin Panel der vccu etwas verkackt habe oder halt das Update irgendeinen Unsinn getrieben hat.
Grüße Alex

**Comment by rplc** [comment]
War eine falsche IP Konfiguration.
