### ISSUE TITLE
HmIP-RFUSB nicht mehr erkannt nach update auf pivccu-modules-dkms 1.0.84

### ISSUE THREAD

**Issue by ordo01** [alexreinert/piVCCU#509]
Hallo,
die Version 1.0.84 von pivccu-modules-dkms funktioniert nicht bei meiner raspberrymatic in home-assistant. Der HmIP-RFUSB Stick wird nicht mehr erkannt. Ein Downgrad auf Version 1.0.82 hat das Problem gelöst.

Meine Umgebung:
Home-Asssitant 2023.10.4
RaspberryMatic 3.71.12.20231020
Debian 11.8
Kernel 5.10.0-26-arm64

**Comment by alexreinert** [comment]
Sorry ich kann leider keinen Support für RaspberryMatic leisten.
