### ISSUE TITLE
Question: migrate piVCCU to another machine

### ISSUE THREAD

**Issue by s0170071** [alexreinert/piVCCU#51]
I had a stetch installation of piVCCU fully up and running and want to migrate that to an openhabian installation without going through the whole re-configuration process. 
I did already install piVCCU on the destination system. I thought, maybe I can just copy some folders over to the new system... 
Can you point me to the folders in question ?

**Comment by alexreinert** [comment]
/etc/piVCCU if you did changes there and for the CCU itself just do a backup and restore using the web interface.

**Comment by s0170071** [comment]
no, that was not what I meant. I wanted to clone the whole container. 
I copied the old /var/lib/piVCCU folder over the existing folder of the fresh installation- that seemed to do the trick. 
I had to skip some "special files" though. Still seems to work but needs some testing.
One thing that does not work are the cuxd highcharts. I copied the log files from my old ccu into the same folder, root took ownership and still only those logs that were not copied are displayed...

**Comment by alexreinert** [comment]
You *should* not clone the whole container. The root filesystem of the CCU (/var/lib/piVCCU/rootfs) is installed by the deb package, as all other piVCCU scripts under the folder /var/lib/piVCCU. These files should be treated readonly and only to be changed by the package installer.

You can copy the folder /var/lib/piVCCU/userfs and /var/lib/piVCCU/sdcardfs. First one is the same as backup using the web interface, the second one is only for the ccu builtin diagrams.

**Comment by s0170071** [comment]
`You can copy the folder /var/lib/piVCCU/userfs and /var/lib/piVCCU/sdcardfs. `

That did the trick. All CCU settings, programs and addons are still there in the copy

`the second one is only for the ccu builtin diagrams.`

Still got the problem that cuxd highcharts only displays log files that were created after I moved to piVCCU. My old files (same DPs) which are in the same folder are ignored. This may not be a piVCCU issue but I am still thankful for any hints.

**Comment by alexreinert** [comment]
This is not a piVCCU issue.

If there is anything left or unclear, please reopen
