### ISSUE TITLE
pivccu-modules-dkms wird nicht gebaut

### ISSUE THREAD

**Issue by hennedo** [alexreinert/piVCCU#512]
Moin,
ich hab gestern seit längerer Zeit mein NAS (ubuntu jammy) updated und seitdem failed der pivccu-dkms service und mein HMIP-RFUSB geht nichtmehr. Ich hab dann versucht mittels ```dpkg-reconfigure pivccu-modules-dkms``` die Kernel Module neuzubauen aber das schlägt auch fehl.

```bash
henne@nas:~$ sudo dpkg-reconfigure pivccu-modules-dkms
Disabled DKMS service ... Done
Remove obsolete kernel modules ... Done
Create kernel modules ... FAILED
Check kernel headers ... Done
Prepare kernel headers ... Done
Install DKMS package ... Done
Try to load fresh build modules ... FAILED
modprobe: ERROR: could not insert 'generic_raw_uart': Exec format error
Enable DKMS service ... Done
henne@nas:~$ uname -a
Linux nas 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Mache ich was falsch, oder fehlt mir noch etwas?
Grüße
Henne

**Comment by hennedo** [comment]
Grade nochmal nachgeschaut, SecureBoot ist aus (ich las damit könnte es zu Problemen kommen)

**Comment by alexreinert** [comment]
Ubuntu installiert manchmal korrupte Header, das sollte das beheben:

```
sudo apt install --reinstall linux-headers-$(uname -r)
sudo apt-mark auto linux-headers-$(uname -r)
sudo dpkg-reconfigure pivccu-modules-dkms
```

**Comment by hennedo** [comment]
Yaay, das hat funktioniert, danke!
