### ISSUE TITLE
pivccu-modules-dkms kann nicht gefunden werden

### ISSUE THREAD

**Issue by susiartig** [alexreinert/piVCCU#513]
Hallo,
habe nun bei der Neuinstallation auf einem Pi3 mit bookworm das Problem, dass sich pivccu-modules-dkms nicht installieren lässt.
sudo apt update
sudo apt upgrade
zuvor ausgeführt.
`root@raspberrypi:~# sudo apt install raspberrypi-kernel-headers pivccu-modules-dkms
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
E: Paket pivccu-modules-dkms kann nicht gefunden werden.`
Grüße, susi

**Comment by alexreinert** [comment]
Was gibt apt update aus?

**Comment by susiartig** [comment]
root@raspberrypi:~# sudo apt update
OK:1 http://deb.debian.org/debian bookworm InRelease
OK:2 http://deb.debian.org/debian-security bookworm-security InRelease
Holen:3 http://deb.debian.org/debian bookworm-updates InRelease [52,1 kB]
OK:4 http://archive.raspberrypi.com/debian bookworm InRelease
Es wurden 52,1 kB in 2 s geholt (21,0 kB/s).
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Alle Pakete sind aktuell.

`

**Comment by susiartig** [comment]
root@raspberrypi:~# sudo apt install pivccu-modules-dkms
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
E: Paket pivccu-modules-dkms kann nicht gefunden werden.

**Comment by alexreinert** [comment]
Wurdendie Schritte 1 und 2 der Anleitung ausgeführt und wenn ja, kamen da Fehler?
Wie ist der Inhalt der Datei /etc/apt/sources.list.d/pivccu.list?

**Comment by susiartig** [comment]
Ja - es wurden beide Schritte ausgeführt. Habe die gerade nochmals wiederholt.
Inhalt der pivccu.list:

login as: root
root@192.168.0.26's password:
Linux raspberrypi 6.1.0-rpi6-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-                                                                                               10-27) aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Nov 22 15:55:05 2023 from 192.168.0.148

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set                                                                                                a new password.

root@raspberrypi:~# wget -q -O - https://apt.pivccu.de/piVCCU/public.key | sudo tee /usr/share/keyrings/pivccu.asc
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.14 (GNU/Linux)

mQENBFJsL6IBCADMlaNsEi/CXNdYeacssVfjj+//N0VNjRdV+BIRB7WUvEZX6dS5
FNiJpJAohYmQWNz16jCI2uMuPOLsTl10K0CIUmfVtCeHQCe0w13AJMRJSA3/JoPJ
ZBkZ05xY7Wqh3HTRy8hI7f6ZCtWjsmQvA9r3T6FUd6/5cBZxFCSI4llS6vDsREk6
G+05T78FNtfaxHfobYZI16qMzWevvNqjBn7rQZLn4TBNuvqnhshpoYZUnjCi1Yoz
UjcReKhGNIC6kfeoFIoHy3fFKAQwknZnN6mXflGP5IVEH6jm790LZIDwrdGU8avf
97JloGWQXtd35psHaMPm02zffz3QozlmMtZBABEBAAG0NkFsZXhhbmRlciBSZWlu
ZXJ0IChQYWNrYWdlIFNpZ25pbmcpIDxhbGV4QGFyZWluZXJ0LmRlPokBOAQTAQIA
IgUCUmwvogIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQVBIwugXDi8QT
FAf8DBGo1c00wWC2RwpFo414hGrEqlQTt8wWEwZJdPByO7i3ZNHvYpqjJr/8HR50
uyxg9Xomg2Gb03vD1xjdVPAZcTz2Jtfa6JiNmN1hC3Wxz0fUbwKcdEdhhXr8iRts
1EycRjjy4O3J2ty5kEjI5WCjnyGyqAxdIOPpocyzIIWBSBGHfy6fI9/35LNmZ2Tr
6XJJJfI7NXcrKzu48YEQxy4QdvpEI5ahwJmyFjVJjFM8HtFOVxliFOzMjzkvhiEo
SwO2SQvo0o2MdBsl3OlzvwNm0z6ffh8/3uGk0WmwaFoeCRs+plkG2zy/GOS7YrSY
DrpLTIThPQQV3A2rFFqRVYqZ8bkBDQRSbC+iAQgApIQ4HmDzQYwLgMrEgDVts/8S
fIdKHxeZ0MSltbNbgUwptfeW+LhtWBJ6niZkV+7U7kSGEbZBGWqsybEHdGcG3S4N
xlR9AoCEPRoiwbChy0nOOYCDySgfk35coP32+yzcAVvvCx/Tu8rdl4H+l00a23nl
x3aiRPlWkrrDJg5GqAkIfTX9j/MCGDYJ4j5TCWT4FbGuEF+fExgko5cUzG8y/2Hz
aHcEfC+Zt4P48Ir9MGwcImY45uHr8Z4UOaQ1WQBG8KAxKWmpqhik/8rLro91GnaA
L0Hip+vgkT7+Y7iPbVxIp+hr7wnHt7WCiccUXMIpCvo93GLR9jcReIzCx0/gOQAR
AQABiQEfBBgBAgAJBQJSbC+iAhsMAAoJEFQSMLoFw4vE0z8H/jQPJtfdh8s9AgWl
hhzCsm0b8LmhYW4bmOrbN5PCI1qTfnP68GCAOFHYqnGSbJvMYp07Yfcx90KRYP4E
yQxsVbnaiVj3d3teH8o7Nw8WaH+9XKsfg/vAyc7VRtr1UB0IvolGdeNeXjvJ3/PG
AfsSY8CGlA6ClBhZ8+q5cUVJLCvy+4emvXTiwJ4XZp96bmBHkit9QFbrqSoIo3Vr
gF0f4ZB/NFyL0VcZscH9yE4BXAqvs5uIGt8QQ03YrQJ2/JLzu/jUe0iEB3WWXxFm
JDDElWaDoRMaZTSxJgzuRi9/xhMlNRS45CI38FpiCS9AWgmyBBq9xKI6BMLunRWj
4CUtOWQ=
=jgj0
-----END PGP PUBLIC KEY BLOCK-----
root@raspberrypi:~# sudo apt install build-essential bison flex libssl-dev
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
build-essential ist schon die neueste Version (12.9).
bison ist schon die neueste Version (2:3.8.2+dfsg-1+b1).
flex ist schon die neueste Version (2.6.4-8.2).
libssl-dev ist schon die neueste Version (3.0.11-1~deb12u2+rpt1).
Das folgende Paket wurde automatisch installiert und wird nicht mehr benötigt:
  libpisp0.0.1
Verwenden Sie »sudo apt autoremove«, um es zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
root@raspberrypi:~# sudo apt install raspberrypi-kernel-headers pivccu-modules-dkms
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
E: Paket pivccu-modules-dkms kann nicht gefunden werden.
root@raspberrypi:~# nano /etc/apt/sources.list.d/pivccu.list
  GNU nano 7.2                                                          /etc/apt/sources.list.d/pivccu.list

**Comment by alexreinert** [comment]
Das waren Schritt 1 und 3. Schritt 2 fehlt in der Ausgabe.

**Comment by susiartig** [comment]
Sorry - hab ich tatsächlich übersehen - bin da mit meiner älteren Doku vor 1 Jahr durcheinander gekommen.
War Anfängerfehler von mir - Danke für die Unterstützung.
Nun funktioniert die Installation:
root@raspberrypi:~# echo "deb [signed-by=/usr/share/keyrings/pivccu.asc] https://apt.pivccu.de/piVCCU stable main" | sudo tee /etc/apt/sources.list.d/pivccu.list
sudo apt update
deb [signed-by=/usr/share/keyrings/pivccu.asc] https://apt.pivccu.de/piVCCU stable main
OK:1 http://deb.debian.org/debian bookworm InRelease
OK:2 http://deb.debian.org/debian-security bookworm-security InRelease
OK:3 http://deb.debian.org/debian bookworm-updates InRelease
OK:4 http://archive.raspberrypi.com/debian bookworm InRelease
Holen:5 https://apt.pivccu.de/piVCCU stable InRelease [13,6 kB]
Holen:6 https://apt.pivccu.de/piVCCU stable/main armhf Packages [13,9 kB]
Holen:7 https://apt.pivccu.de/piVCCU stable/main arm64 Packages [13,8 kB]
Es wurden 41,3 kB in 4 s geholt (11,5 kB/s).
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Alle Pakete sind aktuell.
root@raspberrypi:~# sudo **apt install raspberrypi-kernel-headers pivccu-modules-dkms**
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
raspberrypi-kernel-headers ist schon die neueste Version (1:1.20230405-1).
Das folgende Paket wurde automatisch installiert und wird nicht mehr benötigt:
  libpisp0.0.1
Verwenden Sie »sudo apt autoremove«, um es zu entfernen.
Vorgeschlagene Pakete:
  menu
Die folgenden NEUEN Pakete werden installiert:
  dkms pivccu-modules-dkms
0 aktualisiert, 2 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 91,9 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 190 kB Plattenplatz zusätzlich benutzt.
Holen:1 http://deb.debian.org/debian bookworm/main arm64 dkms all 3.0.10-8+deb12u1 [48,7 kB]
Holen:2 https://apt.pivccu.de/piVCCU stable/main arm64 pivccu-modules-dkms all 1.0.84 [43,1 kB]
Es wurden 91,9 kB in 4 s geholt (23,4 kB/s).
Vorkonfiguration der Pakete ...
Vormals nicht ausgewähltes Paket dkms wird gewählt.
(Lese Datenbank ... 93082 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../dkms_3.0.10-8+deb12u1_all.deb ...
Entpacken von dkms (3.0.10-8+deb12u1) ...
dkms (3.0.10-8+deb12u1) wird eingerichtet ...
Vormals nicht ausgewähltes Paket pivccu-modules-dkms wird gewählt.
(Lese Datenbank ... 93106 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../pivccu-modules-dkms_1.0.84_all.deb ...
Entpacken von pivccu-modules-dkms (1.0.84) ...
pivccu-modules-dkms (1.0.84) wird eingerichtet ...
Ensure non mixed processor architecure ... Done
Create kernel modules ... Done
Enable DKMS service ... Done
Trigger für man-db (2.11.2-2) werden verarbeitet ...
root@raspberrypi:~#

Nochmals Entschuldigung für die Mühe,
Danke, susi
