### ISSUE TITLE
Keine Verbindung zum HmIPW Access Point mit piVCCU3

### ISSUE THREAD

**Issue by brunsheinz** [alexreinert/piVCCU#515]
Hallo , Ich habe mehre Varianten der CCU3 laufen . (nicht gleichzeitig) Auf dem dem Raspi 4 mit 32 bit Version ( Image mit Debian 10) , als auch auf der 64 bit Version (Debian 12) wird der Homematic IP Wired Access Point nicht mehr erkannt . Im Access Point blinkt die Lampe türkis und alle nachfolgenden Geräte werden nicht erkannt . 
Auf dem Container in Proxmox mit Raspberrymatic funktioniert alles einwandfrei . Der Access Point hat eine feste IP zugeordnet . Auf der Fritzbox 4040 wird der Access Point immer erkannt .

**Comment by alexreinert** [comment]
Was heißt "nicht mehr"? Welches Funkmodul? War er schon angemeldet oder soll er frisch angemeldet werden? Was liefert pivccu-info? Welche Hardware wird verwendet?

**Comment by brunsheinz** [comment]
Hallo , Der HmIPW-Drap läuft bei mir schon länger . Zunächst mit der CCU3 und dem RPI-RF-Mod Modul , dann im Container von Proxmox mit dem HmIP-RFUSB Stick . In der Geräteliste der WebUIi st der HmipW AP immer vorhanden .
Nur auf dem Raspberry Pi4 läuft der HmipW AP nicht . Wenn ich unter Geräte auf Test gehe ,geht es auch nicht (bleibt gelb) . Der HmIPW hat eine feste Ip Adresse und ist auf der Fritz Box4040 immer zu erkennen . Gleichzeitig habe ich im Heimnetz noch eine CCU2 als Lan Gateway auch mit fester IP . Diese wird immer erkannt .
Bei der Installation habe immer das Backup von der Raspberrymatic genommen , um alle Geräte zu installieren .
Hier die Info piVCCU
64Bit Debian12
pi@raspberrypi4:~ $ sudo pivccu-info
piVCCU version: 3.73.9-87
OS:             Debian GNU/Linux 12 (bookworm)
Kernel:         6.1.0-rpi7-rpi-v8 aarch64
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO@fe201000.serial (/dev/raw-uart)
 Board serial:  REQ0911958
 Radio MAC:     0x71D2D7
HMIP Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO@fe201000.serial (/dev/raw-uart)
 SGTIN:         3014F711A061A7DBE9975256
 Radio MAC:     0xBB02B8
State:          RUNNING
PID:            1450
IP:             192.168.123.107
Link:           vethpivccu
 TX bytes:      1.15 MiB
 RX bytes:      653.90 KiB
 Total bytes:   1.79 MiB
hier die log Datei von piVCCU3
[ccu3-webui-2024-01-05 (5).log](https://github.com/alexreinert/piVCCU/files/13843372/ccu3-webui-2024-01-05.5.log)
hier dann mal der Log von der Raspberrymatic (dort funktioniert alles)
[ccu3-Proxmox-2024-01-05 (2).log](https://github.com/alexreinert/piVCCU/files/13843394/ccu3-Proxmox-2024-01-05.2.log)

**Comment by brunsheinz** [comment]
Hallo , Das Problem habe ich gelöst . In der Fritz Box alle Ungenutzten Ip`s und auch den Eintrag für HmIpW gelöscht . Dann noch mal piVCCU3 neu installiert und mit neuer IP Adresse vom HmIPW Drap meldet sich der Homematic IP Wired Access Poit richtig in der piVCCU3 an .

**Comment by brunsheinz** [comment]
Danke für die Bemühungen , andere Ip vom HmipW Drap und alles funktioniert
