### ISSUE TITLE
Raspberry pi5 HM-RF Usb 2 + HM-MOD-RPI-PCB funktioniert nicht

### ISSUE THREAD

**Issue by rmp63526** [alexreinert/piVCCU#517]
Hallo, ich habe jetzt nach dieser Anleitung installiert ( https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md ) und Punkt 4-5 und Punkt 6 Option 2 ausgelassen. Punkt 7 ausgelassen.

Leider funktioniert es nicht. Die aufgesteckte Antenne am HM-RF -Usb-2 wird über den USB-Slot nicht erkannt.

Auf meinem raspberry pi 4 funktioniert es.

Was kann ich noch tun?

![Unbenannt](https://github.com/alexreinert/piVCCU/assets/65367883/89a7dfb1-dd82-46a3-8646-952ba6e7fb4d)
![Unbenannt](https://github.com/alexreinert/piVCCU/assets/65367883/5a24fbdd-f132-4ee6-b931-05a01322c93f)

**Comment by alexreinert** [comment]
Bitte Bilder der Lötstellen der Platine und des aufgesteckten Funkmoduls.
Ebenfalls bitte die Ausgabe von lsusb.

**Comment by rmp63526** [comment]
Ich glaube, ich kann ausschließen, dass es an einer schlechten Lötstelle liegt, obwohl meine nicht die besten sind. :-)
Ich benutze die Platine und das Funkmodul auf meinem Pi 4 und es läuft da wie ein Uhrwerk.

Ausgabe lsusb:
![Unbenannt](https://github.com/alexreinert/piVCCU/assets/65367883/65badd71-dbbe-4980-8734-f7b310cd3208)


![IMG_3561](https://github.com/alexreinert/piVCCU/assets/65367883/1c2c9fe3-d615-4ce5-a16e-fdda02e91ebe)
![IMG_3562](https://github.com/alexreinert/piVCCU/assets/65367883/92f6bb94-12bf-49ed-8438-1ec17117328a)
![IMG_3566](https://github.com/alexreinert/piVCCU/assets/65367883/769f62d9-3e5f-4cce-b26c-d24e35bebb4a)
![IMG_3567](https://github.com/alexreinert/piVCCU/assets/65367883/6c5f8367-b5f4-4161-8d7f-28f18e981806)
![IMG_3568](https://github.com/alexreinert/piVCCU/assets/65367883/bca7f64a-1019-4cb2-9fa8-9d6b3011855a)
![IMG_3569](https://github.com/alexreinert/piVCCU/assets/65367883/be219bdb-2ec1-463a-8249-7a3a67068cb2)
![IMG_3570](https://github.com/alexreinert/piVCCU/assets/65367883/0916a532-f623-450c-94ee-03cc08fc796c)

**Comment by alexreinert** [comment]
Bitte mal diese Befehle ausführen und die Ausgabe hier posten:

```
sudo lsusb | grep raw
sudo ls -la /dev/raw*
```

**Comment by rmp63526** [comment]
![Unbenannt](https://github.com/alexreinert/piVCCU/assets/65367883/7b78b7ea-026a-4fbb-8de8-faa64b242e9c)

**Comment by rmp63526** [comment]
@alexreinert  hast du eventuell eine Idee?

**Comment by rmp63526** [comment]
@alexreinert ???

**Comment by rmp63526** [comment]
Finde ich echt Schade das ich mit deiner Platine so im Regen stehen gelassen werde!
Ich würde sie halt echt gern langsam mal mit meinem Raspberrypi 5 benutzen!

**Comment by alexreinert** [comment]
Ich kann leider nur sagen, dass die Platine allgemein am Pi5 funktioniert.
Auf den Bildern sind einige Lötkontakte, die sehr grenzwertig sind, möglicherweise schaffen die es am Pi4 grade noch zu funktionieren und der Pi5 ist empfindlicher. Ist aber leider nur stochern im Nebel.

**Comment by rmp63526** [comment]
Kannst du mir von der Anleitung genau sagen welche Befehle/Punkte du eingegeben hast.
https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md

**Comment by alexreinert** [comment]
1,2,3,5,8,9,10,11

**Comment by rmp63526** [comment]
keine chance!
Muss ich etwas in der boot config datei anpassen?

**Comment by alexreinert** [comment]
Nein.
Aber magst du vielleicht einfach mal die Platine nachlöten, einfach um sicher zu gehen? Kalte Lötstellen funktionieren teilweise auch mal, haben aber einen höheren Widerstand, welcher möglicherweise zu Problemen führt. Und du hast mehrere Lötstellen, welche verdächtig nach kalter Lötstelle aussehen.

**Comment by rmp63526** [comment]
Ich habe alle Punkte noch einmal mit der Entlötpumpe freigelegt und neu gelötet. Leider immer noch das gleiche Ergebnis.
Ich stecke die Antenne jetzt einfach direkt auf den Pi5, das funktioniert auf Anhieb. Schade um die Platine, die geht auf dem Pi4 sofort.  Issue kann geschlossen werden!
