### ISSUE TITLE
Question: read only file system

### ISSUE THREAD

**Issue by s0170071** [alexreinert/piVCCU#52]
I plan on hardening the pi by having it boot from an read only sd card and write logs to another drive. 
Does that work with piVCCU ?  I am aware of the fact that I cannot modify programs then...

Have you ever tried it ?

**Comment by alexreinert** [comment]
Never tried it, but I'm really sure, that this will not work that stable.

**Comment by alexreinert** [comment]
If there is anything left or unclear, please reopen
