### ISSUE TITLE
Restoring CC3 backup fails with error

### ISSUE THREAD

**Issue by Ltty** [alexreinert/piVCCU#527]
Hi @alexreinert,

I'm migrating my pivccu from a Pi4 to a Pi5 (fresh install).

I now tried to export a backup from the old CCU3 and import it in the new CCU3 and get the following error:
![image](https://github.com/user-attachments/assets/0b85244b-db0c-40b6-807e-c4848fdfa683)

Do you have any idea what might be wrong?

Thanks,
Florian

**Comment by alexreinert** [comment]
The radio module is needed when restoring the backup, but it is not found.

Please provide the output of `sudo pivccu-info` on the Pi 5 before restoring the backup.

**Comment by Ltty** [comment]
Thanks, using the hardware resolved the issue
