### ISSUE TITLE
Gruppen anlegen nicht möglich.

### ISSUE THREAD

**Issue by 0x7878** [alexreinert/piVCCU#531]
Hallo zusammen,

In der aktuellen Firmware-Version 3.77.7 ist es nicht möglich, neue Gruppen zu erstellen (siehe Screenshot).

Zunächst dachte ich, es läge am Browser, und habe verschiedene Optionen ausprobiert, von Chrome bis Firefox. Leider lässt sich selbst eine leere Gruppe, wie im Screenshot dargestellt, nicht anlegen, da ein Skriptfehler auftritt. Hat jemand eine Idee für einen möglichen Workaround?

![image](https://github.com/user-attachments/assets/18591126-aeb4-45f0-823b-8e8707c6015a)

**Comment by alexreinert** [comment]
Ich kann das Problem in einer Testinstallation nicht nachvollziehen, da funktioniert das einwandfrei.

**Comment by 0x7878** [comment]
Kurze Aufklärung. Leiche war im Posteingang :D Es war nicht konfiguriert und daduch konnte man keine Gruppen mehr anlegen. Problem ist gelöst.
