### ISSUE TITLE
Device firmware update not possible?

### ISSUE THREAD

**Issue by webphi** [alexreinert/piVCCU#532]
Hello,

unfortunately it is not possible for me to update a device firmware.
The ccu displays that there are firmware updates for some devices available.
But when I try to download them, I only get redirected to a page with "an error eccoured".

I dont see any other possibility to download the firmware manually.

It would be great if anyone could show me how to upgrade the device firmwares.
Thanks in advance!

Regards
Philip

![image](https://github.com/user-attachments/assets/afdf0fca-8023-4093-a3a6-732ddcb06861)
![image](https://github.com/user-attachments/assets/0325a591-f57d-4421-b574-f3242d12093b)

**Comment by alexreinert** [comment]
The error message is on the website of eQ-3. Unfortunatly I cannot assist you with that.

**Comment by webphi** [comment]
Okay thanks. I thought it might be a wrong link or something like that.
I will contact eQ-3 directy then.

**Comment by malloy139** [comment]
> Okay thanks. I thought it might be a wrong link or something like that. I will contact eQ-3 directy then.

Did you get a response from them?

**Comment by webphi** [comment]
Yes, they said is has something to do with the browser or the cache. I could not solve it.

To be honest I switched to Home Assistant meanwhile and a new smart home server, so I also switched to RaspberryMatic.
I had no problems with that one and could download the firmware update instantly.
