### ISSUE TITLE
Anzahl der sonst wenn Einträge weniger als mit CCU2

### ISSUE THREAD

**Issue by reibbi** [alexreinert/piVCCU#59]
Hallo, habe das Problem dass ich im WebUI teilweise Programme auf 2 Programme aufteilen muss, da piVCCU anscheinend nur 9 SonstWenn Abfragen verträgt.
Sobald es mehr sind werden die danach einfach nicht abgearbeitet.
Mit der CCU2 hatte ich hier keine Probleme.

Bsp.: Bei einem 6fach Taster wenn man hier auch noch ein paar kurze bzw. lange Tastendrücke abfragt wird dies dann zum Problem.

**Comment by alexreinert** [comment]
Hi,
es gibt hier keinen Unterschied zur CCU2, da die gleichen Binaries verwendet werden.

Testweise habe ich hier auch ein Programm mit 11 SonstWenn angelegt, das ging ohne Probleme.

**Comment by alexreinert** [comment]
Wie äußert sich denn das "anscheinend verträgt piVCCU nicht" genau?

**Comment by reibbi** [comment]
Komisch läuft bei mir nicht.

Ich hab das paket iobroker mit pivccu aug der iobroker homepage grladen.

Was ich auch nicht einstellen kann ist https bei der web oberflaeche.  Das
wird einfach nicht übernommen nach dem reboot.



Alexander Reinert <notifications@github.com> schrieb am So., 1. Juli 2018,
08:09:

**Comment by reibbi** [comment]
![grafik](https://user-images.githubusercontent.com/40730085/42131836-d6b3281c-7d0b-11e8-82e6-2a33e50eabe5.png)

**Comment by reibbi** [comment]
Programm 2:
![grafik](https://user-images.githubusercontent.com/40730085/42131845-009a21bc-7d0c-11e8-9810-1aa8b402af91.png)

**Comment by reibbi** [comment]
![grafik](https://user-images.githubusercontent.com/40730085/42131859-199b5dc0-7d0c-11e8-8635-33b16ee8a854.png)

**Comment by reibbi** [comment]
Zur INfo: Anlegen lassen sich die Programme schon mit mehr abfragen, nur werden die letzten Dann einfach nicht mehr abgearbeitet.

**Comment by reibbi** [comment]
Ev. liegt hier ja wirklich das Problem dass der Taster neu beschrieben werden muss, oder musste, weil sich da was verlaufen hat. Hatte aber mehrere Tests versucht dies zu bewerkstelligen, aber ohne Erfolg. Ich versuchs nochmals und berichte. Vielen Dank.

**Comment by alexreinert** [comment]
Irgendwelche Neuigkeiten? Ansonsten würde ich hier mal zu machen und du kannst bei Bedarf wieder aufmachen.

**Comment by reibbi** [comment]
Ja mach bitte zu ich schreib dann wenn ich wieder zeit habe danke

Alexander Reinert <notifications@github.com> schrieb am Mi., 25. Juli 2018,
13:49:
