### ISSUE TITLE
ELV Funk-Modulplatine RPI-RF-MOD

### ISSUE THREAD

**Issue by amnesiac0815** [alexreinert/piVCCU#60]
Hi:)

wird die neue Funk Modulplatine RPI-RF-MOD überstürzt?

Danke schon Mal und schöne Grüße:)

**Comment by alexreinert** [comment]
Steht doch eindeutig im Readme: Ja.

**Comment by amnesiac0815** [comment]
Sorry:( hab den Button übersehen die komplette Readme zu lesen. Vielen Dank! Und vor allem vielen Dank für die Arbeit!
