### ISSUE TITLE
CCU not starting without network/WiFi?

### ISSUE THREAD

**Issue by Jojo-A** [alexreinert/piVCCU#61]
Hi,

I have installed piVCCU on my ODROID C2, running the current Armbian testing-image.
I am using WiFi, and basically this setup works perfectly.

Problem: the CCU does apparently not start, as long as there is no network connection/WiFi is not reachable and the webUI is not reachable.
A few moments after switching on WiFi on router-side, the CCU starts and the WebUI becomes reachable.

From my point of view, this restriction does not make much sense, because the CCU can be maintained direct locally from the device, where it is installed on (which does not apply to a normal CCU, of course), so network would not be generally needed.

Is this a kind of "feature" or a bug?

Greetings

**Comment by alexreinert** [comment]
I'm not really understanding the issue:
Which images do you use exactly? How did you configure the network? (Provide /etc/network/interfaces)
What do you mean with "CCU does not start"?
How should be WebUI be available in your network, if there is no network connection available? Or do you have a desktop image and are using a browser directly on the Odroid?

**Comment by Jojo-A** [comment]
Ok, sorry for not pointing that out clear enough :/ .

Actually am am using the latest Armbian Stretch Desktop testing image (there is just no "stable" image, yet). But the "problem" is also present in your latest prebuild C2 image.
I configured the network on my C2 to use WiFi: I connected to a known network and I configured the piVCCU stuff according to your tutorial (copy/paste).
With this setup (SBC + HM-MOD-RPI-PCB, desktop image with locally running web browser), I thought I could run a "stand-alone" CCU, which not generally requires to have network access, because it could be accessed and maintained locally. 
Apparently this assumption seems to be wrong, because when I boot up the system (which automatically starts the piVCCU service) while there is no WiFi available, the local browser can not connect to the WebUI (page not found). This made me think, that the piVCCU waits until a network connection is reachable -> this is what I mean with "CCU does not start". 

Don't get me wrong, I just don't know if this is a desired behavior. If yes, then I just like to ask/propose, if this behavior can be changed, so that the piVCCU service completely starts even without network connectivity.

Greetings

**Comment by alexreinert** [comment]
Which URL do you try to connect with? The external address of the host (which is of course not available, if no wifi is available, as the interface is logically down) or the internal IP of the CCU (192.168.253.2)?

**Comment by Jojo-A** [comment]
I try to connect to 192.168.253.2:8181. This fails, if no WiFi is available. When the host WiFi network becomes available, the ODROID connects to it, and a few moments later, the CCU is reachable under the address 192.168.253.2:8181.

**Comment by Jojo-A** [comment]
Ok, I tried it once more with a fresh installation of Armbian. There it seems to work o_O . If you want, you can close this issue with the "cannot reproduce" label. Sorry for the confusion...
Do you know, if this works when using wired network and then using the URL localhost:8181? I havn't tried yet...

Thanks!

**Comment by alexreinert** [comment]
When using wired network localhost will never work. If both, host and ccu, are configured to use static addresses, it should work even without cable when using the static ip of the ccu.
