### ISSUE TITLE
Support for Kernel 3.16.x?

### ISSUE THREAD

**Issue by Jojo-A** [alexreinert/piVCCU#62]
Hi,

Hardkernel recently released a new image for their ODROID C2, based on Ubuntu 18.04 with Kernel version 3.16.x . In terms of support, this Kernel is not bad, because it is an LTS version with support until 2020.

So do you think that we could get piVCCU running on that kernel somehow? Or is it just too far away from mainline?

Greetings

**Comment by alexreinert** [comment]
You can try it, but I will not officially support it, as it is to far away from mainline (not only the version, the patches of Hardkernel as well).
Same goes for the Device Tree Overlays. As far as I remember, they are not supported with the FEX Bootloader of Hardkernel.

**Comment by Jojo-A** [comment]
Ok, thanks for the info, I will give it a shot.
