### ISSUE TITLE
Update auf Firmware 2.35.16 nicht möglich

### ISSUE THREAD

**Issue by maloross** [alexreinert/piVCCU#65]
Versuche, piVCCU mit die o.g. Firmware zu aktualisieren, schlagen leider fehl.
Habe wie angegeben mit **"sudo apt-get update && sudo apt-get upgrade"** das Update gestartet jedoch folgende Fehlermeldung erhalten:
**"The repository 'http://alexreinert.github.io/piVCCU testing Release' does no longer have a Release file"**
Wie kann ich das Update korrekt installieren?

**Comment by alexreinert** [comment]
Das ist dann ein wirklich altes System, bei dem schon lange keine Updates eingespielt wurden.

Das Repository hat sich vor etlichen Monaten geändert auf https://www.pivccu.de/piVCCU

Um das zu ändern, muss die Datei /etc/apt/sources.list oder /etc/apt/sources.list.de/pivccu.list angepasst werden (je nachdem welches Image oder welche Anleitung genutzt wurde).

Daneben sollte nicht apt-get sondern apt verwendet werden, weil apt-get einige Pakete zurückhält.

**Comment by maloross** [comment]
Danke, so hat's einwandfrei funktioniert.
