### ISSUE TITLE
Can't download public key.

### ISSUE THREAD

**Issue by Abraham1220** [alexreinert/piVCCU#67]
From my home network I am not able to download the public key with command

`wget -q -O - https://www.pivccu.de/piVCCU/public.key | sudo apt-key add -`

Could it be possible that you block specific IP ranges (91.118.* and 91.119.*), because from a cloud server it's working fine? I cannot find any issue in my own network, therefore I am asking for support. Also a ping to 95.216.13.95 fails.

Thanks.

**Comment by alexreinert** [comment]
No, right now there are no blocks.
Maybe something could be seen on a tracert?

**Comment by Abraham1220** [comment]
Tracert doesn't bring any useful info. Also HTTPS redirection from www.pivccu.de to github is not working from my home network.

In the afternoon i will try with another dialin method and feedback.

**Comment by Abraham1220** [comment]
Ok, it was my firewall. 95.216.0.0/15 was in the drop table. Old Spamhaus list.
