### ISSUE TITLE
Backup while SD-Card is damaged

### ISSUE THREAD

**Issue by Nic0205** [alexreinert/piVCCU#69]
Hi, 

my SD-Card (Raspi) seems to be broken and I did not made a backup of my piVCCU.
The Raspi does not boot anymore and so I just have access to more or less the filesystem of the sd card.

Is there are possibility that I could make a backup of the CCU through the file system? I can only open the sd card in an Ubuntu session. Which files do I have to copy? Or is it not that easy?

Greetings 
Dominic

**Comment by alexreinert** [comment]
All settings of the CCU are stored in the folder /var/lib/piVCCU/userfs
If you used the CCU diagrams the data is stored in /var/lib/piVCCU/sdcardfs

To restore the data, the CCU container needs to be stopped. (sudo systemctl stop pivccu) and all existing data in this folders needs to be deleted first.

**Comment by Nic0205** [comment]
Thanks!
