### ISSUE TITLE
USB mounten

### ISSUE THREAD

**Issue by herbylfs** [alexreinert/piVCCU#70]
Hi,
habe dieses probiert:
Using CUxD and USB devices

    You can find available devices on the host using

    sudo pivccu-device listavailable

    Create a hook script on the host

    bash -c 'echo "#!/bin/bash" > /etc/piVCCU/post-start.sh'
    sudo chmod +x /etc/piVCCU/post-start.sh

    For each device add an entry to this hook file, e.g. here for /dev/ttyUSB0

    bash -c 'echo "pivccu-device add /dev/ttyUSB0" >> /etc/piVCCU/post-start.sh'

    The devices will now be available inside the container, just use them like it is described in the CUxD documentation
Wenn diese Zeile:
 bash -c 'echo "pivccu-device add /dev/ttyUSB0" >> /etc/piVCCU/post-start.sh'
nach add /dev/ttyACM0 
eingefügt wird, ist nach einen Neustart ttyACM0 verschwunden.
Habe dann per VI den usb-stick in /etc/fstab eingefügt.

pi@raspberrypi:~ $ sudo pivccu-device listavailable                             
/dev/ttyACM0 - busware.de_CUL868
/dev/sda - Flash_USB_Disk_37272805A225B26494192-0:0
/dev/sda1 - Flash_USB_Disk_37272805A225B26494192-0:0
pi@raspberrypi:~ $

root@tinkerboard:~# sudo pivccu-device listavailable                             
/dev/ttyACM0 - busware.de_CUL868
/dev/sda - Flash_USB_Disk_3727133EA246815113548-0:0
/dev/sda1 - Flash_USB_Disk_3727133EA246815113548-0:0
/dev/input/event1 - Generic_USB_Audio_201405280001
/dev/snd/controlC0 - Generic_USB_Audio_201405280001
root@tinkerboard:~#

Im Filesystem der pivccu:

VI /etc/fstab:
 /etc/fstab: static file system information.
#
# <file system> <mount pt>     <type>   <options>         <dump> <pass
/dev/sda1 /media/usb0 vfat auto,users,defaults   0   2

Im CUxD erscheint dann:
 Filesystem: /                  ext4     (rw) Total   30604164k  Used    2940764k ( 9.6%)  Free   27663400k 90.4%)
  Filesystem: /tmp               tmpfs    (rw) Total     474720k  Used         64k ( 0.0%)  Free     474656k (100.0%)
  Filesystem: /var               tmpfs    (rw) Total     200704k  Used        368k ( 0.2%)  Free     200336k (99.8%)
  Filesystem: /usr/local         ext4     (rw) Total   30604164k  Used    2940764k ( 9.6%)  Free   27663400k (90.4%)
  Filesystem: /media/sd-mmcblk0  ext4     (rw) Total   30604164k  Used    2940764k ( 9.6%)  Free   27663400k (90.4%)
  Filesystem: /media/usb0        vfat     (rw) Total   30659952k  Used          4k ( 0.0%)  Free   30659948k (100.0%)

Vielleicht hilft es ja! 
mfg
herby

**Comment by alexreinert** [comment]
Duplicate zu #36
