### ISSUE TITLE
piVCCU startet nicht mehr nach Upgrade auf 2.35.16-38

### ISSUE THREAD

**Issue by EriHau** [alexreinert/piVCCU#71]
Hallo Alex,
bei mir lief seit Jänner piVCCU ohne Probleme. Heute zog ich den RPI inkl. piVCCU auf die neueste Version hoch. Jetzt fährt das service nicht mehr hoch.
Habe viel gelesen und alles mögliche probiert. Kein Erfolg.
pivccu-info sagt:
`piVCCU version: 2.35.16-38
Kernel modules: Not available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          STOPPED`

Kernel re-installiert -> ok

`sudo apt --reinstall install pivccu-modules-dkms pivccu-modul` durchgeführt.
Output:

`Unpacking
pivccu-modules-dkms (1.0.13) over (1.0.13) ...
Preparing to unpack .../pivccu-modules-raspberrypi_2.0-8_armhf.deb ...
Removed /etc/systemd/system/multi-user.target.wants/pivccu-rpi-modules.service.
Adding 'diversion of /boot/overlays/pivccu-raspberrypi.dtbo to /usr/share/rpikernelhack/overlays/pivccu-raspberrypi.dtbo by rpikernelhack'
Unpacking pivccu-modules-raspberrypi (2.0-8) over (2.0-8) ...
Setting up pivccu-modules-dkms (1.0.13) ...
Loading new pivccu-1.0.13 DKMS files...
It is likely that 4.14.70-v7+ belongs to a chroot's host
Building for 3.6-trunk-rpi, 4.14.70+ and 4.14.70-v7+
Building initial module for 3.6-trunk-rpi
Error! Bad return status for module build on kernel: 3.6-trunk-rpi (armv7l)
Consult /var/lib/dkms/pivccu/1.0.13/build/make.log for more information.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service ? /lib/systemd/system/pivccu-dkms.service.
Setting up pivccu (2.35.16-38) ...
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu.service ? /lib/systemd/system/pivccu.service.
Job for pivccu.service failed because the control process exited with error code.
See "systemctl status pivccu.service" and "journalctl -xe" for details.
Setting up pivccu-modules-raspberrypi (2.0-8) ...
Removing 'diversion of /boot/overlays/pivccu-raspberrypi.dtbo to /usr/share/rpikernelhack/overlays/pivccu-raspberrypi.dtbo by rpikernelhack'
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-rpi-modules.service ? /lib/systemd/system/pivccu-rpi-modules.service.
`

Inhalt Make.log
`DKMS make.log for pivccu-1.0.13 for kernel 3.6-trunk-rpi (armv7l)
Sat 22 Sep 17:33:21 CEST 2018
make -C /lib/modules/3.6-trunk-rpi/build M=/var/lib/dkms/pivccu/1.0.13/build modules
make[1]: Entering directory '/usr/src/linux-headers-3.6-trunk-rpi'
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
  CC [M]  /var/lib/dkms/pivccu/1.0.13/build/eq3_char_loop.o
  CC [M]  /var/lib/dkms/pivccu/1.0.13/build/plat_eq3ccu2.o
  CC [M]  /var/lib/dkms/pivccu/1.0.13/build/generic_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.13/build/pl011_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.13/build/dw_apb_raw_uart.o
/var/lib/dkms/pivccu/1.0.13/build/generic_raw_uart.c: In function ?generic_raw_uart_probe?:
/var/lib/dkms/pivccu/1.0.13/build/generic_raw_uart.c:712:3: error: implicit declaration of function ?device_property_read_u32? [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
/usr/src/linux-headers-3.6-trunk-common/scripts/Makefile.build:313: recipe for target '/var/lib/dkms/pivccu/1.0.13/build/generic_raw_uart.o' failed
make[4]: *** [/var/lib/dkms/pivccu/1.0.13/build/generic_raw_uart.o] Error 1
make[4]: *** Waiting for unfinished jobs....
/var/lib/dkms/pivccu/1.0.13/build/dw_apb_raw_uart.c:28:25: fatal error: linux/reset.h: No such file or directory
compilation terminated.
/usr/src/linux-headers-3.6-trunk-common/scripts/Makefile.build:313: recipe for target '/var/lib/dkms/pivccu/1.0.13/build/dw_apb_raw_uart.o' failed
make[4]: *** [/var/lib/dkms/pivccu/1.0.13/build/dw_apb_raw_uart.o] Error 1
/usr/src/linux-headers-3.6-trunk-common/Makefile:1208: recipe for target '_module_/var/lib/dkms/pivccu/1.0.13/build' failed
make[3]: *** [_module_/var/lib/dkms/pivccu/1.0.13/build] Error 2
Makefile:130: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.6-trunk-rpi'
Makefile:18: recipe for target 'all' failed
make: *** [all] Error 2
`

Was kann ich noch machen ohne das System komplet neu aufzusetzen?

Viele Grüße
Erich

**Comment by alexreinert** [comment]
Mir ist nicht ganz klar, weshalb du da noch Kernel Header für einen 3.6 Kernel liegen hast.
Ich würde Folgendes vorschlagen:
Erstmal komplette Sicherung der SD Karte. Dann unter /usr/src alle Kernel Header löschen außer den für den aktuellen Kernel, dann ein Reboot.
Nach dem Reboot sollte er seöbstständig versuchen die Kernel Module neu zu bauen, also einfach mal 10 Minuten rödeln lassen ohne was zu machen. Danach dann nochmal die Info von oben hier posten.

**Comment by EriHau** [comment]
ok - jetzt ist nur mehr 4.14.70-v7+ drauf.
Die HM-Hardware findet er nicht und es kommt ein Fehler.

> pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 2.35.16-38
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          RUNNING
PID:            3430
IP:             192.168.0.71
CPU use:        1.07 seconds
BlkIO use:      4.67 MiB
Link:           vethpivccu
 TX bytes:      2.38 KiB
 RX bytes:      10.02 KiB
 Total bytes:   12.40 KiB
pi@raspberrypi:~ $ sudo apt --reinstall install pivccu-modules-dkms pivccu-modulReading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package pivccu-modul

**Comment by alexreinert** [comment]
Fahr mal komplett runter und dann für 1 Minute komplett stromlos machen. Manchmal hängt sich das Funkmodul auf.

**Comment by EriHau** [comment]
War leider nicht erfolgreich. Hab sogar das Modul nochmal runter/rauf falls ein Kontaktproblem wäre. Kann ich rigendwie "händisch" das Modul prüfen. Glaube ja nicht, dass es bei einem SW-Update des Pi stirbt. Wäre schon ein seltsamer Zufall.

**Comment by alexreinert** [comment]
Einfachste Variante, falls du noch eine SD Karte frei hast: Das fertige Image nehmen und damit schauen, ob das Modul erkannt wird. Da weiß ich, dass sämtliche Einstellungen in der Software korrekt sind. Dann hätten wir an der Stelle Sicherheit, ob es an der Hardware oder an der Software liegt.

In der bestehenden Installation wären folgende Sachen noch interessant:
```
sudo cat /boot/config.txt
sudo systemctl stop pivccu
sudo pivccu-info
sudo dmesg
```

**Comment by EriHau** [comment]
Fertiges Image bringt das gleiche Ergebnis:

> pi@raspberrypi:~ $ sudo pivccu-info 
piVCCU version: 2.35.16-35
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          RUNNING
PID:            681
IP:             192.168.0.108
CPU use:        17.63 seconds
BlkIO use:      20.88 MiB
Link:           vethpivccu
 TX bytes:      7.00 KiB
 RX bytes:      104.18 KiB
 Total bytes:   111.18 KiB


dmesg am Image bringt:

> [   51.487071] eq3loop: created slave ttyS0
[   51.487321] eq3loop: created slave mmd_bidcos
[   66.104589] eq3loop: eq3loop_open_slave() mmd_bidcos
[   68.356433] eq3loop: eq3loop_close_slave() mmd_bidcos
[   77.765833] eq3loop: eq3loop_open_slave() ttyS0
[   77.765969] eq3loop: eq3loop_close_slave() ttyS0
[   77.769535] eq3loop: eq3loop_open_slave() ttyS0
[   77.769638] eq3loop: eq3loop_close_slave() ttyS0
[   77.779365] eq3loop: eq3loop_open_slave() ttyS0
[   77.781612] eq3loop: eq3loop_ioctl_slave() ttyS0: unhandled ioctl 0x5459
[   77.781625] eq3loop: eq3loop_ioctl_slave() ttyS0: unhandled ioctl 0x545D
[  652.467706] eq3loop: eq3loop_close_master() mmd_bidcos
[  652.467720] eq3loop: eq3loop_close_master() mmd_bidcos destroy device
[  652.467981] eq3loop: eq3loop_close_master() ttyS0
[  652.814031] eq3loop: eq3loop_close_slave() ttyS0
[  652.814040] eq3loop: eq3loop_close_slave() ttyS0 destroy device
[  656.776379] br0: port 2(vethpivccu) entered disabled state
[  656.778932] device vethpivccu left promiscuous mode
[  656.778942] br0: port 2(vethpivccu) entered disabled state
[  656.930988] Stopped plat_eq3ccu2
[  674.233315] Started plat_eq3ccu2


Hast du noch eine Idee oder soll ich mir gleich ein neues Modul bestellen?

**Comment by alexreinert** [comment]
Beim fertigen Image weiß ich, dass alles korrekt eingestellt ist, daher gehe ich von einem Hardware Problem aus. Wenn du ausschließen kannst, dass das Modul falsch aufgesteckt ist, würde ich auf einen Defekt tippen.
Was du noch probieren kannst, wäre es mal alle Lötpunkte nachzulöten, vielleicht ist ja eine kalte Lötstelle dabei.

**Comment by EriHau** [comment]
**** gelöst ****
was habe ich gemacht (zum Nachvollziehen damit die Nachwelt auch etwas zum Lesen hat )

1.) Nachlöten -> war auch erfolglos.

2.) Modul runter und Tx-Rx gebrückt am GPIO

3.) mit `sudo nano /boot/config.txt` den Eintrag "dtoverlay= pivccu-raspberry" mit "#" ausgehängt

4.) reboot

5.) jetzt ist mit `ls -lh /dev/serial[0,1]` auch serial0 wieder sichtbar

6.) minicom installiert

7.) `minicom -D /dev/serial0` aufgerufen und bei Tastendruck muss ein Echo über die Loopback-Brücke kommen -> ok. Damit ist klar: Der PI3 funktioniert noch.

8.) Die EQ3-Utils (occu) hatte ich gestern schon installiert

9.) im occu-Verzeichnis Aufruf des Test `eq3configcmd test-coprocessor -p /dev/serial0 -i 5 -l 0` -> Test läuft durch. Damit ist klar, das Modul funktioniert noch.

10.) Firmware vom Modul abgefragt mit `eq3configcmd update-coprocessor -p /dev/serial0 -v -c -d ./firmware/ -l0` -> bringt leider Fehlermeldung: 

> 2018/09/23 11:12:04.815 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2018/09/23 11:12:05.346 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2018/09/23 11:12:05.876 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2018/09/23 11:12:06.406 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2018/09/23 11:12:09.286 <Error> CoprocessorUpdate::startApplication():Could not start Coprocessor application.
2018/09/23 11:12:09.286 <Error> Could not start Application, maybe no application on device, do update with dummy Version: 0.0.0

11.) Modul in den Bootloder gesetzt mit `eq3configcmd update-coprocessor -p /dev/serial0 -bl -c -d ./firmware/HM-MOD-UART/ -l 0 -t HM-MOD-UART`

12.) Firmware mit Force-Flag reingeschossen: `eq3configcmd update-coprocessor -p /dev/serial0 -u -f -c -d ./firmware/HM-MOD-UART/ -l 0 -t HM-MOD-UART` -> Firmware erfolgreich geladen!!!

13.) Firmware-Version  zur Sicherheit nochmal ausgelesen `eq3configcmd update-coprocessor -p /dev/serial0 -v -f -c -d ./firmware/HM-MOD-UART/ -l 0 -t HM-MOD-UART` -> Version 1.4.1

14.) App am Modul gestartet mit `eq3configcmd update-coprocessor -p /dev/serial0 -app -f -c -d ./firmware/HM-MOD-UART/ -l 0 -t HM-MOD-UART`

15.) im config.txt das Overlay wieder freigegeben (siehe Punkt3)

16.) reboot

17.) piVCCU schnurrt wieder

> pi@raspberrypi:~ $ sudo pivccu-info
piVCCU version: 2.35.16-38
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   OEQ0607068
Radio MAC:      0x59d874
SGTIN:          unknown
State:          RUNNING
PID:            1489
IP:             192.168.0.71
CPU use:        0.89 seconds
BlkIO use:      5.46 MiB
Link:           vethpivccu
 TX bytes:      18.60 KiB
 RX bytes:      17.13 KiB
 Total bytes:   35.73 KiB

Scheinbar wurde beim Update die Firmwware am Modul zerschossen.

Damit ist meine Hütte und mein Blutdruck wieder normal und ich kann den Rest des Wochenendes genießen.
Vielen Dank für deinen Support!
Liebe Grüße / Erich
