### ISSUE TITLE
ccu3

### ISSUE THREAD

**Issue by herbylfs** [alexreinert/piVCCU#72]
Hallo,
ich stehe momentan irgendwie auf dem Schlauch.
Habe dies durchgeführt:
Installation

    Create full backup of your SD card

    Add the public key of the repository

    wget -q -O - https://www.pivccu.de/piVCCU/public.key | sudo apt-key add -

    Add the package repository

    sudo bash -c 'echo "deb https://www.pivccu.de/piVCCU stable main" > /etc/apt/sources.list.d/pivccu.list'
    sudo apt update
Bekomme aber nach einen sudo apt update die Meldung:
Hit:3 https://www.pivccu.de/piVCCU stable InRelease
Kein stable main
mfg
herby

**Comment by herbylfs** [comment]
Die Ausgabe komplett.
pi@raspberrypi:~ $ sudo apt update
Get:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Hit:3 https://www.pivccu.de/piVCCU stable InRelease
Ign:4 https://download.webmin.com/download/repository sarge InRelease
Hit:5 https://download.webmin.com/download/repository sarge Release
Fetched 15.0 kB in 1s (7,966 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
pi@raspberrypi:~ $
herby

**Comment by herbylfs** [comment]
Irgendwie verkehrt gelaufen.
Die Ausgabe komplett.
pi@raspberrypi:~ $ sudo apt update
Get:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Hit:3 https://www.pivccu.de/piVCCU stable InRelease
Ign:4 https://download.webmin.com/download/repository sarge InRelease
Hit:5 https://download.webmin.com/download/repository sarge Release
Fetched 15.0 kB in 1s (7,966 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
pi@raspberrypi:~ $
herby

**Comment by alexreinert** [comment]
Der CCU3 code ist bisher noch nicht in Stable (siehe auch #68)

Daher muss das nicht "stable main" sein, sondern "testing main".

Falls es eine frische Installation ist, kannst du auch einfach das piVCCU3 testing Image nehmen (https://www.pivccu.de/images/testing/Raspbian_Stretch_Lite_piVCCU3_2018-09-26.zip), das habe ich gestern erstellt.

**Comment by alexreinert** [comment]
Sind noch Fragen offen oder kann ich hier zu machen?
