### ISSUE TITLE
pivccu3 image: 

### ISSUE THREAD

**Issue by saturn-hh** [alexreinert/piVCCU#73]
Hi,
this is my first post and I want to say thank you for this software. I used the ccu2 version last winter and it was perfect. Unfortunately I couldn't get the server working again, so I decided to switch to ccu3.

Here are my questions/issues:
In the messages of the pivccu3 I get: No BidCoS-Interface available
ls -l /dev/tty shows only /dev/ttyS0 on the host and no device on the container

Things I already tried:
 dpkg-reconfigure  pivccu3
dpkg-reconfigure pivccu-modules-dkms
apt install pivccu-modules-raspberrypi 

Now I'm lost and the system isn't working.

Any advise is welcome.

Alexander

Container
/var/log/messages
http://paste.debian.net/1045543/

Host
/var/log/syslog
http://paste.ubuntu.com/p/6mqqs2MmDq/
lsmod
http://paste.ubuntu.com/p/dq28gFT7mS/
uname -a
Linux raspberrypi 4.14.70-v7+ #1144 SMP Tue Sep 18 17:34:46 BST 2018 armv7l GNU/Linux

ls -l /dev/ttyS*  
/dev/ttyS0

pivccu-info
piVCCU version: 3.37.8-3
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   OEQ0610534
Radio MAC:      0x59e5fc
SGTIN:          unknown
State:          RUNNING
PID:            620
IP:             192.168.188.14
CPU use:        10.65 seconds
BlkIO use:      39.52 MiB
Link:           vethpivccu
 TX bytes:      43.14 KiB
 RX bytes:      41.99 KiB
 Total bytes:   85.13 KiB

**Comment by alexreinert** [comment]
You have an old firmware on your HM-MOD-RPI-PCB that is not DualCoPro capable. It seems, that there is a little issue updating this firmware inside the the CCU3 version, which I will fix in the next days.
For now, the easiest solution would be, to start your system using the CCU2 image one time to perform the firmware update.
The device /dev/ttyS0 is not used in the CCU3 anymore. Instead there are the device /dev/mmd_bidcos and /dev/mmd_hmip.

**Comment by saturn-hh** [comment]
Thts realy funny: I walked through the update today, BUT to get the newes firmware one has to choose this file:
dualcopro_si1002_update_blhm.eq3
Now the system is working again. But for me it is really annoying that this firmware update was the reason for this issue.
Anyhow thank you for your support and your quick response.

**Comment by alexreinert** [comment]
As said, there is a little issue, that will be fixed. The idea is, that the needed firmware is installed automatically (as in the CCU2 version)

**Comment by alexreinert** [comment]
Fixed in testing apt repo

**Comment by alexreinert** [comment]
Released in stable apt repo
