### ISSUE TITLE
Kein USB-Speicher 

### ISSUE THREAD

**Issue by FlavorFx** [alexreinert/piVCCU#74]
Hallo Alex,

Danke für deine tolle Arbeit!

Hier noch eine Frage: Nach dem Wechsel auf CCU3 Firmware scheint bei mir alles gut zu laufen.  Bis auf die Darstellung der Diagramme. Hier erscheint folgende Meldung: "Es ist kein USB-Speicher für die Speicherung der Diagrammdaten vorhanden oder auf diesen konnte nicht zugegriffen werden. Um die Diagrammdaten zu speichern, ist externer USB-Speicher erforderlich." 

Bei der CCU2 ging das einfach. Mache ich noch etwas falsch oder hat sich da ein Fehler eingeschliffen?

Grüße,
Michael

**Comment by alexreinert** [comment]
Kein Fehler. Die CCU3 braucht zwingend einen externen USB Stick für die Diagramme, entsprechend braucht piVCCU3 jetzt auch einen externen USB Stick.

**Comment by bbr111** [comment]
> Hallo Alex,
> 
> Danke für deine tolle Arbeit!
> 
> Hier noch eine Frage: Nach dem Wechsel auf CCU3 Firmware scheint bei mir alles gut zu laufen. Bis auf die Darstellung der Diagramme. Hier erscheint folgende Meldung: "Es ist kein USB-Speicher für die Speicherung der Diagrammdaten vorhanden oder auf diesen konnte nicht zugegriffen werden. Um die Diagrammdaten zu speichern, ist externer USB-Speicher erforderlich."
> 
> Bei der CCU2 ging das einfach. Mache ich noch etwas falsch oder hat sich da ein Fehler eingeschliffen?
> 
> Grüße,
> Michael

Wenn man sich mit "pivccu-attach" in den Container einloggt, kann man mit bestehenden Scripten den bestehenden Scripten unter /etc/usbmount/mount.d/ dem System vorgaukeln, es wäre ein Stick einsteckt.

einfach dort mit ./01_create_statusfile und ./02_setup_measurement das System für USB vorbereiten, obwohl kein Stick eingesteckt wurde.
Ich weiß allerdings nicht welche Effekte auftreten, wenn man dann wirklich einen USB Stick einsteckt.

**Comment by lobocobra** [comment]
Hallo zusammen
Ich starte nun meinen Raspi von einer SSD, wie kann ich nun Diagramme ohne usb-stick aktivieren?

**Comment by alexreinert** [comment]
Siehe mein Kommentar weiter oben vom 3. Oktober.

**Comment by lobocobra** [comment]
Hallo

Den Kommentar hatte ich natürlich gelesen, macht aber nur Sinn, wenn jemand eine SD Karte benutzt. Wenn man ein 256GB SSD dran hat macht die Benutzung eines USB Sticks keinen Sinn, zumal der weniger Schreibzykeln erträgt als eine SSD.

=> Wie kann man den check umgehen? Welche Scripts sind betroffen? Kannst Du mir einen Hint geben, dann ändere ich diese. Da es früher mal ohne ging, kann man es sicher deaktivieren.

**Comment by lobocobra** [comment]
> 
> 
> > Hallo Alex,
> > Danke für deine tolle Arbeit!
> > Hier noch eine Frage: Nach dem Wechsel auf CCU3 Firmware scheint bei mir alles gut zu laufen. Bis auf die Darstellung der Diagramme. Hier erscheint folgende Meldung: "Es ist kein USB-Speicher für die Speicherung der Diagrammdaten vorhanden oder auf diesen konnte nicht zugegriffen werden. Um die Diagrammdaten zu speichern, ist externer USB-Speicher erforderlich."
> > Bei der CCU2 ging das einfach. Mache ich noch etwas falsch oder hat sich da ein Fehler eingeschliffen?
> > Grüße,
> > Michael
> 
> Wenn man sich mit "pivccu-attach" in den Container einloggt, kann man mit bestehenden Scripten den bestehenden Scripten unter /etc/usbmount/mount.d/ dem System vorgaukeln, es wäre ein Stick einsteckt.
> 
> einfach dort mit ./01_create_statusfile und ./02_setup_measurement das System für USB vorbereiten, obwohl kein Stick eingesteckt wurde.
> Ich weiß allerdings nicht welche Effekte auftreten, wenn man dann wirklich einen USB Stick einsteckt.

@bbr111 
welchen mount point hast Du genommen? Ich habe gesehen, dass 2x ein file erstellt wird und danach erwartet wird dass unter dem  ${UM_MOUNTPOINT} der Folder Measurement erstellt wird.
=> Wo ist der MountPoint hinterlegt?

Vielen Dank

**Comment by lobocobra** [comment]
**Found the solution....**
touch /var/status/hasUSB
touch /var/status/hasSD //probably not needed
touch "/var/status/USBinitialised"
touch "/var/status/SDinitialised" //probably not needed
**Now either mount a free partition under /media/usb0**
mkdir /media/usb0/measurement

or just give write access to root disk
mount -o remount rw /

Pack all this in a script and launch it at start (the touch part needs probably no repeating)

**Comment by alexreinert** [comment]
Die Root Partition wird bei jedem Update platt gemacht, so wie es bei der Original CCU auch der Fall ist, die RW zu mounten ist keine gute Idee.
Die Dateien unter /var/status können die Lösung sein, aber in der CCU sind so viele versteckte Abhängigkeiten, dass ich mich nicht drauf verlassen würde. Für jmd. der weiß, was er macht, ok, aber allgemeingültig sollte man das nicht betrachten.

**Comment by lobocobra** [comment]
Danke für die Info, ich versuche es mal mit rc.local oder einem Script von der CCU aus.
