### ISSUE TITLE
/media/sd-mmcblk0 folder is not there after update to ccu3

### ISSUE THREAD

**Issue by s0170071** [alexreinert/piVCCU#75]
While I had the CCU2 firmware running there was a log file which went to: 

DEVLOGFILE=/media/sd-mmcblk0/devlog.txt

however, the folder media/sd-mmcblk0 (used to be the SD card) is gone :-(

**Comment by alexreinert** [comment]
This is correct. The original CCU3 does not have this folder anymore and because of this piVCCU3 does not have this folder.

I suggest to use an external usb storage or a folder below /usr/local
