### ISSUE TITLE
orangepiprime

### ISSUE THREAD

**Issue by Pocky2507** [alexreinert/piVCCU#76]
Gibt von Eurer Seite her die Möglichkeit den orangepiprime zu unterstützen?
Lässt sich nicht installieren.
Unbekannte Plattform.
Habe es auf einem Armbian Image für den orangepiprime versucht.

**Comment by alexreinert** [comment]
Grundsätzlich ist das vorstellbar. Allerdings habe ich keinen Zugriff auf ein Testgerät, weder auf den Orange Pi Prime selbst, noch auf irgendwas artverwandtes mit H5 Prozessor. Und komplett ohne Testgerät mit mind. mal gleichem Prozessor ist das nicht sinnvoll umsetzbar.

**Comment by Pocky2507** [comment]
Das kann ich sehr gut verstehen.
Vieleicht irgendwann mal.
Benutze nun erstmal den Raspi weiter und den orangepiprime im Multihost.
Das geht erstmal so.

**Comment by alexreinert** [comment]
Ich habe mir die Schematics vom Orange Pi Prime angeschaut. So wie es aussieht ist die GPIO Leiste von der Belegung her nicht kompatibel, da an den Pins 8 und 10 kein UART verfügbar ist, sondern nur generische I/O-Pins. Daher ist die Hardware nicht kompatibel zu den beiden Homematic Funkmodulen.
