### ISSUE TITLE
Restoring backup from CCU2 doesnt work

### ISSUE THREAD

**Issue by passuff** [alexreinert/piVCCU#81]
Tried to restore a backup from piVCCU2 2.35.16 but piVCCU3 always freezes while uploading.
Anyone else had this issue?

**Comment by passuff** [comment]
treid with several browser. edge gave me an errror message (translated from DE): failed with restore: there is no coprocessor available.

**Comment by alexreinert** [comment]
Please provide more information:

- Which hardware are you using?
- Output of the following commands

```bash
sudo pivccu-info
sudo pivccu-attach cat /var/hm_mode
sudo pivccu-attach cat /var/log/hmserver.log
sudo pivccu-attach cat /var/log/messages
```

**Comment by passuff** [comment]
I'm using a Raspberry Pi 3 Modell B+.

`sudo pivccu-info
piVCCU version: 3.37.8-3
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          RUNNING
PID:            760
IP:             192.168.178.55
IP:             2a02:908:1988:6a0:98c6:96ff:fe91:4a94
CPU use:        191.63 seconds
BlkIO use:      36.91 MiB
Link:           vethpivccu
 TX bytes:      5.28 MiB
 RX bytes:      10.48 MiB
 Total bytes:   15.76 MiB
`
`sudo pivccu-attach cat /var/hm_mode
HM_HMIP_ADDRESS=''
HM_HMIP_DEV=''
HM_HMIP_DEVNODE=''
HM_HMIP_SERIAL=''
HM_HMIP_SGTIN=''
HM_HMIP_VERSION=''
HM_HMRF_ADDRESS=''
HM_HMRF_DEV=''
HM_HMRF_DEVNODE=''
HM_HMRF_SERIAL=''
HM_HMRF_VERSION=''
HM_HOST='rpi3'
HM_HOST_GPIO_RESET=''
HM_HOST_GPIO_UART='/dev/raw-uart'
HM_LED_GREEN=''
HM_LED_RED=''
HM_LED_YELLOW=''
HM_MODE='NORMAL'
HM_RTC=''
`
`Oct 16 05:06:14 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloo                                                                                                                     p-thread-0] SYSTEM ADVICE: long-lasting deployment, check deployment configurati                                                                                                                     on - currently deployed 18 out of 20
Oct 16 05:06:14 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloo                                                                                                                     p-thread-6] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareU                                                                                                                     pdateInitialization still not met - check deployment configuration  (still unful                                                                                                                     filled: [connector.open])
Oct 16 05:06:14 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloo                                                                                                                     p-thread-3] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion s                                                                                                                     till not met - check deployment configuration  (still unfulfilled: [connector.op                                                                                                                     en])
Oct 16 05:06:21 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloo                                                                                                                     p-thread-6] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareU                                                                                                                     pdateInitialization still not met - check deployment configuration  (still unful                                                                                                                     filled: [connector.open])
Oct 16 05:06:21 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloo                                                                                                                     p-thread-3] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion s                                                                                                                     till not met - check deployment configuration  (still unfulfilled: [connector.op                                                                                                                     en])
`

`sudo pivccu-attach cat /var/log/messages
Oct 15 22:28:15 piVCCU syslog.info syslogd started: BusyBox v1.28.4
Oct 15 22:28:15 piVCCU user.notice kernel: klogd started: BusyBox v1.28.4 (2018-08-29 11:23:30 CEST)
Oct 15 22:28:15 piVCCU syslog.info syslogd exiting
Oct 15 22:28:15 ccu3-webui syslog.info syslogd started: BusyBox v1.28.4
Oct 15 22:28:15 ccu3-webui user.notice kernel: klogd started: BusyBox v1.28.4 (2018-08-29 11:23:30 CEST)
Oct 15 22:28:15 ccu3-webui daemon.err udhcpc[150]: started, v1.28.4
Oct 15 22:28:15 ccu3-webui daemon.err udhcpc[150]: sending discover
Oct 15 22:28:15 ccu3-webui daemon.err udhcpc[150]: sending select for 192.168.178.55
Oct 15 22:28:15 ccu3-webui daemon.err udhcpc[150]: lease of 192.168.178.55 obtained, lease time 864000
Oct 15 22:28:16 ccu3-webui user.info firewall: 'modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.14.70-v7+ ip6tables v1.6.2: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?) Perhaps ip6tables or your kernel needs to be upgraded.'
Oct 15 22:28:16 ccu3-webui daemon.info ifplugd(eth0)[198]: ifplugd 0.28 initializing.
Oct 15 22:28:16 ccu3-webui daemon.info ifplugd(eth0)[198]: Using interface eth0/9A:C6:96:91:4A:94 with driver <veth> (version: 1.0)
Oct 15 22:28:16 ccu3-webui daemon.info ifplugd(eth0)[198]: Using detection mode: SIOCETHTOOL
Oct 15 22:28:16 ccu3-webui daemon.info ifplugd(eth0)[198]: Initialization complete, link beat detected.
Oct 15 22:28:16 ccu3-webui daemon.warn ifplugd(eth0)[198]: Could not open /dev/tty, cannot beep.
Oct 15 22:28:16 ccu3-webui daemon.info ifplugd(eth0)[198]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
Oct 15 22:28:16 ccu3-webui daemon.warn ifplugd(eth0)[198]: client: ifup: interface eth0 already configured
Oct 15 22:28:16 ccu3-webui daemon.info ifplugd(eth0)[198]: Program executed successfully.
Oct 15 22:28:27 ccu3-webui daemon.notice ntpdate[204]: step time server 131.188.3.221 offset 0.002807 sec
Oct 15 22:28:27 ccu3-webui daemon.notice ntpd[205]: ntpd 4.2.8p11@1.3728-o Wed Aug 29 10:08:05 UTC 2018 (1): Starting
Oct 15 22:28:27 ccu3-webui daemon.info ntpd[205]: Command line: /usr/sbin/ntpd -g 0.de.pool.ntp.org 1.de.pool.ntp.org 2.de.pool.ntp.org 3.de.pool.ntp.org
Oct 15 22:28:27 ccu3-webui daemon.info ntpd[207]: proto: precision = 0.989 usec (-20)
Oct 15 22:28:27 ccu3-webui daemon.info ntpd[207]: Listen and drop on 0 v6wildcard [::]:123
Oct 15 22:28:27 ccu3-webui daemon.info ntpd[207]: Listen and drop on 1 v4wildcard 0.0.0.0:123
Oct 15 22:28:27 ccu3-webui daemon.info ntpd[207]: Listen normally on 2 lo 127.0.0.1:123
Oct 15 22:28:27 ccu3-webui daemon.info ntpd[207]: Listen normally on 3 eth0 192.168.178.55:123
Oct 15 22:28:27 ccu3-webui daemon.info ntpd[207]: Listen normally on 4 lo [::1]:123
Oct 15 22:28:27 ccu3-webui daemon.info ntpd[207]: Listening on routing socket on fd #21 for interface updates
Oct 15 22:28:27 ccu3-webui daemon.err xinetd[249]: Unable to read included directory: /etc/config/xinetd.d [file=/etc/xinetd.conf] [line=14]
Oct 15 22:28:27 ccu3-webui daemon.crit xinetd[249]: 249 {init_services} no services. Exiting...
Oct 15 22:28:29 ccu3-webui user.info root: Updating RF Lan Gateway Coprocessor Firmware
Oct 15 22:28:29 ccu3-webui user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
Oct 15 22:28:29 ccu3-webui user.debug update-coprocessor: No updatable gateways found in rfd.conf file.
Oct 15 22:28:29 ccu3-webui user.info root: Updating RF Lan Gateway Firmware
Oct 15 22:28:29 ccu3-webui user.info update-lgw-firmware: No gateway found in config file /etc/config/rfd.conf
Oct 15 22:28:29 ccu3-webui user.info root: Updating Wired Lan Gateway Firmware
Oct 15 22:28:29 ccu3-webui user.info update-lgw-firmware: No gateway found in config file /etc/config/hs485d.conf
Oct 15 22:28:29 ccu3-webui daemon.info snmpd[311]: Created directory: /var/lib/snmp
Oct 15 22:28:29 ccu3-webui daemon.info snmpd[311]: Created directory: /var/lib/snmp/cert_indexes
Oct 15 22:28:29 ccu3-webui daemon.info snmpd[311]: Created directory: /var/lib/snmp/mib_indexes
Oct 15 22:28:29 ccu3-webui daemon.info snmpd[311]: Turning on AgentX master support.
Oct 15 22:28:29 ccu3-webui daemon.info snmpd[313]: NET-SNMP version 5.7.3
Oct 15 22:28:30 ccu3-webui user.info kernel: [   57.632451] eq3loop: created slave mmd_hmip
Oct 15 22:28:30 ccu3-webui user.info kernel: [   57.632880] eq3loop: created slave mmd_bidcos
Oct 15 22:28:36 ccu3-webui user.err d^N▒~^B: No Coprocessor detected!!!
Oct 15 22:28:36 ccu3-webui user.info kernel: [   63.634530] eq3loop: eq3loop_close_master() mmd_bidcos
Oct 15 22:28:36 ccu3-webui user.info kernel: [   63.634538] eq3loop: eq3loop_close_master() mmd_bidcos destroy device
Oct 15 22:28:36 ccu3-webui user.info kernel: [   63.634684] eq3loop: eq3loop_close_master() mmd_hmip
Oct 15 22:28:36 ccu3-webui user.info kernel: [   63.634688] eq3loop: eq3loop_close_master() mmd_hmip destroy device
Oct 15 22:28:40 ccu3-webui user.err rfd: CCU2CommController::improvedInit() - Identify response string not handled:
Oct 15 22:28:40 ccu3-webui user.info kernel: [   67.753543] eq3loop: eq3loop_open_slave() mmd_bidcos
Oct 15 22:28:45 ccu3-webui user.err rfd: () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
Oct 15 22:28:45 ccu3-webui user.err rfd: No BidCoS-Interface available
Oct 15 22:28:52 ccu3-webui daemon.info ntpd[207]: Listen normally on 5 eth0 [2a02:908:1988:6a0:98c6:96ff:fe91:4a94]:123
Oct 15 22:29:00 ccu3-webui user.info kernel: [   88.113176] eq3loop: eq3loop_open_slave() mmd_hmip
Oct 15 22:33:46 ccu3-webui local0.err ReGaHss: Error: IseDOM::LoadOM: original file not exists, so try load new file. [iseDOM.cpp:2609]
Oct 15 22:33:46 ccu3-webui local0.err ReGaHss: Error: IseDOM::LoadOM: new file not exists, so try load bak file. [iseDOM.cpp:2621]
Oct 15 22:33:46 ccu3-webui local0.err ReGaHss: Error: IsePersist::LoadFromFile-> failed open file= /etc/config/homematic.regadom.bak [iseDOMpersist.cpp:78]
Oct 15 22:33:46 ccu3-webui local0.err ReGaHss: Error: IseObjectMap::Insert(202) failed! Already in map! [iseDOMobj.cpp:462]
Oct 15 22:33:46 ccu3-webui local0.err ReGaHss: Error: IseAddFavorite failed! ID=202 [iseDOM.cpp:644]
Oct 15 22:33:46 ccu3-webui local0.err ReGaHss: Error: IseObjectMap::Insert(203) failed! Already in map! [iseDOMobj.cpp:462]
Oct 15 22:33:46 ccu3-webui local0.err ReGaHss: Error: IseAddFavorite failed! ID=203 [iseDOM.cpp:644]
Oct 15 22:33:46 ccu3-webui local0.err ReGaHss: Error: IseObjectMap::Insert(204) failed! Already in map! [iseDOMobj.cpp:462]
Oct 15 22:33:46 ccu3-webui local0.err ReGaHss: Error: IseAddFavorite failed! ID=204 [iseDOM.cpp:644]
Oct 15 22:33:49 ccu3-webui user.info homematic: meine-homematic.de Versions - Upgrade auf 1.503
Oct 15 22:33:49 ccu3-webui user.info homematic: meine-homematic.de VPN Dienst und Autoupdate DEAKTIVIERT
Oct 15 22:33:53 ccu3-webui local0.err ReGaHss: Error: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [iseXmlRpc.h:281]
Oct 15 22:33:53 ccu3-webui local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute failed; method =init Params = {"xmlrpc_bin://127.0.0.1:1999","1007"} result= nil [iseXmlRpc.cpp:2599]
Oct 15 22:33:53 ccu3-webui local0.err ReGaHss: Error: IseXmlRpc::CallInit: CallXmlrpcMethod failed [iseXmlRpc.cpp:1204]
Oct 15 22:33:53 ccu3-webui local0.err ReGaHss: Error: XmlRpcClientThread::ThreadFunction(): failed call init for interface=VirtualDevices [iseRTHss.cpp:163]
Oct 15 22:35:07 ccu3-webui user.info kernel: [  454.744773] eq3loop: eq3loop_open_slave() mmd_hmip
Oct 15 22:35:39 ccu3-webui user.crit kernel: [  486.714518] Under-voltage detected! (0x00050005)
Oct 15 22:42:41 ccu3-webui user.warn kernel: [  908.956450] rpi_firmware_get_throttled: 5 callbacks suppressed
Oct 15 22:42:43 ccu3-webui user.warn kernel: [  911.036506] rpi_firmware_get_throttled: 5 callbacks suppressed
Oct 15 22:44:54 ccu3-webui user.crit kernel: [ 1042.076229] Under-voltage detected! (0x00050005)
Oct 15 22:46:42 ccu3-webui user.info kernel: [ 1150.236963] Voltage normalised (0x00000000)
Oct 15 22:46:44 ccu3-webui user.crit kernel: [ 1152.317021] Under-voltage detected! (0x00050005)
Oct 15 22:51:52 ccu3-webui user.info kernel: [ 1460.158096] Voltage normalised (0x00000000)
Oct 15 22:51:54 ccu3-webui user.crit kernel: [ 1462.238162] Under-voltage detected! (0x00050005)
Oct 15 22:52:02 ccu3-webui user.info kernel: [ 1470.558113] Voltage normalised (0x00000000)
Oct 16 02:17:02 ccu3-webui user.warn kernel: [13769.661547] rpi_firmware_get_throttled: 2 callbacks suppressed
Oct 16 02:17:02 ccu3-webui user.crit kernel: [13769.661553] Under-voltage detected! (0x00050005)
Oct 16 02:17:08 ccu3-webui user.warn kernel: [13775.901521] rpi_firmware_get_throttled: 2 callbacks suppressed
Oct 16 02:17:08 ccu3-webui user.info kernel: [13775.901524] Voltage normalised (0x00000000)
Oct 16 02:17:12 ccu3-webui user.crit kernel: [13780.061589] Under-voltage detected! (0x00050005)
Oct 16 03:17:02 ccu3-webui user.crit kernel: [17370.160587] Under-voltage detected! (0x00050005)
Oct 16 03:17:06 ccu3-webui user.info kernel: [17374.320181] Voltage normalised (0x00000000)
Oct 16 04:17:02 ccu3-webui user.crit kernel: [20970.657171] Under-voltage detected! (0x00050005)
Oct 16 05:17:03 ccu3-webui user.crit kernel: [24571.154760] Under-voltage detected! (0x00050005)
`

**Comment by alexreinert** [comment]
Which RF hardware are  you using?
The output of pivccu-info indicates, that you have no RF hardware connected to the Pi.

**Comment by passuff** [comment]
I'm waiting to finish the restore to connect it. its currently connected to the piVCCU2 raspi.

**Comment by alexreinert** [comment]
This explains your issue: The CCU3 firmware has some validations on the restore, which require a RF module. I do not really know, what this validation do exactly, as they are inside the closed source of eQ-3.

**Comment by passuff** [comment]
OK, I think it was different for the CCU2 firmware as this is my usual (failsafe) update procedure. Anyway I will try again with the hardware connected.

**Comment by alexreinert** [comment]
Any news?

**Comment by alexreinert** [comment]
Please reopen, if there are still issues with connected hardware.

**Comment by passuff** [comment]
Sorry for the late feedback. After installing the RF Module everything worked fine.
