### ISSUE TITLE
Support for RockPro64

### ISSUE THREAD

**Issue by alexreinert** [alexreinert/piVCCU#83]
Test devices needed

**Comment by Pocky2507** [comment]
Ich würde mir jetzt einen Bestellen und ihn Dir dann zum testen zusenden.
Was hältst Du davon?

**Comment by alexreinert** [comment]
Können wir so machen, meldest du dich vielleicht direkt bei mir für die Einzelheiten (alex@areinert.de)

**Comment by alexreinert** [comment]
Hopefully Pine64 will send me a RockPro64 dev package in the near future.

**Comment by alexreinert** [comment]
Testdevice arrived today, so I hope to get some progress, soon.

**Comment by alexreinert** [comment]
Support added. (Experimental for the time beeing).
Right now it needs to be installed manually, Image creation will be done together with image recreation of 3.43.15 version.
