### ISSUE TITLE
Question: List of all available device channels

### ISSUE THREAD

**Issue by steilerDev** [alexreinert/piVCCU#87]
Hi Alex,

first of all: Love the great work you put into that project, realizing my first smart home here :)

I have got a general question about the integration between the CCU and OpenHab (since you mentioned that in your talk at the user forum I thought maybe you can point me in the right direction here, being a CCU expert, otherwise just close the issue ;) ). 

I have some devices (currently looking at the weather station in particular) that are exposing information to the CCU, which are not discovered in the PaperUI of OpenHab (It is only showing me the Humidity part, but not all the other metrics available). I was wondering if you are aware of any documentation, where all available metrics/channels are listed, or if there is a possibility to display them either through the CCU webinterface or your pivCCU CLI. Through trial-and-error I was able to put together some others but still missing a few. That tells me that there is no support and just a discovery issue.

(Only the first channel shows up in the PaperUI)

```
Number AB_S_Wetter_Humidity "Außenluftfeuchtigkeit" (AB_Klima) {channel="homematic:HmIP-SWO-PL:OEQ0610217:00181709ADB464:1#HUMIDITY"}
Number AB_S_Wetter_Illumination "Außenhelligkeit" (AB_Klima) {channel="homematic:HmIP-SWO-PL:OEQ0610217:00181709ADB464:1#ILLUMINATION"}
Contact AB_S_Wetter_Raining "Regenfall" (AB_Klima) {channel="homematic:HmIP-SWO-PL:OEQ0610217:00181709ADB464:1#RAINING"}
Number AB_S_Wetter_Raincounter "Regenmenge" (AB_Klima) {channel="homematic:HmIP-SWO-PL:OEQ0610217:00181709ADB464:1#RAIN_COUNTER"}
Number AB_S_Wetter_SunshineDuration "Sonnendauer" (AB_Klima) {channel="homematic:HmIP-SWO-PL:OEQ0610217:00181709ADB464:1#SUNSHINEDURATION"}
Number AB_S_Wetter_WindSpeed "Windgeschwindigkeit" (AB_Klima) {channel="homematic:HmIP-SWO-PL:OEQ0610217:00181709ADB464:1#WIND_SPEED"}
```

Hope you can give me a tip here.

Thanks again and all the best!

**Comment by alexreinert** [comment]
Maybe the official documentation of eQ-3 helps:

https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM-Script_4-Datenpunkte.pdf
https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf

And you could use the the devconfig inside the CCU WebUI:
https://homematic.simdorn.net/verstecktes-config-tool/

(Parts of the links are german speaking, but reading your thing descriptions, I assume this is no problem for you.

**Comment by steilerDev** [comment]
Yes, the hidden devconfig is exactly what I am looking for. It shows me all channels and metrics. Not pretty but very functional. Thanks so much!
