### ISSUE TITLE
Support for OSMC running rpi

### ISSUE THREAD

**Issue by efefef** [alexreinert/piVCCU#89]
Hello Alex.

I am running the (popular) media-centre-image Kodi (aka osmc) on my RPI 3b.

osmc@osmc:~$ cat /proc/version
Linux version 4.14.34-6-osmc (root@vero3-db) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)) #1 SMP PREEMPT Thu Sep 6 00:47:56 UTC 2018

On this RPI also already runs the software openhab (and this works so far with a real CCU2 together).

Now when I try to install pivCCU, I follow your "manual Raspberry" Link.

But at Step 3 ("sudo apt install pivccu-modules-raspberrypi") i geht following error:
The following packages have unmet dependencies:

 pivccu-modules-raspberrypi : Depends: raspberrypi-kernel-headers but it is not installable
E: Unable to correct problems, you have held broken packages.

" sudo apt-get install raspberrypi-kernel-headers" brings then the error:
E: Package 'raspberrypi-kernel-headers' has no installation candidate

So maybe you know a solution for me. Or how i can instal the missing packages?

Thank you very much!

BR
Edi

![2018-10-30_19h02_44](https://user-images.githubusercontent.com/35331895/47746872-57691400-dc87-11e8-8527-b4fff755a087.jpg)

![2018-10-30_21h04_55](https://user-images.githubusercontent.com/35331895/47746924-79629680-dc87-11e8-8f30-73e2b291dacb.jpg)

**Comment by alexreinert** [comment]
The Raspberry version of piVCCU depends on Raspbian Stretch. As far as I understand, OSMC is Debian based but not Raspbian based.
Netherless: You do not want to install Kodi, Openhab and piVCCU on a single Raspberry Pi, this will not fit inside 1GB RAM.
