### ISSUE TITLE
Fake radio module driver

### ISSUE THREAD

**Issue by alexreinert** [alexreinert/piVCCU#9]
Add a fake radio module driver to emulate the radio module to use piVCCU just with HM-LAN-GW.

**Comment by leonsio** [comment]
Solltest darüber genau nachdenken. Es wird so ohne weiteres funktionieren Bzw. Ist begrenzt nutzbar. 
LAN Gateway unterstützt kein Homematic IP. Führt Ggf nur zur Verwirrung. 

Von meinem iPhone gesendet

**Comment by alexreinert** [comment]
Geht ja auch nicht drum, dass der Treiber das LAN GW nutzt, sondern der Treiber emuliert das Funkmodul im Strahlenkäfig. (Also Protokoll wird verstanden, Sendebefehle als gesendet quitiert, aber nie etwas empfangen). Und innerhalb der CCU kann dann ein LAN GW angemeldet werden.

**Comment by leonsio** [comment]
Ja aber das führt bei vielen zu Problemen. 
Es wird von vielen angenommen  dass Homematic IP ebenfalls funktioniert. Du müsstest es dann riesengroß in h1 überall hinschreiben. :)

Leider weist eq3 niergends drauf explizit hin. 

Von meinem iPhone gesendet

**Comment by alexreinert** [comment]
Released in testing

**Comment by alexreinert** [comment]
Released in stable
