### ISSUE TITLE
Einstellung - Gewerke, Räume, Programme und Verknüpfungen "not found"

### ISSUE THREAD

**Issue by maloross** [alexreinert/piVCCU#90]
Unter den Einstellungen lassen sich folgende Punkte weder anzeigen noch hinzufügen:

- Gewerke
- Räume
- Programme und Verknüpfungen

Alle noch auf der Original-CCU2 angelegten sind vorhanden und können auch Geräten zugeordnet werden. Leider sind meine Programm (Sonnenstand, Feiertage usw.) futsch.

**Comment by alexreinert** [comment]
Mit der Fehlerbeschreibung kann man leider reichlich wenig anfangen.

Zwischen den Zeilen lese ich, dass du eine Migration von einer Original CCU2 durchgeführt hast, ist das korrekt?
Bitte einmal den Befehl ``sudo pivccu-info`` ausführen und die Ausgabe hier posten, dann kann man schonmal sehen, welche Version du installiert hast, ob und welches Funkmodul erkannt wurde, etc.
Und dann bitte einmal das Vorgehen beschreiben, welches zu dem Fehler geführt hat.

**Comment by maloross** [comment]
ja Migration im letzten Jahr gemacht, hatte bisher auch keine Fehler. Auch das Hinzufügen neuer Geräte unproblematisch.
Der Fehler tritt auf, wenn ich über das Web-UI den jeweiligen Button betätige; dann erscheint der Hinweis dort, wo normalerweise die Liste der Geräte, Programme usw. zu sehen ist.  Alles andere kann funktioniert.
Kleine Korrektur: die von mir erstellten Programme sind noch da, kann sie unter "Status und Bedienung" aktivieren oder abschalten.

Hier die Ausgabe der Info:

> pi@raspberrypi:~ $ sudo pivccu-info
> piVCCU version: 2.35.16-35
> Kernel modules: Available
> Raw UART dev:   Available
> Rasp.Pi3 UART:  Assigned to GPIO pins
> HMRF Hardware:  HM-MOD-RPI-PCB
> HMIP Hardware:  HM-MOD-RPI-PCB
> Board serial:   OEQ0610401
> Radio MAC:      0x59e575
> SGTIN:          3014F711A061A7D70992B861
> State:          RUNNING
> PID:            22507
> CPU use:        92.06 seconds
> BlkIO use:      7.77 MiB
> Link:           veth60AH75
>  TX bytes:      13.33 MiB
>  RX bytes:      5.80 MiB
>  Total bytes:   19.13 MiB

**Comment by alexreinert** [comment]
Ich stehe auf dem Schlauch:
Seit wann hast du den Fehler? Ist der neu, ist das schon immer so seit der Migration?
Was für ein Hinweis erscheint?

**Comment by maloross** [comment]
Gute Frage,.. Was ich sagen kann: ich hatte anfangs ein Gewerk hinzugefügt, da funktionierte es. Hier mal als visuelle Unterstützung ein [Bild](https://photos.app.goo.gl/wyHb7WFy8ppbcMUa8)
Ich habe den Button "Programme und Verknüpfungen" betätigt und es erscheint die Ansicht im Bild oben
Danach den Button "Programme und Zentralverknüpfungen" angeklickt und ich bekomme die Ansicht im Bild unten

**Comment by real-easy** [comment]
nur mal auf die schnelle eine idee... 
schon mal den browser cache gelöscht ? (sollte man nach jedem ccu update machen) 

zum test kannst du auch mal einen anderen browser testen, den du normalerweise nicht nimmst. 

oder ein inkognito tag öffnen 




Von: "maloross" <notifications@github.com> 
An: "alexreinert/piVCCU" <piVCCU@noreply.github.com> 
CC: "Subscribed" <subscribed@noreply.github.com> 
Gesendet: Mittwoch, 31. Oktober 2018 22:00:11 
Betreff: Re: [alexreinert/piVCCU] Einstellung - Gewerke, Räume, Programme und Verknüpfungen "not found" (#90) 



Gute Frage,.. Was ich sagen kann: ich hatte anfangs ein Gewerk hinzugefügt, da funktionierte es. Hier mal als visuelle Unterstützung ein [ https://photos.app.goo.gl/wyHb7WFy8ppbcMUa8 | Bild ] 
Ich habe den Button "Programme und Verknüpfungen" betätigt und es erscheint die Ansicht im Bild oben 
Danach den Button "Programme und Zentralverknüpfungen" angeklickt und ich bekomme die Ansicht im Bild unten

**Comment by maloross** [comment]
ja, alles schon gemacht, inklusive reboot.

**Comment by maloross** [comment]
Anscheinend ist beim letzten Update etwas falsch gelaufen, hatte einige Fehlermeldungen bei update&upgrade. Nach Neuinstallation läuft alles sauber.
