### ISSUE TITLE
Probleme während Update nach backup abfrage

### ISSUE THREAD

**Issue by Semesch** [alexreinert/piVCCU#92]
Wenn ich update/upgrade machen möchte kommt die abfrage ob ein Backup vorhanden ist.
Dies wird mit ja beantwortet. danach reagiert nix mehr.

DKMS: uninstall completed.

------------------------------
Deleting module version: 1.0.10
completely from the DKMS tree.
------------------------------
Done.
Entpacken von pivccu-modules-dkms (1.0.13) über (1.0.10) ...
debconf: kann Oberfläche nicht initialisieren: Dialog
debconf: (Die Dialog-Oberfläche funktioniert nicht auf einem Dumb-Terminal, einem Emacs-Shellbuffer oder ohne ein steuerndes Terminal.)
debconf: greife zurück auf die Oberfläche: Readline
perl-modules-5.24 (5.24.1-3+deb9u4) wird eingerichtet ...
libperl5.24:armhf (5.24.1-3+deb9u4) wird eingerichtet ...
perl (5.24.1-3+deb9u4) wird eingerichtet ...
libprocps6:armhf (2:3.3.12-3+deb9u1) wird eingerichtet ...
procps (2:3.3.12-3+deb9u1) wird eingerichtet ...
systemd (232-25+deb9u4) wird eingerichtet ...
addgroup:
Die Gruppe »systemd-journal« existiert bereits als Systemgruppe. Programmende.
(Lese Datenbank ...
(Lese Datenbank ... 5% (Lese Datenbank ... 10%
(Lese Datenbank ... 15% (Lese Datenbank ... 20% (Lese Datenbank ... 25% (Lese Datenbank ... 30% (Lese Datenbank ... 35% (Lese Datenbank ... 40% (Lese Datenbank ... 45% (Lese Datenbank ... 50% (Lese Datenbank ... 55% (Lese Datenbank ... 60%
(Lese Datenbank ... 65%
(Lese Datenbank ... 70%
(Lese Datenbank ... 75%
(Lese Datenbank ... 80%
(Lese Datenbank ... 85%
(Lese Datenbank ... 90%
(Lese Datenbank ... 95%
(Lese Datenbank ... 100% (Lese Datenbank ...
77751 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../0-pivccu_2.35.16-38_all.deb ...
Removed /etc/systemd/system/multi-user.target.wants/pivccu.service.
debconf: kann Oberfläche nicht initialisieren: Dialog
debconf: (Die Dialog-Oberfläche funktioniert nicht auf einem Dumb-Terminal, einem Emacs-Shellbuffer oder ohne ein steuerndes Terminal.)
debconf: greife zurück auf die Oberfläche: Readline
Konfiguriere pivccu
-------------------

A new CCU firmware version is to be installed.

It is recommended that you create a backup before installing a new CCU firmware 
version.

Do you have a backup?

[ja/nein]
 ja

**Comment by alexreinert** [comment]
Nach der Abfrage wird das Deb Paket entpackt. Je nach Geschwindigkeit der SD Karte kann das durchaus ein paar Minuten dauern, in welchen gefühlt nichts passiert.

**Comment by Semesch** [comment]
ich kann jetzt im Terminal wieder etwas tippen aber auch nach 20 Minuten tut sich nichts mehr.

**Comment by alexreinert** [comment]
Mit welchem Programm bist du auf dem Pi eingeloggt? Das Dialog nicht funktioniert ist schon etwas komisch. Ich will nicht ausschließen, dass da noch irgendeine Meldung angezeigt wird, welche du aber ohne dialog nicht sehen kannst.

Ansonsten kann ich an der Stelle recht wenig beeinflussen, das ist der in Debian eingebaute Installer.

**Comment by Semesch** [comment]
ich bin Opera auf dem iobroker übers webterminal eingeloggt, da ich über putty immer die fehlermeldung "Access Denied" bekomme

**Comment by alexreinert** [comment]
Bitte mit putty probieren, wenn Access Denied kommt, dann musst du halt klären, wie der richtige Benutzer/Passwort ist, je nachdem woher das Image kam.

**Comment by Semesch** [comment]
alles klar. trotzdem vielen dank
