### ISSUE TITLE
OpenWRT support

### ISSUE THREAD

**Issue by renne** [alexreinert/piVCCU#94]
@alexreinert 
I'm using a [TurrisOmnia](https://omnia.turris.cz/en/) router (ARMv7, 2 GByte RAM). It has a spare [UART and GPIOs](https://doc.turris.cz/doc/_media/omnia-pinout.png) to connect HM-MOD-RPI-PCB. The OS is OpenWRT 15.05, 18.06 is in the works. It ships with [LXC support](https://doc.turris.cz/doc/en/howto/lxc).

Please support [OPKG package manager](https://en.wikipedia.org/wiki/Opkg) for OpenWRT.

**Comment by alexreinert** [comment]
No chance without a test device and this device is way to expansive for me without knowing if this could work at all. For example I did not find any information about the used UART chip, nor the ability to add custom device tree overlays.

**Comment by alexreinert** [comment]
Yes, you miss something. Even if the CCU firmware is loaded inside a LXC container, it is neccessary to load custom kernel modules on the host for the communication with the radio module using the direct hardware registers of the UART chip. A communication using the TTY devices of the UART is not possible in the current CCU architecture.
