### ISSUE TITLE
Question: How to debug

### ISSUE THREAD

**Issue by nobodyman1** [alexreinert/piVCCU#95]
I tried different hardware platforms to get piVCCU working. But no success until now.
I flashed [Armbian_5.67_Orangepizero_Stretch_next_piVCCU3_2018-11-18.zip](https://www.pivccu.de/images/piVCCU3/Armbian_5.67_Orangepizero_Stretch_next_piVCCU3_2018-11-18.zip) on a micro sd card and bootet the image. Everything looked nice. The webinterface was working and I didn´t see any problem.
But if I wanted to connect a new device nothing happened.

Things I tried:
- `pivccu-info` returned `Board serial`, `Radio MAC`, `SGTIN` and so on.
- I found some debug output:
  - `pivccu-attach cat /var/log/messages`
  - `pivccu-attach cat /var/log/hmserver.log`
- and some configration: `pivccu-attach cat /var/hm_mode`

1. How do I get some useful debug information? What kind of information has to be visible if the pairing happens?

**Comment by nobodyman1** [comment]
I tried different things:
- One thermostat (MAX! Radiator Thermostat basic) was paired with my homegear installation. I unpaired it and found in the log
`MAX packet received (My-MAX-CUL, RSSI: 0x2C): xxx`
`Module MAX: Removed peer 1`. I think this looks ok.
After that I set the thermostat to factory defaults.
Pairing with piVCCU is not successful! But I´m still able to pair it with homegear!
- I tried a new device which was never paired before. I doesn´t work too.
The antenna of the module is not modified and the distance is only about 1m.

Could you please attach some debug output which shows the pairing process?

**Comment by alexreinert** [comment]
It is not possible to pair MAX and Homematic. (And this is not related to piVCCU, it is not possible on every CCU solution)

**Comment by nobodyman1** [comment]
Ups. Sorry, I didn´t know that.
To complete the issue, I found following description: [Sind die von eQ-3 hergestellten Systeme untereinander kompatibel?](https://www.eq-3.de/service/faq.html?id=144)
