### ISSUE TITLE
Fehler oder nur nervig?

### ISSUE THREAD

**Issue by mdk2412** [alexreinert/piVCCU#97]
Hallo,

ich habe von pivccu(2) auf pivccu3 aktualisiert, was für sich reibungslos ging. Jetzt frage ich mich allerdings, ob dieser "Sicherheitshinweis" beim Start jetzt jedes Mal kommt? Ich habe es schon x-mal bestätigt, mit User mit und ohne Admin-Status versucht, Neustart vom Raspberry3, vergeblich: es kommt jedes Mal erneut! Gibt es eine Möglichkeit, das dauerhaft zu unterbinden, oder ist das ein "Feature" der CCU3?

Mit freundlichen Grüßen

**Comment by alexreinert** [comment]
Hi,

bitte einen Screenshot, es gibt da mehrere mögliche Dialoge, wobei die eigentlich alle nur einmal angezeigt werden.

**Comment by mdk2412** [comment]
Hallo,

ich musste (WAF...) das Backup auf CCU2-Stand zurückspielen, daher momentan kein Screenshot. Es war aber die folgende Meldung (die ich gefühlt mind. ein dutzend Mal weggeklickt habe):
![hinweis](https://user-images.githubusercontent.com/23579032/49332177-6a357800-f5a8-11e8-9f9d-35fd397fc2b1.jpg)

Und ich entnehme dem, dass das nicht normal ist (beruhigend!). Dann wäre die Frage, wo man in der Konfiguration zur Not manuell die Meldung auf "gelesen" setzen kann.

**Comment by alexreinert** [comment]
Das Abhaken dieser Meldung sollte normalerweise eine (leere) Datei /etc/config/userAckSecurityHint (im Container, bzw. /var/lib/piVCCU3/userfs/etc/config/userAckSecurityHint im Host) anlegen.
Bei jedem Einspielen eines Backups bzw. beim Werksreset wird diese Datei gelöscht. Wenn die aber generell nicht angelegt werden kann, dann klingt das erstmal nach einem größeren Problem, weil dann die Frage ist, ob er andere Dateien ebenfalls nicht anlegen bzw. aktualisieren kann wie z.B. dann auch die RegaDOM, in welcher alle EInstellungen und Programme drin stehen. Ein solches Problem ist mir bisher aber noch nie untergekommen, sofern da nicht die SD Karte Hardware mäßig einen Schlag hatte.

**Comment by alexreinert** [comment]
Irgendwelche neuen Erkenntnisse? Sonst würde ich hier zumachen.

**Comment by mdk2412** [comment]
Ich werde versuchen, es gleich noch zu testen (ist immer etwas lästig mit Vollbackup hin- und herspielen), dann kann ich mehr sagen. Bin bisher nicht dazu gekommen.

**Comment by mdk2412** [comment]
So, habe jetzt nochmals upgedatet. Bestätigungs-Datei wurde nach dem erstmaligen Abhaken angelegt. Dann mein Backup der CCU2 eingespielt. Jetzt wurde die Datei nicht mehr angelegt... habe ich dann händisch getan. Scheint bisher zu funktionieren.
Es liegt also scheinbar an meinem Backup. Naja vorerst ist mein Problem damit gelöst, auch wenn nicht klar ist, warum es auftrat.
