### ISSUE TITLE
Slightly shorter main interface detection

### ISSUE THREAD

**Issue by moranaga** [alexreinert/piVCCU#98]
The statements in 640eb6f might be reduced as follows:

```
route | grep 'default' | awk '{print $5" "$8}' | sort | awk '{print $2}' | uniq | head -n 1

route | awk '/default/{a[$8]+=1}END{for(v in a)print v}' | sed 1q
```
I am no awk wizard and on a single interface SBC, though.

**Comment by alexreinert** [comment]
Thanks for the idea.

But the sort (by metric and name) is missing. So this would work on a SBC with a single interface, but not on a SBC with two interfaces.
